%TEST_PPSUBJECTCON_FUN_MP_CON_FUN_MP

%% Test 1.1: Instantiation - empty

pr = PPSubjectCON_FUN_MP_CON_FUN_MP();

prop_number = PPSubjectCON_FUN_MP_CON_FUN_MP.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(PPSubjectCON_FUN_MP_CON_FUN_MP.getPropTag(prop));
	assert( ...
		isa(pr.getr(prop), 'NoValue'), ...
		[BRAPH2.STR ':PPSubjectCON_FUN_MP_CON_FUN_MP:' BRAPH2.BUG_FUNC], ...
		['PPSubjectCON_FUN_MP_CON_FUN_MP.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
		'Or there could be an error in PPSubjectCON_FUN_MP_CON_FUN_MP.getr(' int2str(prop) ').'] ...
		)
	assert( ...
		isa(pr.getr(TAG), 'NoValue'), ...
		[BRAPH2.STR ':PPSubjectCON_FUN_MP_CON_FUN_MP:' BRAPH2.BUG_FUNC], ...
		['PPSubjectCON_FUN_MP_CON_FUN_MP.getr(''' TAG ''') must be inizialized to NoValue(). ' ...
		'Or there could be an error in PPSubjectCON_FUN_MP_CON_FUN_MP.getr(''' TAG ''').'] ...
		)
end

%% Test 1.2: Instantiation - defaults

warning('off', 'BRAPH2:PPSubjectCON_FUN_MP_CON_FUN_MP')
pr = PPSubjectCON_FUN_MP_CON_FUN_MP( ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.ID, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.ID), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.BKGCOLOR, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.BKGCOLOR), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.EL, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.EL), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.PROP, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.PROP), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.TITLE, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.TITLE), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.ENABLE, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.ENABLE), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.WAITBAR, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.WAITBAR) ...
	);
warning('on', 'BRAPH2:PPSubjectCON_FUN_MP_CON_FUN_MP')

for prop = 1:1:PPSubjectCON_FUN_MP_CON_FUN_MP.getPropNumber()
	TAG = upper(PPSubjectCON_FUN_MP_CON_FUN_MP.getPropTag(prop));
	switch PPSubjectCON_FUN_MP_CON_FUN_MP.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isequal(pr.getr(prop), PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefaultConditioned(prop)), ...
				[BRAPH2.STR ':PPSubjectCON_FUN_MP_CON_FUN_MP:' BRAPH2.BUG_FUNC], ...
				['PPSubjectCON_FUN_MP_CON_FUN_MP.getr(' int2str(prop) ') must be inizialized to its default value ' ...
				'given by PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefaultConditioned(' int2str(prop) '). ' ...
				'Or there could be an error in PPSubjectCON_FUN_MP_CON_FUN_MP.getr(' int2str(prop) ').'] ...
				)
			assert( ...
				isequal(pr.getr(TAG), PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefaultConditioned(prop)), ...
				[BRAPH2.STR ':PPSubjectCON_FUN_MP_CON_FUN_MP:' BRAPH2.BUG_FUNC], ...
				['PPSubjectCON_FUN_MP_CON_FUN_MP.getr(''' TAG ''') must be inizialized to its default value ' ...
				'given by PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefaultConditioned(' int2str(prop) '). ' ...
				'Or there could be an error in PPSubjectCON_FUN_MP_CON_FUN_MP.getr(''' TAG ''').'] ...
				)
		case Category.RESULT
			assert( ...
				isa(pr.getr(prop), 'NoValue'), ...
				[BRAPH2.STR ':PPSubjectCON_FUN_MP_CON_FUN_MP:' BRAPH2.BUG_FUNC], ...
				['Being a result, PPSubjectCON_FUN_MP_CON_FUN_MP.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
				'Or there could be an error in PPSubjectCON_FUN_MP_CON_FUN_MP.getr(' int2str(prop) ').'] ...
				)
			assert( ...
				isa(pr.getr(TAG), 'NoValue'), ...
				[BRAPH2.STR ':PPSubjectCON_FUN_MP_CON_FUN_MP:' BRAPH2.BUG_FUNC], ...
				['Being a result, PPSubjectCON_FUN_MP_CON_FUN_MP.getr(''' TAG ''') must be inizialized to NoValue(). ' ...
				'Or there could be an error in PPSubjectCON_FUN_MP_CON_FUN_MP.getr(''' TAG ''').'] ...
				)
	end
end

%% Test 2: Callbacks

warning('off', 'BRAPH2:PPSubjectCON_FUN_MP_CON_FUN_MP')
pr_0 = PPSubjectCON_FUN_MP_CON_FUN_MP( ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.ID, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.ID), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.BKGCOLOR, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.BKGCOLOR), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.EL, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.EL), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.PROP, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.PROP), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.TITLE, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.TITLE), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.ENABLE, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.ENABLE), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.WAITBAR, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.WAITBAR) ...
	);
warning('on', 'BRAPH2:PPSubjectCON_FUN_MP_CON_FUN_MP')

pr_1 = PPSubjectCON_FUN_MP_CON_FUN_MP( ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.ID, Callback('EL', pr_0, 'PROP', 1), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.BKGCOLOR, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.BKGCOLOR), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.EL, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.EL), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.PROP, Callback('EL', pr_0, 'PROP', 4), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.TITLE, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.TITLE), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.ENABLE, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.ENABLE), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.WAITBAR, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.WAITBAR) ...
	);
	
prop_number = PPSubjectCON_FUN_MP_CON_FUN_MP.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(PPSubjectCON_FUN_MP_CON_FUN_MP.getPropTag(prop));
	switch PPSubjectCON_FUN_MP_CON_FUN_MP.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(pr_1.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':PPSubjectCON_FUN_MP_CON_FUN_MP:' BRAPH2.BUG_FUNC], ...
				['PPSubjectCON_FUN_MP_CON_FUN_MP.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(pr_1.get(prop), pr_0.get(prop)) && ~isa(pr_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':PPSubjectCON_FUN_MP_CON_FUN_MP:' BRAPH2.BUG_FUNC], ...
				['PPSubjectCON_FUN_MP_CON_FUN_MP.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(pr_1.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':PPSubjectCON_FUN_MP_CON_FUN_MP:' BRAPH2.BUG_FUNC], ...
				['PPSubjectCON_FUN_MP_CON_FUN_MP.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end
pr_2 = PPSubjectCON_FUN_MP_CON_FUN_MP( ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.ID, Callback('EL', pr_1, 'PROP', 1), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.BKGCOLOR, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.BKGCOLOR), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.EL, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.EL), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.PROP, Callback('EL', pr_1, 'PROP', 4), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.TITLE, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.TITLE), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.ENABLE, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.ENABLE), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.WAITBAR, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.WAITBAR) ...
	);
	
prop_number = PPSubjectCON_FUN_MP_CON_FUN_MP.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(PPSubjectCON_FUN_MP_CON_FUN_MP.getPropTag(prop));
	switch PPSubjectCON_FUN_MP_CON_FUN_MP.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(pr_2.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':PPSubjectCON_FUN_MP_CON_FUN_MP:' BRAPH2.BUG_FUNC], ...
				['PPSubjectCON_FUN_MP_CON_FUN_MP.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(pr_2.get(prop), pr_0.get(prop)) && ~isa(pr_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':PPSubjectCON_FUN_MP_CON_FUN_MP:' BRAPH2.BUG_FUNC], ...
				['PPSubjectCON_FUN_MP_CON_FUN_MP.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(pr_2.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':PPSubjectCON_FUN_MP_CON_FUN_MP:' BRAPH2.BUG_FUNC], ...
				['PPSubjectCON_FUN_MP_CON_FUN_MP.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end
pr_3 = PPSubjectCON_FUN_MP_CON_FUN_MP( ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.ID, Callback('EL', pr_2, 'PROP', 1), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.BKGCOLOR, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.BKGCOLOR), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.EL, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.EL), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.PROP, Callback('EL', pr_2, 'PROP', 4), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.TITLE, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.TITLE), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.ENABLE, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.ENABLE), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.WAITBAR, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.WAITBAR) ...
	);
	
prop_number = PPSubjectCON_FUN_MP_CON_FUN_MP.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(PPSubjectCON_FUN_MP_CON_FUN_MP.getPropTag(prop));
	switch PPSubjectCON_FUN_MP_CON_FUN_MP.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(pr_3.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':PPSubjectCON_FUN_MP_CON_FUN_MP:' BRAPH2.BUG_FUNC], ...
				['PPSubjectCON_FUN_MP_CON_FUN_MP.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(pr_3.get(prop), pr_0.get(prop)) && ~isa(pr_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':PPSubjectCON_FUN_MP_CON_FUN_MP:' BRAPH2.BUG_FUNC], ...
				['PPSubjectCON_FUN_MP_CON_FUN_MP.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(pr_3.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':PPSubjectCON_FUN_MP_CON_FUN_MP:' BRAPH2.BUG_FUNC], ...
				['PPSubjectCON_FUN_MP_CON_FUN_MP.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end

%% Test 3: Result

warning('off', 'BRAPH2:PPSubjectCON_FUN_MP_CON_FUN_MP')
pr = PPSubjectCON_FUN_MP_CON_FUN_MP( ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.ID, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.ID), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.BKGCOLOR, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.BKGCOLOR), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.EL, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.EL), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.PROP, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.PROP), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.TITLE, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.TITLE), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.ENABLE, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.ENABLE), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.WAITBAR, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.WAITBAR) ...
	);
warning('on', 'BRAPH2:PPSubjectCON_FUN_MP_CON_FUN_MP')

prop_number = PPSubjectCON_FUN_MP_CON_FUN_MP.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(PPSubjectCON_FUN_MP_CON_FUN_MP.getPropTag(prop));
	switch PPSubjectCON_FUN_MP_CON_FUN_MP.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
		case Category.RESULT
			assert( ...
				~isa(pr.get(prop),  'NoValue'), ...
				[BRAPH2.STR ':PPSubjectCON_FUN_MP_CON_FUN_MP:' BRAPH2.BUG_FUNC], ...
				['PPSubjectCON_FUN_MP_CON_FUN_MP.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				isa(pr.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':PPSubjectCON_FUN_MP_CON_FUN_MP:' BRAPH2.BUG_FUNC], ...
				['PPSubjectCON_FUN_MP_CON_FUN_MP.getr(' int2str(prop) ') must be a NoValue, because it has not been memorized.'] ...
				)
			if isempty(pr.getPropSettings(prop))
				assert( ...
					pr.checkFormat(pr.getPropFormat(prop), pr.get(prop)), ...
					[BRAPH2.STR ':PPSubjectCON_FUN_MP_CON_FUN_MP:' BRAPH2.BUG_FUNC], ...
					['PPSubjectCON_FUN_MP_CON_FUN_MP.get(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			else
				assert( ...
					pr.checkFormat(pr.getPropFormat(prop), pr.get(prop), pr.getPropSettings(prop)), ...
					[BRAPH2.STR ':PPSubjectCON_FUN_MP_CON_FUN_MP:' BRAPH2.BUG_FUNC], ...
					['PPSubjectCON_FUN_MP_CON_FUN_MP.get(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			end
	end
end

%% Test 4: Memorize

warning('off', 'BRAPH2:PPSubjectCON_FUN_MP_CON_FUN_MP')
pr = PPSubjectCON_FUN_MP_CON_FUN_MP( ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.ID, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.ID), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.BKGCOLOR, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.BKGCOLOR), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.EL, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.EL), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.PROP, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.PROP), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.TITLE, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.TITLE), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.ENABLE, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.ENABLE), ...
	PPSubjectCON_FUN_MP_CON_FUN_MP.WAITBAR, PPSubjectCON_FUN_MP_CON_FUN_MP.getPropDefault(PPSubjectCON_FUN_MP_CON_FUN_MP.WAITBAR) ...
	);
warning('on', 'BRAPH2:PPSubjectCON_FUN_MP_CON_FUN_MP')

for prop = 1:1:PPSubjectCON_FUN_MP_CON_FUN_MP.getPropNumber()
	TAG = upper(PPSubjectCON_FUN_MP_CON_FUN_MP.getPropTag(prop));
	switch PPSubjectCON_FUN_MP_CON_FUN_MP.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
		case Category.RESULT
			assert( ...
				~isa(pr.get(prop),  'NoValue'), ...
				[BRAPH2.STR ':PPSubjectCON_FUN_MP_CON_FUN_MP:' BRAPH2.BUG_FUNC], ...
				['PPSubjectCON_FUN_MP_CON_FUN_MP.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				isa(pr.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':PPSubjectCON_FUN_MP_CON_FUN_MP:' BRAPH2.BUG_FUNC], ...
				['PPSubjectCON_FUN_MP_CON_FUN_MP.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
				)
			assert( ...
				~isa(pr.memorize(prop),  'NoValue'), ...
				[BRAPH2.STR ':PPSubjectCON_FUN_MP_CON_FUN_MP:' BRAPH2.BUG_FUNC], ...
				['PPSubjectCON_FUN_MP_CON_FUN_MP.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				~isa(pr.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':PPSubjectCON_FUN_MP_CON_FUN_MP:' BRAPH2.BUG_FUNC], ...
				['PPSubjectCON_FUN_MP_CON_FUN_MP.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
				)
			assert( ...
				pr.checkFormat(pr.getPropFormat(prop), pr.getr(prop),pr.getPropSettings(prop)), ...
				[BRAPH2.STR ':PPSubjectCON_FUN_MP_CON_FUN_MP:' BRAPH2.BUG_FUNC], ...
				['PPSubjectCON_FUN_MP_CON_FUN_MP.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
				)
	end
end

