%TEST_SUBJECTST

%% Test 1.1: Instantiation - empty

sub = SubjectST();

prop_number = SubjectST.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(SubjectST.getPropTag(prop));
	assert( ...
		isa(sub.getr(prop), 'NoValue'), ...
		[BRAPH2.STR ':SubjectST:' BRAPH2.BUG_FUNC], ...
		['SubjectST.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
		'Or there could be an error in SubjectST.getr(' int2str(prop) ').'] ...
		)
	assert( ...
		isa(sub.getr(TAG), 'NoValue'), ...
		[BRAPH2.STR ':SubjectST:' BRAPH2.BUG_FUNC], ...
		['SubjectST.getr(''' TAG ''') must be inizialized to NoValue(). ' ...
		'Or there could be an error in SubjectST.getr(''' TAG ''').'] ...
		)
end

%% Test 1.2: Instantiation - defaults

warning('off', 'BRAPH2:SubjectST')
sub = SubjectST( ...
	SubjectST.ID, SubjectST.getPropDefault(SubjectST.ID), ...
	SubjectST.LABEL, SubjectST.getPropDefault(SubjectST.LABEL), ...
	SubjectST.NOTES, SubjectST.getPropDefault(SubjectST.NOTES), ...
	SubjectST.BA, SubjectST.getPropDefault(SubjectST.BA), ...
	SubjectST.ST, SubjectST.getPropDefault(SubjectST.ST), ...
	SubjectST.AGE, SubjectST.getPropDefault(SubjectST.AGE), ...
	SubjectST.SEX, SubjectST.getPropDefault(SubjectST.SEX) ...
	);
warning('on', 'BRAPH2:SubjectST')

for prop = 1:1:SubjectST.getPropNumber()
	TAG = upper(SubjectST.getPropTag(prop));
	switch SubjectST.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isequal(sub.getr(prop), SubjectST.getPropDefaultConditioned(prop)), ...
				[BRAPH2.STR ':SubjectST:' BRAPH2.BUG_FUNC], ...
				['SubjectST.getr(' int2str(prop) ') must be inizialized to its default value ' ...
				'given by SubjectST.getPropDefaultConditioned(' int2str(prop) '). ' ...
				'Or there could be an error in SubjectST.getr(' int2str(prop) ').'] ...
				)
			assert( ...
				isequal(sub.getr(TAG), SubjectST.getPropDefaultConditioned(prop)), ...
				[BRAPH2.STR ':SubjectST:' BRAPH2.BUG_FUNC], ...
				['SubjectST.getr(''' TAG ''') must be inizialized to its default value ' ...
				'given by SubjectST.getPropDefaultConditioned(' int2str(prop) '). ' ...
				'Or there could be an error in SubjectST.getr(''' TAG ''').'] ...
				)
		case Category.RESULT
			assert( ...
				isa(sub.getr(prop), 'NoValue'), ...
				[BRAPH2.STR ':SubjectST:' BRAPH2.BUG_FUNC], ...
				['Being a result, SubjectST.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
				'Or there could be an error in SubjectST.getr(' int2str(prop) ').'] ...
				)
			assert( ...
				isa(sub.getr(TAG), 'NoValue'), ...
				[BRAPH2.STR ':SubjectST:' BRAPH2.BUG_FUNC], ...
				['Being a result, SubjectST.getr(''' TAG ''') must be inizialized to NoValue(). ' ...
				'Or there could be an error in SubjectST.getr(''' TAG ''').'] ...
				)
	end
end

%% Test 2: Callbacks

warning('off', 'BRAPH2:SubjectST')
sub_0 = SubjectST( ...
	SubjectST.ID, SubjectST.getPropDefault(SubjectST.ID), ...
	SubjectST.LABEL, SubjectST.getPropDefault(SubjectST.LABEL), ...
	SubjectST.NOTES, SubjectST.getPropDefault(SubjectST.NOTES), ...
	SubjectST.BA, SubjectST.getPropDefault(SubjectST.BA), ...
	SubjectST.ST, SubjectST.getPropDefault(SubjectST.ST), ...
	SubjectST.AGE, SubjectST.getPropDefault(SubjectST.AGE), ...
	SubjectST.SEX, SubjectST.getPropDefault(SubjectST.SEX) ...
	);
warning('on', 'BRAPH2:SubjectST')

sub_1 = SubjectST( ...
	SubjectST.ID, Callback('EL', sub_0, 'PROP', 1), ...
	SubjectST.LABEL, SubjectST.getPropDefault(SubjectST.LABEL), ...
	SubjectST.NOTES, SubjectST.getPropDefault(SubjectST.NOTES), ...
	SubjectST.BA, Callback('EL', sub_0, 'PROP', 4), ...
	SubjectST.ST, Callback('EL', sub_0, 'PROP', 5), ...
	SubjectST.AGE, Callback('EL', sub_0, 'PROP', 6), ...
	SubjectST.SEX, Callback('EL', sub_0, 'PROP', 7) ...
	);
	
prop_number = SubjectST.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(SubjectST.getPropTag(prop));
	switch SubjectST.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(sub_1.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':SubjectST:' BRAPH2.BUG_FUNC], ...
				['SubjectST.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(sub_1.get(prop), sub_0.get(prop)) && ~isa(sub_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':SubjectST:' BRAPH2.BUG_FUNC], ...
				['SubjectST.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(sub_1.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':SubjectST:' BRAPH2.BUG_FUNC], ...
				['SubjectST.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end
sub_2 = SubjectST( ...
	SubjectST.ID, Callback('EL', sub_1, 'PROP', 1), ...
	SubjectST.LABEL, SubjectST.getPropDefault(SubjectST.LABEL), ...
	SubjectST.NOTES, SubjectST.getPropDefault(SubjectST.NOTES), ...
	SubjectST.BA, Callback('EL', sub_1, 'PROP', 4), ...
	SubjectST.ST, Callback('EL', sub_1, 'PROP', 5), ...
	SubjectST.AGE, Callback('EL', sub_1, 'PROP', 6), ...
	SubjectST.SEX, Callback('EL', sub_1, 'PROP', 7) ...
	);
	
prop_number = SubjectST.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(SubjectST.getPropTag(prop));
	switch SubjectST.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(sub_2.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':SubjectST:' BRAPH2.BUG_FUNC], ...
				['SubjectST.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(sub_2.get(prop), sub_0.get(prop)) && ~isa(sub_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':SubjectST:' BRAPH2.BUG_FUNC], ...
				['SubjectST.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(sub_2.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':SubjectST:' BRAPH2.BUG_FUNC], ...
				['SubjectST.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end
sub_3 = SubjectST( ...
	SubjectST.ID, Callback('EL', sub_2, 'PROP', 1), ...
	SubjectST.LABEL, SubjectST.getPropDefault(SubjectST.LABEL), ...
	SubjectST.NOTES, SubjectST.getPropDefault(SubjectST.NOTES), ...
	SubjectST.BA, Callback('EL', sub_2, 'PROP', 4), ...
	SubjectST.ST, Callback('EL', sub_2, 'PROP', 5), ...
	SubjectST.AGE, Callback('EL', sub_2, 'PROP', 6), ...
	SubjectST.SEX, Callback('EL', sub_2, 'PROP', 7) ...
	);
	
prop_number = SubjectST.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(SubjectST.getPropTag(prop));
	switch SubjectST.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(sub_3.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':SubjectST:' BRAPH2.BUG_FUNC], ...
				['SubjectST.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(sub_3.get(prop), sub_0.get(prop)) && ~isa(sub_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':SubjectST:' BRAPH2.BUG_FUNC], ...
				['SubjectST.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(sub_3.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':SubjectST:' BRAPH2.BUG_FUNC], ...
				['SubjectST.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end

%% Test 3: Result

warning('off', 'BRAPH2:SubjectST')
sub = SubjectST( ...
	SubjectST.ID, SubjectST.getPropDefault(SubjectST.ID), ...
	SubjectST.LABEL, SubjectST.getPropDefault(SubjectST.LABEL), ...
	SubjectST.NOTES, SubjectST.getPropDefault(SubjectST.NOTES), ...
	SubjectST.BA, SubjectST.getPropDefault(SubjectST.BA), ...
	SubjectST.ST, SubjectST.getPropDefault(SubjectST.ST), ...
	SubjectST.AGE, SubjectST.getPropDefault(SubjectST.AGE), ...
	SubjectST.SEX, SubjectST.getPropDefault(SubjectST.SEX) ...
	);
warning('on', 'BRAPH2:SubjectST')

prop_number = SubjectST.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(SubjectST.getPropTag(prop));
	switch SubjectST.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
		case Category.RESULT
			assert( ...
				~isa(sub.get(prop),  'NoValue'), ...
				[BRAPH2.STR ':SubjectST:' BRAPH2.BUG_FUNC], ...
				['SubjectST.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				isa(sub.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':SubjectST:' BRAPH2.BUG_FUNC], ...
				['SubjectST.getr(' int2str(prop) ') must be a NoValue, because it has not been memorized.'] ...
				)
			if isempty(sub.getPropSettings(prop))
				assert( ...
					sub.checkFormat(sub.getPropFormat(prop), sub.get(prop)), ...
					[BRAPH2.STR ':SubjectST:' BRAPH2.BUG_FUNC], ...
					['SubjectST.get(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			else
				assert( ...
					sub.checkFormat(sub.getPropFormat(prop), sub.get(prop), sub.getPropSettings(prop)), ...
					[BRAPH2.STR ':SubjectST:' BRAPH2.BUG_FUNC], ...
					['SubjectST.get(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			end
	end
end

%% Test 4: Memorize

warning('off', 'BRAPH2:SubjectST')
sub = SubjectST( ...
	SubjectST.ID, SubjectST.getPropDefault(SubjectST.ID), ...
	SubjectST.LABEL, SubjectST.getPropDefault(SubjectST.LABEL), ...
	SubjectST.NOTES, SubjectST.getPropDefault(SubjectST.NOTES), ...
	SubjectST.BA, SubjectST.getPropDefault(SubjectST.BA), ...
	SubjectST.ST, SubjectST.getPropDefault(SubjectST.ST), ...
	SubjectST.AGE, SubjectST.getPropDefault(SubjectST.AGE), ...
	SubjectST.SEX, SubjectST.getPropDefault(SubjectST.SEX) ...
	);
warning('on', 'BRAPH2:SubjectST')

for prop = 1:1:SubjectST.getPropNumber()
	TAG = upper(SubjectST.getPropTag(prop));
	switch SubjectST.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
		case Category.RESULT
			assert( ...
				~isa(sub.get(prop),  'NoValue'), ...
				[BRAPH2.STR ':SubjectST:' BRAPH2.BUG_FUNC], ...
				['SubjectST.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				isa(sub.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':SubjectST:' BRAPH2.BUG_FUNC], ...
				['SubjectST.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
				)
			assert( ...
				~isa(sub.memorize(prop),  'NoValue'), ...
				[BRAPH2.STR ':SubjectST:' BRAPH2.BUG_FUNC], ...
				['SubjectST.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				~isa(sub.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':SubjectST:' BRAPH2.BUG_FUNC], ...
				['SubjectST.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
				)
			assert( ...
				sub.checkFormat(sub.getPropFormat(prop), sub.getr(prop),sub.getPropSettings(prop)), ...
				[BRAPH2.STR ':SubjectST:' BRAPH2.BUG_FUNC], ...
				['SubjectST.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
				)
	end
end

%% Test 5: GUI

im_ba = ImporterBrainAtlasXLS('FILE', [fileparts(which('SubjectST')) filesep 'example data ST (MRI)' filesep 'desikan_atlas.xlsx']);
ba = im_ba.get('BA');
im_gr = ImporterGroupSubjectST_XLS( ...
    'FILE', [fileparts(which('SubjectST')) filesep 'example data ST (MRI)' filesep 'xls' filesep 'ST_group1.xlsx'], ...
    'BA', ba ...
    );
gr = im_gr.get('GR');
GUI('PE', gr, 'CLOSEREQ', false).draw()

close(gcf)

