%TEST_STRENGTHOUT

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	m = StrengthOut();
	 
	% get('ELCLASS')
	if isa(StrengthOut, 'ConcreteElement')
		assert(strcmp(StrengthOut().get('ELCLASS'), 'StrengthOut'), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'StrengthOut().get(''ELCLASS'') should return ''StrengthOut''.')
	end
	 
	% getBuild()
	assert(StrengthOut.getBuild() == 1 && StrengthOut.getBuild() > 0, ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'StrengthOut.getBuild() should return the StrengthOut build number.')
	assert(m.getBuild() == 1 && m.getBuild() > 0 , ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'm.getBuild() should return the StrengthOut build number.')
	assert(Element.getBuild(m) == 1 && Element.getBuild(m) > 0, ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(m) should return the StrengthOut build number.')
	assert(Element.getBuild('StrengthOut') == 1 && Element.getBuild('StrengthOut') > 0, ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''StrengthOut'') should return the StrengthOut build number.')
	 
	% getClass()
	assert(strcmp(StrengthOut.getClass(), 'StrengthOut'), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'StrengthOut.getClass() should return ''StrengthOut''.')
	assert(strcmp(m.getClass(), 'StrengthOut'), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'm.getClass() should return ''StrengthOut''.')
	assert(strcmp(Element.getClass(m), 'StrengthOut'), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(m) should return ''StrengthOut''.')
	assert(strcmp(Element.getClass('StrengthOut'), 'StrengthOut'), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''StrengthOut'') should return ''StrengthOut''.')
	 
	% getSubclasses()
	assert(isequal(StrengthOut.getSubclasses(), subclasses('StrengthOut', [], [], true)), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'StrengthOut.getSubclasses() should return the same result as subclasses(''StrengthOut'', [], [], true).')
	assert(isequal(m.getSubclasses(), subclasses('StrengthOut', [], [], true)), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''StrengthOut'', [], [], true).')
	assert(isequal(Element.getSubclasses(m), subclasses('StrengthOut', [], [], true)), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(m) should return the same result as subclasses(''StrengthOut'', [], [], true).')
	assert(isequal(Element.getSubclasses('StrengthOut'), subclasses('StrengthOut', [], [], true)), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''StrengthOut'') should return the same result as subclasses(''StrengthOut'', [], [], true).')
	 
	% getProps()
	assert(isempty(StrengthOut.getProps()) || isequal(StrengthOut.getProps(), 1:1:length(StrengthOut.getProps())), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'StrengthOut.getProps() should return a row vector [1:1:N].')
	assert(isempty(StrengthOut.getProps()) || isequal(m.getProps(), 1:1:length(StrengthOut.getProps())), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'm.getProps() should return a row vector [1:1:N].')
	assert(isempty(StrengthOut.getProps()) || isequal(Element.getProps(m), 1:1:length(StrengthOut.getProps())), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(m) should return a row vector [1:1:N].')
	assert(isempty(StrengthOut.getProps()) || isequal(Element.getProps('StrengthOut'), 1:1:length(StrengthOut.getProps())), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''StrengthOut'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) StrengthOut.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(StrengthOut.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(StrengthOut.getProps())), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'StrengthOut.getProps(category) does not work.')
	tmp = cellfun(@(category) m.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(StrengthOut.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(StrengthOut.getProps())), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'm.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(m, category), categories, 'UniformOutput', false);
	assert(isempty(StrengthOut.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(StrengthOut.getProps())), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(m, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('StrengthOut', category), categories, 'UniformOutput', false);
	assert(isempty(StrengthOut.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(StrengthOut.getProps())), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''StrengthOut'', category) does not work.')
	 
	% getPropNumber()
	assert(StrengthOut.getPropNumber() == length(StrengthOut.getProps()), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'StrengthOut.getPropNumber() should return the number of properties.')
	assert(m.getPropNumber() == length(StrengthOut.getProps()), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'm.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(m) == length(StrengthOut.getProps()), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(m) should return the number of properties.')
	assert(Element.getPropNumber('StrengthOut') == length(StrengthOut.getProps()), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''StrengthOut'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) StrengthOut.getPropNumber(category), categories)) == StrengthOut.getPropNumber(), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'StrengthOut.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) m.getPropNumber(category), categories)) == StrengthOut.getPropNumber(), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'm.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(m, category), categories)) == StrengthOut.getPropNumber(), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(m, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('StrengthOut', category), categories)) == StrengthOut.getPropNumber(), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''StrengthOut'', category) does not work.')
	 
	% existsProp(prop)
	assert(~StrengthOut.existsProp(NaN), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'StrengthOut.existsProp(prop) does not work.')
	assert(~m.existsProp(NaN), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'm.existsProp(prop) does not work.')
	assert(~Element.existsProp(m, NaN), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(m, prop) does not work.')
	assert(~Element.existsProp('StrengthOut', NaN), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''StrengthOut'', prop) does not work.')
	 
	assert_with_error('StrengthOut.existsProp(NaN)', [BRAPH2.STR ':StrengthOut:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':StrengthOut:' BRAPH2.WRONG_INPUT], m)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':StrengthOut:' BRAPH2.WRONG_INPUT], m)
	assert_with_error('Element.existsProp(''StrengthOut'', NaN)', [BRAPH2.STR ':StrengthOut:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:StrengthOut.getPropNumber()
		assert(StrengthOut.existsProp(prop), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'StrengthOut.existsProp(prop) does not work.')
		assert(m.existsProp(prop), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'm.existsProp(prop) does not work.')
		assert(Element.existsProp(m, prop), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(m, prop) does not work.')
		assert(Element.existsProp('StrengthOut', prop), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''StrengthOut'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~StrengthOut.existsTag(''), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'StrengthOut.existsTag(tag) does not work.')
	assert(~m.existsTag(''), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'm.existsTag(tag) does not work.')
	assert(~Element.existsTag(m, ''), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(m, tag) does not work.')
	assert(~Element.existsTag('StrengthOut', ''), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''StrengthOut'', tag) does not work.')
	 
	assert_with_error('StrengthOut.existsTag('''')', [BRAPH2.STR ':StrengthOut:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':StrengthOut:' BRAPH2.WRONG_INPUT], m)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':StrengthOut:' BRAPH2.WRONG_INPUT], m)
	assert_with_error('Element.existsTag(''StrengthOut'', '''')', [BRAPH2.STR ':StrengthOut:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:StrengthOut.getPropNumber()
		tag = m.getPropTag(prop);
		assert(StrengthOut.existsTag(tag), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'StrengthOut.existsTag(tag) does not work.')
		assert(m.existsTag(tag), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'm.existsTag(tag) does not work.')
		assert(Element.existsTag(m, tag), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(m, tga) does not work.')
		assert(Element.existsTag('StrengthOut', tag), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''StrengthOut'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:StrengthOut.getPropNumber()
		assert(StrengthOut.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'StrengthOut.getPropProp(prop) does not work.')
		assert(m.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'm.getPropProp(prop) does not work.')
		assert(Element.getPropProp(m, prop) == prop, ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(m, prop) does not work.')
		assert(Element.getPropProp('StrengthOut', prop) == prop, ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''StrengthOut'', prop) does not work.')
	 
		tag = m.getPropTag(prop);
		assert(StrengthOut.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'StrengthOut.getPropProp(tag) does not work.')
		assert(m.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'm.getPropProp(tag) does not work.')
		assert(Element.getPropProp(m, tag) == prop, ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(m, tag) does not work.')
		assert(Element.getPropProp('StrengthOut', prop) == prop, ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''StrengthOut'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:StrengthOut.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(strcmp(StrengthOut.getPropTag(prop), tag), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'StrengthOut.getPropTag(prop) does not work.')
		assert(strcmp(m.getPropTag(prop), tag), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'm.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(m, prop), tag), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(m, prop) does not work.')
		assert(strcmp(Element.getPropTag('StrengthOut', prop), tag), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''StrengthOut'', prop) does not work.')
	 
		assert(strcmp(StrengthOut.getPropTag(tag), tag), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'StrengthOut.getPropTag(tag) does not work.')
		assert(strcmp(m.getPropTag(tag), tag), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'm.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(m, tag), tag), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(m, tag) does not work.')
		assert(strcmp(Element.getPropTag('StrengthOut', prop), tag), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''StrengthOut'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:StrengthOut.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(Category.existsCategory(StrengthOut.getPropCategory(prop)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'StrengthOut.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(m.getPropCategory(prop)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'm.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(m, prop)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(m, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(m, prop)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''StrengthOut'', prop) does not work.')
	 
		assert(Category.existsCategory(StrengthOut.getPropCategory(tag)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'StrengthOut.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(m.getPropCategory(tag)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'm.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(m, tag)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(m, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(m, tag)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''StrengthOut'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:StrengthOut.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(Format.existsFormat(StrengthOut.getPropFormat(prop)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'StrengthOut.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(m.getPropFormat(prop)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'm.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(m, prop)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(m, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(m, prop)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''StrengthOut'', prop) does not work.')
	 
		assert(Format.existsFormat(StrengthOut.getPropFormat(tag)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'StrengthOut.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(m.getPropFormat(tag)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'm.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(m, tag)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(m, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(m, tag)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''StrengthOut'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:StrengthOut.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(ischar(StrengthOut.getPropDescription(prop)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'StrengthOut.getPropDescription(prop) does not work.')
		assert(ischar(m.getPropDescription(prop)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'm.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(m, prop)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(m, prop) does not work.')
		assert(ischar(Element.getPropDescription(m, prop)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''StrengthOut'', prop) does not work.')
	 
		assert(ischar(StrengthOut.getPropDescription(tag)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'StrengthOut.getPropDescription(tag) does not work.')
		assert(ischar(m.getPropDescription(tag)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'm.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(m, tag)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(m, tag) does not work.')
		assert(ischar(Element.getPropDescription(m, tag)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''StrengthOut'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:StrengthOut.getPropNumber()
		tag = m.getPropTag(prop);
	 
		settings = StrengthOut.getPropSettings(prop);
		settings = m.getPropSettings(prop);
		settings = Element.getPropSettings(m, prop);
		settings = Element.getPropSettings('StrengthOut', prop);
	 
		settings = StrengthOut.getPropSettings(tag);
		settings = m.getPropSettings(tag);
		settings = Element.getPropSettings(m, tag);
		settings = Element.getPropSettings('StrengthOut', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:StrengthOut.getPropNumber()
		tag = m.getPropTag(prop);
	 
		default = StrengthOut.getPropDefault(prop);
		default = m.getPropDefault(prop);
		default = Element.getPropDefault(m, prop);
		default = Element.getPropDefault('StrengthOut', prop);
	 
		default = StrengthOut.getPropDefault(tag);
		default = m.getPropDefault(tag);
		default = Element.getPropDefault(m, tag);
		default = Element.getPropDefault('StrengthOut', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:StrengthOut.getPropNumber()
		tag = m.getPropTag(prop);
	 
		conditioned_default = StrengthOut.getPropDefaultConditioned(prop);
		conditioned_default = m.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(m, prop);
		conditioned_default = Element.getPropDefaultConditioned('StrengthOut', prop);
	 
		conditioned_default = StrengthOut.getPropDefaultConditioned(tag);
		conditioned_default = m.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(m, tag);
		conditioned_default = Element.getPropDefaultConditioned('StrengthOut', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:StrengthOut.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(~StrengthOut.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'StrengthOut.checkProp(prop, value) does not work.')
		assert(~m.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'm.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(m, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(m, prop, value) does not work.')
		assert(~Element.checkProp('StrengthOut', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''StrengthOut'', prop, value) does not work.')
	 
		assert_with_error('StrengthOut.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':StrengthOut:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':StrengthOut:' BRAPH2.WRONG_INPUT], prop, m)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':StrengthOut:' BRAPH2.WRONG_INPUT], prop, m)
		assert_with_error('Element.checkProp(''StrengthOut'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':StrengthOut:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~StrengthOut.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'StrengthOut.checkProp(tag, value) does not work.')
		assert(~m.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'm.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(m, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(m, tag, value) does not work.')
		assert(~Element.checkProp('StrengthOut', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''StrengthOut'', tag, value) does not work.')
	 
		assert_with_error('StrengthOut.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':StrengthOut:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':StrengthOut:' BRAPH2.WRONG_INPUT], tag, m)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':StrengthOut:' BRAPH2.WRONG_INPUT], tag, m)
		assert_with_error('Element.checkProp(''StrengthOut'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':StrengthOut:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(StrengthOut.checkProp(prop, Element.getPropDefaultConditioned(StrengthOut, prop)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'StrengthOut.checkProp(prop, <conditioned default value>) does not work.')
		assert(m.checkProp(prop, Element.getPropDefaultConditioned(StrengthOut, prop)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'm.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(m, prop, Element.getPropDefaultConditioned(StrengthOut, prop)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(m, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('StrengthOut', prop, Element.getPropDefaultConditioned(StrengthOut, prop)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''StrengthOut'', prop, <conditioned default value>) does not work.')
	 
		assert(StrengthOut.checkProp(tag, Element.getPropDefaultConditioned(StrengthOut, prop)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'StrengthOut.checkProp(tag, <conditioned default value>) does not work.')
		assert(m.checkProp(tag, Element.getPropDefaultConditioned(StrengthOut, prop)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'm.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(m, tag, Element.getPropDefaultConditioned(StrengthOut, prop)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(m, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('StrengthOut', tag, Element.getPropDefaultConditioned(StrengthOut, prop)), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''StrengthOut'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = StrengthOut( ...
		StrengthOut.ELCLASS, StrengthOut.getNoValue(), ...
		StrengthOut.NAME, StrengthOut.getNoValue(), ...
		StrengthOut.DESCRIPTION, StrengthOut.getNoValue(), ...
		StrengthOut.TEMPLATE, StrengthOut.getPropDefault(StrengthOut.TEMPLATE), ...
		StrengthOut.ID, StrengthOut.getPropDefault(StrengthOut.ID), ...
		StrengthOut.LABEL, StrengthOut.getPropDefault(StrengthOut.LABEL), ...
		StrengthOut.NOTES, StrengthOut.getPropDefault(StrengthOut.NOTES), ...
		StrengthOut.TOSTRING, StrengthOut.getNoValue(), ...
		StrengthOut.SHAPE, StrengthOut.getNoValue(), ...
		StrengthOut.SCOPE, StrengthOut.getNoValue(), ...
		StrengthOut.PARAMETRICITY, StrengthOut.getNoValue(), ...
		StrengthOut.COMPATIBLE_GRAPHS, StrengthOut.getNoValue(), ...
		StrengthOut.G, StrengthOut.getPropDefault(StrengthOut.G), ...
		StrengthOut.M, StrengthOut.getNoValue(), ...
		StrengthOut.PFM, StrengthOut.getPropDefault(StrengthOut.PFM) ...
		);
	 
	for prop = 1:1:StrengthOut.getPropNumber()
	 
		% excluded props
		if any(prop == [StrengthIn.PFM])
			continue
		end
	 
		TAG = upper(StrengthOut.getPropTag(prop));
		switch StrengthOut.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					m.getr(prop) == StrengthOut.getNoValue(), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['Being a ' StrengthOut.getCategoryName(StrengthOut.getPropCategory(prop)) ', StrengthOut.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in StrengthOut.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					m.getr(TAG) == StrengthOut.getNoValue(), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['Being a ' StrengthOut.getCategoryName(StrengthOut.getPropCategory(prop)) ', StrengthOut.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in StrengthOut.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(m.getPropSettings(prop))
					assert( ...
						m.checkFormat(m.getPropFormat(prop), m.get(prop)), ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						['StrengthOut.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						m.checkFormat(m.getPropFormat(prop), m.get(prop), m.getPropSettings(prop)), ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						['StrengthOut.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					m.getr(prop) == StrengthOut.getNoValue(), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['Being a ' StrengthOut.getCategoryName(StrengthOut.getPropCategory(prop)) ', StrengthOut.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in StrengthOut.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					m.getr(TAG) == StrengthOut.getNoValue(), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['Being a ' StrengthOut.getCategoryName(StrengthOut.getPropCategory(prop)) ', StrengthOut.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in StrengthOut.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':StrengthOut']);
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(m.getPropSettings(prop))
					assert( ...
						m.checkFormat(m.getPropFormat(prop), m.get(prop)), ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						['StrengthOut.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						m.checkFormat(m.getPropFormat(prop), m.get(prop), m.getPropSettings(prop)), ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						['StrengthOut.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(m.getr(prop), StrengthOut.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by StrengthOut.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in StrengthOut.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(m.getr(TAG), StrengthOut.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.getr(' TAG ') must be inizialized to its default value ' ...
					'given by StrengthOut.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in StrengthOut.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = StrengthOut( ...
		StrengthOut.ELCLASS, StrengthOut.getNoValue(), ...
		StrengthOut.NAME, StrengthOut.getNoValue(), ...
		StrengthOut.DESCRIPTION, StrengthOut.getNoValue(), ...
		StrengthOut.TEMPLATE, StrengthOut.getPropDefault(StrengthOut.TEMPLATE), ...
		StrengthOut.ID, StrengthOut.getPropDefault(StrengthOut.ID), ...
		StrengthOut.LABEL, StrengthOut.getPropDefault(StrengthOut.LABEL), ...
		StrengthOut.NOTES, StrengthOut.getPropDefault(StrengthOut.NOTES), ...
		StrengthOut.TOSTRING, StrengthOut.getNoValue(), ...
		StrengthOut.SHAPE, StrengthOut.getNoValue(), ...
		StrengthOut.SCOPE, StrengthOut.getNoValue(), ...
		StrengthOut.PARAMETRICITY, StrengthOut.getNoValue(), ...
		StrengthOut.COMPATIBLE_GRAPHS, StrengthOut.getNoValue(), ...
		StrengthOut.G, StrengthOut.getPropDefault(StrengthOut.G), ...
		StrengthOut.M, StrengthOut.getNoValue(), ...
		StrengthOut.PFM, StrengthOut.getPropDefault(StrengthOut.PFM) ...
		);
	 
	for prop = 1:1:StrengthOut.getPropNumber()
	 
		% excluded props
		if any(prop == [StrengthIn.PFM])
			continue
		end
	 
		TAG = upper(StrengthOut.getPropTag(prop));
		switch StrengthOut.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(m.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					m.checkFormat(m.getPropFormat(prop), m.getr(prop),m.getPropSettings(prop)), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':StrengthOut']);
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':StrengthOut']);
	% 			assert( ...
	% 				~isa(m.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
	% 				['StrengthOut.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(m.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
	% 				['StrengthOut.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				m.checkFormat(m.getPropFormat(prop), m.getr(prop),m.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
	% 				['StrengthOut.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':StrengthOut']);
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(m.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					m.checkFormat(m.getPropFormat(prop), m.getr(prop),m.getPropSettings(prop)), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if m.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:StrengthOut');
					delete(ancestor(m.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(StrengthOut.getProps(Category.RESULT))
		for prop = 1:1:StrengthOut.getPropNumber()
	 
			% excluded props
			if any(prop == [StrengthIn.PFM])
				continue
			end
	 
			switch StrengthOut.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						m.isLocked(prop), ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						['StrengthOut.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~m.isLocked(prop), ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						['StrengthOut.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = StrengthOut();
	 
	for prop = 1:1:StrengthOut.getPropNumber()
		TAG = upper(StrengthOut.getPropTag(prop));
		assert( ...
			~m.isLocked(prop), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			['StrengthOut.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~m.isLocked(TAG), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			['StrengthOut.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	m.lock()
	 
	for prop = 1:1:StrengthOut.getPropNumber()
		switch StrengthOut.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					m.isLocked(prop), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~m.isLocked(prop), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = StrengthOut();
	 
	warning_backup = warning('off', 'BRAPH2:StrengthOut');
	for prop = 1:1:StrengthOut.getPropNumber()
		m.lock(prop)
		switch StrengthOut.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					m.isLocked(prop), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~m.isLocked(prop), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = StrengthOut();
	 
	for prop = 1:1:StrengthOut.getPropNumber()
		TAG = upper(StrengthOut.getPropTag(prop));
		assert( ...
			m.isChecked(prop), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			['StrengthOut.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			m.isChecked(TAG), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			['StrengthOut.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	m.unchecked()
	 
	for prop = 1:1:StrengthOut.getPropNumber()
		assert( ...
			~m.isChecked(prop), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			['StrengthOut.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	m.checked()
	 
	for prop = 1:1:StrengthOut.getPropNumber()
		assert( ...
			m.isChecked(prop), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			['StrengthOut.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic StrengthOut
	m_0 = StrengthOut( ...
		StrengthOut.ELCLASS, StrengthOut.getNoValue(), ...
		StrengthOut.NAME, StrengthOut.getNoValue(), ...
		StrengthOut.DESCRIPTION, StrengthOut.getNoValue(), ...
		StrengthOut.TEMPLATE, StrengthOut.getPropDefault(StrengthOut.TEMPLATE), ...
		StrengthOut.ID, StrengthOut.getPropDefault(StrengthOut.ID), ...
		StrengthOut.LABEL, StrengthOut.getPropDefault(StrengthOut.LABEL), ...
		StrengthOut.NOTES, StrengthOut.getPropDefault(StrengthOut.NOTES), ...
		StrengthOut.TOSTRING, StrengthOut.getNoValue(), ...
		StrengthOut.SHAPE, StrengthOut.getNoValue(), ...
		StrengthOut.SCOPE, StrengthOut.getNoValue(), ...
		StrengthOut.PARAMETRICITY, StrengthOut.getNoValue(), ...
		StrengthOut.COMPATIBLE_GRAPHS, StrengthOut.getNoValue(), ...
		StrengthOut.G, StrengthOut.getPropDefault(StrengthOut.G), ...
		StrengthOut.M, StrengthOut.getNoValue(), ...
		StrengthOut.PFM, StrengthOut.getPropDefault(StrengthOut.PFM) ...
		);
	 
	% StrengthOut with 1st callbacks
	m_1 = StrengthOut( ...
		StrengthOut.ELCLASS, StrengthOut.getNoValue(), ...
		StrengthOut.NAME, StrengthOut.getNoValue(), ...
		StrengthOut.DESCRIPTION, StrengthOut.getNoValue(), ...
		StrengthOut.TEMPLATE, m_0.getCallback(4), ..., ...
		StrengthOut.ID, m_0.getCallback(5), ..., ...
		StrengthOut.LABEL, StrengthOut.getPropDefault(StrengthOut.LABEL), ...
		StrengthOut.NOTES, StrengthOut.getPropDefault(StrengthOut.NOTES), ...
		StrengthOut.TOSTRING, StrengthOut.getNoValue(), ...
		StrengthOut.SHAPE, StrengthOut.getNoValue(), ...
		StrengthOut.SCOPE, StrengthOut.getNoValue(), ...
		StrengthOut.PARAMETRICITY, StrengthOut.getNoValue(), ...
		StrengthOut.COMPATIBLE_GRAPHS, StrengthOut.getNoValue(), ...
		StrengthOut.G, m_0.getCallback(13), ..., ...
		StrengthOut.M, StrengthOut.getNoValue(), ...
		StrengthOut.PFM, m_0.getCallback(15) ... ...
		);
	 
	prop_number = StrengthOut.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(StrengthOut.getPropTag(prop));
		switch StrengthOut.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(m_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(m_1.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(m_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% StrengthOut with 2nd callbacks
	m_2 = StrengthOut( ...
		StrengthOut.ELCLASS, StrengthOut.getNoValue(), ...
		StrengthOut.NAME, StrengthOut.getNoValue(), ...
		StrengthOut.DESCRIPTION, StrengthOut.getNoValue(), ...
		StrengthOut.TEMPLATE, m_1.getCallback(4), ..., ...
		StrengthOut.ID, m_1.getCallback(5), ..., ...
		StrengthOut.LABEL, StrengthOut.getPropDefault(StrengthOut.LABEL), ...
		StrengthOut.NOTES, StrengthOut.getPropDefault(StrengthOut.NOTES), ...
		StrengthOut.TOSTRING, StrengthOut.getNoValue(), ...
		StrengthOut.SHAPE, StrengthOut.getNoValue(), ...
		StrengthOut.SCOPE, StrengthOut.getNoValue(), ...
		StrengthOut.PARAMETRICITY, StrengthOut.getNoValue(), ...
		StrengthOut.COMPATIBLE_GRAPHS, StrengthOut.getNoValue(), ...
		StrengthOut.G, m_1.getCallback(13), ..., ...
		StrengthOut.M, StrengthOut.getNoValue(), ...
		StrengthOut.PFM, m_1.getCallback(15) ... ...
		);
	 
	prop_number = StrengthOut.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(StrengthOut.getPropTag(prop));
		switch StrengthOut.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(m_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(m_2.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(m_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% StrengthOut with 3rd callbacks
	m_3 = StrengthOut( ...
		StrengthOut.ELCLASS, StrengthOut.getNoValue(), ...
		StrengthOut.NAME, StrengthOut.getNoValue(), ...
		StrengthOut.DESCRIPTION, StrengthOut.getNoValue(), ...
		StrengthOut.TEMPLATE, m_2.getCallback(4), ..., ...
		StrengthOut.ID, m_2.getCallback(5), ..., ...
		StrengthOut.LABEL, StrengthOut.getPropDefault(StrengthOut.LABEL), ...
		StrengthOut.NOTES, StrengthOut.getPropDefault(StrengthOut.NOTES), ...
		StrengthOut.TOSTRING, StrengthOut.getNoValue(), ...
		StrengthOut.SHAPE, StrengthOut.getNoValue(), ...
		StrengthOut.SCOPE, StrengthOut.getNoValue(), ...
		StrengthOut.PARAMETRICITY, StrengthOut.getNoValue(), ...
		StrengthOut.COMPATIBLE_GRAPHS, StrengthOut.getNoValue(), ...
		StrengthOut.G, m_2.getCallback(13), ..., ...
		StrengthOut.M, StrengthOut.getNoValue(), ...
		StrengthOut.PFM, m_2.getCallback(15) ... ...
		);
	 
	prop_number = StrengthOut.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(StrengthOut.getPropTag(prop));
		switch StrengthOut.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(m_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(m_3.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(m_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	m = StrengthOut();
	 
	m_copy = m.copy();
	 
	assert(m_copy ~= m, ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'StrengthOut.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(m_copy, m), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'StrengthOut.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:StrengthOut.getPropNumber()
		value = m.getr(prop);
		value_copy = m_copy.getr(prop);
		switch StrengthOut.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					'StrengthOut.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						'StrengthOut.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						'StrengthOut.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						'StrengthOut.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
							'StrengthOut.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
							'StrengthOut.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						'StrengthOut.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					m_copy.isLocked(prop) == m.isLocked(prop), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					'StrengthOut.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					m_copy.isChecked(prop) == m.isChecked(prop), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					'StrengthOut.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					m_copy.getPropSeed(prop) == m.getPropSeed(prop), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					'StrengthOut.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	m = StrengthOut( ...
		StrengthOut.ELCLASS, StrengthOut.getNoValue(), ...
		StrengthOut.NAME, StrengthOut.getNoValue(), ...
		StrengthOut.DESCRIPTION, StrengthOut.getNoValue(), ...
		StrengthOut.TEMPLATE, StrengthOut.getPropDefault(StrengthOut.TEMPLATE), ...
		StrengthOut.ID, StrengthOut.getPropDefault(StrengthOut.ID), ...
		StrengthOut.LABEL, StrengthOut.getPropDefault(StrengthOut.LABEL), ...
		StrengthOut.NOTES, StrengthOut.getPropDefault(StrengthOut.NOTES), ...
		StrengthOut.TOSTRING, StrengthOut.getNoValue(), ...
		StrengthOut.SHAPE, StrengthOut.getNoValue(), ...
		StrengthOut.SCOPE, StrengthOut.getNoValue(), ...
		StrengthOut.PARAMETRICITY, StrengthOut.getNoValue(), ...
		StrengthOut.COMPATIBLE_GRAPHS, StrengthOut.getNoValue(), ...
		StrengthOut.G, StrengthOut.getPropDefault(StrengthOut.G), ...
		StrengthOut.M, StrengthOut.getNoValue(), ...
		StrengthOut.PFM, StrengthOut.getPropDefault(StrengthOut.PFM) ...
		);
	 
	for prop = 1:1:StrengthOut.getPropNumber()
		if StrengthOut.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':StrengthOut']);
			% m.memorize(prop);
			% warning(warning_backup)
		elseif StrengthOut.getPropCategory(prop) == Category.EVANESCENT && m.getPropFormat(prop) == Format.HANDLE
			m.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:StrengthOut');
			delete(ancestor(m.get(prop), 'figure'))
			warning(warning_backup)
		else
			m.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	m_copy = m.copy();
	 
	for prop = 1:1:StrengthOut.getPropNumber()
		value = m.getr(prop);
		value_copy = m_copy.getr(prop);
		switch StrengthOut.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					'StrengthOut.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						'StrengthOut.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						'StrengthOut.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						'StrengthOut.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
							'StrengthOut.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
							'StrengthOut.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						'StrengthOut.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						m_copy.isLocked(prop) == m.isLocked(prop), ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						'StrengthOut.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						m_copy.isChecked(prop) == m.isChecked(prop), ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						'StrengthOut.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						m_copy.getPropSeed(prop) == m.getPropSeed(prop), ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						'StrengthOut.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	m_0 = StrengthOut( ...
		StrengthOut.ELCLASS, StrengthOut.getNoValue(), ...
		StrengthOut.NAME, StrengthOut.getNoValue(), ...
		StrengthOut.DESCRIPTION, StrengthOut.getNoValue(), ...
		StrengthOut.TEMPLATE, StrengthOut.getPropDefault(StrengthOut.TEMPLATE), ...
		StrengthOut.ID, StrengthOut.getPropDefault(StrengthOut.ID), ...
		StrengthOut.LABEL, StrengthOut.getPropDefault(StrengthOut.LABEL), ...
		StrengthOut.NOTES, StrengthOut.getPropDefault(StrengthOut.NOTES), ...
		StrengthOut.TOSTRING, StrengthOut.getNoValue(), ...
		StrengthOut.SHAPE, StrengthOut.getNoValue(), ...
		StrengthOut.SCOPE, StrengthOut.getNoValue(), ...
		StrengthOut.PARAMETRICITY, StrengthOut.getNoValue(), ...
		StrengthOut.COMPATIBLE_GRAPHS, StrengthOut.getNoValue(), ...
		StrengthOut.G, StrengthOut.getPropDefault(StrengthOut.G), ...
		StrengthOut.M, StrengthOut.getNoValue(), ...
		StrengthOut.PFM, StrengthOut.getPropDefault(StrengthOut.PFM) ...
		);
	 
	m = StrengthOut( ...
		StrengthOut.ELCLASS, StrengthOut.getNoValue(), ...
		StrengthOut.NAME, StrengthOut.getNoValue(), ...
		StrengthOut.DESCRIPTION, StrengthOut.getNoValue(), ...
		StrengthOut.TEMPLATE, m_0.getCallback(4), ..., ...
		StrengthOut.ID, m_0.getCallback(5), ..., ...
		StrengthOut.LABEL, StrengthOut.getPropDefault(StrengthOut.LABEL), ...
		StrengthOut.NOTES, StrengthOut.getPropDefault(StrengthOut.NOTES), ...
		StrengthOut.TOSTRING, StrengthOut.getNoValue(), ...
		StrengthOut.SHAPE, StrengthOut.getNoValue(), ...
		StrengthOut.SCOPE, StrengthOut.getNoValue(), ...
		StrengthOut.PARAMETRICITY, StrengthOut.getNoValue(), ...
		StrengthOut.COMPATIBLE_GRAPHS, StrengthOut.getNoValue(), ...
		StrengthOut.G, m_0.getCallback(13), ..., ...
		StrengthOut.M, StrengthOut.getNoValue(), ...
		StrengthOut.PFM, m_0.getCallback(15) ... ...
		);
	 
	m_copy = m.copy();
	m_0_copy = m_copy.getr('ID').get('EL');
	 
	for prop = 1:1:StrengthOut.getPropNumber()
		value = m.getr(prop);
		value_copy = m_copy.getr(prop);
		switch StrengthOut.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					'StrengthOut.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						'StrengthOut.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						'StrengthOut.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						'StrengthOut.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
							'StrengthOut.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
							'StrengthOut.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						'StrengthOut.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == m_0.getCallback(prop), ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						'StrengthOut.copy() does not work. The callback should be obtained from StrengthOut.getCallback().' ...
						)
					assert( ...
						value_copy == m_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						'StrengthOut.copy() does not work. The callback should be obtained from StrengthOut.getCallback().' ...
						)
				end
	 
					assert( ...
						m_copy.isLocked(prop) == m.isLocked(prop), ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						'StrengthOut.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						m_copy.isChecked(prop) == m.isChecked(prop), ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						'StrengthOut.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						m_copy.getPropSeed(prop) == m.getPropSeed(prop), ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						'StrengthOut.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m_template = StrengthOut();
	m = StrengthOut('TEMPLATE', m_template);
	 
	for prop = 1:1:StrengthOut.getPropNumber()
	 
		% excluded props
		if any(prop == [StrengthIn.PFM])
			continue
		end
	 
		TAG = upper(StrengthOut.getPropTag(prop));
		switch StrengthOut.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == StrengthOut.TEMPLATE
					assert( ...
						isa(m.getr(prop), 'StrengthOut'), ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						'StrengthOut TEMPLATE does not work. StrengthOut.getr(''TEMPLATE'') should be a StrengthOut element.' ...
						)
					assert( ...
						isa(m_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						'StrengthOut TEMPLATE does not work. StrengthOut_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(m.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						['StrengthOut TEMPLATE does not work. StrengthOut.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						m.getr(prop).get('EL') == m_template && m.getr(prop).get('PROP') == prop && strcmp(m.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						['StrengthOut TEMPLATE does not work. StrengthOut.getr(' TAG ') should be a Callback to m_template.' TAG '.'] ...
						)
					assert( ...
						isa(m_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
						['StrengthOut TEMPLATE does not work. StrengthOut_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut TEMPLATE does not work. StrengthOut.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(m_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
					['StrengthOut TEMPLATE does not work. StrengthOut_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = StrengthOut( ...
		StrengthOut.ELCLASS, StrengthOut.getNoValue(), ...
		StrengthOut.NAME, StrengthOut.getNoValue(), ...
		StrengthOut.DESCRIPTION, StrengthOut.getNoValue(), ...
		StrengthOut.TEMPLATE, StrengthOut.getPropDefault(StrengthOut.TEMPLATE), ...
		StrengthOut.ID, StrengthOut.getPropDefault(StrengthOut.ID), ...
		StrengthOut.LABEL, StrengthOut.getPropDefault(StrengthOut.LABEL), ...
		StrengthOut.NOTES, StrengthOut.getPropDefault(StrengthOut.NOTES), ...
		StrengthOut.TOSTRING, StrengthOut.getNoValue(), ...
		StrengthOut.SHAPE, StrengthOut.getNoValue(), ...
		StrengthOut.SCOPE, StrengthOut.getNoValue(), ...
		StrengthOut.PARAMETRICITY, StrengthOut.getNoValue(), ...
		StrengthOut.COMPATIBLE_GRAPHS, StrengthOut.getNoValue(), ...
		StrengthOut.G, StrengthOut.getPropDefault(StrengthOut.G), ...
		StrengthOut.M, StrengthOut.getNoValue(), ...
		StrengthOut.PFM, StrengthOut.getPropDefault(StrengthOut.PFM) ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'strengthout_to_be_erased.b2'];
	 
	Element.save(m, filename)
	 
	m_loaded = Element.load(filename);
	 
	assert( ...
		isequal(m.copy(), m_loaded), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'StrengthOut.save(m) and/or StrengthOut.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = StrengthOut( ...
		StrengthOut.ELCLASS, StrengthOut.getNoValue(), ...
		StrengthOut.NAME, StrengthOut.getNoValue(), ...
		StrengthOut.DESCRIPTION, StrengthOut.getNoValue(), ...
		StrengthOut.TEMPLATE, StrengthOut.getPropDefault(StrengthOut.TEMPLATE), ...
		StrengthOut.ID, StrengthOut.getPropDefault(StrengthOut.ID), ...
		StrengthOut.LABEL, StrengthOut.getPropDefault(StrengthOut.LABEL), ...
		StrengthOut.NOTES, StrengthOut.getPropDefault(StrengthOut.NOTES), ...
		StrengthOut.TOSTRING, StrengthOut.getNoValue(), ...
		StrengthOut.SHAPE, StrengthOut.getNoValue(), ...
		StrengthOut.SCOPE, StrengthOut.getNoValue(), ...
		StrengthOut.PARAMETRICITY, StrengthOut.getNoValue(), ...
		StrengthOut.COMPATIBLE_GRAPHS, StrengthOut.getNoValue(), ...
		StrengthOut.G, StrengthOut.getPropDefault(StrengthOut.G), ...
		StrengthOut.M, StrengthOut.getNoValue(), ...
		StrengthOut.PFM, StrengthOut.getPropDefault(StrengthOut.PFM) ...
		);
	 
	[json, struct, el_list] = encodeJSON(m);
	[m_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(m_dec ~= m, ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		'StrengthOut.encodeJSON() or StrengthOut.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) StrengthOut.getPropFormat(prop), num2cell(StrengthOut.getProps())) == Format.HANDLE) && all(cellfun(@(prop) StrengthOut.getPropFormat(prop), num2cell(StrengthOut.getProps())) == Format.NET)
		assert(isequal(m_dec, m), ...
			[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
			'StrengthOut.encodeJSON() or StrengthOut.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: GraphWD
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	B = [
	    0  .2 1
	    .2 0  0
	    1  0  0
	    ];
	known_strength = {[1.2 0.2 1]'};
	g = GraphWD('B', B);
	m_outside_g = StrengthOut('G', g);
	assert(isequal(m_outside_g.get('M'), known_strength), ...
	    [BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
	    [class(m_outside_g) ' is not being calculated correctly for ' class(g) '.'])
	
	m_inside_g = g.get('MEASURE', 'StrengthOut');
	assert(isequal(m_inside_g.get('M'), known_strength), ...
	    [BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
	    [class(m_inside_g) ' is not being calculated correctly for ' class(g) '.'])
end

%% Test 13: MultiplexWD
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	B11 = [
	    0  .2 1
	    .2 0  0
	    1  0  0
	    ];
	B22 = [
	    0 1  0
	    1 0  .4
	    0 .4 0
	    ];
	B = {B11 B22};
	
	known_strength = {
	                 [1.2 .2  1]'
	                 [1   1.4 .4]'
	                 };
	                                
	g = MultiplexWD('B', B);
	m_outside_g = StrengthOut('G', g);
	assert(isequal(m_outside_g.get('M'), known_strength), ...
	    [BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
	    [class(m_outside_g) ' is not being calculated correctly for ' class(g) '.'])
	
	m_inside_g = g.get('MEASURE', 'StrengthOut');
	assert(isequal(m_inside_g.get('M'), known_strength), ...
	    [BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
	    [class(m_inside_g) ' is not being calculated correctly for ' class(g) '.'])
end

%% Test 14: OrdMxWD
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	B11 = [
	    0   .3  1
	    .2  0   0
	    1   0   0
	    ];
	B22 = [
	    0   0.3   0
	    1   0   .3
	    0   .3  0
	    ];
	B= {B11 B22};
	
	known_strength = {
	    [1.3 .2 1]'
	    [0.3 1.3 .3]'
	    };
	
	g = OrdMxWD('B', B);
	
	m_outside_g = StrengthOut('G', g);
	assert(isequal(m_outside_g.get('M'), known_strength), ...
	    [BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
	    [class(m_outside_g) ' is not being calculated correctly for ' class(g) '.'])
	
	m_inside_g = g.get('MEASURE', 'StrengthOut');
	assert(isequal(m_inside_g.get('M'), known_strength), ...
	    [BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
	    [class(m_inside_g) ' is not being calculated correctly for ' class(g) '.'])
end

%% Test 15: MultilayerWD
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	B11 = [
	    0   0.2   .7
	    .2   0   .1
	    .7  .1   0
	    ];
	
	B22 = [    
	    0   .2   .7 .5
	    .2   0   .1 .5
	    .7  .1   0  .5
	    .5  .5  .5  0
	    ];
	B33 = [    
	    0   .2   .9 .5
	    .2   0   .1 .5
	    .9  .1   0  .2
	    .5  .5  .2  0
	    ];
	B12 = rand(size(B11,1),size(B22,2));
	B13 = rand(size(B11,1),size(B33,2));
	B23 = rand(size(B22,1),size(B33,2));
	B21 = B12';
	B31 = B13';
	B32 = B23';
	B= {B11 B12 B13;
	    B21 B22 B23;
	    B31 B32 B33};
	
	known_strength = {
	    [0.9 0.3 0.8]'
	    [1.4 0.8 1.3 1.5]'
	    [1.6 0.8 1.2 1.2]'
	    };
	
	g = MultilayerWD('B', B);
	
	m_outside_g = StrengthOut('G', g);
	pl_answer = cellfun(@(x) round(x, 3), m_outside_g.get('M'), 'UniformOutput', false);;
	assert(isequal(pl_answer, known_strength), ...
	    [BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
	    [class(m_outside_g) ' is not being calculated correctly for ' class(g) '.'])
	
	m_inside_g = g.get('MEASURE', 'StrengthOut');
	pl_answer = cellfun(@(x) round(x, 3), m_inside_g.get('M'), 'UniformOutput', false);
	assert(isequal(pl_answer, known_strength), ...
	    [BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
	    [class(m_inside_g) ' is not being calculated correctly for ' class(g) '.'])
end

%% Test 16: OrdMlWD
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	B11 = [
	    0   0.2   .7
	    .2   0   .1
	    .7  .1   0
	    ];
	
	B22 = [    
	    0   .2   .7 .5
	    .2   0   .1 .5
	    .7  .1   0  .5
	    .5  .5  .5  0
	    ];
	B33 = [    
	     0  .2   .9 .5
	    .2   0   .1 .5
	    .9  .1   0  .2
	    .5  .5  .2  0
	    ];
	B12 = rand(size(B11,1),size(B22,2));
	B13 = rand(size(B11,1),size(B33,2));
	B23 = rand(size(B22,1),size(B33,2));
	B21 = B12';
	B31 = B13';
	B32 = B23';
	B= {B11 B12 B13;
	    B21 B22 B23;
	    B31 B32 B33};
	
	known_strength = {
	    [0.9 0.3 0.8]'
	    [1.4 0.8 1.3 1.5]'
	    [1.6 0.8 1.2 1.2]'
	    };
	
	g = OrdMlWD('B', B);
	m_outside_g = StrengthOut('G', g);
	pl_answer = cellfun(@(x) round(x, 3), m_outside_g.get('M'), 'UniformOutput', false);
	assert(isequal(pl_answer, known_strength), ...
	    [BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
	    [class(m_outside_g) ' is not being calculated correctly for ' class(g) '.'])
	
	m_inside_g = g.get('MEASURE', 'StrengthOut');
	pl_answer = cellfun(@(x) round(x, 3), m_inside_g.get('M'), 'UniformOutput', false);
	assert(isequal(pl_answer, known_strength), ...
	    [BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
	    [class(m_inside_g) ' is not being calculated correctly for ' class(g) '.'])
end

%% Test 17: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':StrengthOut:' BRAPH2.FAIL_TEST], ...
		[' When testing StrengthOut no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 18: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

