%TEST_WEIGHTEDMXPIN

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	m = WeightedMxPIn();
	 
	% get('ELCLASS')
	if isa(WeightedMxPIn, 'ConcreteElement')
		assert(strcmp(WeightedMxPIn().get('ELCLASS'), 'WeightedMxPIn'), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'WeightedMxPIn().get(''ELCLASS'') should return ''WeightedMxPIn''.')
	end
	 
	% getBuild()
	assert(WeightedMxPIn.getBuild() == 1 && WeightedMxPIn.getBuild() > 0, ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'WeightedMxPIn.getBuild() should return the WeightedMxPIn build number.')
	assert(m.getBuild() == 1 && m.getBuild() > 0 , ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'm.getBuild() should return the WeightedMxPIn build number.')
	assert(Element.getBuild(m) == 1 && Element.getBuild(m) > 0, ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(m) should return the WeightedMxPIn build number.')
	assert(Element.getBuild('WeightedMxPIn') == 1 && Element.getBuild('WeightedMxPIn') > 0, ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''WeightedMxPIn'') should return the WeightedMxPIn build number.')
	 
	% getClass()
	assert(strcmp(WeightedMxPIn.getClass(), 'WeightedMxPIn'), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'WeightedMxPIn.getClass() should return ''WeightedMxPIn''.')
	assert(strcmp(m.getClass(), 'WeightedMxPIn'), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'm.getClass() should return ''WeightedMxPIn''.')
	assert(strcmp(Element.getClass(m), 'WeightedMxPIn'), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(m) should return ''WeightedMxPIn''.')
	assert(strcmp(Element.getClass('WeightedMxPIn'), 'WeightedMxPIn'), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''WeightedMxPIn'') should return ''WeightedMxPIn''.')
	 
	% getSubclasses()
	assert(isequal(WeightedMxPIn.getSubclasses(), subclasses('WeightedMxPIn', [], [], true)), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'WeightedMxPIn.getSubclasses() should return the same result as subclasses(''WeightedMxPIn'', [], [], true).')
	assert(isequal(m.getSubclasses(), subclasses('WeightedMxPIn', [], [], true)), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''WeightedMxPIn'', [], [], true).')
	assert(isequal(Element.getSubclasses(m), subclasses('WeightedMxPIn', [], [], true)), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(m) should return the same result as subclasses(''WeightedMxPIn'', [], [], true).')
	assert(isequal(Element.getSubclasses('WeightedMxPIn'), subclasses('WeightedMxPIn', [], [], true)), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''WeightedMxPIn'') should return the same result as subclasses(''WeightedMxPIn'', [], [], true).')
	 
	% getProps()
	assert(isempty(WeightedMxPIn.getProps()) || isequal(WeightedMxPIn.getProps(), 1:1:length(WeightedMxPIn.getProps())), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'WeightedMxPIn.getProps() should return a row vector [1:1:N].')
	assert(isempty(WeightedMxPIn.getProps()) || isequal(m.getProps(), 1:1:length(WeightedMxPIn.getProps())), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'm.getProps() should return a row vector [1:1:N].')
	assert(isempty(WeightedMxPIn.getProps()) || isequal(Element.getProps(m), 1:1:length(WeightedMxPIn.getProps())), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(m) should return a row vector [1:1:N].')
	assert(isempty(WeightedMxPIn.getProps()) || isequal(Element.getProps('WeightedMxPIn'), 1:1:length(WeightedMxPIn.getProps())), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''WeightedMxPIn'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) WeightedMxPIn.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(WeightedMxPIn.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(WeightedMxPIn.getProps())), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'WeightedMxPIn.getProps(category) does not work.')
	tmp = cellfun(@(category) m.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(WeightedMxPIn.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(WeightedMxPIn.getProps())), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'm.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(m, category), categories, 'UniformOutput', false);
	assert(isempty(WeightedMxPIn.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(WeightedMxPIn.getProps())), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(m, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('WeightedMxPIn', category), categories, 'UniformOutput', false);
	assert(isempty(WeightedMxPIn.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(WeightedMxPIn.getProps())), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''WeightedMxPIn'', category) does not work.')
	 
	% getPropNumber()
	assert(WeightedMxPIn.getPropNumber() == length(WeightedMxPIn.getProps()), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'WeightedMxPIn.getPropNumber() should return the number of properties.')
	assert(m.getPropNumber() == length(WeightedMxPIn.getProps()), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'm.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(m) == length(WeightedMxPIn.getProps()), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(m) should return the number of properties.')
	assert(Element.getPropNumber('WeightedMxPIn') == length(WeightedMxPIn.getProps()), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''WeightedMxPIn'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) WeightedMxPIn.getPropNumber(category), categories)) == WeightedMxPIn.getPropNumber(), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'WeightedMxPIn.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) m.getPropNumber(category), categories)) == WeightedMxPIn.getPropNumber(), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'm.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(m, category), categories)) == WeightedMxPIn.getPropNumber(), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(m, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('WeightedMxPIn', category), categories)) == WeightedMxPIn.getPropNumber(), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''WeightedMxPIn'', category) does not work.')
	 
	% existsProp(prop)
	assert(~WeightedMxPIn.existsProp(NaN), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'WeightedMxPIn.existsProp(prop) does not work.')
	assert(~m.existsProp(NaN), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'm.existsProp(prop) does not work.')
	assert(~Element.existsProp(m, NaN), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(m, prop) does not work.')
	assert(~Element.existsProp('WeightedMxPIn', NaN), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''WeightedMxPIn'', prop) does not work.')
	 
	assert_with_error('WeightedMxPIn.existsProp(NaN)', [BRAPH2.STR ':WeightedMxPIn:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':WeightedMxPIn:' BRAPH2.WRONG_INPUT], m)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':WeightedMxPIn:' BRAPH2.WRONG_INPUT], m)
	assert_with_error('Element.existsProp(''WeightedMxPIn'', NaN)', [BRAPH2.STR ':WeightedMxPIn:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:WeightedMxPIn.getPropNumber()
		assert(WeightedMxPIn.existsProp(prop), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'WeightedMxPIn.existsProp(prop) does not work.')
		assert(m.existsProp(prop), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'm.existsProp(prop) does not work.')
		assert(Element.existsProp(m, prop), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(m, prop) does not work.')
		assert(Element.existsProp('WeightedMxPIn', prop), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''WeightedMxPIn'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~WeightedMxPIn.existsTag(''), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'WeightedMxPIn.existsTag(tag) does not work.')
	assert(~m.existsTag(''), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'm.existsTag(tag) does not work.')
	assert(~Element.existsTag(m, ''), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(m, tag) does not work.')
	assert(~Element.existsTag('WeightedMxPIn', ''), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''WeightedMxPIn'', tag) does not work.')
	 
	assert_with_error('WeightedMxPIn.existsTag('''')', [BRAPH2.STR ':WeightedMxPIn:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':WeightedMxPIn:' BRAPH2.WRONG_INPUT], m)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':WeightedMxPIn:' BRAPH2.WRONG_INPUT], m)
	assert_with_error('Element.existsTag(''WeightedMxPIn'', '''')', [BRAPH2.STR ':WeightedMxPIn:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:WeightedMxPIn.getPropNumber()
		tag = m.getPropTag(prop);
		assert(WeightedMxPIn.existsTag(tag), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'WeightedMxPIn.existsTag(tag) does not work.')
		assert(m.existsTag(tag), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'm.existsTag(tag) does not work.')
		assert(Element.existsTag(m, tag), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(m, tga) does not work.')
		assert(Element.existsTag('WeightedMxPIn', tag), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''WeightedMxPIn'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:WeightedMxPIn.getPropNumber()
		assert(WeightedMxPIn.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'WeightedMxPIn.getPropProp(prop) does not work.')
		assert(m.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'm.getPropProp(prop) does not work.')
		assert(Element.getPropProp(m, prop) == prop, ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(m, prop) does not work.')
		assert(Element.getPropProp('WeightedMxPIn', prop) == prop, ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''WeightedMxPIn'', prop) does not work.')
	 
		tag = m.getPropTag(prop);
		assert(WeightedMxPIn.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'WeightedMxPIn.getPropProp(tag) does not work.')
		assert(m.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'm.getPropProp(tag) does not work.')
		assert(Element.getPropProp(m, tag) == prop, ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(m, tag) does not work.')
		assert(Element.getPropProp('WeightedMxPIn', prop) == prop, ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''WeightedMxPIn'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:WeightedMxPIn.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(strcmp(WeightedMxPIn.getPropTag(prop), tag), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'WeightedMxPIn.getPropTag(prop) does not work.')
		assert(strcmp(m.getPropTag(prop), tag), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'm.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(m, prop), tag), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(m, prop) does not work.')
		assert(strcmp(Element.getPropTag('WeightedMxPIn', prop), tag), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''WeightedMxPIn'', prop) does not work.')
	 
		assert(strcmp(WeightedMxPIn.getPropTag(tag), tag), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'WeightedMxPIn.getPropTag(tag) does not work.')
		assert(strcmp(m.getPropTag(tag), tag), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'm.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(m, tag), tag), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(m, tag) does not work.')
		assert(strcmp(Element.getPropTag('WeightedMxPIn', prop), tag), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''WeightedMxPIn'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:WeightedMxPIn.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(Category.existsCategory(WeightedMxPIn.getPropCategory(prop)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'WeightedMxPIn.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(m.getPropCategory(prop)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'm.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(m, prop)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(m, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(m, prop)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''WeightedMxPIn'', prop) does not work.')
	 
		assert(Category.existsCategory(WeightedMxPIn.getPropCategory(tag)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'WeightedMxPIn.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(m.getPropCategory(tag)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'm.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(m, tag)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(m, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(m, tag)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''WeightedMxPIn'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:WeightedMxPIn.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(Format.existsFormat(WeightedMxPIn.getPropFormat(prop)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'WeightedMxPIn.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(m.getPropFormat(prop)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'm.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(m, prop)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(m, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(m, prop)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''WeightedMxPIn'', prop) does not work.')
	 
		assert(Format.existsFormat(WeightedMxPIn.getPropFormat(tag)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'WeightedMxPIn.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(m.getPropFormat(tag)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'm.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(m, tag)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(m, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(m, tag)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''WeightedMxPIn'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:WeightedMxPIn.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(ischar(WeightedMxPIn.getPropDescription(prop)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'WeightedMxPIn.getPropDescription(prop) does not work.')
		assert(ischar(m.getPropDescription(prop)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'm.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(m, prop)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(m, prop) does not work.')
		assert(ischar(Element.getPropDescription(m, prop)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''WeightedMxPIn'', prop) does not work.')
	 
		assert(ischar(WeightedMxPIn.getPropDescription(tag)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'WeightedMxPIn.getPropDescription(tag) does not work.')
		assert(ischar(m.getPropDescription(tag)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'm.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(m, tag)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(m, tag) does not work.')
		assert(ischar(Element.getPropDescription(m, tag)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''WeightedMxPIn'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:WeightedMxPIn.getPropNumber()
		tag = m.getPropTag(prop);
	 
		settings = WeightedMxPIn.getPropSettings(prop);
		settings = m.getPropSettings(prop);
		settings = Element.getPropSettings(m, prop);
		settings = Element.getPropSettings('WeightedMxPIn', prop);
	 
		settings = WeightedMxPIn.getPropSettings(tag);
		settings = m.getPropSettings(tag);
		settings = Element.getPropSettings(m, tag);
		settings = Element.getPropSettings('WeightedMxPIn', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:WeightedMxPIn.getPropNumber()
		tag = m.getPropTag(prop);
	 
		default = WeightedMxPIn.getPropDefault(prop);
		default = m.getPropDefault(prop);
		default = Element.getPropDefault(m, prop);
		default = Element.getPropDefault('WeightedMxPIn', prop);
	 
		default = WeightedMxPIn.getPropDefault(tag);
		default = m.getPropDefault(tag);
		default = Element.getPropDefault(m, tag);
		default = Element.getPropDefault('WeightedMxPIn', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:WeightedMxPIn.getPropNumber()
		tag = m.getPropTag(prop);
	 
		conditioned_default = WeightedMxPIn.getPropDefaultConditioned(prop);
		conditioned_default = m.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(m, prop);
		conditioned_default = Element.getPropDefaultConditioned('WeightedMxPIn', prop);
	 
		conditioned_default = WeightedMxPIn.getPropDefaultConditioned(tag);
		conditioned_default = m.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(m, tag);
		conditioned_default = Element.getPropDefaultConditioned('WeightedMxPIn', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:WeightedMxPIn.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(~WeightedMxPIn.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'WeightedMxPIn.checkProp(prop, value) does not work.')
		assert(~m.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'm.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(m, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(m, prop, value) does not work.')
		assert(~Element.checkProp('WeightedMxPIn', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''WeightedMxPIn'', prop, value) does not work.')
	 
		assert_with_error('WeightedMxPIn.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':WeightedMxPIn:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':WeightedMxPIn:' BRAPH2.WRONG_INPUT], prop, m)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':WeightedMxPIn:' BRAPH2.WRONG_INPUT], prop, m)
		assert_with_error('Element.checkProp(''WeightedMxPIn'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':WeightedMxPIn:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~WeightedMxPIn.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'WeightedMxPIn.checkProp(tag, value) does not work.')
		assert(~m.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'm.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(m, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(m, tag, value) does not work.')
		assert(~Element.checkProp('WeightedMxPIn', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''WeightedMxPIn'', tag, value) does not work.')
	 
		assert_with_error('WeightedMxPIn.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':WeightedMxPIn:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':WeightedMxPIn:' BRAPH2.WRONG_INPUT], tag, m)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':WeightedMxPIn:' BRAPH2.WRONG_INPUT], tag, m)
		assert_with_error('Element.checkProp(''WeightedMxPIn'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':WeightedMxPIn:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(WeightedMxPIn.checkProp(prop, Element.getPropDefaultConditioned(WeightedMxPIn, prop)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'WeightedMxPIn.checkProp(prop, <conditioned default value>) does not work.')
		assert(m.checkProp(prop, Element.getPropDefaultConditioned(WeightedMxPIn, prop)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'm.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(m, prop, Element.getPropDefaultConditioned(WeightedMxPIn, prop)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(m, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('WeightedMxPIn', prop, Element.getPropDefaultConditioned(WeightedMxPIn, prop)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''WeightedMxPIn'', prop, <conditioned default value>) does not work.')
	 
		assert(WeightedMxPIn.checkProp(tag, Element.getPropDefaultConditioned(WeightedMxPIn, prop)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'WeightedMxPIn.checkProp(tag, <conditioned default value>) does not work.')
		assert(m.checkProp(tag, Element.getPropDefaultConditioned(WeightedMxPIn, prop)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'm.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(m, tag, Element.getPropDefaultConditioned(WeightedMxPIn, prop)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(m, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('WeightedMxPIn', tag, Element.getPropDefaultConditioned(WeightedMxPIn, prop)), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''WeightedMxPIn'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = WeightedMxPIn( ...
		WeightedMxPIn.ELCLASS, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.NAME, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.DESCRIPTION, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.TEMPLATE, WeightedMxPIn.getPropDefault(WeightedMxPIn.TEMPLATE), ...
		WeightedMxPIn.ID, WeightedMxPIn.getPropDefault(WeightedMxPIn.ID), ...
		WeightedMxPIn.LABEL, WeightedMxPIn.getPropDefault(WeightedMxPIn.LABEL), ...
		WeightedMxPIn.NOTES, WeightedMxPIn.getPropDefault(WeightedMxPIn.NOTES), ...
		WeightedMxPIn.TOSTRING, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.SHAPE, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.SCOPE, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.PARAMETRICITY, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.COMPATIBLE_GRAPHS, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.G, WeightedMxPIn.getPropDefault(WeightedMxPIn.G), ...
		WeightedMxPIn.M, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.PFM, WeightedMxPIn.getPropDefault(WeightedMxPIn.PFM) ...
		);
	 
	for prop = 1:1:WeightedMxPIn.getPropNumber()
	 
		% excluded props
		if any(prop == [WeightedMxPIn.PFM])
			continue
		end
	 
		TAG = upper(WeightedMxPIn.getPropTag(prop));
		switch WeightedMxPIn.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					m.getr(prop) == WeightedMxPIn.getNoValue(), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['Being a ' WeightedMxPIn.getCategoryName(WeightedMxPIn.getPropCategory(prop)) ', WeightedMxPIn.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in WeightedMxPIn.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					m.getr(TAG) == WeightedMxPIn.getNoValue(), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['Being a ' WeightedMxPIn.getCategoryName(WeightedMxPIn.getPropCategory(prop)) ', WeightedMxPIn.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in WeightedMxPIn.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(m.getPropSettings(prop))
					assert( ...
						m.checkFormat(m.getPropFormat(prop), m.get(prop)), ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						['WeightedMxPIn.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						m.checkFormat(m.getPropFormat(prop), m.get(prop), m.getPropSettings(prop)), ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						['WeightedMxPIn.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					m.getr(prop) == WeightedMxPIn.getNoValue(), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['Being a ' WeightedMxPIn.getCategoryName(WeightedMxPIn.getPropCategory(prop)) ', WeightedMxPIn.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in WeightedMxPIn.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					m.getr(TAG) == WeightedMxPIn.getNoValue(), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['Being a ' WeightedMxPIn.getCategoryName(WeightedMxPIn.getPropCategory(prop)) ', WeightedMxPIn.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in WeightedMxPIn.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':WeightedMxPIn']);
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(m.getPropSettings(prop))
					assert( ...
						m.checkFormat(m.getPropFormat(prop), m.get(prop)), ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						['WeightedMxPIn.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						m.checkFormat(m.getPropFormat(prop), m.get(prop), m.getPropSettings(prop)), ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						['WeightedMxPIn.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(m.getr(prop), WeightedMxPIn.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by WeightedMxPIn.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in WeightedMxPIn.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(m.getr(TAG), WeightedMxPIn.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.getr(' TAG ') must be inizialized to its default value ' ...
					'given by WeightedMxPIn.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in WeightedMxPIn.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = WeightedMxPIn( ...
		WeightedMxPIn.ELCLASS, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.NAME, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.DESCRIPTION, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.TEMPLATE, WeightedMxPIn.getPropDefault(WeightedMxPIn.TEMPLATE), ...
		WeightedMxPIn.ID, WeightedMxPIn.getPropDefault(WeightedMxPIn.ID), ...
		WeightedMxPIn.LABEL, WeightedMxPIn.getPropDefault(WeightedMxPIn.LABEL), ...
		WeightedMxPIn.NOTES, WeightedMxPIn.getPropDefault(WeightedMxPIn.NOTES), ...
		WeightedMxPIn.TOSTRING, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.SHAPE, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.SCOPE, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.PARAMETRICITY, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.COMPATIBLE_GRAPHS, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.G, WeightedMxPIn.getPropDefault(WeightedMxPIn.G), ...
		WeightedMxPIn.M, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.PFM, WeightedMxPIn.getPropDefault(WeightedMxPIn.PFM) ...
		);
	 
	for prop = 1:1:WeightedMxPIn.getPropNumber()
	 
		% excluded props
		if any(prop == [WeightedMxPIn.PFM])
			continue
		end
	 
		TAG = upper(WeightedMxPIn.getPropTag(prop));
		switch WeightedMxPIn.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(m.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					m.checkFormat(m.getPropFormat(prop), m.getr(prop),m.getPropSettings(prop)), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':WeightedMxPIn']);
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':WeightedMxPIn']);
	% 			assert( ...
	% 				~isa(m.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
	% 				['WeightedMxPIn.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(m.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
	% 				['WeightedMxPIn.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				m.checkFormat(m.getPropFormat(prop), m.getr(prop),m.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
	% 				['WeightedMxPIn.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':WeightedMxPIn']);
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(m.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					m.checkFormat(m.getPropFormat(prop), m.getr(prop),m.getPropSettings(prop)), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if m.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:WeightedMxPIn');
					delete(ancestor(m.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(WeightedMxPIn.getProps(Category.RESULT))
		for prop = 1:1:WeightedMxPIn.getPropNumber()
	 
			% excluded props
			if any(prop == [WeightedMxPIn.PFM])
				continue
			end
	 
			switch WeightedMxPIn.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						m.isLocked(prop), ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						['WeightedMxPIn.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~m.isLocked(prop), ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						['WeightedMxPIn.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = WeightedMxPIn();
	 
	for prop = 1:1:WeightedMxPIn.getPropNumber()
		TAG = upper(WeightedMxPIn.getPropTag(prop));
		assert( ...
			~m.isLocked(prop), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			['WeightedMxPIn.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~m.isLocked(TAG), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			['WeightedMxPIn.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	m.lock()
	 
	for prop = 1:1:WeightedMxPIn.getPropNumber()
		switch WeightedMxPIn.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					m.isLocked(prop), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~m.isLocked(prop), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = WeightedMxPIn();
	 
	warning_backup = warning('off', 'BRAPH2:WeightedMxPIn');
	for prop = 1:1:WeightedMxPIn.getPropNumber()
		m.lock(prop)
		switch WeightedMxPIn.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					m.isLocked(prop), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~m.isLocked(prop), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = WeightedMxPIn();
	 
	for prop = 1:1:WeightedMxPIn.getPropNumber()
		TAG = upper(WeightedMxPIn.getPropTag(prop));
		assert( ...
			m.isChecked(prop), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			['WeightedMxPIn.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			m.isChecked(TAG), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			['WeightedMxPIn.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	m.unchecked()
	 
	for prop = 1:1:WeightedMxPIn.getPropNumber()
		assert( ...
			~m.isChecked(prop), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			['WeightedMxPIn.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	m.checked()
	 
	for prop = 1:1:WeightedMxPIn.getPropNumber()
		assert( ...
			m.isChecked(prop), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			['WeightedMxPIn.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic WeightedMxPIn
	m_0 = WeightedMxPIn( ...
		WeightedMxPIn.ELCLASS, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.NAME, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.DESCRIPTION, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.TEMPLATE, WeightedMxPIn.getPropDefault(WeightedMxPIn.TEMPLATE), ...
		WeightedMxPIn.ID, WeightedMxPIn.getPropDefault(WeightedMxPIn.ID), ...
		WeightedMxPIn.LABEL, WeightedMxPIn.getPropDefault(WeightedMxPIn.LABEL), ...
		WeightedMxPIn.NOTES, WeightedMxPIn.getPropDefault(WeightedMxPIn.NOTES), ...
		WeightedMxPIn.TOSTRING, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.SHAPE, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.SCOPE, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.PARAMETRICITY, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.COMPATIBLE_GRAPHS, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.G, WeightedMxPIn.getPropDefault(WeightedMxPIn.G), ...
		WeightedMxPIn.M, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.PFM, WeightedMxPIn.getPropDefault(WeightedMxPIn.PFM) ...
		);
	 
	% WeightedMxPIn with 1st callbacks
	m_1 = WeightedMxPIn( ...
		WeightedMxPIn.ELCLASS, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.NAME, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.DESCRIPTION, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.TEMPLATE, m_0.getCallback(4), ..., ...
		WeightedMxPIn.ID, m_0.getCallback(5), ..., ...
		WeightedMxPIn.LABEL, WeightedMxPIn.getPropDefault(WeightedMxPIn.LABEL), ...
		WeightedMxPIn.NOTES, WeightedMxPIn.getPropDefault(WeightedMxPIn.NOTES), ...
		WeightedMxPIn.TOSTRING, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.SHAPE, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.SCOPE, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.PARAMETRICITY, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.COMPATIBLE_GRAPHS, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.G, m_0.getCallback(13), ..., ...
		WeightedMxPIn.M, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.PFM, m_0.getCallback(15) ... ...
		);
	 
	prop_number = WeightedMxPIn.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(WeightedMxPIn.getPropTag(prop));
		switch WeightedMxPIn.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(m_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(m_1.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(m_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% WeightedMxPIn with 2nd callbacks
	m_2 = WeightedMxPIn( ...
		WeightedMxPIn.ELCLASS, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.NAME, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.DESCRIPTION, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.TEMPLATE, m_1.getCallback(4), ..., ...
		WeightedMxPIn.ID, m_1.getCallback(5), ..., ...
		WeightedMxPIn.LABEL, WeightedMxPIn.getPropDefault(WeightedMxPIn.LABEL), ...
		WeightedMxPIn.NOTES, WeightedMxPIn.getPropDefault(WeightedMxPIn.NOTES), ...
		WeightedMxPIn.TOSTRING, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.SHAPE, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.SCOPE, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.PARAMETRICITY, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.COMPATIBLE_GRAPHS, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.G, m_1.getCallback(13), ..., ...
		WeightedMxPIn.M, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.PFM, m_1.getCallback(15) ... ...
		);
	 
	prop_number = WeightedMxPIn.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(WeightedMxPIn.getPropTag(prop));
		switch WeightedMxPIn.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(m_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(m_2.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(m_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% WeightedMxPIn with 3rd callbacks
	m_3 = WeightedMxPIn( ...
		WeightedMxPIn.ELCLASS, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.NAME, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.DESCRIPTION, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.TEMPLATE, m_2.getCallback(4), ..., ...
		WeightedMxPIn.ID, m_2.getCallback(5), ..., ...
		WeightedMxPIn.LABEL, WeightedMxPIn.getPropDefault(WeightedMxPIn.LABEL), ...
		WeightedMxPIn.NOTES, WeightedMxPIn.getPropDefault(WeightedMxPIn.NOTES), ...
		WeightedMxPIn.TOSTRING, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.SHAPE, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.SCOPE, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.PARAMETRICITY, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.COMPATIBLE_GRAPHS, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.G, m_2.getCallback(13), ..., ...
		WeightedMxPIn.M, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.PFM, m_2.getCallback(15) ... ...
		);
	 
	prop_number = WeightedMxPIn.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(WeightedMxPIn.getPropTag(prop));
		switch WeightedMxPIn.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(m_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(m_3.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(m_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	m = WeightedMxPIn();
	 
	m_copy = m.copy();
	 
	assert(m_copy ~= m, ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'WeightedMxPIn.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(m_copy, m), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'WeightedMxPIn.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:WeightedMxPIn.getPropNumber()
		value = m.getr(prop);
		value_copy = m_copy.getr(prop);
		switch WeightedMxPIn.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					'WeightedMxPIn.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						'WeightedMxPIn.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						'WeightedMxPIn.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						'WeightedMxPIn.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
							'WeightedMxPIn.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
							'WeightedMxPIn.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						'WeightedMxPIn.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					m_copy.isLocked(prop) == m.isLocked(prop), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					'WeightedMxPIn.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					m_copy.isChecked(prop) == m.isChecked(prop), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					'WeightedMxPIn.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					m_copy.getPropSeed(prop) == m.getPropSeed(prop), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					'WeightedMxPIn.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	m = WeightedMxPIn( ...
		WeightedMxPIn.ELCLASS, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.NAME, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.DESCRIPTION, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.TEMPLATE, WeightedMxPIn.getPropDefault(WeightedMxPIn.TEMPLATE), ...
		WeightedMxPIn.ID, WeightedMxPIn.getPropDefault(WeightedMxPIn.ID), ...
		WeightedMxPIn.LABEL, WeightedMxPIn.getPropDefault(WeightedMxPIn.LABEL), ...
		WeightedMxPIn.NOTES, WeightedMxPIn.getPropDefault(WeightedMxPIn.NOTES), ...
		WeightedMxPIn.TOSTRING, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.SHAPE, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.SCOPE, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.PARAMETRICITY, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.COMPATIBLE_GRAPHS, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.G, WeightedMxPIn.getPropDefault(WeightedMxPIn.G), ...
		WeightedMxPIn.M, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.PFM, WeightedMxPIn.getPropDefault(WeightedMxPIn.PFM) ...
		);
	 
	for prop = 1:1:WeightedMxPIn.getPropNumber()
		if WeightedMxPIn.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':WeightedMxPIn']);
			% m.memorize(prop);
			% warning(warning_backup)
		elseif WeightedMxPIn.getPropCategory(prop) == Category.EVANESCENT && m.getPropFormat(prop) == Format.HANDLE
			m.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:WeightedMxPIn');
			delete(ancestor(m.get(prop), 'figure'))
			warning(warning_backup)
		else
			m.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	m_copy = m.copy();
	 
	for prop = 1:1:WeightedMxPIn.getPropNumber()
		value = m.getr(prop);
		value_copy = m_copy.getr(prop);
		switch WeightedMxPIn.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					'WeightedMxPIn.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						'WeightedMxPIn.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						'WeightedMxPIn.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						'WeightedMxPIn.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
							'WeightedMxPIn.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
							'WeightedMxPIn.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						'WeightedMxPIn.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						m_copy.isLocked(prop) == m.isLocked(prop), ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						'WeightedMxPIn.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						m_copy.isChecked(prop) == m.isChecked(prop), ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						'WeightedMxPIn.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						m_copy.getPropSeed(prop) == m.getPropSeed(prop), ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						'WeightedMxPIn.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	m_0 = WeightedMxPIn( ...
		WeightedMxPIn.ELCLASS, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.NAME, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.DESCRIPTION, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.TEMPLATE, WeightedMxPIn.getPropDefault(WeightedMxPIn.TEMPLATE), ...
		WeightedMxPIn.ID, WeightedMxPIn.getPropDefault(WeightedMxPIn.ID), ...
		WeightedMxPIn.LABEL, WeightedMxPIn.getPropDefault(WeightedMxPIn.LABEL), ...
		WeightedMxPIn.NOTES, WeightedMxPIn.getPropDefault(WeightedMxPIn.NOTES), ...
		WeightedMxPIn.TOSTRING, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.SHAPE, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.SCOPE, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.PARAMETRICITY, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.COMPATIBLE_GRAPHS, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.G, WeightedMxPIn.getPropDefault(WeightedMxPIn.G), ...
		WeightedMxPIn.M, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.PFM, WeightedMxPIn.getPropDefault(WeightedMxPIn.PFM) ...
		);
	 
	m = WeightedMxPIn( ...
		WeightedMxPIn.ELCLASS, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.NAME, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.DESCRIPTION, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.TEMPLATE, m_0.getCallback(4), ..., ...
		WeightedMxPIn.ID, m_0.getCallback(5), ..., ...
		WeightedMxPIn.LABEL, WeightedMxPIn.getPropDefault(WeightedMxPIn.LABEL), ...
		WeightedMxPIn.NOTES, WeightedMxPIn.getPropDefault(WeightedMxPIn.NOTES), ...
		WeightedMxPIn.TOSTRING, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.SHAPE, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.SCOPE, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.PARAMETRICITY, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.COMPATIBLE_GRAPHS, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.G, m_0.getCallback(13), ..., ...
		WeightedMxPIn.M, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.PFM, m_0.getCallback(15) ... ...
		);
	 
	m_copy = m.copy();
	m_0_copy = m_copy.getr('ID').get('EL');
	 
	for prop = 1:1:WeightedMxPIn.getPropNumber()
		value = m.getr(prop);
		value_copy = m_copy.getr(prop);
		switch WeightedMxPIn.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					'WeightedMxPIn.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						'WeightedMxPIn.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						'WeightedMxPIn.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						'WeightedMxPIn.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
							'WeightedMxPIn.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
							'WeightedMxPIn.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						'WeightedMxPIn.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == m_0.getCallback(prop), ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						'WeightedMxPIn.copy() does not work. The callback should be obtained from WeightedMxPIn.getCallback().' ...
						)
					assert( ...
						value_copy == m_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						'WeightedMxPIn.copy() does not work. The callback should be obtained from WeightedMxPIn.getCallback().' ...
						)
				end
	 
					assert( ...
						m_copy.isLocked(prop) == m.isLocked(prop), ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						'WeightedMxPIn.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						m_copy.isChecked(prop) == m.isChecked(prop), ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						'WeightedMxPIn.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						m_copy.getPropSeed(prop) == m.getPropSeed(prop), ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						'WeightedMxPIn.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m_template = WeightedMxPIn();
	m = WeightedMxPIn('TEMPLATE', m_template);
	 
	for prop = 1:1:WeightedMxPIn.getPropNumber()
	 
		% excluded props
		if any(prop == [WeightedMxPIn.PFM])
			continue
		end
	 
		TAG = upper(WeightedMxPIn.getPropTag(prop));
		switch WeightedMxPIn.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == WeightedMxPIn.TEMPLATE
					assert( ...
						isa(m.getr(prop), 'WeightedMxPIn'), ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						'WeightedMxPIn TEMPLATE does not work. WeightedMxPIn.getr(''TEMPLATE'') should be a WeightedMxPIn element.' ...
						)
					assert( ...
						isa(m_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						'WeightedMxPIn TEMPLATE does not work. WeightedMxPIn_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(m.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						['WeightedMxPIn TEMPLATE does not work. WeightedMxPIn.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						m.getr(prop).get('EL') == m_template && m.getr(prop).get('PROP') == prop && strcmp(m.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						['WeightedMxPIn TEMPLATE does not work. WeightedMxPIn.getr(' TAG ') should be a Callback to m_template.' TAG '.'] ...
						)
					assert( ...
						isa(m_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
						['WeightedMxPIn TEMPLATE does not work. WeightedMxPIn_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn TEMPLATE does not work. WeightedMxPIn.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(m_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
					['WeightedMxPIn TEMPLATE does not work. WeightedMxPIn_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = WeightedMxPIn( ...
		WeightedMxPIn.ELCLASS, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.NAME, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.DESCRIPTION, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.TEMPLATE, WeightedMxPIn.getPropDefault(WeightedMxPIn.TEMPLATE), ...
		WeightedMxPIn.ID, WeightedMxPIn.getPropDefault(WeightedMxPIn.ID), ...
		WeightedMxPIn.LABEL, WeightedMxPIn.getPropDefault(WeightedMxPIn.LABEL), ...
		WeightedMxPIn.NOTES, WeightedMxPIn.getPropDefault(WeightedMxPIn.NOTES), ...
		WeightedMxPIn.TOSTRING, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.SHAPE, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.SCOPE, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.PARAMETRICITY, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.COMPATIBLE_GRAPHS, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.G, WeightedMxPIn.getPropDefault(WeightedMxPIn.G), ...
		WeightedMxPIn.M, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.PFM, WeightedMxPIn.getPropDefault(WeightedMxPIn.PFM) ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'weightedmxpin_to_be_erased.b2'];
	 
	Element.save(m, filename)
	 
	m_loaded = Element.load(filename);
	 
	assert( ...
		isequal(m.copy(), m_loaded), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'WeightedMxPIn.save(m) and/or WeightedMxPIn.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = WeightedMxPIn( ...
		WeightedMxPIn.ELCLASS, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.NAME, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.DESCRIPTION, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.TEMPLATE, WeightedMxPIn.getPropDefault(WeightedMxPIn.TEMPLATE), ...
		WeightedMxPIn.ID, WeightedMxPIn.getPropDefault(WeightedMxPIn.ID), ...
		WeightedMxPIn.LABEL, WeightedMxPIn.getPropDefault(WeightedMxPIn.LABEL), ...
		WeightedMxPIn.NOTES, WeightedMxPIn.getPropDefault(WeightedMxPIn.NOTES), ...
		WeightedMxPIn.TOSTRING, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.SHAPE, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.SCOPE, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.PARAMETRICITY, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.COMPATIBLE_GRAPHS, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.G, WeightedMxPIn.getPropDefault(WeightedMxPIn.G), ...
		WeightedMxPIn.M, WeightedMxPIn.getNoValue(), ...
		WeightedMxPIn.PFM, WeightedMxPIn.getPropDefault(WeightedMxPIn.PFM) ...
		);
	 
	[json, struct, el_list] = encodeJSON(m);
	[m_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(m_dec ~= m, ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		'WeightedMxPIn.encodeJSON() or WeightedMxPIn.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) WeightedMxPIn.getPropFormat(prop), num2cell(WeightedMxPIn.getProps())) == Format.HANDLE) && all(cellfun(@(prop) WeightedMxPIn.getPropFormat(prop), num2cell(WeightedMxPIn.getProps())) == Format.NET)
		assert(isequal(m_dec, m), ...
			[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
			'WeightedMxPIn.encodeJSON() or WeightedMxPIn.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: MultiplexWD
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	B11 = [
	    0   .5  1
	    .5  0   0
	    1   0   0
	    ];
	B22 = [
	    0   1   0
	    1   0   0
	    0   .5  0
	    ];
	B = {B11  B22};
	
	known_weighted_multiplex_in_participation = {[24/25 3/4 0]'};
	
	g = MultiplexWD('B', B);
	m_outside_g = WeightedMxPIn('G', g);
	
	assert(isequal(m_outside_g.get('M'), known_weighted_multiplex_in_participation), ...
	    [BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
	    [class(m_outside_g) ' is not being calculated correctly for ' class(g) '.'])
	
	m_inside_g = g.get('MEASURE', 'WeightedMxPIn');
	assert(isequal(m_inside_g.get('M'), known_weighted_multiplex_in_participation), ...
	    [BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
	    [class(m_inside_g) ' is not being calculated correctly for ' class(g) '.'])
end

%% Test 13: OrdMxWD
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	B11 = [
	    0   .5  1
	    .5  0   0
	    1   0   0
	    ];
	B22 = [
	    0   1   0
	    1   0   0
	    0   .5  0
	    ];
	B = {B11  B22};
	
	known_weighted_multiplex_in_participation = {[24/25 3/4 0]'};
	
	g = OrdMxWD('B', B);
	m_outside_g = WeightedMxPIn('G', g);
	
	assert(isequal(m_outside_g.get('M'), known_weighted_multiplex_in_participation), ...
	    [BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
	    [class(m_outside_g) ' is not being calculated correctly for ' class(g) '.'])
	
	m_inside_g = g.get('MEASURE', 'WeightedMxPIn');
	assert(isequal(m_inside_g.get('M'), known_weighted_multiplex_in_participation), ...
	    [BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
	    [class(m_inside_g) ' is not being calculated correctly for ' class(g) '.'])
end

%% Test 14: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':WeightedMxPIn:' BRAPH2.FAIL_TEST], ...
		[' When testing WeightedMxPIn no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 15: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

