%TEST_KCORENESSCENTRALITY

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	m = KCorenessCentrality();
	 
	% get('ELCLASS')
	if isa(KCorenessCentrality, 'ConcreteElement')
		assert(strcmp(KCorenessCentrality().get('ELCLASS'), 'KCorenessCentrality'), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'KCorenessCentrality().get(''ELCLASS'') should return ''KCorenessCentrality''.')
	end
	 
	% getBuild()
	assert(KCorenessCentrality.getBuild() == 1 && KCorenessCentrality.getBuild() > 0, ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'KCorenessCentrality.getBuild() should return the KCorenessCentrality build number.')
	assert(m.getBuild() == 1 && m.getBuild() > 0 , ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'm.getBuild() should return the KCorenessCentrality build number.')
	assert(Element.getBuild(m) == 1 && Element.getBuild(m) > 0, ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(m) should return the KCorenessCentrality build number.')
	assert(Element.getBuild('KCorenessCentrality') == 1 && Element.getBuild('KCorenessCentrality') > 0, ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''KCorenessCentrality'') should return the KCorenessCentrality build number.')
	 
	% getClass()
	assert(strcmp(KCorenessCentrality.getClass(), 'KCorenessCentrality'), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'KCorenessCentrality.getClass() should return ''KCorenessCentrality''.')
	assert(strcmp(m.getClass(), 'KCorenessCentrality'), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'm.getClass() should return ''KCorenessCentrality''.')
	assert(strcmp(Element.getClass(m), 'KCorenessCentrality'), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(m) should return ''KCorenessCentrality''.')
	assert(strcmp(Element.getClass('KCorenessCentrality'), 'KCorenessCentrality'), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''KCorenessCentrality'') should return ''KCorenessCentrality''.')
	 
	% getSubclasses()
	assert(isequal(KCorenessCentrality.getSubclasses(), subclasses('KCorenessCentrality', [], [], true)), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'KCorenessCentrality.getSubclasses() should return the same result as subclasses(''KCorenessCentrality'', [], [], true).')
	assert(isequal(m.getSubclasses(), subclasses('KCorenessCentrality', [], [], true)), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''KCorenessCentrality'', [], [], true).')
	assert(isequal(Element.getSubclasses(m), subclasses('KCorenessCentrality', [], [], true)), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(m) should return the same result as subclasses(''KCorenessCentrality'', [], [], true).')
	assert(isequal(Element.getSubclasses('KCorenessCentrality'), subclasses('KCorenessCentrality', [], [], true)), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''KCorenessCentrality'') should return the same result as subclasses(''KCorenessCentrality'', [], [], true).')
	 
	% getProps()
	assert(isempty(KCorenessCentrality.getProps()) || isequal(KCorenessCentrality.getProps(), 1:1:length(KCorenessCentrality.getProps())), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'KCorenessCentrality.getProps() should return a row vector [1:1:N].')
	assert(isempty(KCorenessCentrality.getProps()) || isequal(m.getProps(), 1:1:length(KCorenessCentrality.getProps())), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'm.getProps() should return a row vector [1:1:N].')
	assert(isempty(KCorenessCentrality.getProps()) || isequal(Element.getProps(m), 1:1:length(KCorenessCentrality.getProps())), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(m) should return a row vector [1:1:N].')
	assert(isempty(KCorenessCentrality.getProps()) || isequal(Element.getProps('KCorenessCentrality'), 1:1:length(KCorenessCentrality.getProps())), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''KCorenessCentrality'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) KCorenessCentrality.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(KCorenessCentrality.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(KCorenessCentrality.getProps())), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'KCorenessCentrality.getProps(category) does not work.')
	tmp = cellfun(@(category) m.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(KCorenessCentrality.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(KCorenessCentrality.getProps())), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'm.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(m, category), categories, 'UniformOutput', false);
	assert(isempty(KCorenessCentrality.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(KCorenessCentrality.getProps())), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(m, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('KCorenessCentrality', category), categories, 'UniformOutput', false);
	assert(isempty(KCorenessCentrality.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(KCorenessCentrality.getProps())), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''KCorenessCentrality'', category) does not work.')
	 
	% getPropNumber()
	assert(KCorenessCentrality.getPropNumber() == length(KCorenessCentrality.getProps()), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'KCorenessCentrality.getPropNumber() should return the number of properties.')
	assert(m.getPropNumber() == length(KCorenessCentrality.getProps()), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'm.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(m) == length(KCorenessCentrality.getProps()), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(m) should return the number of properties.')
	assert(Element.getPropNumber('KCorenessCentrality') == length(KCorenessCentrality.getProps()), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''KCorenessCentrality'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) KCorenessCentrality.getPropNumber(category), categories)) == KCorenessCentrality.getPropNumber(), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'KCorenessCentrality.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) m.getPropNumber(category), categories)) == KCorenessCentrality.getPropNumber(), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'm.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(m, category), categories)) == KCorenessCentrality.getPropNumber(), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(m, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('KCorenessCentrality', category), categories)) == KCorenessCentrality.getPropNumber(), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''KCorenessCentrality'', category) does not work.')
	 
	% existsProp(prop)
	assert(~KCorenessCentrality.existsProp(NaN), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'KCorenessCentrality.existsProp(prop) does not work.')
	assert(~m.existsProp(NaN), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'm.existsProp(prop) does not work.')
	assert(~Element.existsProp(m, NaN), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(m, prop) does not work.')
	assert(~Element.existsProp('KCorenessCentrality', NaN), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''KCorenessCentrality'', prop) does not work.')
	 
	assert_with_error('KCorenessCentrality.existsProp(NaN)', [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.WRONG_INPUT], m)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.WRONG_INPUT], m)
	assert_with_error('Element.existsProp(''KCorenessCentrality'', NaN)', [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:KCorenessCentrality.getPropNumber()
		assert(KCorenessCentrality.existsProp(prop), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'KCorenessCentrality.existsProp(prop) does not work.')
		assert(m.existsProp(prop), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'm.existsProp(prop) does not work.')
		assert(Element.existsProp(m, prop), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(m, prop) does not work.')
		assert(Element.existsProp('KCorenessCentrality', prop), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''KCorenessCentrality'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~KCorenessCentrality.existsTag(''), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'KCorenessCentrality.existsTag(tag) does not work.')
	assert(~m.existsTag(''), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'm.existsTag(tag) does not work.')
	assert(~Element.existsTag(m, ''), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(m, tag) does not work.')
	assert(~Element.existsTag('KCorenessCentrality', ''), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''KCorenessCentrality'', tag) does not work.')
	 
	assert_with_error('KCorenessCentrality.existsTag('''')', [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.WRONG_INPUT], m)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.WRONG_INPUT], m)
	assert_with_error('Element.existsTag(''KCorenessCentrality'', '''')', [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:KCorenessCentrality.getPropNumber()
		tag = m.getPropTag(prop);
		assert(KCorenessCentrality.existsTag(tag), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'KCorenessCentrality.existsTag(tag) does not work.')
		assert(m.existsTag(tag), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'm.existsTag(tag) does not work.')
		assert(Element.existsTag(m, tag), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(m, tga) does not work.')
		assert(Element.existsTag('KCorenessCentrality', tag), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''KCorenessCentrality'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:KCorenessCentrality.getPropNumber()
		assert(KCorenessCentrality.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'KCorenessCentrality.getPropProp(prop) does not work.')
		assert(m.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'm.getPropProp(prop) does not work.')
		assert(Element.getPropProp(m, prop) == prop, ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(m, prop) does not work.')
		assert(Element.getPropProp('KCorenessCentrality', prop) == prop, ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''KCorenessCentrality'', prop) does not work.')
	 
		tag = m.getPropTag(prop);
		assert(KCorenessCentrality.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'KCorenessCentrality.getPropProp(tag) does not work.')
		assert(m.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'm.getPropProp(tag) does not work.')
		assert(Element.getPropProp(m, tag) == prop, ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(m, tag) does not work.')
		assert(Element.getPropProp('KCorenessCentrality', prop) == prop, ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''KCorenessCentrality'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:KCorenessCentrality.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(strcmp(KCorenessCentrality.getPropTag(prop), tag), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'KCorenessCentrality.getPropTag(prop) does not work.')
		assert(strcmp(m.getPropTag(prop), tag), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'm.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(m, prop), tag), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(m, prop) does not work.')
		assert(strcmp(Element.getPropTag('KCorenessCentrality', prop), tag), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''KCorenessCentrality'', prop) does not work.')
	 
		assert(strcmp(KCorenessCentrality.getPropTag(tag), tag), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'KCorenessCentrality.getPropTag(tag) does not work.')
		assert(strcmp(m.getPropTag(tag), tag), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'm.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(m, tag), tag), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(m, tag) does not work.')
		assert(strcmp(Element.getPropTag('KCorenessCentrality', prop), tag), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''KCorenessCentrality'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:KCorenessCentrality.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(Category.existsCategory(KCorenessCentrality.getPropCategory(prop)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'KCorenessCentrality.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(m.getPropCategory(prop)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'm.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(m, prop)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(m, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(m, prop)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''KCorenessCentrality'', prop) does not work.')
	 
		assert(Category.existsCategory(KCorenessCentrality.getPropCategory(tag)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'KCorenessCentrality.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(m.getPropCategory(tag)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'm.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(m, tag)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(m, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(m, tag)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''KCorenessCentrality'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:KCorenessCentrality.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(Format.existsFormat(KCorenessCentrality.getPropFormat(prop)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'KCorenessCentrality.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(m.getPropFormat(prop)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'm.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(m, prop)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(m, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(m, prop)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''KCorenessCentrality'', prop) does not work.')
	 
		assert(Format.existsFormat(KCorenessCentrality.getPropFormat(tag)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'KCorenessCentrality.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(m.getPropFormat(tag)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'm.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(m, tag)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(m, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(m, tag)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''KCorenessCentrality'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:KCorenessCentrality.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(ischar(KCorenessCentrality.getPropDescription(prop)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'KCorenessCentrality.getPropDescription(prop) does not work.')
		assert(ischar(m.getPropDescription(prop)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'm.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(m, prop)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(m, prop) does not work.')
		assert(ischar(Element.getPropDescription(m, prop)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''KCorenessCentrality'', prop) does not work.')
	 
		assert(ischar(KCorenessCentrality.getPropDescription(tag)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'KCorenessCentrality.getPropDescription(tag) does not work.')
		assert(ischar(m.getPropDescription(tag)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'm.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(m, tag)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(m, tag) does not work.')
		assert(ischar(Element.getPropDescription(m, tag)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''KCorenessCentrality'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:KCorenessCentrality.getPropNumber()
		tag = m.getPropTag(prop);
	 
		settings = KCorenessCentrality.getPropSettings(prop);
		settings = m.getPropSettings(prop);
		settings = Element.getPropSettings(m, prop);
		settings = Element.getPropSettings('KCorenessCentrality', prop);
	 
		settings = KCorenessCentrality.getPropSettings(tag);
		settings = m.getPropSettings(tag);
		settings = Element.getPropSettings(m, tag);
		settings = Element.getPropSettings('KCorenessCentrality', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:KCorenessCentrality.getPropNumber()
		tag = m.getPropTag(prop);
	 
		default = KCorenessCentrality.getPropDefault(prop);
		default = m.getPropDefault(prop);
		default = Element.getPropDefault(m, prop);
		default = Element.getPropDefault('KCorenessCentrality', prop);
	 
		default = KCorenessCentrality.getPropDefault(tag);
		default = m.getPropDefault(tag);
		default = Element.getPropDefault(m, tag);
		default = Element.getPropDefault('KCorenessCentrality', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:KCorenessCentrality.getPropNumber()
		tag = m.getPropTag(prop);
	 
		conditioned_default = KCorenessCentrality.getPropDefaultConditioned(prop);
		conditioned_default = m.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(m, prop);
		conditioned_default = Element.getPropDefaultConditioned('KCorenessCentrality', prop);
	 
		conditioned_default = KCorenessCentrality.getPropDefaultConditioned(tag);
		conditioned_default = m.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(m, tag);
		conditioned_default = Element.getPropDefaultConditioned('KCorenessCentrality', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:KCorenessCentrality.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(~KCorenessCentrality.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'KCorenessCentrality.checkProp(prop, value) does not work.')
		assert(~m.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'm.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(m, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(m, prop, value) does not work.')
		assert(~Element.checkProp('KCorenessCentrality', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''KCorenessCentrality'', prop, value) does not work.')
	 
		assert_with_error('KCorenessCentrality.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.WRONG_INPUT], prop, m)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.WRONG_INPUT], prop, m)
		assert_with_error('Element.checkProp(''KCorenessCentrality'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~KCorenessCentrality.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'KCorenessCentrality.checkProp(tag, value) does not work.')
		assert(~m.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'm.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(m, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(m, tag, value) does not work.')
		assert(~Element.checkProp('KCorenessCentrality', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''KCorenessCentrality'', tag, value) does not work.')
	 
		assert_with_error('KCorenessCentrality.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.WRONG_INPUT], tag, m)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.WRONG_INPUT], tag, m)
		assert_with_error('Element.checkProp(''KCorenessCentrality'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(KCorenessCentrality.checkProp(prop, Element.getPropDefaultConditioned(KCorenessCentrality, prop)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'KCorenessCentrality.checkProp(prop, <conditioned default value>) does not work.')
		assert(m.checkProp(prop, Element.getPropDefaultConditioned(KCorenessCentrality, prop)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'm.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(m, prop, Element.getPropDefaultConditioned(KCorenessCentrality, prop)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(m, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('KCorenessCentrality', prop, Element.getPropDefaultConditioned(KCorenessCentrality, prop)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''KCorenessCentrality'', prop, <conditioned default value>) does not work.')
	 
		assert(KCorenessCentrality.checkProp(tag, Element.getPropDefaultConditioned(KCorenessCentrality, prop)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'KCorenessCentrality.checkProp(tag, <conditioned default value>) does not work.')
		assert(m.checkProp(tag, Element.getPropDefaultConditioned(KCorenessCentrality, prop)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'm.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(m, tag, Element.getPropDefaultConditioned(KCorenessCentrality, prop)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(m, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('KCorenessCentrality', tag, Element.getPropDefaultConditioned(KCorenessCentrality, prop)), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''KCorenessCentrality'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = KCorenessCentrality( ...
		KCorenessCentrality.ELCLASS, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.NAME, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.DESCRIPTION, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.TEMPLATE, KCorenessCentrality.getPropDefault(KCorenessCentrality.TEMPLATE), ...
		KCorenessCentrality.ID, KCorenessCentrality.getPropDefault(KCorenessCentrality.ID), ...
		KCorenessCentrality.LABEL, KCorenessCentrality.getPropDefault(KCorenessCentrality.LABEL), ...
		KCorenessCentrality.NOTES, KCorenessCentrality.getPropDefault(KCorenessCentrality.NOTES), ...
		KCorenessCentrality.TOSTRING, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.SHAPE, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.SCOPE, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.PARAMETRICITY, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.COMPATIBLE_GRAPHS, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.G, KCorenessCentrality.getPropDefault(KCorenessCentrality.G), ...
		KCorenessCentrality.M, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.PFM, KCorenessCentrality.getPropDefault(KCorenessCentrality.PFM) ...
		);
	 
	for prop = 1:1:KCorenessCentrality.getPropNumber()
	 
		% excluded props
		if any(prop == [KCorenessCentrality.PFM])
			continue
		end
	 
		TAG = upper(KCorenessCentrality.getPropTag(prop));
		switch KCorenessCentrality.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					m.getr(prop) == KCorenessCentrality.getNoValue(), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['Being a ' KCorenessCentrality.getCategoryName(KCorenessCentrality.getPropCategory(prop)) ', KCorenessCentrality.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in KCorenessCentrality.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					m.getr(TAG) == KCorenessCentrality.getNoValue(), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['Being a ' KCorenessCentrality.getCategoryName(KCorenessCentrality.getPropCategory(prop)) ', KCorenessCentrality.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in KCorenessCentrality.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(m.getPropSettings(prop))
					assert( ...
						m.checkFormat(m.getPropFormat(prop), m.get(prop)), ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						['KCorenessCentrality.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						m.checkFormat(m.getPropFormat(prop), m.get(prop), m.getPropSettings(prop)), ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						['KCorenessCentrality.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					m.getr(prop) == KCorenessCentrality.getNoValue(), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['Being a ' KCorenessCentrality.getCategoryName(KCorenessCentrality.getPropCategory(prop)) ', KCorenessCentrality.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in KCorenessCentrality.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					m.getr(TAG) == KCorenessCentrality.getNoValue(), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['Being a ' KCorenessCentrality.getCategoryName(KCorenessCentrality.getPropCategory(prop)) ', KCorenessCentrality.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in KCorenessCentrality.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':KCorenessCentrality']);
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(m.getPropSettings(prop))
					assert( ...
						m.checkFormat(m.getPropFormat(prop), m.get(prop)), ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						['KCorenessCentrality.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						m.checkFormat(m.getPropFormat(prop), m.get(prop), m.getPropSettings(prop)), ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						['KCorenessCentrality.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(m.getr(prop), KCorenessCentrality.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by KCorenessCentrality.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in KCorenessCentrality.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(m.getr(TAG), KCorenessCentrality.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.getr(' TAG ') must be inizialized to its default value ' ...
					'given by KCorenessCentrality.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in KCorenessCentrality.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = KCorenessCentrality( ...
		KCorenessCentrality.ELCLASS, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.NAME, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.DESCRIPTION, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.TEMPLATE, KCorenessCentrality.getPropDefault(KCorenessCentrality.TEMPLATE), ...
		KCorenessCentrality.ID, KCorenessCentrality.getPropDefault(KCorenessCentrality.ID), ...
		KCorenessCentrality.LABEL, KCorenessCentrality.getPropDefault(KCorenessCentrality.LABEL), ...
		KCorenessCentrality.NOTES, KCorenessCentrality.getPropDefault(KCorenessCentrality.NOTES), ...
		KCorenessCentrality.TOSTRING, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.SHAPE, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.SCOPE, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.PARAMETRICITY, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.COMPATIBLE_GRAPHS, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.G, KCorenessCentrality.getPropDefault(KCorenessCentrality.G), ...
		KCorenessCentrality.M, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.PFM, KCorenessCentrality.getPropDefault(KCorenessCentrality.PFM) ...
		);
	 
	for prop = 1:1:KCorenessCentrality.getPropNumber()
	 
		% excluded props
		if any(prop == [KCorenessCentrality.PFM])
			continue
		end
	 
		TAG = upper(KCorenessCentrality.getPropTag(prop));
		switch KCorenessCentrality.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(m.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					m.checkFormat(m.getPropFormat(prop), m.getr(prop),m.getPropSettings(prop)), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':KCorenessCentrality']);
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':KCorenessCentrality']);
	% 			assert( ...
	% 				~isa(m.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
	% 				['KCorenessCentrality.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(m.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
	% 				['KCorenessCentrality.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				m.checkFormat(m.getPropFormat(prop), m.getr(prop),m.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
	% 				['KCorenessCentrality.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':KCorenessCentrality']);
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(m.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					m.checkFormat(m.getPropFormat(prop), m.getr(prop),m.getPropSettings(prop)), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if m.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:KCorenessCentrality');
					delete(ancestor(m.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(KCorenessCentrality.getProps(Category.RESULT))
		for prop = 1:1:KCorenessCentrality.getPropNumber()
	 
			% excluded props
			if any(prop == [KCorenessCentrality.PFM])
				continue
			end
	 
			switch KCorenessCentrality.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						m.isLocked(prop), ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						['KCorenessCentrality.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~m.isLocked(prop), ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						['KCorenessCentrality.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = KCorenessCentrality();
	 
	for prop = 1:1:KCorenessCentrality.getPropNumber()
		TAG = upper(KCorenessCentrality.getPropTag(prop));
		assert( ...
			~m.isLocked(prop), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			['KCorenessCentrality.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~m.isLocked(TAG), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			['KCorenessCentrality.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	m.lock()
	 
	for prop = 1:1:KCorenessCentrality.getPropNumber()
		switch KCorenessCentrality.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					m.isLocked(prop), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~m.isLocked(prop), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = KCorenessCentrality();
	 
	warning_backup = warning('off', 'BRAPH2:KCorenessCentrality');
	for prop = 1:1:KCorenessCentrality.getPropNumber()
		m.lock(prop)
		switch KCorenessCentrality.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					m.isLocked(prop), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~m.isLocked(prop), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = KCorenessCentrality();
	 
	for prop = 1:1:KCorenessCentrality.getPropNumber()
		TAG = upper(KCorenessCentrality.getPropTag(prop));
		assert( ...
			m.isChecked(prop), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			['KCorenessCentrality.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			m.isChecked(TAG), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			['KCorenessCentrality.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	m.unchecked()
	 
	for prop = 1:1:KCorenessCentrality.getPropNumber()
		assert( ...
			~m.isChecked(prop), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			['KCorenessCentrality.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	m.checked()
	 
	for prop = 1:1:KCorenessCentrality.getPropNumber()
		assert( ...
			m.isChecked(prop), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			['KCorenessCentrality.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic KCorenessCentrality
	m_0 = KCorenessCentrality( ...
		KCorenessCentrality.ELCLASS, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.NAME, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.DESCRIPTION, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.TEMPLATE, KCorenessCentrality.getPropDefault(KCorenessCentrality.TEMPLATE), ...
		KCorenessCentrality.ID, KCorenessCentrality.getPropDefault(KCorenessCentrality.ID), ...
		KCorenessCentrality.LABEL, KCorenessCentrality.getPropDefault(KCorenessCentrality.LABEL), ...
		KCorenessCentrality.NOTES, KCorenessCentrality.getPropDefault(KCorenessCentrality.NOTES), ...
		KCorenessCentrality.TOSTRING, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.SHAPE, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.SCOPE, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.PARAMETRICITY, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.COMPATIBLE_GRAPHS, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.G, KCorenessCentrality.getPropDefault(KCorenessCentrality.G), ...
		KCorenessCentrality.M, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.PFM, KCorenessCentrality.getPropDefault(KCorenessCentrality.PFM) ...
		);
	 
	% KCorenessCentrality with 1st callbacks
	m_1 = KCorenessCentrality( ...
		KCorenessCentrality.ELCLASS, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.NAME, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.DESCRIPTION, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.TEMPLATE, m_0.getCallback(4), ..., ...
		KCorenessCentrality.ID, m_0.getCallback(5), ..., ...
		KCorenessCentrality.LABEL, KCorenessCentrality.getPropDefault(KCorenessCentrality.LABEL), ...
		KCorenessCentrality.NOTES, KCorenessCentrality.getPropDefault(KCorenessCentrality.NOTES), ...
		KCorenessCentrality.TOSTRING, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.SHAPE, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.SCOPE, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.PARAMETRICITY, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.COMPATIBLE_GRAPHS, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.G, m_0.getCallback(13), ..., ...
		KCorenessCentrality.M, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.PFM, m_0.getCallback(15) ... ...
		);
	 
	prop_number = KCorenessCentrality.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(KCorenessCentrality.getPropTag(prop));
		switch KCorenessCentrality.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(m_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(m_1.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(m_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% KCorenessCentrality with 2nd callbacks
	m_2 = KCorenessCentrality( ...
		KCorenessCentrality.ELCLASS, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.NAME, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.DESCRIPTION, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.TEMPLATE, m_1.getCallback(4), ..., ...
		KCorenessCentrality.ID, m_1.getCallback(5), ..., ...
		KCorenessCentrality.LABEL, KCorenessCentrality.getPropDefault(KCorenessCentrality.LABEL), ...
		KCorenessCentrality.NOTES, KCorenessCentrality.getPropDefault(KCorenessCentrality.NOTES), ...
		KCorenessCentrality.TOSTRING, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.SHAPE, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.SCOPE, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.PARAMETRICITY, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.COMPATIBLE_GRAPHS, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.G, m_1.getCallback(13), ..., ...
		KCorenessCentrality.M, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.PFM, m_1.getCallback(15) ... ...
		);
	 
	prop_number = KCorenessCentrality.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(KCorenessCentrality.getPropTag(prop));
		switch KCorenessCentrality.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(m_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(m_2.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(m_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% KCorenessCentrality with 3rd callbacks
	m_3 = KCorenessCentrality( ...
		KCorenessCentrality.ELCLASS, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.NAME, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.DESCRIPTION, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.TEMPLATE, m_2.getCallback(4), ..., ...
		KCorenessCentrality.ID, m_2.getCallback(5), ..., ...
		KCorenessCentrality.LABEL, KCorenessCentrality.getPropDefault(KCorenessCentrality.LABEL), ...
		KCorenessCentrality.NOTES, KCorenessCentrality.getPropDefault(KCorenessCentrality.NOTES), ...
		KCorenessCentrality.TOSTRING, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.SHAPE, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.SCOPE, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.PARAMETRICITY, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.COMPATIBLE_GRAPHS, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.G, m_2.getCallback(13), ..., ...
		KCorenessCentrality.M, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.PFM, m_2.getCallback(15) ... ...
		);
	 
	prop_number = KCorenessCentrality.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(KCorenessCentrality.getPropTag(prop));
		switch KCorenessCentrality.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(m_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(m_3.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(m_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	m = KCorenessCentrality();
	 
	m_copy = m.copy();
	 
	assert(m_copy ~= m, ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'KCorenessCentrality.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(m_copy, m), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'KCorenessCentrality.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:KCorenessCentrality.getPropNumber()
		value = m.getr(prop);
		value_copy = m_copy.getr(prop);
		switch KCorenessCentrality.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					'KCorenessCentrality.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						'KCorenessCentrality.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						'KCorenessCentrality.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						'KCorenessCentrality.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
							'KCorenessCentrality.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
							'KCorenessCentrality.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						'KCorenessCentrality.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					m_copy.isLocked(prop) == m.isLocked(prop), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					'KCorenessCentrality.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					m_copy.isChecked(prop) == m.isChecked(prop), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					'KCorenessCentrality.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					m_copy.getPropSeed(prop) == m.getPropSeed(prop), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					'KCorenessCentrality.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	m = KCorenessCentrality( ...
		KCorenessCentrality.ELCLASS, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.NAME, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.DESCRIPTION, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.TEMPLATE, KCorenessCentrality.getPropDefault(KCorenessCentrality.TEMPLATE), ...
		KCorenessCentrality.ID, KCorenessCentrality.getPropDefault(KCorenessCentrality.ID), ...
		KCorenessCentrality.LABEL, KCorenessCentrality.getPropDefault(KCorenessCentrality.LABEL), ...
		KCorenessCentrality.NOTES, KCorenessCentrality.getPropDefault(KCorenessCentrality.NOTES), ...
		KCorenessCentrality.TOSTRING, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.SHAPE, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.SCOPE, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.PARAMETRICITY, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.COMPATIBLE_GRAPHS, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.G, KCorenessCentrality.getPropDefault(KCorenessCentrality.G), ...
		KCorenessCentrality.M, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.PFM, KCorenessCentrality.getPropDefault(KCorenessCentrality.PFM) ...
		);
	 
	for prop = 1:1:KCorenessCentrality.getPropNumber()
		if KCorenessCentrality.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':KCorenessCentrality']);
			% m.memorize(prop);
			% warning(warning_backup)
		elseif KCorenessCentrality.getPropCategory(prop) == Category.EVANESCENT && m.getPropFormat(prop) == Format.HANDLE
			m.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:KCorenessCentrality');
			delete(ancestor(m.get(prop), 'figure'))
			warning(warning_backup)
		else
			m.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	m_copy = m.copy();
	 
	for prop = 1:1:KCorenessCentrality.getPropNumber()
		value = m.getr(prop);
		value_copy = m_copy.getr(prop);
		switch KCorenessCentrality.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					'KCorenessCentrality.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						'KCorenessCentrality.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						'KCorenessCentrality.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						'KCorenessCentrality.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
							'KCorenessCentrality.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
							'KCorenessCentrality.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						'KCorenessCentrality.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						m_copy.isLocked(prop) == m.isLocked(prop), ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						'KCorenessCentrality.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						m_copy.isChecked(prop) == m.isChecked(prop), ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						'KCorenessCentrality.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						m_copy.getPropSeed(prop) == m.getPropSeed(prop), ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						'KCorenessCentrality.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	m_0 = KCorenessCentrality( ...
		KCorenessCentrality.ELCLASS, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.NAME, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.DESCRIPTION, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.TEMPLATE, KCorenessCentrality.getPropDefault(KCorenessCentrality.TEMPLATE), ...
		KCorenessCentrality.ID, KCorenessCentrality.getPropDefault(KCorenessCentrality.ID), ...
		KCorenessCentrality.LABEL, KCorenessCentrality.getPropDefault(KCorenessCentrality.LABEL), ...
		KCorenessCentrality.NOTES, KCorenessCentrality.getPropDefault(KCorenessCentrality.NOTES), ...
		KCorenessCentrality.TOSTRING, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.SHAPE, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.SCOPE, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.PARAMETRICITY, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.COMPATIBLE_GRAPHS, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.G, KCorenessCentrality.getPropDefault(KCorenessCentrality.G), ...
		KCorenessCentrality.M, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.PFM, KCorenessCentrality.getPropDefault(KCorenessCentrality.PFM) ...
		);
	 
	m = KCorenessCentrality( ...
		KCorenessCentrality.ELCLASS, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.NAME, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.DESCRIPTION, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.TEMPLATE, m_0.getCallback(4), ..., ...
		KCorenessCentrality.ID, m_0.getCallback(5), ..., ...
		KCorenessCentrality.LABEL, KCorenessCentrality.getPropDefault(KCorenessCentrality.LABEL), ...
		KCorenessCentrality.NOTES, KCorenessCentrality.getPropDefault(KCorenessCentrality.NOTES), ...
		KCorenessCentrality.TOSTRING, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.SHAPE, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.SCOPE, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.PARAMETRICITY, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.COMPATIBLE_GRAPHS, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.G, m_0.getCallback(13), ..., ...
		KCorenessCentrality.M, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.PFM, m_0.getCallback(15) ... ...
		);
	 
	m_copy = m.copy();
	m_0_copy = m_copy.getr('ID').get('EL');
	 
	for prop = 1:1:KCorenessCentrality.getPropNumber()
		value = m.getr(prop);
		value_copy = m_copy.getr(prop);
		switch KCorenessCentrality.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					'KCorenessCentrality.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						'KCorenessCentrality.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						'KCorenessCentrality.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						'KCorenessCentrality.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
							'KCorenessCentrality.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
							'KCorenessCentrality.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						'KCorenessCentrality.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == m_0.getCallback(prop), ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						'KCorenessCentrality.copy() does not work. The callback should be obtained from KCorenessCentrality.getCallback().' ...
						)
					assert( ...
						value_copy == m_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						'KCorenessCentrality.copy() does not work. The callback should be obtained from KCorenessCentrality.getCallback().' ...
						)
				end
	 
					assert( ...
						m_copy.isLocked(prop) == m.isLocked(prop), ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						'KCorenessCentrality.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						m_copy.isChecked(prop) == m.isChecked(prop), ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						'KCorenessCentrality.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						m_copy.getPropSeed(prop) == m.getPropSeed(prop), ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						'KCorenessCentrality.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m_template = KCorenessCentrality();
	m = KCorenessCentrality('TEMPLATE', m_template);
	 
	for prop = 1:1:KCorenessCentrality.getPropNumber()
	 
		% excluded props
		if any(prop == [KCorenessCentrality.PFM])
			continue
		end
	 
		TAG = upper(KCorenessCentrality.getPropTag(prop));
		switch KCorenessCentrality.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == KCorenessCentrality.TEMPLATE
					assert( ...
						isa(m.getr(prop), 'KCorenessCentrality'), ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						'KCorenessCentrality TEMPLATE does not work. KCorenessCentrality.getr(''TEMPLATE'') should be a KCorenessCentrality element.' ...
						)
					assert( ...
						isa(m_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						'KCorenessCentrality TEMPLATE does not work. KCorenessCentrality_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(m.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						['KCorenessCentrality TEMPLATE does not work. KCorenessCentrality.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						m.getr(prop).get('EL') == m_template && m.getr(prop).get('PROP') == prop && strcmp(m.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						['KCorenessCentrality TEMPLATE does not work. KCorenessCentrality.getr(' TAG ') should be a Callback to m_template.' TAG '.'] ...
						)
					assert( ...
						isa(m_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
						['KCorenessCentrality TEMPLATE does not work. KCorenessCentrality_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality TEMPLATE does not work. KCorenessCentrality.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(m_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
					['KCorenessCentrality TEMPLATE does not work. KCorenessCentrality_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = KCorenessCentrality( ...
		KCorenessCentrality.ELCLASS, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.NAME, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.DESCRIPTION, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.TEMPLATE, KCorenessCentrality.getPropDefault(KCorenessCentrality.TEMPLATE), ...
		KCorenessCentrality.ID, KCorenessCentrality.getPropDefault(KCorenessCentrality.ID), ...
		KCorenessCentrality.LABEL, KCorenessCentrality.getPropDefault(KCorenessCentrality.LABEL), ...
		KCorenessCentrality.NOTES, KCorenessCentrality.getPropDefault(KCorenessCentrality.NOTES), ...
		KCorenessCentrality.TOSTRING, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.SHAPE, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.SCOPE, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.PARAMETRICITY, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.COMPATIBLE_GRAPHS, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.G, KCorenessCentrality.getPropDefault(KCorenessCentrality.G), ...
		KCorenessCentrality.M, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.PFM, KCorenessCentrality.getPropDefault(KCorenessCentrality.PFM) ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'kcorenesscentrality_to_be_erased.b2'];
	 
	Element.save(m, filename)
	 
	m_loaded = Element.load(filename);
	 
	assert( ...
		isequal(m.copy(), m_loaded), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'KCorenessCentrality.save(m) and/or KCorenessCentrality.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = KCorenessCentrality( ...
		KCorenessCentrality.ELCLASS, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.NAME, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.DESCRIPTION, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.TEMPLATE, KCorenessCentrality.getPropDefault(KCorenessCentrality.TEMPLATE), ...
		KCorenessCentrality.ID, KCorenessCentrality.getPropDefault(KCorenessCentrality.ID), ...
		KCorenessCentrality.LABEL, KCorenessCentrality.getPropDefault(KCorenessCentrality.LABEL), ...
		KCorenessCentrality.NOTES, KCorenessCentrality.getPropDefault(KCorenessCentrality.NOTES), ...
		KCorenessCentrality.TOSTRING, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.SHAPE, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.SCOPE, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.PARAMETRICITY, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.COMPATIBLE_GRAPHS, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.G, KCorenessCentrality.getPropDefault(KCorenessCentrality.G), ...
		KCorenessCentrality.M, KCorenessCentrality.getNoValue(), ...
		KCorenessCentrality.PFM, KCorenessCentrality.getPropDefault(KCorenessCentrality.PFM) ...
		);
	 
	[json, struct, el_list] = encodeJSON(m);
	[m_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(m_dec ~= m, ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		'KCorenessCentrality.encodeJSON() or KCorenessCentrality.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) KCorenessCentrality.getPropFormat(prop), num2cell(KCorenessCentrality.getProps())) == Format.HANDLE) && all(cellfun(@(prop) KCorenessCentrality.getPropFormat(prop), num2cell(KCorenessCentrality.getProps())) == Format.NET)
		assert(isequal(m_dec, m), ...
			[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
			'KCorenessCentrality.encodeJSON() or KCorenessCentrality.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: GraphBU
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	B = [
	    0  1  1  0; 
	    1  0  1  1; 
	    1  1  0  0;
	    0  1  0  0
	    ];
	
	known_k_coreness_centrality = {[2 2 2 1]'};
	
	g = GraphBU('B', B);
	
	m_outside_g = KCorenessCentrality('G', g);
	assert(isequal(m_outside_g.get('M'), known_k_coreness_centrality), ...
	    [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
	    [class(m_outside_g) ' is not being calculated correctly for ' class(g) '.'])
	
	m_inside_g = g.get('MEASURE', 'KCorenessCentrality');
	assert(isequal(m_inside_g.get('M'), known_k_coreness_centrality), ...
	    [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
	    [class(m_inside_g) ' is not being calculated correctly for ' class(g) '.'])
end

%% Test 13: GraphWD
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	B =  [
	    0   1   1  .1;
	    .2  0   1  1;
	    1   1   0  0;
	    0   .3  0  0
	    ];
	
	known_k_coreness_centrality = {[4 4 4 3]'};
	
	g = GraphWD('B', B);
	
	m_outside_g = KCorenessCentrality('G', g);
	assert(isequal(m_outside_g.get('M'), known_k_coreness_centrality), ...
	    [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
	    [class(m_outside_g) ' is not being calculated correctly for ' class(g) '.'])
	
	m_inside_g = g.get('MEASURE', 'KCorenessCentrality');
	assert(isequal(m_inside_g.get('M'), known_k_coreness_centrality), ...
	    [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
	    [class(m_inside_g) ' is not being calculated correctly for ' class(g) '.'])
end

%% Test 14: MultiplexBD
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	A11 = [
	    0  1  1  1; 
	    1  0  1  1; 
	    1  1  0  0;
	    0  1  0  0
	    ];
	
	A22 = [
	    0  1  1  1; 
	    1  0  1  1; 
	    1  1  0  0;
	    0  1  1  0
	    ];
	A = {A11 A22};
	
	known_k_coreness_centrality = {
	                        [4 4 4 3]'
	                        [4 4 4 4]'
	                        };
	
	g = MultiplexBD('B', A);
	m_outside_g = KCorenessCentrality('G', g);
	assert(isequal(m_outside_g.get('M'), known_k_coreness_centrality), ...
	    [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
	    [class(m_outside_g) ' is not being calculated correctly for ' class(g) '.'])
	
	m_inside_g = g.get('MEASURE', 'KCorenessCentrality');
	assert(isequal(m_inside_g.get('M'), known_k_coreness_centrality), ...
	    [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
	    [class(m_inside_g) ' is not being calculated correctly for ' class(g) '.'])
end

%% Test 15: MultiplexWU
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	A11 = [
	    0   .1  1  0; 
	    .1  0   1  .8; 
	    1   1   0  0;
	    0   .8  0  0
	    ];
	
	A22 = [
	    0   .1  1  1; 
	    .1  0   1  .8; 
	    1   1   0  0;
	    1   .8  0  0
	    ];
	A = {A11 A22};
	             
	known_k_coreness_centrality = {
	                        [2 2 2 1]'
	                        [2 2 2 2]'
	                        };        
	
	g = MultiplexWU('B', A);
	m_outside_g = KCorenessCentrality('G', g);
	assert(isequal(m_outside_g.get('M'), known_k_coreness_centrality), ...
	    [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
	    [class(m_outside_g) ' is not being calculated correctly for ' class(g) '.'])
	
	m_inside_g = g.get('MEASURE', 'KCorenessCentrality');
	assert(isequal(m_inside_g.get('M'), known_k_coreness_centrality), ...
	    [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
	    [class(m_inside_g) ' is not being calculated correctly for ' class(g) '.'])
end

%% Test 16: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.FAIL_TEST], ...
		[' When testing KCorenessCentrality no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 17: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

