%TEST_CATEGORY

%% Test 1: Static methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
    category_list = Category.getCategories();
    
    assert(numel(category_list) == Category.getCategoryNumber(), ...
        [BRAPH2.STR ':Category:' BRAPH2.FAIL_TEST], ...
        'Category.getCategoryNumber() does not return the correct number of categories.')
    
    for category = category_list
        assert(Category.existsCategory(category), ...
            [BRAPH2.STR ':Category:' BRAPH2.FAIL_TEST], ...
            ['Category.existsCategory(' tostring(category) ') must return true.'])

        assert(strcmp(eval(['Category.' upper(Category.getCategoryName(category)) '_TAG']), Category.getCategoryTag(category)), ...
            [BRAPH2.STR ':Category:' BRAPH2.FAIL_TEST], ...
            ['Category.getCategoryTag(' tostring(category) ') must return be equal to Category.' upper(Category.getCategoryName(category)) '_TAG.'])

        assert(strcmp(eval(['Category.' upper(Category.getCategoryName(category)) '_NAME']), Category.getCategoryName(category)), ...
            [BRAPH2.STR ':Category:' BRAPH2.FAIL_TEST], ...
            ['Category.getCategoryName(' tostring(category) ') must return be equal to Category.' upper(Category.getCategoryName(category)) '_NAME.'])

        assert(strcmp(eval(['Category.' upper(Category.getCategoryName(category)) '_DESCRIPTION']), Category.getCategoryDescription(category)), ...
            [BRAPH2.STR ':Category:' BRAPH2.FAIL_TEST], ...
            ['Category.getCategoryDescription(' tostring(category) ') must be equal to Category.' upper(Category.getCategoryName(category)) '_DESCRIPTION.'])
    end
end