%TEST_STRENGTHAV

%% Test 1.1: Instantiation - empty

m = StrengthAv();

prop_number = StrengthAv.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(StrengthAv.getPropTag(prop));
	assert( ...
		isa(m.getr(prop), 'NoValue'), ...
		[BRAPH2.STR ':StrengthAv:' BRAPH2.BUG_FUNC], ...
		['StrengthAv.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
		'Or there could be an error in StrengthAv.getr(' int2str(prop) ').'] ...
		)
	assert( ...
		isa(m.getr(TAG), 'NoValue'), ...
		[BRAPH2.STR ':StrengthAv:' BRAPH2.BUG_FUNC], ...
		['StrengthAv.getr(''' TAG ''') must be inizialized to NoValue(). ' ...
		'Or there could be an error in StrengthAv.getr(''' TAG ''').'] ...
		)
end

%% Test 1.2: Instantiation - defaults

warning('off', 'BRAPH2:StrengthAv')
m = StrengthAv( ...
	StrengthAv.ID, StrengthAv.getPropDefault(StrengthAv.ID), ...
	StrengthAv.LABEL, StrengthAv.getPropDefault(StrengthAv.LABEL), ...
	StrengthAv.NOTES, StrengthAv.getPropDefault(StrengthAv.NOTES), ...
	StrengthAv.G, StrengthAv.getPropDefault(StrengthAv.G), ...
	StrengthAv.M, StrengthAv.getPropDefault(StrengthAv.M) ...
	);
warning('on', 'BRAPH2:StrengthAv')

for prop = 1:1:StrengthAv.getPropNumber()
	TAG = upper(StrengthAv.getPropTag(prop));
	switch StrengthAv.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isequal(m.getr(prop), StrengthAv.getPropDefaultConditioned(prop)), ...
				[BRAPH2.STR ':StrengthAv:' BRAPH2.BUG_FUNC], ...
				['StrengthAv.getr(' int2str(prop) ') must be inizialized to its default value ' ...
				'given by StrengthAv.getPropDefaultConditioned(' int2str(prop) '). ' ...
				'Or there could be an error in StrengthAv.getr(' int2str(prop) ').'] ...
				)
			assert( ...
				isequal(m.getr(TAG), StrengthAv.getPropDefaultConditioned(prop)), ...
				[BRAPH2.STR ':StrengthAv:' BRAPH2.BUG_FUNC], ...
				['StrengthAv.getr(''' TAG ''') must be inizialized to its default value ' ...
				'given by StrengthAv.getPropDefaultConditioned(' int2str(prop) '). ' ...
				'Or there could be an error in StrengthAv.getr(''' TAG ''').'] ...
				)
		case Category.RESULT
			assert( ...
				isa(m.getr(prop), 'NoValue'), ...
				[BRAPH2.STR ':StrengthAv:' BRAPH2.BUG_FUNC], ...
				['Being a result, StrengthAv.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
				'Or there could be an error in StrengthAv.getr(' int2str(prop) ').'] ...
				)
			assert( ...
				isa(m.getr(TAG), 'NoValue'), ...
				[BRAPH2.STR ':StrengthAv:' BRAPH2.BUG_FUNC], ...
				['Being a result, StrengthAv.getr(''' TAG ''') must be inizialized to NoValue(). ' ...
				'Or there could be an error in StrengthAv.getr(''' TAG ''').'] ...
				)
	end
end

%% Test 2: Callbacks

warning('off', 'BRAPH2:StrengthAv')
m_0 = StrengthAv( ...
	StrengthAv.ID, StrengthAv.getPropDefault(StrengthAv.ID), ...
	StrengthAv.LABEL, StrengthAv.getPropDefault(StrengthAv.LABEL), ...
	StrengthAv.NOTES, StrengthAv.getPropDefault(StrengthAv.NOTES), ...
	StrengthAv.G, StrengthAv.getPropDefault(StrengthAv.G), ...
	StrengthAv.M, StrengthAv.getPropDefault(StrengthAv.M) ...
	);
warning('on', 'BRAPH2:StrengthAv')

m_1 = StrengthAv( ...
	StrengthAv.ID, Callback('EL', m_0, 'PROP', 1), ...
	StrengthAv.LABEL, StrengthAv.getPropDefault(StrengthAv.LABEL), ...
	StrengthAv.NOTES, StrengthAv.getPropDefault(StrengthAv.NOTES), ...
	StrengthAv.G, Callback('EL', m_0, 'PROP', 4), ...
	StrengthAv.M, NoValue() ...
	);
	
prop_number = StrengthAv.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(StrengthAv.getPropTag(prop));
	switch StrengthAv.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(m_1.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':StrengthAv:' BRAPH2.BUG_FUNC], ...
				['StrengthAv.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(m_1.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':StrengthAv:' BRAPH2.BUG_FUNC], ...
				['StrengthAv.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(m_1.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':StrengthAv:' BRAPH2.BUG_FUNC], ...
				['StrengthAv.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end
m_2 = StrengthAv( ...
	StrengthAv.ID, Callback('EL', m_1, 'PROP', 1), ...
	StrengthAv.LABEL, StrengthAv.getPropDefault(StrengthAv.LABEL), ...
	StrengthAv.NOTES, StrengthAv.getPropDefault(StrengthAv.NOTES), ...
	StrengthAv.G, Callback('EL', m_1, 'PROP', 4), ...
	StrengthAv.M, NoValue() ...
	);
	
prop_number = StrengthAv.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(StrengthAv.getPropTag(prop));
	switch StrengthAv.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(m_2.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':StrengthAv:' BRAPH2.BUG_FUNC], ...
				['StrengthAv.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(m_2.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':StrengthAv:' BRAPH2.BUG_FUNC], ...
				['StrengthAv.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(m_2.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':StrengthAv:' BRAPH2.BUG_FUNC], ...
				['StrengthAv.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end
m_3 = StrengthAv( ...
	StrengthAv.ID, Callback('EL', m_2, 'PROP', 1), ...
	StrengthAv.LABEL, StrengthAv.getPropDefault(StrengthAv.LABEL), ...
	StrengthAv.NOTES, StrengthAv.getPropDefault(StrengthAv.NOTES), ...
	StrengthAv.G, Callback('EL', m_2, 'PROP', 4), ...
	StrengthAv.M, NoValue() ...
	);
	
prop_number = StrengthAv.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(StrengthAv.getPropTag(prop));
	switch StrengthAv.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(m_3.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':StrengthAv:' BRAPH2.BUG_FUNC], ...
				['StrengthAv.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(m_3.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':StrengthAv:' BRAPH2.BUG_FUNC], ...
				['StrengthAv.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(m_3.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':StrengthAv:' BRAPH2.BUG_FUNC], ...
				['StrengthAv.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end

%% Test 3: Result

warning('off', 'BRAPH2:StrengthAv')
m = StrengthAv( ...
	StrengthAv.ID, StrengthAv.getPropDefault(StrengthAv.ID), ...
	StrengthAv.LABEL, StrengthAv.getPropDefault(StrengthAv.LABEL), ...
	StrengthAv.NOTES, StrengthAv.getPropDefault(StrengthAv.NOTES), ...
	StrengthAv.G, StrengthAv.getPropDefault(StrengthAv.G), ...
	StrengthAv.M, StrengthAv.getPropDefault(StrengthAv.M) ...
	);
warning('on', 'BRAPH2:StrengthAv')

prop_number = StrengthAv.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(StrengthAv.getPropTag(prop));
	switch StrengthAv.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
		case Category.RESULT
			assert( ...
				~isa(m.get(prop),  'NoValue'), ...
				[BRAPH2.STR ':StrengthAv:' BRAPH2.BUG_FUNC], ...
				['StrengthAv.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				isa(m.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':StrengthAv:' BRAPH2.BUG_FUNC], ...
				['StrengthAv.getr(' int2str(prop) ') must be a NoValue, because it has not been memorized.'] ...
				)
			if isempty(m.getPropSettings(prop))
				assert( ...
					m.checkFormat(m.getPropFormat(prop), m.get(prop)), ...
					[BRAPH2.STR ':StrengthAv:' BRAPH2.BUG_FUNC], ...
					['StrengthAv.get(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			else
				assert( ...
					m.checkFormat(m.getPropFormat(prop), m.get(prop), m.getPropSettings(prop)), ...
					[BRAPH2.STR ':StrengthAv:' BRAPH2.BUG_FUNC], ...
					['StrengthAv.get(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			end
	end
end

%% Test 4: Memorize

warning('off', 'BRAPH2:StrengthAv')
m = StrengthAv( ...
	StrengthAv.ID, StrengthAv.getPropDefault(StrengthAv.ID), ...
	StrengthAv.LABEL, StrengthAv.getPropDefault(StrengthAv.LABEL), ...
	StrengthAv.NOTES, StrengthAv.getPropDefault(StrengthAv.NOTES), ...
	StrengthAv.G, StrengthAv.getPropDefault(StrengthAv.G), ...
	StrengthAv.M, StrengthAv.getPropDefault(StrengthAv.M) ...
	);
warning('on', 'BRAPH2:StrengthAv')

for prop = 1:1:StrengthAv.getPropNumber()
	TAG = upper(StrengthAv.getPropTag(prop));
	switch StrengthAv.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
		case Category.RESULT
			assert( ...
				~isa(m.get(prop),  'NoValue'), ...
				[BRAPH2.STR ':StrengthAv:' BRAPH2.BUG_FUNC], ...
				['StrengthAv.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				isa(m.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':StrengthAv:' BRAPH2.BUG_FUNC], ...
				['StrengthAv.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
				)
			assert( ...
				~isa(m.memorize(prop),  'NoValue'), ...
				[BRAPH2.STR ':StrengthAv:' BRAPH2.BUG_FUNC], ...
				['StrengthAv.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				~isa(m.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':StrengthAv:' BRAPH2.BUG_FUNC], ...
				['StrengthAv.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
				)
			assert( ...
				m.checkFormat(m.getPropFormat(prop), m.getr(prop),m.getPropSettings(prop)), ...
				[BRAPH2.STR ':StrengthAv:' BRAPH2.BUG_FUNC], ...
				['StrengthAv.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
				)
	end
end

%% Test 5: GraphWU

B = [
    0  .2 1
    .2 0  0
    1  0  0
    ];
known_strength_av = {mean([1.2 0.2 1])'};
g = GraphWU('B', B);
s_outside_g = StrengthAv('G', g);

assert(isequal(s_outside_g.get('M'), known_strength_av), ...
    [BRAPH2.STR ':Strength:' BRAPH2.BUG_ERR], ...
    'StrengthAV is not being calculated correctly for GraphWU.')

%% Test 6: MultiplexWU

B11 = [
    0  .2 1
    .2 0  0
    1  0  0
    ];
B22 = [
    0 1  0
    1 0  .4
    0 .4 0
    ];
B = {B11 B22};

known_strength_av = {
                 mean([1.2 .2  1]')
                 mean([1   1.4 .4]')
                 };
                                
g = MultiplexWU('B', B);
strength_av = StrengthAv('G', g);

assert(isequal(strength_av.get('M'), known_strength_av), ...
    [BRAPH2.STR ':Strength:' BRAPH2.BUG_ERR], ...
    'StrengthAV is not being calculated correctly for MultiplexWU.')

