%TEST_MULTIPLEXTRIANGLES

%% Test 1.1: Instantiation - empty

m = MultiplexTriangles();

prop_number = MultiplexTriangles.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(MultiplexTriangles.getPropTag(prop));
	assert( ...
		isa(m.getr(prop), 'NoValue'), ...
		[BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_FUNC], ...
		['MultiplexTriangles.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
		'Or there could be an error in MultiplexTriangles.getr(' int2str(prop) ').'] ...
		)
	assert( ...
		isa(m.getr(TAG), 'NoValue'), ...
		[BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_FUNC], ...
		['MultiplexTriangles.getr(''' TAG ''') must be inizialized to NoValue(). ' ...
		'Or there could be an error in MultiplexTriangles.getr(''' TAG ''').'] ...
		)
end

%% Test 1.2: Instantiation - defaults

warning('off', 'BRAPH2:MultiplexTriangles')
m = MultiplexTriangles( ...
	MultiplexTriangles.ID, MultiplexTriangles.getPropDefault(MultiplexTriangles.ID), ...
	MultiplexTriangles.LABEL, MultiplexTriangles.getPropDefault(MultiplexTriangles.LABEL), ...
	MultiplexTriangles.NOTES, MultiplexTriangles.getPropDefault(MultiplexTriangles.NOTES), ...
	MultiplexTriangles.G, MultiplexTriangles.getPropDefault(MultiplexTriangles.G), ...
	MultiplexTriangles.M, MultiplexTriangles.getPropDefault(MultiplexTriangles.M) ...
	);
warning('on', 'BRAPH2:MultiplexTriangles')

for prop = 1:1:MultiplexTriangles.getPropNumber()
	TAG = upper(MultiplexTriangles.getPropTag(prop));
	switch MultiplexTriangles.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isequal(m.getr(prop), MultiplexTriangles.getPropDefaultConditioned(prop)), ...
				[BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_FUNC], ...
				['MultiplexTriangles.getr(' int2str(prop) ') must be inizialized to its default value ' ...
				'given by MultiplexTriangles.getPropDefaultConditioned(' int2str(prop) '). ' ...
				'Or there could be an error in MultiplexTriangles.getr(' int2str(prop) ').'] ...
				)
			assert( ...
				isequal(m.getr(TAG), MultiplexTriangles.getPropDefaultConditioned(prop)), ...
				[BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_FUNC], ...
				['MultiplexTriangles.getr(''' TAG ''') must be inizialized to its default value ' ...
				'given by MultiplexTriangles.getPropDefaultConditioned(' int2str(prop) '). ' ...
				'Or there could be an error in MultiplexTriangles.getr(''' TAG ''').'] ...
				)
		case Category.RESULT
			assert( ...
				isa(m.getr(prop), 'NoValue'), ...
				[BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_FUNC], ...
				['Being a result, MultiplexTriangles.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
				'Or there could be an error in MultiplexTriangles.getr(' int2str(prop) ').'] ...
				)
			assert( ...
				isa(m.getr(TAG), 'NoValue'), ...
				[BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_FUNC], ...
				['Being a result, MultiplexTriangles.getr(''' TAG ''') must be inizialized to NoValue(). ' ...
				'Or there could be an error in MultiplexTriangles.getr(''' TAG ''').'] ...
				)
	end
end

%% Test 2: Callbacks

warning('off', 'BRAPH2:MultiplexTriangles')
m_0 = MultiplexTriangles( ...
	MultiplexTriangles.ID, MultiplexTriangles.getPropDefault(MultiplexTriangles.ID), ...
	MultiplexTriangles.LABEL, MultiplexTriangles.getPropDefault(MultiplexTriangles.LABEL), ...
	MultiplexTriangles.NOTES, MultiplexTriangles.getPropDefault(MultiplexTriangles.NOTES), ...
	MultiplexTriangles.G, MultiplexTriangles.getPropDefault(MultiplexTriangles.G), ...
	MultiplexTriangles.M, MultiplexTriangles.getPropDefault(MultiplexTriangles.M) ...
	);
warning('on', 'BRAPH2:MultiplexTriangles')

m_1 = MultiplexTriangles( ...
	MultiplexTriangles.ID, Callback('EL', m_0, 'PROP', 1), ...
	MultiplexTriangles.LABEL, MultiplexTriangles.getPropDefault(MultiplexTriangles.LABEL), ...
	MultiplexTriangles.NOTES, MultiplexTriangles.getPropDefault(MultiplexTriangles.NOTES), ...
	MultiplexTriangles.G, Callback('EL', m_0, 'PROP', 4), ...
	MultiplexTriangles.M, NoValue() ...
	);
	
prop_number = MultiplexTriangles.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(MultiplexTriangles.getPropTag(prop));
	switch MultiplexTriangles.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(m_1.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_FUNC], ...
				['MultiplexTriangles.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(m_1.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_FUNC], ...
				['MultiplexTriangles.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(m_1.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_FUNC], ...
				['MultiplexTriangles.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end
m_2 = MultiplexTriangles( ...
	MultiplexTriangles.ID, Callback('EL', m_1, 'PROP', 1), ...
	MultiplexTriangles.LABEL, MultiplexTriangles.getPropDefault(MultiplexTriangles.LABEL), ...
	MultiplexTriangles.NOTES, MultiplexTriangles.getPropDefault(MultiplexTriangles.NOTES), ...
	MultiplexTriangles.G, Callback('EL', m_1, 'PROP', 4), ...
	MultiplexTriangles.M, NoValue() ...
	);
	
prop_number = MultiplexTriangles.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(MultiplexTriangles.getPropTag(prop));
	switch MultiplexTriangles.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(m_2.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_FUNC], ...
				['MultiplexTriangles.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(m_2.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_FUNC], ...
				['MultiplexTriangles.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(m_2.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_FUNC], ...
				['MultiplexTriangles.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end
m_3 = MultiplexTriangles( ...
	MultiplexTriangles.ID, Callback('EL', m_2, 'PROP', 1), ...
	MultiplexTriangles.LABEL, MultiplexTriangles.getPropDefault(MultiplexTriangles.LABEL), ...
	MultiplexTriangles.NOTES, MultiplexTriangles.getPropDefault(MultiplexTriangles.NOTES), ...
	MultiplexTriangles.G, Callback('EL', m_2, 'PROP', 4), ...
	MultiplexTriangles.M, NoValue() ...
	);
	
prop_number = MultiplexTriangles.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(MultiplexTriangles.getPropTag(prop));
	switch MultiplexTriangles.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(m_3.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_FUNC], ...
				['MultiplexTriangles.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(m_3.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_FUNC], ...
				['MultiplexTriangles.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(m_3.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_FUNC], ...
				['MultiplexTriangles.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end

%% Test 3: Result

warning('off', 'BRAPH2:MultiplexTriangles')
m = MultiplexTriangles( ...
	MultiplexTriangles.ID, MultiplexTriangles.getPropDefault(MultiplexTriangles.ID), ...
	MultiplexTriangles.LABEL, MultiplexTriangles.getPropDefault(MultiplexTriangles.LABEL), ...
	MultiplexTriangles.NOTES, MultiplexTriangles.getPropDefault(MultiplexTriangles.NOTES), ...
	MultiplexTriangles.G, MultiplexTriangles.getPropDefault(MultiplexTriangles.G), ...
	MultiplexTriangles.M, MultiplexTriangles.getPropDefault(MultiplexTriangles.M) ...
	);
warning('on', 'BRAPH2:MultiplexTriangles')

prop_number = MultiplexTriangles.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(MultiplexTriangles.getPropTag(prop));
	switch MultiplexTriangles.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
		case Category.RESULT
			assert( ...
				~isa(m.get(prop),  'NoValue'), ...
				[BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_FUNC], ...
				['MultiplexTriangles.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				isa(m.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_FUNC], ...
				['MultiplexTriangles.getr(' int2str(prop) ') must be a NoValue, because it has not been memorized.'] ...
				)
			if isempty(m.getPropSettings(prop))
				assert( ...
					m.checkFormat(m.getPropFormat(prop), m.get(prop)), ...
					[BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_FUNC], ...
					['MultiplexTriangles.get(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			else
				assert( ...
					m.checkFormat(m.getPropFormat(prop), m.get(prop), m.getPropSettings(prop)), ...
					[BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_FUNC], ...
					['MultiplexTriangles.get(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			end
	end
end

%% Test 4: Memorize

warning('off', 'BRAPH2:MultiplexTriangles')
m = MultiplexTriangles( ...
	MultiplexTriangles.ID, MultiplexTriangles.getPropDefault(MultiplexTriangles.ID), ...
	MultiplexTriangles.LABEL, MultiplexTriangles.getPropDefault(MultiplexTriangles.LABEL), ...
	MultiplexTriangles.NOTES, MultiplexTriangles.getPropDefault(MultiplexTriangles.NOTES), ...
	MultiplexTriangles.G, MultiplexTriangles.getPropDefault(MultiplexTriangles.G), ...
	MultiplexTriangles.M, MultiplexTriangles.getPropDefault(MultiplexTriangles.M) ...
	);
warning('on', 'BRAPH2:MultiplexTriangles')

for prop = 1:1:MultiplexTriangles.getPropNumber()
	TAG = upper(MultiplexTriangles.getPropTag(prop));
	switch MultiplexTriangles.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
		case Category.RESULT
			assert( ...
				~isa(m.get(prop),  'NoValue'), ...
				[BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_FUNC], ...
				['MultiplexTriangles.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				isa(m.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_FUNC], ...
				['MultiplexTriangles.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
				)
			assert( ...
				~isa(m.memorize(prop),  'NoValue'), ...
				[BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_FUNC], ...
				['MultiplexTriangles.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				~isa(m.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_FUNC], ...
				['MultiplexTriangles.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
				)
			assert( ...
				m.checkFormat(m.getPropFormat(prop), m.getr(prop),m.getPropSettings(prop)), ...
				[BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_FUNC], ...
				['MultiplexTriangles.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
				)
	end
end

%% Test 5: MultiplexBU

B11 = [
      0 1 1 1;
      1 0 1 0;
      1 1 0 0;
      1 0 0 0
      ];
B22 = [
      0 1 1 1;
      1 0 0 0;
      1 0 0 0;
      1 0 0 0
      ];
B = {B11 B22};

known_multiplex_triangles = {
                 [2 2 2 0]'
                 };      

g = MultiplexBU('B', B);
multiplex_triangles = MultiplexTriangles('G', g);

assert(isequal(multiplex_triangles.get('M'), known_multiplex_triangles), ...
    [BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_ERR], ...
    'MultiplexTriangles is not being calculated correctly for MultiplexBU.')

%% Test 6: MultiplexBUT

B11 = [
      0 1 1 1;
      1 0 1 0;
      1 1 0 0;
      1 0 0 0
      ];
B22 = [
      0 1 1 1;
      1 0 0 0;
      1 0 0 0;
      1 0 0 0
      ];
B = {B11 B22};

known_multiplex_triangles = {
                 [2 2 2 0]'
                 [0 0 0 0]'
                 };      

g = MultiplexBUT('B', B, 'THRESHOLDS', [0 1]);
multiplex_triangles = MultiplexTriangles('G', g);

assert(isequal(multiplex_triangles.get('M'), known_multiplex_triangles), ...
    [BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_ERR], ...
    'MultiplexTriangles is not being calculated correctly for MultiplexBUT.')

%% Test 7: MultiplexWU

B11 = [
      0   .2  1   1;
      .2  0   1  0;
      1   1  0   0;
      1   0   0   0
      ];
B22 = [
      0   .2  1  .7;
      .2  0   0  0;
      1   0   0  0;
      .7  0   0  0
      ];
B = {B11 B22};

known_multiplex_triangles = {
                 diag(B11.^(1/3)*B22.^(1/3)*B11.^(1/3) + B22.^(1/3)*B11.^(1/3)*B22.^(1/3))
                 };      

g = MultiplexWU('B', B);
multiplex_triangles = MultiplexTriangles('G', g);

assert(isequal(multiplex_triangles.get('M'), known_multiplex_triangles), ...
    [BRAPH2.STR ':MultiplexTriangles:' BRAPH2.BUG_ERR], ...
    'MultiplexTriangles is not being calculated correctly for MultiplexWU.')

