%TEST_INSTRENGTHAV

%% Test 1.1: Instantiation - empty

m = InStrengthAv();

prop_number = InStrengthAv.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(InStrengthAv.getPropTag(prop));
	assert( ...
		isa(m.getr(prop), 'NoValue'), ...
		[BRAPH2.STR ':InStrengthAv:' BRAPH2.BUG_FUNC], ...
		['InStrengthAv.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
		'Or there could be an error in InStrengthAv.getr(' int2str(prop) ').'] ...
		)
	assert( ...
		isa(m.getr(TAG), 'NoValue'), ...
		[BRAPH2.STR ':InStrengthAv:' BRAPH2.BUG_FUNC], ...
		['InStrengthAv.getr(''' TAG ''') must be inizialized to NoValue(). ' ...
		'Or there could be an error in InStrengthAv.getr(''' TAG ''').'] ...
		)
end

%% Test 1.2: Instantiation - defaults

warning('off', 'BRAPH2:InStrengthAv')
m = InStrengthAv( ...
	InStrengthAv.ID, InStrengthAv.getPropDefault(InStrengthAv.ID), ...
	InStrengthAv.LABEL, InStrengthAv.getPropDefault(InStrengthAv.LABEL), ...
	InStrengthAv.NOTES, InStrengthAv.getPropDefault(InStrengthAv.NOTES), ...
	InStrengthAv.G, InStrengthAv.getPropDefault(InStrengthAv.G), ...
	InStrengthAv.M, InStrengthAv.getPropDefault(InStrengthAv.M) ...
	);
warning('on', 'BRAPH2:InStrengthAv')

for prop = 1:1:InStrengthAv.getPropNumber()
	TAG = upper(InStrengthAv.getPropTag(prop));
	switch InStrengthAv.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isequal(m.getr(prop), InStrengthAv.getPropDefaultConditioned(prop)), ...
				[BRAPH2.STR ':InStrengthAv:' BRAPH2.BUG_FUNC], ...
				['InStrengthAv.getr(' int2str(prop) ') must be inizialized to its default value ' ...
				'given by InStrengthAv.getPropDefaultConditioned(' int2str(prop) '). ' ...
				'Or there could be an error in InStrengthAv.getr(' int2str(prop) ').'] ...
				)
			assert( ...
				isequal(m.getr(TAG), InStrengthAv.getPropDefaultConditioned(prop)), ...
				[BRAPH2.STR ':InStrengthAv:' BRAPH2.BUG_FUNC], ...
				['InStrengthAv.getr(''' TAG ''') must be inizialized to its default value ' ...
				'given by InStrengthAv.getPropDefaultConditioned(' int2str(prop) '). ' ...
				'Or there could be an error in InStrengthAv.getr(''' TAG ''').'] ...
				)
		case Category.RESULT
			assert( ...
				isa(m.getr(prop), 'NoValue'), ...
				[BRAPH2.STR ':InStrengthAv:' BRAPH2.BUG_FUNC], ...
				['Being a result, InStrengthAv.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
				'Or there could be an error in InStrengthAv.getr(' int2str(prop) ').'] ...
				)
			assert( ...
				isa(m.getr(TAG), 'NoValue'), ...
				[BRAPH2.STR ':InStrengthAv:' BRAPH2.BUG_FUNC], ...
				['Being a result, InStrengthAv.getr(''' TAG ''') must be inizialized to NoValue(). ' ...
				'Or there could be an error in InStrengthAv.getr(''' TAG ''').'] ...
				)
	end
end

%% Test 2: Callbacks

warning('off', 'BRAPH2:InStrengthAv')
m_0 = InStrengthAv( ...
	InStrengthAv.ID, InStrengthAv.getPropDefault(InStrengthAv.ID), ...
	InStrengthAv.LABEL, InStrengthAv.getPropDefault(InStrengthAv.LABEL), ...
	InStrengthAv.NOTES, InStrengthAv.getPropDefault(InStrengthAv.NOTES), ...
	InStrengthAv.G, InStrengthAv.getPropDefault(InStrengthAv.G), ...
	InStrengthAv.M, InStrengthAv.getPropDefault(InStrengthAv.M) ...
	);
warning('on', 'BRAPH2:InStrengthAv')

m_1 = InStrengthAv( ...
	InStrengthAv.ID, Callback('EL', m_0, 'PROP', 1), ...
	InStrengthAv.LABEL, InStrengthAv.getPropDefault(InStrengthAv.LABEL), ...
	InStrengthAv.NOTES, InStrengthAv.getPropDefault(InStrengthAv.NOTES), ...
	InStrengthAv.G, Callback('EL', m_0, 'PROP', 4), ...
	InStrengthAv.M, NoValue() ...
	);
	
prop_number = InStrengthAv.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(InStrengthAv.getPropTag(prop));
	switch InStrengthAv.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(m_1.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':InStrengthAv:' BRAPH2.BUG_FUNC], ...
				['InStrengthAv.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(m_1.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':InStrengthAv:' BRAPH2.BUG_FUNC], ...
				['InStrengthAv.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(m_1.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':InStrengthAv:' BRAPH2.BUG_FUNC], ...
				['InStrengthAv.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end
m_2 = InStrengthAv( ...
	InStrengthAv.ID, Callback('EL', m_1, 'PROP', 1), ...
	InStrengthAv.LABEL, InStrengthAv.getPropDefault(InStrengthAv.LABEL), ...
	InStrengthAv.NOTES, InStrengthAv.getPropDefault(InStrengthAv.NOTES), ...
	InStrengthAv.G, Callback('EL', m_1, 'PROP', 4), ...
	InStrengthAv.M, NoValue() ...
	);
	
prop_number = InStrengthAv.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(InStrengthAv.getPropTag(prop));
	switch InStrengthAv.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(m_2.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':InStrengthAv:' BRAPH2.BUG_FUNC], ...
				['InStrengthAv.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(m_2.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':InStrengthAv:' BRAPH2.BUG_FUNC], ...
				['InStrengthAv.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(m_2.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':InStrengthAv:' BRAPH2.BUG_FUNC], ...
				['InStrengthAv.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end
m_3 = InStrengthAv( ...
	InStrengthAv.ID, Callback('EL', m_2, 'PROP', 1), ...
	InStrengthAv.LABEL, InStrengthAv.getPropDefault(InStrengthAv.LABEL), ...
	InStrengthAv.NOTES, InStrengthAv.getPropDefault(InStrengthAv.NOTES), ...
	InStrengthAv.G, Callback('EL', m_2, 'PROP', 4), ...
	InStrengthAv.M, NoValue() ...
	);
	
prop_number = InStrengthAv.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(InStrengthAv.getPropTag(prop));
	switch InStrengthAv.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(m_3.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':InStrengthAv:' BRAPH2.BUG_FUNC], ...
				['InStrengthAv.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(m_3.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':InStrengthAv:' BRAPH2.BUG_FUNC], ...
				['InStrengthAv.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(m_3.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':InStrengthAv:' BRAPH2.BUG_FUNC], ...
				['InStrengthAv.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end

%% Test 3: Result

warning('off', 'BRAPH2:InStrengthAv')
m = InStrengthAv( ...
	InStrengthAv.ID, InStrengthAv.getPropDefault(InStrengthAv.ID), ...
	InStrengthAv.LABEL, InStrengthAv.getPropDefault(InStrengthAv.LABEL), ...
	InStrengthAv.NOTES, InStrengthAv.getPropDefault(InStrengthAv.NOTES), ...
	InStrengthAv.G, InStrengthAv.getPropDefault(InStrengthAv.G), ...
	InStrengthAv.M, InStrengthAv.getPropDefault(InStrengthAv.M) ...
	);
warning('on', 'BRAPH2:InStrengthAv')

prop_number = InStrengthAv.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(InStrengthAv.getPropTag(prop));
	switch InStrengthAv.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
		case Category.RESULT
			assert( ...
				~isa(m.get(prop),  'NoValue'), ...
				[BRAPH2.STR ':InStrengthAv:' BRAPH2.BUG_FUNC], ...
				['InStrengthAv.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				isa(m.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':InStrengthAv:' BRAPH2.BUG_FUNC], ...
				['InStrengthAv.getr(' int2str(prop) ') must be a NoValue, because it has not been memorized.'] ...
				)
			if isempty(m.getPropSettings(prop))
				assert( ...
					m.checkFormat(m.getPropFormat(prop), m.get(prop)), ...
					[BRAPH2.STR ':InStrengthAv:' BRAPH2.BUG_FUNC], ...
					['InStrengthAv.get(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			else
				assert( ...
					m.checkFormat(m.getPropFormat(prop), m.get(prop), m.getPropSettings(prop)), ...
					[BRAPH2.STR ':InStrengthAv:' BRAPH2.BUG_FUNC], ...
					['InStrengthAv.get(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			end
	end
end

%% Test 4: Memorize

warning('off', 'BRAPH2:InStrengthAv')
m = InStrengthAv( ...
	InStrengthAv.ID, InStrengthAv.getPropDefault(InStrengthAv.ID), ...
	InStrengthAv.LABEL, InStrengthAv.getPropDefault(InStrengthAv.LABEL), ...
	InStrengthAv.NOTES, InStrengthAv.getPropDefault(InStrengthAv.NOTES), ...
	InStrengthAv.G, InStrengthAv.getPropDefault(InStrengthAv.G), ...
	InStrengthAv.M, InStrengthAv.getPropDefault(InStrengthAv.M) ...
	);
warning('on', 'BRAPH2:InStrengthAv')

for prop = 1:1:InStrengthAv.getPropNumber()
	TAG = upper(InStrengthAv.getPropTag(prop));
	switch InStrengthAv.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
		case Category.RESULT
			assert( ...
				~isa(m.get(prop),  'NoValue'), ...
				[BRAPH2.STR ':InStrengthAv:' BRAPH2.BUG_FUNC], ...
				['InStrengthAv.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				isa(m.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':InStrengthAv:' BRAPH2.BUG_FUNC], ...
				['InStrengthAv.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
				)
			assert( ...
				~isa(m.memorize(prop),  'NoValue'), ...
				[BRAPH2.STR ':InStrengthAv:' BRAPH2.BUG_FUNC], ...
				['InStrengthAv.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				~isa(m.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':InStrengthAv:' BRAPH2.BUG_FUNC], ...
				['InStrengthAv.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
				)
			assert( ...
				m.checkFormat(m.getPropFormat(prop), m.getr(prop),m.getPropSettings(prop)), ...
				[BRAPH2.STR ':InStrengthAv:' BRAPH2.BUG_FUNC], ...
				['InStrengthAv.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
				)
	end
end

%% Test 5: GraphWD

B = [
    0  .2 1
    0  0  .8
    1  0  0
    ];
known_in_strength_av = {mean([[1 0.2 1.8]])'};
g = GraphWD('B', B);
s_outside_g = InStrengthAv('G', g);

assert(isequal(s_outside_g.get('M'), known_in_strength_av), ...
    [BRAPH2.STR ':InStrengthAv:' BRAPH2.BUG_ERR], ...
    'InStrengthAv is not being calculated correctly for GraphWD.')

%% Test 6: MultiplexWD

B11 = [
    0   .2  1
    0   0   .8
    1   0   0
    ];
B22 = [
    0  1   .6
    1  0   .4
    0  .4  0
    ];
B = {B11 B22};

known_in_strength_av = {
                 mean([1 .2  1.8])
                 mean([1 1.4 1])
                 };
                                
g = MultiplexWD('B', B);
in_strength_av = InStrengthAv('G', g);

assert(isequal(in_strength_av.get('M'), known_in_strength_av), ...
    [BRAPH2.STR ':InStrengthAv:' BRAPH2.BUG_ERR], ...
    'InStrengthAv is not being calculated correctly for MultiplexWD.')

