%TEST_KCORENESSCENTRALITY

%% Test 1.1: Instantiation - empty

m = KCorenessCentrality();

prop_number = KCorenessCentrality.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(KCorenessCentrality.getPropTag(prop));
	assert( ...
		isa(m.getr(prop), 'NoValue'), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_FUNC], ...
		['KCorenessCentrality.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
		'Or there could be an error in KCorenessCentrality.getr(' int2str(prop) ').'] ...
		)
	assert( ...
		isa(m.getr(TAG), 'NoValue'), ...
		[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_FUNC], ...
		['KCorenessCentrality.getr(''' TAG ''') must be inizialized to NoValue(). ' ...
		'Or there could be an error in KCorenessCentrality.getr(''' TAG ''').'] ...
		)
end

%% Test 1.2: Instantiation - defaults

warning('off', 'BRAPH2:KCorenessCentrality')
m = KCorenessCentrality( ...
	KCorenessCentrality.ID, KCorenessCentrality.getPropDefault(KCorenessCentrality.ID), ...
	KCorenessCentrality.LABEL, KCorenessCentrality.getPropDefault(KCorenessCentrality.LABEL), ...
	KCorenessCentrality.NOTES, KCorenessCentrality.getPropDefault(KCorenessCentrality.NOTES), ...
	KCorenessCentrality.G, KCorenessCentrality.getPropDefault(KCorenessCentrality.G), ...
	KCorenessCentrality.M, KCorenessCentrality.getPropDefault(KCorenessCentrality.M) ...
	);
warning('on', 'BRAPH2:KCorenessCentrality')

for prop = 1:1:KCorenessCentrality.getPropNumber()
	TAG = upper(KCorenessCentrality.getPropTag(prop));
	switch KCorenessCentrality.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isequal(m.getr(prop), KCorenessCentrality.getPropDefaultConditioned(prop)), ...
				[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_FUNC], ...
				['KCorenessCentrality.getr(' int2str(prop) ') must be inizialized to its default value ' ...
				'given by KCorenessCentrality.getPropDefaultConditioned(' int2str(prop) '). ' ...
				'Or there could be an error in KCorenessCentrality.getr(' int2str(prop) ').'] ...
				)
			assert( ...
				isequal(m.getr(TAG), KCorenessCentrality.getPropDefaultConditioned(prop)), ...
				[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_FUNC], ...
				['KCorenessCentrality.getr(''' TAG ''') must be inizialized to its default value ' ...
				'given by KCorenessCentrality.getPropDefaultConditioned(' int2str(prop) '). ' ...
				'Or there could be an error in KCorenessCentrality.getr(''' TAG ''').'] ...
				)
		case Category.RESULT
			assert( ...
				isa(m.getr(prop), 'NoValue'), ...
				[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_FUNC], ...
				['Being a result, KCorenessCentrality.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
				'Or there could be an error in KCorenessCentrality.getr(' int2str(prop) ').'] ...
				)
			assert( ...
				isa(m.getr(TAG), 'NoValue'), ...
				[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_FUNC], ...
				['Being a result, KCorenessCentrality.getr(''' TAG ''') must be inizialized to NoValue(). ' ...
				'Or there could be an error in KCorenessCentrality.getr(''' TAG ''').'] ...
				)
	end
end

%% Test 2: Callbacks

warning('off', 'BRAPH2:KCorenessCentrality')
m_0 = KCorenessCentrality( ...
	KCorenessCentrality.ID, KCorenessCentrality.getPropDefault(KCorenessCentrality.ID), ...
	KCorenessCentrality.LABEL, KCorenessCentrality.getPropDefault(KCorenessCentrality.LABEL), ...
	KCorenessCentrality.NOTES, KCorenessCentrality.getPropDefault(KCorenessCentrality.NOTES), ...
	KCorenessCentrality.G, KCorenessCentrality.getPropDefault(KCorenessCentrality.G), ...
	KCorenessCentrality.M, KCorenessCentrality.getPropDefault(KCorenessCentrality.M) ...
	);
warning('on', 'BRAPH2:KCorenessCentrality')

m_1 = KCorenessCentrality( ...
	KCorenessCentrality.ID, Callback('EL', m_0, 'PROP', 1), ...
	KCorenessCentrality.LABEL, KCorenessCentrality.getPropDefault(KCorenessCentrality.LABEL), ...
	KCorenessCentrality.NOTES, KCorenessCentrality.getPropDefault(KCorenessCentrality.NOTES), ...
	KCorenessCentrality.G, Callback('EL', m_0, 'PROP', 4), ...
	KCorenessCentrality.M, NoValue() ...
	);
	
prop_number = KCorenessCentrality.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(KCorenessCentrality.getPropTag(prop));
	switch KCorenessCentrality.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(m_1.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_FUNC], ...
				['KCorenessCentrality.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(m_1.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_FUNC], ...
				['KCorenessCentrality.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(m_1.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_FUNC], ...
				['KCorenessCentrality.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end
m_2 = KCorenessCentrality( ...
	KCorenessCentrality.ID, Callback('EL', m_1, 'PROP', 1), ...
	KCorenessCentrality.LABEL, KCorenessCentrality.getPropDefault(KCorenessCentrality.LABEL), ...
	KCorenessCentrality.NOTES, KCorenessCentrality.getPropDefault(KCorenessCentrality.NOTES), ...
	KCorenessCentrality.G, Callback('EL', m_1, 'PROP', 4), ...
	KCorenessCentrality.M, NoValue() ...
	);
	
prop_number = KCorenessCentrality.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(KCorenessCentrality.getPropTag(prop));
	switch KCorenessCentrality.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(m_2.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_FUNC], ...
				['KCorenessCentrality.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(m_2.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_FUNC], ...
				['KCorenessCentrality.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(m_2.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_FUNC], ...
				['KCorenessCentrality.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end
m_3 = KCorenessCentrality( ...
	KCorenessCentrality.ID, Callback('EL', m_2, 'PROP', 1), ...
	KCorenessCentrality.LABEL, KCorenessCentrality.getPropDefault(KCorenessCentrality.LABEL), ...
	KCorenessCentrality.NOTES, KCorenessCentrality.getPropDefault(KCorenessCentrality.NOTES), ...
	KCorenessCentrality.G, Callback('EL', m_2, 'PROP', 4), ...
	KCorenessCentrality.M, NoValue() ...
	);
	
prop_number = KCorenessCentrality.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(KCorenessCentrality.getPropTag(prop));
	switch KCorenessCentrality.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(m_3.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_FUNC], ...
				['KCorenessCentrality.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(m_3.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_FUNC], ...
				['KCorenessCentrality.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(m_3.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_FUNC], ...
				['KCorenessCentrality.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end

%% Test 3: Result

warning('off', 'BRAPH2:KCorenessCentrality')
m = KCorenessCentrality( ...
	KCorenessCentrality.ID, KCorenessCentrality.getPropDefault(KCorenessCentrality.ID), ...
	KCorenessCentrality.LABEL, KCorenessCentrality.getPropDefault(KCorenessCentrality.LABEL), ...
	KCorenessCentrality.NOTES, KCorenessCentrality.getPropDefault(KCorenessCentrality.NOTES), ...
	KCorenessCentrality.G, KCorenessCentrality.getPropDefault(KCorenessCentrality.G), ...
	KCorenessCentrality.M, KCorenessCentrality.getPropDefault(KCorenessCentrality.M) ...
	);
warning('on', 'BRAPH2:KCorenessCentrality')

prop_number = KCorenessCentrality.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(KCorenessCentrality.getPropTag(prop));
	switch KCorenessCentrality.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
		case Category.RESULT
			assert( ...
				~isa(m.get(prop),  'NoValue'), ...
				[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_FUNC], ...
				['KCorenessCentrality.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				isa(m.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_FUNC], ...
				['KCorenessCentrality.getr(' int2str(prop) ') must be a NoValue, because it has not been memorized.'] ...
				)
			if isempty(m.getPropSettings(prop))
				assert( ...
					m.checkFormat(m.getPropFormat(prop), m.get(prop)), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_FUNC], ...
					['KCorenessCentrality.get(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			else
				assert( ...
					m.checkFormat(m.getPropFormat(prop), m.get(prop), m.getPropSettings(prop)), ...
					[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_FUNC], ...
					['KCorenessCentrality.get(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			end
	end
end

%% Test 4: Memorize

warning('off', 'BRAPH2:KCorenessCentrality')
m = KCorenessCentrality( ...
	KCorenessCentrality.ID, KCorenessCentrality.getPropDefault(KCorenessCentrality.ID), ...
	KCorenessCentrality.LABEL, KCorenessCentrality.getPropDefault(KCorenessCentrality.LABEL), ...
	KCorenessCentrality.NOTES, KCorenessCentrality.getPropDefault(KCorenessCentrality.NOTES), ...
	KCorenessCentrality.G, KCorenessCentrality.getPropDefault(KCorenessCentrality.G), ...
	KCorenessCentrality.M, KCorenessCentrality.getPropDefault(KCorenessCentrality.M) ...
	);
warning('on', 'BRAPH2:KCorenessCentrality')

for prop = 1:1:KCorenessCentrality.getPropNumber()
	TAG = upper(KCorenessCentrality.getPropTag(prop));
	switch KCorenessCentrality.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
		case Category.RESULT
			assert( ...
				~isa(m.get(prop),  'NoValue'), ...
				[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_FUNC], ...
				['KCorenessCentrality.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				isa(m.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_FUNC], ...
				['KCorenessCentrality.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
				)
			assert( ...
				~isa(m.memorize(prop),  'NoValue'), ...
				[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_FUNC], ...
				['KCorenessCentrality.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				~isa(m.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_FUNC], ...
				['KCorenessCentrality.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
				)
			assert( ...
				m.checkFormat(m.getPropFormat(prop), m.getr(prop),m.getPropSettings(prop)), ...
				[BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_FUNC], ...
				['KCorenessCentrality.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
				)
	end
end

%% Test 5: GraphBU

A = [
    0  1  1  0; 
    1  0  1  1; 
    1  1  0  0;
    0  1  0  0
    ];

known_k_coreness_centrality = {[2 2 2 1]'};

g = GraphBU('B', A);
k_coreness_centrality = KCorenessCentrality('G', g).get('M');

assert(isequal(k_coreness_centrality, known_k_coreness_centrality), ...
    [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_ERR], ...
    'KCorenessCentrality is not being calculated correctly for GraphBU.')

%% Test 6: GraphWD

A = [
    0   1   1  .1; 
    .2  0   1  1; 
    1   1   0  0;
    0   .3  0  0
    ];

known_k_coreness_centrality = {[4 4 4 3]'};

g = GraphWD('B', A);
k_coreness_centrality = KCorenessCentrality('G', g).get('M');

assert(isequal(k_coreness_centrality, known_k_coreness_centrality), ...
    [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_ERR], ...
    'KCorenessCentrality is not being calculated correctly for GraphWD.')

%% Test 7: MultiplexBD

A11 = [
    0  1  1  1; 
    1  0  1  1; 
    1  1  0  0;
    0  1  0  0
    ];

A22 = [
    0  1  1  1; 
    1  0  1  1; 
    1  1  0  0;
    0  1  1  0
    ];
A = {A11 A22};

known_k_coreness_centrality = {
                        [4 4 4 3]'
                        [4 4 4 4]'
                        };

g = MultiplexBD('B', A);
k_coreness_centrality = KCorenessCentrality('G', g).get('M');

assert(isequal(k_coreness_centrality, known_k_coreness_centrality), ...
    [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_ERR], ...
    'KCorenessCentrality is not being calculated correctly for MultiplexBD.')

%% Test 8: MultiplexWU

A11 = [
    0   .1  1  0; 
    .1  0   1  .8; 
    1   1   0  0;
    0   .8  0  0
    ];

A22 = [
    0   .1  1  1; 
    .1  0   1  .8; 
    1   1   0  0;
    1   .8  0  0
    ];
A = {A11 A22};
             
known_k_coreness_centrality = {
                        [2 2 2 1]'
                        [2 2 2 2]'
                        };        

g = MultiplexWU('B', A);
k_coreness_centrality = KCorenessCentrality('G', g).get('M');

assert(isequal(k_coreness_centrality, known_k_coreness_centrality), ...
    [BRAPH2.STR ':KCorenessCentrality:' BRAPH2.BUG_ERR], ...
    'KCorenessCentrality is not being calculated correctly for MultiplexWU.')

