%TEST_PPSUBJECT_ID

%% Test 1.1: Instantiation - empty

pr = PPSubject_ID();

prop_number = PPSubject_ID.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(PPSubject_ID.getPropTag(prop));
	assert( ...
		isa(pr.getr(prop), 'NoValue'), ...
		[BRAPH2.STR ':PPSubject_ID:' BRAPH2.BUG_FUNC], ...
		['PPSubject_ID.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
		'Or there could be an error in PPSubject_ID.getr(' int2str(prop) ').'] ...
		)
	assert( ...
		isa(pr.getr(TAG), 'NoValue'), ...
		[BRAPH2.STR ':PPSubject_ID:' BRAPH2.BUG_FUNC], ...
		['PPSubject_ID.getr(''' TAG ''') must be inizialized to NoValue(). ' ...
		'Or there could be an error in PPSubject_ID.getr(''' TAG ''').'] ...
		)
end

%% Test 1.2: Instantiation - defaults

warning('off', 'BRAPH2:PPSubject_ID')
pr = PPSubject_ID( ...
	PPSubject_ID.ID, PPSubject_ID.getPropDefault(PPSubject_ID.ID), ...
	PPSubject_ID.BKGCOLOR, PPSubject_ID.getPropDefault(PPSubject_ID.BKGCOLOR), ...
	PPSubject_ID.EL, PPSubject_ID.getPropDefault(PPSubject_ID.EL), ...
	PPSubject_ID.PROP, PPSubject_ID.getPropDefault(PPSubject_ID.PROP), ...
	PPSubject_ID.TITLE, PPSubject_ID.getPropDefault(PPSubject_ID.TITLE), ...
	PPSubject_ID.ENABLE, PPSubject_ID.getPropDefault(PPSubject_ID.ENABLE), ...
	PPSubject_ID.WAITBAR, PPSubject_ID.getPropDefault(PPSubject_ID.WAITBAR), ...
	PPSubject_ID.LINES, PPSubject_ID.getPropDefault(PPSubject_ID.LINES), ...
	PPSubject_ID.EDITHEIGHT, PPSubject_ID.getPropDefault(PPSubject_ID.EDITHEIGHT) ...
	);
warning('on', 'BRAPH2:PPSubject_ID')

for prop = 1:1:PPSubject_ID.getPropNumber()
	TAG = upper(PPSubject_ID.getPropTag(prop));
	switch PPSubject_ID.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isequal(pr.getr(prop), PPSubject_ID.getPropDefaultConditioned(prop)), ...
				[BRAPH2.STR ':PPSubject_ID:' BRAPH2.BUG_FUNC], ...
				['PPSubject_ID.getr(' int2str(prop) ') must be inizialized to its default value ' ...
				'given by PPSubject_ID.getPropDefaultConditioned(' int2str(prop) '). ' ...
				'Or there could be an error in PPSubject_ID.getr(' int2str(prop) ').'] ...
				)
			assert( ...
				isequal(pr.getr(TAG), PPSubject_ID.getPropDefaultConditioned(prop)), ...
				[BRAPH2.STR ':PPSubject_ID:' BRAPH2.BUG_FUNC], ...
				['PPSubject_ID.getr(''' TAG ''') must be inizialized to its default value ' ...
				'given by PPSubject_ID.getPropDefaultConditioned(' int2str(prop) '). ' ...
				'Or there could be an error in PPSubject_ID.getr(''' TAG ''').'] ...
				)
		case Category.RESULT
			assert( ...
				isa(pr.getr(prop), 'NoValue'), ...
				[BRAPH2.STR ':PPSubject_ID:' BRAPH2.BUG_FUNC], ...
				['Being a result, PPSubject_ID.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
				'Or there could be an error in PPSubject_ID.getr(' int2str(prop) ').'] ...
				)
			assert( ...
				isa(pr.getr(TAG), 'NoValue'), ...
				[BRAPH2.STR ':PPSubject_ID:' BRAPH2.BUG_FUNC], ...
				['Being a result, PPSubject_ID.getr(''' TAG ''') must be inizialized to NoValue(). ' ...
				'Or there could be an error in PPSubject_ID.getr(''' TAG ''').'] ...
				)
	end
end

%% Test 2: Callbacks

warning('off', 'BRAPH2:PPSubject_ID')
pr_0 = PPSubject_ID( ...
	PPSubject_ID.ID, PPSubject_ID.getPropDefault(PPSubject_ID.ID), ...
	PPSubject_ID.BKGCOLOR, PPSubject_ID.getPropDefault(PPSubject_ID.BKGCOLOR), ...
	PPSubject_ID.EL, PPSubject_ID.getPropDefault(PPSubject_ID.EL), ...
	PPSubject_ID.PROP, PPSubject_ID.getPropDefault(PPSubject_ID.PROP), ...
	PPSubject_ID.TITLE, PPSubject_ID.getPropDefault(PPSubject_ID.TITLE), ...
	PPSubject_ID.ENABLE, PPSubject_ID.getPropDefault(PPSubject_ID.ENABLE), ...
	PPSubject_ID.WAITBAR, PPSubject_ID.getPropDefault(PPSubject_ID.WAITBAR), ...
	PPSubject_ID.LINES, PPSubject_ID.getPropDefault(PPSubject_ID.LINES), ...
	PPSubject_ID.EDITHEIGHT, PPSubject_ID.getPropDefault(PPSubject_ID.EDITHEIGHT) ...
	);
warning('on', 'BRAPH2:PPSubject_ID')

pr_1 = PPSubject_ID( ...
	PPSubject_ID.ID, Callback('EL', pr_0, 'PROP', 1), ...
	PPSubject_ID.BKGCOLOR, PPSubject_ID.getPropDefault(PPSubject_ID.BKGCOLOR), ...
	PPSubject_ID.EL, PPSubject_ID.getPropDefault(PPSubject_ID.EL), ...
	PPSubject_ID.PROP, Callback('EL', pr_0, 'PROP', 4), ...
	PPSubject_ID.TITLE, PPSubject_ID.getPropDefault(PPSubject_ID.TITLE), ...
	PPSubject_ID.ENABLE, PPSubject_ID.getPropDefault(PPSubject_ID.ENABLE), ...
	PPSubject_ID.WAITBAR, PPSubject_ID.getPropDefault(PPSubject_ID.WAITBAR), ...
	PPSubject_ID.LINES, PPSubject_ID.getPropDefault(PPSubject_ID.LINES), ...
	PPSubject_ID.EDITHEIGHT, PPSubject_ID.getPropDefault(PPSubject_ID.EDITHEIGHT) ...
	);
	
prop_number = PPSubject_ID.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(PPSubject_ID.getPropTag(prop));
	switch PPSubject_ID.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(pr_1.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':PPSubject_ID:' BRAPH2.BUG_FUNC], ...
				['PPSubject_ID.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(pr_1.get(prop), pr_0.get(prop)) && ~isa(pr_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':PPSubject_ID:' BRAPH2.BUG_FUNC], ...
				['PPSubject_ID.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(pr_1.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':PPSubject_ID:' BRAPH2.BUG_FUNC], ...
				['PPSubject_ID.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end
pr_2 = PPSubject_ID( ...
	PPSubject_ID.ID, Callback('EL', pr_1, 'PROP', 1), ...
	PPSubject_ID.BKGCOLOR, PPSubject_ID.getPropDefault(PPSubject_ID.BKGCOLOR), ...
	PPSubject_ID.EL, PPSubject_ID.getPropDefault(PPSubject_ID.EL), ...
	PPSubject_ID.PROP, Callback('EL', pr_1, 'PROP', 4), ...
	PPSubject_ID.TITLE, PPSubject_ID.getPropDefault(PPSubject_ID.TITLE), ...
	PPSubject_ID.ENABLE, PPSubject_ID.getPropDefault(PPSubject_ID.ENABLE), ...
	PPSubject_ID.WAITBAR, PPSubject_ID.getPropDefault(PPSubject_ID.WAITBAR), ...
	PPSubject_ID.LINES, PPSubject_ID.getPropDefault(PPSubject_ID.LINES), ...
	PPSubject_ID.EDITHEIGHT, PPSubject_ID.getPropDefault(PPSubject_ID.EDITHEIGHT) ...
	);
	
prop_number = PPSubject_ID.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(PPSubject_ID.getPropTag(prop));
	switch PPSubject_ID.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(pr_2.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':PPSubject_ID:' BRAPH2.BUG_FUNC], ...
				['PPSubject_ID.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(pr_2.get(prop), pr_0.get(prop)) && ~isa(pr_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':PPSubject_ID:' BRAPH2.BUG_FUNC], ...
				['PPSubject_ID.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(pr_2.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':PPSubject_ID:' BRAPH2.BUG_FUNC], ...
				['PPSubject_ID.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end
pr_3 = PPSubject_ID( ...
	PPSubject_ID.ID, Callback('EL', pr_2, 'PROP', 1), ...
	PPSubject_ID.BKGCOLOR, PPSubject_ID.getPropDefault(PPSubject_ID.BKGCOLOR), ...
	PPSubject_ID.EL, PPSubject_ID.getPropDefault(PPSubject_ID.EL), ...
	PPSubject_ID.PROP, Callback('EL', pr_2, 'PROP', 4), ...
	PPSubject_ID.TITLE, PPSubject_ID.getPropDefault(PPSubject_ID.TITLE), ...
	PPSubject_ID.ENABLE, PPSubject_ID.getPropDefault(PPSubject_ID.ENABLE), ...
	PPSubject_ID.WAITBAR, PPSubject_ID.getPropDefault(PPSubject_ID.WAITBAR), ...
	PPSubject_ID.LINES, PPSubject_ID.getPropDefault(PPSubject_ID.LINES), ...
	PPSubject_ID.EDITHEIGHT, PPSubject_ID.getPropDefault(PPSubject_ID.EDITHEIGHT) ...
	);
	
prop_number = PPSubject_ID.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(PPSubject_ID.getPropTag(prop));
	switch PPSubject_ID.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(pr_3.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':PPSubject_ID:' BRAPH2.BUG_FUNC], ...
				['PPSubject_ID.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(pr_3.get(prop), pr_0.get(prop)) && ~isa(pr_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':PPSubject_ID:' BRAPH2.BUG_FUNC], ...
				['PPSubject_ID.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(pr_3.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':PPSubject_ID:' BRAPH2.BUG_FUNC], ...
				['PPSubject_ID.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end

%% Test 3: Result

warning('off', 'BRAPH2:PPSubject_ID')
pr = PPSubject_ID( ...
	PPSubject_ID.ID, PPSubject_ID.getPropDefault(PPSubject_ID.ID), ...
	PPSubject_ID.BKGCOLOR, PPSubject_ID.getPropDefault(PPSubject_ID.BKGCOLOR), ...
	PPSubject_ID.EL, PPSubject_ID.getPropDefault(PPSubject_ID.EL), ...
	PPSubject_ID.PROP, PPSubject_ID.getPropDefault(PPSubject_ID.PROP), ...
	PPSubject_ID.TITLE, PPSubject_ID.getPropDefault(PPSubject_ID.TITLE), ...
	PPSubject_ID.ENABLE, PPSubject_ID.getPropDefault(PPSubject_ID.ENABLE), ...
	PPSubject_ID.WAITBAR, PPSubject_ID.getPropDefault(PPSubject_ID.WAITBAR), ...
	PPSubject_ID.LINES, PPSubject_ID.getPropDefault(PPSubject_ID.LINES), ...
	PPSubject_ID.EDITHEIGHT, PPSubject_ID.getPropDefault(PPSubject_ID.EDITHEIGHT) ...
	);
warning('on', 'BRAPH2:PPSubject_ID')

prop_number = PPSubject_ID.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(PPSubject_ID.getPropTag(prop));
	switch PPSubject_ID.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
		case Category.RESULT
			assert( ...
				~isa(pr.get(prop),  'NoValue'), ...
				[BRAPH2.STR ':PPSubject_ID:' BRAPH2.BUG_FUNC], ...
				['PPSubject_ID.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				isa(pr.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':PPSubject_ID:' BRAPH2.BUG_FUNC], ...
				['PPSubject_ID.getr(' int2str(prop) ') must be a NoValue, because it has not been memorized.'] ...
				)
			if isempty(pr.getPropSettings(prop))
				assert( ...
					pr.checkFormat(pr.getPropFormat(prop), pr.get(prop)), ...
					[BRAPH2.STR ':PPSubject_ID:' BRAPH2.BUG_FUNC], ...
					['PPSubject_ID.get(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			else
				assert( ...
					pr.checkFormat(pr.getPropFormat(prop), pr.get(prop), pr.getPropSettings(prop)), ...
					[BRAPH2.STR ':PPSubject_ID:' BRAPH2.BUG_FUNC], ...
					['PPSubject_ID.get(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			end
	end
end

%% Test 4: Memorize

warning('off', 'BRAPH2:PPSubject_ID')
pr = PPSubject_ID( ...
	PPSubject_ID.ID, PPSubject_ID.getPropDefault(PPSubject_ID.ID), ...
	PPSubject_ID.BKGCOLOR, PPSubject_ID.getPropDefault(PPSubject_ID.BKGCOLOR), ...
	PPSubject_ID.EL, PPSubject_ID.getPropDefault(PPSubject_ID.EL), ...
	PPSubject_ID.PROP, PPSubject_ID.getPropDefault(PPSubject_ID.PROP), ...
	PPSubject_ID.TITLE, PPSubject_ID.getPropDefault(PPSubject_ID.TITLE), ...
	PPSubject_ID.ENABLE, PPSubject_ID.getPropDefault(PPSubject_ID.ENABLE), ...
	PPSubject_ID.WAITBAR, PPSubject_ID.getPropDefault(PPSubject_ID.WAITBAR), ...
	PPSubject_ID.LINES, PPSubject_ID.getPropDefault(PPSubject_ID.LINES), ...
	PPSubject_ID.EDITHEIGHT, PPSubject_ID.getPropDefault(PPSubject_ID.EDITHEIGHT) ...
	);
warning('on', 'BRAPH2:PPSubject_ID')

for prop = 1:1:PPSubject_ID.getPropNumber()
	TAG = upper(PPSubject_ID.getPropTag(prop));
	switch PPSubject_ID.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
		case Category.RESULT
			assert( ...
				~isa(pr.get(prop),  'NoValue'), ...
				[BRAPH2.STR ':PPSubject_ID:' BRAPH2.BUG_FUNC], ...
				['PPSubject_ID.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				isa(pr.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':PPSubject_ID:' BRAPH2.BUG_FUNC], ...
				['PPSubject_ID.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
				)
			assert( ...
				~isa(pr.memorize(prop),  'NoValue'), ...
				[BRAPH2.STR ':PPSubject_ID:' BRAPH2.BUG_FUNC], ...
				['PPSubject_ID.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				~isa(pr.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':PPSubject_ID:' BRAPH2.BUG_FUNC], ...
				['PPSubject_ID.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
				)
			assert( ...
				pr.checkFormat(pr.getPropFormat(prop), pr.getr(prop),pr.getPropSettings(prop)), ...
				[BRAPH2.STR ':PPSubject_ID:' BRAPH2.BUG_FUNC], ...
				['PPSubject_ID.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
				)
	end
end

