%% ¡header!
NNGroup < Group (gr, group of subjects) is a group of subjects for a neural network analysis.

%%% ¡description!
NNGroup represents a group of NNSubjects whose class is defined in the property SUB_CLASS.
NNGroup provides the ready-to-use inputs and targets from all NN subjects, for 
performing a neural network analysis.

%%% ¡seealso!
NNSubject

%% ¡props!

%%% ¡prop!
INPUTS (result, cell) is a collection of the input from all NN subjects.
%%%% ¡calculate!
if gr.get('SUB_DICT').length() == 0
    inputs = {};
else
    inputs = cellfun(@(x) x.get('INPUT'), gr.get('SUB_DICT').getItems(), 'UniformOutput', false);
end

value = inputs;

%%% ¡prop!
TARGETS (result, cell) is a collection of the target from all NN subjects.
%%%% ¡calculate!
if gr.get('SUB_DICT').length() == 0
    targets = {};
else
    targets = cellfun(@(x) x.get('TARGET'), gr.get('SUB_DICT').getItems(), 'UniformOutput', false);
end

value = targets;

%%% ¡prop!
GRAPH_CLASS (result, class) is the graph obtained from this analysis.
%%%% ¡settings!
'Graph'
%%%% ¡calculate!
sub_dict = gr.get('SUB_DICT');
if sub_dict.length == 0
    value = 'Graph';
else
    sub = sub_dict.getItem(1);
    value = sub.get('G').getClass();
end

%%% ¡prop!
FEATURE_SELECTION_MASK (data, cell) is a feature mask generated by feature selection analysis.
