%% ¡header!
NNSubject < Subject (sub, subject with connectivity matrix) is a subject for the neural network analysis.

%%% ¡description!
NNSubject contains the required information of individual to be analyzed by neural network analysis.

%%% ¡seealso!
Subject, NNGroup

%% ¡props!

%%% ¡prop!
G (data, item) is a graph obtained from the data of the subject.
%%%% ¡settings!
'Graph'

%%% ¡prop!
INPUT (data, cell) is the input obtained from the data of subject for the neural network analysis.
% % %%%% ¡gui!
% % pr = PPSubjectCON_CON('EL', sub, 'PROP', SubjectCON.CON, varargin{:})

%%% ¡prop!
FEATURE_MASK (data, cell) is an feature mask generated by feature selection analysis.

%%% ¡prop!
MASKED_INPUT (result, cell) is the masked input with the feature mask.
%%%% ¡calculate!
feature_mask = sub.get('FEATURE_MASK');
input = sub.get('INPUT');
for i = 1:1:length(feature_mask)
    input_per_cluster = input{i};
    mask_per_cluster = feature_mask{i};
    input_per_cluster(mask_per_cluster == 0) = 0;
    masked_input{j} = input_per_cluster;
end

value = masked_input;

% % %%%% ¡gui!
% % pr = PPSubjectCON_CON('EL', sub, 'PROP', SubjectCON.CON, varargin{:});

%%% ¡prop!
TARGET_NAME (data, string) is the name of the target for the neural network analysis.

%%% ¡prop!
TARGET (data, cell) is the encoded values of a target for the neural network analysis.

%%% ¡prop!
PREDICTION (data, cell) is the prediction of the subject from the neural network analysis.

%%% ¡prop!
BA (data, item) is a brain atlas.
%%%% ¡settings!
'BrainAtlas'
%%%% ¡default!
BrainAtlas()

%%% ¡prop!
age (data, scalar) is a scalar number containing the age of the subject.
%%%% ¡default!
0

%%% ¡prop!
sex (data, option) is an option containing the sex of the subject (female/male).
%%%% ¡default!
'unassigned'
%%%% ¡settings!
{'Female', 'Male', 'unassigned'}