%TEST_GRAPHWD

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	g = GraphWD();
	 
	% get('ELCLASS')
	if isa(GraphWD, 'ConcreteElement')
		assert(strcmp(GraphWD().get('ELCLASS'), 'GraphWD'), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'GraphWD().get(''ELCLASS'') should return ''GraphWD''.')
	end
	 
	% getBuild()
	assert(GraphWD.getBuild() == 1 && GraphWD.getBuild() > 0, ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'GraphWD.getBuild() should return the GraphWD build number.')
	assert(g.getBuild() == 1 && g.getBuild() > 0 , ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'g.getBuild() should return the GraphWD build number.')
	assert(Element.getBuild(g) == 1 && Element.getBuild(g) > 0, ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(g) should return the GraphWD build number.')
	assert(Element.getBuild('GraphWD') == 1 && Element.getBuild('GraphWD') > 0, ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''GraphWD'') should return the GraphWD build number.')
	 
	% getClass()
	assert(strcmp(GraphWD.getClass(), 'GraphWD'), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'GraphWD.getClass() should return ''GraphWD''.')
	assert(strcmp(g.getClass(), 'GraphWD'), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'g.getClass() should return ''GraphWD''.')
	assert(strcmp(Element.getClass(g), 'GraphWD'), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(g) should return ''GraphWD''.')
	assert(strcmp(Element.getClass('GraphWD'), 'GraphWD'), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''GraphWD'') should return ''GraphWD''.')
	 
	% getSubclasses()
	assert(isequal(GraphWD.getSubclasses(), subclasses('GraphWD', [], [], true)), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'GraphWD.getSubclasses() should return the same result as subclasses(''GraphWD'', [], [], true).')
	assert(isequal(g.getSubclasses(), subclasses('GraphWD', [], [], true)), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''GraphWD'', [], [], true).')
	assert(isequal(Element.getSubclasses(g), subclasses('GraphWD', [], [], true)), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(g) should return the same result as subclasses(''GraphWD'', [], [], true).')
	assert(isequal(Element.getSubclasses('GraphWD'), subclasses('GraphWD', [], [], true)), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''GraphWD'') should return the same result as subclasses(''GraphWD'', [], [], true).')
	 
	% getProps()
	assert(isempty(GraphWD.getProps()) || isequal(GraphWD.getProps(), 1:1:length(GraphWD.getProps())), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'GraphWD.getProps() should return a row vector [1:1:N].')
	assert(isempty(GraphWD.getProps()) || isequal(g.getProps(), 1:1:length(GraphWD.getProps())), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'g.getProps() should return a row vector [1:1:N].')
	assert(isempty(GraphWD.getProps()) || isequal(Element.getProps(g), 1:1:length(GraphWD.getProps())), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(g) should return a row vector [1:1:N].')
	assert(isempty(GraphWD.getProps()) || isequal(Element.getProps('GraphWD'), 1:1:length(GraphWD.getProps())), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''GraphWD'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) GraphWD.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(GraphWD.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(GraphWD.getProps())), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'GraphWD.getProps(category) does not work.')
	tmp = cellfun(@(category) g.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(GraphWD.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(GraphWD.getProps())), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'g.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(g, category), categories, 'UniformOutput', false);
	assert(isempty(GraphWD.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(GraphWD.getProps())), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(g, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('GraphWD', category), categories, 'UniformOutput', false);
	assert(isempty(GraphWD.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(GraphWD.getProps())), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''GraphWD'', category) does not work.')
	 
	% getPropNumber()
	assert(GraphWD.getPropNumber() == length(GraphWD.getProps()), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'GraphWD.getPropNumber() should return the number of properties.')
	assert(g.getPropNumber() == length(GraphWD.getProps()), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'g.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(g) == length(GraphWD.getProps()), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(g) should return the number of properties.')
	assert(Element.getPropNumber('GraphWD') == length(GraphWD.getProps()), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''GraphWD'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) GraphWD.getPropNumber(category), categories)) == GraphWD.getPropNumber(), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'GraphWD.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) g.getPropNumber(category), categories)) == GraphWD.getPropNumber(), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'g.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(g, category), categories)) == GraphWD.getPropNumber(), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(g, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('GraphWD', category), categories)) == GraphWD.getPropNumber(), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''GraphWD'', category) does not work.')
	 
	% existsProp(prop)
	assert(~GraphWD.existsProp(NaN), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'GraphWD.existsProp(prop) does not work.')
	assert(~g.existsProp(NaN), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'g.existsProp(prop) does not work.')
	assert(~Element.existsProp(g, NaN), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(g, prop) does not work.')
	assert(~Element.existsProp('GraphWD', NaN), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''GraphWD'', prop) does not work.')
	 
	assert_with_error('GraphWD.existsProp(NaN)', [BRAPH2.STR ':GraphWD:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':GraphWD:' BRAPH2.WRONG_INPUT], g)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':GraphWD:' BRAPH2.WRONG_INPUT], g)
	assert_with_error('Element.existsProp(''GraphWD'', NaN)', [BRAPH2.STR ':GraphWD:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:GraphWD.getPropNumber()
		assert(GraphWD.existsProp(prop), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'GraphWD.existsProp(prop) does not work.')
		assert(g.existsProp(prop), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'g.existsProp(prop) does not work.')
		assert(Element.existsProp(g, prop), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(g, prop) does not work.')
		assert(Element.existsProp('GraphWD', prop), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''GraphWD'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~GraphWD.existsTag(''), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'GraphWD.existsTag(tag) does not work.')
	assert(~g.existsTag(''), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'g.existsTag(tag) does not work.')
	assert(~Element.existsTag(g, ''), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(g, tag) does not work.')
	assert(~Element.existsTag('GraphWD', ''), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''GraphWD'', tag) does not work.')
	 
	assert_with_error('GraphWD.existsTag('''')', [BRAPH2.STR ':GraphWD:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':GraphWD:' BRAPH2.WRONG_INPUT], g)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':GraphWD:' BRAPH2.WRONG_INPUT], g)
	assert_with_error('Element.existsTag(''GraphWD'', '''')', [BRAPH2.STR ':GraphWD:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:GraphWD.getPropNumber()
		tag = g.getPropTag(prop);
		assert(GraphWD.existsTag(tag), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'GraphWD.existsTag(tag) does not work.')
		assert(g.existsTag(tag), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'g.existsTag(tag) does not work.')
		assert(Element.existsTag(g, tag), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(g, tga) does not work.')
		assert(Element.existsTag('GraphWD', tag), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''GraphWD'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:GraphWD.getPropNumber()
		assert(GraphWD.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'GraphWD.getPropProp(prop) does not work.')
		assert(g.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'g.getPropProp(prop) does not work.')
		assert(Element.getPropProp(g, prop) == prop, ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(g, prop) does not work.')
		assert(Element.getPropProp('GraphWD', prop) == prop, ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''GraphWD'', prop) does not work.')
	 
		tag = g.getPropTag(prop);
		assert(GraphWD.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'GraphWD.getPropProp(tag) does not work.')
		assert(g.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'g.getPropProp(tag) does not work.')
		assert(Element.getPropProp(g, tag) == prop, ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(g, tag) does not work.')
		assert(Element.getPropProp('GraphWD', prop) == prop, ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''GraphWD'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:GraphWD.getPropNumber()
		tag = g.getPropTag(prop);
	 
		assert(strcmp(GraphWD.getPropTag(prop), tag), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'GraphWD.getPropTag(prop) does not work.')
		assert(strcmp(g.getPropTag(prop), tag), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'g.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(g, prop), tag), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(g, prop) does not work.')
		assert(strcmp(Element.getPropTag('GraphWD', prop), tag), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''GraphWD'', prop) does not work.')
	 
		assert(strcmp(GraphWD.getPropTag(tag), tag), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'GraphWD.getPropTag(tag) does not work.')
		assert(strcmp(g.getPropTag(tag), tag), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'g.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(g, tag), tag), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(g, tag) does not work.')
		assert(strcmp(Element.getPropTag('GraphWD', prop), tag), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''GraphWD'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:GraphWD.getPropNumber()
		tag = g.getPropTag(prop);
	 
		assert(Category.existsCategory(GraphWD.getPropCategory(prop)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'GraphWD.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(g.getPropCategory(prop)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'g.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(g, prop)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(g, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(g, prop)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''GraphWD'', prop) does not work.')
	 
		assert(Category.existsCategory(GraphWD.getPropCategory(tag)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'GraphWD.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(g.getPropCategory(tag)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'g.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(g, tag)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(g, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(g, tag)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''GraphWD'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:GraphWD.getPropNumber()
		tag = g.getPropTag(prop);
	 
		assert(Format.existsFormat(GraphWD.getPropFormat(prop)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'GraphWD.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(g.getPropFormat(prop)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'g.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(g, prop)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(g, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(g, prop)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''GraphWD'', prop) does not work.')
	 
		assert(Format.existsFormat(GraphWD.getPropFormat(tag)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'GraphWD.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(g.getPropFormat(tag)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'g.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(g, tag)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(g, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(g, tag)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''GraphWD'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:GraphWD.getPropNumber()
		tag = g.getPropTag(prop);
	 
		assert(ischar(GraphWD.getPropDescription(prop)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'GraphWD.getPropDescription(prop) does not work.')
		assert(ischar(g.getPropDescription(prop)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'g.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(g, prop)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(g, prop) does not work.')
		assert(ischar(Element.getPropDescription(g, prop)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''GraphWD'', prop) does not work.')
	 
		assert(ischar(GraphWD.getPropDescription(tag)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'GraphWD.getPropDescription(tag) does not work.')
		assert(ischar(g.getPropDescription(tag)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'g.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(g, tag)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(g, tag) does not work.')
		assert(ischar(Element.getPropDescription(g, tag)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''GraphWD'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:GraphWD.getPropNumber()
		tag = g.getPropTag(prop);
	 
		settings = GraphWD.getPropSettings(prop);
		settings = g.getPropSettings(prop);
		settings = Element.getPropSettings(g, prop);
		settings = Element.getPropSettings('GraphWD', prop);
	 
		settings = GraphWD.getPropSettings(tag);
		settings = g.getPropSettings(tag);
		settings = Element.getPropSettings(g, tag);
		settings = Element.getPropSettings('GraphWD', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:GraphWD.getPropNumber()
		tag = g.getPropTag(prop);
	 
		default = GraphWD.getPropDefault(prop);
		default = g.getPropDefault(prop);
		default = Element.getPropDefault(g, prop);
		default = Element.getPropDefault('GraphWD', prop);
	 
		default = GraphWD.getPropDefault(tag);
		default = g.getPropDefault(tag);
		default = Element.getPropDefault(g, tag);
		default = Element.getPropDefault('GraphWD', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:GraphWD.getPropNumber()
		tag = g.getPropTag(prop);
	 
		conditioned_default = GraphWD.getPropDefaultConditioned(prop);
		conditioned_default = g.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(g, prop);
		conditioned_default = Element.getPropDefaultConditioned('GraphWD', prop);
	 
		conditioned_default = GraphWD.getPropDefaultConditioned(tag);
		conditioned_default = g.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(g, tag);
		conditioned_default = Element.getPropDefaultConditioned('GraphWD', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:GraphWD.getPropNumber()
		tag = g.getPropTag(prop);
	 
		assert(~GraphWD.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'GraphWD.checkProp(prop, value) does not work.')
		assert(~g.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'g.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(g, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(g, prop, value) does not work.')
		assert(~Element.checkProp('GraphWD', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''GraphWD'', prop, value) does not work.')
	 
		assert_with_error('GraphWD.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':GraphWD:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':GraphWD:' BRAPH2.WRONG_INPUT], prop, g)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':GraphWD:' BRAPH2.WRONG_INPUT], prop, g)
		assert_with_error('Element.checkProp(''GraphWD'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':GraphWD:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~GraphWD.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'GraphWD.checkProp(tag, value) does not work.')
		assert(~g.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'g.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(g, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(g, tag, value) does not work.')
		assert(~Element.checkProp('GraphWD', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''GraphWD'', tag, value) does not work.')
	 
		assert_with_error('GraphWD.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':GraphWD:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':GraphWD:' BRAPH2.WRONG_INPUT], tag, g)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':GraphWD:' BRAPH2.WRONG_INPUT], tag, g)
		assert_with_error('Element.checkProp(''GraphWD'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':GraphWD:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(GraphWD.checkProp(prop, Element.getPropDefaultConditioned(GraphWD, prop)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'GraphWD.checkProp(prop, <conditioned default value>) does not work.')
		assert(g.checkProp(prop, Element.getPropDefaultConditioned(GraphWD, prop)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'g.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(g, prop, Element.getPropDefaultConditioned(GraphWD, prop)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(g, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('GraphWD', prop, Element.getPropDefaultConditioned(GraphWD, prop)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''GraphWD'', prop, <conditioned default value>) does not work.')
	 
		assert(GraphWD.checkProp(tag, Element.getPropDefaultConditioned(GraphWD, prop)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'GraphWD.checkProp(tag, <conditioned default value>) does not work.')
		assert(g.checkProp(tag, Element.getPropDefaultConditioned(GraphWD, prop)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'g.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(g, tag, Element.getPropDefaultConditioned(GraphWD, prop)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(g, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('GraphWD', tag, Element.getPropDefaultConditioned(GraphWD, prop)), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''GraphWD'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	g = GraphWD( ...
		GraphWD.ELCLASS, GraphWD.getNoValue(), ...
		GraphWD.NAME, GraphWD.getNoValue(), ...
		GraphWD.DESCRIPTION, GraphWD.getNoValue(), ...
		GraphWD.TEMPLATE, GraphWD.getPropDefault(GraphWD.TEMPLATE), ...
		GraphWD.ID, GraphWD.getPropDefault(GraphWD.ID), ...
		GraphWD.LABEL, GraphWD.getPropDefault(GraphWD.LABEL), ...
		GraphWD.NOTES, GraphWD.getPropDefault(GraphWD.NOTES), ...
		GraphWD.TOSTRING, GraphWD.getNoValue(), ...
		GraphWD.GRAPH_TYPE, GraphWD.getNoValue(), ...
		GraphWD.CONNECTIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.DIRECTIONALITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.SELFCONNECTIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.NEGATIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.LAYERTICKS, GraphWD.getPropDefault(GraphWD.LAYERTICKS), ...
		GraphWD.ALAYERTICKS, GraphWD.getNoValue(), ...
		GraphWD.LAYERLABELS, GraphWD.getPropDefault(GraphWD.LAYERLABELS), ...
		GraphWD.ALAYERLABELS, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONTICKS, GraphWD.getPropDefault(GraphWD.PARTITIONTICKS), ...
		GraphWD.APARTITIONTICKS, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONLABELS, GraphWD.getPropDefault(GraphWD.PARTITIONLABELS), ...
		GraphWD.APARTITIONLABELS, GraphWD.getNoValue(), ...
		GraphWD.NODELABELS, GraphWD.getPropDefault(GraphWD.NODELABELS), ...
		GraphWD.ANODELABELS, GraphWD.getNoValue(), ...
		GraphWD.RANDOMIZE, GraphWD.getPropDefault(GraphWD.RANDOMIZE), ...
		GraphWD.RANDOM_SEED, GraphWD.getPropDefault(GraphWD.RANDOM_SEED), ...
		GraphWD.A, GraphWD.getNoValue(), ...
		GraphWD.A_CHECK, GraphWD.getNoValue(), ...
		GraphWD.NODENUMBER, GraphWD.getNoValue(), ...
		GraphWD.LAYERNUMBER, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONS, GraphWD.getNoValue(), ...
		GraphWD.M_DICT, GraphWD.getNoValue(), ...
		GraphWD.COMPATIBLE_MEASURES, GraphWD.getNoValue(), ...
		GraphWD.MEASURE, GraphWD.getNoValue(), ...
		GraphWD.PFGA, GraphWD.getPropDefault(GraphWD.PFGA), ...
		GraphWD.PFGH, GraphWD.getPropDefault(GraphWD.PFGH), ...
		GraphWD.B, GraphWD.getPropDefault(GraphWD.B), ...
		GraphWD.SEMIPOSITIVIZE_RULE, GraphWD.getPropDefault(GraphWD.SEMIPOSITIVIZE_RULE), ...
		GraphWD.STANDARDIZE_RULE, GraphWD.getPropDefault(GraphWD.STANDARDIZE_RULE), ...
		GraphWD.ATTEMPTSPEREDGE, GraphWD.getPropDefault(GraphWD.ATTEMPTSPEREDGE), ...
		GraphWD.NUMBEROFWEIGHTS, GraphWD.getPropDefault(GraphWD.NUMBEROFWEIGHTS), ...
		GraphWD.RANDOMIZATION, GraphWD.getNoValue() ...
		);
	 
	for prop = 1:1:GraphWD.getPropNumber()
	 
		% excluded props
		if any(prop == [GraphWD.PFGA GraphWD.PFGH])
			continue
		end
	 
		TAG = upper(GraphWD.getPropTag(prop));
		switch GraphWD.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					g.getr(prop) == GraphWD.getNoValue(), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['Being a ' GraphWD.getCategoryName(GraphWD.getPropCategory(prop)) ', GraphWD.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in GraphWD.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					g.getr(TAG) == GraphWD.getNoValue(), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['Being a ' GraphWD.getCategoryName(GraphWD.getPropCategory(prop)) ', GraphWD.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in GraphWD.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(g.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(g.getPropSettings(prop))
					assert( ...
						g.checkFormat(g.getPropFormat(prop), g.get(prop)), ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						['GraphWD.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						g.checkFormat(g.getPropFormat(prop), g.get(prop), g.getPropSettings(prop)), ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						['GraphWD.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					g.getr(prop) == GraphWD.getNoValue(), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['Being a ' GraphWD.getCategoryName(GraphWD.getPropCategory(prop)) ', GraphWD.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in GraphWD.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					g.getr(TAG) == GraphWD.getNoValue(), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['Being a ' GraphWD.getCategoryName(GraphWD.getPropCategory(prop)) ', GraphWD.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in GraphWD.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':GraphWD']);
				assert( ...
					~isa(g.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(g.getPropSettings(prop))
					assert( ...
						g.checkFormat(g.getPropFormat(prop), g.get(prop)), ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						['GraphWD.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						g.checkFormat(g.getPropFormat(prop), g.get(prop), g.getPropSettings(prop)), ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						['GraphWD.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(g.getr(prop), GraphWD.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by GraphWD.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in GraphWD.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(g.getr(TAG), GraphWD.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.getr(' TAG ') must be inizialized to its default value ' ...
					'given by GraphWD.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in GraphWD.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	g = GraphWD( ...
		GraphWD.ELCLASS, GraphWD.getNoValue(), ...
		GraphWD.NAME, GraphWD.getNoValue(), ...
		GraphWD.DESCRIPTION, GraphWD.getNoValue(), ...
		GraphWD.TEMPLATE, GraphWD.getPropDefault(GraphWD.TEMPLATE), ...
		GraphWD.ID, GraphWD.getPropDefault(GraphWD.ID), ...
		GraphWD.LABEL, GraphWD.getPropDefault(GraphWD.LABEL), ...
		GraphWD.NOTES, GraphWD.getPropDefault(GraphWD.NOTES), ...
		GraphWD.TOSTRING, GraphWD.getNoValue(), ...
		GraphWD.GRAPH_TYPE, GraphWD.getNoValue(), ...
		GraphWD.CONNECTIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.DIRECTIONALITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.SELFCONNECTIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.NEGATIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.LAYERTICKS, GraphWD.getPropDefault(GraphWD.LAYERTICKS), ...
		GraphWD.ALAYERTICKS, GraphWD.getNoValue(), ...
		GraphWD.LAYERLABELS, GraphWD.getPropDefault(GraphWD.LAYERLABELS), ...
		GraphWD.ALAYERLABELS, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONTICKS, GraphWD.getPropDefault(GraphWD.PARTITIONTICKS), ...
		GraphWD.APARTITIONTICKS, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONLABELS, GraphWD.getPropDefault(GraphWD.PARTITIONLABELS), ...
		GraphWD.APARTITIONLABELS, GraphWD.getNoValue(), ...
		GraphWD.NODELABELS, GraphWD.getPropDefault(GraphWD.NODELABELS), ...
		GraphWD.ANODELABELS, GraphWD.getNoValue(), ...
		GraphWD.RANDOMIZE, GraphWD.getPropDefault(GraphWD.RANDOMIZE), ...
		GraphWD.RANDOM_SEED, GraphWD.getPropDefault(GraphWD.RANDOM_SEED), ...
		GraphWD.A, GraphWD.getNoValue(), ...
		GraphWD.A_CHECK, GraphWD.getNoValue(), ...
		GraphWD.NODENUMBER, GraphWD.getNoValue(), ...
		GraphWD.LAYERNUMBER, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONS, GraphWD.getNoValue(), ...
		GraphWD.M_DICT, GraphWD.getNoValue(), ...
		GraphWD.COMPATIBLE_MEASURES, GraphWD.getNoValue(), ...
		GraphWD.MEASURE, GraphWD.getNoValue(), ...
		GraphWD.PFGA, GraphWD.getPropDefault(GraphWD.PFGA), ...
		GraphWD.PFGH, GraphWD.getPropDefault(GraphWD.PFGH), ...
		GraphWD.B, GraphWD.getPropDefault(GraphWD.B), ...
		GraphWD.SEMIPOSITIVIZE_RULE, GraphWD.getPropDefault(GraphWD.SEMIPOSITIVIZE_RULE), ...
		GraphWD.STANDARDIZE_RULE, GraphWD.getPropDefault(GraphWD.STANDARDIZE_RULE), ...
		GraphWD.ATTEMPTSPEREDGE, GraphWD.getPropDefault(GraphWD.ATTEMPTSPEREDGE), ...
		GraphWD.NUMBEROFWEIGHTS, GraphWD.getPropDefault(GraphWD.NUMBEROFWEIGHTS), ...
		GraphWD.RANDOMIZATION, GraphWD.getNoValue() ...
		);
	 
	for prop = 1:1:GraphWD.getPropNumber()
	 
		% excluded props
		if any(prop == [GraphWD.PFGA GraphWD.PFGH])
			continue
		end
	 
		TAG = upper(GraphWD.getPropTag(prop));
		switch GraphWD.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(g.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(g.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(g.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(g.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					g.checkFormat(g.getPropFormat(prop), g.getr(prop),g.getPropSettings(prop)), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':GraphWD']);
				assert( ...
					~isa(g.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(g.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':GraphWD']);
	% 			assert( ...
	% 				~isa(g.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
	% 				['GraphWD.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(g.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
	% 				['GraphWD.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				g.checkFormat(g.getPropFormat(prop), g.getr(prop),g.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
	% 				['GraphWD.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':GraphWD']);
				assert( ...
					~isa(g.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(g.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(g.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(g.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					g.checkFormat(g.getPropFormat(prop), g.getr(prop),g.getPropSettings(prop)), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if g.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:GraphWD');
					delete(ancestor(g.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(GraphWD.getProps(Category.RESULT))
		for prop = 1:1:GraphWD.getPropNumber()
	 
			% excluded props
			if any(prop == [GraphWD.PFGA GraphWD.PFGH])
				continue
			end
	 
			switch GraphWD.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						g.isLocked(prop), ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						['GraphWD.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~g.isLocked(prop), ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						['GraphWD.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	g = GraphWD();
	 
	for prop = 1:1:GraphWD.getPropNumber()
		TAG = upper(GraphWD.getPropTag(prop));
		assert( ...
			~g.isLocked(prop), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			['GraphWD.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~g.isLocked(TAG), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			['GraphWD.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	g.lock()
	 
	for prop = 1:1:GraphWD.getPropNumber()
		switch GraphWD.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					g.isLocked(prop), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~g.isLocked(prop), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	g = GraphWD();
	 
	warning_backup = warning('off', 'BRAPH2:GraphWD');
	for prop = 1:1:GraphWD.getPropNumber()
		g.lock(prop)
		switch GraphWD.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					g.isLocked(prop), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~g.isLocked(prop), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	g = GraphWD();
	 
	for prop = 1:1:GraphWD.getPropNumber()
		TAG = upper(GraphWD.getPropTag(prop));
		assert( ...
			g.isChecked(prop), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			['GraphWD.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			g.isChecked(TAG), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			['GraphWD.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	g.unchecked()
	 
	for prop = 1:1:GraphWD.getPropNumber()
		assert( ...
			~g.isChecked(prop), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			['GraphWD.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	g.checked()
	 
	for prop = 1:1:GraphWD.getPropNumber()
		assert( ...
			g.isChecked(prop), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			['GraphWD.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic GraphWD
	g_0 = GraphWD( ...
		GraphWD.ELCLASS, GraphWD.getNoValue(), ...
		GraphWD.NAME, GraphWD.getNoValue(), ...
		GraphWD.DESCRIPTION, GraphWD.getNoValue(), ...
		GraphWD.TEMPLATE, GraphWD.getPropDefault(GraphWD.TEMPLATE), ...
		GraphWD.ID, GraphWD.getPropDefault(GraphWD.ID), ...
		GraphWD.LABEL, GraphWD.getPropDefault(GraphWD.LABEL), ...
		GraphWD.NOTES, GraphWD.getPropDefault(GraphWD.NOTES), ...
		GraphWD.TOSTRING, GraphWD.getNoValue(), ...
		GraphWD.GRAPH_TYPE, GraphWD.getNoValue(), ...
		GraphWD.CONNECTIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.DIRECTIONALITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.SELFCONNECTIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.NEGATIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.LAYERTICKS, GraphWD.getPropDefault(GraphWD.LAYERTICKS), ...
		GraphWD.ALAYERTICKS, GraphWD.getNoValue(), ...
		GraphWD.LAYERLABELS, GraphWD.getPropDefault(GraphWD.LAYERLABELS), ...
		GraphWD.ALAYERLABELS, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONTICKS, GraphWD.getPropDefault(GraphWD.PARTITIONTICKS), ...
		GraphWD.APARTITIONTICKS, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONLABELS, GraphWD.getPropDefault(GraphWD.PARTITIONLABELS), ...
		GraphWD.APARTITIONLABELS, GraphWD.getNoValue(), ...
		GraphWD.NODELABELS, GraphWD.getPropDefault(GraphWD.NODELABELS), ...
		GraphWD.ANODELABELS, GraphWD.getNoValue(), ...
		GraphWD.RANDOMIZE, GraphWD.getPropDefault(GraphWD.RANDOMIZE), ...
		GraphWD.RANDOM_SEED, GraphWD.getPropDefault(GraphWD.RANDOM_SEED), ...
		GraphWD.A, GraphWD.getNoValue(), ...
		GraphWD.A_CHECK, GraphWD.getNoValue(), ...
		GraphWD.NODENUMBER, GraphWD.getNoValue(), ...
		GraphWD.LAYERNUMBER, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONS, GraphWD.getNoValue(), ...
		GraphWD.M_DICT, GraphWD.getNoValue(), ...
		GraphWD.COMPATIBLE_MEASURES, GraphWD.getNoValue(), ...
		GraphWD.MEASURE, GraphWD.getNoValue(), ...
		GraphWD.PFGA, GraphWD.getPropDefault(GraphWD.PFGA), ...
		GraphWD.PFGH, GraphWD.getPropDefault(GraphWD.PFGH), ...
		GraphWD.B, GraphWD.getPropDefault(GraphWD.B), ...
		GraphWD.SEMIPOSITIVIZE_RULE, GraphWD.getPropDefault(GraphWD.SEMIPOSITIVIZE_RULE), ...
		GraphWD.STANDARDIZE_RULE, GraphWD.getPropDefault(GraphWD.STANDARDIZE_RULE), ...
		GraphWD.ATTEMPTSPEREDGE, GraphWD.getPropDefault(GraphWD.ATTEMPTSPEREDGE), ...
		GraphWD.NUMBEROFWEIGHTS, GraphWD.getPropDefault(GraphWD.NUMBEROFWEIGHTS), ...
		GraphWD.RANDOMIZATION, GraphWD.getNoValue() ...
		);
	 
	% GraphWD with 1st callbacks
	g_1 = GraphWD( ...
		GraphWD.ELCLASS, GraphWD.getNoValue(), ...
		GraphWD.NAME, GraphWD.getNoValue(), ...
		GraphWD.DESCRIPTION, GraphWD.getNoValue(), ...
		GraphWD.TEMPLATE, g_0.getCallback(4), ..., ...
		GraphWD.ID, g_0.getCallback(5), ..., ...
		GraphWD.LABEL, GraphWD.getPropDefault(GraphWD.LABEL), ...
		GraphWD.NOTES, GraphWD.getPropDefault(GraphWD.NOTES), ...
		GraphWD.TOSTRING, GraphWD.getNoValue(), ...
		GraphWD.GRAPH_TYPE, GraphWD.getNoValue(), ...
		GraphWD.CONNECTIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.DIRECTIONALITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.SELFCONNECTIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.NEGATIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.LAYERTICKS, GraphWD.getPropDefault(GraphWD.LAYERTICKS), ...
		GraphWD.ALAYERTICKS, GraphWD.getNoValue(), ...
		GraphWD.LAYERLABELS, GraphWD.getPropDefault(GraphWD.LAYERLABELS), ...
		GraphWD.ALAYERLABELS, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONTICKS, GraphWD.getPropDefault(GraphWD.PARTITIONTICKS), ...
		GraphWD.APARTITIONTICKS, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONLABELS, GraphWD.getPropDefault(GraphWD.PARTITIONLABELS), ...
		GraphWD.APARTITIONLABELS, GraphWD.getNoValue(), ...
		GraphWD.NODELABELS, GraphWD.getPropDefault(GraphWD.NODELABELS), ...
		GraphWD.ANODELABELS, GraphWD.getNoValue(), ...
		GraphWD.RANDOMIZE, g_0.getCallback(24), ..., ...
		GraphWD.RANDOM_SEED, g_0.getCallback(25), ..., ...
		GraphWD.A, GraphWD.getNoValue(), ...
		GraphWD.A_CHECK, GraphWD.getNoValue(), ...
		GraphWD.NODENUMBER, GraphWD.getNoValue(), ...
		GraphWD.LAYERNUMBER, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONS, GraphWD.getNoValue(), ...
		GraphWD.M_DICT, GraphWD.getNoValue(), ...
		GraphWD.COMPATIBLE_MEASURES, GraphWD.getNoValue(), ...
		GraphWD.MEASURE, GraphWD.getNoValue(), ...
		GraphWD.PFGA, g_0.getCallback(34), ..., ...
		GraphWD.PFGH, g_0.getCallback(35), ..., ...
		GraphWD.B, g_0.getCallback(36), ..., ...
		GraphWD.SEMIPOSITIVIZE_RULE, g_0.getCallback(37), ..., ...
		GraphWD.STANDARDIZE_RULE, g_0.getCallback(38), ..., ...
		GraphWD.ATTEMPTSPEREDGE, g_0.getCallback(39), ..., ...
		GraphWD.NUMBEROFWEIGHTS, g_0.getCallback(40), ..., ...
		GraphWD.RANDOMIZATION, GraphWD.getNoValue() ...
		);
	 
	prop_number = GraphWD.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(GraphWD.getPropTag(prop));
		switch GraphWD.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(g_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(g_1.get(prop), g_0.get(prop)) && ~isa(g_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(g_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% GraphWD with 2nd callbacks
	g_2 = GraphWD( ...
		GraphWD.ELCLASS, GraphWD.getNoValue(), ...
		GraphWD.NAME, GraphWD.getNoValue(), ...
		GraphWD.DESCRIPTION, GraphWD.getNoValue(), ...
		GraphWD.TEMPLATE, g_1.getCallback(4), ..., ...
		GraphWD.ID, g_1.getCallback(5), ..., ...
		GraphWD.LABEL, GraphWD.getPropDefault(GraphWD.LABEL), ...
		GraphWD.NOTES, GraphWD.getPropDefault(GraphWD.NOTES), ...
		GraphWD.TOSTRING, GraphWD.getNoValue(), ...
		GraphWD.GRAPH_TYPE, GraphWD.getNoValue(), ...
		GraphWD.CONNECTIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.DIRECTIONALITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.SELFCONNECTIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.NEGATIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.LAYERTICKS, GraphWD.getPropDefault(GraphWD.LAYERTICKS), ...
		GraphWD.ALAYERTICKS, GraphWD.getNoValue(), ...
		GraphWD.LAYERLABELS, GraphWD.getPropDefault(GraphWD.LAYERLABELS), ...
		GraphWD.ALAYERLABELS, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONTICKS, GraphWD.getPropDefault(GraphWD.PARTITIONTICKS), ...
		GraphWD.APARTITIONTICKS, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONLABELS, GraphWD.getPropDefault(GraphWD.PARTITIONLABELS), ...
		GraphWD.APARTITIONLABELS, GraphWD.getNoValue(), ...
		GraphWD.NODELABELS, GraphWD.getPropDefault(GraphWD.NODELABELS), ...
		GraphWD.ANODELABELS, GraphWD.getNoValue(), ...
		GraphWD.RANDOMIZE, g_1.getCallback(24), ..., ...
		GraphWD.RANDOM_SEED, g_1.getCallback(25), ..., ...
		GraphWD.A, GraphWD.getNoValue(), ...
		GraphWD.A_CHECK, GraphWD.getNoValue(), ...
		GraphWD.NODENUMBER, GraphWD.getNoValue(), ...
		GraphWD.LAYERNUMBER, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONS, GraphWD.getNoValue(), ...
		GraphWD.M_DICT, GraphWD.getNoValue(), ...
		GraphWD.COMPATIBLE_MEASURES, GraphWD.getNoValue(), ...
		GraphWD.MEASURE, GraphWD.getNoValue(), ...
		GraphWD.PFGA, g_1.getCallback(34), ..., ...
		GraphWD.PFGH, g_1.getCallback(35), ..., ...
		GraphWD.B, g_1.getCallback(36), ..., ...
		GraphWD.SEMIPOSITIVIZE_RULE, g_1.getCallback(37), ..., ...
		GraphWD.STANDARDIZE_RULE, g_1.getCallback(38), ..., ...
		GraphWD.ATTEMPTSPEREDGE, g_1.getCallback(39), ..., ...
		GraphWD.NUMBEROFWEIGHTS, g_1.getCallback(40), ..., ...
		GraphWD.RANDOMIZATION, GraphWD.getNoValue() ...
		);
	 
	prop_number = GraphWD.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(GraphWD.getPropTag(prop));
		switch GraphWD.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(g_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(g_2.get(prop), g_0.get(prop)) && ~isa(g_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(g_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% GraphWD with 3rd callbacks
	g_3 = GraphWD( ...
		GraphWD.ELCLASS, GraphWD.getNoValue(), ...
		GraphWD.NAME, GraphWD.getNoValue(), ...
		GraphWD.DESCRIPTION, GraphWD.getNoValue(), ...
		GraphWD.TEMPLATE, g_2.getCallback(4), ..., ...
		GraphWD.ID, g_2.getCallback(5), ..., ...
		GraphWD.LABEL, GraphWD.getPropDefault(GraphWD.LABEL), ...
		GraphWD.NOTES, GraphWD.getPropDefault(GraphWD.NOTES), ...
		GraphWD.TOSTRING, GraphWD.getNoValue(), ...
		GraphWD.GRAPH_TYPE, GraphWD.getNoValue(), ...
		GraphWD.CONNECTIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.DIRECTIONALITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.SELFCONNECTIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.NEGATIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.LAYERTICKS, GraphWD.getPropDefault(GraphWD.LAYERTICKS), ...
		GraphWD.ALAYERTICKS, GraphWD.getNoValue(), ...
		GraphWD.LAYERLABELS, GraphWD.getPropDefault(GraphWD.LAYERLABELS), ...
		GraphWD.ALAYERLABELS, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONTICKS, GraphWD.getPropDefault(GraphWD.PARTITIONTICKS), ...
		GraphWD.APARTITIONTICKS, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONLABELS, GraphWD.getPropDefault(GraphWD.PARTITIONLABELS), ...
		GraphWD.APARTITIONLABELS, GraphWD.getNoValue(), ...
		GraphWD.NODELABELS, GraphWD.getPropDefault(GraphWD.NODELABELS), ...
		GraphWD.ANODELABELS, GraphWD.getNoValue(), ...
		GraphWD.RANDOMIZE, g_2.getCallback(24), ..., ...
		GraphWD.RANDOM_SEED, g_2.getCallback(25), ..., ...
		GraphWD.A, GraphWD.getNoValue(), ...
		GraphWD.A_CHECK, GraphWD.getNoValue(), ...
		GraphWD.NODENUMBER, GraphWD.getNoValue(), ...
		GraphWD.LAYERNUMBER, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONS, GraphWD.getNoValue(), ...
		GraphWD.M_DICT, GraphWD.getNoValue(), ...
		GraphWD.COMPATIBLE_MEASURES, GraphWD.getNoValue(), ...
		GraphWD.MEASURE, GraphWD.getNoValue(), ...
		GraphWD.PFGA, g_2.getCallback(34), ..., ...
		GraphWD.PFGH, g_2.getCallback(35), ..., ...
		GraphWD.B, g_2.getCallback(36), ..., ...
		GraphWD.SEMIPOSITIVIZE_RULE, g_2.getCallback(37), ..., ...
		GraphWD.STANDARDIZE_RULE, g_2.getCallback(38), ..., ...
		GraphWD.ATTEMPTSPEREDGE, g_2.getCallback(39), ..., ...
		GraphWD.NUMBEROFWEIGHTS, g_2.getCallback(40), ..., ...
		GraphWD.RANDOMIZATION, GraphWD.getNoValue() ...
		);
	 
	prop_number = GraphWD.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(GraphWD.getPropTag(prop));
		switch GraphWD.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(g_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(g_3.get(prop), g_0.get(prop)) && ~isa(g_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(g_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	g = GraphWD();
	 
	g_copy = g.copy();
	 
	assert(g_copy ~= g, ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'GraphWD.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(g_copy, g), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'GraphWD.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:GraphWD.getPropNumber()
		value = g.getr(prop);
		value_copy = g_copy.getr(prop);
		switch GraphWD.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					'GraphWD.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						'GraphWD.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						'GraphWD.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						'GraphWD.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
							'GraphWD.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
							'GraphWD.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						'GraphWD.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					g_copy.isLocked(prop) == g.isLocked(prop), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					'GraphWD.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					g_copy.isChecked(prop) == g.isChecked(prop), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					'GraphWD.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					g_copy.getPropSeed(prop) == g.getPropSeed(prop), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					'GraphWD.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	g = GraphWD( ...
		GraphWD.ELCLASS, GraphWD.getNoValue(), ...
		GraphWD.NAME, GraphWD.getNoValue(), ...
		GraphWD.DESCRIPTION, GraphWD.getNoValue(), ...
		GraphWD.TEMPLATE, GraphWD.getPropDefault(GraphWD.TEMPLATE), ...
		GraphWD.ID, GraphWD.getPropDefault(GraphWD.ID), ...
		GraphWD.LABEL, GraphWD.getPropDefault(GraphWD.LABEL), ...
		GraphWD.NOTES, GraphWD.getPropDefault(GraphWD.NOTES), ...
		GraphWD.TOSTRING, GraphWD.getNoValue(), ...
		GraphWD.GRAPH_TYPE, GraphWD.getNoValue(), ...
		GraphWD.CONNECTIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.DIRECTIONALITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.SELFCONNECTIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.NEGATIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.LAYERTICKS, GraphWD.getPropDefault(GraphWD.LAYERTICKS), ...
		GraphWD.ALAYERTICKS, GraphWD.getNoValue(), ...
		GraphWD.LAYERLABELS, GraphWD.getPropDefault(GraphWD.LAYERLABELS), ...
		GraphWD.ALAYERLABELS, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONTICKS, GraphWD.getPropDefault(GraphWD.PARTITIONTICKS), ...
		GraphWD.APARTITIONTICKS, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONLABELS, GraphWD.getPropDefault(GraphWD.PARTITIONLABELS), ...
		GraphWD.APARTITIONLABELS, GraphWD.getNoValue(), ...
		GraphWD.NODELABELS, GraphWD.getPropDefault(GraphWD.NODELABELS), ...
		GraphWD.ANODELABELS, GraphWD.getNoValue(), ...
		GraphWD.RANDOMIZE, GraphWD.getPropDefault(GraphWD.RANDOMIZE), ...
		GraphWD.RANDOM_SEED, GraphWD.getPropDefault(GraphWD.RANDOM_SEED), ...
		GraphWD.A, GraphWD.getNoValue(), ...
		GraphWD.A_CHECK, GraphWD.getNoValue(), ...
		GraphWD.NODENUMBER, GraphWD.getNoValue(), ...
		GraphWD.LAYERNUMBER, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONS, GraphWD.getNoValue(), ...
		GraphWD.M_DICT, GraphWD.getNoValue(), ...
		GraphWD.COMPATIBLE_MEASURES, GraphWD.getNoValue(), ...
		GraphWD.MEASURE, GraphWD.getNoValue(), ...
		GraphWD.PFGA, GraphWD.getPropDefault(GraphWD.PFGA), ...
		GraphWD.PFGH, GraphWD.getPropDefault(GraphWD.PFGH), ...
		GraphWD.B, GraphWD.getPropDefault(GraphWD.B), ...
		GraphWD.SEMIPOSITIVIZE_RULE, GraphWD.getPropDefault(GraphWD.SEMIPOSITIVIZE_RULE), ...
		GraphWD.STANDARDIZE_RULE, GraphWD.getPropDefault(GraphWD.STANDARDIZE_RULE), ...
		GraphWD.ATTEMPTSPEREDGE, GraphWD.getPropDefault(GraphWD.ATTEMPTSPEREDGE), ...
		GraphWD.NUMBEROFWEIGHTS, GraphWD.getPropDefault(GraphWD.NUMBEROFWEIGHTS), ...
		GraphWD.RANDOMIZATION, GraphWD.getNoValue() ...
		);
	 
	for prop = 1:1:GraphWD.getPropNumber()
		if GraphWD.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':GraphWD']);
			% g.memorize(prop);
			% warning(warning_backup)
		elseif GraphWD.getPropCategory(prop) == Category.EVANESCENT && g.getPropFormat(prop) == Format.HANDLE
			g.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:GraphWD');
			delete(ancestor(g.get(prop), 'figure'))
			warning(warning_backup)
		else
			g.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	g_copy = g.copy();
	 
	for prop = 1:1:GraphWD.getPropNumber()
		value = g.getr(prop);
		value_copy = g_copy.getr(prop);
		switch GraphWD.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					'GraphWD.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						'GraphWD.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						'GraphWD.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						'GraphWD.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
							'GraphWD.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
							'GraphWD.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						'GraphWD.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						g_copy.isLocked(prop) == g.isLocked(prop), ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						'GraphWD.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						g_copy.isChecked(prop) == g.isChecked(prop), ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						'GraphWD.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						g_copy.getPropSeed(prop) == g.getPropSeed(prop), ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						'GraphWD.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	g_0 = GraphWD( ...
		GraphWD.ELCLASS, GraphWD.getNoValue(), ...
		GraphWD.NAME, GraphWD.getNoValue(), ...
		GraphWD.DESCRIPTION, GraphWD.getNoValue(), ...
		GraphWD.TEMPLATE, GraphWD.getPropDefault(GraphWD.TEMPLATE), ...
		GraphWD.ID, GraphWD.getPropDefault(GraphWD.ID), ...
		GraphWD.LABEL, GraphWD.getPropDefault(GraphWD.LABEL), ...
		GraphWD.NOTES, GraphWD.getPropDefault(GraphWD.NOTES), ...
		GraphWD.TOSTRING, GraphWD.getNoValue(), ...
		GraphWD.GRAPH_TYPE, GraphWD.getNoValue(), ...
		GraphWD.CONNECTIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.DIRECTIONALITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.SELFCONNECTIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.NEGATIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.LAYERTICKS, GraphWD.getPropDefault(GraphWD.LAYERTICKS), ...
		GraphWD.ALAYERTICKS, GraphWD.getNoValue(), ...
		GraphWD.LAYERLABELS, GraphWD.getPropDefault(GraphWD.LAYERLABELS), ...
		GraphWD.ALAYERLABELS, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONTICKS, GraphWD.getPropDefault(GraphWD.PARTITIONTICKS), ...
		GraphWD.APARTITIONTICKS, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONLABELS, GraphWD.getPropDefault(GraphWD.PARTITIONLABELS), ...
		GraphWD.APARTITIONLABELS, GraphWD.getNoValue(), ...
		GraphWD.NODELABELS, GraphWD.getPropDefault(GraphWD.NODELABELS), ...
		GraphWD.ANODELABELS, GraphWD.getNoValue(), ...
		GraphWD.RANDOMIZE, GraphWD.getPropDefault(GraphWD.RANDOMIZE), ...
		GraphWD.RANDOM_SEED, GraphWD.getPropDefault(GraphWD.RANDOM_SEED), ...
		GraphWD.A, GraphWD.getNoValue(), ...
		GraphWD.A_CHECK, GraphWD.getNoValue(), ...
		GraphWD.NODENUMBER, GraphWD.getNoValue(), ...
		GraphWD.LAYERNUMBER, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONS, GraphWD.getNoValue(), ...
		GraphWD.M_DICT, GraphWD.getNoValue(), ...
		GraphWD.COMPATIBLE_MEASURES, GraphWD.getNoValue(), ...
		GraphWD.MEASURE, GraphWD.getNoValue(), ...
		GraphWD.PFGA, GraphWD.getPropDefault(GraphWD.PFGA), ...
		GraphWD.PFGH, GraphWD.getPropDefault(GraphWD.PFGH), ...
		GraphWD.B, GraphWD.getPropDefault(GraphWD.B), ...
		GraphWD.SEMIPOSITIVIZE_RULE, GraphWD.getPropDefault(GraphWD.SEMIPOSITIVIZE_RULE), ...
		GraphWD.STANDARDIZE_RULE, GraphWD.getPropDefault(GraphWD.STANDARDIZE_RULE), ...
		GraphWD.ATTEMPTSPEREDGE, GraphWD.getPropDefault(GraphWD.ATTEMPTSPEREDGE), ...
		GraphWD.NUMBEROFWEIGHTS, GraphWD.getPropDefault(GraphWD.NUMBEROFWEIGHTS), ...
		GraphWD.RANDOMIZATION, GraphWD.getNoValue() ...
		);
	 
	g = GraphWD( ...
		GraphWD.ELCLASS, GraphWD.getNoValue(), ...
		GraphWD.NAME, GraphWD.getNoValue(), ...
		GraphWD.DESCRIPTION, GraphWD.getNoValue(), ...
		GraphWD.TEMPLATE, g_0.getCallback(4), ..., ...
		GraphWD.ID, g_0.getCallback(5), ..., ...
		GraphWD.LABEL, GraphWD.getPropDefault(GraphWD.LABEL), ...
		GraphWD.NOTES, GraphWD.getPropDefault(GraphWD.NOTES), ...
		GraphWD.TOSTRING, GraphWD.getNoValue(), ...
		GraphWD.GRAPH_TYPE, GraphWD.getNoValue(), ...
		GraphWD.CONNECTIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.DIRECTIONALITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.SELFCONNECTIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.NEGATIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.LAYERTICKS, GraphWD.getPropDefault(GraphWD.LAYERTICKS), ...
		GraphWD.ALAYERTICKS, GraphWD.getNoValue(), ...
		GraphWD.LAYERLABELS, GraphWD.getPropDefault(GraphWD.LAYERLABELS), ...
		GraphWD.ALAYERLABELS, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONTICKS, GraphWD.getPropDefault(GraphWD.PARTITIONTICKS), ...
		GraphWD.APARTITIONTICKS, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONLABELS, GraphWD.getPropDefault(GraphWD.PARTITIONLABELS), ...
		GraphWD.APARTITIONLABELS, GraphWD.getNoValue(), ...
		GraphWD.NODELABELS, GraphWD.getPropDefault(GraphWD.NODELABELS), ...
		GraphWD.ANODELABELS, GraphWD.getNoValue(), ...
		GraphWD.RANDOMIZE, g_0.getCallback(24), ..., ...
		GraphWD.RANDOM_SEED, g_0.getCallback(25), ..., ...
		GraphWD.A, GraphWD.getNoValue(), ...
		GraphWD.A_CHECK, GraphWD.getNoValue(), ...
		GraphWD.NODENUMBER, GraphWD.getNoValue(), ...
		GraphWD.LAYERNUMBER, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONS, GraphWD.getNoValue(), ...
		GraphWD.M_DICT, GraphWD.getNoValue(), ...
		GraphWD.COMPATIBLE_MEASURES, GraphWD.getNoValue(), ...
		GraphWD.MEASURE, GraphWD.getNoValue(), ...
		GraphWD.PFGA, g_0.getCallback(34), ..., ...
		GraphWD.PFGH, g_0.getCallback(35), ..., ...
		GraphWD.B, g_0.getCallback(36), ..., ...
		GraphWD.SEMIPOSITIVIZE_RULE, g_0.getCallback(37), ..., ...
		GraphWD.STANDARDIZE_RULE, g_0.getCallback(38), ..., ...
		GraphWD.ATTEMPTSPEREDGE, g_0.getCallback(39), ..., ...
		GraphWD.NUMBEROFWEIGHTS, g_0.getCallback(40), ..., ...
		GraphWD.RANDOMIZATION, GraphWD.getNoValue() ...
		);
	 
	g_copy = g.copy();
	g_0_copy = g_copy.getr('ID').get('EL');
	 
	for prop = 1:1:GraphWD.getPropNumber()
		value = g.getr(prop);
		value_copy = g_copy.getr(prop);
		switch GraphWD.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					'GraphWD.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						'GraphWD.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						'GraphWD.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						'GraphWD.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
							'GraphWD.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
							'GraphWD.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						'GraphWD.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == g_0.getCallback(prop), ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						'GraphWD.copy() does not work. The callback should be obtained from GraphWD.getCallback().' ...
						)
					assert( ...
						value_copy == g_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						'GraphWD.copy() does not work. The callback should be obtained from GraphWD.getCallback().' ...
						)
				end
	 
					assert( ...
						g_copy.isLocked(prop) == g.isLocked(prop), ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						'GraphWD.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						g_copy.isChecked(prop) == g.isChecked(prop), ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						'GraphWD.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						g_copy.getPropSeed(prop) == g.getPropSeed(prop), ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						'GraphWD.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	g_template = GraphWD();
	g = GraphWD('TEMPLATE', g_template);
	 
	for prop = 1:1:GraphWD.getPropNumber()
	 
		% excluded props
		if any(prop == [GraphWD.PFGA GraphWD.PFGH])
			continue
		end
	 
		TAG = upper(GraphWD.getPropTag(prop));
		switch GraphWD.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == GraphWD.TEMPLATE
					assert( ...
						isa(g.getr(prop), 'GraphWD'), ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						'GraphWD TEMPLATE does not work. GraphWD.getr(''TEMPLATE'') should be a GraphWD element.' ...
						)
					assert( ...
						isa(g_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						'GraphWD TEMPLATE does not work. GraphWD_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(g.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						['GraphWD TEMPLATE does not work. GraphWD.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						g.getr(prop).get('EL') == g_template && g.getr(prop).get('PROP') == prop && strcmp(g.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						['GraphWD TEMPLATE does not work. GraphWD.getr(' TAG ') should be a Callback to g_template.' TAG '.'] ...
						)
					assert( ...
						isa(g_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
						['GraphWD TEMPLATE does not work. GraphWD_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(g.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD TEMPLATE does not work. GraphWD.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(g_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
					['GraphWD TEMPLATE does not work. GraphWD_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	g = GraphWD( ...
		GraphWD.ELCLASS, GraphWD.getNoValue(), ...
		GraphWD.NAME, GraphWD.getNoValue(), ...
		GraphWD.DESCRIPTION, GraphWD.getNoValue(), ...
		GraphWD.TEMPLATE, GraphWD.getPropDefault(GraphWD.TEMPLATE), ...
		GraphWD.ID, GraphWD.getPropDefault(GraphWD.ID), ...
		GraphWD.LABEL, GraphWD.getPropDefault(GraphWD.LABEL), ...
		GraphWD.NOTES, GraphWD.getPropDefault(GraphWD.NOTES), ...
		GraphWD.TOSTRING, GraphWD.getNoValue(), ...
		GraphWD.GRAPH_TYPE, GraphWD.getNoValue(), ...
		GraphWD.CONNECTIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.DIRECTIONALITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.SELFCONNECTIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.NEGATIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.LAYERTICKS, GraphWD.getPropDefault(GraphWD.LAYERTICKS), ...
		GraphWD.ALAYERTICKS, GraphWD.getNoValue(), ...
		GraphWD.LAYERLABELS, GraphWD.getPropDefault(GraphWD.LAYERLABELS), ...
		GraphWD.ALAYERLABELS, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONTICKS, GraphWD.getPropDefault(GraphWD.PARTITIONTICKS), ...
		GraphWD.APARTITIONTICKS, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONLABELS, GraphWD.getPropDefault(GraphWD.PARTITIONLABELS), ...
		GraphWD.APARTITIONLABELS, GraphWD.getNoValue(), ...
		GraphWD.NODELABELS, GraphWD.getPropDefault(GraphWD.NODELABELS), ...
		GraphWD.ANODELABELS, GraphWD.getNoValue(), ...
		GraphWD.RANDOMIZE, GraphWD.getPropDefault(GraphWD.RANDOMIZE), ...
		GraphWD.RANDOM_SEED, GraphWD.getPropDefault(GraphWD.RANDOM_SEED), ...
		GraphWD.A, GraphWD.getNoValue(), ...
		GraphWD.A_CHECK, GraphWD.getNoValue(), ...
		GraphWD.NODENUMBER, GraphWD.getNoValue(), ...
		GraphWD.LAYERNUMBER, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONS, GraphWD.getNoValue(), ...
		GraphWD.M_DICT, GraphWD.getNoValue(), ...
		GraphWD.COMPATIBLE_MEASURES, GraphWD.getNoValue(), ...
		GraphWD.MEASURE, GraphWD.getNoValue(), ...
		GraphWD.PFGA, GraphWD.getPropDefault(GraphWD.PFGA), ...
		GraphWD.PFGH, GraphWD.getPropDefault(GraphWD.PFGH), ...
		GraphWD.B, GraphWD.getPropDefault(GraphWD.B), ...
		GraphWD.SEMIPOSITIVIZE_RULE, GraphWD.getPropDefault(GraphWD.SEMIPOSITIVIZE_RULE), ...
		GraphWD.STANDARDIZE_RULE, GraphWD.getPropDefault(GraphWD.STANDARDIZE_RULE), ...
		GraphWD.ATTEMPTSPEREDGE, GraphWD.getPropDefault(GraphWD.ATTEMPTSPEREDGE), ...
		GraphWD.NUMBEROFWEIGHTS, GraphWD.getPropDefault(GraphWD.NUMBEROFWEIGHTS), ...
		GraphWD.RANDOMIZATION, GraphWD.getNoValue() ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'graphwd_to_be_erased.b2'];
	 
	Element.save(g, filename)
	 
	g_loaded = Element.load(filename);
	 
	assert( ...
		isequal(g.copy(), g_loaded), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'GraphWD.save(g) and/or GraphWD.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	g = GraphWD( ...
		GraphWD.ELCLASS, GraphWD.getNoValue(), ...
		GraphWD.NAME, GraphWD.getNoValue(), ...
		GraphWD.DESCRIPTION, GraphWD.getNoValue(), ...
		GraphWD.TEMPLATE, GraphWD.getPropDefault(GraphWD.TEMPLATE), ...
		GraphWD.ID, GraphWD.getPropDefault(GraphWD.ID), ...
		GraphWD.LABEL, GraphWD.getPropDefault(GraphWD.LABEL), ...
		GraphWD.NOTES, GraphWD.getPropDefault(GraphWD.NOTES), ...
		GraphWD.TOSTRING, GraphWD.getNoValue(), ...
		GraphWD.GRAPH_TYPE, GraphWD.getNoValue(), ...
		GraphWD.CONNECTIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.DIRECTIONALITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.SELFCONNECTIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.NEGATIVITY_TYPE, GraphWD.getNoValue(), ...
		GraphWD.LAYERTICKS, GraphWD.getPropDefault(GraphWD.LAYERTICKS), ...
		GraphWD.ALAYERTICKS, GraphWD.getNoValue(), ...
		GraphWD.LAYERLABELS, GraphWD.getPropDefault(GraphWD.LAYERLABELS), ...
		GraphWD.ALAYERLABELS, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONTICKS, GraphWD.getPropDefault(GraphWD.PARTITIONTICKS), ...
		GraphWD.APARTITIONTICKS, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONLABELS, GraphWD.getPropDefault(GraphWD.PARTITIONLABELS), ...
		GraphWD.APARTITIONLABELS, GraphWD.getNoValue(), ...
		GraphWD.NODELABELS, GraphWD.getPropDefault(GraphWD.NODELABELS), ...
		GraphWD.ANODELABELS, GraphWD.getNoValue(), ...
		GraphWD.RANDOMIZE, GraphWD.getPropDefault(GraphWD.RANDOMIZE), ...
		GraphWD.RANDOM_SEED, GraphWD.getPropDefault(GraphWD.RANDOM_SEED), ...
		GraphWD.A, GraphWD.getNoValue(), ...
		GraphWD.A_CHECK, GraphWD.getNoValue(), ...
		GraphWD.NODENUMBER, GraphWD.getNoValue(), ...
		GraphWD.LAYERNUMBER, GraphWD.getNoValue(), ...
		GraphWD.PARTITIONS, GraphWD.getNoValue(), ...
		GraphWD.M_DICT, GraphWD.getNoValue(), ...
		GraphWD.COMPATIBLE_MEASURES, GraphWD.getNoValue(), ...
		GraphWD.MEASURE, GraphWD.getNoValue(), ...
		GraphWD.PFGA, GraphWD.getPropDefault(GraphWD.PFGA), ...
		GraphWD.PFGH, GraphWD.getPropDefault(GraphWD.PFGH), ...
		GraphWD.B, GraphWD.getPropDefault(GraphWD.B), ...
		GraphWD.SEMIPOSITIVIZE_RULE, GraphWD.getPropDefault(GraphWD.SEMIPOSITIVIZE_RULE), ...
		GraphWD.STANDARDIZE_RULE, GraphWD.getPropDefault(GraphWD.STANDARDIZE_RULE), ...
		GraphWD.ATTEMPTSPEREDGE, GraphWD.getPropDefault(GraphWD.ATTEMPTSPEREDGE), ...
		GraphWD.NUMBEROFWEIGHTS, GraphWD.getPropDefault(GraphWD.NUMBEROFWEIGHTS), ...
		GraphWD.RANDOMIZATION, GraphWD.getNoValue() ...
		);
	 
	[json, struct, el_list] = encodeJSON(g);
	[g_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(g_dec ~= g, ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		'GraphWD.encodeJSON() or GraphWD.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) GraphWD.getPropFormat(prop), num2cell(GraphWD.getProps())) == Format.HANDLE) && all(cellfun(@(prop) GraphWD.getPropFormat(prop), num2cell(GraphWD.getProps())) == Format.NET)
		assert(isequal(g_dec, g), ...
			[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
			'GraphWD.encodeJSON() or GraphWD.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: Constructor - Empty
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	B = [];
	g = GraphWD('B', B);
	
	g.get('A_CHECK')
	
	A = {standardize(semipositivize(dediagonalize(B)))};
	assert(isequal(g.get('A'), A), ...
	    [BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
	    'GraphWD is not constructing well.')
end

%% Test 13: Constructor - Full
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	B = rand(randi(10));
	g = GraphWD('B', B);
	
	g.get('A_CHECK')
	
	A = {standardize(semipositivize(dediagonalize(B)))};
	assert(isequal(g.get('A'), A), ...
	    [BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
	    'GraphWD is not constructing well.')
end

%% Test 14: Semipositivize and Standardize Rules
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	B = 10 * rand(randi(10) + 5) - 5; % random number in U(-5, 5)
	
	g0 = GraphWD('B', B); % 'SEMIPOSITIVIZE_RULE', 'zero', 'STANDARDIZE_RULE', 'threshold'
	A0 = B;
	A0(A0 < 0) = 0;
	A0(A0 > 1) = 1;
	A0 = {dediagonalize(A0)};
	assert(isequal(g0.get('A'), A0), ...
	    [BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
	    'GraphWD is not constructing well.')
	
	g_zero = GraphWD('B', B, 'SEMIPOSITIVIZE_RULE', 'zero'); % 'STANDARDIZE_RULE', 'threshold'
	A_zero = B;
	A_zero(A_zero < 0) = 0;
	A_zero(A_zero > 1) = 1;
	A_zero = {dediagonalize(A_zero)};
	assert(isequal(g_zero.get('A'), A_zero), ...
	    [BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
	    'GraphWD is not constructing well.')
	
	g_absolute = GraphWD('B', B, 'SEMIPOSITIVIZE_RULE', 'absolute'); % 'STANDARDIZE_RULE', 'threshold'
	A_absolute = abs(B);
	A_absolute(A_absolute < 0) = 0;
	A_absolute(A_absolute > 1) = 1;
	A_absolute = {dediagonalize(A_absolute)};
	assert(isequal(g_absolute.get('A'), A_absolute), ...
	    [BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
	    'GraphWD is not constructing well.')
	
	g_theresold = GraphWD('B', B, 'STANDARDIZE_RULE', 'threshold'); % 'SEMIPOSITIVIZE_RULE', 'zero'
	A_theresold = B;
	A_theresold(A_theresold < 0) = 0;
	A_theresold(A_theresold > 1) = 1;
	A_theresold = {dediagonalize(A_theresold)};
	assert(isequal(g_theresold.get('A'), A_theresold), ...
	    [BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
	    'GraphWD is not constructing well.')
	
	g_zero_theresold = GraphWD('B', B, 'SEMIPOSITIVIZE_RULE', 'zero', 'STANDARDIZE_RULE', 'threshold');
	A_zero_theresold = B;
	A_zero_theresold(A_zero_theresold < 0) = 0;
	A_zero_theresold(A_zero_theresold > 1) = 1;
	A_zero_theresold = {dediagonalize(A_zero_theresold)};
	assert(isequal(g_zero_theresold.get('A'), A_zero_theresold), ...
	    [BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
	    'GraphWD is not constructing well.')
	
	g_absolute_theresold = GraphWD('B', B, 'SEMIPOSITIVIZE_RULE', 'absolute', 'STANDARDIZE_RULE', 'threshold');
	A_absolute_theresold = abs(B);
	A_absolute_theresold(A_absolute_theresold < 0) = 0;
	A_absolute_theresold(A_absolute_theresold > 1) = 1;
	A_absolute_theresold = {dediagonalize(A_absolute_theresold)};
	assert(isequal(g_absolute_theresold.get('A'), A_absolute_theresold), ...
	    [BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
	    'GraphWD is not constructing well.')
	
	g_range = GraphWD('B', B, 'STANDARDIZE_RULE', 'range'); % 'SEMIPOSITIVIZE_RULE', 'zero'
	A_range = dediagonalize(B);
	A_range(A_range < 0) = 0;
	A_range = A_range / max(max(A_range));
	A_range = {A_range};
	assert(isequal(g_range.get('A'), A_range), ...
	    [BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
	    'GraphWD is not constructing well.')
	
	g_zero_range = GraphWD('B', B, 'SEMIPOSITIVIZE_RULE', 'zero', 'STANDARDIZE_RULE', 'range');
	A_zero_range = dediagonalize(B);
	A_zero_range(A_zero_range < 0) = 0;
	A_zero_range = A_zero_range / max(max(A_zero_range));
	A_zero_range = {A_zero_range};
	assert(isequal(g_zero_range.get('A'), A_zero_range), ...
	    [BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
	    'GraphWD is not constructing well.')
	
	g_absolute_range = GraphWD('B', B, 'SEMIPOSITIVIZE_RULE', 'absolute', 'STANDARDIZE_RULE', 'range');
	A_absolute_range = abs(B);
	A_absolute_range = standardize(dediagonalize(A_absolute_range), 'StandardizeRule', 'range');
	A_absolute_range = {A_absolute_range};
	assert(isequal(g_absolute_range.get('A'), A_absolute_range), ...
	    [BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
	    'GraphWD is not constructing well.')
end

%% Test 15: Randomize Rules
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	B = randn(10);
	
	g = GraphWD('B', B);
	g.set('RANDOMIZE', true);
	g.set('ATTEMPTSPEREDGE', 4);
	
	A = g.get('A');
	
	assert(isequal(size(A{1}), size(B)), ...
	    [BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
	    'GraphWD Randomize is not functioning well.')
	
	g2 = GraphWD('B', B);
	g2.set('RANDOMIZE', false);
	g2.set('ATTEMPTSPEREDGE', 4);
	A2 = g2.get('A');
	random_A = g2.get('RANDOMIZATION', A2);
	
	if all(A2{1}==0, "all") %if all nodes are zero, the random matrix is also all zeros
	    assert(isequal(A2{1}, random_A), ...
	        [BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
	        'GraphWD Randomize is not functioning well.')
	elseif isequal((length(A2{1}).^2)- length(A2{1}), sum(A2{1}==1, "all")) %if all nodes (except diagonal) are one, the random matrix is the same as original
	    assert(isequal(A2{1}, random_A), ...
	        [BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
	        'GraphWD Randomize is not functioning well.')
	else
	%     assert(~isequal(A2{1}, random_A), ...
	%         [BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
	%         'GraphWD Randomize is not functioning well.')
	end
	
	assert(isequal(numel(find(A2{1})), numel(find(random_A))), ... % check same number of nodes
	    [BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
	    'GraphWD Randomize is not functioning well.')
end

%% Test 16: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':GraphWD:' BRAPH2.FAIL_TEST], ...
		[' When testing GraphWD no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 17: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

