%TEST_MULTILAYERWD

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	g = MultilayerWD();
	 
	% get('ELCLASS')
	if isa(MultilayerWD, 'ConcreteElement')
		assert(strcmp(MultilayerWD().get('ELCLASS'), 'MultilayerWD'), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'MultilayerWD().get(''ELCLASS'') should return ''MultilayerWD''.')
	end
	 
	% getBuild()
	assert(MultilayerWD.getBuild() == 1 && MultilayerWD.getBuild() > 0, ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'MultilayerWD.getBuild() should return the MultilayerWD build number.')
	assert(g.getBuild() == 1 && g.getBuild() > 0 , ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'g.getBuild() should return the MultilayerWD build number.')
	assert(Element.getBuild(g) == 1 && Element.getBuild(g) > 0, ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(g) should return the MultilayerWD build number.')
	assert(Element.getBuild('MultilayerWD') == 1 && Element.getBuild('MultilayerWD') > 0, ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''MultilayerWD'') should return the MultilayerWD build number.')
	 
	% getClass()
	assert(strcmp(MultilayerWD.getClass(), 'MultilayerWD'), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'MultilayerWD.getClass() should return ''MultilayerWD''.')
	assert(strcmp(g.getClass(), 'MultilayerWD'), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'g.getClass() should return ''MultilayerWD''.')
	assert(strcmp(Element.getClass(g), 'MultilayerWD'), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(g) should return ''MultilayerWD''.')
	assert(strcmp(Element.getClass('MultilayerWD'), 'MultilayerWD'), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''MultilayerWD'') should return ''MultilayerWD''.')
	 
	% getSubclasses()
	assert(isequal(MultilayerWD.getSubclasses(), subclasses('MultilayerWD', [], [], true)), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'MultilayerWD.getSubclasses() should return the same result as subclasses(''MultilayerWD'', [], [], true).')
	assert(isequal(g.getSubclasses(), subclasses('MultilayerWD', [], [], true)), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''MultilayerWD'', [], [], true).')
	assert(isequal(Element.getSubclasses(g), subclasses('MultilayerWD', [], [], true)), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(g) should return the same result as subclasses(''MultilayerWD'', [], [], true).')
	assert(isequal(Element.getSubclasses('MultilayerWD'), subclasses('MultilayerWD', [], [], true)), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''MultilayerWD'') should return the same result as subclasses(''MultilayerWD'', [], [], true).')
	 
	% getProps()
	assert(isempty(MultilayerWD.getProps()) || isequal(MultilayerWD.getProps(), 1:1:length(MultilayerWD.getProps())), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'MultilayerWD.getProps() should return a row vector [1:1:N].')
	assert(isempty(MultilayerWD.getProps()) || isequal(g.getProps(), 1:1:length(MultilayerWD.getProps())), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'g.getProps() should return a row vector [1:1:N].')
	assert(isempty(MultilayerWD.getProps()) || isequal(Element.getProps(g), 1:1:length(MultilayerWD.getProps())), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(g) should return a row vector [1:1:N].')
	assert(isempty(MultilayerWD.getProps()) || isequal(Element.getProps('MultilayerWD'), 1:1:length(MultilayerWD.getProps())), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''MultilayerWD'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) MultilayerWD.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(MultilayerWD.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(MultilayerWD.getProps())), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'MultilayerWD.getProps(category) does not work.')
	tmp = cellfun(@(category) g.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(MultilayerWD.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(MultilayerWD.getProps())), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'g.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(g, category), categories, 'UniformOutput', false);
	assert(isempty(MultilayerWD.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(MultilayerWD.getProps())), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(g, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('MultilayerWD', category), categories, 'UniformOutput', false);
	assert(isempty(MultilayerWD.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(MultilayerWD.getProps())), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''MultilayerWD'', category) does not work.')
	 
	% getPropNumber()
	assert(MultilayerWD.getPropNumber() == length(MultilayerWD.getProps()), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'MultilayerWD.getPropNumber() should return the number of properties.')
	assert(g.getPropNumber() == length(MultilayerWD.getProps()), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'g.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(g) == length(MultilayerWD.getProps()), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(g) should return the number of properties.')
	assert(Element.getPropNumber('MultilayerWD') == length(MultilayerWD.getProps()), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''MultilayerWD'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) MultilayerWD.getPropNumber(category), categories)) == MultilayerWD.getPropNumber(), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'MultilayerWD.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) g.getPropNumber(category), categories)) == MultilayerWD.getPropNumber(), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'g.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(g, category), categories)) == MultilayerWD.getPropNumber(), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(g, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('MultilayerWD', category), categories)) == MultilayerWD.getPropNumber(), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''MultilayerWD'', category) does not work.')
	 
	% existsProp(prop)
	assert(~MultilayerWD.existsProp(NaN), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'MultilayerWD.existsProp(prop) does not work.')
	assert(~g.existsProp(NaN), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'g.existsProp(prop) does not work.')
	assert(~Element.existsProp(g, NaN), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(g, prop) does not work.')
	assert(~Element.existsProp('MultilayerWD', NaN), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''MultilayerWD'', prop) does not work.')
	 
	assert_with_error('MultilayerWD.existsProp(NaN)', [BRAPH2.STR ':MultilayerWD:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':MultilayerWD:' BRAPH2.WRONG_INPUT], g)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':MultilayerWD:' BRAPH2.WRONG_INPUT], g)
	assert_with_error('Element.existsProp(''MultilayerWD'', NaN)', [BRAPH2.STR ':MultilayerWD:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:MultilayerWD.getPropNumber()
		assert(MultilayerWD.existsProp(prop), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'MultilayerWD.existsProp(prop) does not work.')
		assert(g.existsProp(prop), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'g.existsProp(prop) does not work.')
		assert(Element.existsProp(g, prop), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(g, prop) does not work.')
		assert(Element.existsProp('MultilayerWD', prop), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''MultilayerWD'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~MultilayerWD.existsTag(''), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'MultilayerWD.existsTag(tag) does not work.')
	assert(~g.existsTag(''), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'g.existsTag(tag) does not work.')
	assert(~Element.existsTag(g, ''), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(g, tag) does not work.')
	assert(~Element.existsTag('MultilayerWD', ''), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''MultilayerWD'', tag) does not work.')
	 
	assert_with_error('MultilayerWD.existsTag('''')', [BRAPH2.STR ':MultilayerWD:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':MultilayerWD:' BRAPH2.WRONG_INPUT], g)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':MultilayerWD:' BRAPH2.WRONG_INPUT], g)
	assert_with_error('Element.existsTag(''MultilayerWD'', '''')', [BRAPH2.STR ':MultilayerWD:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:MultilayerWD.getPropNumber()
		tag = g.getPropTag(prop);
		assert(MultilayerWD.existsTag(tag), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'MultilayerWD.existsTag(tag) does not work.')
		assert(g.existsTag(tag), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'g.existsTag(tag) does not work.')
		assert(Element.existsTag(g, tag), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(g, tga) does not work.')
		assert(Element.existsTag('MultilayerWD', tag), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''MultilayerWD'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:MultilayerWD.getPropNumber()
		assert(MultilayerWD.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'MultilayerWD.getPropProp(prop) does not work.')
		assert(g.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'g.getPropProp(prop) does not work.')
		assert(Element.getPropProp(g, prop) == prop, ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(g, prop) does not work.')
		assert(Element.getPropProp('MultilayerWD', prop) == prop, ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''MultilayerWD'', prop) does not work.')
	 
		tag = g.getPropTag(prop);
		assert(MultilayerWD.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'MultilayerWD.getPropProp(tag) does not work.')
		assert(g.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'g.getPropProp(tag) does not work.')
		assert(Element.getPropProp(g, tag) == prop, ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(g, tag) does not work.')
		assert(Element.getPropProp('MultilayerWD', prop) == prop, ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''MultilayerWD'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:MultilayerWD.getPropNumber()
		tag = g.getPropTag(prop);
	 
		assert(strcmp(MultilayerWD.getPropTag(prop), tag), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'MultilayerWD.getPropTag(prop) does not work.')
		assert(strcmp(g.getPropTag(prop), tag), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'g.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(g, prop), tag), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(g, prop) does not work.')
		assert(strcmp(Element.getPropTag('MultilayerWD', prop), tag), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''MultilayerWD'', prop) does not work.')
	 
		assert(strcmp(MultilayerWD.getPropTag(tag), tag), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'MultilayerWD.getPropTag(tag) does not work.')
		assert(strcmp(g.getPropTag(tag), tag), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'g.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(g, tag), tag), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(g, tag) does not work.')
		assert(strcmp(Element.getPropTag('MultilayerWD', prop), tag), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''MultilayerWD'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:MultilayerWD.getPropNumber()
		tag = g.getPropTag(prop);
	 
		assert(Category.existsCategory(MultilayerWD.getPropCategory(prop)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'MultilayerWD.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(g.getPropCategory(prop)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'g.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(g, prop)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(g, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(g, prop)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''MultilayerWD'', prop) does not work.')
	 
		assert(Category.existsCategory(MultilayerWD.getPropCategory(tag)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'MultilayerWD.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(g.getPropCategory(tag)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'g.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(g, tag)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(g, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(g, tag)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''MultilayerWD'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:MultilayerWD.getPropNumber()
		tag = g.getPropTag(prop);
	 
		assert(Format.existsFormat(MultilayerWD.getPropFormat(prop)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'MultilayerWD.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(g.getPropFormat(prop)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'g.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(g, prop)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(g, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(g, prop)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''MultilayerWD'', prop) does not work.')
	 
		assert(Format.existsFormat(MultilayerWD.getPropFormat(tag)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'MultilayerWD.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(g.getPropFormat(tag)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'g.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(g, tag)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(g, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(g, tag)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''MultilayerWD'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:MultilayerWD.getPropNumber()
		tag = g.getPropTag(prop);
	 
		assert(ischar(MultilayerWD.getPropDescription(prop)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'MultilayerWD.getPropDescription(prop) does not work.')
		assert(ischar(g.getPropDescription(prop)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'g.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(g, prop)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(g, prop) does not work.')
		assert(ischar(Element.getPropDescription(g, prop)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''MultilayerWD'', prop) does not work.')
	 
		assert(ischar(MultilayerWD.getPropDescription(tag)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'MultilayerWD.getPropDescription(tag) does not work.')
		assert(ischar(g.getPropDescription(tag)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'g.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(g, tag)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(g, tag) does not work.')
		assert(ischar(Element.getPropDescription(g, tag)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''MultilayerWD'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:MultilayerWD.getPropNumber()
		tag = g.getPropTag(prop);
	 
		settings = MultilayerWD.getPropSettings(prop);
		settings = g.getPropSettings(prop);
		settings = Element.getPropSettings(g, prop);
		settings = Element.getPropSettings('MultilayerWD', prop);
	 
		settings = MultilayerWD.getPropSettings(tag);
		settings = g.getPropSettings(tag);
		settings = Element.getPropSettings(g, tag);
		settings = Element.getPropSettings('MultilayerWD', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:MultilayerWD.getPropNumber()
		tag = g.getPropTag(prop);
	 
		default = MultilayerWD.getPropDefault(prop);
		default = g.getPropDefault(prop);
		default = Element.getPropDefault(g, prop);
		default = Element.getPropDefault('MultilayerWD', prop);
	 
		default = MultilayerWD.getPropDefault(tag);
		default = g.getPropDefault(tag);
		default = Element.getPropDefault(g, tag);
		default = Element.getPropDefault('MultilayerWD', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:MultilayerWD.getPropNumber()
		tag = g.getPropTag(prop);
	 
		conditioned_default = MultilayerWD.getPropDefaultConditioned(prop);
		conditioned_default = g.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(g, prop);
		conditioned_default = Element.getPropDefaultConditioned('MultilayerWD', prop);
	 
		conditioned_default = MultilayerWD.getPropDefaultConditioned(tag);
		conditioned_default = g.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(g, tag);
		conditioned_default = Element.getPropDefaultConditioned('MultilayerWD', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:MultilayerWD.getPropNumber()
		tag = g.getPropTag(prop);
	 
		assert(~MultilayerWD.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'MultilayerWD.checkProp(prop, value) does not work.')
		assert(~g.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'g.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(g, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(g, prop, value) does not work.')
		assert(~Element.checkProp('MultilayerWD', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''MultilayerWD'', prop, value) does not work.')
	 
		assert_with_error('MultilayerWD.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':MultilayerWD:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':MultilayerWD:' BRAPH2.WRONG_INPUT], prop, g)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':MultilayerWD:' BRAPH2.WRONG_INPUT], prop, g)
		assert_with_error('Element.checkProp(''MultilayerWD'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':MultilayerWD:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~MultilayerWD.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'MultilayerWD.checkProp(tag, value) does not work.')
		assert(~g.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'g.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(g, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(g, tag, value) does not work.')
		assert(~Element.checkProp('MultilayerWD', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''MultilayerWD'', tag, value) does not work.')
	 
		assert_with_error('MultilayerWD.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':MultilayerWD:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':MultilayerWD:' BRAPH2.WRONG_INPUT], tag, g)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':MultilayerWD:' BRAPH2.WRONG_INPUT], tag, g)
		assert_with_error('Element.checkProp(''MultilayerWD'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':MultilayerWD:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(MultilayerWD.checkProp(prop, Element.getPropDefaultConditioned(MultilayerWD, prop)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'MultilayerWD.checkProp(prop, <conditioned default value>) does not work.')
		assert(g.checkProp(prop, Element.getPropDefaultConditioned(MultilayerWD, prop)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'g.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(g, prop, Element.getPropDefaultConditioned(MultilayerWD, prop)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(g, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('MultilayerWD', prop, Element.getPropDefaultConditioned(MultilayerWD, prop)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''MultilayerWD'', prop, <conditioned default value>) does not work.')
	 
		assert(MultilayerWD.checkProp(tag, Element.getPropDefaultConditioned(MultilayerWD, prop)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'MultilayerWD.checkProp(tag, <conditioned default value>) does not work.')
		assert(g.checkProp(tag, Element.getPropDefaultConditioned(MultilayerWD, prop)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'g.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(g, tag, Element.getPropDefaultConditioned(MultilayerWD, prop)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(g, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('MultilayerWD', tag, Element.getPropDefaultConditioned(MultilayerWD, prop)), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''MultilayerWD'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	g = MultilayerWD( ...
		MultilayerWD.ELCLASS, MultilayerWD.getNoValue(), ...
		MultilayerWD.NAME, MultilayerWD.getNoValue(), ...
		MultilayerWD.DESCRIPTION, MultilayerWD.getNoValue(), ...
		MultilayerWD.TEMPLATE, MultilayerWD.getPropDefault(MultilayerWD.TEMPLATE), ...
		MultilayerWD.ID, MultilayerWD.getPropDefault(MultilayerWD.ID), ...
		MultilayerWD.LABEL, MultilayerWD.getPropDefault(MultilayerWD.LABEL), ...
		MultilayerWD.NOTES, MultilayerWD.getPropDefault(MultilayerWD.NOTES), ...
		MultilayerWD.TOSTRING, MultilayerWD.getNoValue(), ...
		MultilayerWD.GRAPH_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.CONNECTIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.DIRECTIONALITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.SELFCONNECTIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.NEGATIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERTICKS, MultilayerWD.getPropDefault(MultilayerWD.LAYERTICKS), ...
		MultilayerWD.ALAYERTICKS, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERLABELS, MultilayerWD.getPropDefault(MultilayerWD.LAYERLABELS), ...
		MultilayerWD.ALAYERLABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONTICKS, MultilayerWD.getPropDefault(MultilayerWD.PARTITIONTICKS), ...
		MultilayerWD.APARTITIONTICKS, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONLABELS, MultilayerWD.getPropDefault(MultilayerWD.PARTITIONLABELS), ...
		MultilayerWD.APARTITIONLABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.NODELABELS, MultilayerWD.getPropDefault(MultilayerWD.NODELABELS), ...
		MultilayerWD.ANODELABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.RANDOMIZE, MultilayerWD.getPropDefault(MultilayerWD.RANDOMIZE), ...
		MultilayerWD.RANDOM_SEED, MultilayerWD.getPropDefault(MultilayerWD.RANDOM_SEED), ...
		MultilayerWD.A, MultilayerWD.getNoValue(), ...
		MultilayerWD.A_CHECK, MultilayerWD.getNoValue(), ...
		MultilayerWD.NODENUMBER, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERNUMBER, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONS, MultilayerWD.getNoValue(), ...
		MultilayerWD.M_DICT, MultilayerWD.getNoValue(), ...
		MultilayerWD.COMPATIBLE_MEASURES, MultilayerWD.getNoValue(), ...
		MultilayerWD.MEASURE, MultilayerWD.getNoValue(), ...
		MultilayerWD.PFGA, MultilayerWD.getPropDefault(MultilayerWD.PFGA), ...
		MultilayerWD.PFGH, MultilayerWD.getPropDefault(MultilayerWD.PFGH), ...
		MultilayerWD.B, MultilayerWD.getPropDefault(MultilayerWD.B), ...
		MultilayerWD.SEMIPOSITIVIZE_RULE, MultilayerWD.getPropDefault(MultilayerWD.SEMIPOSITIVIZE_RULE), ...
		MultilayerWD.STANDARDIZE_RULE, MultilayerWD.getPropDefault(MultilayerWD.STANDARDIZE_RULE), ...
		MultilayerWD.ATTEMPTSPEREDGE, MultilayerWD.getPropDefault(MultilayerWD.ATTEMPTSPEREDGE), ...
		MultilayerWD.NUMBEROFWEIGHTS, MultilayerWD.getPropDefault(MultilayerWD.NUMBEROFWEIGHTS), ...
		MultilayerWD.RANDOMIZATION, MultilayerWD.getNoValue() ...
		);
	 
	for prop = 1:1:MultilayerWD.getPropNumber()
	 
		% excluded props
		if any(prop == [MultilayerWD.PFGA MultilayerWD.PFGH])
			continue
		end
	 
		TAG = upper(MultilayerWD.getPropTag(prop));
		switch MultilayerWD.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					g.getr(prop) == MultilayerWD.getNoValue(), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['Being a ' MultilayerWD.getCategoryName(MultilayerWD.getPropCategory(prop)) ', MultilayerWD.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in MultilayerWD.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					g.getr(TAG) == MultilayerWD.getNoValue(), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['Being a ' MultilayerWD.getCategoryName(MultilayerWD.getPropCategory(prop)) ', MultilayerWD.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in MultilayerWD.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(g.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(g.getPropSettings(prop))
					assert( ...
						g.checkFormat(g.getPropFormat(prop), g.get(prop)), ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						['MultilayerWD.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						g.checkFormat(g.getPropFormat(prop), g.get(prop), g.getPropSettings(prop)), ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						['MultilayerWD.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					g.getr(prop) == MultilayerWD.getNoValue(), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['Being a ' MultilayerWD.getCategoryName(MultilayerWD.getPropCategory(prop)) ', MultilayerWD.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in MultilayerWD.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					g.getr(TAG) == MultilayerWD.getNoValue(), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['Being a ' MultilayerWD.getCategoryName(MultilayerWD.getPropCategory(prop)) ', MultilayerWD.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in MultilayerWD.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':MultilayerWD']);
				assert( ...
					~isa(g.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(g.getPropSettings(prop))
					assert( ...
						g.checkFormat(g.getPropFormat(prop), g.get(prop)), ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						['MultilayerWD.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						g.checkFormat(g.getPropFormat(prop), g.get(prop), g.getPropSettings(prop)), ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						['MultilayerWD.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(g.getr(prop), MultilayerWD.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by MultilayerWD.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in MultilayerWD.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(g.getr(TAG), MultilayerWD.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.getr(' TAG ') must be inizialized to its default value ' ...
					'given by MultilayerWD.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in MultilayerWD.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	g = MultilayerWD( ...
		MultilayerWD.ELCLASS, MultilayerWD.getNoValue(), ...
		MultilayerWD.NAME, MultilayerWD.getNoValue(), ...
		MultilayerWD.DESCRIPTION, MultilayerWD.getNoValue(), ...
		MultilayerWD.TEMPLATE, MultilayerWD.getPropDefault(MultilayerWD.TEMPLATE), ...
		MultilayerWD.ID, MultilayerWD.getPropDefault(MultilayerWD.ID), ...
		MultilayerWD.LABEL, MultilayerWD.getPropDefault(MultilayerWD.LABEL), ...
		MultilayerWD.NOTES, MultilayerWD.getPropDefault(MultilayerWD.NOTES), ...
		MultilayerWD.TOSTRING, MultilayerWD.getNoValue(), ...
		MultilayerWD.GRAPH_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.CONNECTIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.DIRECTIONALITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.SELFCONNECTIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.NEGATIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERTICKS, MultilayerWD.getPropDefault(MultilayerWD.LAYERTICKS), ...
		MultilayerWD.ALAYERTICKS, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERLABELS, MultilayerWD.getPropDefault(MultilayerWD.LAYERLABELS), ...
		MultilayerWD.ALAYERLABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONTICKS, MultilayerWD.getPropDefault(MultilayerWD.PARTITIONTICKS), ...
		MultilayerWD.APARTITIONTICKS, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONLABELS, MultilayerWD.getPropDefault(MultilayerWD.PARTITIONLABELS), ...
		MultilayerWD.APARTITIONLABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.NODELABELS, MultilayerWD.getPropDefault(MultilayerWD.NODELABELS), ...
		MultilayerWD.ANODELABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.RANDOMIZE, MultilayerWD.getPropDefault(MultilayerWD.RANDOMIZE), ...
		MultilayerWD.RANDOM_SEED, MultilayerWD.getPropDefault(MultilayerWD.RANDOM_SEED), ...
		MultilayerWD.A, MultilayerWD.getNoValue(), ...
		MultilayerWD.A_CHECK, MultilayerWD.getNoValue(), ...
		MultilayerWD.NODENUMBER, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERNUMBER, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONS, MultilayerWD.getNoValue(), ...
		MultilayerWD.M_DICT, MultilayerWD.getNoValue(), ...
		MultilayerWD.COMPATIBLE_MEASURES, MultilayerWD.getNoValue(), ...
		MultilayerWD.MEASURE, MultilayerWD.getNoValue(), ...
		MultilayerWD.PFGA, MultilayerWD.getPropDefault(MultilayerWD.PFGA), ...
		MultilayerWD.PFGH, MultilayerWD.getPropDefault(MultilayerWD.PFGH), ...
		MultilayerWD.B, MultilayerWD.getPropDefault(MultilayerWD.B), ...
		MultilayerWD.SEMIPOSITIVIZE_RULE, MultilayerWD.getPropDefault(MultilayerWD.SEMIPOSITIVIZE_RULE), ...
		MultilayerWD.STANDARDIZE_RULE, MultilayerWD.getPropDefault(MultilayerWD.STANDARDIZE_RULE), ...
		MultilayerWD.ATTEMPTSPEREDGE, MultilayerWD.getPropDefault(MultilayerWD.ATTEMPTSPEREDGE), ...
		MultilayerWD.NUMBEROFWEIGHTS, MultilayerWD.getPropDefault(MultilayerWD.NUMBEROFWEIGHTS), ...
		MultilayerWD.RANDOMIZATION, MultilayerWD.getNoValue() ...
		);
	 
	for prop = 1:1:MultilayerWD.getPropNumber()
	 
		% excluded props
		if any(prop == [MultilayerWD.PFGA MultilayerWD.PFGH])
			continue
		end
	 
		TAG = upper(MultilayerWD.getPropTag(prop));
		switch MultilayerWD.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(g.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(g.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(g.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(g.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					g.checkFormat(g.getPropFormat(prop), g.getr(prop),g.getPropSettings(prop)), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':MultilayerWD']);
				assert( ...
					~isa(g.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(g.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':MultilayerWD']);
	% 			assert( ...
	% 				~isa(g.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
	% 				['MultilayerWD.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(g.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
	% 				['MultilayerWD.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				g.checkFormat(g.getPropFormat(prop), g.getr(prop),g.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
	% 				['MultilayerWD.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':MultilayerWD']);
				assert( ...
					~isa(g.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(g.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(g.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(g.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					g.checkFormat(g.getPropFormat(prop), g.getr(prop),g.getPropSettings(prop)), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if g.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:MultilayerWD');
					delete(ancestor(g.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(MultilayerWD.getProps(Category.RESULT))
		for prop = 1:1:MultilayerWD.getPropNumber()
	 
			% excluded props
			if any(prop == [MultilayerWD.PFGA MultilayerWD.PFGH])
				continue
			end
	 
			switch MultilayerWD.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						g.isLocked(prop), ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						['MultilayerWD.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~g.isLocked(prop), ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						['MultilayerWD.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	g = MultilayerWD();
	 
	for prop = 1:1:MultilayerWD.getPropNumber()
		TAG = upper(MultilayerWD.getPropTag(prop));
		assert( ...
			~g.isLocked(prop), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			['MultilayerWD.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~g.isLocked(TAG), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			['MultilayerWD.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	g.lock()
	 
	for prop = 1:1:MultilayerWD.getPropNumber()
		switch MultilayerWD.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					g.isLocked(prop), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~g.isLocked(prop), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	g = MultilayerWD();
	 
	warning_backup = warning('off', 'BRAPH2:MultilayerWD');
	for prop = 1:1:MultilayerWD.getPropNumber()
		g.lock(prop)
		switch MultilayerWD.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					g.isLocked(prop), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~g.isLocked(prop), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	g = MultilayerWD();
	 
	for prop = 1:1:MultilayerWD.getPropNumber()
		TAG = upper(MultilayerWD.getPropTag(prop));
		assert( ...
			g.isChecked(prop), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			['MultilayerWD.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			g.isChecked(TAG), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			['MultilayerWD.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	g.unchecked()
	 
	for prop = 1:1:MultilayerWD.getPropNumber()
		assert( ...
			~g.isChecked(prop), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			['MultilayerWD.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	g.checked()
	 
	for prop = 1:1:MultilayerWD.getPropNumber()
		assert( ...
			g.isChecked(prop), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			['MultilayerWD.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic MultilayerWD
	g_0 = MultilayerWD( ...
		MultilayerWD.ELCLASS, MultilayerWD.getNoValue(), ...
		MultilayerWD.NAME, MultilayerWD.getNoValue(), ...
		MultilayerWD.DESCRIPTION, MultilayerWD.getNoValue(), ...
		MultilayerWD.TEMPLATE, MultilayerWD.getPropDefault(MultilayerWD.TEMPLATE), ...
		MultilayerWD.ID, MultilayerWD.getPropDefault(MultilayerWD.ID), ...
		MultilayerWD.LABEL, MultilayerWD.getPropDefault(MultilayerWD.LABEL), ...
		MultilayerWD.NOTES, MultilayerWD.getPropDefault(MultilayerWD.NOTES), ...
		MultilayerWD.TOSTRING, MultilayerWD.getNoValue(), ...
		MultilayerWD.GRAPH_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.CONNECTIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.DIRECTIONALITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.SELFCONNECTIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.NEGATIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERTICKS, MultilayerWD.getPropDefault(MultilayerWD.LAYERTICKS), ...
		MultilayerWD.ALAYERTICKS, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERLABELS, MultilayerWD.getPropDefault(MultilayerWD.LAYERLABELS), ...
		MultilayerWD.ALAYERLABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONTICKS, MultilayerWD.getPropDefault(MultilayerWD.PARTITIONTICKS), ...
		MultilayerWD.APARTITIONTICKS, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONLABELS, MultilayerWD.getPropDefault(MultilayerWD.PARTITIONLABELS), ...
		MultilayerWD.APARTITIONLABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.NODELABELS, MultilayerWD.getPropDefault(MultilayerWD.NODELABELS), ...
		MultilayerWD.ANODELABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.RANDOMIZE, MultilayerWD.getPropDefault(MultilayerWD.RANDOMIZE), ...
		MultilayerWD.RANDOM_SEED, MultilayerWD.getPropDefault(MultilayerWD.RANDOM_SEED), ...
		MultilayerWD.A, MultilayerWD.getNoValue(), ...
		MultilayerWD.A_CHECK, MultilayerWD.getNoValue(), ...
		MultilayerWD.NODENUMBER, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERNUMBER, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONS, MultilayerWD.getNoValue(), ...
		MultilayerWD.M_DICT, MultilayerWD.getNoValue(), ...
		MultilayerWD.COMPATIBLE_MEASURES, MultilayerWD.getNoValue(), ...
		MultilayerWD.MEASURE, MultilayerWD.getNoValue(), ...
		MultilayerWD.PFGA, MultilayerWD.getPropDefault(MultilayerWD.PFGA), ...
		MultilayerWD.PFGH, MultilayerWD.getPropDefault(MultilayerWD.PFGH), ...
		MultilayerWD.B, MultilayerWD.getPropDefault(MultilayerWD.B), ...
		MultilayerWD.SEMIPOSITIVIZE_RULE, MultilayerWD.getPropDefault(MultilayerWD.SEMIPOSITIVIZE_RULE), ...
		MultilayerWD.STANDARDIZE_RULE, MultilayerWD.getPropDefault(MultilayerWD.STANDARDIZE_RULE), ...
		MultilayerWD.ATTEMPTSPEREDGE, MultilayerWD.getPropDefault(MultilayerWD.ATTEMPTSPEREDGE), ...
		MultilayerWD.NUMBEROFWEIGHTS, MultilayerWD.getPropDefault(MultilayerWD.NUMBEROFWEIGHTS), ...
		MultilayerWD.RANDOMIZATION, MultilayerWD.getNoValue() ...
		);
	 
	% MultilayerWD with 1st callbacks
	g_1 = MultilayerWD( ...
		MultilayerWD.ELCLASS, MultilayerWD.getNoValue(), ...
		MultilayerWD.NAME, MultilayerWD.getNoValue(), ...
		MultilayerWD.DESCRIPTION, MultilayerWD.getNoValue(), ...
		MultilayerWD.TEMPLATE, g_0.getCallback(4), ..., ...
		MultilayerWD.ID, g_0.getCallback(5), ..., ...
		MultilayerWD.LABEL, MultilayerWD.getPropDefault(MultilayerWD.LABEL), ...
		MultilayerWD.NOTES, MultilayerWD.getPropDefault(MultilayerWD.NOTES), ...
		MultilayerWD.TOSTRING, MultilayerWD.getNoValue(), ...
		MultilayerWD.GRAPH_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.CONNECTIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.DIRECTIONALITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.SELFCONNECTIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.NEGATIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERTICKS, MultilayerWD.getPropDefault(MultilayerWD.LAYERTICKS), ...
		MultilayerWD.ALAYERTICKS, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERLABELS, MultilayerWD.getPropDefault(MultilayerWD.LAYERLABELS), ...
		MultilayerWD.ALAYERLABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONTICKS, MultilayerWD.getPropDefault(MultilayerWD.PARTITIONTICKS), ...
		MultilayerWD.APARTITIONTICKS, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONLABELS, MultilayerWD.getPropDefault(MultilayerWD.PARTITIONLABELS), ...
		MultilayerWD.APARTITIONLABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.NODELABELS, MultilayerWD.getPropDefault(MultilayerWD.NODELABELS), ...
		MultilayerWD.ANODELABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.RANDOMIZE, g_0.getCallback(24), ..., ...
		MultilayerWD.RANDOM_SEED, g_0.getCallback(25), ..., ...
		MultilayerWD.A, MultilayerWD.getNoValue(), ...
		MultilayerWD.A_CHECK, MultilayerWD.getNoValue(), ...
		MultilayerWD.NODENUMBER, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERNUMBER, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONS, MultilayerWD.getNoValue(), ...
		MultilayerWD.M_DICT, MultilayerWD.getNoValue(), ...
		MultilayerWD.COMPATIBLE_MEASURES, MultilayerWD.getNoValue(), ...
		MultilayerWD.MEASURE, MultilayerWD.getNoValue(), ...
		MultilayerWD.PFGA, g_0.getCallback(34), ..., ...
		MultilayerWD.PFGH, g_0.getCallback(35), ..., ...
		MultilayerWD.B, g_0.getCallback(36), ..., ...
		MultilayerWD.SEMIPOSITIVIZE_RULE, g_0.getCallback(37), ..., ...
		MultilayerWD.STANDARDIZE_RULE, g_0.getCallback(38), ..., ...
		MultilayerWD.ATTEMPTSPEREDGE, g_0.getCallback(39), ..., ...
		MultilayerWD.NUMBEROFWEIGHTS, g_0.getCallback(40), ..., ...
		MultilayerWD.RANDOMIZATION, MultilayerWD.getNoValue() ...
		);
	 
	prop_number = MultilayerWD.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(MultilayerWD.getPropTag(prop));
		switch MultilayerWD.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(g_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(g_1.get(prop), g_0.get(prop)) && ~isa(g_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(g_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% MultilayerWD with 2nd callbacks
	g_2 = MultilayerWD( ...
		MultilayerWD.ELCLASS, MultilayerWD.getNoValue(), ...
		MultilayerWD.NAME, MultilayerWD.getNoValue(), ...
		MultilayerWD.DESCRIPTION, MultilayerWD.getNoValue(), ...
		MultilayerWD.TEMPLATE, g_1.getCallback(4), ..., ...
		MultilayerWD.ID, g_1.getCallback(5), ..., ...
		MultilayerWD.LABEL, MultilayerWD.getPropDefault(MultilayerWD.LABEL), ...
		MultilayerWD.NOTES, MultilayerWD.getPropDefault(MultilayerWD.NOTES), ...
		MultilayerWD.TOSTRING, MultilayerWD.getNoValue(), ...
		MultilayerWD.GRAPH_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.CONNECTIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.DIRECTIONALITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.SELFCONNECTIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.NEGATIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERTICKS, MultilayerWD.getPropDefault(MultilayerWD.LAYERTICKS), ...
		MultilayerWD.ALAYERTICKS, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERLABELS, MultilayerWD.getPropDefault(MultilayerWD.LAYERLABELS), ...
		MultilayerWD.ALAYERLABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONTICKS, MultilayerWD.getPropDefault(MultilayerWD.PARTITIONTICKS), ...
		MultilayerWD.APARTITIONTICKS, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONLABELS, MultilayerWD.getPropDefault(MultilayerWD.PARTITIONLABELS), ...
		MultilayerWD.APARTITIONLABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.NODELABELS, MultilayerWD.getPropDefault(MultilayerWD.NODELABELS), ...
		MultilayerWD.ANODELABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.RANDOMIZE, g_1.getCallback(24), ..., ...
		MultilayerWD.RANDOM_SEED, g_1.getCallback(25), ..., ...
		MultilayerWD.A, MultilayerWD.getNoValue(), ...
		MultilayerWD.A_CHECK, MultilayerWD.getNoValue(), ...
		MultilayerWD.NODENUMBER, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERNUMBER, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONS, MultilayerWD.getNoValue(), ...
		MultilayerWD.M_DICT, MultilayerWD.getNoValue(), ...
		MultilayerWD.COMPATIBLE_MEASURES, MultilayerWD.getNoValue(), ...
		MultilayerWD.MEASURE, MultilayerWD.getNoValue(), ...
		MultilayerWD.PFGA, g_1.getCallback(34), ..., ...
		MultilayerWD.PFGH, g_1.getCallback(35), ..., ...
		MultilayerWD.B, g_1.getCallback(36), ..., ...
		MultilayerWD.SEMIPOSITIVIZE_RULE, g_1.getCallback(37), ..., ...
		MultilayerWD.STANDARDIZE_RULE, g_1.getCallback(38), ..., ...
		MultilayerWD.ATTEMPTSPEREDGE, g_1.getCallback(39), ..., ...
		MultilayerWD.NUMBEROFWEIGHTS, g_1.getCallback(40), ..., ...
		MultilayerWD.RANDOMIZATION, MultilayerWD.getNoValue() ...
		);
	 
	prop_number = MultilayerWD.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(MultilayerWD.getPropTag(prop));
		switch MultilayerWD.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(g_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(g_2.get(prop), g_0.get(prop)) && ~isa(g_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(g_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% MultilayerWD with 3rd callbacks
	g_3 = MultilayerWD( ...
		MultilayerWD.ELCLASS, MultilayerWD.getNoValue(), ...
		MultilayerWD.NAME, MultilayerWD.getNoValue(), ...
		MultilayerWD.DESCRIPTION, MultilayerWD.getNoValue(), ...
		MultilayerWD.TEMPLATE, g_2.getCallback(4), ..., ...
		MultilayerWD.ID, g_2.getCallback(5), ..., ...
		MultilayerWD.LABEL, MultilayerWD.getPropDefault(MultilayerWD.LABEL), ...
		MultilayerWD.NOTES, MultilayerWD.getPropDefault(MultilayerWD.NOTES), ...
		MultilayerWD.TOSTRING, MultilayerWD.getNoValue(), ...
		MultilayerWD.GRAPH_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.CONNECTIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.DIRECTIONALITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.SELFCONNECTIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.NEGATIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERTICKS, MultilayerWD.getPropDefault(MultilayerWD.LAYERTICKS), ...
		MultilayerWD.ALAYERTICKS, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERLABELS, MultilayerWD.getPropDefault(MultilayerWD.LAYERLABELS), ...
		MultilayerWD.ALAYERLABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONTICKS, MultilayerWD.getPropDefault(MultilayerWD.PARTITIONTICKS), ...
		MultilayerWD.APARTITIONTICKS, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONLABELS, MultilayerWD.getPropDefault(MultilayerWD.PARTITIONLABELS), ...
		MultilayerWD.APARTITIONLABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.NODELABELS, MultilayerWD.getPropDefault(MultilayerWD.NODELABELS), ...
		MultilayerWD.ANODELABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.RANDOMIZE, g_2.getCallback(24), ..., ...
		MultilayerWD.RANDOM_SEED, g_2.getCallback(25), ..., ...
		MultilayerWD.A, MultilayerWD.getNoValue(), ...
		MultilayerWD.A_CHECK, MultilayerWD.getNoValue(), ...
		MultilayerWD.NODENUMBER, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERNUMBER, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONS, MultilayerWD.getNoValue(), ...
		MultilayerWD.M_DICT, MultilayerWD.getNoValue(), ...
		MultilayerWD.COMPATIBLE_MEASURES, MultilayerWD.getNoValue(), ...
		MultilayerWD.MEASURE, MultilayerWD.getNoValue(), ...
		MultilayerWD.PFGA, g_2.getCallback(34), ..., ...
		MultilayerWD.PFGH, g_2.getCallback(35), ..., ...
		MultilayerWD.B, g_2.getCallback(36), ..., ...
		MultilayerWD.SEMIPOSITIVIZE_RULE, g_2.getCallback(37), ..., ...
		MultilayerWD.STANDARDIZE_RULE, g_2.getCallback(38), ..., ...
		MultilayerWD.ATTEMPTSPEREDGE, g_2.getCallback(39), ..., ...
		MultilayerWD.NUMBEROFWEIGHTS, g_2.getCallback(40), ..., ...
		MultilayerWD.RANDOMIZATION, MultilayerWD.getNoValue() ...
		);
	 
	prop_number = MultilayerWD.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(MultilayerWD.getPropTag(prop));
		switch MultilayerWD.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(g_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(g_3.get(prop), g_0.get(prop)) && ~isa(g_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(g_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	g = MultilayerWD();
	 
	g_copy = g.copy();
	 
	assert(g_copy ~= g, ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'MultilayerWD.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(g_copy, g), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'MultilayerWD.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:MultilayerWD.getPropNumber()
		value = g.getr(prop);
		value_copy = g_copy.getr(prop);
		switch MultilayerWD.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					'MultilayerWD.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						'MultilayerWD.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						'MultilayerWD.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						'MultilayerWD.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
							'MultilayerWD.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
							'MultilayerWD.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						'MultilayerWD.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					g_copy.isLocked(prop) == g.isLocked(prop), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					'MultilayerWD.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					g_copy.isChecked(prop) == g.isChecked(prop), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					'MultilayerWD.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					g_copy.getPropSeed(prop) == g.getPropSeed(prop), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					'MultilayerWD.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	g = MultilayerWD( ...
		MultilayerWD.ELCLASS, MultilayerWD.getNoValue(), ...
		MultilayerWD.NAME, MultilayerWD.getNoValue(), ...
		MultilayerWD.DESCRIPTION, MultilayerWD.getNoValue(), ...
		MultilayerWD.TEMPLATE, MultilayerWD.getPropDefault(MultilayerWD.TEMPLATE), ...
		MultilayerWD.ID, MultilayerWD.getPropDefault(MultilayerWD.ID), ...
		MultilayerWD.LABEL, MultilayerWD.getPropDefault(MultilayerWD.LABEL), ...
		MultilayerWD.NOTES, MultilayerWD.getPropDefault(MultilayerWD.NOTES), ...
		MultilayerWD.TOSTRING, MultilayerWD.getNoValue(), ...
		MultilayerWD.GRAPH_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.CONNECTIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.DIRECTIONALITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.SELFCONNECTIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.NEGATIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERTICKS, MultilayerWD.getPropDefault(MultilayerWD.LAYERTICKS), ...
		MultilayerWD.ALAYERTICKS, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERLABELS, MultilayerWD.getPropDefault(MultilayerWD.LAYERLABELS), ...
		MultilayerWD.ALAYERLABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONTICKS, MultilayerWD.getPropDefault(MultilayerWD.PARTITIONTICKS), ...
		MultilayerWD.APARTITIONTICKS, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONLABELS, MultilayerWD.getPropDefault(MultilayerWD.PARTITIONLABELS), ...
		MultilayerWD.APARTITIONLABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.NODELABELS, MultilayerWD.getPropDefault(MultilayerWD.NODELABELS), ...
		MultilayerWD.ANODELABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.RANDOMIZE, MultilayerWD.getPropDefault(MultilayerWD.RANDOMIZE), ...
		MultilayerWD.RANDOM_SEED, MultilayerWD.getPropDefault(MultilayerWD.RANDOM_SEED), ...
		MultilayerWD.A, MultilayerWD.getNoValue(), ...
		MultilayerWD.A_CHECK, MultilayerWD.getNoValue(), ...
		MultilayerWD.NODENUMBER, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERNUMBER, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONS, MultilayerWD.getNoValue(), ...
		MultilayerWD.M_DICT, MultilayerWD.getNoValue(), ...
		MultilayerWD.COMPATIBLE_MEASURES, MultilayerWD.getNoValue(), ...
		MultilayerWD.MEASURE, MultilayerWD.getNoValue(), ...
		MultilayerWD.PFGA, MultilayerWD.getPropDefault(MultilayerWD.PFGA), ...
		MultilayerWD.PFGH, MultilayerWD.getPropDefault(MultilayerWD.PFGH), ...
		MultilayerWD.B, MultilayerWD.getPropDefault(MultilayerWD.B), ...
		MultilayerWD.SEMIPOSITIVIZE_RULE, MultilayerWD.getPropDefault(MultilayerWD.SEMIPOSITIVIZE_RULE), ...
		MultilayerWD.STANDARDIZE_RULE, MultilayerWD.getPropDefault(MultilayerWD.STANDARDIZE_RULE), ...
		MultilayerWD.ATTEMPTSPEREDGE, MultilayerWD.getPropDefault(MultilayerWD.ATTEMPTSPEREDGE), ...
		MultilayerWD.NUMBEROFWEIGHTS, MultilayerWD.getPropDefault(MultilayerWD.NUMBEROFWEIGHTS), ...
		MultilayerWD.RANDOMIZATION, MultilayerWD.getNoValue() ...
		);
	 
	for prop = 1:1:MultilayerWD.getPropNumber()
		if MultilayerWD.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':MultilayerWD']);
			% g.memorize(prop);
			% warning(warning_backup)
		elseif MultilayerWD.getPropCategory(prop) == Category.EVANESCENT && g.getPropFormat(prop) == Format.HANDLE
			g.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:MultilayerWD');
			delete(ancestor(g.get(prop), 'figure'))
			warning(warning_backup)
		else
			g.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	g_copy = g.copy();
	 
	for prop = 1:1:MultilayerWD.getPropNumber()
		value = g.getr(prop);
		value_copy = g_copy.getr(prop);
		switch MultilayerWD.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					'MultilayerWD.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						'MultilayerWD.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						'MultilayerWD.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						'MultilayerWD.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
							'MultilayerWD.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
							'MultilayerWD.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						'MultilayerWD.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						g_copy.isLocked(prop) == g.isLocked(prop), ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						'MultilayerWD.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						g_copy.isChecked(prop) == g.isChecked(prop), ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						'MultilayerWD.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						g_copy.getPropSeed(prop) == g.getPropSeed(prop), ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						'MultilayerWD.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	g_0 = MultilayerWD( ...
		MultilayerWD.ELCLASS, MultilayerWD.getNoValue(), ...
		MultilayerWD.NAME, MultilayerWD.getNoValue(), ...
		MultilayerWD.DESCRIPTION, MultilayerWD.getNoValue(), ...
		MultilayerWD.TEMPLATE, MultilayerWD.getPropDefault(MultilayerWD.TEMPLATE), ...
		MultilayerWD.ID, MultilayerWD.getPropDefault(MultilayerWD.ID), ...
		MultilayerWD.LABEL, MultilayerWD.getPropDefault(MultilayerWD.LABEL), ...
		MultilayerWD.NOTES, MultilayerWD.getPropDefault(MultilayerWD.NOTES), ...
		MultilayerWD.TOSTRING, MultilayerWD.getNoValue(), ...
		MultilayerWD.GRAPH_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.CONNECTIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.DIRECTIONALITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.SELFCONNECTIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.NEGATIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERTICKS, MultilayerWD.getPropDefault(MultilayerWD.LAYERTICKS), ...
		MultilayerWD.ALAYERTICKS, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERLABELS, MultilayerWD.getPropDefault(MultilayerWD.LAYERLABELS), ...
		MultilayerWD.ALAYERLABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONTICKS, MultilayerWD.getPropDefault(MultilayerWD.PARTITIONTICKS), ...
		MultilayerWD.APARTITIONTICKS, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONLABELS, MultilayerWD.getPropDefault(MultilayerWD.PARTITIONLABELS), ...
		MultilayerWD.APARTITIONLABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.NODELABELS, MultilayerWD.getPropDefault(MultilayerWD.NODELABELS), ...
		MultilayerWD.ANODELABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.RANDOMIZE, MultilayerWD.getPropDefault(MultilayerWD.RANDOMIZE), ...
		MultilayerWD.RANDOM_SEED, MultilayerWD.getPropDefault(MultilayerWD.RANDOM_SEED), ...
		MultilayerWD.A, MultilayerWD.getNoValue(), ...
		MultilayerWD.A_CHECK, MultilayerWD.getNoValue(), ...
		MultilayerWD.NODENUMBER, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERNUMBER, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONS, MultilayerWD.getNoValue(), ...
		MultilayerWD.M_DICT, MultilayerWD.getNoValue(), ...
		MultilayerWD.COMPATIBLE_MEASURES, MultilayerWD.getNoValue(), ...
		MultilayerWD.MEASURE, MultilayerWD.getNoValue(), ...
		MultilayerWD.PFGA, MultilayerWD.getPropDefault(MultilayerWD.PFGA), ...
		MultilayerWD.PFGH, MultilayerWD.getPropDefault(MultilayerWD.PFGH), ...
		MultilayerWD.B, MultilayerWD.getPropDefault(MultilayerWD.B), ...
		MultilayerWD.SEMIPOSITIVIZE_RULE, MultilayerWD.getPropDefault(MultilayerWD.SEMIPOSITIVIZE_RULE), ...
		MultilayerWD.STANDARDIZE_RULE, MultilayerWD.getPropDefault(MultilayerWD.STANDARDIZE_RULE), ...
		MultilayerWD.ATTEMPTSPEREDGE, MultilayerWD.getPropDefault(MultilayerWD.ATTEMPTSPEREDGE), ...
		MultilayerWD.NUMBEROFWEIGHTS, MultilayerWD.getPropDefault(MultilayerWD.NUMBEROFWEIGHTS), ...
		MultilayerWD.RANDOMIZATION, MultilayerWD.getNoValue() ...
		);
	 
	g = MultilayerWD( ...
		MultilayerWD.ELCLASS, MultilayerWD.getNoValue(), ...
		MultilayerWD.NAME, MultilayerWD.getNoValue(), ...
		MultilayerWD.DESCRIPTION, MultilayerWD.getNoValue(), ...
		MultilayerWD.TEMPLATE, g_0.getCallback(4), ..., ...
		MultilayerWD.ID, g_0.getCallback(5), ..., ...
		MultilayerWD.LABEL, MultilayerWD.getPropDefault(MultilayerWD.LABEL), ...
		MultilayerWD.NOTES, MultilayerWD.getPropDefault(MultilayerWD.NOTES), ...
		MultilayerWD.TOSTRING, MultilayerWD.getNoValue(), ...
		MultilayerWD.GRAPH_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.CONNECTIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.DIRECTIONALITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.SELFCONNECTIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.NEGATIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERTICKS, MultilayerWD.getPropDefault(MultilayerWD.LAYERTICKS), ...
		MultilayerWD.ALAYERTICKS, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERLABELS, MultilayerWD.getPropDefault(MultilayerWD.LAYERLABELS), ...
		MultilayerWD.ALAYERLABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONTICKS, MultilayerWD.getPropDefault(MultilayerWD.PARTITIONTICKS), ...
		MultilayerWD.APARTITIONTICKS, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONLABELS, MultilayerWD.getPropDefault(MultilayerWD.PARTITIONLABELS), ...
		MultilayerWD.APARTITIONLABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.NODELABELS, MultilayerWD.getPropDefault(MultilayerWD.NODELABELS), ...
		MultilayerWD.ANODELABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.RANDOMIZE, g_0.getCallback(24), ..., ...
		MultilayerWD.RANDOM_SEED, g_0.getCallback(25), ..., ...
		MultilayerWD.A, MultilayerWD.getNoValue(), ...
		MultilayerWD.A_CHECK, MultilayerWD.getNoValue(), ...
		MultilayerWD.NODENUMBER, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERNUMBER, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONS, MultilayerWD.getNoValue(), ...
		MultilayerWD.M_DICT, MultilayerWD.getNoValue(), ...
		MultilayerWD.COMPATIBLE_MEASURES, MultilayerWD.getNoValue(), ...
		MultilayerWD.MEASURE, MultilayerWD.getNoValue(), ...
		MultilayerWD.PFGA, g_0.getCallback(34), ..., ...
		MultilayerWD.PFGH, g_0.getCallback(35), ..., ...
		MultilayerWD.B, g_0.getCallback(36), ..., ...
		MultilayerWD.SEMIPOSITIVIZE_RULE, g_0.getCallback(37), ..., ...
		MultilayerWD.STANDARDIZE_RULE, g_0.getCallback(38), ..., ...
		MultilayerWD.ATTEMPTSPEREDGE, g_0.getCallback(39), ..., ...
		MultilayerWD.NUMBEROFWEIGHTS, g_0.getCallback(40), ..., ...
		MultilayerWD.RANDOMIZATION, MultilayerWD.getNoValue() ...
		);
	 
	g_copy = g.copy();
	g_0_copy = g_copy.getr('ID').get('EL');
	 
	for prop = 1:1:MultilayerWD.getPropNumber()
		value = g.getr(prop);
		value_copy = g_copy.getr(prop);
		switch MultilayerWD.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					'MultilayerWD.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						'MultilayerWD.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						'MultilayerWD.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						'MultilayerWD.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
							'MultilayerWD.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
							'MultilayerWD.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						'MultilayerWD.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == g_0.getCallback(prop), ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						'MultilayerWD.copy() does not work. The callback should be obtained from MultilayerWD.getCallback().' ...
						)
					assert( ...
						value_copy == g_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						'MultilayerWD.copy() does not work. The callback should be obtained from MultilayerWD.getCallback().' ...
						)
				end
	 
					assert( ...
						g_copy.isLocked(prop) == g.isLocked(prop), ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						'MultilayerWD.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						g_copy.isChecked(prop) == g.isChecked(prop), ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						'MultilayerWD.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						g_copy.getPropSeed(prop) == g.getPropSeed(prop), ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						'MultilayerWD.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	g_template = MultilayerWD();
	g = MultilayerWD('TEMPLATE', g_template);
	 
	for prop = 1:1:MultilayerWD.getPropNumber()
	 
		% excluded props
		if any(prop == [MultilayerWD.PFGA MultilayerWD.PFGH])
			continue
		end
	 
		TAG = upper(MultilayerWD.getPropTag(prop));
		switch MultilayerWD.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == MultilayerWD.TEMPLATE
					assert( ...
						isa(g.getr(prop), 'MultilayerWD'), ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						'MultilayerWD TEMPLATE does not work. MultilayerWD.getr(''TEMPLATE'') should be a MultilayerWD element.' ...
						)
					assert( ...
						isa(g_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						'MultilayerWD TEMPLATE does not work. MultilayerWD_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(g.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						['MultilayerWD TEMPLATE does not work. MultilayerWD.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						g.getr(prop).get('EL') == g_template && g.getr(prop).get('PROP') == prop && strcmp(g.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						['MultilayerWD TEMPLATE does not work. MultilayerWD.getr(' TAG ') should be a Callback to g_template.' TAG '.'] ...
						)
					assert( ...
						isa(g_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
						['MultilayerWD TEMPLATE does not work. MultilayerWD_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(g.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD TEMPLATE does not work. MultilayerWD.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(g_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
					['MultilayerWD TEMPLATE does not work. MultilayerWD_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	g = MultilayerWD( ...
		MultilayerWD.ELCLASS, MultilayerWD.getNoValue(), ...
		MultilayerWD.NAME, MultilayerWD.getNoValue(), ...
		MultilayerWD.DESCRIPTION, MultilayerWD.getNoValue(), ...
		MultilayerWD.TEMPLATE, MultilayerWD.getPropDefault(MultilayerWD.TEMPLATE), ...
		MultilayerWD.ID, MultilayerWD.getPropDefault(MultilayerWD.ID), ...
		MultilayerWD.LABEL, MultilayerWD.getPropDefault(MultilayerWD.LABEL), ...
		MultilayerWD.NOTES, MultilayerWD.getPropDefault(MultilayerWD.NOTES), ...
		MultilayerWD.TOSTRING, MultilayerWD.getNoValue(), ...
		MultilayerWD.GRAPH_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.CONNECTIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.DIRECTIONALITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.SELFCONNECTIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.NEGATIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERTICKS, MultilayerWD.getPropDefault(MultilayerWD.LAYERTICKS), ...
		MultilayerWD.ALAYERTICKS, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERLABELS, MultilayerWD.getPropDefault(MultilayerWD.LAYERLABELS), ...
		MultilayerWD.ALAYERLABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONTICKS, MultilayerWD.getPropDefault(MultilayerWD.PARTITIONTICKS), ...
		MultilayerWD.APARTITIONTICKS, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONLABELS, MultilayerWD.getPropDefault(MultilayerWD.PARTITIONLABELS), ...
		MultilayerWD.APARTITIONLABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.NODELABELS, MultilayerWD.getPropDefault(MultilayerWD.NODELABELS), ...
		MultilayerWD.ANODELABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.RANDOMIZE, MultilayerWD.getPropDefault(MultilayerWD.RANDOMIZE), ...
		MultilayerWD.RANDOM_SEED, MultilayerWD.getPropDefault(MultilayerWD.RANDOM_SEED), ...
		MultilayerWD.A, MultilayerWD.getNoValue(), ...
		MultilayerWD.A_CHECK, MultilayerWD.getNoValue(), ...
		MultilayerWD.NODENUMBER, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERNUMBER, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONS, MultilayerWD.getNoValue(), ...
		MultilayerWD.M_DICT, MultilayerWD.getNoValue(), ...
		MultilayerWD.COMPATIBLE_MEASURES, MultilayerWD.getNoValue(), ...
		MultilayerWD.MEASURE, MultilayerWD.getNoValue(), ...
		MultilayerWD.PFGA, MultilayerWD.getPropDefault(MultilayerWD.PFGA), ...
		MultilayerWD.PFGH, MultilayerWD.getPropDefault(MultilayerWD.PFGH), ...
		MultilayerWD.B, MultilayerWD.getPropDefault(MultilayerWD.B), ...
		MultilayerWD.SEMIPOSITIVIZE_RULE, MultilayerWD.getPropDefault(MultilayerWD.SEMIPOSITIVIZE_RULE), ...
		MultilayerWD.STANDARDIZE_RULE, MultilayerWD.getPropDefault(MultilayerWD.STANDARDIZE_RULE), ...
		MultilayerWD.ATTEMPTSPEREDGE, MultilayerWD.getPropDefault(MultilayerWD.ATTEMPTSPEREDGE), ...
		MultilayerWD.NUMBEROFWEIGHTS, MultilayerWD.getPropDefault(MultilayerWD.NUMBEROFWEIGHTS), ...
		MultilayerWD.RANDOMIZATION, MultilayerWD.getNoValue() ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'multilayerwd_to_be_erased.b2'];
	 
	Element.save(g, filename)
	 
	g_loaded = Element.load(filename);
	 
	assert( ...
		isequal(g.copy(), g_loaded), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'MultilayerWD.save(g) and/or MultilayerWD.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	g = MultilayerWD( ...
		MultilayerWD.ELCLASS, MultilayerWD.getNoValue(), ...
		MultilayerWD.NAME, MultilayerWD.getNoValue(), ...
		MultilayerWD.DESCRIPTION, MultilayerWD.getNoValue(), ...
		MultilayerWD.TEMPLATE, MultilayerWD.getPropDefault(MultilayerWD.TEMPLATE), ...
		MultilayerWD.ID, MultilayerWD.getPropDefault(MultilayerWD.ID), ...
		MultilayerWD.LABEL, MultilayerWD.getPropDefault(MultilayerWD.LABEL), ...
		MultilayerWD.NOTES, MultilayerWD.getPropDefault(MultilayerWD.NOTES), ...
		MultilayerWD.TOSTRING, MultilayerWD.getNoValue(), ...
		MultilayerWD.GRAPH_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.CONNECTIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.DIRECTIONALITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.SELFCONNECTIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.NEGATIVITY_TYPE, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERTICKS, MultilayerWD.getPropDefault(MultilayerWD.LAYERTICKS), ...
		MultilayerWD.ALAYERTICKS, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERLABELS, MultilayerWD.getPropDefault(MultilayerWD.LAYERLABELS), ...
		MultilayerWD.ALAYERLABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONTICKS, MultilayerWD.getPropDefault(MultilayerWD.PARTITIONTICKS), ...
		MultilayerWD.APARTITIONTICKS, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONLABELS, MultilayerWD.getPropDefault(MultilayerWD.PARTITIONLABELS), ...
		MultilayerWD.APARTITIONLABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.NODELABELS, MultilayerWD.getPropDefault(MultilayerWD.NODELABELS), ...
		MultilayerWD.ANODELABELS, MultilayerWD.getNoValue(), ...
		MultilayerWD.RANDOMIZE, MultilayerWD.getPropDefault(MultilayerWD.RANDOMIZE), ...
		MultilayerWD.RANDOM_SEED, MultilayerWD.getPropDefault(MultilayerWD.RANDOM_SEED), ...
		MultilayerWD.A, MultilayerWD.getNoValue(), ...
		MultilayerWD.A_CHECK, MultilayerWD.getNoValue(), ...
		MultilayerWD.NODENUMBER, MultilayerWD.getNoValue(), ...
		MultilayerWD.LAYERNUMBER, MultilayerWD.getNoValue(), ...
		MultilayerWD.PARTITIONS, MultilayerWD.getNoValue(), ...
		MultilayerWD.M_DICT, MultilayerWD.getNoValue(), ...
		MultilayerWD.COMPATIBLE_MEASURES, MultilayerWD.getNoValue(), ...
		MultilayerWD.MEASURE, MultilayerWD.getNoValue(), ...
		MultilayerWD.PFGA, MultilayerWD.getPropDefault(MultilayerWD.PFGA), ...
		MultilayerWD.PFGH, MultilayerWD.getPropDefault(MultilayerWD.PFGH), ...
		MultilayerWD.B, MultilayerWD.getPropDefault(MultilayerWD.B), ...
		MultilayerWD.SEMIPOSITIVIZE_RULE, MultilayerWD.getPropDefault(MultilayerWD.SEMIPOSITIVIZE_RULE), ...
		MultilayerWD.STANDARDIZE_RULE, MultilayerWD.getPropDefault(MultilayerWD.STANDARDIZE_RULE), ...
		MultilayerWD.ATTEMPTSPEREDGE, MultilayerWD.getPropDefault(MultilayerWD.ATTEMPTSPEREDGE), ...
		MultilayerWD.NUMBEROFWEIGHTS, MultilayerWD.getPropDefault(MultilayerWD.NUMBEROFWEIGHTS), ...
		MultilayerWD.RANDOMIZATION, MultilayerWD.getNoValue() ...
		);
	 
	[json, struct, el_list] = encodeJSON(g);
	[g_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(g_dec ~= g, ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		'MultilayerWD.encodeJSON() or MultilayerWD.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) MultilayerWD.getPropFormat(prop), num2cell(MultilayerWD.getProps())) == Format.HANDLE) && all(cellfun(@(prop) MultilayerWD.getPropFormat(prop), num2cell(MultilayerWD.getProps())) == Format.NET)
		assert(isequal(g_dec, g), ...
			[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
			'MultilayerWD.encodeJSON() or MultilayerWD.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: Constructor - Full
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	B1 = rand(randi(10));
	B2 = rand(randi(10));
	B3 = rand(randi(10));
	B12 = rand(size(B1, 1),size(B2, 2));
	B13 = rand(size(B1, 1),size(B3, 2));
	B23 = rand(size(B2, 1),size(B3, 2));
	B21 = rand(size(B2, 1),size(B1, 2));
	B31 = rand(size(B3, 1),size(B1, 2));
	B32 = rand(size(B3, 1),size(B2, 2));
	B = {
	    B1                           B12                            B13
	    B21                          B2                             B23
	    B31                          B32                            B3
	    };
	g = MultilayerWD('B', B);
	g.get('A_CHECK')
	A1 = standardize(semipositivize(dediagonalize(B1)));
	A2 = standardize(semipositivize(dediagonalize(B2)));
	A3 = standardize(semipositivize(dediagonalize(B3)));
	A12 = standardize(semipositivize(B12));
	A13 = standardize(semipositivize(B13));
	A23 = standardize(semipositivize(B23));
	A21 = standardize(semipositivize(B21));
	A31 = standardize(semipositivize(B31));
	A32 = standardize(semipositivize(B32));
	B{1,1} = A1;
	B{2,2} = A2;
	B{3,3} = A3;
	B{1,2} = A12;
	B{1,3} = A13;
	B{2,3} = A23;
	B{2,1} = A21;
	B{3,1} = A31;
	B{3,2} = A32;
	A = B;
	assert(isequal(g.get('A'), A), ...
	    [BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
	    'MultilayerWD is not constructing well.')
	
	% %% ¡test!
	% %% ¡name!
	% Semipositivize Rule
	% %% ¡probability!
	% .01
	% %% ¡code!
end

%% Test 13: Randomize Rules
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	B1 = rand(randi(10));
	B2 = rand(randi(10));
	B3 = rand(randi(10));
	B12 = rand(size(B1, 1),size(B2, 2));
	B13 = rand(size(B1, 1),size(B3, 2));
	B23 = rand(size(B2, 1),size(B3, 2));
	B21 = rand(size(B2, 1),size(B1, 2));
	B31 = rand(size(B3, 1),size(B1, 2));
	B32 = rand(size(B3, 1),size(B2, 2));
	B = {
	    B1                           B12                            B13
	    B21                          B2                             B23
	    B31                          B32                            B3
	    };
	g = MultilayerWD('B', B);
	g.set('RANDOMIZE', true);
	g.set('ATTEMPTSPEREDGE', 4);
	g.get('A_CHECK')
	
	A = g.get('A');
	
	assert(isequal(size(A{1}), size(B{1})), ...
	    [BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
	    'MultilayerWD Randomize is not functioning well.')
	
	g2 = MultilayerWD('B', B);
	g2.set('RANDOMIZE', true);
	g2.set('ATTEMPTSPEREDGE', 4);
	g2.get('A_CHECK')
	A2 = g2.get('A');
	random_A = g2.get('RANDOMIZATION', A2);
	
	for i = 1:length(A2)
	    if all(A2{i, i}==0, "all") %if all nodes are zero, the random matrix is also all zeros
	        assert(isequal(A2{i, i}, random_A{i, i}), ...
	            [BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
	            'MultilayerWD Randomize is not functioning well.')
	    elseif isequal((length(A2{i, i}).^2)- length(A2{i, i}), sum(A2{i, i}==1, "all")) %if all nodes (except diagonal) are one, the random matrix is the same as original
	        assert(isequal(A2{i, i}, random_A{i, i}), ...
	            [BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
	            'MultilayerWD Randomize is not functioning well.')
	    else
	%         assert(~isequal(A2{i, i}, random_A{i, i}), ...
	%             [BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
	%             'MultilayerWD Randomize is not functioning well.')
	    end
	
	    assert(isequal(numel(find(A2{i, i})), numel(find(random_A{i, i}))), ... % check same number of nodes
	        [BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
	        'MultilayerWD Randomize is not functioning well.')
	end
end

%% Test 14: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':MultilayerWD:' BRAPH2.FAIL_TEST], ...
		[' When testing MultilayerWD no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 15: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

