%TEST_MULTILAYERWU

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	g = MultilayerWU();
	 
	% get('ELCLASS')
	if isa(MultilayerWU, 'ConcreteElement')
		assert(strcmp(MultilayerWU().get('ELCLASS'), 'MultilayerWU'), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'MultilayerWU().get(''ELCLASS'') should return ''MultilayerWU''.')
	end
	 
	% getBuild()
	assert(MultilayerWU.getBuild() == 1 && MultilayerWU.getBuild() > 0, ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'MultilayerWU.getBuild() should return the MultilayerWU build number.')
	assert(g.getBuild() == 1 && g.getBuild() > 0 , ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'g.getBuild() should return the MultilayerWU build number.')
	assert(Element.getBuild(g) == 1 && Element.getBuild(g) > 0, ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(g) should return the MultilayerWU build number.')
	assert(Element.getBuild('MultilayerWU') == 1 && Element.getBuild('MultilayerWU') > 0, ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''MultilayerWU'') should return the MultilayerWU build number.')
	 
	% getClass()
	assert(strcmp(MultilayerWU.getClass(), 'MultilayerWU'), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'MultilayerWU.getClass() should return ''MultilayerWU''.')
	assert(strcmp(g.getClass(), 'MultilayerWU'), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'g.getClass() should return ''MultilayerWU''.')
	assert(strcmp(Element.getClass(g), 'MultilayerWU'), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(g) should return ''MultilayerWU''.')
	assert(strcmp(Element.getClass('MultilayerWU'), 'MultilayerWU'), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''MultilayerWU'') should return ''MultilayerWU''.')
	 
	% getSubclasses()
	assert(isequal(MultilayerWU.getSubclasses(), subclasses('MultilayerWU', [], [], true)), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'MultilayerWU.getSubclasses() should return the same result as subclasses(''MultilayerWU'', [], [], true).')
	assert(isequal(g.getSubclasses(), subclasses('MultilayerWU', [], [], true)), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''MultilayerWU'', [], [], true).')
	assert(isequal(Element.getSubclasses(g), subclasses('MultilayerWU', [], [], true)), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(g) should return the same result as subclasses(''MultilayerWU'', [], [], true).')
	assert(isequal(Element.getSubclasses('MultilayerWU'), subclasses('MultilayerWU', [], [], true)), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''MultilayerWU'') should return the same result as subclasses(''MultilayerWU'', [], [], true).')
	 
	% getProps()
	assert(isempty(MultilayerWU.getProps()) || isequal(MultilayerWU.getProps(), 1:1:length(MultilayerWU.getProps())), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'MultilayerWU.getProps() should return a row vector [1:1:N].')
	assert(isempty(MultilayerWU.getProps()) || isequal(g.getProps(), 1:1:length(MultilayerWU.getProps())), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'g.getProps() should return a row vector [1:1:N].')
	assert(isempty(MultilayerWU.getProps()) || isequal(Element.getProps(g), 1:1:length(MultilayerWU.getProps())), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(g) should return a row vector [1:1:N].')
	assert(isempty(MultilayerWU.getProps()) || isequal(Element.getProps('MultilayerWU'), 1:1:length(MultilayerWU.getProps())), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''MultilayerWU'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) MultilayerWU.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(MultilayerWU.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(MultilayerWU.getProps())), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'MultilayerWU.getProps(category) does not work.')
	tmp = cellfun(@(category) g.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(MultilayerWU.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(MultilayerWU.getProps())), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'g.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(g, category), categories, 'UniformOutput', false);
	assert(isempty(MultilayerWU.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(MultilayerWU.getProps())), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(g, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('MultilayerWU', category), categories, 'UniformOutput', false);
	assert(isempty(MultilayerWU.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(MultilayerWU.getProps())), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''MultilayerWU'', category) does not work.')
	 
	% getPropNumber()
	assert(MultilayerWU.getPropNumber() == length(MultilayerWU.getProps()), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'MultilayerWU.getPropNumber() should return the number of properties.')
	assert(g.getPropNumber() == length(MultilayerWU.getProps()), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'g.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(g) == length(MultilayerWU.getProps()), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(g) should return the number of properties.')
	assert(Element.getPropNumber('MultilayerWU') == length(MultilayerWU.getProps()), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''MultilayerWU'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) MultilayerWU.getPropNumber(category), categories)) == MultilayerWU.getPropNumber(), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'MultilayerWU.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) g.getPropNumber(category), categories)) == MultilayerWU.getPropNumber(), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'g.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(g, category), categories)) == MultilayerWU.getPropNumber(), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(g, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('MultilayerWU', category), categories)) == MultilayerWU.getPropNumber(), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''MultilayerWU'', category) does not work.')
	 
	% existsProp(prop)
	assert(~MultilayerWU.existsProp(NaN), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'MultilayerWU.existsProp(prop) does not work.')
	assert(~g.existsProp(NaN), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'g.existsProp(prop) does not work.')
	assert(~Element.existsProp(g, NaN), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(g, prop) does not work.')
	assert(~Element.existsProp('MultilayerWU', NaN), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''MultilayerWU'', prop) does not work.')
	 
	assert_with_error('MultilayerWU.existsProp(NaN)', [BRAPH2.STR ':MultilayerWU:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':MultilayerWU:' BRAPH2.WRONG_INPUT], g)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':MultilayerWU:' BRAPH2.WRONG_INPUT], g)
	assert_with_error('Element.existsProp(''MultilayerWU'', NaN)', [BRAPH2.STR ':MultilayerWU:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:MultilayerWU.getPropNumber()
		assert(MultilayerWU.existsProp(prop), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'MultilayerWU.existsProp(prop) does not work.')
		assert(g.existsProp(prop), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'g.existsProp(prop) does not work.')
		assert(Element.existsProp(g, prop), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(g, prop) does not work.')
		assert(Element.existsProp('MultilayerWU', prop), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''MultilayerWU'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~MultilayerWU.existsTag(''), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'MultilayerWU.existsTag(tag) does not work.')
	assert(~g.existsTag(''), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'g.existsTag(tag) does not work.')
	assert(~Element.existsTag(g, ''), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(g, tag) does not work.')
	assert(~Element.existsTag('MultilayerWU', ''), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''MultilayerWU'', tag) does not work.')
	 
	assert_with_error('MultilayerWU.existsTag('''')', [BRAPH2.STR ':MultilayerWU:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':MultilayerWU:' BRAPH2.WRONG_INPUT], g)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':MultilayerWU:' BRAPH2.WRONG_INPUT], g)
	assert_with_error('Element.existsTag(''MultilayerWU'', '''')', [BRAPH2.STR ':MultilayerWU:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:MultilayerWU.getPropNumber()
		tag = g.getPropTag(prop);
		assert(MultilayerWU.existsTag(tag), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'MultilayerWU.existsTag(tag) does not work.')
		assert(g.existsTag(tag), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'g.existsTag(tag) does not work.')
		assert(Element.existsTag(g, tag), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(g, tga) does not work.')
		assert(Element.existsTag('MultilayerWU', tag), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''MultilayerWU'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:MultilayerWU.getPropNumber()
		assert(MultilayerWU.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'MultilayerWU.getPropProp(prop) does not work.')
		assert(g.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'g.getPropProp(prop) does not work.')
		assert(Element.getPropProp(g, prop) == prop, ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(g, prop) does not work.')
		assert(Element.getPropProp('MultilayerWU', prop) == prop, ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''MultilayerWU'', prop) does not work.')
	 
		tag = g.getPropTag(prop);
		assert(MultilayerWU.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'MultilayerWU.getPropProp(tag) does not work.')
		assert(g.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'g.getPropProp(tag) does not work.')
		assert(Element.getPropProp(g, tag) == prop, ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(g, tag) does not work.')
		assert(Element.getPropProp('MultilayerWU', prop) == prop, ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''MultilayerWU'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:MultilayerWU.getPropNumber()
		tag = g.getPropTag(prop);
	 
		assert(strcmp(MultilayerWU.getPropTag(prop), tag), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'MultilayerWU.getPropTag(prop) does not work.')
		assert(strcmp(g.getPropTag(prop), tag), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'g.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(g, prop), tag), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(g, prop) does not work.')
		assert(strcmp(Element.getPropTag('MultilayerWU', prop), tag), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''MultilayerWU'', prop) does not work.')
	 
		assert(strcmp(MultilayerWU.getPropTag(tag), tag), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'MultilayerWU.getPropTag(tag) does not work.')
		assert(strcmp(g.getPropTag(tag), tag), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'g.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(g, tag), tag), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(g, tag) does not work.')
		assert(strcmp(Element.getPropTag('MultilayerWU', prop), tag), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''MultilayerWU'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:MultilayerWU.getPropNumber()
		tag = g.getPropTag(prop);
	 
		assert(Category.existsCategory(MultilayerWU.getPropCategory(prop)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'MultilayerWU.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(g.getPropCategory(prop)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'g.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(g, prop)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(g, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(g, prop)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''MultilayerWU'', prop) does not work.')
	 
		assert(Category.existsCategory(MultilayerWU.getPropCategory(tag)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'MultilayerWU.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(g.getPropCategory(tag)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'g.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(g, tag)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(g, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(g, tag)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''MultilayerWU'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:MultilayerWU.getPropNumber()
		tag = g.getPropTag(prop);
	 
		assert(Format.existsFormat(MultilayerWU.getPropFormat(prop)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'MultilayerWU.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(g.getPropFormat(prop)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'g.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(g, prop)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(g, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(g, prop)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''MultilayerWU'', prop) does not work.')
	 
		assert(Format.existsFormat(MultilayerWU.getPropFormat(tag)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'MultilayerWU.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(g.getPropFormat(tag)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'g.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(g, tag)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(g, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(g, tag)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''MultilayerWU'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:MultilayerWU.getPropNumber()
		tag = g.getPropTag(prop);
	 
		assert(ischar(MultilayerWU.getPropDescription(prop)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'MultilayerWU.getPropDescription(prop) does not work.')
		assert(ischar(g.getPropDescription(prop)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'g.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(g, prop)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(g, prop) does not work.')
		assert(ischar(Element.getPropDescription(g, prop)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''MultilayerWU'', prop) does not work.')
	 
		assert(ischar(MultilayerWU.getPropDescription(tag)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'MultilayerWU.getPropDescription(tag) does not work.')
		assert(ischar(g.getPropDescription(tag)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'g.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(g, tag)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(g, tag) does not work.')
		assert(ischar(Element.getPropDescription(g, tag)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''MultilayerWU'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:MultilayerWU.getPropNumber()
		tag = g.getPropTag(prop);
	 
		settings = MultilayerWU.getPropSettings(prop);
		settings = g.getPropSettings(prop);
		settings = Element.getPropSettings(g, prop);
		settings = Element.getPropSettings('MultilayerWU', prop);
	 
		settings = MultilayerWU.getPropSettings(tag);
		settings = g.getPropSettings(tag);
		settings = Element.getPropSettings(g, tag);
		settings = Element.getPropSettings('MultilayerWU', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:MultilayerWU.getPropNumber()
		tag = g.getPropTag(prop);
	 
		default = MultilayerWU.getPropDefault(prop);
		default = g.getPropDefault(prop);
		default = Element.getPropDefault(g, prop);
		default = Element.getPropDefault('MultilayerWU', prop);
	 
		default = MultilayerWU.getPropDefault(tag);
		default = g.getPropDefault(tag);
		default = Element.getPropDefault(g, tag);
		default = Element.getPropDefault('MultilayerWU', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:MultilayerWU.getPropNumber()
		tag = g.getPropTag(prop);
	 
		conditioned_default = MultilayerWU.getPropDefaultConditioned(prop);
		conditioned_default = g.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(g, prop);
		conditioned_default = Element.getPropDefaultConditioned('MultilayerWU', prop);
	 
		conditioned_default = MultilayerWU.getPropDefaultConditioned(tag);
		conditioned_default = g.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(g, tag);
		conditioned_default = Element.getPropDefaultConditioned('MultilayerWU', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:MultilayerWU.getPropNumber()
		tag = g.getPropTag(prop);
	 
		assert(~MultilayerWU.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'MultilayerWU.checkProp(prop, value) does not work.')
		assert(~g.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'g.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(g, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(g, prop, value) does not work.')
		assert(~Element.checkProp('MultilayerWU', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''MultilayerWU'', prop, value) does not work.')
	 
		assert_with_error('MultilayerWU.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':MultilayerWU:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':MultilayerWU:' BRAPH2.WRONG_INPUT], prop, g)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':MultilayerWU:' BRAPH2.WRONG_INPUT], prop, g)
		assert_with_error('Element.checkProp(''MultilayerWU'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':MultilayerWU:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~MultilayerWU.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'MultilayerWU.checkProp(tag, value) does not work.')
		assert(~g.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'g.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(g, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(g, tag, value) does not work.')
		assert(~Element.checkProp('MultilayerWU', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''MultilayerWU'', tag, value) does not work.')
	 
		assert_with_error('MultilayerWU.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':MultilayerWU:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':MultilayerWU:' BRAPH2.WRONG_INPUT], tag, g)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':MultilayerWU:' BRAPH2.WRONG_INPUT], tag, g)
		assert_with_error('Element.checkProp(''MultilayerWU'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':MultilayerWU:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(MultilayerWU.checkProp(prop, Element.getPropDefaultConditioned(MultilayerWU, prop)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'MultilayerWU.checkProp(prop, <conditioned default value>) does not work.')
		assert(g.checkProp(prop, Element.getPropDefaultConditioned(MultilayerWU, prop)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'g.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(g, prop, Element.getPropDefaultConditioned(MultilayerWU, prop)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(g, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('MultilayerWU', prop, Element.getPropDefaultConditioned(MultilayerWU, prop)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''MultilayerWU'', prop, <conditioned default value>) does not work.')
	 
		assert(MultilayerWU.checkProp(tag, Element.getPropDefaultConditioned(MultilayerWU, prop)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'MultilayerWU.checkProp(tag, <conditioned default value>) does not work.')
		assert(g.checkProp(tag, Element.getPropDefaultConditioned(MultilayerWU, prop)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'g.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(g, tag, Element.getPropDefaultConditioned(MultilayerWU, prop)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(g, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('MultilayerWU', tag, Element.getPropDefaultConditioned(MultilayerWU, prop)), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''MultilayerWU'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	g = MultilayerWU( ...
		MultilayerWU.ELCLASS, MultilayerWU.getNoValue(), ...
		MultilayerWU.NAME, MultilayerWU.getNoValue(), ...
		MultilayerWU.DESCRIPTION, MultilayerWU.getNoValue(), ...
		MultilayerWU.TEMPLATE, MultilayerWU.getPropDefault(MultilayerWU.TEMPLATE), ...
		MultilayerWU.ID, MultilayerWU.getPropDefault(MultilayerWU.ID), ...
		MultilayerWU.LABEL, MultilayerWU.getPropDefault(MultilayerWU.LABEL), ...
		MultilayerWU.NOTES, MultilayerWU.getPropDefault(MultilayerWU.NOTES), ...
		MultilayerWU.TOSTRING, MultilayerWU.getNoValue(), ...
		MultilayerWU.GRAPH_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.CONNECTIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.DIRECTIONALITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.SELFCONNECTIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.NEGATIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERTICKS, MultilayerWU.getPropDefault(MultilayerWU.LAYERTICKS), ...
		MultilayerWU.ALAYERTICKS, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERLABELS, MultilayerWU.getPropDefault(MultilayerWU.LAYERLABELS), ...
		MultilayerWU.ALAYERLABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONTICKS, MultilayerWU.getPropDefault(MultilayerWU.PARTITIONTICKS), ...
		MultilayerWU.APARTITIONTICKS, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONLABELS, MultilayerWU.getPropDefault(MultilayerWU.PARTITIONLABELS), ...
		MultilayerWU.APARTITIONLABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.NODELABELS, MultilayerWU.getPropDefault(MultilayerWU.NODELABELS), ...
		MultilayerWU.ANODELABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.RANDOMIZE, MultilayerWU.getPropDefault(MultilayerWU.RANDOMIZE), ...
		MultilayerWU.RANDOM_SEED, MultilayerWU.getPropDefault(MultilayerWU.RANDOM_SEED), ...
		MultilayerWU.A, MultilayerWU.getNoValue(), ...
		MultilayerWU.A_CHECK, MultilayerWU.getNoValue(), ...
		MultilayerWU.NODENUMBER, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERNUMBER, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONS, MultilayerWU.getNoValue(), ...
		MultilayerWU.M_DICT, MultilayerWU.getNoValue(), ...
		MultilayerWU.COMPATIBLE_MEASURES, MultilayerWU.getNoValue(), ...
		MultilayerWU.MEASURE, MultilayerWU.getNoValue(), ...
		MultilayerWU.PFGA, MultilayerWU.getPropDefault(MultilayerWU.PFGA), ...
		MultilayerWU.PFGH, MultilayerWU.getPropDefault(MultilayerWU.PFGH), ...
		MultilayerWU.B, MultilayerWU.getPropDefault(MultilayerWU.B), ...
		MultilayerWU.SYMMETRIZE_RULE, MultilayerWU.getPropDefault(MultilayerWU.SYMMETRIZE_RULE), ...
		MultilayerWU.SEMIPOSITIVIZE_RULE, MultilayerWU.getPropDefault(MultilayerWU.SEMIPOSITIVIZE_RULE), ...
		MultilayerWU.STANDARDIZE_RULE, MultilayerWU.getPropDefault(MultilayerWU.STANDARDIZE_RULE), ...
		MultilayerWU.ATTEMPTSPEREDGE, MultilayerWU.getPropDefault(MultilayerWU.ATTEMPTSPEREDGE), ...
		MultilayerWU.NUMBEROFWEIGHTS, MultilayerWU.getPropDefault(MultilayerWU.NUMBEROFWEIGHTS), ...
		MultilayerWU.RANDOMIZATION, MultilayerWU.getNoValue() ...
		);
	 
	for prop = 1:1:MultilayerWU.getPropNumber()
	 
		% excluded props
		if any(prop == [MultilayerWU.PFGA MultilayerWU.PFGH])
			continue
		end
	 
		TAG = upper(MultilayerWU.getPropTag(prop));
		switch MultilayerWU.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					g.getr(prop) == MultilayerWU.getNoValue(), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['Being a ' MultilayerWU.getCategoryName(MultilayerWU.getPropCategory(prop)) ', MultilayerWU.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in MultilayerWU.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					g.getr(TAG) == MultilayerWU.getNoValue(), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['Being a ' MultilayerWU.getCategoryName(MultilayerWU.getPropCategory(prop)) ', MultilayerWU.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in MultilayerWU.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(g.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(g.getPropSettings(prop))
					assert( ...
						g.checkFormat(g.getPropFormat(prop), g.get(prop)), ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						['MultilayerWU.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						g.checkFormat(g.getPropFormat(prop), g.get(prop), g.getPropSettings(prop)), ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						['MultilayerWU.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					g.getr(prop) == MultilayerWU.getNoValue(), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['Being a ' MultilayerWU.getCategoryName(MultilayerWU.getPropCategory(prop)) ', MultilayerWU.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in MultilayerWU.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					g.getr(TAG) == MultilayerWU.getNoValue(), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['Being a ' MultilayerWU.getCategoryName(MultilayerWU.getPropCategory(prop)) ', MultilayerWU.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in MultilayerWU.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':MultilayerWU']);
				assert( ...
					~isa(g.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(g.getPropSettings(prop))
					assert( ...
						g.checkFormat(g.getPropFormat(prop), g.get(prop)), ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						['MultilayerWU.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						g.checkFormat(g.getPropFormat(prop), g.get(prop), g.getPropSettings(prop)), ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						['MultilayerWU.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(g.getr(prop), MultilayerWU.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by MultilayerWU.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in MultilayerWU.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(g.getr(TAG), MultilayerWU.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.getr(' TAG ') must be inizialized to its default value ' ...
					'given by MultilayerWU.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in MultilayerWU.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	g = MultilayerWU( ...
		MultilayerWU.ELCLASS, MultilayerWU.getNoValue(), ...
		MultilayerWU.NAME, MultilayerWU.getNoValue(), ...
		MultilayerWU.DESCRIPTION, MultilayerWU.getNoValue(), ...
		MultilayerWU.TEMPLATE, MultilayerWU.getPropDefault(MultilayerWU.TEMPLATE), ...
		MultilayerWU.ID, MultilayerWU.getPropDefault(MultilayerWU.ID), ...
		MultilayerWU.LABEL, MultilayerWU.getPropDefault(MultilayerWU.LABEL), ...
		MultilayerWU.NOTES, MultilayerWU.getPropDefault(MultilayerWU.NOTES), ...
		MultilayerWU.TOSTRING, MultilayerWU.getNoValue(), ...
		MultilayerWU.GRAPH_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.CONNECTIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.DIRECTIONALITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.SELFCONNECTIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.NEGATIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERTICKS, MultilayerWU.getPropDefault(MultilayerWU.LAYERTICKS), ...
		MultilayerWU.ALAYERTICKS, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERLABELS, MultilayerWU.getPropDefault(MultilayerWU.LAYERLABELS), ...
		MultilayerWU.ALAYERLABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONTICKS, MultilayerWU.getPropDefault(MultilayerWU.PARTITIONTICKS), ...
		MultilayerWU.APARTITIONTICKS, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONLABELS, MultilayerWU.getPropDefault(MultilayerWU.PARTITIONLABELS), ...
		MultilayerWU.APARTITIONLABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.NODELABELS, MultilayerWU.getPropDefault(MultilayerWU.NODELABELS), ...
		MultilayerWU.ANODELABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.RANDOMIZE, MultilayerWU.getPropDefault(MultilayerWU.RANDOMIZE), ...
		MultilayerWU.RANDOM_SEED, MultilayerWU.getPropDefault(MultilayerWU.RANDOM_SEED), ...
		MultilayerWU.A, MultilayerWU.getNoValue(), ...
		MultilayerWU.A_CHECK, MultilayerWU.getNoValue(), ...
		MultilayerWU.NODENUMBER, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERNUMBER, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONS, MultilayerWU.getNoValue(), ...
		MultilayerWU.M_DICT, MultilayerWU.getNoValue(), ...
		MultilayerWU.COMPATIBLE_MEASURES, MultilayerWU.getNoValue(), ...
		MultilayerWU.MEASURE, MultilayerWU.getNoValue(), ...
		MultilayerWU.PFGA, MultilayerWU.getPropDefault(MultilayerWU.PFGA), ...
		MultilayerWU.PFGH, MultilayerWU.getPropDefault(MultilayerWU.PFGH), ...
		MultilayerWU.B, MultilayerWU.getPropDefault(MultilayerWU.B), ...
		MultilayerWU.SYMMETRIZE_RULE, MultilayerWU.getPropDefault(MultilayerWU.SYMMETRIZE_RULE), ...
		MultilayerWU.SEMIPOSITIVIZE_RULE, MultilayerWU.getPropDefault(MultilayerWU.SEMIPOSITIVIZE_RULE), ...
		MultilayerWU.STANDARDIZE_RULE, MultilayerWU.getPropDefault(MultilayerWU.STANDARDIZE_RULE), ...
		MultilayerWU.ATTEMPTSPEREDGE, MultilayerWU.getPropDefault(MultilayerWU.ATTEMPTSPEREDGE), ...
		MultilayerWU.NUMBEROFWEIGHTS, MultilayerWU.getPropDefault(MultilayerWU.NUMBEROFWEIGHTS), ...
		MultilayerWU.RANDOMIZATION, MultilayerWU.getNoValue() ...
		);
	 
	for prop = 1:1:MultilayerWU.getPropNumber()
	 
		% excluded props
		if any(prop == [MultilayerWU.PFGA MultilayerWU.PFGH])
			continue
		end
	 
		TAG = upper(MultilayerWU.getPropTag(prop));
		switch MultilayerWU.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(g.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(g.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(g.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(g.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					g.checkFormat(g.getPropFormat(prop), g.getr(prop),g.getPropSettings(prop)), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':MultilayerWU']);
				assert( ...
					~isa(g.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(g.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':MultilayerWU']);
	% 			assert( ...
	% 				~isa(g.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
	% 				['MultilayerWU.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(g.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
	% 				['MultilayerWU.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				g.checkFormat(g.getPropFormat(prop), g.getr(prop),g.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
	% 				['MultilayerWU.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':MultilayerWU']);
				assert( ...
					~isa(g.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(g.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(g.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(g.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					g.checkFormat(g.getPropFormat(prop), g.getr(prop),g.getPropSettings(prop)), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if g.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:MultilayerWU');
					delete(ancestor(g.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(MultilayerWU.getProps(Category.RESULT))
		for prop = 1:1:MultilayerWU.getPropNumber()
	 
			% excluded props
			if any(prop == [MultilayerWU.PFGA MultilayerWU.PFGH])
				continue
			end
	 
			switch MultilayerWU.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						g.isLocked(prop), ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						['MultilayerWU.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~g.isLocked(prop), ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						['MultilayerWU.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	g = MultilayerWU();
	 
	for prop = 1:1:MultilayerWU.getPropNumber()
		TAG = upper(MultilayerWU.getPropTag(prop));
		assert( ...
			~g.isLocked(prop), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			['MultilayerWU.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~g.isLocked(TAG), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			['MultilayerWU.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	g.lock()
	 
	for prop = 1:1:MultilayerWU.getPropNumber()
		switch MultilayerWU.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					g.isLocked(prop), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~g.isLocked(prop), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	g = MultilayerWU();
	 
	warning_backup = warning('off', 'BRAPH2:MultilayerWU');
	for prop = 1:1:MultilayerWU.getPropNumber()
		g.lock(prop)
		switch MultilayerWU.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					g.isLocked(prop), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~g.isLocked(prop), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	g = MultilayerWU();
	 
	for prop = 1:1:MultilayerWU.getPropNumber()
		TAG = upper(MultilayerWU.getPropTag(prop));
		assert( ...
			g.isChecked(prop), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			['MultilayerWU.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			g.isChecked(TAG), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			['MultilayerWU.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	g.unchecked()
	 
	for prop = 1:1:MultilayerWU.getPropNumber()
		assert( ...
			~g.isChecked(prop), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			['MultilayerWU.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	g.checked()
	 
	for prop = 1:1:MultilayerWU.getPropNumber()
		assert( ...
			g.isChecked(prop), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			['MultilayerWU.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic MultilayerWU
	g_0 = MultilayerWU( ...
		MultilayerWU.ELCLASS, MultilayerWU.getNoValue(), ...
		MultilayerWU.NAME, MultilayerWU.getNoValue(), ...
		MultilayerWU.DESCRIPTION, MultilayerWU.getNoValue(), ...
		MultilayerWU.TEMPLATE, MultilayerWU.getPropDefault(MultilayerWU.TEMPLATE), ...
		MultilayerWU.ID, MultilayerWU.getPropDefault(MultilayerWU.ID), ...
		MultilayerWU.LABEL, MultilayerWU.getPropDefault(MultilayerWU.LABEL), ...
		MultilayerWU.NOTES, MultilayerWU.getPropDefault(MultilayerWU.NOTES), ...
		MultilayerWU.TOSTRING, MultilayerWU.getNoValue(), ...
		MultilayerWU.GRAPH_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.CONNECTIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.DIRECTIONALITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.SELFCONNECTIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.NEGATIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERTICKS, MultilayerWU.getPropDefault(MultilayerWU.LAYERTICKS), ...
		MultilayerWU.ALAYERTICKS, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERLABELS, MultilayerWU.getPropDefault(MultilayerWU.LAYERLABELS), ...
		MultilayerWU.ALAYERLABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONTICKS, MultilayerWU.getPropDefault(MultilayerWU.PARTITIONTICKS), ...
		MultilayerWU.APARTITIONTICKS, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONLABELS, MultilayerWU.getPropDefault(MultilayerWU.PARTITIONLABELS), ...
		MultilayerWU.APARTITIONLABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.NODELABELS, MultilayerWU.getPropDefault(MultilayerWU.NODELABELS), ...
		MultilayerWU.ANODELABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.RANDOMIZE, MultilayerWU.getPropDefault(MultilayerWU.RANDOMIZE), ...
		MultilayerWU.RANDOM_SEED, MultilayerWU.getPropDefault(MultilayerWU.RANDOM_SEED), ...
		MultilayerWU.A, MultilayerWU.getNoValue(), ...
		MultilayerWU.A_CHECK, MultilayerWU.getNoValue(), ...
		MultilayerWU.NODENUMBER, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERNUMBER, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONS, MultilayerWU.getNoValue(), ...
		MultilayerWU.M_DICT, MultilayerWU.getNoValue(), ...
		MultilayerWU.COMPATIBLE_MEASURES, MultilayerWU.getNoValue(), ...
		MultilayerWU.MEASURE, MultilayerWU.getNoValue(), ...
		MultilayerWU.PFGA, MultilayerWU.getPropDefault(MultilayerWU.PFGA), ...
		MultilayerWU.PFGH, MultilayerWU.getPropDefault(MultilayerWU.PFGH), ...
		MultilayerWU.B, MultilayerWU.getPropDefault(MultilayerWU.B), ...
		MultilayerWU.SYMMETRIZE_RULE, MultilayerWU.getPropDefault(MultilayerWU.SYMMETRIZE_RULE), ...
		MultilayerWU.SEMIPOSITIVIZE_RULE, MultilayerWU.getPropDefault(MultilayerWU.SEMIPOSITIVIZE_RULE), ...
		MultilayerWU.STANDARDIZE_RULE, MultilayerWU.getPropDefault(MultilayerWU.STANDARDIZE_RULE), ...
		MultilayerWU.ATTEMPTSPEREDGE, MultilayerWU.getPropDefault(MultilayerWU.ATTEMPTSPEREDGE), ...
		MultilayerWU.NUMBEROFWEIGHTS, MultilayerWU.getPropDefault(MultilayerWU.NUMBEROFWEIGHTS), ...
		MultilayerWU.RANDOMIZATION, MultilayerWU.getNoValue() ...
		);
	 
	% MultilayerWU with 1st callbacks
	g_1 = MultilayerWU( ...
		MultilayerWU.ELCLASS, MultilayerWU.getNoValue(), ...
		MultilayerWU.NAME, MultilayerWU.getNoValue(), ...
		MultilayerWU.DESCRIPTION, MultilayerWU.getNoValue(), ...
		MultilayerWU.TEMPLATE, g_0.getCallback(4), ..., ...
		MultilayerWU.ID, g_0.getCallback(5), ..., ...
		MultilayerWU.LABEL, MultilayerWU.getPropDefault(MultilayerWU.LABEL), ...
		MultilayerWU.NOTES, MultilayerWU.getPropDefault(MultilayerWU.NOTES), ...
		MultilayerWU.TOSTRING, MultilayerWU.getNoValue(), ...
		MultilayerWU.GRAPH_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.CONNECTIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.DIRECTIONALITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.SELFCONNECTIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.NEGATIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERTICKS, MultilayerWU.getPropDefault(MultilayerWU.LAYERTICKS), ...
		MultilayerWU.ALAYERTICKS, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERLABELS, MultilayerWU.getPropDefault(MultilayerWU.LAYERLABELS), ...
		MultilayerWU.ALAYERLABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONTICKS, MultilayerWU.getPropDefault(MultilayerWU.PARTITIONTICKS), ...
		MultilayerWU.APARTITIONTICKS, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONLABELS, MultilayerWU.getPropDefault(MultilayerWU.PARTITIONLABELS), ...
		MultilayerWU.APARTITIONLABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.NODELABELS, MultilayerWU.getPropDefault(MultilayerWU.NODELABELS), ...
		MultilayerWU.ANODELABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.RANDOMIZE, g_0.getCallback(24), ..., ...
		MultilayerWU.RANDOM_SEED, g_0.getCallback(25), ..., ...
		MultilayerWU.A, MultilayerWU.getNoValue(), ...
		MultilayerWU.A_CHECK, MultilayerWU.getNoValue(), ...
		MultilayerWU.NODENUMBER, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERNUMBER, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONS, MultilayerWU.getNoValue(), ...
		MultilayerWU.M_DICT, MultilayerWU.getNoValue(), ...
		MultilayerWU.COMPATIBLE_MEASURES, MultilayerWU.getNoValue(), ...
		MultilayerWU.MEASURE, MultilayerWU.getNoValue(), ...
		MultilayerWU.PFGA, g_0.getCallback(34), ..., ...
		MultilayerWU.PFGH, g_0.getCallback(35), ..., ...
		MultilayerWU.B, g_0.getCallback(36), ..., ...
		MultilayerWU.SYMMETRIZE_RULE, g_0.getCallback(37), ..., ...
		MultilayerWU.SEMIPOSITIVIZE_RULE, g_0.getCallback(38), ..., ...
		MultilayerWU.STANDARDIZE_RULE, g_0.getCallback(39), ..., ...
		MultilayerWU.ATTEMPTSPEREDGE, g_0.getCallback(40), ..., ...
		MultilayerWU.NUMBEROFWEIGHTS, g_0.getCallback(41), ..., ...
		MultilayerWU.RANDOMIZATION, MultilayerWU.getNoValue() ...
		);
	 
	prop_number = MultilayerWU.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(MultilayerWU.getPropTag(prop));
		switch MultilayerWU.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(g_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(g_1.get(prop), g_0.get(prop)) && ~isa(g_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(g_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% MultilayerWU with 2nd callbacks
	g_2 = MultilayerWU( ...
		MultilayerWU.ELCLASS, MultilayerWU.getNoValue(), ...
		MultilayerWU.NAME, MultilayerWU.getNoValue(), ...
		MultilayerWU.DESCRIPTION, MultilayerWU.getNoValue(), ...
		MultilayerWU.TEMPLATE, g_1.getCallback(4), ..., ...
		MultilayerWU.ID, g_1.getCallback(5), ..., ...
		MultilayerWU.LABEL, MultilayerWU.getPropDefault(MultilayerWU.LABEL), ...
		MultilayerWU.NOTES, MultilayerWU.getPropDefault(MultilayerWU.NOTES), ...
		MultilayerWU.TOSTRING, MultilayerWU.getNoValue(), ...
		MultilayerWU.GRAPH_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.CONNECTIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.DIRECTIONALITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.SELFCONNECTIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.NEGATIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERTICKS, MultilayerWU.getPropDefault(MultilayerWU.LAYERTICKS), ...
		MultilayerWU.ALAYERTICKS, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERLABELS, MultilayerWU.getPropDefault(MultilayerWU.LAYERLABELS), ...
		MultilayerWU.ALAYERLABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONTICKS, MultilayerWU.getPropDefault(MultilayerWU.PARTITIONTICKS), ...
		MultilayerWU.APARTITIONTICKS, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONLABELS, MultilayerWU.getPropDefault(MultilayerWU.PARTITIONLABELS), ...
		MultilayerWU.APARTITIONLABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.NODELABELS, MultilayerWU.getPropDefault(MultilayerWU.NODELABELS), ...
		MultilayerWU.ANODELABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.RANDOMIZE, g_1.getCallback(24), ..., ...
		MultilayerWU.RANDOM_SEED, g_1.getCallback(25), ..., ...
		MultilayerWU.A, MultilayerWU.getNoValue(), ...
		MultilayerWU.A_CHECK, MultilayerWU.getNoValue(), ...
		MultilayerWU.NODENUMBER, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERNUMBER, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONS, MultilayerWU.getNoValue(), ...
		MultilayerWU.M_DICT, MultilayerWU.getNoValue(), ...
		MultilayerWU.COMPATIBLE_MEASURES, MultilayerWU.getNoValue(), ...
		MultilayerWU.MEASURE, MultilayerWU.getNoValue(), ...
		MultilayerWU.PFGA, g_1.getCallback(34), ..., ...
		MultilayerWU.PFGH, g_1.getCallback(35), ..., ...
		MultilayerWU.B, g_1.getCallback(36), ..., ...
		MultilayerWU.SYMMETRIZE_RULE, g_1.getCallback(37), ..., ...
		MultilayerWU.SEMIPOSITIVIZE_RULE, g_1.getCallback(38), ..., ...
		MultilayerWU.STANDARDIZE_RULE, g_1.getCallback(39), ..., ...
		MultilayerWU.ATTEMPTSPEREDGE, g_1.getCallback(40), ..., ...
		MultilayerWU.NUMBEROFWEIGHTS, g_1.getCallback(41), ..., ...
		MultilayerWU.RANDOMIZATION, MultilayerWU.getNoValue() ...
		);
	 
	prop_number = MultilayerWU.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(MultilayerWU.getPropTag(prop));
		switch MultilayerWU.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(g_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(g_2.get(prop), g_0.get(prop)) && ~isa(g_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(g_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% MultilayerWU with 3rd callbacks
	g_3 = MultilayerWU( ...
		MultilayerWU.ELCLASS, MultilayerWU.getNoValue(), ...
		MultilayerWU.NAME, MultilayerWU.getNoValue(), ...
		MultilayerWU.DESCRIPTION, MultilayerWU.getNoValue(), ...
		MultilayerWU.TEMPLATE, g_2.getCallback(4), ..., ...
		MultilayerWU.ID, g_2.getCallback(5), ..., ...
		MultilayerWU.LABEL, MultilayerWU.getPropDefault(MultilayerWU.LABEL), ...
		MultilayerWU.NOTES, MultilayerWU.getPropDefault(MultilayerWU.NOTES), ...
		MultilayerWU.TOSTRING, MultilayerWU.getNoValue(), ...
		MultilayerWU.GRAPH_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.CONNECTIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.DIRECTIONALITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.SELFCONNECTIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.NEGATIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERTICKS, MultilayerWU.getPropDefault(MultilayerWU.LAYERTICKS), ...
		MultilayerWU.ALAYERTICKS, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERLABELS, MultilayerWU.getPropDefault(MultilayerWU.LAYERLABELS), ...
		MultilayerWU.ALAYERLABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONTICKS, MultilayerWU.getPropDefault(MultilayerWU.PARTITIONTICKS), ...
		MultilayerWU.APARTITIONTICKS, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONLABELS, MultilayerWU.getPropDefault(MultilayerWU.PARTITIONLABELS), ...
		MultilayerWU.APARTITIONLABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.NODELABELS, MultilayerWU.getPropDefault(MultilayerWU.NODELABELS), ...
		MultilayerWU.ANODELABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.RANDOMIZE, g_2.getCallback(24), ..., ...
		MultilayerWU.RANDOM_SEED, g_2.getCallback(25), ..., ...
		MultilayerWU.A, MultilayerWU.getNoValue(), ...
		MultilayerWU.A_CHECK, MultilayerWU.getNoValue(), ...
		MultilayerWU.NODENUMBER, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERNUMBER, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONS, MultilayerWU.getNoValue(), ...
		MultilayerWU.M_DICT, MultilayerWU.getNoValue(), ...
		MultilayerWU.COMPATIBLE_MEASURES, MultilayerWU.getNoValue(), ...
		MultilayerWU.MEASURE, MultilayerWU.getNoValue(), ...
		MultilayerWU.PFGA, g_2.getCallback(34), ..., ...
		MultilayerWU.PFGH, g_2.getCallback(35), ..., ...
		MultilayerWU.B, g_2.getCallback(36), ..., ...
		MultilayerWU.SYMMETRIZE_RULE, g_2.getCallback(37), ..., ...
		MultilayerWU.SEMIPOSITIVIZE_RULE, g_2.getCallback(38), ..., ...
		MultilayerWU.STANDARDIZE_RULE, g_2.getCallback(39), ..., ...
		MultilayerWU.ATTEMPTSPEREDGE, g_2.getCallback(40), ..., ...
		MultilayerWU.NUMBEROFWEIGHTS, g_2.getCallback(41), ..., ...
		MultilayerWU.RANDOMIZATION, MultilayerWU.getNoValue() ...
		);
	 
	prop_number = MultilayerWU.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(MultilayerWU.getPropTag(prop));
		switch MultilayerWU.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(g_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(g_3.get(prop), g_0.get(prop)) && ~isa(g_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(g_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	g = MultilayerWU();
	 
	g_copy = g.copy();
	 
	assert(g_copy ~= g, ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'MultilayerWU.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(g_copy, g), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'MultilayerWU.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:MultilayerWU.getPropNumber()
		value = g.getr(prop);
		value_copy = g_copy.getr(prop);
		switch MultilayerWU.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					'MultilayerWU.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						'MultilayerWU.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						'MultilayerWU.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						'MultilayerWU.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
							'MultilayerWU.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
							'MultilayerWU.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						'MultilayerWU.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					g_copy.isLocked(prop) == g.isLocked(prop), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					'MultilayerWU.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					g_copy.isChecked(prop) == g.isChecked(prop), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					'MultilayerWU.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					g_copy.getPropSeed(prop) == g.getPropSeed(prop), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					'MultilayerWU.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	g = MultilayerWU( ...
		MultilayerWU.ELCLASS, MultilayerWU.getNoValue(), ...
		MultilayerWU.NAME, MultilayerWU.getNoValue(), ...
		MultilayerWU.DESCRIPTION, MultilayerWU.getNoValue(), ...
		MultilayerWU.TEMPLATE, MultilayerWU.getPropDefault(MultilayerWU.TEMPLATE), ...
		MultilayerWU.ID, MultilayerWU.getPropDefault(MultilayerWU.ID), ...
		MultilayerWU.LABEL, MultilayerWU.getPropDefault(MultilayerWU.LABEL), ...
		MultilayerWU.NOTES, MultilayerWU.getPropDefault(MultilayerWU.NOTES), ...
		MultilayerWU.TOSTRING, MultilayerWU.getNoValue(), ...
		MultilayerWU.GRAPH_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.CONNECTIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.DIRECTIONALITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.SELFCONNECTIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.NEGATIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERTICKS, MultilayerWU.getPropDefault(MultilayerWU.LAYERTICKS), ...
		MultilayerWU.ALAYERTICKS, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERLABELS, MultilayerWU.getPropDefault(MultilayerWU.LAYERLABELS), ...
		MultilayerWU.ALAYERLABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONTICKS, MultilayerWU.getPropDefault(MultilayerWU.PARTITIONTICKS), ...
		MultilayerWU.APARTITIONTICKS, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONLABELS, MultilayerWU.getPropDefault(MultilayerWU.PARTITIONLABELS), ...
		MultilayerWU.APARTITIONLABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.NODELABELS, MultilayerWU.getPropDefault(MultilayerWU.NODELABELS), ...
		MultilayerWU.ANODELABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.RANDOMIZE, MultilayerWU.getPropDefault(MultilayerWU.RANDOMIZE), ...
		MultilayerWU.RANDOM_SEED, MultilayerWU.getPropDefault(MultilayerWU.RANDOM_SEED), ...
		MultilayerWU.A, MultilayerWU.getNoValue(), ...
		MultilayerWU.A_CHECK, MultilayerWU.getNoValue(), ...
		MultilayerWU.NODENUMBER, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERNUMBER, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONS, MultilayerWU.getNoValue(), ...
		MultilayerWU.M_DICT, MultilayerWU.getNoValue(), ...
		MultilayerWU.COMPATIBLE_MEASURES, MultilayerWU.getNoValue(), ...
		MultilayerWU.MEASURE, MultilayerWU.getNoValue(), ...
		MultilayerWU.PFGA, MultilayerWU.getPropDefault(MultilayerWU.PFGA), ...
		MultilayerWU.PFGH, MultilayerWU.getPropDefault(MultilayerWU.PFGH), ...
		MultilayerWU.B, MultilayerWU.getPropDefault(MultilayerWU.B), ...
		MultilayerWU.SYMMETRIZE_RULE, MultilayerWU.getPropDefault(MultilayerWU.SYMMETRIZE_RULE), ...
		MultilayerWU.SEMIPOSITIVIZE_RULE, MultilayerWU.getPropDefault(MultilayerWU.SEMIPOSITIVIZE_RULE), ...
		MultilayerWU.STANDARDIZE_RULE, MultilayerWU.getPropDefault(MultilayerWU.STANDARDIZE_RULE), ...
		MultilayerWU.ATTEMPTSPEREDGE, MultilayerWU.getPropDefault(MultilayerWU.ATTEMPTSPEREDGE), ...
		MultilayerWU.NUMBEROFWEIGHTS, MultilayerWU.getPropDefault(MultilayerWU.NUMBEROFWEIGHTS), ...
		MultilayerWU.RANDOMIZATION, MultilayerWU.getNoValue() ...
		);
	 
	for prop = 1:1:MultilayerWU.getPropNumber()
		if MultilayerWU.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':MultilayerWU']);
			% g.memorize(prop);
			% warning(warning_backup)
		elseif MultilayerWU.getPropCategory(prop) == Category.EVANESCENT && g.getPropFormat(prop) == Format.HANDLE
			g.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:MultilayerWU');
			delete(ancestor(g.get(prop), 'figure'))
			warning(warning_backup)
		else
			g.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	g_copy = g.copy();
	 
	for prop = 1:1:MultilayerWU.getPropNumber()
		value = g.getr(prop);
		value_copy = g_copy.getr(prop);
		switch MultilayerWU.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					'MultilayerWU.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						'MultilayerWU.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						'MultilayerWU.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						'MultilayerWU.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
							'MultilayerWU.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
							'MultilayerWU.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						'MultilayerWU.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						g_copy.isLocked(prop) == g.isLocked(prop), ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						'MultilayerWU.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						g_copy.isChecked(prop) == g.isChecked(prop), ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						'MultilayerWU.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						g_copy.getPropSeed(prop) == g.getPropSeed(prop), ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						'MultilayerWU.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	g_0 = MultilayerWU( ...
		MultilayerWU.ELCLASS, MultilayerWU.getNoValue(), ...
		MultilayerWU.NAME, MultilayerWU.getNoValue(), ...
		MultilayerWU.DESCRIPTION, MultilayerWU.getNoValue(), ...
		MultilayerWU.TEMPLATE, MultilayerWU.getPropDefault(MultilayerWU.TEMPLATE), ...
		MultilayerWU.ID, MultilayerWU.getPropDefault(MultilayerWU.ID), ...
		MultilayerWU.LABEL, MultilayerWU.getPropDefault(MultilayerWU.LABEL), ...
		MultilayerWU.NOTES, MultilayerWU.getPropDefault(MultilayerWU.NOTES), ...
		MultilayerWU.TOSTRING, MultilayerWU.getNoValue(), ...
		MultilayerWU.GRAPH_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.CONNECTIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.DIRECTIONALITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.SELFCONNECTIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.NEGATIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERTICKS, MultilayerWU.getPropDefault(MultilayerWU.LAYERTICKS), ...
		MultilayerWU.ALAYERTICKS, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERLABELS, MultilayerWU.getPropDefault(MultilayerWU.LAYERLABELS), ...
		MultilayerWU.ALAYERLABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONTICKS, MultilayerWU.getPropDefault(MultilayerWU.PARTITIONTICKS), ...
		MultilayerWU.APARTITIONTICKS, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONLABELS, MultilayerWU.getPropDefault(MultilayerWU.PARTITIONLABELS), ...
		MultilayerWU.APARTITIONLABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.NODELABELS, MultilayerWU.getPropDefault(MultilayerWU.NODELABELS), ...
		MultilayerWU.ANODELABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.RANDOMIZE, MultilayerWU.getPropDefault(MultilayerWU.RANDOMIZE), ...
		MultilayerWU.RANDOM_SEED, MultilayerWU.getPropDefault(MultilayerWU.RANDOM_SEED), ...
		MultilayerWU.A, MultilayerWU.getNoValue(), ...
		MultilayerWU.A_CHECK, MultilayerWU.getNoValue(), ...
		MultilayerWU.NODENUMBER, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERNUMBER, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONS, MultilayerWU.getNoValue(), ...
		MultilayerWU.M_DICT, MultilayerWU.getNoValue(), ...
		MultilayerWU.COMPATIBLE_MEASURES, MultilayerWU.getNoValue(), ...
		MultilayerWU.MEASURE, MultilayerWU.getNoValue(), ...
		MultilayerWU.PFGA, MultilayerWU.getPropDefault(MultilayerWU.PFGA), ...
		MultilayerWU.PFGH, MultilayerWU.getPropDefault(MultilayerWU.PFGH), ...
		MultilayerWU.B, MultilayerWU.getPropDefault(MultilayerWU.B), ...
		MultilayerWU.SYMMETRIZE_RULE, MultilayerWU.getPropDefault(MultilayerWU.SYMMETRIZE_RULE), ...
		MultilayerWU.SEMIPOSITIVIZE_RULE, MultilayerWU.getPropDefault(MultilayerWU.SEMIPOSITIVIZE_RULE), ...
		MultilayerWU.STANDARDIZE_RULE, MultilayerWU.getPropDefault(MultilayerWU.STANDARDIZE_RULE), ...
		MultilayerWU.ATTEMPTSPEREDGE, MultilayerWU.getPropDefault(MultilayerWU.ATTEMPTSPEREDGE), ...
		MultilayerWU.NUMBEROFWEIGHTS, MultilayerWU.getPropDefault(MultilayerWU.NUMBEROFWEIGHTS), ...
		MultilayerWU.RANDOMIZATION, MultilayerWU.getNoValue() ...
		);
	 
	g = MultilayerWU( ...
		MultilayerWU.ELCLASS, MultilayerWU.getNoValue(), ...
		MultilayerWU.NAME, MultilayerWU.getNoValue(), ...
		MultilayerWU.DESCRIPTION, MultilayerWU.getNoValue(), ...
		MultilayerWU.TEMPLATE, g_0.getCallback(4), ..., ...
		MultilayerWU.ID, g_0.getCallback(5), ..., ...
		MultilayerWU.LABEL, MultilayerWU.getPropDefault(MultilayerWU.LABEL), ...
		MultilayerWU.NOTES, MultilayerWU.getPropDefault(MultilayerWU.NOTES), ...
		MultilayerWU.TOSTRING, MultilayerWU.getNoValue(), ...
		MultilayerWU.GRAPH_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.CONNECTIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.DIRECTIONALITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.SELFCONNECTIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.NEGATIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERTICKS, MultilayerWU.getPropDefault(MultilayerWU.LAYERTICKS), ...
		MultilayerWU.ALAYERTICKS, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERLABELS, MultilayerWU.getPropDefault(MultilayerWU.LAYERLABELS), ...
		MultilayerWU.ALAYERLABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONTICKS, MultilayerWU.getPropDefault(MultilayerWU.PARTITIONTICKS), ...
		MultilayerWU.APARTITIONTICKS, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONLABELS, MultilayerWU.getPropDefault(MultilayerWU.PARTITIONLABELS), ...
		MultilayerWU.APARTITIONLABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.NODELABELS, MultilayerWU.getPropDefault(MultilayerWU.NODELABELS), ...
		MultilayerWU.ANODELABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.RANDOMIZE, g_0.getCallback(24), ..., ...
		MultilayerWU.RANDOM_SEED, g_0.getCallback(25), ..., ...
		MultilayerWU.A, MultilayerWU.getNoValue(), ...
		MultilayerWU.A_CHECK, MultilayerWU.getNoValue(), ...
		MultilayerWU.NODENUMBER, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERNUMBER, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONS, MultilayerWU.getNoValue(), ...
		MultilayerWU.M_DICT, MultilayerWU.getNoValue(), ...
		MultilayerWU.COMPATIBLE_MEASURES, MultilayerWU.getNoValue(), ...
		MultilayerWU.MEASURE, MultilayerWU.getNoValue(), ...
		MultilayerWU.PFGA, g_0.getCallback(34), ..., ...
		MultilayerWU.PFGH, g_0.getCallback(35), ..., ...
		MultilayerWU.B, g_0.getCallback(36), ..., ...
		MultilayerWU.SYMMETRIZE_RULE, g_0.getCallback(37), ..., ...
		MultilayerWU.SEMIPOSITIVIZE_RULE, g_0.getCallback(38), ..., ...
		MultilayerWU.STANDARDIZE_RULE, g_0.getCallback(39), ..., ...
		MultilayerWU.ATTEMPTSPEREDGE, g_0.getCallback(40), ..., ...
		MultilayerWU.NUMBEROFWEIGHTS, g_0.getCallback(41), ..., ...
		MultilayerWU.RANDOMIZATION, MultilayerWU.getNoValue() ...
		);
	 
	g_copy = g.copy();
	g_0_copy = g_copy.getr('ID').get('EL');
	 
	for prop = 1:1:MultilayerWU.getPropNumber()
		value = g.getr(prop);
		value_copy = g_copy.getr(prop);
		switch MultilayerWU.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					'MultilayerWU.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						'MultilayerWU.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						'MultilayerWU.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						'MultilayerWU.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
							'MultilayerWU.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
							'MultilayerWU.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						'MultilayerWU.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == g_0.getCallback(prop), ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						'MultilayerWU.copy() does not work. The callback should be obtained from MultilayerWU.getCallback().' ...
						)
					assert( ...
						value_copy == g_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						'MultilayerWU.copy() does not work. The callback should be obtained from MultilayerWU.getCallback().' ...
						)
				end
	 
					assert( ...
						g_copy.isLocked(prop) == g.isLocked(prop), ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						'MultilayerWU.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						g_copy.isChecked(prop) == g.isChecked(prop), ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						'MultilayerWU.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						g_copy.getPropSeed(prop) == g.getPropSeed(prop), ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						'MultilayerWU.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	g_template = MultilayerWU();
	g = MultilayerWU('TEMPLATE', g_template);
	 
	for prop = 1:1:MultilayerWU.getPropNumber()
	 
		% excluded props
		if any(prop == [MultilayerWU.PFGA MultilayerWU.PFGH])
			continue
		end
	 
		TAG = upper(MultilayerWU.getPropTag(prop));
		switch MultilayerWU.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == MultilayerWU.TEMPLATE
					assert( ...
						isa(g.getr(prop), 'MultilayerWU'), ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						'MultilayerWU TEMPLATE does not work. MultilayerWU.getr(''TEMPLATE'') should be a MultilayerWU element.' ...
						)
					assert( ...
						isa(g_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						'MultilayerWU TEMPLATE does not work. MultilayerWU_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(g.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						['MultilayerWU TEMPLATE does not work. MultilayerWU.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						g.getr(prop).get('EL') == g_template && g.getr(prop).get('PROP') == prop && strcmp(g.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						['MultilayerWU TEMPLATE does not work. MultilayerWU.getr(' TAG ') should be a Callback to g_template.' TAG '.'] ...
						)
					assert( ...
						isa(g_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
						['MultilayerWU TEMPLATE does not work. MultilayerWU_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(g.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU TEMPLATE does not work. MultilayerWU.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(g_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
					['MultilayerWU TEMPLATE does not work. MultilayerWU_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	g = MultilayerWU( ...
		MultilayerWU.ELCLASS, MultilayerWU.getNoValue(), ...
		MultilayerWU.NAME, MultilayerWU.getNoValue(), ...
		MultilayerWU.DESCRIPTION, MultilayerWU.getNoValue(), ...
		MultilayerWU.TEMPLATE, MultilayerWU.getPropDefault(MultilayerWU.TEMPLATE), ...
		MultilayerWU.ID, MultilayerWU.getPropDefault(MultilayerWU.ID), ...
		MultilayerWU.LABEL, MultilayerWU.getPropDefault(MultilayerWU.LABEL), ...
		MultilayerWU.NOTES, MultilayerWU.getPropDefault(MultilayerWU.NOTES), ...
		MultilayerWU.TOSTRING, MultilayerWU.getNoValue(), ...
		MultilayerWU.GRAPH_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.CONNECTIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.DIRECTIONALITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.SELFCONNECTIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.NEGATIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERTICKS, MultilayerWU.getPropDefault(MultilayerWU.LAYERTICKS), ...
		MultilayerWU.ALAYERTICKS, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERLABELS, MultilayerWU.getPropDefault(MultilayerWU.LAYERLABELS), ...
		MultilayerWU.ALAYERLABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONTICKS, MultilayerWU.getPropDefault(MultilayerWU.PARTITIONTICKS), ...
		MultilayerWU.APARTITIONTICKS, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONLABELS, MultilayerWU.getPropDefault(MultilayerWU.PARTITIONLABELS), ...
		MultilayerWU.APARTITIONLABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.NODELABELS, MultilayerWU.getPropDefault(MultilayerWU.NODELABELS), ...
		MultilayerWU.ANODELABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.RANDOMIZE, MultilayerWU.getPropDefault(MultilayerWU.RANDOMIZE), ...
		MultilayerWU.RANDOM_SEED, MultilayerWU.getPropDefault(MultilayerWU.RANDOM_SEED), ...
		MultilayerWU.A, MultilayerWU.getNoValue(), ...
		MultilayerWU.A_CHECK, MultilayerWU.getNoValue(), ...
		MultilayerWU.NODENUMBER, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERNUMBER, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONS, MultilayerWU.getNoValue(), ...
		MultilayerWU.M_DICT, MultilayerWU.getNoValue(), ...
		MultilayerWU.COMPATIBLE_MEASURES, MultilayerWU.getNoValue(), ...
		MultilayerWU.MEASURE, MultilayerWU.getNoValue(), ...
		MultilayerWU.PFGA, MultilayerWU.getPropDefault(MultilayerWU.PFGA), ...
		MultilayerWU.PFGH, MultilayerWU.getPropDefault(MultilayerWU.PFGH), ...
		MultilayerWU.B, MultilayerWU.getPropDefault(MultilayerWU.B), ...
		MultilayerWU.SYMMETRIZE_RULE, MultilayerWU.getPropDefault(MultilayerWU.SYMMETRIZE_RULE), ...
		MultilayerWU.SEMIPOSITIVIZE_RULE, MultilayerWU.getPropDefault(MultilayerWU.SEMIPOSITIVIZE_RULE), ...
		MultilayerWU.STANDARDIZE_RULE, MultilayerWU.getPropDefault(MultilayerWU.STANDARDIZE_RULE), ...
		MultilayerWU.ATTEMPTSPEREDGE, MultilayerWU.getPropDefault(MultilayerWU.ATTEMPTSPEREDGE), ...
		MultilayerWU.NUMBEROFWEIGHTS, MultilayerWU.getPropDefault(MultilayerWU.NUMBEROFWEIGHTS), ...
		MultilayerWU.RANDOMIZATION, MultilayerWU.getNoValue() ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'multilayerwu_to_be_erased.b2'];
	 
	Element.save(g, filename)
	 
	g_loaded = Element.load(filename);
	 
	assert( ...
		isequal(g.copy(), g_loaded), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'MultilayerWU.save(g) and/or MultilayerWU.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	g = MultilayerWU( ...
		MultilayerWU.ELCLASS, MultilayerWU.getNoValue(), ...
		MultilayerWU.NAME, MultilayerWU.getNoValue(), ...
		MultilayerWU.DESCRIPTION, MultilayerWU.getNoValue(), ...
		MultilayerWU.TEMPLATE, MultilayerWU.getPropDefault(MultilayerWU.TEMPLATE), ...
		MultilayerWU.ID, MultilayerWU.getPropDefault(MultilayerWU.ID), ...
		MultilayerWU.LABEL, MultilayerWU.getPropDefault(MultilayerWU.LABEL), ...
		MultilayerWU.NOTES, MultilayerWU.getPropDefault(MultilayerWU.NOTES), ...
		MultilayerWU.TOSTRING, MultilayerWU.getNoValue(), ...
		MultilayerWU.GRAPH_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.CONNECTIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.DIRECTIONALITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.SELFCONNECTIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.NEGATIVITY_TYPE, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERTICKS, MultilayerWU.getPropDefault(MultilayerWU.LAYERTICKS), ...
		MultilayerWU.ALAYERTICKS, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERLABELS, MultilayerWU.getPropDefault(MultilayerWU.LAYERLABELS), ...
		MultilayerWU.ALAYERLABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONTICKS, MultilayerWU.getPropDefault(MultilayerWU.PARTITIONTICKS), ...
		MultilayerWU.APARTITIONTICKS, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONLABELS, MultilayerWU.getPropDefault(MultilayerWU.PARTITIONLABELS), ...
		MultilayerWU.APARTITIONLABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.NODELABELS, MultilayerWU.getPropDefault(MultilayerWU.NODELABELS), ...
		MultilayerWU.ANODELABELS, MultilayerWU.getNoValue(), ...
		MultilayerWU.RANDOMIZE, MultilayerWU.getPropDefault(MultilayerWU.RANDOMIZE), ...
		MultilayerWU.RANDOM_SEED, MultilayerWU.getPropDefault(MultilayerWU.RANDOM_SEED), ...
		MultilayerWU.A, MultilayerWU.getNoValue(), ...
		MultilayerWU.A_CHECK, MultilayerWU.getNoValue(), ...
		MultilayerWU.NODENUMBER, MultilayerWU.getNoValue(), ...
		MultilayerWU.LAYERNUMBER, MultilayerWU.getNoValue(), ...
		MultilayerWU.PARTITIONS, MultilayerWU.getNoValue(), ...
		MultilayerWU.M_DICT, MultilayerWU.getNoValue(), ...
		MultilayerWU.COMPATIBLE_MEASURES, MultilayerWU.getNoValue(), ...
		MultilayerWU.MEASURE, MultilayerWU.getNoValue(), ...
		MultilayerWU.PFGA, MultilayerWU.getPropDefault(MultilayerWU.PFGA), ...
		MultilayerWU.PFGH, MultilayerWU.getPropDefault(MultilayerWU.PFGH), ...
		MultilayerWU.B, MultilayerWU.getPropDefault(MultilayerWU.B), ...
		MultilayerWU.SYMMETRIZE_RULE, MultilayerWU.getPropDefault(MultilayerWU.SYMMETRIZE_RULE), ...
		MultilayerWU.SEMIPOSITIVIZE_RULE, MultilayerWU.getPropDefault(MultilayerWU.SEMIPOSITIVIZE_RULE), ...
		MultilayerWU.STANDARDIZE_RULE, MultilayerWU.getPropDefault(MultilayerWU.STANDARDIZE_RULE), ...
		MultilayerWU.ATTEMPTSPEREDGE, MultilayerWU.getPropDefault(MultilayerWU.ATTEMPTSPEREDGE), ...
		MultilayerWU.NUMBEROFWEIGHTS, MultilayerWU.getPropDefault(MultilayerWU.NUMBEROFWEIGHTS), ...
		MultilayerWU.RANDOMIZATION, MultilayerWU.getNoValue() ...
		);
	 
	[json, struct, el_list] = encodeJSON(g);
	[g_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(g_dec ~= g, ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		'MultilayerWU.encodeJSON() or MultilayerWU.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) MultilayerWU.getPropFormat(prop), num2cell(MultilayerWU.getProps())) == Format.HANDLE) && all(cellfun(@(prop) MultilayerWU.getPropFormat(prop), num2cell(MultilayerWU.getProps())) == Format.NET)
		assert(isequal(g_dec, g), ...
			[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
			'MultilayerWU.encodeJSON() or MultilayerWU.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: Constructor - Full
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	B1 = rand(randi(10));
	B2 = rand(randi(10));
	B3 = rand(randi(10));
	B12 = rand(size(B1,1),size(B2,2));
	B13 = rand(size(B1,1),size(B3,2));
	B23 = rand(size(B2,1),size(B3,2));
	B = {
	    B1                           B12                            B13
	    B12'                         B2                             B23
	    B13'                         B23'                           B3
	    };
	g = MultilayerWU('B', B);
	g.get('A_CHECK')
	A1 = symmetrize(standardize(semipositivize(dediagonalize(B1))));
	A2 = symmetrize(standardize(semipositivize(dediagonalize(B2))));
	A3 = symmetrize(standardize(semipositivize(dediagonalize(B3))));
	A12 =  standardize(semipositivize(B12));
	A13 =  standardize(semipositivize(B13));
	A23 =  standardize(semipositivize(B23));
	B{1, 1} = A1;
	B{2, 2} = A2;
	B{3, 3} = A3;
	B{1, 2} = A12;
	B{1, 3} = A13;
	B{2, 3} = A23;
	B{2, 1} = A12';
	B{3, 1} = A13';
	B{3, 2} = A23';
	A = B;
	assert(isequal(g.get('A'), A), ...
	    [BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
	    'MultilayerWU is not constructing well.')
end

%% Test 13: Randomize Rules
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	B1 = rand(randi(10));
	B2 = rand(randi(10));
	B3 = rand(randi(10));
	B12 = rand(size(B1,1),size(B2,2));
	B13 = rand(size(B1,1),size(B3,2));
	B23 = rand(size(B2,1),size(B3,2));
	B = {
	    B1                           B12                            B13
	    B12'                         B2                             B23
	    B13'                         B23'                           B3
	    };
	g = MultilayerWU('B', B);
	g.set('RANDOMIZE', true);
	g.set('ATTEMPTSPEREDGE', 4);
	g.get('A_CHECK')
	A = g.get('A');
	
	assert(isequal(size(A{1}), size(B{1})), ...
	    [BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
	    'MultilayerBUD Randomize is not functioning well.')
	
	g2 = MultilayerWU('B', B);
	g2.set('RANDOMIZE', false);
	g2.set('ATTEMPTSPEREDGE', 4);
	g2.get('A_CHECK')
	A2 = g.get('A');
	random_A = g2.get('RANDOMIZATION', A2);
	
	for i = 1:length(A2)
	    if all(A2{i, i}==0, "all") %if all nodes are zero, the random matrix is also all zeros
	        assert(isequal(A2{i, i}, random_A{i, i}), ...
	            [BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
	            'MultilayerWU Randomize is not functioning well.')
	    elseif isequal((length(A2{i, i}).^2)- length(A2{i, i}), sum(A2{i, i}==1, "all")) %if all nodes (except diagonal) are one, the random matrix is the same as original
	        assert(isequal(A2{i, i}, random_A{i, i}), ...
	            [BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
	            'MultilayerWU Randomize is not functioning well.')
	    else
	%         assert(~isequal(A2{i, i}, random_A{i, i}), ...
	%             [BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
	%             'MultilayerWU Randomize is not functioning well.')
	    end
	    
	    assert(isequal(numel(find(A2{i, i})), numel(find(random_A{i, i}))), ... % check same number of nodes
	        [BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
	        'MultilayerWU Randomize is not functioning well.')
	
	    assert(issymmetric(random_A{i, i}), ... % check symmetry 
	    [BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
	    'MultilayerWU Randomize is not functioning well.')
	end
end

%% Test 14: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':MultilayerWU:' BRAPH2.FAIL_TEST], ...
		[' When testing MultilayerWU no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 15: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

