f = uifigure();

c1 = uicheckbox( ...
    'Parent', f, ...
    'Units', 'normalized', ...
    'Position', [0 .5 .2 .1], ...
    'Text', 'w', ...    
    'ValueChangedFcn', {@cb_checkbox_w} ...
    );

c1 = uicheckbox( ...
    'Parent', f, ...
    'Units', 'normalized', ...
    'Position', [.51 .5 .2 .1], ...
    'Text', 'b', ...    
    'ValueChangedFcn', {@cb_checkbox_b} ...
    );

function cb_checkbox_w(~, ~)
    set(c2, 'Value', 0)
    final()
end

function cb_checkbox_b(~,~)
    set(c1, 'Value', 0)
    final()
end
