%EXAMPLE_CON_ST
% Script example workflow ST CON

clear variables %#ok<*NASGU>

%% Load BrainAtlas
im_ba = ImporterBrainAtlasXLS('FILE', [fileparts(which('example_CON_WU')) filesep 'example data CON (DTI)' filesep 'desikan_atlas.xlsx']);

ba = im_ba.get('BA');

%% Load Groups of SubjectCON
im_gr1 = ImporterGroupSubjectCONXLS( ...
    'DIRECTORY', [fileparts(which('example_CON_WU')) filesep 'example data CON (DTI)' filesep 'xls' filesep 'GroupName1'], ...
    'BA', ba ...
    );

gr1 = im_gr1.get('GR');

im_gr2 = ImporterGroupSubjectCONXLS( ...
    'DIRECTORY', [fileparts(which('example_CON_WU')) filesep 'example data CON (DTI)' filesep 'xls' filesep 'GroupName2'], ...
    'BA', ba ...
    );

gr2 = im_gr2.get('GR');

%% Analysis CON WU
a_WU1 = AnalyzeEnsemble_CON_WU( ...
    'GR', gr1 ...
    );

a_WU2 = AnalyzeEnsemble_CON_WU( ...
    'GR', gr2 ...
    );

% measure calculation
degree_WU1 = a_WU1.getMeasureEnsemble('Degree').get('M');
degree_av_WU1 = a_WU1.getMeasureEnsemble('DegreeAv').get('M');
distance_WU1 = a_WU1.getMeasureEnsemble('Distance').get('M');

degree_WU1 = a_WU2.getMeasureEnsemble('Degree').get('M');
degree_av_WU1 = a_WU2.getMeasureEnsemble('DegreeAv').get('M');
distance_WU1 = a_WU2.getMeasureEnsemble('Distance').get('M');

% % comparison
% c_WU = Comparison( ...
%     'P', 10, ...
%     'A1', a_WU1, ...
%     'A2', a_WU2 ...
%     );
% 
% [degree_WU_p1, degree_WU_p2, degree_WU_ci_lower, degree_WU_ci_upper, ...
%     degree_WU_m1, degree_WU_m2, degree_WU_diff, ...
%     degree_WU_m1_perms, degree_WU_m2_perms, degree_WU_diff_perms] = c_WU.getComparison('DegreeEnsemble', 'verbose', true);
% [degree_av_WU_p1, degree_av_WU_p2, degree_av_WU_ci_lower, degree_av_WU_ci_upper, ...
%     degree_av_WU_m1, degree_av_WU_m2, degree_av_WU_diff, ...
%     degree_av_WU_m1_perms, degree_av_WU_m2_perms, degree_av_WU_diff_perms] = c_WU.getComparison('DegreeAvEnsemble', 'verbose', true);
% [distance_WU_p1, distance_WU_p2, distance_WU_ci_lower, distance_WU_ci_upper, ...
%     distance_WU_m1, distance_WU_m2, distance_WU_diff, ...
%     distance_WU_m1_perms, distance_WU_m2_perms, distance_WU_diff_perms] = c_WU.getComparison('DistanceEnsemble', 'verbose', true);