%TEST_PLOTBRAINATLAS

%% Test 1.1: Instantiation - empty

pl = PlotBrainAtlas();

prop_number = PlotBrainAtlas.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(PlotBrainAtlas.getPropTag(prop));
	assert( ...
		isa(pl.getr(prop), 'NoValue'), ...
		[BRAPH2.STR ':PlotBrainAtlas:' BRAPH2.BUG_FUNC], ...
		['PlotBrainAtlas.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
		'Or there could be an error in PlotBrainAtlas.getr(' int2str(prop) ').'] ...
		)
	assert( ...
		isa(pl.getr(TAG), 'NoValue'), ...
		[BRAPH2.STR ':PlotBrainAtlas:' BRAPH2.BUG_FUNC], ...
		['PlotBrainAtlas.getr(''' TAG ''') must be inizialized to NoValue(). ' ...
		'Or there could be an error in PlotBrainAtlas.getr(''' TAG ''').'] ...
		)
end

%% Test 1.2: Instantiation - defaults

warning('off', 'BRAPH2:PlotBrainAtlas')
pl = PlotBrainAtlas( ...
	PlotBrainAtlas.ID, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.ID), ...
	PlotBrainAtlas.BKGCOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.BKGCOLOR), ...
	PlotBrainAtlas.SURF, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SURF), ...
	PlotBrainAtlas.AXESCOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.AXESCOLOR), ...
	PlotBrainAtlas.VIEW, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.VIEW), ...
	PlotBrainAtlas.HOLD, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.HOLD), ...
	PlotBrainAtlas.GRID, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.GRID), ...
	PlotBrainAtlas.AXIS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.AXIS), ...
	PlotBrainAtlas.EQUAL, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.EQUAL), ...
	PlotBrainAtlas.TIGHT, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.TIGHT), ...
	PlotBrainAtlas.BRAIN, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.BRAIN), ...
	PlotBrainAtlas.EDGECOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.EDGECOLOR), ...
	PlotBrainAtlas.EDGEALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.EDGEALPHA), ...
	PlotBrainAtlas.FACECOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.FACECOLOR), ...
	PlotBrainAtlas.FACEALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.FACEALPHA), ...
	PlotBrainAtlas.LIGHTING, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LIGHTING), ...
	PlotBrainAtlas.MATERIAL, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.MATERIAL), ...
	PlotBrainAtlas.CAMLIGHT, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.CAMLIGHT), ...
	PlotBrainAtlas.SHADING, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SHADING), ...
	PlotBrainAtlas.COLORMAP, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.COLORMAP), ...
	PlotBrainAtlas.COLORMAPSTRING, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.COLORMAPSTRING), ...
	PlotBrainAtlas.ATLAS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.ATLAS), ...
	PlotBrainAtlas.PARENT, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.PARENT), ...
	PlotBrainAtlas.SYMS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS), ...
	PlotBrainAtlas.SYMS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_SIZE), ...
	PlotBrainAtlas.SYMS_MARKER, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_MARKER), ...
	PlotBrainAtlas.SYMS_FACE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_FACE_COLOR), ...
	PlotBrainAtlas.SYMS_EDGE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_EDGE_COLOR), ...
	PlotBrainAtlas.SPHS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS), ...
	PlotBrainAtlas.SPHS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_SIZE), ...
	PlotBrainAtlas.SPHS_EDGE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_EDGE_COLOR), ...
	PlotBrainAtlas.SPHS_FACE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_FACE_COLOR), ...
	PlotBrainAtlas.SPHS_EDGE_ALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_EDGE_ALPHA), ...
	PlotBrainAtlas.SPHS_FACE_ALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_FACE_ALPHA), ...
	PlotBrainAtlas.IDS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS), ...
	PlotBrainAtlas.IDS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_SIZE), ...
	PlotBrainAtlas.IDS_FONT_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_FONT_COLOR), ...
	PlotBrainAtlas.IDS_FONT_NAME, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_FONT_NAME), ...
	PlotBrainAtlas.IDS_FONT_INTERPRETER, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_FONT_INTERPRETER), ...
	PlotBrainAtlas.LABS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS), ...
	PlotBrainAtlas.LABS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_SIZE), ...
	PlotBrainAtlas.LABS_FONT_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_FONT_COLOR), ...
	PlotBrainAtlas.LABS_FONT_NAME, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_FONT_NAME), ...
	PlotBrainAtlas.LABS_FONT_INTERPRETER, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_FONT_INTERPRETER) ...
	);
warning('on', 'BRAPH2:PlotBrainAtlas')

for prop = 1:1:PlotBrainAtlas.getPropNumber()
	TAG = upper(PlotBrainAtlas.getPropTag(prop));
	switch PlotBrainAtlas.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isequal(pl.getr(prop), PlotBrainAtlas.getPropDefaultConditioned(prop)), ...
				[BRAPH2.STR ':PlotBrainAtlas:' BRAPH2.BUG_FUNC], ...
				['PlotBrainAtlas.getr(' int2str(prop) ') must be inizialized to its default value ' ...
				'given by PlotBrainAtlas.getPropDefaultConditioned(' int2str(prop) '). ' ...
				'Or there could be an error in PlotBrainAtlas.getr(' int2str(prop) ').'] ...
				)
			assert( ...
				isequal(pl.getr(TAG), PlotBrainAtlas.getPropDefaultConditioned(prop)), ...
				[BRAPH2.STR ':PlotBrainAtlas:' BRAPH2.BUG_FUNC], ...
				['PlotBrainAtlas.getr(''' TAG ''') must be inizialized to its default value ' ...
				'given by PlotBrainAtlas.getPropDefaultConditioned(' int2str(prop) '). ' ...
				'Or there could be an error in PlotBrainAtlas.getr(''' TAG ''').'] ...
				)
		case Category.RESULT
			assert( ...
				isa(pl.getr(prop), 'NoValue'), ...
				[BRAPH2.STR ':PlotBrainAtlas:' BRAPH2.BUG_FUNC], ...
				['Being a result, PlotBrainAtlas.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
				'Or there could be an error in PlotBrainAtlas.getr(' int2str(prop) ').'] ...
				)
			assert( ...
				isa(pl.getr(TAG), 'NoValue'), ...
				[BRAPH2.STR ':PlotBrainAtlas:' BRAPH2.BUG_FUNC], ...
				['Being a result, PlotBrainAtlas.getr(''' TAG ''') must be inizialized to NoValue(). ' ...
				'Or there could be an error in PlotBrainAtlas.getr(''' TAG ''').'] ...
				)
	end
end

%% Test 2: Callbacks

warning('off', 'BRAPH2:PlotBrainAtlas')
pl_0 = PlotBrainAtlas( ...
	PlotBrainAtlas.ID, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.ID), ...
	PlotBrainAtlas.BKGCOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.BKGCOLOR), ...
	PlotBrainAtlas.SURF, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SURF), ...
	PlotBrainAtlas.AXESCOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.AXESCOLOR), ...
	PlotBrainAtlas.VIEW, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.VIEW), ...
	PlotBrainAtlas.HOLD, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.HOLD), ...
	PlotBrainAtlas.GRID, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.GRID), ...
	PlotBrainAtlas.AXIS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.AXIS), ...
	PlotBrainAtlas.EQUAL, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.EQUAL), ...
	PlotBrainAtlas.TIGHT, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.TIGHT), ...
	PlotBrainAtlas.BRAIN, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.BRAIN), ...
	PlotBrainAtlas.EDGECOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.EDGECOLOR), ...
	PlotBrainAtlas.EDGEALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.EDGEALPHA), ...
	PlotBrainAtlas.FACECOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.FACECOLOR), ...
	PlotBrainAtlas.FACEALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.FACEALPHA), ...
	PlotBrainAtlas.LIGHTING, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LIGHTING), ...
	PlotBrainAtlas.MATERIAL, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.MATERIAL), ...
	PlotBrainAtlas.CAMLIGHT, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.CAMLIGHT), ...
	PlotBrainAtlas.SHADING, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SHADING), ...
	PlotBrainAtlas.COLORMAP, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.COLORMAP), ...
	PlotBrainAtlas.COLORMAPSTRING, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.COLORMAPSTRING), ...
	PlotBrainAtlas.ATLAS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.ATLAS), ...
	PlotBrainAtlas.PARENT, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.PARENT), ...
	PlotBrainAtlas.SYMS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS), ...
	PlotBrainAtlas.SYMS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_SIZE), ...
	PlotBrainAtlas.SYMS_MARKER, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_MARKER), ...
	PlotBrainAtlas.SYMS_FACE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_FACE_COLOR), ...
	PlotBrainAtlas.SYMS_EDGE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_EDGE_COLOR), ...
	PlotBrainAtlas.SPHS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS), ...
	PlotBrainAtlas.SPHS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_SIZE), ...
	PlotBrainAtlas.SPHS_EDGE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_EDGE_COLOR), ...
	PlotBrainAtlas.SPHS_FACE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_FACE_COLOR), ...
	PlotBrainAtlas.SPHS_EDGE_ALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_EDGE_ALPHA), ...
	PlotBrainAtlas.SPHS_FACE_ALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_FACE_ALPHA), ...
	PlotBrainAtlas.IDS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS), ...
	PlotBrainAtlas.IDS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_SIZE), ...
	PlotBrainAtlas.IDS_FONT_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_FONT_COLOR), ...
	PlotBrainAtlas.IDS_FONT_NAME, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_FONT_NAME), ...
	PlotBrainAtlas.IDS_FONT_INTERPRETER, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_FONT_INTERPRETER), ...
	PlotBrainAtlas.LABS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS), ...
	PlotBrainAtlas.LABS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_SIZE), ...
	PlotBrainAtlas.LABS_FONT_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_FONT_COLOR), ...
	PlotBrainAtlas.LABS_FONT_NAME, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_FONT_NAME), ...
	PlotBrainAtlas.LABS_FONT_INTERPRETER, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_FONT_INTERPRETER) ...
	);
warning('on', 'BRAPH2:PlotBrainAtlas')

pl_1 = PlotBrainAtlas( ...
	PlotBrainAtlas.ID, Callback('EL', pl_0, 'PROP', 1), ...
	PlotBrainAtlas.BKGCOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.BKGCOLOR), ...
	PlotBrainAtlas.SURF, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SURF), ...
	PlotBrainAtlas.AXESCOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.AXESCOLOR), ...
	PlotBrainAtlas.VIEW, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.VIEW), ...
	PlotBrainAtlas.HOLD, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.HOLD), ...
	PlotBrainAtlas.GRID, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.GRID), ...
	PlotBrainAtlas.AXIS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.AXIS), ...
	PlotBrainAtlas.EQUAL, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.EQUAL), ...
	PlotBrainAtlas.TIGHT, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.TIGHT), ...
	PlotBrainAtlas.BRAIN, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.BRAIN), ...
	PlotBrainAtlas.EDGECOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.EDGECOLOR), ...
	PlotBrainAtlas.EDGEALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.EDGEALPHA), ...
	PlotBrainAtlas.FACECOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.FACECOLOR), ...
	PlotBrainAtlas.FACEALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.FACEALPHA), ...
	PlotBrainAtlas.LIGHTING, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LIGHTING), ...
	PlotBrainAtlas.MATERIAL, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.MATERIAL), ...
	PlotBrainAtlas.CAMLIGHT, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.CAMLIGHT), ...
	PlotBrainAtlas.SHADING, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SHADING), ...
	PlotBrainAtlas.COLORMAP, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.COLORMAP), ...
	PlotBrainAtlas.COLORMAPSTRING, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.COLORMAPSTRING), ...
	PlotBrainAtlas.ATLAS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.ATLAS), ...
	PlotBrainAtlas.PARENT, Callback('EL', pl_0, 'PROP', 23), ...
	PlotBrainAtlas.SYMS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS), ...
	PlotBrainAtlas.SYMS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_SIZE), ...
	PlotBrainAtlas.SYMS_MARKER, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_MARKER), ...
	PlotBrainAtlas.SYMS_FACE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_FACE_COLOR), ...
	PlotBrainAtlas.SYMS_EDGE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_EDGE_COLOR), ...
	PlotBrainAtlas.SPHS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS), ...
	PlotBrainAtlas.SPHS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_SIZE), ...
	PlotBrainAtlas.SPHS_EDGE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_EDGE_COLOR), ...
	PlotBrainAtlas.SPHS_FACE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_FACE_COLOR), ...
	PlotBrainAtlas.SPHS_EDGE_ALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_EDGE_ALPHA), ...
	PlotBrainAtlas.SPHS_FACE_ALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_FACE_ALPHA), ...
	PlotBrainAtlas.IDS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS), ...
	PlotBrainAtlas.IDS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_SIZE), ...
	PlotBrainAtlas.IDS_FONT_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_FONT_COLOR), ...
	PlotBrainAtlas.IDS_FONT_NAME, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_FONT_NAME), ...
	PlotBrainAtlas.IDS_FONT_INTERPRETER, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_FONT_INTERPRETER), ...
	PlotBrainAtlas.LABS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS), ...
	PlotBrainAtlas.LABS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_SIZE), ...
	PlotBrainAtlas.LABS_FONT_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_FONT_COLOR), ...
	PlotBrainAtlas.LABS_FONT_NAME, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_FONT_NAME), ...
	PlotBrainAtlas.LABS_FONT_INTERPRETER, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_FONT_INTERPRETER) ...
	);
	
prop_number = PlotBrainAtlas.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(PlotBrainAtlas.getPropTag(prop));
	switch PlotBrainAtlas.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(pl_1.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':PlotBrainAtlas:' BRAPH2.BUG_FUNC], ...
				['PlotBrainAtlas.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(pl_1.get(prop), pl_0.get(prop)) && ~isa(pl_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':PlotBrainAtlas:' BRAPH2.BUG_FUNC], ...
				['PlotBrainAtlas.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(pl_1.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':PlotBrainAtlas:' BRAPH2.BUG_FUNC], ...
				['PlotBrainAtlas.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end
pl_2 = PlotBrainAtlas( ...
	PlotBrainAtlas.ID, Callback('EL', pl_1, 'PROP', 1), ...
	PlotBrainAtlas.BKGCOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.BKGCOLOR), ...
	PlotBrainAtlas.SURF, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SURF), ...
	PlotBrainAtlas.AXESCOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.AXESCOLOR), ...
	PlotBrainAtlas.VIEW, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.VIEW), ...
	PlotBrainAtlas.HOLD, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.HOLD), ...
	PlotBrainAtlas.GRID, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.GRID), ...
	PlotBrainAtlas.AXIS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.AXIS), ...
	PlotBrainAtlas.EQUAL, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.EQUAL), ...
	PlotBrainAtlas.TIGHT, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.TIGHT), ...
	PlotBrainAtlas.BRAIN, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.BRAIN), ...
	PlotBrainAtlas.EDGECOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.EDGECOLOR), ...
	PlotBrainAtlas.EDGEALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.EDGEALPHA), ...
	PlotBrainAtlas.FACECOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.FACECOLOR), ...
	PlotBrainAtlas.FACEALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.FACEALPHA), ...
	PlotBrainAtlas.LIGHTING, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LIGHTING), ...
	PlotBrainAtlas.MATERIAL, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.MATERIAL), ...
	PlotBrainAtlas.CAMLIGHT, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.CAMLIGHT), ...
	PlotBrainAtlas.SHADING, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SHADING), ...
	PlotBrainAtlas.COLORMAP, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.COLORMAP), ...
	PlotBrainAtlas.COLORMAPSTRING, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.COLORMAPSTRING), ...
	PlotBrainAtlas.ATLAS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.ATLAS), ...
	PlotBrainAtlas.PARENT, Callback('EL', pl_1, 'PROP', 23), ...
	PlotBrainAtlas.SYMS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS), ...
	PlotBrainAtlas.SYMS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_SIZE), ...
	PlotBrainAtlas.SYMS_MARKER, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_MARKER), ...
	PlotBrainAtlas.SYMS_FACE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_FACE_COLOR), ...
	PlotBrainAtlas.SYMS_EDGE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_EDGE_COLOR), ...
	PlotBrainAtlas.SPHS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS), ...
	PlotBrainAtlas.SPHS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_SIZE), ...
	PlotBrainAtlas.SPHS_EDGE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_EDGE_COLOR), ...
	PlotBrainAtlas.SPHS_FACE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_FACE_COLOR), ...
	PlotBrainAtlas.SPHS_EDGE_ALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_EDGE_ALPHA), ...
	PlotBrainAtlas.SPHS_FACE_ALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_FACE_ALPHA), ...
	PlotBrainAtlas.IDS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS), ...
	PlotBrainAtlas.IDS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_SIZE), ...
	PlotBrainAtlas.IDS_FONT_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_FONT_COLOR), ...
	PlotBrainAtlas.IDS_FONT_NAME, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_FONT_NAME), ...
	PlotBrainAtlas.IDS_FONT_INTERPRETER, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_FONT_INTERPRETER), ...
	PlotBrainAtlas.LABS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS), ...
	PlotBrainAtlas.LABS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_SIZE), ...
	PlotBrainAtlas.LABS_FONT_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_FONT_COLOR), ...
	PlotBrainAtlas.LABS_FONT_NAME, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_FONT_NAME), ...
	PlotBrainAtlas.LABS_FONT_INTERPRETER, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_FONT_INTERPRETER) ...
	);
	
prop_number = PlotBrainAtlas.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(PlotBrainAtlas.getPropTag(prop));
	switch PlotBrainAtlas.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(pl_2.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':PlotBrainAtlas:' BRAPH2.BUG_FUNC], ...
				['PlotBrainAtlas.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(pl_2.get(prop), pl_0.get(prop)) && ~isa(pl_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':PlotBrainAtlas:' BRAPH2.BUG_FUNC], ...
				['PlotBrainAtlas.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(pl_2.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':PlotBrainAtlas:' BRAPH2.BUG_FUNC], ...
				['PlotBrainAtlas.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end
pl_3 = PlotBrainAtlas( ...
	PlotBrainAtlas.ID, Callback('EL', pl_2, 'PROP', 1), ...
	PlotBrainAtlas.BKGCOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.BKGCOLOR), ...
	PlotBrainAtlas.SURF, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SURF), ...
	PlotBrainAtlas.AXESCOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.AXESCOLOR), ...
	PlotBrainAtlas.VIEW, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.VIEW), ...
	PlotBrainAtlas.HOLD, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.HOLD), ...
	PlotBrainAtlas.GRID, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.GRID), ...
	PlotBrainAtlas.AXIS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.AXIS), ...
	PlotBrainAtlas.EQUAL, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.EQUAL), ...
	PlotBrainAtlas.TIGHT, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.TIGHT), ...
	PlotBrainAtlas.BRAIN, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.BRAIN), ...
	PlotBrainAtlas.EDGECOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.EDGECOLOR), ...
	PlotBrainAtlas.EDGEALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.EDGEALPHA), ...
	PlotBrainAtlas.FACECOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.FACECOLOR), ...
	PlotBrainAtlas.FACEALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.FACEALPHA), ...
	PlotBrainAtlas.LIGHTING, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LIGHTING), ...
	PlotBrainAtlas.MATERIAL, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.MATERIAL), ...
	PlotBrainAtlas.CAMLIGHT, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.CAMLIGHT), ...
	PlotBrainAtlas.SHADING, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SHADING), ...
	PlotBrainAtlas.COLORMAP, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.COLORMAP), ...
	PlotBrainAtlas.COLORMAPSTRING, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.COLORMAPSTRING), ...
	PlotBrainAtlas.ATLAS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.ATLAS), ...
	PlotBrainAtlas.PARENT, Callback('EL', pl_2, 'PROP', 23), ...
	PlotBrainAtlas.SYMS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS), ...
	PlotBrainAtlas.SYMS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_SIZE), ...
	PlotBrainAtlas.SYMS_MARKER, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_MARKER), ...
	PlotBrainAtlas.SYMS_FACE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_FACE_COLOR), ...
	PlotBrainAtlas.SYMS_EDGE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_EDGE_COLOR), ...
	PlotBrainAtlas.SPHS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS), ...
	PlotBrainAtlas.SPHS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_SIZE), ...
	PlotBrainAtlas.SPHS_EDGE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_EDGE_COLOR), ...
	PlotBrainAtlas.SPHS_FACE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_FACE_COLOR), ...
	PlotBrainAtlas.SPHS_EDGE_ALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_EDGE_ALPHA), ...
	PlotBrainAtlas.SPHS_FACE_ALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_FACE_ALPHA), ...
	PlotBrainAtlas.IDS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS), ...
	PlotBrainAtlas.IDS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_SIZE), ...
	PlotBrainAtlas.IDS_FONT_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_FONT_COLOR), ...
	PlotBrainAtlas.IDS_FONT_NAME, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_FONT_NAME), ...
	PlotBrainAtlas.IDS_FONT_INTERPRETER, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_FONT_INTERPRETER), ...
	PlotBrainAtlas.LABS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS), ...
	PlotBrainAtlas.LABS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_SIZE), ...
	PlotBrainAtlas.LABS_FONT_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_FONT_COLOR), ...
	PlotBrainAtlas.LABS_FONT_NAME, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_FONT_NAME), ...
	PlotBrainAtlas.LABS_FONT_INTERPRETER, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_FONT_INTERPRETER) ...
	);
	
prop_number = PlotBrainAtlas.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(PlotBrainAtlas.getPropTag(prop));
	switch PlotBrainAtlas.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(pl_3.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':PlotBrainAtlas:' BRAPH2.BUG_FUNC], ...
				['PlotBrainAtlas.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(pl_3.get(prop), pl_0.get(prop)) && ~isa(pl_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':PlotBrainAtlas:' BRAPH2.BUG_FUNC], ...
				['PlotBrainAtlas.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(pl_3.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':PlotBrainAtlas:' BRAPH2.BUG_FUNC], ...
				['PlotBrainAtlas.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end

%% Test 3: Result

warning('off', 'BRAPH2:PlotBrainAtlas')
pl = PlotBrainAtlas( ...
	PlotBrainAtlas.ID, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.ID), ...
	PlotBrainAtlas.BKGCOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.BKGCOLOR), ...
	PlotBrainAtlas.SURF, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SURF), ...
	PlotBrainAtlas.AXESCOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.AXESCOLOR), ...
	PlotBrainAtlas.VIEW, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.VIEW), ...
	PlotBrainAtlas.HOLD, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.HOLD), ...
	PlotBrainAtlas.GRID, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.GRID), ...
	PlotBrainAtlas.AXIS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.AXIS), ...
	PlotBrainAtlas.EQUAL, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.EQUAL), ...
	PlotBrainAtlas.TIGHT, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.TIGHT), ...
	PlotBrainAtlas.BRAIN, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.BRAIN), ...
	PlotBrainAtlas.EDGECOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.EDGECOLOR), ...
	PlotBrainAtlas.EDGEALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.EDGEALPHA), ...
	PlotBrainAtlas.FACECOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.FACECOLOR), ...
	PlotBrainAtlas.FACEALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.FACEALPHA), ...
	PlotBrainAtlas.LIGHTING, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LIGHTING), ...
	PlotBrainAtlas.MATERIAL, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.MATERIAL), ...
	PlotBrainAtlas.CAMLIGHT, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.CAMLIGHT), ...
	PlotBrainAtlas.SHADING, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SHADING), ...
	PlotBrainAtlas.COLORMAP, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.COLORMAP), ...
	PlotBrainAtlas.COLORMAPSTRING, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.COLORMAPSTRING), ...
	PlotBrainAtlas.ATLAS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.ATLAS), ...
	PlotBrainAtlas.PARENT, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.PARENT), ...
	PlotBrainAtlas.SYMS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS), ...
	PlotBrainAtlas.SYMS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_SIZE), ...
	PlotBrainAtlas.SYMS_MARKER, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_MARKER), ...
	PlotBrainAtlas.SYMS_FACE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_FACE_COLOR), ...
	PlotBrainAtlas.SYMS_EDGE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_EDGE_COLOR), ...
	PlotBrainAtlas.SPHS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS), ...
	PlotBrainAtlas.SPHS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_SIZE), ...
	PlotBrainAtlas.SPHS_EDGE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_EDGE_COLOR), ...
	PlotBrainAtlas.SPHS_FACE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_FACE_COLOR), ...
	PlotBrainAtlas.SPHS_EDGE_ALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_EDGE_ALPHA), ...
	PlotBrainAtlas.SPHS_FACE_ALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_FACE_ALPHA), ...
	PlotBrainAtlas.IDS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS), ...
	PlotBrainAtlas.IDS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_SIZE), ...
	PlotBrainAtlas.IDS_FONT_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_FONT_COLOR), ...
	PlotBrainAtlas.IDS_FONT_NAME, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_FONT_NAME), ...
	PlotBrainAtlas.IDS_FONT_INTERPRETER, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_FONT_INTERPRETER), ...
	PlotBrainAtlas.LABS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS), ...
	PlotBrainAtlas.LABS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_SIZE), ...
	PlotBrainAtlas.LABS_FONT_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_FONT_COLOR), ...
	PlotBrainAtlas.LABS_FONT_NAME, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_FONT_NAME), ...
	PlotBrainAtlas.LABS_FONT_INTERPRETER, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_FONT_INTERPRETER) ...
	);
warning('on', 'BRAPH2:PlotBrainAtlas')

prop_number = PlotBrainAtlas.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(PlotBrainAtlas.getPropTag(prop));
	switch PlotBrainAtlas.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
		case Category.RESULT
			assert( ...
				~isa(pl.get(prop),  'NoValue'), ...
				[BRAPH2.STR ':PlotBrainAtlas:' BRAPH2.BUG_FUNC], ...
				['PlotBrainAtlas.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				isa(pl.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':PlotBrainAtlas:' BRAPH2.BUG_FUNC], ...
				['PlotBrainAtlas.getr(' int2str(prop) ') must be a NoValue, because it has not been memorized.'] ...
				)
			if isempty(pl.getPropSettings(prop))
				assert( ...
					pl.checkFormat(pl.getPropFormat(prop), pl.get(prop)), ...
					[BRAPH2.STR ':PlotBrainAtlas:' BRAPH2.BUG_FUNC], ...
					['PlotBrainAtlas.get(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			else
				assert( ...
					pl.checkFormat(pl.getPropFormat(prop), pl.get(prop), pl.getPropSettings(prop)), ...
					[BRAPH2.STR ':PlotBrainAtlas:' BRAPH2.BUG_FUNC], ...
					['PlotBrainAtlas.get(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			end
	end
end

%% Test 4: Memorize

warning('off', 'BRAPH2:PlotBrainAtlas')
pl = PlotBrainAtlas( ...
	PlotBrainAtlas.ID, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.ID), ...
	PlotBrainAtlas.BKGCOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.BKGCOLOR), ...
	PlotBrainAtlas.SURF, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SURF), ...
	PlotBrainAtlas.AXESCOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.AXESCOLOR), ...
	PlotBrainAtlas.VIEW, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.VIEW), ...
	PlotBrainAtlas.HOLD, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.HOLD), ...
	PlotBrainAtlas.GRID, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.GRID), ...
	PlotBrainAtlas.AXIS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.AXIS), ...
	PlotBrainAtlas.EQUAL, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.EQUAL), ...
	PlotBrainAtlas.TIGHT, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.TIGHT), ...
	PlotBrainAtlas.BRAIN, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.BRAIN), ...
	PlotBrainAtlas.EDGECOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.EDGECOLOR), ...
	PlotBrainAtlas.EDGEALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.EDGEALPHA), ...
	PlotBrainAtlas.FACECOLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.FACECOLOR), ...
	PlotBrainAtlas.FACEALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.FACEALPHA), ...
	PlotBrainAtlas.LIGHTING, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LIGHTING), ...
	PlotBrainAtlas.MATERIAL, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.MATERIAL), ...
	PlotBrainAtlas.CAMLIGHT, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.CAMLIGHT), ...
	PlotBrainAtlas.SHADING, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SHADING), ...
	PlotBrainAtlas.COLORMAP, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.COLORMAP), ...
	PlotBrainAtlas.COLORMAPSTRING, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.COLORMAPSTRING), ...
	PlotBrainAtlas.ATLAS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.ATLAS), ...
	PlotBrainAtlas.PARENT, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.PARENT), ...
	PlotBrainAtlas.SYMS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS), ...
	PlotBrainAtlas.SYMS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_SIZE), ...
	PlotBrainAtlas.SYMS_MARKER, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_MARKER), ...
	PlotBrainAtlas.SYMS_FACE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_FACE_COLOR), ...
	PlotBrainAtlas.SYMS_EDGE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SYMS_EDGE_COLOR), ...
	PlotBrainAtlas.SPHS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS), ...
	PlotBrainAtlas.SPHS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_SIZE), ...
	PlotBrainAtlas.SPHS_EDGE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_EDGE_COLOR), ...
	PlotBrainAtlas.SPHS_FACE_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_FACE_COLOR), ...
	PlotBrainAtlas.SPHS_EDGE_ALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_EDGE_ALPHA), ...
	PlotBrainAtlas.SPHS_FACE_ALPHA, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.SPHS_FACE_ALPHA), ...
	PlotBrainAtlas.IDS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS), ...
	PlotBrainAtlas.IDS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_SIZE), ...
	PlotBrainAtlas.IDS_FONT_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_FONT_COLOR), ...
	PlotBrainAtlas.IDS_FONT_NAME, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_FONT_NAME), ...
	PlotBrainAtlas.IDS_FONT_INTERPRETER, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.IDS_FONT_INTERPRETER), ...
	PlotBrainAtlas.LABS, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS), ...
	PlotBrainAtlas.LABS_SIZE, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_SIZE), ...
	PlotBrainAtlas.LABS_FONT_COLOR, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_FONT_COLOR), ...
	PlotBrainAtlas.LABS_FONT_NAME, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_FONT_NAME), ...
	PlotBrainAtlas.LABS_FONT_INTERPRETER, PlotBrainAtlas.getPropDefault(PlotBrainAtlas.LABS_FONT_INTERPRETER) ...
	);
warning('on', 'BRAPH2:PlotBrainAtlas')

for prop = 1:1:PlotBrainAtlas.getPropNumber()
	TAG = upper(PlotBrainAtlas.getPropTag(prop));
	switch PlotBrainAtlas.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
		case Category.RESULT
			assert( ...
				~isa(pl.get(prop),  'NoValue'), ...
				[BRAPH2.STR ':PlotBrainAtlas:' BRAPH2.BUG_FUNC], ...
				['PlotBrainAtlas.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				isa(pl.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':PlotBrainAtlas:' BRAPH2.BUG_FUNC], ...
				['PlotBrainAtlas.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
				)
			assert( ...
				~isa(pl.memorize(prop),  'NoValue'), ...
				[BRAPH2.STR ':PlotBrainAtlas:' BRAPH2.BUG_FUNC], ...
				['PlotBrainAtlas.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				~isa(pl.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':PlotBrainAtlas:' BRAPH2.BUG_FUNC], ...
				['PlotBrainAtlas.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
				)
			assert( ...
				pl.checkFormat(pl.getPropFormat(prop), pl.getr(prop),pl.getPropSettings(prop)), ...
				[BRAPH2.STR ':PlotBrainAtlas:' BRAPH2.BUG_FUNC], ...
				['PlotBrainAtlas.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
				)
	end
end

%% Test 5: Plot

fig = figure();
br1 = BrainRegion('ID', 'BR ID1', 'Label', 'brain region label 1', 'Notes', 'brain region notes 1', 'x', 1, 'y', 10, 'z', 11);
br2 = BrainRegion('ID', 'BR ID2', 'Label', 'brain region label 2', 'Notes', 'brain region notes 2', 'x', 2, 'y', 20, 'z', 22);
br3 = BrainRegion('ID', 'BR ID3', 'Label', 'brain region label 3', 'Notes', 'brain region notes 3', 'x', 3, 'y', 30, 'z', 33);
br4 = BrainRegion('ID', 'BR ID4', 'Label', 'brain region label 4', 'Notes', 'brain region notes 4', 'x', 4, 'y', 40, 'z', 44);
br5 = BrainRegion('ID', 'BR ID5', 'Label', 'brain region label 5', 'Notes', 'brain region notes 5', 'x', 5, 'y', 50, 'z', 55);

bs = BrainSurface('ID', 'Human_Cerebellum.nv');
br_dict =  IndexedDictionary( ...
    'id', 'idict', ...
    'it_class', 'BrainRegion', ...
    'it_key', IndexedDictionary.getPropDefault(IndexedDictionary.IT_KEY), ...
    'it_list', {br1, br2, br3, br4, br5});
atlas = BrainAtlas('ID', 'BA ID', 'Label', 'Brain Atlas Label', 'Notes', 'Brain atlas notes', 'SURF', bs, 'BR_DICT', br_dict);
pl = PlotBrainAtlas('atlas', atlas, ...
    'syms', 1, 'SYMS_SIZE', [1:5:25]', ...
    'SYMS_FACE_COLOR', [0 0 0], 'SYMS_EDGE_COLOR', [0 0 0], ...
    'SPHS', 1, 'SPHS_SIZE', [1:1:5]', ...
    'SPHS_FACE_ALPHA', .7, 'SPHS_FACE_COLOR', [0 1 0], ...
    'SPHS_EDGE_ALPHA', .4, 'SPHS_EDGE_COLOR', [1 1 1], ...
    'IDS', 1, 'IDS_SIZE', [11:1:15]', 'IDS_FONT_COLOR', [0 0 0], ...
    'LABS', 1, 'LABS_SIZE', [12:1:16]', 'LABS_FONT_COLOR', [0 0 0], ...
    'SURF', ImporterBrainSurfaceNV('FILE', 'human_ICBM152.nv').get('SURF'));
pl.draw();
pl.settings();

close(fig)

