%EXAMPLE_CON_NN_WU
% Script example pipeline CON NN WU

clear variables %#ok<*NASGU>

%% Load BrainAtlas
im_ba = ImporterBrainAtlasXLS( ...
    'FILE', [fileparts(which('example_CON_WU')) filesep 'example data CON (DTI)' filesep 'desikan_atlas.xlsx'], ...
    'WAITBAR', true ...
    );

ba = im_ba.get('BA');

%% Load Groups of SubjectCON as Training set
im_gr1 = ImporterGroupSubjectCON_XLS( ...
    'DIRECTORY', [fileparts(which('example_CON_WU')) filesep 'example data CON (DTI)' filesep 'xls' filesep 'GroupName1'], ...
    'BA', ba, ...
    'WAITBAR', true ...
    );

gr1 = im_gr1.get('GR');

im_gr2 = ImporterGroupSubjectCON_XLS( ...
    'DIRECTORY', [fileparts(which('example_CON_WU')) filesep 'example data CON (DTI)' filesep 'xls' filesep 'GroupName2'], ...
    'BA', ba, ...
    'WAITBAR', true ...
    );

gr2 = im_gr2.get('GR');

%% Train the Classifier with training set
ds_processor = DatasetProcessor_Classification_CON_WU( ...
    'GR_1', gr_1, ...
    'GR_2', gr_2, ...
    'DENSITY_OF_FEATURE_SELECTION', 0.05);

classifier_nn = ClassifierNN('DatasetProcessor', ds_processor);

classifier_nn.memorize('TRAINED_NN');
auc_train = classifier_nn.get('AUC');
classifier_nn.getHeatMap('HEATMAP'); % fig
classifier_nn.getConfusionMatrix('CONFUSION_MATRIX'); % fig

%% Load Groups of SubjectCON as Test Set 
im_gr1 = ImporterGroupSubjectCON_XLS( ...
    'DIRECTORY', [fileparts(which('example_CON_WU')) filesep 'example data CON (DTI)' filesep 'xls' filesep 'GroupName1'], ...
    'BA', ba, ...
    'WAITBAR', true ...
    );

gr1_test = im_gr1.get('GR');

im_gr2 = ImporterGroupSubjectCON_XLS( ...
    'DIRECTORY', [fileparts(which('example_CON_WU')) filesep 'example data CON (DTI)' filesep 'xls' filesep 'GroupName2'], ...
    'BA', ba, ...
    'WAITBAR', true ...
    );

gr2_test = im_gr2.get('GR');


%% Evaluate the model with unseen dataset
model_evaluator = ModelEvaluator_Classification( ...
    'TrainedClassifier', classifier_nn, ...
    'gr1', gr1_test, ...
    'gr2', gr2_test);

auc_test = model_evaluator.get('AUC');
model_evaluator.get('CONFUSION_MATRIX'); % fig
