%TEST_NNDATA_CON_FUN_MP_WU

%% Test 1.1: Instantiation - empty

nnd = NNData_CON_FUN_MP_WU();

prop_number = NNData_CON_FUN_MP_WU.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(NNData_CON_FUN_MP_WU.getPropTag(prop));
	assert( ...
		isa(nnd.getr(prop), 'NoValue'), ...
		[BRAPH2.STR ':NNData_CON_FUN_MP_WU:' BRAPH2.BUG_FUNC], ...
		['NNData_CON_FUN_MP_WU.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
		'Or there could be an error in NNData_CON_FUN_MP_WU.getr(' int2str(prop) ').'] ...
		)
	assert( ...
		isa(nnd.getr(TAG), 'NoValue'), ...
		[BRAPH2.STR ':NNData_CON_FUN_MP_WU:' BRAPH2.BUG_FUNC], ...
		['NNData_CON_FUN_MP_WU.getr(''' TAG ''') must be inizialized to NoValue(). ' ...
		'Or there could be an error in NNData_CON_FUN_MP_WU.getr(''' TAG ''').'] ...
		)
end

%% Test 1.2: Instantiation - defaults

warning('off', 'BRAPH2:NNData_CON_FUN_MP_WU')
nnd = NNData_CON_FUN_MP_WU( ...
	NNData_CON_FUN_MP_WU.ID, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.ID), ...
	NNData_CON_FUN_MP_WU.LABEL, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.LABEL), ...
	NNData_CON_FUN_MP_WU.NOTES, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.NOTES), ...
	NNData_CON_FUN_MP_WU.WAITBAR, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.WAITBAR), ...
	NNData_CON_FUN_MP_WU.INPUT_TYPE, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.INPUT_TYPE), ...
	NNData_CON_FUN_MP_WU.G, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.G), ...
	NNData_CON_FUN_MP_WU.MEASURES, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.MEASURES), ...
	NNData_CON_FUN_MP_WU.TARGET_NAME, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.TARGET_NAME), ...
	NNData_CON_FUN_MP_WU.GR, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.GR), ...
	NNData_CON_FUN_MP_WU.GR_NN, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.GR_NN), ...
	NNData_CON_FUN_MP_WU.REPETITION, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.REPETITION), ...
	NNData_CON_FUN_MP_WU.FREQUENCYRULEMIN, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.FREQUENCYRULEMIN), ...
	NNData_CON_FUN_MP_WU.FREQUENCYRULEMAX, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.FREQUENCYRULEMAX), ...
	NNData_CON_FUN_MP_WU.CORRELATION_RULE, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.CORRELATION_RULE), ...
	NNData_CON_FUN_MP_WU.NEGATIVE_WEIGHT_RULE, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.NEGATIVE_WEIGHT_RULE) ...
	);
warning('on', 'BRAPH2:NNData_CON_FUN_MP_WU')

for prop = 1:1:NNData_CON_FUN_MP_WU.getPropNumber()
	TAG = upper(NNData_CON_FUN_MP_WU.getPropTag(prop));
	switch NNData_CON_FUN_MP_WU.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isequal(nnd.getr(prop), NNData_CON_FUN_MP_WU.getPropDefaultConditioned(prop)), ...
				[BRAPH2.STR ':NNData_CON_FUN_MP_WU:' BRAPH2.BUG_FUNC], ...
				['NNData_CON_FUN_MP_WU.getr(' int2str(prop) ') must be inizialized to its default value ' ...
				'given by NNData_CON_FUN_MP_WU.getPropDefaultConditioned(' int2str(prop) '). ' ...
				'Or there could be an error in NNData_CON_FUN_MP_WU.getr(' int2str(prop) ').'] ...
				)
			assert( ...
				isequal(nnd.getr(TAG), NNData_CON_FUN_MP_WU.getPropDefaultConditioned(prop)), ...
				[BRAPH2.STR ':NNData_CON_FUN_MP_WU:' BRAPH2.BUG_FUNC], ...
				['NNData_CON_FUN_MP_WU.getr(''' TAG ''') must be inizialized to its default value ' ...
				'given by NNData_CON_FUN_MP_WU.getPropDefaultConditioned(' int2str(prop) '). ' ...
				'Or there could be an error in NNData_CON_FUN_MP_WU.getr(''' TAG ''').'] ...
				)
		case Category.RESULT
			assert( ...
				isa(nnd.getr(prop), 'NoValue'), ...
				[BRAPH2.STR ':NNData_CON_FUN_MP_WU:' BRAPH2.BUG_FUNC], ...
				['Being a result, NNData_CON_FUN_MP_WU.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
				'Or there could be an error in NNData_CON_FUN_MP_WU.getr(' int2str(prop) ').'] ...
				)
			assert( ...
				isa(nnd.getr(TAG), 'NoValue'), ...
				[BRAPH2.STR ':NNData_CON_FUN_MP_WU:' BRAPH2.BUG_FUNC], ...
				['Being a result, NNData_CON_FUN_MP_WU.getr(''' TAG ''') must be inizialized to NoValue(). ' ...
				'Or there could be an error in NNData_CON_FUN_MP_WU.getr(''' TAG ''').'] ...
				)
	end
end

%% Test 2: Callbacks

warning('off', 'BRAPH2:NNData_CON_FUN_MP_WU')
nnd_0 = NNData_CON_FUN_MP_WU( ...
	NNData_CON_FUN_MP_WU.ID, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.ID), ...
	NNData_CON_FUN_MP_WU.LABEL, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.LABEL), ...
	NNData_CON_FUN_MP_WU.NOTES, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.NOTES), ...
	NNData_CON_FUN_MP_WU.WAITBAR, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.WAITBAR), ...
	NNData_CON_FUN_MP_WU.INPUT_TYPE, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.INPUT_TYPE), ...
	NNData_CON_FUN_MP_WU.G, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.G), ...
	NNData_CON_FUN_MP_WU.MEASURES, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.MEASURES), ...
	NNData_CON_FUN_MP_WU.TARGET_NAME, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.TARGET_NAME), ...
	NNData_CON_FUN_MP_WU.GR, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.GR), ...
	NNData_CON_FUN_MP_WU.GR_NN, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.GR_NN), ...
	NNData_CON_FUN_MP_WU.REPETITION, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.REPETITION), ...
	NNData_CON_FUN_MP_WU.FREQUENCYRULEMIN, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.FREQUENCYRULEMIN), ...
	NNData_CON_FUN_MP_WU.FREQUENCYRULEMAX, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.FREQUENCYRULEMAX), ...
	NNData_CON_FUN_MP_WU.CORRELATION_RULE, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.CORRELATION_RULE), ...
	NNData_CON_FUN_MP_WU.NEGATIVE_WEIGHT_RULE, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.NEGATIVE_WEIGHT_RULE) ...
	);
warning('on', 'BRAPH2:NNData_CON_FUN_MP_WU')

nnd_1 = NNData_CON_FUN_MP_WU( ...
	NNData_CON_FUN_MP_WU.ID, Callback('EL', nnd_0, 'PROP', 1), ...
	NNData_CON_FUN_MP_WU.LABEL, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.LABEL), ...
	NNData_CON_FUN_MP_WU.NOTES, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.NOTES), ...
	NNData_CON_FUN_MP_WU.WAITBAR, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.WAITBAR), ...
	NNData_CON_FUN_MP_WU.INPUT_TYPE, Callback('EL', nnd_0, 'PROP', 5), ...
	NNData_CON_FUN_MP_WU.G, Callback('EL', nnd_0, 'PROP', 6), ...
	NNData_CON_FUN_MP_WU.MEASURES, Callback('EL', nnd_0, 'PROP', 7), ...
	NNData_CON_FUN_MP_WU.TARGET_NAME, Callback('EL', nnd_0, 'PROP', 8), ...
	NNData_CON_FUN_MP_WU.GR, Callback('EL', nnd_0, 'PROP', 9), ...
	NNData_CON_FUN_MP_WU.GR_NN, NoValue(), ...
	NNData_CON_FUN_MP_WU.REPETITION, Callback('EL', nnd_0, 'PROP', 11), ...
	NNData_CON_FUN_MP_WU.FREQUENCYRULEMIN, Callback('EL', nnd_0, 'PROP', 12), ...
	NNData_CON_FUN_MP_WU.FREQUENCYRULEMAX, Callback('EL', nnd_0, 'PROP', 13), ...
	NNData_CON_FUN_MP_WU.CORRELATION_RULE, Callback('EL', nnd_0, 'PROP', 14), ...
	NNData_CON_FUN_MP_WU.NEGATIVE_WEIGHT_RULE, Callback('EL', nnd_0, 'PROP', 15) ...
	);
	
prop_number = NNData_CON_FUN_MP_WU.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(NNData_CON_FUN_MP_WU.getPropTag(prop));
	switch NNData_CON_FUN_MP_WU.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(nnd_1.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':NNData_CON_FUN_MP_WU:' BRAPH2.BUG_FUNC], ...
				['NNData_CON_FUN_MP_WU.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(nnd_1.get(prop), nnd_0.get(prop)) && ~isa(nnd_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':NNData_CON_FUN_MP_WU:' BRAPH2.BUG_FUNC], ...
				['NNData_CON_FUN_MP_WU.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(nnd_1.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':NNData_CON_FUN_MP_WU:' BRAPH2.BUG_FUNC], ...
				['NNData_CON_FUN_MP_WU.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end
nnd_2 = NNData_CON_FUN_MP_WU( ...
	NNData_CON_FUN_MP_WU.ID, Callback('EL', nnd_1, 'PROP', 1), ...
	NNData_CON_FUN_MP_WU.LABEL, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.LABEL), ...
	NNData_CON_FUN_MP_WU.NOTES, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.NOTES), ...
	NNData_CON_FUN_MP_WU.WAITBAR, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.WAITBAR), ...
	NNData_CON_FUN_MP_WU.INPUT_TYPE, Callback('EL', nnd_1, 'PROP', 5), ...
	NNData_CON_FUN_MP_WU.G, Callback('EL', nnd_1, 'PROP', 6), ...
	NNData_CON_FUN_MP_WU.MEASURES, Callback('EL', nnd_1, 'PROP', 7), ...
	NNData_CON_FUN_MP_WU.TARGET_NAME, Callback('EL', nnd_1, 'PROP', 8), ...
	NNData_CON_FUN_MP_WU.GR, Callback('EL', nnd_1, 'PROP', 9), ...
	NNData_CON_FUN_MP_WU.GR_NN, NoValue(), ...
	NNData_CON_FUN_MP_WU.REPETITION, Callback('EL', nnd_1, 'PROP', 11), ...
	NNData_CON_FUN_MP_WU.FREQUENCYRULEMIN, Callback('EL', nnd_1, 'PROP', 12), ...
	NNData_CON_FUN_MP_WU.FREQUENCYRULEMAX, Callback('EL', nnd_1, 'PROP', 13), ...
	NNData_CON_FUN_MP_WU.CORRELATION_RULE, Callback('EL', nnd_1, 'PROP', 14), ...
	NNData_CON_FUN_MP_WU.NEGATIVE_WEIGHT_RULE, Callback('EL', nnd_1, 'PROP', 15) ...
	);
	
prop_number = NNData_CON_FUN_MP_WU.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(NNData_CON_FUN_MP_WU.getPropTag(prop));
	switch NNData_CON_FUN_MP_WU.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(nnd_2.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':NNData_CON_FUN_MP_WU:' BRAPH2.BUG_FUNC], ...
				['NNData_CON_FUN_MP_WU.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(nnd_2.get(prop), nnd_0.get(prop)) && ~isa(nnd_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':NNData_CON_FUN_MP_WU:' BRAPH2.BUG_FUNC], ...
				['NNData_CON_FUN_MP_WU.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(nnd_2.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':NNData_CON_FUN_MP_WU:' BRAPH2.BUG_FUNC], ...
				['NNData_CON_FUN_MP_WU.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end
nnd_3 = NNData_CON_FUN_MP_WU( ...
	NNData_CON_FUN_MP_WU.ID, Callback('EL', nnd_2, 'PROP', 1), ...
	NNData_CON_FUN_MP_WU.LABEL, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.LABEL), ...
	NNData_CON_FUN_MP_WU.NOTES, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.NOTES), ...
	NNData_CON_FUN_MP_WU.WAITBAR, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.WAITBAR), ...
	NNData_CON_FUN_MP_WU.INPUT_TYPE, Callback('EL', nnd_2, 'PROP', 5), ...
	NNData_CON_FUN_MP_WU.G, Callback('EL', nnd_2, 'PROP', 6), ...
	NNData_CON_FUN_MP_WU.MEASURES, Callback('EL', nnd_2, 'PROP', 7), ...
	NNData_CON_FUN_MP_WU.TARGET_NAME, Callback('EL', nnd_2, 'PROP', 8), ...
	NNData_CON_FUN_MP_WU.GR, Callback('EL', nnd_2, 'PROP', 9), ...
	NNData_CON_FUN_MP_WU.GR_NN, NoValue(), ...
	NNData_CON_FUN_MP_WU.REPETITION, Callback('EL', nnd_2, 'PROP', 11), ...
	NNData_CON_FUN_MP_WU.FREQUENCYRULEMIN, Callback('EL', nnd_2, 'PROP', 12), ...
	NNData_CON_FUN_MP_WU.FREQUENCYRULEMAX, Callback('EL', nnd_2, 'PROP', 13), ...
	NNData_CON_FUN_MP_WU.CORRELATION_RULE, Callback('EL', nnd_2, 'PROP', 14), ...
	NNData_CON_FUN_MP_WU.NEGATIVE_WEIGHT_RULE, Callback('EL', nnd_2, 'PROP', 15) ...
	);
	
prop_number = NNData_CON_FUN_MP_WU.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(NNData_CON_FUN_MP_WU.getPropTag(prop));
	switch NNData_CON_FUN_MP_WU.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(nnd_3.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':NNData_CON_FUN_MP_WU:' BRAPH2.BUG_FUNC], ...
				['NNData_CON_FUN_MP_WU.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(nnd_3.get(prop), nnd_0.get(prop)) && ~isa(nnd_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':NNData_CON_FUN_MP_WU:' BRAPH2.BUG_FUNC], ...
				['NNData_CON_FUN_MP_WU.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(nnd_3.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':NNData_CON_FUN_MP_WU:' BRAPH2.BUG_FUNC], ...
				['NNData_CON_FUN_MP_WU.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end

%% Test 3: Result

warning('off', 'BRAPH2:NNData_CON_FUN_MP_WU')
nnd = NNData_CON_FUN_MP_WU( ...
	NNData_CON_FUN_MP_WU.ID, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.ID), ...
	NNData_CON_FUN_MP_WU.LABEL, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.LABEL), ...
	NNData_CON_FUN_MP_WU.NOTES, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.NOTES), ...
	NNData_CON_FUN_MP_WU.WAITBAR, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.WAITBAR), ...
	NNData_CON_FUN_MP_WU.INPUT_TYPE, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.INPUT_TYPE), ...
	NNData_CON_FUN_MP_WU.G, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.G), ...
	NNData_CON_FUN_MP_WU.MEASURES, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.MEASURES), ...
	NNData_CON_FUN_MP_WU.TARGET_NAME, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.TARGET_NAME), ...
	NNData_CON_FUN_MP_WU.GR, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.GR), ...
	NNData_CON_FUN_MP_WU.GR_NN, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.GR_NN), ...
	NNData_CON_FUN_MP_WU.REPETITION, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.REPETITION), ...
	NNData_CON_FUN_MP_WU.FREQUENCYRULEMIN, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.FREQUENCYRULEMIN), ...
	NNData_CON_FUN_MP_WU.FREQUENCYRULEMAX, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.FREQUENCYRULEMAX), ...
	NNData_CON_FUN_MP_WU.CORRELATION_RULE, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.CORRELATION_RULE), ...
	NNData_CON_FUN_MP_WU.NEGATIVE_WEIGHT_RULE, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.NEGATIVE_WEIGHT_RULE) ...
	);
warning('on', 'BRAPH2:NNData_CON_FUN_MP_WU')

prop_number = NNData_CON_FUN_MP_WU.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(NNData_CON_FUN_MP_WU.getPropTag(prop));
	switch NNData_CON_FUN_MP_WU.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
		case Category.RESULT
			assert( ...
				~isa(nnd.get(prop),  'NoValue'), ...
				[BRAPH2.STR ':NNData_CON_FUN_MP_WU:' BRAPH2.BUG_FUNC], ...
				['NNData_CON_FUN_MP_WU.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				isa(nnd.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':NNData_CON_FUN_MP_WU:' BRAPH2.BUG_FUNC], ...
				['NNData_CON_FUN_MP_WU.getr(' int2str(prop) ') must be a NoValue, because it has not been memorized.'] ...
				)
			if isempty(nnd.getPropSettings(prop))
				assert( ...
					nnd.checkFormat(nnd.getPropFormat(prop), nnd.get(prop)), ...
					[BRAPH2.STR ':NNData_CON_FUN_MP_WU:' BRAPH2.BUG_FUNC], ...
					['NNData_CON_FUN_MP_WU.get(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			else
				assert( ...
					nnd.checkFormat(nnd.getPropFormat(prop), nnd.get(prop), nnd.getPropSettings(prop)), ...
					[BRAPH2.STR ':NNData_CON_FUN_MP_WU:' BRAPH2.BUG_FUNC], ...
					['NNData_CON_FUN_MP_WU.get(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			end
	end
end

%% Test 4: Memorize

warning('off', 'BRAPH2:NNData_CON_FUN_MP_WU')
nnd = NNData_CON_FUN_MP_WU( ...
	NNData_CON_FUN_MP_WU.ID, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.ID), ...
	NNData_CON_FUN_MP_WU.LABEL, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.LABEL), ...
	NNData_CON_FUN_MP_WU.NOTES, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.NOTES), ...
	NNData_CON_FUN_MP_WU.WAITBAR, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.WAITBAR), ...
	NNData_CON_FUN_MP_WU.INPUT_TYPE, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.INPUT_TYPE), ...
	NNData_CON_FUN_MP_WU.G, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.G), ...
	NNData_CON_FUN_MP_WU.MEASURES, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.MEASURES), ...
	NNData_CON_FUN_MP_WU.TARGET_NAME, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.TARGET_NAME), ...
	NNData_CON_FUN_MP_WU.GR, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.GR), ...
	NNData_CON_FUN_MP_WU.GR_NN, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.GR_NN), ...
	NNData_CON_FUN_MP_WU.REPETITION, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.REPETITION), ...
	NNData_CON_FUN_MP_WU.FREQUENCYRULEMIN, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.FREQUENCYRULEMIN), ...
	NNData_CON_FUN_MP_WU.FREQUENCYRULEMAX, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.FREQUENCYRULEMAX), ...
	NNData_CON_FUN_MP_WU.CORRELATION_RULE, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.CORRELATION_RULE), ...
	NNData_CON_FUN_MP_WU.NEGATIVE_WEIGHT_RULE, NNData_CON_FUN_MP_WU.getPropDefault(NNData_CON_FUN_MP_WU.NEGATIVE_WEIGHT_RULE) ...
	);
warning('on', 'BRAPH2:NNData_CON_FUN_MP_WU')

for prop = 1:1:NNData_CON_FUN_MP_WU.getPropNumber()
	TAG = upper(NNData_CON_FUN_MP_WU.getPropTag(prop));
	switch NNData_CON_FUN_MP_WU.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
		case Category.RESULT
			assert( ...
				~isa(nnd.get(prop),  'NoValue'), ...
				[BRAPH2.STR ':NNData_CON_FUN_MP_WU:' BRAPH2.BUG_FUNC], ...
				['NNData_CON_FUN_MP_WU.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				isa(nnd.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':NNData_CON_FUN_MP_WU:' BRAPH2.BUG_FUNC], ...
				['NNData_CON_FUN_MP_WU.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
				)
			assert( ...
				~isa(nnd.memorize(prop),  'NoValue'), ...
				[BRAPH2.STR ':NNData_CON_FUN_MP_WU:' BRAPH2.BUG_FUNC], ...
				['NNData_CON_FUN_MP_WU.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				~isa(nnd.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':NNData_CON_FUN_MP_WU:' BRAPH2.BUG_FUNC], ...
				['NNData_CON_FUN_MP_WU.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
				)
			assert( ...
				nnd.checkFormat(nnd.getPropFormat(prop), nnd.getr(prop),nnd.getPropSettings(prop)), ...
				[BRAPH2.STR ':NNData_CON_FUN_MP_WU:' BRAPH2.BUG_FUNC], ...
				['NNData_CON_FUN_MP_WU.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
				)
	end
end

%% Test 5: Example 1

example_NN_CON_FUN_MP_WU_Classification_GraphMeasures

%% Test 6: Example 2

example_NNCV_CON_FUN_MP_WU_Classification_AdjacencyMatrix

