%TEST_SUBJECTCON_FUN_MP

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	sub = SubjectCON_FUN_MP();
	 
	% get('ELCLASS')
	if isa(SubjectCON_FUN_MP, 'ConcreteElement')
		assert(strcmp(SubjectCON_FUN_MP().get('ELCLASS'), 'SubjectCON_FUN_MP'), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'SubjectCON_FUN_MP().get(''ELCLASS'') should return ''SubjectCON_FUN_MP''.')
	end
	 
	% getBuild()
	assert(SubjectCON_FUN_MP.getBuild() == 1 && SubjectCON_FUN_MP.getBuild() > 0, ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'SubjectCON_FUN_MP.getBuild() should return the SubjectCON_FUN_MP build number.')
	assert(sub.getBuild() == 1 && sub.getBuild() > 0 , ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'sub.getBuild() should return the SubjectCON_FUN_MP build number.')
	assert(Element.getBuild(sub) == 1 && Element.getBuild(sub) > 0, ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(sub) should return the SubjectCON_FUN_MP build number.')
	assert(Element.getBuild('SubjectCON_FUN_MP') == 1 && Element.getBuild('SubjectCON_FUN_MP') > 0, ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''SubjectCON_FUN_MP'') should return the SubjectCON_FUN_MP build number.')
	 
	% getClass()
	assert(strcmp(SubjectCON_FUN_MP.getClass(), 'SubjectCON_FUN_MP'), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'SubjectCON_FUN_MP.getClass() should return ''SubjectCON_FUN_MP''.')
	assert(strcmp(sub.getClass(), 'SubjectCON_FUN_MP'), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'sub.getClass() should return ''SubjectCON_FUN_MP''.')
	assert(strcmp(Element.getClass(sub), 'SubjectCON_FUN_MP'), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(sub) should return ''SubjectCON_FUN_MP''.')
	assert(strcmp(Element.getClass('SubjectCON_FUN_MP'), 'SubjectCON_FUN_MP'), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''SubjectCON_FUN_MP'') should return ''SubjectCON_FUN_MP''.')
	 
	% getSubclasses()
	assert(isequal(SubjectCON_FUN_MP.getSubclasses(), subclasses('SubjectCON_FUN_MP', [], [], true)), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'SubjectCON_FUN_MP.getSubclasses() should return the same result as subclasses(''SubjectCON_FUN_MP'', [], [], true).')
	assert(isequal(sub.getSubclasses(), subclasses('SubjectCON_FUN_MP', [], [], true)), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''SubjectCON_FUN_MP'', [], [], true).')
	assert(isequal(Element.getSubclasses(sub), subclasses('SubjectCON_FUN_MP', [], [], true)), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(sub) should return the same result as subclasses(''SubjectCON_FUN_MP'', [], [], true).')
	assert(isequal(Element.getSubclasses('SubjectCON_FUN_MP'), subclasses('SubjectCON_FUN_MP', [], [], true)), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''SubjectCON_FUN_MP'') should return the same result as subclasses(''SubjectCON_FUN_MP'', [], [], true).')
	 
	% getProps()
	assert(isempty(SubjectCON_FUN_MP.getProps()) || isequal(SubjectCON_FUN_MP.getProps(), 1:1:length(SubjectCON_FUN_MP.getProps())), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'SubjectCON_FUN_MP.getProps() should return a row vector [1:1:N].')
	assert(isempty(SubjectCON_FUN_MP.getProps()) || isequal(sub.getProps(), 1:1:length(SubjectCON_FUN_MP.getProps())), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'sub.getProps() should return a row vector [1:1:N].')
	assert(isempty(SubjectCON_FUN_MP.getProps()) || isequal(Element.getProps(sub), 1:1:length(SubjectCON_FUN_MP.getProps())), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(sub) should return a row vector [1:1:N].')
	assert(isempty(SubjectCON_FUN_MP.getProps()) || isequal(Element.getProps('SubjectCON_FUN_MP'), 1:1:length(SubjectCON_FUN_MP.getProps())), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''SubjectCON_FUN_MP'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) SubjectCON_FUN_MP.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(SubjectCON_FUN_MP.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(SubjectCON_FUN_MP.getProps())), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'SubjectCON_FUN_MP.getProps(category) does not work.')
	tmp = cellfun(@(category) sub.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(SubjectCON_FUN_MP.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(SubjectCON_FUN_MP.getProps())), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'sub.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(sub, category), categories, 'UniformOutput', false);
	assert(isempty(SubjectCON_FUN_MP.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(SubjectCON_FUN_MP.getProps())), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(sub, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('SubjectCON_FUN_MP', category), categories, 'UniformOutput', false);
	assert(isempty(SubjectCON_FUN_MP.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(SubjectCON_FUN_MP.getProps())), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''SubjectCON_FUN_MP'', category) does not work.')
	 
	% getPropNumber()
	assert(SubjectCON_FUN_MP.getPropNumber() == length(SubjectCON_FUN_MP.getProps()), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'SubjectCON_FUN_MP.getPropNumber() should return the number of properties.')
	assert(sub.getPropNumber() == length(SubjectCON_FUN_MP.getProps()), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'sub.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(sub) == length(SubjectCON_FUN_MP.getProps()), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(sub) should return the number of properties.')
	assert(Element.getPropNumber('SubjectCON_FUN_MP') == length(SubjectCON_FUN_MP.getProps()), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''SubjectCON_FUN_MP'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) SubjectCON_FUN_MP.getPropNumber(category), categories)) == SubjectCON_FUN_MP.getPropNumber(), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'SubjectCON_FUN_MP.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) sub.getPropNumber(category), categories)) == SubjectCON_FUN_MP.getPropNumber(), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'sub.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(sub, category), categories)) == SubjectCON_FUN_MP.getPropNumber(), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(sub, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('SubjectCON_FUN_MP', category), categories)) == SubjectCON_FUN_MP.getPropNumber(), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''SubjectCON_FUN_MP'', category) does not work.')
	 
	% existsProp(prop)
	assert(~SubjectCON_FUN_MP.existsProp(NaN), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'SubjectCON_FUN_MP.existsProp(prop) does not work.')
	assert(~sub.existsProp(NaN), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'sub.existsProp(prop) does not work.')
	assert(~Element.existsProp(sub, NaN), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(sub, prop) does not work.')
	assert(~Element.existsProp('SubjectCON_FUN_MP', NaN), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''SubjectCON_FUN_MP'', prop) does not work.')
	 
	assert_with_error('SubjectCON_FUN_MP.existsProp(NaN)', [BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.WRONG_INPUT], sub)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.WRONG_INPUT], sub)
	assert_with_error('Element.existsProp(''SubjectCON_FUN_MP'', NaN)', [BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:SubjectCON_FUN_MP.getPropNumber()
		assert(SubjectCON_FUN_MP.existsProp(prop), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'SubjectCON_FUN_MP.existsProp(prop) does not work.')
		assert(sub.existsProp(prop), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'sub.existsProp(prop) does not work.')
		assert(Element.existsProp(sub, prop), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(sub, prop) does not work.')
		assert(Element.existsProp('SubjectCON_FUN_MP', prop), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''SubjectCON_FUN_MP'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~SubjectCON_FUN_MP.existsTag(''), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'SubjectCON_FUN_MP.existsTag(tag) does not work.')
	assert(~sub.existsTag(''), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'sub.existsTag(tag) does not work.')
	assert(~Element.existsTag(sub, ''), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(sub, tag) does not work.')
	assert(~Element.existsTag('SubjectCON_FUN_MP', ''), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''SubjectCON_FUN_MP'', tag) does not work.')
	 
	assert_with_error('SubjectCON_FUN_MP.existsTag('''')', [BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.WRONG_INPUT], sub)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.WRONG_INPUT], sub)
	assert_with_error('Element.existsTag(''SubjectCON_FUN_MP'', '''')', [BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:SubjectCON_FUN_MP.getPropNumber()
		tag = sub.getPropTag(prop);
		assert(SubjectCON_FUN_MP.existsTag(tag), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'SubjectCON_FUN_MP.existsTag(tag) does not work.')
		assert(sub.existsTag(tag), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'sub.existsTag(tag) does not work.')
		assert(Element.existsTag(sub, tag), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(sub, tga) does not work.')
		assert(Element.existsTag('SubjectCON_FUN_MP', tag), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''SubjectCON_FUN_MP'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:SubjectCON_FUN_MP.getPropNumber()
		assert(SubjectCON_FUN_MP.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'SubjectCON_FUN_MP.getPropProp(prop) does not work.')
		assert(sub.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'sub.getPropProp(prop) does not work.')
		assert(Element.getPropProp(sub, prop) == prop, ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(sub, prop) does not work.')
		assert(Element.getPropProp('SubjectCON_FUN_MP', prop) == prop, ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''SubjectCON_FUN_MP'', prop) does not work.')
	 
		tag = sub.getPropTag(prop);
		assert(SubjectCON_FUN_MP.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'SubjectCON_FUN_MP.getPropProp(tag) does not work.')
		assert(sub.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'sub.getPropProp(tag) does not work.')
		assert(Element.getPropProp(sub, tag) == prop, ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(sub, tag) does not work.')
		assert(Element.getPropProp('SubjectCON_FUN_MP', prop) == prop, ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''SubjectCON_FUN_MP'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:SubjectCON_FUN_MP.getPropNumber()
		tag = sub.getPropTag(prop);
	 
		assert(strcmp(SubjectCON_FUN_MP.getPropTag(prop), tag), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'SubjectCON_FUN_MP.getPropTag(prop) does not work.')
		assert(strcmp(sub.getPropTag(prop), tag), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'sub.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(sub, prop), tag), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(sub, prop) does not work.')
		assert(strcmp(Element.getPropTag('SubjectCON_FUN_MP', prop), tag), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''SubjectCON_FUN_MP'', prop) does not work.')
	 
		assert(strcmp(SubjectCON_FUN_MP.getPropTag(tag), tag), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'SubjectCON_FUN_MP.getPropTag(tag) does not work.')
		assert(strcmp(sub.getPropTag(tag), tag), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'sub.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(sub, tag), tag), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(sub, tag) does not work.')
		assert(strcmp(Element.getPropTag('SubjectCON_FUN_MP', prop), tag), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''SubjectCON_FUN_MP'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:SubjectCON_FUN_MP.getPropNumber()
		tag = sub.getPropTag(prop);
	 
		assert(Category.existsCategory(SubjectCON_FUN_MP.getPropCategory(prop)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'SubjectCON_FUN_MP.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(sub.getPropCategory(prop)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'sub.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(sub, prop)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(sub, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(sub, prop)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''SubjectCON_FUN_MP'', prop) does not work.')
	 
		assert(Category.existsCategory(SubjectCON_FUN_MP.getPropCategory(tag)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'SubjectCON_FUN_MP.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(sub.getPropCategory(tag)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'sub.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(sub, tag)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(sub, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(sub, tag)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''SubjectCON_FUN_MP'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:SubjectCON_FUN_MP.getPropNumber()
		tag = sub.getPropTag(prop);
	 
		assert(Format.existsFormat(SubjectCON_FUN_MP.getPropFormat(prop)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'SubjectCON_FUN_MP.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(sub.getPropFormat(prop)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'sub.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(sub, prop)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(sub, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(sub, prop)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''SubjectCON_FUN_MP'', prop) does not work.')
	 
		assert(Format.existsFormat(SubjectCON_FUN_MP.getPropFormat(tag)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'SubjectCON_FUN_MP.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(sub.getPropFormat(tag)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'sub.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(sub, tag)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(sub, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(sub, tag)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''SubjectCON_FUN_MP'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:SubjectCON_FUN_MP.getPropNumber()
		tag = sub.getPropTag(prop);
	 
		assert(ischar(SubjectCON_FUN_MP.getPropDescription(prop)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'SubjectCON_FUN_MP.getPropDescription(prop) does not work.')
		assert(ischar(sub.getPropDescription(prop)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'sub.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(sub, prop)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(sub, prop) does not work.')
		assert(ischar(Element.getPropDescription(sub, prop)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''SubjectCON_FUN_MP'', prop) does not work.')
	 
		assert(ischar(SubjectCON_FUN_MP.getPropDescription(tag)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'SubjectCON_FUN_MP.getPropDescription(tag) does not work.')
		assert(ischar(sub.getPropDescription(tag)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'sub.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(sub, tag)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(sub, tag) does not work.')
		assert(ischar(Element.getPropDescription(sub, tag)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''SubjectCON_FUN_MP'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:SubjectCON_FUN_MP.getPropNumber()
		tag = sub.getPropTag(prop);
	 
		settings = SubjectCON_FUN_MP.getPropSettings(prop);
		settings = sub.getPropSettings(prop);
		settings = Element.getPropSettings(sub, prop);
		settings = Element.getPropSettings('SubjectCON_FUN_MP', prop);
	 
		settings = SubjectCON_FUN_MP.getPropSettings(tag);
		settings = sub.getPropSettings(tag);
		settings = Element.getPropSettings(sub, tag);
		settings = Element.getPropSettings('SubjectCON_FUN_MP', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:SubjectCON_FUN_MP.getPropNumber()
		tag = sub.getPropTag(prop);
	 
		default = SubjectCON_FUN_MP.getPropDefault(prop);
		default = sub.getPropDefault(prop);
		default = Element.getPropDefault(sub, prop);
		default = Element.getPropDefault('SubjectCON_FUN_MP', prop);
	 
		default = SubjectCON_FUN_MP.getPropDefault(tag);
		default = sub.getPropDefault(tag);
		default = Element.getPropDefault(sub, tag);
		default = Element.getPropDefault('SubjectCON_FUN_MP', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:SubjectCON_FUN_MP.getPropNumber()
		tag = sub.getPropTag(prop);
	 
		conditioned_default = SubjectCON_FUN_MP.getPropDefaultConditioned(prop);
		conditioned_default = sub.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(sub, prop);
		conditioned_default = Element.getPropDefaultConditioned('SubjectCON_FUN_MP', prop);
	 
		conditioned_default = SubjectCON_FUN_MP.getPropDefaultConditioned(tag);
		conditioned_default = sub.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(sub, tag);
		conditioned_default = Element.getPropDefaultConditioned('SubjectCON_FUN_MP', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:SubjectCON_FUN_MP.getPropNumber()
		tag = sub.getPropTag(prop);
	 
		assert(~SubjectCON_FUN_MP.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'SubjectCON_FUN_MP.checkProp(prop, value) does not work.')
		assert(~sub.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'sub.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(sub, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(sub, prop, value) does not work.')
		assert(~Element.checkProp('SubjectCON_FUN_MP', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''SubjectCON_FUN_MP'', prop, value) does not work.')
	 
		assert_with_error('SubjectCON_FUN_MP.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.WRONG_INPUT], prop, sub)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.WRONG_INPUT], prop, sub)
		assert_with_error('Element.checkProp(''SubjectCON_FUN_MP'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~SubjectCON_FUN_MP.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'SubjectCON_FUN_MP.checkProp(tag, value) does not work.')
		assert(~sub.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'sub.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(sub, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(sub, tag, value) does not work.')
		assert(~Element.checkProp('SubjectCON_FUN_MP', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''SubjectCON_FUN_MP'', tag, value) does not work.')
	 
		assert_with_error('SubjectCON_FUN_MP.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.WRONG_INPUT], tag, sub)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.WRONG_INPUT], tag, sub)
		assert_with_error('Element.checkProp(''SubjectCON_FUN_MP'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(SubjectCON_FUN_MP.checkProp(prop, Element.getPropDefaultConditioned(SubjectCON_FUN_MP, prop)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'SubjectCON_FUN_MP.checkProp(prop, <conditioned default value>) does not work.')
		assert(sub.checkProp(prop, Element.getPropDefaultConditioned(SubjectCON_FUN_MP, prop)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'sub.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(sub, prop, Element.getPropDefaultConditioned(SubjectCON_FUN_MP, prop)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(sub, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('SubjectCON_FUN_MP', prop, Element.getPropDefaultConditioned(SubjectCON_FUN_MP, prop)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''SubjectCON_FUN_MP'', prop, <conditioned default value>) does not work.')
	 
		assert(SubjectCON_FUN_MP.checkProp(tag, Element.getPropDefaultConditioned(SubjectCON_FUN_MP, prop)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'SubjectCON_FUN_MP.checkProp(tag, <conditioned default value>) does not work.')
		assert(sub.checkProp(tag, Element.getPropDefaultConditioned(SubjectCON_FUN_MP, prop)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'sub.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(sub, tag, Element.getPropDefaultConditioned(SubjectCON_FUN_MP, prop)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(sub, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('SubjectCON_FUN_MP', tag, Element.getPropDefaultConditioned(SubjectCON_FUN_MP, prop)), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''SubjectCON_FUN_MP'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	sub = SubjectCON_FUN_MP( ...
		SubjectCON_FUN_MP.ELCLASS, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.NAME, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.DESCRIPTION, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.TEMPLATE, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.TEMPLATE), ...
		SubjectCON_FUN_MP.ID, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.ID), ...
		SubjectCON_FUN_MP.LABEL, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.LABEL), ...
		SubjectCON_FUN_MP.NOTES, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.NOTES), ...
		SubjectCON_FUN_MP.TOSTRING, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.VOI_DICT, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.VOI_DICT), ...
		SubjectCON_FUN_MP.BA, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.BA), ...
		SubjectCON_FUN_MP.CON, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.CON), ...
		SubjectCON_FUN_MP.FUN, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.FUN) ...
		);
	 
	for prop = 1:1:SubjectCON_FUN_MP.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(SubjectCON_FUN_MP.getPropTag(prop));
		switch SubjectCON_FUN_MP.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					sub.getr(prop) == SubjectCON_FUN_MP.getNoValue(), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['Being a ' SubjectCON_FUN_MP.getCategoryName(SubjectCON_FUN_MP.getPropCategory(prop)) ', SubjectCON_FUN_MP.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in SubjectCON_FUN_MP.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					sub.getr(TAG) == SubjectCON_FUN_MP.getNoValue(), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['Being a ' SubjectCON_FUN_MP.getCategoryName(SubjectCON_FUN_MP.getPropCategory(prop)) ', SubjectCON_FUN_MP.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in SubjectCON_FUN_MP.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(sub.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(sub.getPropSettings(prop))
					assert( ...
						sub.checkFormat(sub.getPropFormat(prop), sub.get(prop)), ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						['SubjectCON_FUN_MP.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						sub.checkFormat(sub.getPropFormat(prop), sub.get(prop), sub.getPropSettings(prop)), ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						['SubjectCON_FUN_MP.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					sub.getr(prop) == SubjectCON_FUN_MP.getNoValue(), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['Being a ' SubjectCON_FUN_MP.getCategoryName(SubjectCON_FUN_MP.getPropCategory(prop)) ', SubjectCON_FUN_MP.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in SubjectCON_FUN_MP.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					sub.getr(TAG) == SubjectCON_FUN_MP.getNoValue(), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['Being a ' SubjectCON_FUN_MP.getCategoryName(SubjectCON_FUN_MP.getPropCategory(prop)) ', SubjectCON_FUN_MP.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in SubjectCON_FUN_MP.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':SubjectCON_FUN_MP']);
				assert( ...
					~isa(sub.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(sub.getPropSettings(prop))
					assert( ...
						sub.checkFormat(sub.getPropFormat(prop), sub.get(prop)), ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						['SubjectCON_FUN_MP.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						sub.checkFormat(sub.getPropFormat(prop), sub.get(prop), sub.getPropSettings(prop)), ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						['SubjectCON_FUN_MP.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(sub.getr(prop), SubjectCON_FUN_MP.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by SubjectCON_FUN_MP.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in SubjectCON_FUN_MP.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(sub.getr(TAG), SubjectCON_FUN_MP.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.getr(' TAG ') must be inizialized to its default value ' ...
					'given by SubjectCON_FUN_MP.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in SubjectCON_FUN_MP.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	sub = SubjectCON_FUN_MP( ...
		SubjectCON_FUN_MP.ELCLASS, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.NAME, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.DESCRIPTION, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.TEMPLATE, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.TEMPLATE), ...
		SubjectCON_FUN_MP.ID, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.ID), ...
		SubjectCON_FUN_MP.LABEL, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.LABEL), ...
		SubjectCON_FUN_MP.NOTES, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.NOTES), ...
		SubjectCON_FUN_MP.TOSTRING, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.VOI_DICT, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.VOI_DICT), ...
		SubjectCON_FUN_MP.BA, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.BA), ...
		SubjectCON_FUN_MP.CON, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.CON), ...
		SubjectCON_FUN_MP.FUN, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.FUN) ...
		);
	 
	for prop = 1:1:SubjectCON_FUN_MP.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(SubjectCON_FUN_MP.getPropTag(prop));
		switch SubjectCON_FUN_MP.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(sub.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(sub.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(sub.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(sub.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					sub.checkFormat(sub.getPropFormat(prop), sub.getr(prop),sub.getPropSettings(prop)), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':SubjectCON_FUN_MP']);
				assert( ...
					~isa(sub.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(sub.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':SubjectCON_FUN_MP']);
	% 			assert( ...
	% 				~isa(sub.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
	% 				['SubjectCON_FUN_MP.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(sub.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
	% 				['SubjectCON_FUN_MP.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				sub.checkFormat(sub.getPropFormat(prop), sub.getr(prop),sub.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
	% 				['SubjectCON_FUN_MP.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':SubjectCON_FUN_MP']);
				assert( ...
					~isa(sub.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(sub.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(sub.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(sub.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					sub.checkFormat(sub.getPropFormat(prop), sub.getr(prop),sub.getPropSettings(prop)), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if sub.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:SubjectCON_FUN_MP');
					delete(ancestor(sub.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(SubjectCON_FUN_MP.getProps(Category.RESULT))
		for prop = 1:1:SubjectCON_FUN_MP.getPropNumber()
	 
			% excluded props
			if any(prop == [])
				continue
			end
	 
			switch SubjectCON_FUN_MP.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						sub.isLocked(prop), ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						['SubjectCON_FUN_MP.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~sub.isLocked(prop), ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						['SubjectCON_FUN_MP.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	sub = SubjectCON_FUN_MP();
	 
	for prop = 1:1:SubjectCON_FUN_MP.getPropNumber()
		TAG = upper(SubjectCON_FUN_MP.getPropTag(prop));
		assert( ...
			~sub.isLocked(prop), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			['SubjectCON_FUN_MP.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~sub.isLocked(TAG), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			['SubjectCON_FUN_MP.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	sub.lock()
	 
	for prop = 1:1:SubjectCON_FUN_MP.getPropNumber()
		switch SubjectCON_FUN_MP.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					sub.isLocked(prop), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~sub.isLocked(prop), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	sub = SubjectCON_FUN_MP();
	 
	warning_backup = warning('off', 'BRAPH2:SubjectCON_FUN_MP');
	for prop = 1:1:SubjectCON_FUN_MP.getPropNumber()
		sub.lock(prop)
		switch SubjectCON_FUN_MP.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					sub.isLocked(prop), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~sub.isLocked(prop), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	sub = SubjectCON_FUN_MP();
	 
	for prop = 1:1:SubjectCON_FUN_MP.getPropNumber()
		TAG = upper(SubjectCON_FUN_MP.getPropTag(prop));
		assert( ...
			sub.isChecked(prop), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			['SubjectCON_FUN_MP.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			sub.isChecked(TAG), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			['SubjectCON_FUN_MP.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	sub.unchecked()
	 
	for prop = 1:1:SubjectCON_FUN_MP.getPropNumber()
		assert( ...
			~sub.isChecked(prop), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			['SubjectCON_FUN_MP.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	sub.checked()
	 
	for prop = 1:1:SubjectCON_FUN_MP.getPropNumber()
		assert( ...
			sub.isChecked(prop), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			['SubjectCON_FUN_MP.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic SubjectCON_FUN_MP
	sub_0 = SubjectCON_FUN_MP( ...
		SubjectCON_FUN_MP.ELCLASS, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.NAME, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.DESCRIPTION, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.TEMPLATE, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.TEMPLATE), ...
		SubjectCON_FUN_MP.ID, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.ID), ...
		SubjectCON_FUN_MP.LABEL, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.LABEL), ...
		SubjectCON_FUN_MP.NOTES, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.NOTES), ...
		SubjectCON_FUN_MP.TOSTRING, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.VOI_DICT, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.VOI_DICT), ...
		SubjectCON_FUN_MP.BA, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.BA), ...
		SubjectCON_FUN_MP.CON, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.CON), ...
		SubjectCON_FUN_MP.FUN, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.FUN) ...
		);
	 
	% SubjectCON_FUN_MP with 1st callbacks
	sub_1 = SubjectCON_FUN_MP( ...
		SubjectCON_FUN_MP.ELCLASS, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.NAME, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.DESCRIPTION, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.TEMPLATE, sub_0.getCallback(4), ..., ...
		SubjectCON_FUN_MP.ID, sub_0.getCallback(5), ..., ...
		SubjectCON_FUN_MP.LABEL, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.LABEL), ...
		SubjectCON_FUN_MP.NOTES, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.NOTES), ...
		SubjectCON_FUN_MP.TOSTRING, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.VOI_DICT, sub_0.getCallback(9), ..., ...
		SubjectCON_FUN_MP.BA, sub_0.getCallback(10), ..., ...
		SubjectCON_FUN_MP.CON, sub_0.getCallback(11), ..., ...
		SubjectCON_FUN_MP.FUN, sub_0.getCallback(12) ... ...
		);
	 
	prop_number = SubjectCON_FUN_MP.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(SubjectCON_FUN_MP.getPropTag(prop));
		switch SubjectCON_FUN_MP.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(sub_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(sub_1.get(prop), sub_0.get(prop)) && ~isa(sub_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(sub_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% SubjectCON_FUN_MP with 2nd callbacks
	sub_2 = SubjectCON_FUN_MP( ...
		SubjectCON_FUN_MP.ELCLASS, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.NAME, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.DESCRIPTION, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.TEMPLATE, sub_1.getCallback(4), ..., ...
		SubjectCON_FUN_MP.ID, sub_1.getCallback(5), ..., ...
		SubjectCON_FUN_MP.LABEL, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.LABEL), ...
		SubjectCON_FUN_MP.NOTES, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.NOTES), ...
		SubjectCON_FUN_MP.TOSTRING, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.VOI_DICT, sub_1.getCallback(9), ..., ...
		SubjectCON_FUN_MP.BA, sub_1.getCallback(10), ..., ...
		SubjectCON_FUN_MP.CON, sub_1.getCallback(11), ..., ...
		SubjectCON_FUN_MP.FUN, sub_1.getCallback(12) ... ...
		);
	 
	prop_number = SubjectCON_FUN_MP.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(SubjectCON_FUN_MP.getPropTag(prop));
		switch SubjectCON_FUN_MP.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(sub_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(sub_2.get(prop), sub_0.get(prop)) && ~isa(sub_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(sub_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% SubjectCON_FUN_MP with 3rd callbacks
	sub_3 = SubjectCON_FUN_MP( ...
		SubjectCON_FUN_MP.ELCLASS, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.NAME, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.DESCRIPTION, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.TEMPLATE, sub_2.getCallback(4), ..., ...
		SubjectCON_FUN_MP.ID, sub_2.getCallback(5), ..., ...
		SubjectCON_FUN_MP.LABEL, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.LABEL), ...
		SubjectCON_FUN_MP.NOTES, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.NOTES), ...
		SubjectCON_FUN_MP.TOSTRING, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.VOI_DICT, sub_2.getCallback(9), ..., ...
		SubjectCON_FUN_MP.BA, sub_2.getCallback(10), ..., ...
		SubjectCON_FUN_MP.CON, sub_2.getCallback(11), ..., ...
		SubjectCON_FUN_MP.FUN, sub_2.getCallback(12) ... ...
		);
	 
	prop_number = SubjectCON_FUN_MP.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(SubjectCON_FUN_MP.getPropTag(prop));
		switch SubjectCON_FUN_MP.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(sub_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(sub_3.get(prop), sub_0.get(prop)) && ~isa(sub_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(sub_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	sub = SubjectCON_FUN_MP();
	 
	sub_copy = sub.copy();
	 
	assert(sub_copy ~= sub, ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'SubjectCON_FUN_MP.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(sub_copy, sub), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'SubjectCON_FUN_MP.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:SubjectCON_FUN_MP.getPropNumber()
		value = sub.getr(prop);
		value_copy = sub_copy.getr(prop);
		switch SubjectCON_FUN_MP.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					'SubjectCON_FUN_MP.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						'SubjectCON_FUN_MP.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						'SubjectCON_FUN_MP.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						'SubjectCON_FUN_MP.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
							'SubjectCON_FUN_MP.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
							'SubjectCON_FUN_MP.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						'SubjectCON_FUN_MP.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					sub_copy.isLocked(prop) == sub.isLocked(prop), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					'SubjectCON_FUN_MP.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					sub_copy.isChecked(prop) == sub.isChecked(prop), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					'SubjectCON_FUN_MP.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					sub_copy.getPropSeed(prop) == sub.getPropSeed(prop), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					'SubjectCON_FUN_MP.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	sub = SubjectCON_FUN_MP( ...
		SubjectCON_FUN_MP.ELCLASS, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.NAME, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.DESCRIPTION, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.TEMPLATE, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.TEMPLATE), ...
		SubjectCON_FUN_MP.ID, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.ID), ...
		SubjectCON_FUN_MP.LABEL, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.LABEL), ...
		SubjectCON_FUN_MP.NOTES, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.NOTES), ...
		SubjectCON_FUN_MP.TOSTRING, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.VOI_DICT, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.VOI_DICT), ...
		SubjectCON_FUN_MP.BA, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.BA), ...
		SubjectCON_FUN_MP.CON, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.CON), ...
		SubjectCON_FUN_MP.FUN, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.FUN) ...
		);
	 
	for prop = 1:1:SubjectCON_FUN_MP.getPropNumber()
		if SubjectCON_FUN_MP.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':SubjectCON_FUN_MP']);
			% sub.memorize(prop);
			% warning(warning_backup)
		elseif SubjectCON_FUN_MP.getPropCategory(prop) == Category.EVANESCENT && sub.getPropFormat(prop) == Format.HANDLE
			sub.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:SubjectCON_FUN_MP');
			delete(ancestor(sub.get(prop), 'figure'))
			warning(warning_backup)
		else
			sub.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	sub_copy = sub.copy();
	 
	for prop = 1:1:SubjectCON_FUN_MP.getPropNumber()
		value = sub.getr(prop);
		value_copy = sub_copy.getr(prop);
		switch SubjectCON_FUN_MP.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					'SubjectCON_FUN_MP.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						'SubjectCON_FUN_MP.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						'SubjectCON_FUN_MP.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						'SubjectCON_FUN_MP.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
							'SubjectCON_FUN_MP.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
							'SubjectCON_FUN_MP.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						'SubjectCON_FUN_MP.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						sub_copy.isLocked(prop) == sub.isLocked(prop), ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						'SubjectCON_FUN_MP.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						sub_copy.isChecked(prop) == sub.isChecked(prop), ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						'SubjectCON_FUN_MP.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						sub_copy.getPropSeed(prop) == sub.getPropSeed(prop), ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						'SubjectCON_FUN_MP.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	sub_0 = SubjectCON_FUN_MP( ...
		SubjectCON_FUN_MP.ELCLASS, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.NAME, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.DESCRIPTION, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.TEMPLATE, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.TEMPLATE), ...
		SubjectCON_FUN_MP.ID, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.ID), ...
		SubjectCON_FUN_MP.LABEL, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.LABEL), ...
		SubjectCON_FUN_MP.NOTES, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.NOTES), ...
		SubjectCON_FUN_MP.TOSTRING, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.VOI_DICT, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.VOI_DICT), ...
		SubjectCON_FUN_MP.BA, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.BA), ...
		SubjectCON_FUN_MP.CON, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.CON), ...
		SubjectCON_FUN_MP.FUN, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.FUN) ...
		);
	 
	sub = SubjectCON_FUN_MP( ...
		SubjectCON_FUN_MP.ELCLASS, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.NAME, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.DESCRIPTION, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.TEMPLATE, sub_0.getCallback(4), ..., ...
		SubjectCON_FUN_MP.ID, sub_0.getCallback(5), ..., ...
		SubjectCON_FUN_MP.LABEL, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.LABEL), ...
		SubjectCON_FUN_MP.NOTES, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.NOTES), ...
		SubjectCON_FUN_MP.TOSTRING, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.VOI_DICT, sub_0.getCallback(9), ..., ...
		SubjectCON_FUN_MP.BA, sub_0.getCallback(10), ..., ...
		SubjectCON_FUN_MP.CON, sub_0.getCallback(11), ..., ...
		SubjectCON_FUN_MP.FUN, sub_0.getCallback(12) ... ...
		);
	 
	sub_copy = sub.copy();
	sub_0_copy = sub_copy.getr('ID').get('EL');
	 
	for prop = 1:1:SubjectCON_FUN_MP.getPropNumber()
		value = sub.getr(prop);
		value_copy = sub_copy.getr(prop);
		switch SubjectCON_FUN_MP.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					'SubjectCON_FUN_MP.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						'SubjectCON_FUN_MP.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						'SubjectCON_FUN_MP.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						'SubjectCON_FUN_MP.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
							'SubjectCON_FUN_MP.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
							'SubjectCON_FUN_MP.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						'SubjectCON_FUN_MP.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == sub_0.getCallback(prop), ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						'SubjectCON_FUN_MP.copy() does not work. The callback should be obtained from SubjectCON_FUN_MP.getCallback().' ...
						)
					assert( ...
						value_copy == sub_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						'SubjectCON_FUN_MP.copy() does not work. The callback should be obtained from SubjectCON_FUN_MP.getCallback().' ...
						)
				end
	 
					assert( ...
						sub_copy.isLocked(prop) == sub.isLocked(prop), ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						'SubjectCON_FUN_MP.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						sub_copy.isChecked(prop) == sub.isChecked(prop), ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						'SubjectCON_FUN_MP.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						sub_copy.getPropSeed(prop) == sub.getPropSeed(prop), ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						'SubjectCON_FUN_MP.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	sub_template = SubjectCON_FUN_MP();
	sub = SubjectCON_FUN_MP('TEMPLATE', sub_template);
	 
	for prop = 1:1:SubjectCON_FUN_MP.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(SubjectCON_FUN_MP.getPropTag(prop));
		switch SubjectCON_FUN_MP.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == SubjectCON_FUN_MP.TEMPLATE
					assert( ...
						isa(sub.getr(prop), 'SubjectCON_FUN_MP'), ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						'SubjectCON_FUN_MP TEMPLATE does not work. SubjectCON_FUN_MP.getr(''TEMPLATE'') should be a SubjectCON_FUN_MP element.' ...
						)
					assert( ...
						isa(sub_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						'SubjectCON_FUN_MP TEMPLATE does not work. SubjectCON_FUN_MP_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(sub.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						['SubjectCON_FUN_MP TEMPLATE does not work. SubjectCON_FUN_MP.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						sub.getr(prop).get('EL') == sub_template && sub.getr(prop).get('PROP') == prop && strcmp(sub.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						['SubjectCON_FUN_MP TEMPLATE does not work. SubjectCON_FUN_MP.getr(' TAG ') should be a Callback to sub_template.' TAG '.'] ...
						)
					assert( ...
						isa(sub_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
						['SubjectCON_FUN_MP TEMPLATE does not work. SubjectCON_FUN_MP_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(sub.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP TEMPLATE does not work. SubjectCON_FUN_MP.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(sub_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
					['SubjectCON_FUN_MP TEMPLATE does not work. SubjectCON_FUN_MP_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	sub = SubjectCON_FUN_MP( ...
		SubjectCON_FUN_MP.ELCLASS, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.NAME, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.DESCRIPTION, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.TEMPLATE, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.TEMPLATE), ...
		SubjectCON_FUN_MP.ID, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.ID), ...
		SubjectCON_FUN_MP.LABEL, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.LABEL), ...
		SubjectCON_FUN_MP.NOTES, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.NOTES), ...
		SubjectCON_FUN_MP.TOSTRING, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.VOI_DICT, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.VOI_DICT), ...
		SubjectCON_FUN_MP.BA, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.BA), ...
		SubjectCON_FUN_MP.CON, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.CON), ...
		SubjectCON_FUN_MP.FUN, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.FUN) ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'subjectcon_fun_mp_to_be_erased.b2'];
	 
	Element.save(sub, filename)
	 
	sub_loaded = Element.load(filename);
	 
	assert( ...
		isequal(sub.copy(), sub_loaded), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'SubjectCON_FUN_MP.save(sub) and/or SubjectCON_FUN_MP.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	sub = SubjectCON_FUN_MP( ...
		SubjectCON_FUN_MP.ELCLASS, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.NAME, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.DESCRIPTION, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.TEMPLATE, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.TEMPLATE), ...
		SubjectCON_FUN_MP.ID, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.ID), ...
		SubjectCON_FUN_MP.LABEL, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.LABEL), ...
		SubjectCON_FUN_MP.NOTES, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.NOTES), ...
		SubjectCON_FUN_MP.TOSTRING, SubjectCON_FUN_MP.getNoValue(), ...
		SubjectCON_FUN_MP.VOI_DICT, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.VOI_DICT), ...
		SubjectCON_FUN_MP.BA, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.BA), ...
		SubjectCON_FUN_MP.CON, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.CON), ...
		SubjectCON_FUN_MP.FUN, SubjectCON_FUN_MP.getPropDefault(SubjectCON_FUN_MP.FUN) ...
		);
	 
	[json, struct, el_list] = encodeJSON(sub);
	[sub_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(sub_dec ~= sub, ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		'SubjectCON_FUN_MP.encodeJSON() or SubjectCON_FUN_MP.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) SubjectCON_FUN_MP.getPropFormat(prop), num2cell(SubjectCON_FUN_MP.getProps())) == Format.HANDLE) && all(cellfun(@(prop) SubjectCON_FUN_MP.getPropFormat(prop), num2cell(SubjectCON_FUN_MP.getProps())) == Format.NET)
		assert(isequal(sub_dec, sub), ...
			[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
			'SubjectCON_FUN_MP.encodeJSON() or SubjectCON_FUN_MP.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: GUI
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	im_ba = ImporterBrainAtlasXLS('FILE', 'desikan_atlas.xlsx');
	ba = im_ba.get('BA');
	
	gr = Group('SUB_CLASS', 'SubjectCON_FUN_MP', 'SUB_DICT', IndexedDictionary('IT_CLASS', 'SubjectCON_FUN_MP'));
	for i = 1:1:50
	    sub = SubjectCON_FUN_MP( ...
	        'ID', ['SUB CON ' int2str(i)], ...
	        'LABEL', ['Subejct CON ' int2str(i)], ...
	        'NOTES', ['Notes on subject CON ' int2str(i)], ...
	        'BA', ba, ...
	        'CON', rand(ba.get('BR_DICT').get('LENGTH')), ...
	        'FUN', rand(10, ba.get('BR_DICT').get('LENGTH')) ...
	        );
	    sub.memorize('VOI_DICT').get('ADD', VOINumeric('ID', 'Age', 'V', 100 * rand()))
	    sub.memorize('VOI_DICT').get('ADD', VOICategoric('ID', 'Sex', 'CATEGORIES', {'Female', 'Male'}, 'V', randi(2, 1)))
	    gr.get('SUB_DICT').get('ADD', sub)
	end
	
	gui = GUIElement('PE', gr, 'CLOSEREQ', false);
	gui.get('DRAW')
	gui.get('SHOW')
	
	gui.get('CLOSE')
end

%% Test 13: Create example files XLS
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	create_data_CON_FUN_MP_XLS() % only creates files if the example folder doesn't already exist
end

%% Test 14: Create example files TXT
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	create_data_CON_FUN_MP_TXT() % only creates files if the example folder doesn't already exist
end

%% Test 15: GUI XLS
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	im_ba = ImporterBrainAtlasXLS('FILE', [fileparts(which('SubjectCON_FUN_MP')) filesep 'Example data CON_FUN_MP XLS' filesep 'atlas.xlsx']);
	ba = im_ba.get('BA');
	
	im_gr_CON = ImporterGroupSubjectCON_XLS( ...
	    'DIRECTORY', [fileparts(which('SubjectCON_FUN_MP')) filesep 'Example data CON_FUN_MP XLS' filesep 'CON_FUN_MP_Group_1_XLS.CON'], ...
	    'BA', ba, ...
	    'WAITBAR', true ...
	    );
	gr_CON = im_gr_CON.get('GR');
	
	gui_CON = GUIElement('PE', gr_CON, 'CLOSEREQ', false);
	gui_CON.get('DRAW')
	gui_CON.get('SHOW')
	
	gui_CON.get('CLOSE')
	
	im_gr_FUN = ImporterGroupSubjectFUN_XLS( ...
	    'DIRECTORY', [fileparts(which('SubjectCON_FUN_MP')) filesep 'Example data CON_FUN_MP XLS' filesep 'CON_FUN_MP_Group_1_XLS.FUN'], ...
	    'BA', ba, ...
	    'WAITBAR', true ...
	    );
	gr_FUN = im_gr_FUN.get('GR');
	
	gui_FUN = GUIElement('PE', gr_FUN, 'CLOSEREQ', false);
	gui_FUN.get('DRAW')
	gui_FUN.get('SHOW')
	
	gui_FUN.get('CLOSE')
end

%% Test 16: GUI TXT
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	im_ba = ImporterBrainAtlasTXT('FILE', [fileparts(which('SubjectCON_FUN_MP')) filesep 'Example data CON_FUN_MP TXT' filesep 'atlas.txt']);
	ba = im_ba.get('BA');
	
	im_gr_CON = ImporterGroupSubjectCON_TXT( ...
	    'DIRECTORY', [fileparts(which('SubjectCON_FUN_MP')) filesep 'Example data CON_FUN_MP TXT' filesep 'CON_FUN_MP_Group_1_TXT.CON'], ...
	    'BA', ba, ...
	    'WAITBAR', true ...
	    );
	gr_CON = im_gr_CON.get('GR');
	
	gui_CON = GUIElement('PE', gr_CON, 'CLOSEREQ', false);
	gui_CON.get('DRAW')
	gui_CON.get('SHOW')
	
	gui_CON.get('CLOSE')
	
	im_gr_FUN = ImporterGroupSubjectFUN_TXT( ...
	    'DIRECTORY', [fileparts(which('SubjectCON_FUN_MP')) filesep 'Example data CON_FUN_MP TXT' filesep 'CON_FUN_MP_Group_1_TXT.FUN'], ...
	    'BA', ba, ...
	    'WAITBAR', true ...
	    );
	gr_FUN = im_gr_FUN.get('GR');
	
	gui_FUN = GUIElement('PE', gr_FUN, 'CLOSEREQ', false);
	gui_FUN.get('DRAW')
	gui_FUN.get('SHOW')
	
	gui_FUN.get('CLOSE')
end

%% Test 17: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':SubjectCON_FUN_MP:' BRAPH2.FAIL_TEST], ...
		[' When testing SubjectCON_FUN_MP no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 18: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

%% Test functions
function h = WattsStrogatz(N,K,beta)
% H = WattsStrogatz(N,K,beta) returns a Watts-Strogatz model graph with N
% nodes, N*K edges, mean node degree 2*K, and rewiring probability beta.
%
% beta = 0 is a ring lattice, and beta = 1 is a random graph.

% Connect each node to its K next and previous neighbors. This constructs
% indices for a ring lattice.
s = repelem((1:N)',1,K);
t = s + repmat(1:K,N,1);
t = mod(t-1,N)+1;

% Rewire the target node of each edge with probability beta
for source=1:N
    switchEdge = rand(K, 1) < beta;
    
    newTargets = rand(N, 1);
    newTargets(source) = 0;
    newTargets(s(t==source)) = 0;
    newTargets(t(source, ~switchEdge)) = 0;
    
    [~, ind] = sort(newTargets, 'descend');
    t(source, switchEdge) = ind(1:nnz(switchEdge));
end

h = graph(s,t);
end
