% Script example workflow Functional WU
clear
%#ok<*NOPTS>

%% Load BrainAtlas
[file, path, filterindex] = uigetfile('*.xlsx');
if filterindex
    atlas_file = fullfile(path, file);
else
    atlas_file = [fileparts(which('example_FUN.m')) filesep() 'example data FUN (fMRI)' filesep() 'desikan_atlas.xlsx'];
end
clear file filterindex path

im = ImporterBrainAtlasXLS('File', atlas_file);
ba_loaded = im.get('BA');

disp(['Loaded BrainAtlas: ' ba_loaded.tostring()])
%%
sub_class = 'SubjectFUN';
input_rule = 'FUN';
input_data = rand(ba_loaded.get('BR_DICT').length(), 10);
save_dir_rule = 'Directory';
save_dir_path = [fileparts(which('test_braph2')) filesep 'trial_cohort_to_be_erased'];
sub1 = SubjectFUN( ...
    'ID', 'SUB FUN 1', ...
    'LABEL', 'Subejct FUN 1', ...
    'NOTES', 'Notes on subject FUN 1', ...
    'BA', ba_loaded, ...
    'FUN', input_data ...
    );
sub2 = SubjectFUN( ...
    'ID', 'SUB FUN 2', ...
    'LABEL', 'Subejct FUN 2', ...
    'NOTES', 'Notes on subject FUN 2', ...
    'BA', ba_loaded, ...
    'FUN', input_data ...
    );
sub3 = SubjectFUN( ...
    'ID', 'SUB FUN 3', ...
    'LABEL', 'Subejct FUN 3', ...
    'NOTES', 'Notes on subject FUN 3', ...
    'BA', ba_loaded, ...
    'FUN', input_data ...
    );
sub4 = SubjectFUN( ...
    'ID', 'SUB FUN 4', ...
    'LABEL', 'Subejct FUN 4', ...
    'NOTES', 'Notes on subject FUN 4', ...
    'BA', ba_loaded, ...
    'FUN', input_data ...
    );
sub5 = SubjectFUN( ...
    'ID', 'SUB FUN 5', ...
    'LABEL', 'Subejct FUN 5', ...
    'NOTES', 'Notes on subject FUN 5', ...
    'BA', ba_loaded, ...
    'FUN', input_data ...
    );

gr = Group( ...
    'ID', 'GR FUN', ...
    'LABEL', 'Group label', ...
    'NOTES', 'Group notes', ...
    'SUB_CLASS', 'SubjectFUN', ...
    'SUB_DICT', IndexedDictionary('IT_CLASS', 'SubjectFUN', 'IT_KEY', 1, 'IT_LIST', {sub1, sub2, sub3, sub4, sub5}) ...
    );

ex = ExporterGroupSubjectFUNTXT( ...
    'DIRECTORY', save_dir_path, ...
    'GR', gr ...
    );

ex.get('SAVE');

%% Load FNC Subject Data for group 1
[file, path, filterindex] = uigetfile('.xlsx');
if filterindex
    group1_file = fullfile(path, file);
else
    group1_file = [fileparts(which('example_FUN.m')) filesep() 'example data FNC (fMRI)'  filesep() 'xls' filesep() 'GroupName1'];
end
clear file path filterindex;

im1 = ImporterGroupSubjectFUNXLS( ...
    'DIRECTORY', group1_file, ...
    'BA', ba_loaded ...
    );

gr_loaded1 = im1.get('GR');

disp(['Loaded Group 1: ' gr_loaded1.tostring()])

%% Load FNC Subject Data for group 2
[file, path, filterindex] = uigetfile('.xlsx');
if filterindex
    group2_file = fullfile(path, file);
else
    group2_file = [fileparts(which('example_FUN.m')) filesep() 'example data FNC (fMRI)'  filesep() 'xls' filesep() 'GroupName2'];
end
clear file path filterindex;

im2 = ImporterGroupSubjectFUNXLS( ...
    'DIRECTORY', group2_file, ...
    'BA', ba_loaded ...
    );

gr_loaded2 = im2.get('GR');

disp(['Loaded Group 2: ' gr_loaded2.tostring()])
