%TEST_EXPORTERPIPELINEBRAPH2

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	ex = ExporterPipelineBRAPH2();
	 
	% get('ELCLASS')
	if isa(ExporterPipelineBRAPH2, 'ConcreteElement')
		assert(strcmp(ExporterPipelineBRAPH2().get('ELCLASS'), 'ExporterPipelineBRAPH2'), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ExporterPipelineBRAPH2().get(''ELCLASS'') should return ''ExporterPipelineBRAPH2''.')
	end
	 
	% getBuild()
	assert(ExporterPipelineBRAPH2.getBuild() == 1 && ExporterPipelineBRAPH2.getBuild() > 0, ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'ExporterPipelineBRAPH2.getBuild() should return the ExporterPipelineBRAPH2 build number.')
	assert(ex.getBuild() == 1 && ex.getBuild() > 0 , ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'ex.getBuild() should return the ExporterPipelineBRAPH2 build number.')
	assert(Element.getBuild(ex) == 1 && Element.getBuild(ex) > 0, ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(ex) should return the ExporterPipelineBRAPH2 build number.')
	assert(Element.getBuild('ExporterPipelineBRAPH2') == 1 && Element.getBuild('ExporterPipelineBRAPH2') > 0, ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''ExporterPipelineBRAPH2'') should return the ExporterPipelineBRAPH2 build number.')
	 
	% getClass()
	assert(strcmp(ExporterPipelineBRAPH2.getClass(), 'ExporterPipelineBRAPH2'), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'ExporterPipelineBRAPH2.getClass() should return ''ExporterPipelineBRAPH2''.')
	assert(strcmp(ex.getClass(), 'ExporterPipelineBRAPH2'), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'ex.getClass() should return ''ExporterPipelineBRAPH2''.')
	assert(strcmp(Element.getClass(ex), 'ExporterPipelineBRAPH2'), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(ex) should return ''ExporterPipelineBRAPH2''.')
	assert(strcmp(Element.getClass('ExporterPipelineBRAPH2'), 'ExporterPipelineBRAPH2'), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''ExporterPipelineBRAPH2'') should return ''ExporterPipelineBRAPH2''.')
	 
	% getSubclasses()
	assert(isequal(ExporterPipelineBRAPH2.getSubclasses(), subclasses('ExporterPipelineBRAPH2', [], [], true)), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'ExporterPipelineBRAPH2.getSubclasses() should return the same result as subclasses(''ExporterPipelineBRAPH2'', [], [], true).')
	assert(isequal(ex.getSubclasses(), subclasses('ExporterPipelineBRAPH2', [], [], true)), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''ExporterPipelineBRAPH2'', [], [], true).')
	assert(isequal(Element.getSubclasses(ex), subclasses('ExporterPipelineBRAPH2', [], [], true)), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(ex) should return the same result as subclasses(''ExporterPipelineBRAPH2'', [], [], true).')
	assert(isequal(Element.getSubclasses('ExporterPipelineBRAPH2'), subclasses('ExporterPipelineBRAPH2', [], [], true)), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''ExporterPipelineBRAPH2'') should return the same result as subclasses(''ExporterPipelineBRAPH2'', [], [], true).')
	 
	% getProps()
	assert(isempty(ExporterPipelineBRAPH2.getProps()) || isequal(ExporterPipelineBRAPH2.getProps(), 1:1:length(ExporterPipelineBRAPH2.getProps())), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'ExporterPipelineBRAPH2.getProps() should return a row vector [1:1:N].')
	assert(isempty(ExporterPipelineBRAPH2.getProps()) || isequal(ex.getProps(), 1:1:length(ExporterPipelineBRAPH2.getProps())), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'ex.getProps() should return a row vector [1:1:N].')
	assert(isempty(ExporterPipelineBRAPH2.getProps()) || isequal(Element.getProps(ex), 1:1:length(ExporterPipelineBRAPH2.getProps())), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(ex) should return a row vector [1:1:N].')
	assert(isempty(ExporterPipelineBRAPH2.getProps()) || isequal(Element.getProps('ExporterPipelineBRAPH2'), 1:1:length(ExporterPipelineBRAPH2.getProps())), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''ExporterPipelineBRAPH2'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) ExporterPipelineBRAPH2.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(ExporterPipelineBRAPH2.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ExporterPipelineBRAPH2.getProps())), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'ExporterPipelineBRAPH2.getProps(category) does not work.')
	tmp = cellfun(@(category) ex.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(ExporterPipelineBRAPH2.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ExporterPipelineBRAPH2.getProps())), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'ex.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(ex, category), categories, 'UniformOutput', false);
	assert(isempty(ExporterPipelineBRAPH2.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ExporterPipelineBRAPH2.getProps())), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(ex, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('ExporterPipelineBRAPH2', category), categories, 'UniformOutput', false);
	assert(isempty(ExporterPipelineBRAPH2.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ExporterPipelineBRAPH2.getProps())), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''ExporterPipelineBRAPH2'', category) does not work.')
	 
	% getPropNumber()
	assert(ExporterPipelineBRAPH2.getPropNumber() == length(ExporterPipelineBRAPH2.getProps()), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'ExporterPipelineBRAPH2.getPropNumber() should return the number of properties.')
	assert(ex.getPropNumber() == length(ExporterPipelineBRAPH2.getProps()), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'ex.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(ex) == length(ExporterPipelineBRAPH2.getProps()), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(ex) should return the number of properties.')
	assert(Element.getPropNumber('ExporterPipelineBRAPH2') == length(ExporterPipelineBRAPH2.getProps()), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''ExporterPipelineBRAPH2'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) ExporterPipelineBRAPH2.getPropNumber(category), categories)) == ExporterPipelineBRAPH2.getPropNumber(), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'ExporterPipelineBRAPH2.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) ex.getPropNumber(category), categories)) == ExporterPipelineBRAPH2.getPropNumber(), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'ex.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(ex, category), categories)) == ExporterPipelineBRAPH2.getPropNumber(), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(ex, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('ExporterPipelineBRAPH2', category), categories)) == ExporterPipelineBRAPH2.getPropNumber(), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''ExporterPipelineBRAPH2'', category) does not work.')
	 
	% existsProp(prop)
	assert(~ExporterPipelineBRAPH2.existsProp(NaN), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'ExporterPipelineBRAPH2.existsProp(prop) does not work.')
	assert(~ex.existsProp(NaN), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'ex.existsProp(prop) does not work.')
	assert(~Element.existsProp(ex, NaN), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(ex, prop) does not work.')
	assert(~Element.existsProp('ExporterPipelineBRAPH2', NaN), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''ExporterPipelineBRAPH2'', prop) does not work.')
	 
	assert_with_error('ExporterPipelineBRAPH2.existsProp(NaN)', [BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.WRONG_INPUT], ex)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.WRONG_INPUT], ex)
	assert_with_error('Element.existsProp(''ExporterPipelineBRAPH2'', NaN)', [BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:ExporterPipelineBRAPH2.getPropNumber()
		assert(ExporterPipelineBRAPH2.existsProp(prop), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ExporterPipelineBRAPH2.existsProp(prop) does not work.')
		assert(ex.existsProp(prop), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ex.existsProp(prop) does not work.')
		assert(Element.existsProp(ex, prop), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(ex, prop) does not work.')
		assert(Element.existsProp('ExporterPipelineBRAPH2', prop), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''ExporterPipelineBRAPH2'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~ExporterPipelineBRAPH2.existsTag(''), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'ExporterPipelineBRAPH2.existsTag(tag) does not work.')
	assert(~ex.existsTag(''), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'ex.existsTag(tag) does not work.')
	assert(~Element.existsTag(ex, ''), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(ex, tag) does not work.')
	assert(~Element.existsTag('ExporterPipelineBRAPH2', ''), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''ExporterPipelineBRAPH2'', tag) does not work.')
	 
	assert_with_error('ExporterPipelineBRAPH2.existsTag('''')', [BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.WRONG_INPUT], ex)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.WRONG_INPUT], ex)
	assert_with_error('Element.existsTag(''ExporterPipelineBRAPH2'', '''')', [BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:ExporterPipelineBRAPH2.getPropNumber()
		tag = ex.getPropTag(prop);
		assert(ExporterPipelineBRAPH2.existsTag(tag), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ExporterPipelineBRAPH2.existsTag(tag) does not work.')
		assert(ex.existsTag(tag), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ex.existsTag(tag) does not work.')
		assert(Element.existsTag(ex, tag), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(ex, tga) does not work.')
		assert(Element.existsTag('ExporterPipelineBRAPH2', tag), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''ExporterPipelineBRAPH2'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:ExporterPipelineBRAPH2.getPropNumber()
		assert(ExporterPipelineBRAPH2.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ExporterPipelineBRAPH2.getPropProp(prop) does not work.')
		assert(ex.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ex.getPropProp(prop) does not work.')
		assert(Element.getPropProp(ex, prop) == prop, ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(ex, prop) does not work.')
		assert(Element.getPropProp('ExporterPipelineBRAPH2', prop) == prop, ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''ExporterPipelineBRAPH2'', prop) does not work.')
	 
		tag = ex.getPropTag(prop);
		assert(ExporterPipelineBRAPH2.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ExporterPipelineBRAPH2.getPropProp(tag) does not work.')
		assert(ex.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ex.getPropProp(tag) does not work.')
		assert(Element.getPropProp(ex, tag) == prop, ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(ex, tag) does not work.')
		assert(Element.getPropProp('ExporterPipelineBRAPH2', prop) == prop, ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''ExporterPipelineBRAPH2'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:ExporterPipelineBRAPH2.getPropNumber()
		tag = ex.getPropTag(prop);
	 
		assert(strcmp(ExporterPipelineBRAPH2.getPropTag(prop), tag), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ExporterPipelineBRAPH2.getPropTag(prop) does not work.')
		assert(strcmp(ex.getPropTag(prop), tag), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ex.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(ex, prop), tag), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(ex, prop) does not work.')
		assert(strcmp(Element.getPropTag('ExporterPipelineBRAPH2', prop), tag), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''ExporterPipelineBRAPH2'', prop) does not work.')
	 
		assert(strcmp(ExporterPipelineBRAPH2.getPropTag(tag), tag), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ExporterPipelineBRAPH2.getPropTag(tag) does not work.')
		assert(strcmp(ex.getPropTag(tag), tag), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ex.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(ex, tag), tag), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(ex, tag) does not work.')
		assert(strcmp(Element.getPropTag('ExporterPipelineBRAPH2', prop), tag), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''ExporterPipelineBRAPH2'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:ExporterPipelineBRAPH2.getPropNumber()
		tag = ex.getPropTag(prop);
	 
		assert(Category.existsCategory(ExporterPipelineBRAPH2.getPropCategory(prop)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ExporterPipelineBRAPH2.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(ex.getPropCategory(prop)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ex.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(ex, prop)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(ex, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(ex, prop)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''ExporterPipelineBRAPH2'', prop) does not work.')
	 
		assert(Category.existsCategory(ExporterPipelineBRAPH2.getPropCategory(tag)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ExporterPipelineBRAPH2.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(ex.getPropCategory(tag)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ex.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(ex, tag)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(ex, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(ex, tag)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''ExporterPipelineBRAPH2'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:ExporterPipelineBRAPH2.getPropNumber()
		tag = ex.getPropTag(prop);
	 
		assert(Format.existsFormat(ExporterPipelineBRAPH2.getPropFormat(prop)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ExporterPipelineBRAPH2.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(ex.getPropFormat(prop)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ex.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(ex, prop)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(ex, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(ex, prop)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''ExporterPipelineBRAPH2'', prop) does not work.')
	 
		assert(Format.existsFormat(ExporterPipelineBRAPH2.getPropFormat(tag)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ExporterPipelineBRAPH2.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(ex.getPropFormat(tag)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ex.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(ex, tag)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(ex, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(ex, tag)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''ExporterPipelineBRAPH2'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:ExporterPipelineBRAPH2.getPropNumber()
		tag = ex.getPropTag(prop);
	 
		assert(ischar(ExporterPipelineBRAPH2.getPropDescription(prop)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ExporterPipelineBRAPH2.getPropDescription(prop) does not work.')
		assert(ischar(ex.getPropDescription(prop)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ex.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(ex, prop)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(ex, prop) does not work.')
		assert(ischar(Element.getPropDescription(ex, prop)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''ExporterPipelineBRAPH2'', prop) does not work.')
	 
		assert(ischar(ExporterPipelineBRAPH2.getPropDescription(tag)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ExporterPipelineBRAPH2.getPropDescription(tag) does not work.')
		assert(ischar(ex.getPropDescription(tag)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ex.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(ex, tag)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(ex, tag) does not work.')
		assert(ischar(Element.getPropDescription(ex, tag)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''ExporterPipelineBRAPH2'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:ExporterPipelineBRAPH2.getPropNumber()
		tag = ex.getPropTag(prop);
	 
		settings = ExporterPipelineBRAPH2.getPropSettings(prop);
		settings = ex.getPropSettings(prop);
		settings = Element.getPropSettings(ex, prop);
		settings = Element.getPropSettings('ExporterPipelineBRAPH2', prop);
	 
		settings = ExporterPipelineBRAPH2.getPropSettings(tag);
		settings = ex.getPropSettings(tag);
		settings = Element.getPropSettings(ex, tag);
		settings = Element.getPropSettings('ExporterPipelineBRAPH2', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:ExporterPipelineBRAPH2.getPropNumber()
		tag = ex.getPropTag(prop);
	 
		default = ExporterPipelineBRAPH2.getPropDefault(prop);
		default = ex.getPropDefault(prop);
		default = Element.getPropDefault(ex, prop);
		default = Element.getPropDefault('ExporterPipelineBRAPH2', prop);
	 
		default = ExporterPipelineBRAPH2.getPropDefault(tag);
		default = ex.getPropDefault(tag);
		default = Element.getPropDefault(ex, tag);
		default = Element.getPropDefault('ExporterPipelineBRAPH2', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:ExporterPipelineBRAPH2.getPropNumber()
		tag = ex.getPropTag(prop);
	 
		conditioned_default = ExporterPipelineBRAPH2.getPropDefaultConditioned(prop);
		conditioned_default = ex.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(ex, prop);
		conditioned_default = Element.getPropDefaultConditioned('ExporterPipelineBRAPH2', prop);
	 
		conditioned_default = ExporterPipelineBRAPH2.getPropDefaultConditioned(tag);
		conditioned_default = ex.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(ex, tag);
		conditioned_default = Element.getPropDefaultConditioned('ExporterPipelineBRAPH2', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:ExporterPipelineBRAPH2.getPropNumber()
		tag = ex.getPropTag(prop);
	 
		assert(~ExporterPipelineBRAPH2.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ExporterPipelineBRAPH2.checkProp(prop, value) does not work.')
		assert(~ex.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ex.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(ex, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(ex, prop, value) does not work.')
		assert(~Element.checkProp('ExporterPipelineBRAPH2', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ExporterPipelineBRAPH2'', prop, value) does not work.')
	 
		assert_with_error('ExporterPipelineBRAPH2.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.WRONG_INPUT], prop, ex)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.WRONG_INPUT], prop, ex)
		assert_with_error('Element.checkProp(''ExporterPipelineBRAPH2'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~ExporterPipelineBRAPH2.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ExporterPipelineBRAPH2.checkProp(tag, value) does not work.')
		assert(~ex.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ex.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(ex, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(ex, tag, value) does not work.')
		assert(~Element.checkProp('ExporterPipelineBRAPH2', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ExporterPipelineBRAPH2'', tag, value) does not work.')
	 
		assert_with_error('ExporterPipelineBRAPH2.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.WRONG_INPUT], tag, ex)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.WRONG_INPUT], tag, ex)
		assert_with_error('Element.checkProp(''ExporterPipelineBRAPH2'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(ExporterPipelineBRAPH2.checkProp(prop, Element.getPropDefaultConditioned(ExporterPipelineBRAPH2, prop)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ExporterPipelineBRAPH2.checkProp(prop, <conditioned default value>) does not work.')
		assert(ex.checkProp(prop, Element.getPropDefaultConditioned(ExporterPipelineBRAPH2, prop)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ex.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(ex, prop, Element.getPropDefaultConditioned(ExporterPipelineBRAPH2, prop)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(ex, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('ExporterPipelineBRAPH2', prop, Element.getPropDefaultConditioned(ExporterPipelineBRAPH2, prop)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ExporterPipelineBRAPH2'', prop, <conditioned default value>) does not work.')
	 
		assert(ExporterPipelineBRAPH2.checkProp(tag, Element.getPropDefaultConditioned(ExporterPipelineBRAPH2, prop)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ExporterPipelineBRAPH2.checkProp(tag, <conditioned default value>) does not work.')
		assert(ex.checkProp(tag, Element.getPropDefaultConditioned(ExporterPipelineBRAPH2, prop)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ex.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(ex, tag, Element.getPropDefaultConditioned(ExporterPipelineBRAPH2, prop)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(ex, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('ExporterPipelineBRAPH2', tag, Element.getPropDefaultConditioned(ExporterPipelineBRAPH2, prop)), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ExporterPipelineBRAPH2'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	ex = ExporterPipelineBRAPH2( ...
		ExporterPipelineBRAPH2.ELCLASS, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.NAME, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.DESCRIPTION, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.TEMPLATE, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.TEMPLATE), ...
		ExporterPipelineBRAPH2.ID, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.ID), ...
		ExporterPipelineBRAPH2.LABEL, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.LABEL), ...
		ExporterPipelineBRAPH2.NOTES, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.NOTES), ...
		ExporterPipelineBRAPH2.TOSTRING, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.WAITBAR, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.WAITBAR), ...
		ExporterPipelineBRAPH2.PIP, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.PIP), ...
		ExporterPipelineBRAPH2.FILE, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.FILE), ...
		ExporterPipelineBRAPH2.PUT_FILE, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.SAVE, ExporterPipelineBRAPH2.getNoValue() ...
		);
	 
	for prop = 1:1:ExporterPipelineBRAPH2.getPropNumber()
	 
		% excluded props
		if any(prop == [ExporterPipelineBRAPH2.PUT_FILE])
			continue
		end
	 
		TAG = upper(ExporterPipelineBRAPH2.getPropTag(prop));
		switch ExporterPipelineBRAPH2.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					ex.getr(prop) == ExporterPipelineBRAPH2.getNoValue(), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['Being a ' ExporterPipelineBRAPH2.getCategoryName(ExporterPipelineBRAPH2.getPropCategory(prop)) ', ExporterPipelineBRAPH2.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ExporterPipelineBRAPH2.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					ex.getr(TAG) == ExporterPipelineBRAPH2.getNoValue(), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['Being a ' ExporterPipelineBRAPH2.getCategoryName(ExporterPipelineBRAPH2.getPropCategory(prop)) ', ExporterPipelineBRAPH2.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ExporterPipelineBRAPH2.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(ex.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(ex.getPropSettings(prop))
					assert( ...
						ex.checkFormat(ex.getPropFormat(prop), ex.get(prop)), ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						['ExporterPipelineBRAPH2.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						ex.checkFormat(ex.getPropFormat(prop), ex.get(prop), ex.getPropSettings(prop)), ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						['ExporterPipelineBRAPH2.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					ex.getr(prop) == ExporterPipelineBRAPH2.getNoValue(), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['Being a ' ExporterPipelineBRAPH2.getCategoryName(ExporterPipelineBRAPH2.getPropCategory(prop)) ', ExporterPipelineBRAPH2.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ExporterPipelineBRAPH2.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					ex.getr(TAG) == ExporterPipelineBRAPH2.getNoValue(), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['Being a ' ExporterPipelineBRAPH2.getCategoryName(ExporterPipelineBRAPH2.getPropCategory(prop)) ', ExporterPipelineBRAPH2.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ExporterPipelineBRAPH2.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':ExporterPipelineBRAPH2']);
				assert( ...
					~isa(ex.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(ex.getPropSettings(prop))
					assert( ...
						ex.checkFormat(ex.getPropFormat(prop), ex.get(prop)), ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						['ExporterPipelineBRAPH2.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						ex.checkFormat(ex.getPropFormat(prop), ex.get(prop), ex.getPropSettings(prop)), ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						['ExporterPipelineBRAPH2.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(ex.getr(prop), ExporterPipelineBRAPH2.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by ExporterPipelineBRAPH2.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in ExporterPipelineBRAPH2.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(ex.getr(TAG), ExporterPipelineBRAPH2.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.getr(' TAG ') must be inizialized to its default value ' ...
					'given by ExporterPipelineBRAPH2.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in ExporterPipelineBRAPH2.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	ex = ExporterPipelineBRAPH2( ...
		ExporterPipelineBRAPH2.ELCLASS, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.NAME, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.DESCRIPTION, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.TEMPLATE, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.TEMPLATE), ...
		ExporterPipelineBRAPH2.ID, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.ID), ...
		ExporterPipelineBRAPH2.LABEL, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.LABEL), ...
		ExporterPipelineBRAPH2.NOTES, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.NOTES), ...
		ExporterPipelineBRAPH2.TOSTRING, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.WAITBAR, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.WAITBAR), ...
		ExporterPipelineBRAPH2.PIP, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.PIP), ...
		ExporterPipelineBRAPH2.FILE, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.FILE), ...
		ExporterPipelineBRAPH2.PUT_FILE, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.SAVE, ExporterPipelineBRAPH2.getNoValue() ...
		);
	 
	for prop = 1:1:ExporterPipelineBRAPH2.getPropNumber()
	 
		% excluded props
		if any(prop == [ExporterPipelineBRAPH2.PUT_FILE])
			continue
		end
	 
		TAG = upper(ExporterPipelineBRAPH2.getPropTag(prop));
		switch ExporterPipelineBRAPH2.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(ex.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(ex.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(ex.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(ex.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					ex.checkFormat(ex.getPropFormat(prop), ex.getr(prop),ex.getPropSettings(prop)), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':ExporterPipelineBRAPH2']);
				assert( ...
					~isa(ex.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(ex.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':ExporterPipelineBRAPH2']);
	% 			assert( ...
	% 				~isa(ex.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
	% 				['ExporterPipelineBRAPH2.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(ex.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
	% 				['ExporterPipelineBRAPH2.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				ex.checkFormat(ex.getPropFormat(prop), ex.getr(prop),ex.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
	% 				['ExporterPipelineBRAPH2.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':ExporterPipelineBRAPH2']);
				assert( ...
					~isa(ex.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(ex.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(ex.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(ex.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					ex.checkFormat(ex.getPropFormat(prop), ex.getr(prop),ex.getPropSettings(prop)), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if ex.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:ExporterPipelineBRAPH2');
					delete(ancestor(ex.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(ExporterPipelineBRAPH2.getProps(Category.RESULT))
		for prop = 1:1:ExporterPipelineBRAPH2.getPropNumber()
	 
			% excluded props
			if any(prop == [ExporterPipelineBRAPH2.PUT_FILE])
				continue
			end
	 
			switch ExporterPipelineBRAPH2.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						ex.isLocked(prop), ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						['ExporterPipelineBRAPH2.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~ex.isLocked(prop), ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						['ExporterPipelineBRAPH2.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	ex = ExporterPipelineBRAPH2();
	 
	for prop = 1:1:ExporterPipelineBRAPH2.getPropNumber()
		TAG = upper(ExporterPipelineBRAPH2.getPropTag(prop));
		assert( ...
			~ex.isLocked(prop), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			['ExporterPipelineBRAPH2.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~ex.isLocked(TAG), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			['ExporterPipelineBRAPH2.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	ex.lock()
	 
	for prop = 1:1:ExporterPipelineBRAPH2.getPropNumber()
		switch ExporterPipelineBRAPH2.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					ex.isLocked(prop), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~ex.isLocked(prop), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	ex = ExporterPipelineBRAPH2();
	 
	warning_backup = warning('off', 'BRAPH2:ExporterPipelineBRAPH2');
	for prop = 1:1:ExporterPipelineBRAPH2.getPropNumber()
		ex.lock(prop)
		switch ExporterPipelineBRAPH2.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					ex.isLocked(prop), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~ex.isLocked(prop), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	ex = ExporterPipelineBRAPH2();
	 
	for prop = 1:1:ExporterPipelineBRAPH2.getPropNumber()
		TAG = upper(ExporterPipelineBRAPH2.getPropTag(prop));
		assert( ...
			ex.isChecked(prop), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			['ExporterPipelineBRAPH2.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			ex.isChecked(TAG), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			['ExporterPipelineBRAPH2.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	ex.unchecked()
	 
	for prop = 1:1:ExporterPipelineBRAPH2.getPropNumber()
		assert( ...
			~ex.isChecked(prop), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			['ExporterPipelineBRAPH2.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	ex.checked()
	 
	for prop = 1:1:ExporterPipelineBRAPH2.getPropNumber()
		assert( ...
			ex.isChecked(prop), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			['ExporterPipelineBRAPH2.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic ExporterPipelineBRAPH2
	ex_0 = ExporterPipelineBRAPH2( ...
		ExporterPipelineBRAPH2.ELCLASS, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.NAME, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.DESCRIPTION, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.TEMPLATE, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.TEMPLATE), ...
		ExporterPipelineBRAPH2.ID, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.ID), ...
		ExporterPipelineBRAPH2.LABEL, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.LABEL), ...
		ExporterPipelineBRAPH2.NOTES, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.NOTES), ...
		ExporterPipelineBRAPH2.TOSTRING, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.WAITBAR, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.WAITBAR), ...
		ExporterPipelineBRAPH2.PIP, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.PIP), ...
		ExporterPipelineBRAPH2.FILE, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.FILE), ...
		ExporterPipelineBRAPH2.PUT_FILE, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.SAVE, ExporterPipelineBRAPH2.getNoValue() ...
		);
	 
	% ExporterPipelineBRAPH2 with 1st callbacks
	ex_1 = ExporterPipelineBRAPH2( ...
		ExporterPipelineBRAPH2.ELCLASS, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.NAME, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.DESCRIPTION, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.TEMPLATE, ex_0.getCallback(4), ..., ...
		ExporterPipelineBRAPH2.ID, ex_0.getCallback(5), ..., ...
		ExporterPipelineBRAPH2.LABEL, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.LABEL), ...
		ExporterPipelineBRAPH2.NOTES, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.NOTES), ...
		ExporterPipelineBRAPH2.TOSTRING, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.WAITBAR, ex_0.getCallback(9), ..., ...
		ExporterPipelineBRAPH2.PIP, ex_0.getCallback(10), ..., ...
		ExporterPipelineBRAPH2.FILE, ex_0.getCallback(11), ..., ...
		ExporterPipelineBRAPH2.PUT_FILE, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.SAVE, ExporterPipelineBRAPH2.getNoValue() ...
		);
	 
	prop_number = ExporterPipelineBRAPH2.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ExporterPipelineBRAPH2.getPropTag(prop));
		switch ExporterPipelineBRAPH2.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(ex_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(ex_1.get(prop), ex_0.get(prop)) && ~isa(ex_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(ex_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% ExporterPipelineBRAPH2 with 2nd callbacks
	ex_2 = ExporterPipelineBRAPH2( ...
		ExporterPipelineBRAPH2.ELCLASS, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.NAME, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.DESCRIPTION, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.TEMPLATE, ex_1.getCallback(4), ..., ...
		ExporterPipelineBRAPH2.ID, ex_1.getCallback(5), ..., ...
		ExporterPipelineBRAPH2.LABEL, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.LABEL), ...
		ExporterPipelineBRAPH2.NOTES, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.NOTES), ...
		ExporterPipelineBRAPH2.TOSTRING, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.WAITBAR, ex_1.getCallback(9), ..., ...
		ExporterPipelineBRAPH2.PIP, ex_1.getCallback(10), ..., ...
		ExporterPipelineBRAPH2.FILE, ex_1.getCallback(11), ..., ...
		ExporterPipelineBRAPH2.PUT_FILE, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.SAVE, ExporterPipelineBRAPH2.getNoValue() ...
		);
	 
	prop_number = ExporterPipelineBRAPH2.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ExporterPipelineBRAPH2.getPropTag(prop));
		switch ExporterPipelineBRAPH2.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(ex_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(ex_2.get(prop), ex_0.get(prop)) && ~isa(ex_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(ex_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% ExporterPipelineBRAPH2 with 3rd callbacks
	ex_3 = ExporterPipelineBRAPH2( ...
		ExporterPipelineBRAPH2.ELCLASS, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.NAME, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.DESCRIPTION, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.TEMPLATE, ex_2.getCallback(4), ..., ...
		ExporterPipelineBRAPH2.ID, ex_2.getCallback(5), ..., ...
		ExporterPipelineBRAPH2.LABEL, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.LABEL), ...
		ExporterPipelineBRAPH2.NOTES, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.NOTES), ...
		ExporterPipelineBRAPH2.TOSTRING, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.WAITBAR, ex_2.getCallback(9), ..., ...
		ExporterPipelineBRAPH2.PIP, ex_2.getCallback(10), ..., ...
		ExporterPipelineBRAPH2.FILE, ex_2.getCallback(11), ..., ...
		ExporterPipelineBRAPH2.PUT_FILE, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.SAVE, ExporterPipelineBRAPH2.getNoValue() ...
		);
	 
	prop_number = ExporterPipelineBRAPH2.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ExporterPipelineBRAPH2.getPropTag(prop));
		switch ExporterPipelineBRAPH2.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(ex_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(ex_3.get(prop), ex_0.get(prop)) && ~isa(ex_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(ex_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	ex = ExporterPipelineBRAPH2();
	 
	ex_copy = ex.copy();
	 
	assert(ex_copy ~= ex, ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'ExporterPipelineBRAPH2.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(ex_copy, ex), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'ExporterPipelineBRAPH2.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:ExporterPipelineBRAPH2.getPropNumber()
		value = ex.getr(prop);
		value_copy = ex_copy.getr(prop);
		switch ExporterPipelineBRAPH2.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					'ExporterPipelineBRAPH2.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						'ExporterPipelineBRAPH2.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						'ExporterPipelineBRAPH2.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						'ExporterPipelineBRAPH2.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
							'ExporterPipelineBRAPH2.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
							'ExporterPipelineBRAPH2.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						'ExporterPipelineBRAPH2.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					ex_copy.isLocked(prop) == ex.isLocked(prop), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					'ExporterPipelineBRAPH2.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					ex_copy.isChecked(prop) == ex.isChecked(prop), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					'ExporterPipelineBRAPH2.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					ex_copy.getPropSeed(prop) == ex.getPropSeed(prop), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					'ExporterPipelineBRAPH2.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	ex = ExporterPipelineBRAPH2( ...
		ExporterPipelineBRAPH2.ELCLASS, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.NAME, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.DESCRIPTION, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.TEMPLATE, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.TEMPLATE), ...
		ExporterPipelineBRAPH2.ID, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.ID), ...
		ExporterPipelineBRAPH2.LABEL, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.LABEL), ...
		ExporterPipelineBRAPH2.NOTES, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.NOTES), ...
		ExporterPipelineBRAPH2.TOSTRING, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.WAITBAR, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.WAITBAR), ...
		ExporterPipelineBRAPH2.PIP, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.PIP), ...
		ExporterPipelineBRAPH2.FILE, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.FILE), ...
		ExporterPipelineBRAPH2.PUT_FILE, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.SAVE, ExporterPipelineBRAPH2.getNoValue() ...
		);
	 
	for prop = 1:1:ExporterPipelineBRAPH2.getPropNumber()
		if ExporterPipelineBRAPH2.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':ExporterPipelineBRAPH2']);
			% ex.memorize(prop);
			% warning(warning_backup)
		elseif ExporterPipelineBRAPH2.getPropCategory(prop) == Category.EVANESCENT && ex.getPropFormat(prop) == Format.HANDLE
			ex.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:ExporterPipelineBRAPH2');
			delete(ancestor(ex.get(prop), 'figure'))
			warning(warning_backup)
		else
			ex.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	ex_copy = ex.copy();
	 
	for prop = 1:1:ExporterPipelineBRAPH2.getPropNumber()
		value = ex.getr(prop);
		value_copy = ex_copy.getr(prop);
		switch ExporterPipelineBRAPH2.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					'ExporterPipelineBRAPH2.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						'ExporterPipelineBRAPH2.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						'ExporterPipelineBRAPH2.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						'ExporterPipelineBRAPH2.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
							'ExporterPipelineBRAPH2.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
							'ExporterPipelineBRAPH2.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						'ExporterPipelineBRAPH2.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						ex_copy.isLocked(prop) == ex.isLocked(prop), ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						'ExporterPipelineBRAPH2.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						ex_copy.isChecked(prop) == ex.isChecked(prop), ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						'ExporterPipelineBRAPH2.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						ex_copy.getPropSeed(prop) == ex.getPropSeed(prop), ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						'ExporterPipelineBRAPH2.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	ex_0 = ExporterPipelineBRAPH2( ...
		ExporterPipelineBRAPH2.ELCLASS, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.NAME, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.DESCRIPTION, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.TEMPLATE, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.TEMPLATE), ...
		ExporterPipelineBRAPH2.ID, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.ID), ...
		ExporterPipelineBRAPH2.LABEL, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.LABEL), ...
		ExporterPipelineBRAPH2.NOTES, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.NOTES), ...
		ExporterPipelineBRAPH2.TOSTRING, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.WAITBAR, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.WAITBAR), ...
		ExporterPipelineBRAPH2.PIP, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.PIP), ...
		ExporterPipelineBRAPH2.FILE, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.FILE), ...
		ExporterPipelineBRAPH2.PUT_FILE, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.SAVE, ExporterPipelineBRAPH2.getNoValue() ...
		);
	 
	ex = ExporterPipelineBRAPH2( ...
		ExporterPipelineBRAPH2.ELCLASS, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.NAME, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.DESCRIPTION, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.TEMPLATE, ex_0.getCallback(4), ..., ...
		ExporterPipelineBRAPH2.ID, ex_0.getCallback(5), ..., ...
		ExporterPipelineBRAPH2.LABEL, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.LABEL), ...
		ExporterPipelineBRAPH2.NOTES, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.NOTES), ...
		ExporterPipelineBRAPH2.TOSTRING, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.WAITBAR, ex_0.getCallback(9), ..., ...
		ExporterPipelineBRAPH2.PIP, ex_0.getCallback(10), ..., ...
		ExporterPipelineBRAPH2.FILE, ex_0.getCallback(11), ..., ...
		ExporterPipelineBRAPH2.PUT_FILE, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.SAVE, ExporterPipelineBRAPH2.getNoValue() ...
		);
	 
	ex_copy = ex.copy();
	ex_0_copy = ex_copy.getr('ID').get('EL');
	 
	for prop = 1:1:ExporterPipelineBRAPH2.getPropNumber()
		value = ex.getr(prop);
		value_copy = ex_copy.getr(prop);
		switch ExporterPipelineBRAPH2.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					'ExporterPipelineBRAPH2.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						'ExporterPipelineBRAPH2.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						'ExporterPipelineBRAPH2.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						'ExporterPipelineBRAPH2.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
							'ExporterPipelineBRAPH2.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
							'ExporterPipelineBRAPH2.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						'ExporterPipelineBRAPH2.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == ex_0.getCallback(prop), ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						'ExporterPipelineBRAPH2.copy() does not work. The callback should be obtained from ExporterPipelineBRAPH2.getCallback().' ...
						)
					assert( ...
						value_copy == ex_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						'ExporterPipelineBRAPH2.copy() does not work. The callback should be obtained from ExporterPipelineBRAPH2.getCallback().' ...
						)
				end
	 
					assert( ...
						ex_copy.isLocked(prop) == ex.isLocked(prop), ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						'ExporterPipelineBRAPH2.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						ex_copy.isChecked(prop) == ex.isChecked(prop), ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						'ExporterPipelineBRAPH2.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						ex_copy.getPropSeed(prop) == ex.getPropSeed(prop), ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						'ExporterPipelineBRAPH2.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	ex_template = ExporterPipelineBRAPH2();
	ex = ExporterPipelineBRAPH2('TEMPLATE', ex_template);
	 
	for prop = 1:1:ExporterPipelineBRAPH2.getPropNumber()
	 
		% excluded props
		if any(prop == [ExporterPipelineBRAPH2.PUT_FILE])
			continue
		end
	 
		TAG = upper(ExporterPipelineBRAPH2.getPropTag(prop));
		switch ExporterPipelineBRAPH2.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == ExporterPipelineBRAPH2.TEMPLATE
					assert( ...
						isa(ex.getr(prop), 'ExporterPipelineBRAPH2'), ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						'ExporterPipelineBRAPH2 TEMPLATE does not work. ExporterPipelineBRAPH2.getr(''TEMPLATE'') should be a ExporterPipelineBRAPH2 element.' ...
						)
					assert( ...
						isa(ex_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						'ExporterPipelineBRAPH2 TEMPLATE does not work. ExporterPipelineBRAPH2_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(ex.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						['ExporterPipelineBRAPH2 TEMPLATE does not work. ExporterPipelineBRAPH2.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						ex.getr(prop).get('EL') == ex_template && ex.getr(prop).get('PROP') == prop && strcmp(ex.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						['ExporterPipelineBRAPH2 TEMPLATE does not work. ExporterPipelineBRAPH2.getr(' TAG ') should be a Callback to ex_template.' TAG '.'] ...
						)
					assert( ...
						isa(ex_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
						['ExporterPipelineBRAPH2 TEMPLATE does not work. ExporterPipelineBRAPH2_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(ex.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2 TEMPLATE does not work. ExporterPipelineBRAPH2.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(ex_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
					['ExporterPipelineBRAPH2 TEMPLATE does not work. ExporterPipelineBRAPH2_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	ex = ExporterPipelineBRAPH2( ...
		ExporterPipelineBRAPH2.ELCLASS, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.NAME, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.DESCRIPTION, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.TEMPLATE, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.TEMPLATE), ...
		ExporterPipelineBRAPH2.ID, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.ID), ...
		ExporterPipelineBRAPH2.LABEL, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.LABEL), ...
		ExporterPipelineBRAPH2.NOTES, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.NOTES), ...
		ExporterPipelineBRAPH2.TOSTRING, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.WAITBAR, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.WAITBAR), ...
		ExporterPipelineBRAPH2.PIP, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.PIP), ...
		ExporterPipelineBRAPH2.FILE, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.FILE), ...
		ExporterPipelineBRAPH2.PUT_FILE, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.SAVE, ExporterPipelineBRAPH2.getNoValue() ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'exporterpipelinebraph2_to_be_erased.b2'];
	 
	Element.save(ex, filename)
	 
	ex_loaded = Element.load(filename);
	 
	assert( ...
		isequal(ex.copy(), ex_loaded), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'ExporterPipelineBRAPH2.save(ex) and/or ExporterPipelineBRAPH2.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	ex = ExporterPipelineBRAPH2( ...
		ExporterPipelineBRAPH2.ELCLASS, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.NAME, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.DESCRIPTION, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.TEMPLATE, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.TEMPLATE), ...
		ExporterPipelineBRAPH2.ID, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.ID), ...
		ExporterPipelineBRAPH2.LABEL, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.LABEL), ...
		ExporterPipelineBRAPH2.NOTES, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.NOTES), ...
		ExporterPipelineBRAPH2.TOSTRING, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.WAITBAR, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.WAITBAR), ...
		ExporterPipelineBRAPH2.PIP, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.PIP), ...
		ExporterPipelineBRAPH2.FILE, ExporterPipelineBRAPH2.getPropDefault(ExporterPipelineBRAPH2.FILE), ...
		ExporterPipelineBRAPH2.PUT_FILE, ExporterPipelineBRAPH2.getNoValue(), ...
		ExporterPipelineBRAPH2.SAVE, ExporterPipelineBRAPH2.getNoValue() ...
		);
	 
	[json, struct, el_list] = encodeJSON(ex);
	[ex_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(ex_dec ~= ex, ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		'ExporterPipelineBRAPH2.encodeJSON() or ExporterPipelineBRAPH2.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) ExporterPipelineBRAPH2.getPropFormat(prop), num2cell(ExporterPipelineBRAPH2.getProps())) == Format.HANDLE) && all(cellfun(@(prop) ExporterPipelineBRAPH2.getPropFormat(prop), num2cell(ExporterPipelineBRAPH2.getProps())) == Format.NET)
		assert(isequal(ex_dec, ex), ...
			[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
			'ExporterPipelineBRAPH2.encodeJSON() or ExporterPipelineBRAPH2.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: Example
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	im = ImporterPipelineBRAPH2(...
	    'FILE', [fileparts(which('Pipeline')) filesep 'gui_examples' filesep 'pipeline_atlas.braph2'], ...
	    'WAITBAR', true ...
	    ); 
	pip = im.get('PIP');
	% pip.tree(4)
	
	ex= ExporterPipelineBRAPH2( ...
	    'PIP', pip, ...
	    'WAITBAR', true ...
	    );
	ex.get('SAVE');
end

%% Test 13: Delete file TBE
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	warning('off', 'MATLAB:DELETE:FileNotFound')
	delete([fileparts(which('test_braph2')) filesep 'default_braph2_file_to_save_pipeline_most_likely_to_be_erased.braph2'])
	warning('on', 'MATLAB:DELETE:FileNotFound')
end

%% Test 14: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':ExporterPipelineBRAPH2:' BRAPH2.FAIL_TEST], ...
		[' When testing ExporterPipelineBRAPH2 no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 15: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

