%TEST_SETTINGSLINE

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	st = SettingsLine();
	 
	% get('ELCLASS')
	if isa(SettingsLine, 'ConcreteElement')
		assert(strcmp(SettingsLine().get('ELCLASS'), 'SettingsLine'), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'SettingsLine().get(''ELCLASS'') should return ''SettingsLine''.')
	end
	 
	% getBuild()
	assert(SettingsLine.getBuild() == 1 && SettingsLine.getBuild() > 0, ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'SettingsLine.getBuild() should return the SettingsLine build number.')
	assert(st.getBuild() == 1 && st.getBuild() > 0 , ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'st.getBuild() should return the SettingsLine build number.')
	assert(Element.getBuild(st) == 1 && Element.getBuild(st) > 0, ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(st) should return the SettingsLine build number.')
	assert(Element.getBuild('SettingsLine') == 1 && Element.getBuild('SettingsLine') > 0, ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''SettingsLine'') should return the SettingsLine build number.')
	 
	% getClass()
	assert(strcmp(SettingsLine.getClass(), 'SettingsLine'), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'SettingsLine.getClass() should return ''SettingsLine''.')
	assert(strcmp(st.getClass(), 'SettingsLine'), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'st.getClass() should return ''SettingsLine''.')
	assert(strcmp(Element.getClass(st), 'SettingsLine'), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(st) should return ''SettingsLine''.')
	assert(strcmp(Element.getClass('SettingsLine'), 'SettingsLine'), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''SettingsLine'') should return ''SettingsLine''.')
	 
	% getSubclasses()
	assert(isequal(SettingsLine.getSubclasses(), subclasses('SettingsLine', [], [], true)), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'SettingsLine.getSubclasses() should return the same result as subclasses(''SettingsLine'', [], [], true).')
	assert(isequal(st.getSubclasses(), subclasses('SettingsLine', [], [], true)), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''SettingsLine'', [], [], true).')
	assert(isequal(Element.getSubclasses(st), subclasses('SettingsLine', [], [], true)), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(st) should return the same result as subclasses(''SettingsLine'', [], [], true).')
	assert(isequal(Element.getSubclasses('SettingsLine'), subclasses('SettingsLine', [], [], true)), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''SettingsLine'') should return the same result as subclasses(''SettingsLine'', [], [], true).')
	 
	% getProps()
	assert(isempty(SettingsLine.getProps()) || isequal(SettingsLine.getProps(), 1:1:length(SettingsLine.getProps())), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'SettingsLine.getProps() should return a row vector [1:1:N].')
	assert(isempty(SettingsLine.getProps()) || isequal(st.getProps(), 1:1:length(SettingsLine.getProps())), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'st.getProps() should return a row vector [1:1:N].')
	assert(isempty(SettingsLine.getProps()) || isequal(Element.getProps(st), 1:1:length(SettingsLine.getProps())), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(st) should return a row vector [1:1:N].')
	assert(isempty(SettingsLine.getProps()) || isequal(Element.getProps('SettingsLine'), 1:1:length(SettingsLine.getProps())), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''SettingsLine'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) SettingsLine.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(SettingsLine.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(SettingsLine.getProps())), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'SettingsLine.getProps(category) does not work.')
	tmp = cellfun(@(category) st.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(SettingsLine.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(SettingsLine.getProps())), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'st.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(st, category), categories, 'UniformOutput', false);
	assert(isempty(SettingsLine.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(SettingsLine.getProps())), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(st, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('SettingsLine', category), categories, 'UniformOutput', false);
	assert(isempty(SettingsLine.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(SettingsLine.getProps())), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''SettingsLine'', category) does not work.')
	 
	% getPropNumber()
	assert(SettingsLine.getPropNumber() == length(SettingsLine.getProps()), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'SettingsLine.getPropNumber() should return the number of properties.')
	assert(st.getPropNumber() == length(SettingsLine.getProps()), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'st.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(st) == length(SettingsLine.getProps()), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(st) should return the number of properties.')
	assert(Element.getPropNumber('SettingsLine') == length(SettingsLine.getProps()), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''SettingsLine'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) SettingsLine.getPropNumber(category), categories)) == SettingsLine.getPropNumber(), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'SettingsLine.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) st.getPropNumber(category), categories)) == SettingsLine.getPropNumber(), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'st.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(st, category), categories)) == SettingsLine.getPropNumber(), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(st, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('SettingsLine', category), categories)) == SettingsLine.getPropNumber(), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''SettingsLine'', category) does not work.')
	 
	% existsProp(prop)
	assert(~SettingsLine.existsProp(NaN), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'SettingsLine.existsProp(prop) does not work.')
	assert(~st.existsProp(NaN), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'st.existsProp(prop) does not work.')
	assert(~Element.existsProp(st, NaN), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(st, prop) does not work.')
	assert(~Element.existsProp('SettingsLine', NaN), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''SettingsLine'', prop) does not work.')
	 
	assert_with_error('SettingsLine.existsProp(NaN)', [BRAPH2.STR ':SettingsLine:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':SettingsLine:' BRAPH2.WRONG_INPUT], st)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':SettingsLine:' BRAPH2.WRONG_INPUT], st)
	assert_with_error('Element.existsProp(''SettingsLine'', NaN)', [BRAPH2.STR ':SettingsLine:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:SettingsLine.getPropNumber()
		assert(SettingsLine.existsProp(prop), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'SettingsLine.existsProp(prop) does not work.')
		assert(st.existsProp(prop), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'st.existsProp(prop) does not work.')
		assert(Element.existsProp(st, prop), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(st, prop) does not work.')
		assert(Element.existsProp('SettingsLine', prop), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''SettingsLine'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~SettingsLine.existsTag(''), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'SettingsLine.existsTag(tag) does not work.')
	assert(~st.existsTag(''), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'st.existsTag(tag) does not work.')
	assert(~Element.existsTag(st, ''), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(st, tag) does not work.')
	assert(~Element.existsTag('SettingsLine', ''), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''SettingsLine'', tag) does not work.')
	 
	assert_with_error('SettingsLine.existsTag('''')', [BRAPH2.STR ':SettingsLine:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':SettingsLine:' BRAPH2.WRONG_INPUT], st)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':SettingsLine:' BRAPH2.WRONG_INPUT], st)
	assert_with_error('Element.existsTag(''SettingsLine'', '''')', [BRAPH2.STR ':SettingsLine:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:SettingsLine.getPropNumber()
		tag = st.getPropTag(prop);
		assert(SettingsLine.existsTag(tag), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'SettingsLine.existsTag(tag) does not work.')
		assert(st.existsTag(tag), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'st.existsTag(tag) does not work.')
		assert(Element.existsTag(st, tag), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(st, tga) does not work.')
		assert(Element.existsTag('SettingsLine', tag), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''SettingsLine'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:SettingsLine.getPropNumber()
		assert(SettingsLine.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'SettingsLine.getPropProp(prop) does not work.')
		assert(st.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'st.getPropProp(prop) does not work.')
		assert(Element.getPropProp(st, prop) == prop, ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(st, prop) does not work.')
		assert(Element.getPropProp('SettingsLine', prop) == prop, ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''SettingsLine'', prop) does not work.')
	 
		tag = st.getPropTag(prop);
		assert(SettingsLine.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'SettingsLine.getPropProp(tag) does not work.')
		assert(st.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'st.getPropProp(tag) does not work.')
		assert(Element.getPropProp(st, tag) == prop, ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(st, tag) does not work.')
		assert(Element.getPropProp('SettingsLine', prop) == prop, ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''SettingsLine'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:SettingsLine.getPropNumber()
		tag = st.getPropTag(prop);
	 
		assert(strcmp(SettingsLine.getPropTag(prop), tag), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'SettingsLine.getPropTag(prop) does not work.')
		assert(strcmp(st.getPropTag(prop), tag), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'st.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(st, prop), tag), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(st, prop) does not work.')
		assert(strcmp(Element.getPropTag('SettingsLine', prop), tag), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''SettingsLine'', prop) does not work.')
	 
		assert(strcmp(SettingsLine.getPropTag(tag), tag), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'SettingsLine.getPropTag(tag) does not work.')
		assert(strcmp(st.getPropTag(tag), tag), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'st.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(st, tag), tag), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(st, tag) does not work.')
		assert(strcmp(Element.getPropTag('SettingsLine', prop), tag), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''SettingsLine'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:SettingsLine.getPropNumber()
		tag = st.getPropTag(prop);
	 
		assert(Category.existsCategory(SettingsLine.getPropCategory(prop)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'SettingsLine.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(st.getPropCategory(prop)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'st.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(st, prop)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(st, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(st, prop)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''SettingsLine'', prop) does not work.')
	 
		assert(Category.existsCategory(SettingsLine.getPropCategory(tag)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'SettingsLine.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(st.getPropCategory(tag)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'st.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(st, tag)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(st, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(st, tag)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''SettingsLine'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:SettingsLine.getPropNumber()
		tag = st.getPropTag(prop);
	 
		assert(Format.existsFormat(SettingsLine.getPropFormat(prop)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'SettingsLine.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(st.getPropFormat(prop)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'st.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(st, prop)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(st, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(st, prop)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''SettingsLine'', prop) does not work.')
	 
		assert(Format.existsFormat(SettingsLine.getPropFormat(tag)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'SettingsLine.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(st.getPropFormat(tag)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'st.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(st, tag)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(st, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(st, tag)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''SettingsLine'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:SettingsLine.getPropNumber()
		tag = st.getPropTag(prop);
	 
		assert(ischar(SettingsLine.getPropDescription(prop)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'SettingsLine.getPropDescription(prop) does not work.')
		assert(ischar(st.getPropDescription(prop)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'st.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(st, prop)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(st, prop) does not work.')
		assert(ischar(Element.getPropDescription(st, prop)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''SettingsLine'', prop) does not work.')
	 
		assert(ischar(SettingsLine.getPropDescription(tag)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'SettingsLine.getPropDescription(tag) does not work.')
		assert(ischar(st.getPropDescription(tag)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'st.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(st, tag)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(st, tag) does not work.')
		assert(ischar(Element.getPropDescription(st, tag)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''SettingsLine'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:SettingsLine.getPropNumber()
		tag = st.getPropTag(prop);
	 
		settings = SettingsLine.getPropSettings(prop);
		settings = st.getPropSettings(prop);
		settings = Element.getPropSettings(st, prop);
		settings = Element.getPropSettings('SettingsLine', prop);
	 
		settings = SettingsLine.getPropSettings(tag);
		settings = st.getPropSettings(tag);
		settings = Element.getPropSettings(st, tag);
		settings = Element.getPropSettings('SettingsLine', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:SettingsLine.getPropNumber()
		tag = st.getPropTag(prop);
	 
		default = SettingsLine.getPropDefault(prop);
		default = st.getPropDefault(prop);
		default = Element.getPropDefault(st, prop);
		default = Element.getPropDefault('SettingsLine', prop);
	 
		default = SettingsLine.getPropDefault(tag);
		default = st.getPropDefault(tag);
		default = Element.getPropDefault(st, tag);
		default = Element.getPropDefault('SettingsLine', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:SettingsLine.getPropNumber()
		tag = st.getPropTag(prop);
	 
		conditioned_default = SettingsLine.getPropDefaultConditioned(prop);
		conditioned_default = st.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(st, prop);
		conditioned_default = Element.getPropDefaultConditioned('SettingsLine', prop);
	 
		conditioned_default = SettingsLine.getPropDefaultConditioned(tag);
		conditioned_default = st.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(st, tag);
		conditioned_default = Element.getPropDefaultConditioned('SettingsLine', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:SettingsLine.getPropNumber()
		tag = st.getPropTag(prop);
	 
		assert(~SettingsLine.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'SettingsLine.checkProp(prop, value) does not work.')
		assert(~st.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'st.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(st, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(st, prop, value) does not work.')
		assert(~Element.checkProp('SettingsLine', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''SettingsLine'', prop, value) does not work.')
	 
		assert_with_error('SettingsLine.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SettingsLine:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SettingsLine:' BRAPH2.WRONG_INPUT], prop, st)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SettingsLine:' BRAPH2.WRONG_INPUT], prop, st)
		assert_with_error('Element.checkProp(''SettingsLine'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SettingsLine:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~SettingsLine.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'SettingsLine.checkProp(tag, value) does not work.')
		assert(~st.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'st.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(st, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(st, tag, value) does not work.')
		assert(~Element.checkProp('SettingsLine', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''SettingsLine'', tag, value) does not work.')
	 
		assert_with_error('SettingsLine.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SettingsLine:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SettingsLine:' BRAPH2.WRONG_INPUT], tag, st)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SettingsLine:' BRAPH2.WRONG_INPUT], tag, st)
		assert_with_error('Element.checkProp(''SettingsLine'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SettingsLine:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(SettingsLine.checkProp(prop, Element.getPropDefaultConditioned(SettingsLine, prop)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'SettingsLine.checkProp(prop, <conditioned default value>) does not work.')
		assert(st.checkProp(prop, Element.getPropDefaultConditioned(SettingsLine, prop)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'st.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(st, prop, Element.getPropDefaultConditioned(SettingsLine, prop)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(st, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('SettingsLine', prop, Element.getPropDefaultConditioned(SettingsLine, prop)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''SettingsLine'', prop, <conditioned default value>) does not work.')
	 
		assert(SettingsLine.checkProp(tag, Element.getPropDefaultConditioned(SettingsLine, prop)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'SettingsLine.checkProp(tag, <conditioned default value>) does not work.')
		assert(st.checkProp(tag, Element.getPropDefaultConditioned(SettingsLine, prop)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'st.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(st, tag, Element.getPropDefaultConditioned(SettingsLine, prop)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(st, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('SettingsLine', tag, Element.getPropDefaultConditioned(SettingsLine, prop)), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''SettingsLine'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = SettingsLine( ...
		SettingsLine.ELCLASS, SettingsLine.getNoValue(), ...
		SettingsLine.NAME, SettingsLine.getNoValue(), ...
		SettingsLine.DESCRIPTION, SettingsLine.getNoValue(), ...
		SettingsLine.TEMPLATE, SettingsLine.getPropDefault(SettingsLine.TEMPLATE), ...
		SettingsLine.ID, SettingsLine.getPropDefault(SettingsLine.ID), ...
		SettingsLine.LABEL, SettingsLine.getPropDefault(SettingsLine.LABEL), ...
		SettingsLine.NOTES, SettingsLine.getPropDefault(SettingsLine.NOTES), ...
		SettingsLine.TOSTRING, SettingsLine.getNoValue(), ...
		SettingsLine.PANEL, SettingsLine.getPropDefault(SettingsLine.PANEL), ...
		SettingsLine.PROP, SettingsLine.getPropDefault(SettingsLine.PROP), ...
		SettingsLine.TAG, SettingsLine.getPropDefault(SettingsLine.TAG), ...
		SettingsLine.I, SettingsLine.getPropDefault(SettingsLine.I), ...
		SettingsLine.H, SettingsLine.getNoValue(), ...
		SettingsLine.SETUP, SettingsLine.getNoValue(), ...
		SettingsLine.VISIBLE, SettingsLine.getPropDefault(SettingsLine.VISIBLE), ...
		SettingsLine.X, SettingsLine.getPropDefault(SettingsLine.X), ...
		SettingsLine.Y, SettingsLine.getPropDefault(SettingsLine.Y), ...
		SettingsLine.Z, SettingsLine.getPropDefault(SettingsLine.Z), ...
		SettingsLine.LINESTYLE, SettingsLine.getPropDefault(SettingsLine.LINESTYLE), ...
		SettingsLine.LINEWIDTH, SettingsLine.getPropDefault(SettingsLine.LINEWIDTH), ...
		SettingsLine.LINECOLOR, SettingsLine.getPropDefault(SettingsLine.LINECOLOR), ...
		SettingsLine.SYMBOL, SettingsLine.getPropDefault(SettingsLine.SYMBOL), ...
		SettingsLine.SYMBOLSIZE, SettingsLine.getPropDefault(SettingsLine.SYMBOLSIZE), ...
		SettingsLine.EDGECOLOR, SettingsLine.getPropDefault(SettingsLine.EDGECOLOR), ...
		SettingsLine.FACECOLOR, SettingsLine.getPropDefault(SettingsLine.FACECOLOR) ...
		);
	 
	for prop = 1:1:SettingsLine.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(SettingsLine.getPropTag(prop));
		switch SettingsLine.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					st.getr(prop) == SettingsLine.getNoValue(), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['Being a ' SettingsLine.getCategoryName(SettingsLine.getPropCategory(prop)) ', SettingsLine.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in SettingsLine.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					st.getr(TAG) == SettingsLine.getNoValue(), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['Being a ' SettingsLine.getCategoryName(SettingsLine.getPropCategory(prop)) ', SettingsLine.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in SettingsLine.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(st.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(st.getPropSettings(prop))
					assert( ...
						st.checkFormat(st.getPropFormat(prop), st.get(prop)), ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						['SettingsLine.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						st.checkFormat(st.getPropFormat(prop), st.get(prop), st.getPropSettings(prop)), ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						['SettingsLine.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					st.getr(prop) == SettingsLine.getNoValue(), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['Being a ' SettingsLine.getCategoryName(SettingsLine.getPropCategory(prop)) ', SettingsLine.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in SettingsLine.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					st.getr(TAG) == SettingsLine.getNoValue(), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['Being a ' SettingsLine.getCategoryName(SettingsLine.getPropCategory(prop)) ', SettingsLine.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in SettingsLine.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':SettingsLine']);
				assert( ...
					~isa(st.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(st.getPropSettings(prop))
					assert( ...
						st.checkFormat(st.getPropFormat(prop), st.get(prop)), ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						['SettingsLine.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						st.checkFormat(st.getPropFormat(prop), st.get(prop), st.getPropSettings(prop)), ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						['SettingsLine.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(st.getr(prop), SettingsLine.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by SettingsLine.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in SettingsLine.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(st.getr(TAG), SettingsLine.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.getr(' TAG ') must be inizialized to its default value ' ...
					'given by SettingsLine.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in SettingsLine.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = SettingsLine( ...
		SettingsLine.ELCLASS, SettingsLine.getNoValue(), ...
		SettingsLine.NAME, SettingsLine.getNoValue(), ...
		SettingsLine.DESCRIPTION, SettingsLine.getNoValue(), ...
		SettingsLine.TEMPLATE, SettingsLine.getPropDefault(SettingsLine.TEMPLATE), ...
		SettingsLine.ID, SettingsLine.getPropDefault(SettingsLine.ID), ...
		SettingsLine.LABEL, SettingsLine.getPropDefault(SettingsLine.LABEL), ...
		SettingsLine.NOTES, SettingsLine.getPropDefault(SettingsLine.NOTES), ...
		SettingsLine.TOSTRING, SettingsLine.getNoValue(), ...
		SettingsLine.PANEL, SettingsLine.getPropDefault(SettingsLine.PANEL), ...
		SettingsLine.PROP, SettingsLine.getPropDefault(SettingsLine.PROP), ...
		SettingsLine.TAG, SettingsLine.getPropDefault(SettingsLine.TAG), ...
		SettingsLine.I, SettingsLine.getPropDefault(SettingsLine.I), ...
		SettingsLine.H, SettingsLine.getNoValue(), ...
		SettingsLine.SETUP, SettingsLine.getNoValue(), ...
		SettingsLine.VISIBLE, SettingsLine.getPropDefault(SettingsLine.VISIBLE), ...
		SettingsLine.X, SettingsLine.getPropDefault(SettingsLine.X), ...
		SettingsLine.Y, SettingsLine.getPropDefault(SettingsLine.Y), ...
		SettingsLine.Z, SettingsLine.getPropDefault(SettingsLine.Z), ...
		SettingsLine.LINESTYLE, SettingsLine.getPropDefault(SettingsLine.LINESTYLE), ...
		SettingsLine.LINEWIDTH, SettingsLine.getPropDefault(SettingsLine.LINEWIDTH), ...
		SettingsLine.LINECOLOR, SettingsLine.getPropDefault(SettingsLine.LINECOLOR), ...
		SettingsLine.SYMBOL, SettingsLine.getPropDefault(SettingsLine.SYMBOL), ...
		SettingsLine.SYMBOLSIZE, SettingsLine.getPropDefault(SettingsLine.SYMBOLSIZE), ...
		SettingsLine.EDGECOLOR, SettingsLine.getPropDefault(SettingsLine.EDGECOLOR), ...
		SettingsLine.FACECOLOR, SettingsLine.getPropDefault(SettingsLine.FACECOLOR) ...
		);
	 
	for prop = 1:1:SettingsLine.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(SettingsLine.getPropTag(prop));
		switch SettingsLine.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(st.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(st.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(st.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(st.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					st.checkFormat(st.getPropFormat(prop), st.getr(prop),st.getPropSettings(prop)), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':SettingsLine']);
				assert( ...
					~isa(st.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(st.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':SettingsLine']);
	% 			assert( ...
	% 				~isa(st.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
	% 				['SettingsLine.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(st.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
	% 				['SettingsLine.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				st.checkFormat(st.getPropFormat(prop), st.getr(prop),st.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
	% 				['SettingsLine.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':SettingsLine']);
				assert( ...
					~isa(st.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(st.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(st.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(st.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					st.checkFormat(st.getPropFormat(prop), st.getr(prop),st.getPropSettings(prop)), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if st.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:SettingsLine');
					delete(ancestor(st.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(SettingsLine.getProps(Category.RESULT))
		for prop = 1:1:SettingsLine.getPropNumber()
	 
			% excluded props
			if any(prop == [])
				continue
			end
	 
			switch SettingsLine.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						st.isLocked(prop), ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						['SettingsLine.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~st.isLocked(prop), ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						['SettingsLine.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = SettingsLine();
	 
	for prop = 1:1:SettingsLine.getPropNumber()
		TAG = upper(SettingsLine.getPropTag(prop));
		assert( ...
			~st.isLocked(prop), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			['SettingsLine.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~st.isLocked(TAG), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			['SettingsLine.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	st.lock()
	 
	for prop = 1:1:SettingsLine.getPropNumber()
		switch SettingsLine.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					st.isLocked(prop), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~st.isLocked(prop), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = SettingsLine();
	 
	warning_backup = warning('off', 'BRAPH2:SettingsLine');
	for prop = 1:1:SettingsLine.getPropNumber()
		st.lock(prop)
		switch SettingsLine.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					st.isLocked(prop), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~st.isLocked(prop), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = SettingsLine();
	 
	for prop = 1:1:SettingsLine.getPropNumber()
		TAG = upper(SettingsLine.getPropTag(prop));
		assert( ...
			st.isChecked(prop), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			['SettingsLine.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			st.isChecked(TAG), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			['SettingsLine.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	st.unchecked()
	 
	for prop = 1:1:SettingsLine.getPropNumber()
		assert( ...
			~st.isChecked(prop), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			['SettingsLine.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	st.checked()
	 
	for prop = 1:1:SettingsLine.getPropNumber()
		assert( ...
			st.isChecked(prop), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			['SettingsLine.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic SettingsLine
	st_0 = SettingsLine( ...
		SettingsLine.ELCLASS, SettingsLine.getNoValue(), ...
		SettingsLine.NAME, SettingsLine.getNoValue(), ...
		SettingsLine.DESCRIPTION, SettingsLine.getNoValue(), ...
		SettingsLine.TEMPLATE, SettingsLine.getPropDefault(SettingsLine.TEMPLATE), ...
		SettingsLine.ID, SettingsLine.getPropDefault(SettingsLine.ID), ...
		SettingsLine.LABEL, SettingsLine.getPropDefault(SettingsLine.LABEL), ...
		SettingsLine.NOTES, SettingsLine.getPropDefault(SettingsLine.NOTES), ...
		SettingsLine.TOSTRING, SettingsLine.getNoValue(), ...
		SettingsLine.PANEL, SettingsLine.getPropDefault(SettingsLine.PANEL), ...
		SettingsLine.PROP, SettingsLine.getPropDefault(SettingsLine.PROP), ...
		SettingsLine.TAG, SettingsLine.getPropDefault(SettingsLine.TAG), ...
		SettingsLine.I, SettingsLine.getPropDefault(SettingsLine.I), ...
		SettingsLine.H, SettingsLine.getNoValue(), ...
		SettingsLine.SETUP, SettingsLine.getNoValue(), ...
		SettingsLine.VISIBLE, SettingsLine.getPropDefault(SettingsLine.VISIBLE), ...
		SettingsLine.X, SettingsLine.getPropDefault(SettingsLine.X), ...
		SettingsLine.Y, SettingsLine.getPropDefault(SettingsLine.Y), ...
		SettingsLine.Z, SettingsLine.getPropDefault(SettingsLine.Z), ...
		SettingsLine.LINESTYLE, SettingsLine.getPropDefault(SettingsLine.LINESTYLE), ...
		SettingsLine.LINEWIDTH, SettingsLine.getPropDefault(SettingsLine.LINEWIDTH), ...
		SettingsLine.LINECOLOR, SettingsLine.getPropDefault(SettingsLine.LINECOLOR), ...
		SettingsLine.SYMBOL, SettingsLine.getPropDefault(SettingsLine.SYMBOL), ...
		SettingsLine.SYMBOLSIZE, SettingsLine.getPropDefault(SettingsLine.SYMBOLSIZE), ...
		SettingsLine.EDGECOLOR, SettingsLine.getPropDefault(SettingsLine.EDGECOLOR), ...
		SettingsLine.FACECOLOR, SettingsLine.getPropDefault(SettingsLine.FACECOLOR) ...
		);
	 
	% SettingsLine with 1st callbacks
	st_1 = SettingsLine( ...
		SettingsLine.ELCLASS, SettingsLine.getNoValue(), ...
		SettingsLine.NAME, SettingsLine.getNoValue(), ...
		SettingsLine.DESCRIPTION, SettingsLine.getNoValue(), ...
		SettingsLine.TEMPLATE, st_0.getCallback(4), ..., ...
		SettingsLine.ID, st_0.getCallback(5), ..., ...
		SettingsLine.LABEL, SettingsLine.getPropDefault(SettingsLine.LABEL), ...
		SettingsLine.NOTES, SettingsLine.getPropDefault(SettingsLine.NOTES), ...
		SettingsLine.TOSTRING, SettingsLine.getNoValue(), ...
		SettingsLine.PANEL, st_0.getCallback(9), ..., ...
		SettingsLine.PROP, st_0.getCallback(10), ..., ...
		SettingsLine.TAG, st_0.getCallback(11), ..., ...
		SettingsLine.I, st_0.getCallback(12), ..., ...
		SettingsLine.H, SettingsLine.getNoValue(), ...
		SettingsLine.SETUP, SettingsLine.getNoValue(), ...
		SettingsLine.VISIBLE, st_0.getCallback(15), ..., ...
		SettingsLine.X, st_0.getCallback(16), ..., ...
		SettingsLine.Y, st_0.getCallback(17), ..., ...
		SettingsLine.Z, st_0.getCallback(18), ..., ...
		SettingsLine.LINESTYLE, st_0.getCallback(19), ..., ...
		SettingsLine.LINEWIDTH, st_0.getCallback(20), ..., ...
		SettingsLine.LINECOLOR, st_0.getCallback(21), ..., ...
		SettingsLine.SYMBOL, st_0.getCallback(22), ..., ...
		SettingsLine.SYMBOLSIZE, st_0.getCallback(23), ..., ...
		SettingsLine.EDGECOLOR, st_0.getCallback(24), ..., ...
		SettingsLine.FACECOLOR, st_0.getCallback(25) ... ...
		);
	 
	prop_number = SettingsLine.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(SettingsLine.getPropTag(prop));
		switch SettingsLine.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(st_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(st_1.get(prop), st_0.get(prop)) && ~isa(st_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(st_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% SettingsLine with 2nd callbacks
	st_2 = SettingsLine( ...
		SettingsLine.ELCLASS, SettingsLine.getNoValue(), ...
		SettingsLine.NAME, SettingsLine.getNoValue(), ...
		SettingsLine.DESCRIPTION, SettingsLine.getNoValue(), ...
		SettingsLine.TEMPLATE, st_1.getCallback(4), ..., ...
		SettingsLine.ID, st_1.getCallback(5), ..., ...
		SettingsLine.LABEL, SettingsLine.getPropDefault(SettingsLine.LABEL), ...
		SettingsLine.NOTES, SettingsLine.getPropDefault(SettingsLine.NOTES), ...
		SettingsLine.TOSTRING, SettingsLine.getNoValue(), ...
		SettingsLine.PANEL, st_1.getCallback(9), ..., ...
		SettingsLine.PROP, st_1.getCallback(10), ..., ...
		SettingsLine.TAG, st_1.getCallback(11), ..., ...
		SettingsLine.I, st_1.getCallback(12), ..., ...
		SettingsLine.H, SettingsLine.getNoValue(), ...
		SettingsLine.SETUP, SettingsLine.getNoValue(), ...
		SettingsLine.VISIBLE, st_1.getCallback(15), ..., ...
		SettingsLine.X, st_1.getCallback(16), ..., ...
		SettingsLine.Y, st_1.getCallback(17), ..., ...
		SettingsLine.Z, st_1.getCallback(18), ..., ...
		SettingsLine.LINESTYLE, st_1.getCallback(19), ..., ...
		SettingsLine.LINEWIDTH, st_1.getCallback(20), ..., ...
		SettingsLine.LINECOLOR, st_1.getCallback(21), ..., ...
		SettingsLine.SYMBOL, st_1.getCallback(22), ..., ...
		SettingsLine.SYMBOLSIZE, st_1.getCallback(23), ..., ...
		SettingsLine.EDGECOLOR, st_1.getCallback(24), ..., ...
		SettingsLine.FACECOLOR, st_1.getCallback(25) ... ...
		);
	 
	prop_number = SettingsLine.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(SettingsLine.getPropTag(prop));
		switch SettingsLine.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(st_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(st_2.get(prop), st_0.get(prop)) && ~isa(st_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(st_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% SettingsLine with 3rd callbacks
	st_3 = SettingsLine( ...
		SettingsLine.ELCLASS, SettingsLine.getNoValue(), ...
		SettingsLine.NAME, SettingsLine.getNoValue(), ...
		SettingsLine.DESCRIPTION, SettingsLine.getNoValue(), ...
		SettingsLine.TEMPLATE, st_2.getCallback(4), ..., ...
		SettingsLine.ID, st_2.getCallback(5), ..., ...
		SettingsLine.LABEL, SettingsLine.getPropDefault(SettingsLine.LABEL), ...
		SettingsLine.NOTES, SettingsLine.getPropDefault(SettingsLine.NOTES), ...
		SettingsLine.TOSTRING, SettingsLine.getNoValue(), ...
		SettingsLine.PANEL, st_2.getCallback(9), ..., ...
		SettingsLine.PROP, st_2.getCallback(10), ..., ...
		SettingsLine.TAG, st_2.getCallback(11), ..., ...
		SettingsLine.I, st_2.getCallback(12), ..., ...
		SettingsLine.H, SettingsLine.getNoValue(), ...
		SettingsLine.SETUP, SettingsLine.getNoValue(), ...
		SettingsLine.VISIBLE, st_2.getCallback(15), ..., ...
		SettingsLine.X, st_2.getCallback(16), ..., ...
		SettingsLine.Y, st_2.getCallback(17), ..., ...
		SettingsLine.Z, st_2.getCallback(18), ..., ...
		SettingsLine.LINESTYLE, st_2.getCallback(19), ..., ...
		SettingsLine.LINEWIDTH, st_2.getCallback(20), ..., ...
		SettingsLine.LINECOLOR, st_2.getCallback(21), ..., ...
		SettingsLine.SYMBOL, st_2.getCallback(22), ..., ...
		SettingsLine.SYMBOLSIZE, st_2.getCallback(23), ..., ...
		SettingsLine.EDGECOLOR, st_2.getCallback(24), ..., ...
		SettingsLine.FACECOLOR, st_2.getCallback(25) ... ...
		);
	 
	prop_number = SettingsLine.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(SettingsLine.getPropTag(prop));
		switch SettingsLine.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(st_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(st_3.get(prop), st_0.get(prop)) && ~isa(st_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(st_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	st = SettingsLine();
	 
	st_copy = st.copy();
	 
	assert(st_copy ~= st, ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'SettingsLine.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(st_copy, st), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'SettingsLine.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:SettingsLine.getPropNumber()
		value = st.getr(prop);
		value_copy = st_copy.getr(prop);
		switch SettingsLine.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					'SettingsLine.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						'SettingsLine.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						'SettingsLine.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						'SettingsLine.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
							'SettingsLine.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
							'SettingsLine.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						'SettingsLine.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					st_copy.isLocked(prop) == st.isLocked(prop), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					'SettingsLine.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					st_copy.isChecked(prop) == st.isChecked(prop), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					'SettingsLine.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					st_copy.getPropSeed(prop) == st.getPropSeed(prop), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					'SettingsLine.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	st = SettingsLine( ...
		SettingsLine.ELCLASS, SettingsLine.getNoValue(), ...
		SettingsLine.NAME, SettingsLine.getNoValue(), ...
		SettingsLine.DESCRIPTION, SettingsLine.getNoValue(), ...
		SettingsLine.TEMPLATE, SettingsLine.getPropDefault(SettingsLine.TEMPLATE), ...
		SettingsLine.ID, SettingsLine.getPropDefault(SettingsLine.ID), ...
		SettingsLine.LABEL, SettingsLine.getPropDefault(SettingsLine.LABEL), ...
		SettingsLine.NOTES, SettingsLine.getPropDefault(SettingsLine.NOTES), ...
		SettingsLine.TOSTRING, SettingsLine.getNoValue(), ...
		SettingsLine.PANEL, SettingsLine.getPropDefault(SettingsLine.PANEL), ...
		SettingsLine.PROP, SettingsLine.getPropDefault(SettingsLine.PROP), ...
		SettingsLine.TAG, SettingsLine.getPropDefault(SettingsLine.TAG), ...
		SettingsLine.I, SettingsLine.getPropDefault(SettingsLine.I), ...
		SettingsLine.H, SettingsLine.getNoValue(), ...
		SettingsLine.SETUP, SettingsLine.getNoValue(), ...
		SettingsLine.VISIBLE, SettingsLine.getPropDefault(SettingsLine.VISIBLE), ...
		SettingsLine.X, SettingsLine.getPropDefault(SettingsLine.X), ...
		SettingsLine.Y, SettingsLine.getPropDefault(SettingsLine.Y), ...
		SettingsLine.Z, SettingsLine.getPropDefault(SettingsLine.Z), ...
		SettingsLine.LINESTYLE, SettingsLine.getPropDefault(SettingsLine.LINESTYLE), ...
		SettingsLine.LINEWIDTH, SettingsLine.getPropDefault(SettingsLine.LINEWIDTH), ...
		SettingsLine.LINECOLOR, SettingsLine.getPropDefault(SettingsLine.LINECOLOR), ...
		SettingsLine.SYMBOL, SettingsLine.getPropDefault(SettingsLine.SYMBOL), ...
		SettingsLine.SYMBOLSIZE, SettingsLine.getPropDefault(SettingsLine.SYMBOLSIZE), ...
		SettingsLine.EDGECOLOR, SettingsLine.getPropDefault(SettingsLine.EDGECOLOR), ...
		SettingsLine.FACECOLOR, SettingsLine.getPropDefault(SettingsLine.FACECOLOR) ...
		);
	 
	for prop = 1:1:SettingsLine.getPropNumber()
		if SettingsLine.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':SettingsLine']);
			% st.memorize(prop);
			% warning(warning_backup)
		elseif SettingsLine.getPropCategory(prop) == Category.EVANESCENT && st.getPropFormat(prop) == Format.HANDLE
			st.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:SettingsLine');
			delete(ancestor(st.get(prop), 'figure'))
			warning(warning_backup)
		else
			st.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	st_copy = st.copy();
	 
	for prop = 1:1:SettingsLine.getPropNumber()
		value = st.getr(prop);
		value_copy = st_copy.getr(prop);
		switch SettingsLine.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					'SettingsLine.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						'SettingsLine.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						'SettingsLine.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						'SettingsLine.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
							'SettingsLine.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
							'SettingsLine.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						'SettingsLine.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						st_copy.isLocked(prop) == st.isLocked(prop), ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						'SettingsLine.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						st_copy.isChecked(prop) == st.isChecked(prop), ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						'SettingsLine.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						st_copy.getPropSeed(prop) == st.getPropSeed(prop), ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						'SettingsLine.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	st_0 = SettingsLine( ...
		SettingsLine.ELCLASS, SettingsLine.getNoValue(), ...
		SettingsLine.NAME, SettingsLine.getNoValue(), ...
		SettingsLine.DESCRIPTION, SettingsLine.getNoValue(), ...
		SettingsLine.TEMPLATE, SettingsLine.getPropDefault(SettingsLine.TEMPLATE), ...
		SettingsLine.ID, SettingsLine.getPropDefault(SettingsLine.ID), ...
		SettingsLine.LABEL, SettingsLine.getPropDefault(SettingsLine.LABEL), ...
		SettingsLine.NOTES, SettingsLine.getPropDefault(SettingsLine.NOTES), ...
		SettingsLine.TOSTRING, SettingsLine.getNoValue(), ...
		SettingsLine.PANEL, SettingsLine.getPropDefault(SettingsLine.PANEL), ...
		SettingsLine.PROP, SettingsLine.getPropDefault(SettingsLine.PROP), ...
		SettingsLine.TAG, SettingsLine.getPropDefault(SettingsLine.TAG), ...
		SettingsLine.I, SettingsLine.getPropDefault(SettingsLine.I), ...
		SettingsLine.H, SettingsLine.getNoValue(), ...
		SettingsLine.SETUP, SettingsLine.getNoValue(), ...
		SettingsLine.VISIBLE, SettingsLine.getPropDefault(SettingsLine.VISIBLE), ...
		SettingsLine.X, SettingsLine.getPropDefault(SettingsLine.X), ...
		SettingsLine.Y, SettingsLine.getPropDefault(SettingsLine.Y), ...
		SettingsLine.Z, SettingsLine.getPropDefault(SettingsLine.Z), ...
		SettingsLine.LINESTYLE, SettingsLine.getPropDefault(SettingsLine.LINESTYLE), ...
		SettingsLine.LINEWIDTH, SettingsLine.getPropDefault(SettingsLine.LINEWIDTH), ...
		SettingsLine.LINECOLOR, SettingsLine.getPropDefault(SettingsLine.LINECOLOR), ...
		SettingsLine.SYMBOL, SettingsLine.getPropDefault(SettingsLine.SYMBOL), ...
		SettingsLine.SYMBOLSIZE, SettingsLine.getPropDefault(SettingsLine.SYMBOLSIZE), ...
		SettingsLine.EDGECOLOR, SettingsLine.getPropDefault(SettingsLine.EDGECOLOR), ...
		SettingsLine.FACECOLOR, SettingsLine.getPropDefault(SettingsLine.FACECOLOR) ...
		);
	 
	st = SettingsLine( ...
		SettingsLine.ELCLASS, SettingsLine.getNoValue(), ...
		SettingsLine.NAME, SettingsLine.getNoValue(), ...
		SettingsLine.DESCRIPTION, SettingsLine.getNoValue(), ...
		SettingsLine.TEMPLATE, st_0.getCallback(4), ..., ...
		SettingsLine.ID, st_0.getCallback(5), ..., ...
		SettingsLine.LABEL, SettingsLine.getPropDefault(SettingsLine.LABEL), ...
		SettingsLine.NOTES, SettingsLine.getPropDefault(SettingsLine.NOTES), ...
		SettingsLine.TOSTRING, SettingsLine.getNoValue(), ...
		SettingsLine.PANEL, st_0.getCallback(9), ..., ...
		SettingsLine.PROP, st_0.getCallback(10), ..., ...
		SettingsLine.TAG, st_0.getCallback(11), ..., ...
		SettingsLine.I, st_0.getCallback(12), ..., ...
		SettingsLine.H, SettingsLine.getNoValue(), ...
		SettingsLine.SETUP, SettingsLine.getNoValue(), ...
		SettingsLine.VISIBLE, st_0.getCallback(15), ..., ...
		SettingsLine.X, st_0.getCallback(16), ..., ...
		SettingsLine.Y, st_0.getCallback(17), ..., ...
		SettingsLine.Z, st_0.getCallback(18), ..., ...
		SettingsLine.LINESTYLE, st_0.getCallback(19), ..., ...
		SettingsLine.LINEWIDTH, st_0.getCallback(20), ..., ...
		SettingsLine.LINECOLOR, st_0.getCallback(21), ..., ...
		SettingsLine.SYMBOL, st_0.getCallback(22), ..., ...
		SettingsLine.SYMBOLSIZE, st_0.getCallback(23), ..., ...
		SettingsLine.EDGECOLOR, st_0.getCallback(24), ..., ...
		SettingsLine.FACECOLOR, st_0.getCallback(25) ... ...
		);
	 
	st_copy = st.copy();
	st_0_copy = st_copy.getr('ID').get('EL');
	 
	for prop = 1:1:SettingsLine.getPropNumber()
		value = st.getr(prop);
		value_copy = st_copy.getr(prop);
		switch SettingsLine.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					'SettingsLine.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						'SettingsLine.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						'SettingsLine.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						'SettingsLine.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
							'SettingsLine.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
							'SettingsLine.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						'SettingsLine.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == st_0.getCallback(prop), ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						'SettingsLine.copy() does not work. The callback should be obtained from SettingsLine.getCallback().' ...
						)
					assert( ...
						value_copy == st_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						'SettingsLine.copy() does not work. The callback should be obtained from SettingsLine.getCallback().' ...
						)
				end
	 
					assert( ...
						st_copy.isLocked(prop) == st.isLocked(prop), ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						'SettingsLine.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						st_copy.isChecked(prop) == st.isChecked(prop), ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						'SettingsLine.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						st_copy.getPropSeed(prop) == st.getPropSeed(prop), ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						'SettingsLine.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st_template = SettingsLine();
	st = SettingsLine('TEMPLATE', st_template);
	 
	for prop = 1:1:SettingsLine.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(SettingsLine.getPropTag(prop));
		switch SettingsLine.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == SettingsLine.TEMPLATE
					assert( ...
						isa(st.getr(prop), 'SettingsLine'), ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						'SettingsLine TEMPLATE does not work. SettingsLine.getr(''TEMPLATE'') should be a SettingsLine element.' ...
						)
					assert( ...
						isa(st_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						'SettingsLine TEMPLATE does not work. SettingsLine_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(st.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						['SettingsLine TEMPLATE does not work. SettingsLine.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						st.getr(prop).get('EL') == st_template && st.getr(prop).get('PROP') == prop && strcmp(st.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						['SettingsLine TEMPLATE does not work. SettingsLine.getr(' TAG ') should be a Callback to st_template.' TAG '.'] ...
						)
					assert( ...
						isa(st_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
						['SettingsLine TEMPLATE does not work. SettingsLine_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(st.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine TEMPLATE does not work. SettingsLine.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(st_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
					['SettingsLine TEMPLATE does not work. SettingsLine_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = SettingsLine( ...
		SettingsLine.ELCLASS, SettingsLine.getNoValue(), ...
		SettingsLine.NAME, SettingsLine.getNoValue(), ...
		SettingsLine.DESCRIPTION, SettingsLine.getNoValue(), ...
		SettingsLine.TEMPLATE, SettingsLine.getPropDefault(SettingsLine.TEMPLATE), ...
		SettingsLine.ID, SettingsLine.getPropDefault(SettingsLine.ID), ...
		SettingsLine.LABEL, SettingsLine.getPropDefault(SettingsLine.LABEL), ...
		SettingsLine.NOTES, SettingsLine.getPropDefault(SettingsLine.NOTES), ...
		SettingsLine.TOSTRING, SettingsLine.getNoValue(), ...
		SettingsLine.PANEL, SettingsLine.getPropDefault(SettingsLine.PANEL), ...
		SettingsLine.PROP, SettingsLine.getPropDefault(SettingsLine.PROP), ...
		SettingsLine.TAG, SettingsLine.getPropDefault(SettingsLine.TAG), ...
		SettingsLine.I, SettingsLine.getPropDefault(SettingsLine.I), ...
		SettingsLine.H, SettingsLine.getNoValue(), ...
		SettingsLine.SETUP, SettingsLine.getNoValue(), ...
		SettingsLine.VISIBLE, SettingsLine.getPropDefault(SettingsLine.VISIBLE), ...
		SettingsLine.X, SettingsLine.getPropDefault(SettingsLine.X), ...
		SettingsLine.Y, SettingsLine.getPropDefault(SettingsLine.Y), ...
		SettingsLine.Z, SettingsLine.getPropDefault(SettingsLine.Z), ...
		SettingsLine.LINESTYLE, SettingsLine.getPropDefault(SettingsLine.LINESTYLE), ...
		SettingsLine.LINEWIDTH, SettingsLine.getPropDefault(SettingsLine.LINEWIDTH), ...
		SettingsLine.LINECOLOR, SettingsLine.getPropDefault(SettingsLine.LINECOLOR), ...
		SettingsLine.SYMBOL, SettingsLine.getPropDefault(SettingsLine.SYMBOL), ...
		SettingsLine.SYMBOLSIZE, SettingsLine.getPropDefault(SettingsLine.SYMBOLSIZE), ...
		SettingsLine.EDGECOLOR, SettingsLine.getPropDefault(SettingsLine.EDGECOLOR), ...
		SettingsLine.FACECOLOR, SettingsLine.getPropDefault(SettingsLine.FACECOLOR) ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'settingsline_to_be_erased.b2'];
	 
	Element.save(st, filename)
	 
	st_loaded = Element.load(filename);
	 
	assert( ...
		isequal(st.copy(), st_loaded), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'SettingsLine.save(st) and/or SettingsLine.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = SettingsLine( ...
		SettingsLine.ELCLASS, SettingsLine.getNoValue(), ...
		SettingsLine.NAME, SettingsLine.getNoValue(), ...
		SettingsLine.DESCRIPTION, SettingsLine.getNoValue(), ...
		SettingsLine.TEMPLATE, SettingsLine.getPropDefault(SettingsLine.TEMPLATE), ...
		SettingsLine.ID, SettingsLine.getPropDefault(SettingsLine.ID), ...
		SettingsLine.LABEL, SettingsLine.getPropDefault(SettingsLine.LABEL), ...
		SettingsLine.NOTES, SettingsLine.getPropDefault(SettingsLine.NOTES), ...
		SettingsLine.TOSTRING, SettingsLine.getNoValue(), ...
		SettingsLine.PANEL, SettingsLine.getPropDefault(SettingsLine.PANEL), ...
		SettingsLine.PROP, SettingsLine.getPropDefault(SettingsLine.PROP), ...
		SettingsLine.TAG, SettingsLine.getPropDefault(SettingsLine.TAG), ...
		SettingsLine.I, SettingsLine.getPropDefault(SettingsLine.I), ...
		SettingsLine.H, SettingsLine.getNoValue(), ...
		SettingsLine.SETUP, SettingsLine.getNoValue(), ...
		SettingsLine.VISIBLE, SettingsLine.getPropDefault(SettingsLine.VISIBLE), ...
		SettingsLine.X, SettingsLine.getPropDefault(SettingsLine.X), ...
		SettingsLine.Y, SettingsLine.getPropDefault(SettingsLine.Y), ...
		SettingsLine.Z, SettingsLine.getPropDefault(SettingsLine.Z), ...
		SettingsLine.LINESTYLE, SettingsLine.getPropDefault(SettingsLine.LINESTYLE), ...
		SettingsLine.LINEWIDTH, SettingsLine.getPropDefault(SettingsLine.LINEWIDTH), ...
		SettingsLine.LINECOLOR, SettingsLine.getPropDefault(SettingsLine.LINECOLOR), ...
		SettingsLine.SYMBOL, SettingsLine.getPropDefault(SettingsLine.SYMBOL), ...
		SettingsLine.SYMBOLSIZE, SettingsLine.getPropDefault(SettingsLine.SYMBOLSIZE), ...
		SettingsLine.EDGECOLOR, SettingsLine.getPropDefault(SettingsLine.EDGECOLOR), ...
		SettingsLine.FACECOLOR, SettingsLine.getPropDefault(SettingsLine.FACECOLOR) ...
		);
	 
	[json, struct, el_list] = encodeJSON(st);
	[st_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(st_dec ~= st, ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		'SettingsLine.encodeJSON() or SettingsLine.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) SettingsLine.getPropFormat(prop), num2cell(SettingsLine.getProps())) == Format.HANDLE) && all(cellfun(@(prop) SettingsLine.getPropFormat(prop), num2cell(SettingsLine.getProps())) == Format.NET)
		assert(isequal(st_dec, st), ...
			[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
			'SettingsLine.encodeJSON() or SettingsLine.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':SettingsLine:' BRAPH2.FAIL_TEST], ...
		[' When testing SettingsLine no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 13: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

