%TEST_SETTINGSAMBIENT

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	st = SettingsAmbient();
	 
	% get('ELCLASS')
	if isa(SettingsAmbient, 'ConcreteElement')
		assert(strcmp(SettingsAmbient().get('ELCLASS'), 'SettingsAmbient'), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'SettingsAmbient().get(''ELCLASS'') should return ''SettingsAmbient''.')
	end
	 
	% getBuild()
	assert(SettingsAmbient.getBuild() == 1 && SettingsAmbient.getBuild() > 0, ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'SettingsAmbient.getBuild() should return the SettingsAmbient build number.')
	assert(st.getBuild() == 1 && st.getBuild() > 0 , ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'st.getBuild() should return the SettingsAmbient build number.')
	assert(Element.getBuild(st) == 1 && Element.getBuild(st) > 0, ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(st) should return the SettingsAmbient build number.')
	assert(Element.getBuild('SettingsAmbient') == 1 && Element.getBuild('SettingsAmbient') > 0, ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''SettingsAmbient'') should return the SettingsAmbient build number.')
	 
	% getClass()
	assert(strcmp(SettingsAmbient.getClass(), 'SettingsAmbient'), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'SettingsAmbient.getClass() should return ''SettingsAmbient''.')
	assert(strcmp(st.getClass(), 'SettingsAmbient'), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'st.getClass() should return ''SettingsAmbient''.')
	assert(strcmp(Element.getClass(st), 'SettingsAmbient'), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(st) should return ''SettingsAmbient''.')
	assert(strcmp(Element.getClass('SettingsAmbient'), 'SettingsAmbient'), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''SettingsAmbient'') should return ''SettingsAmbient''.')
	 
	% getSubclasses()
	assert(isequal(SettingsAmbient.getSubclasses(), subclasses('SettingsAmbient', [], [], true)), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'SettingsAmbient.getSubclasses() should return the same result as subclasses(''SettingsAmbient'', [], [], true).')
	assert(isequal(st.getSubclasses(), subclasses('SettingsAmbient', [], [], true)), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''SettingsAmbient'', [], [], true).')
	assert(isequal(Element.getSubclasses(st), subclasses('SettingsAmbient', [], [], true)), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(st) should return the same result as subclasses(''SettingsAmbient'', [], [], true).')
	assert(isequal(Element.getSubclasses('SettingsAmbient'), subclasses('SettingsAmbient', [], [], true)), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''SettingsAmbient'') should return the same result as subclasses(''SettingsAmbient'', [], [], true).')
	 
	% getProps()
	assert(isempty(SettingsAmbient.getProps()) || isequal(SettingsAmbient.getProps(), 1:1:length(SettingsAmbient.getProps())), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'SettingsAmbient.getProps() should return a row vector [1:1:N].')
	assert(isempty(SettingsAmbient.getProps()) || isequal(st.getProps(), 1:1:length(SettingsAmbient.getProps())), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'st.getProps() should return a row vector [1:1:N].')
	assert(isempty(SettingsAmbient.getProps()) || isequal(Element.getProps(st), 1:1:length(SettingsAmbient.getProps())), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(st) should return a row vector [1:1:N].')
	assert(isempty(SettingsAmbient.getProps()) || isequal(Element.getProps('SettingsAmbient'), 1:1:length(SettingsAmbient.getProps())), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''SettingsAmbient'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) SettingsAmbient.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(SettingsAmbient.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(SettingsAmbient.getProps())), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'SettingsAmbient.getProps(category) does not work.')
	tmp = cellfun(@(category) st.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(SettingsAmbient.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(SettingsAmbient.getProps())), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'st.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(st, category), categories, 'UniformOutput', false);
	assert(isempty(SettingsAmbient.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(SettingsAmbient.getProps())), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(st, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('SettingsAmbient', category), categories, 'UniformOutput', false);
	assert(isempty(SettingsAmbient.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(SettingsAmbient.getProps())), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''SettingsAmbient'', category) does not work.')
	 
	% getPropNumber()
	assert(SettingsAmbient.getPropNumber() == length(SettingsAmbient.getProps()), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'SettingsAmbient.getPropNumber() should return the number of properties.')
	assert(st.getPropNumber() == length(SettingsAmbient.getProps()), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'st.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(st) == length(SettingsAmbient.getProps()), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(st) should return the number of properties.')
	assert(Element.getPropNumber('SettingsAmbient') == length(SettingsAmbient.getProps()), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''SettingsAmbient'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) SettingsAmbient.getPropNumber(category), categories)) == SettingsAmbient.getPropNumber(), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'SettingsAmbient.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) st.getPropNumber(category), categories)) == SettingsAmbient.getPropNumber(), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'st.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(st, category), categories)) == SettingsAmbient.getPropNumber(), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(st, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('SettingsAmbient', category), categories)) == SettingsAmbient.getPropNumber(), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''SettingsAmbient'', category) does not work.')
	 
	% existsProp(prop)
	assert(~SettingsAmbient.existsProp(NaN), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'SettingsAmbient.existsProp(prop) does not work.')
	assert(~st.existsProp(NaN), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'st.existsProp(prop) does not work.')
	assert(~Element.existsProp(st, NaN), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(st, prop) does not work.')
	assert(~Element.existsProp('SettingsAmbient', NaN), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''SettingsAmbient'', prop) does not work.')
	 
	assert_with_error('SettingsAmbient.existsProp(NaN)', [BRAPH2.STR ':SettingsAmbient:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':SettingsAmbient:' BRAPH2.WRONG_INPUT], st)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':SettingsAmbient:' BRAPH2.WRONG_INPUT], st)
	assert_with_error('Element.existsProp(''SettingsAmbient'', NaN)', [BRAPH2.STR ':SettingsAmbient:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:SettingsAmbient.getPropNumber()
		assert(SettingsAmbient.existsProp(prop), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'SettingsAmbient.existsProp(prop) does not work.')
		assert(st.existsProp(prop), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'st.existsProp(prop) does not work.')
		assert(Element.existsProp(st, prop), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(st, prop) does not work.')
		assert(Element.existsProp('SettingsAmbient', prop), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''SettingsAmbient'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~SettingsAmbient.existsTag(''), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'SettingsAmbient.existsTag(tag) does not work.')
	assert(~st.existsTag(''), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'st.existsTag(tag) does not work.')
	assert(~Element.existsTag(st, ''), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(st, tag) does not work.')
	assert(~Element.existsTag('SettingsAmbient', ''), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''SettingsAmbient'', tag) does not work.')
	 
	assert_with_error('SettingsAmbient.existsTag('''')', [BRAPH2.STR ':SettingsAmbient:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':SettingsAmbient:' BRAPH2.WRONG_INPUT], st)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':SettingsAmbient:' BRAPH2.WRONG_INPUT], st)
	assert_with_error('Element.existsTag(''SettingsAmbient'', '''')', [BRAPH2.STR ':SettingsAmbient:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:SettingsAmbient.getPropNumber()
		tag = st.getPropTag(prop);
		assert(SettingsAmbient.existsTag(tag), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'SettingsAmbient.existsTag(tag) does not work.')
		assert(st.existsTag(tag), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'st.existsTag(tag) does not work.')
		assert(Element.existsTag(st, tag), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(st, tga) does not work.')
		assert(Element.existsTag('SettingsAmbient', tag), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''SettingsAmbient'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:SettingsAmbient.getPropNumber()
		assert(SettingsAmbient.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'SettingsAmbient.getPropProp(prop) does not work.')
		assert(st.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'st.getPropProp(prop) does not work.')
		assert(Element.getPropProp(st, prop) == prop, ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(st, prop) does not work.')
		assert(Element.getPropProp('SettingsAmbient', prop) == prop, ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''SettingsAmbient'', prop) does not work.')
	 
		tag = st.getPropTag(prop);
		assert(SettingsAmbient.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'SettingsAmbient.getPropProp(tag) does not work.')
		assert(st.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'st.getPropProp(tag) does not work.')
		assert(Element.getPropProp(st, tag) == prop, ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(st, tag) does not work.')
		assert(Element.getPropProp('SettingsAmbient', prop) == prop, ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''SettingsAmbient'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:SettingsAmbient.getPropNumber()
		tag = st.getPropTag(prop);
	 
		assert(strcmp(SettingsAmbient.getPropTag(prop), tag), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'SettingsAmbient.getPropTag(prop) does not work.')
		assert(strcmp(st.getPropTag(prop), tag), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'st.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(st, prop), tag), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(st, prop) does not work.')
		assert(strcmp(Element.getPropTag('SettingsAmbient', prop), tag), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''SettingsAmbient'', prop) does not work.')
	 
		assert(strcmp(SettingsAmbient.getPropTag(tag), tag), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'SettingsAmbient.getPropTag(tag) does not work.')
		assert(strcmp(st.getPropTag(tag), tag), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'st.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(st, tag), tag), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(st, tag) does not work.')
		assert(strcmp(Element.getPropTag('SettingsAmbient', prop), tag), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''SettingsAmbient'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:SettingsAmbient.getPropNumber()
		tag = st.getPropTag(prop);
	 
		assert(Category.existsCategory(SettingsAmbient.getPropCategory(prop)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'SettingsAmbient.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(st.getPropCategory(prop)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'st.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(st, prop)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(st, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(st, prop)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''SettingsAmbient'', prop) does not work.')
	 
		assert(Category.existsCategory(SettingsAmbient.getPropCategory(tag)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'SettingsAmbient.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(st.getPropCategory(tag)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'st.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(st, tag)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(st, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(st, tag)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''SettingsAmbient'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:SettingsAmbient.getPropNumber()
		tag = st.getPropTag(prop);
	 
		assert(Format.existsFormat(SettingsAmbient.getPropFormat(prop)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'SettingsAmbient.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(st.getPropFormat(prop)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'st.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(st, prop)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(st, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(st, prop)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''SettingsAmbient'', prop) does not work.')
	 
		assert(Format.existsFormat(SettingsAmbient.getPropFormat(tag)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'SettingsAmbient.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(st.getPropFormat(tag)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'st.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(st, tag)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(st, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(st, tag)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''SettingsAmbient'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:SettingsAmbient.getPropNumber()
		tag = st.getPropTag(prop);
	 
		assert(ischar(SettingsAmbient.getPropDescription(prop)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'SettingsAmbient.getPropDescription(prop) does not work.')
		assert(ischar(st.getPropDescription(prop)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'st.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(st, prop)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(st, prop) does not work.')
		assert(ischar(Element.getPropDescription(st, prop)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''SettingsAmbient'', prop) does not work.')
	 
		assert(ischar(SettingsAmbient.getPropDescription(tag)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'SettingsAmbient.getPropDescription(tag) does not work.')
		assert(ischar(st.getPropDescription(tag)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'st.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(st, tag)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(st, tag) does not work.')
		assert(ischar(Element.getPropDescription(st, tag)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''SettingsAmbient'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:SettingsAmbient.getPropNumber()
		tag = st.getPropTag(prop);
	 
		settings = SettingsAmbient.getPropSettings(prop);
		settings = st.getPropSettings(prop);
		settings = Element.getPropSettings(st, prop);
		settings = Element.getPropSettings('SettingsAmbient', prop);
	 
		settings = SettingsAmbient.getPropSettings(tag);
		settings = st.getPropSettings(tag);
		settings = Element.getPropSettings(st, tag);
		settings = Element.getPropSettings('SettingsAmbient', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:SettingsAmbient.getPropNumber()
		tag = st.getPropTag(prop);
	 
		default = SettingsAmbient.getPropDefault(prop);
		default = st.getPropDefault(prop);
		default = Element.getPropDefault(st, prop);
		default = Element.getPropDefault('SettingsAmbient', prop);
	 
		default = SettingsAmbient.getPropDefault(tag);
		default = st.getPropDefault(tag);
		default = Element.getPropDefault(st, tag);
		default = Element.getPropDefault('SettingsAmbient', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:SettingsAmbient.getPropNumber()
		tag = st.getPropTag(prop);
	 
		conditioned_default = SettingsAmbient.getPropDefaultConditioned(prop);
		conditioned_default = st.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(st, prop);
		conditioned_default = Element.getPropDefaultConditioned('SettingsAmbient', prop);
	 
		conditioned_default = SettingsAmbient.getPropDefaultConditioned(tag);
		conditioned_default = st.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(st, tag);
		conditioned_default = Element.getPropDefaultConditioned('SettingsAmbient', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:SettingsAmbient.getPropNumber()
		tag = st.getPropTag(prop);
	 
		assert(~SettingsAmbient.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'SettingsAmbient.checkProp(prop, value) does not work.')
		assert(~st.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'st.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(st, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(st, prop, value) does not work.')
		assert(~Element.checkProp('SettingsAmbient', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''SettingsAmbient'', prop, value) does not work.')
	 
		assert_with_error('SettingsAmbient.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SettingsAmbient:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SettingsAmbient:' BRAPH2.WRONG_INPUT], prop, st)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SettingsAmbient:' BRAPH2.WRONG_INPUT], prop, st)
		assert_with_error('Element.checkProp(''SettingsAmbient'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SettingsAmbient:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~SettingsAmbient.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'SettingsAmbient.checkProp(tag, value) does not work.')
		assert(~st.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'st.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(st, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(st, tag, value) does not work.')
		assert(~Element.checkProp('SettingsAmbient', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''SettingsAmbient'', tag, value) does not work.')
	 
		assert_with_error('SettingsAmbient.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SettingsAmbient:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SettingsAmbient:' BRAPH2.WRONG_INPUT], tag, st)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SettingsAmbient:' BRAPH2.WRONG_INPUT], tag, st)
		assert_with_error('Element.checkProp(''SettingsAmbient'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SettingsAmbient:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(SettingsAmbient.checkProp(prop, Element.getPropDefaultConditioned(SettingsAmbient, prop)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'SettingsAmbient.checkProp(prop, <conditioned default value>) does not work.')
		assert(st.checkProp(prop, Element.getPropDefaultConditioned(SettingsAmbient, prop)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'st.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(st, prop, Element.getPropDefaultConditioned(SettingsAmbient, prop)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(st, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('SettingsAmbient', prop, Element.getPropDefaultConditioned(SettingsAmbient, prop)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''SettingsAmbient'', prop, <conditioned default value>) does not work.')
	 
		assert(SettingsAmbient.checkProp(tag, Element.getPropDefaultConditioned(SettingsAmbient, prop)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'SettingsAmbient.checkProp(tag, <conditioned default value>) does not work.')
		assert(st.checkProp(tag, Element.getPropDefaultConditioned(SettingsAmbient, prop)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'st.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(st, tag, Element.getPropDefaultConditioned(SettingsAmbient, prop)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(st, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('SettingsAmbient', tag, Element.getPropDefaultConditioned(SettingsAmbient, prop)), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''SettingsAmbient'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = SettingsAmbient( ...
		SettingsAmbient.ELCLASS, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.NAME, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.DESCRIPTION, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.TEMPLATE, SettingsAmbient.getPropDefault(SettingsAmbient.TEMPLATE), ...
		SettingsAmbient.ID, SettingsAmbient.getPropDefault(SettingsAmbient.ID), ...
		SettingsAmbient.LABEL, SettingsAmbient.getPropDefault(SettingsAmbient.LABEL), ...
		SettingsAmbient.NOTES, SettingsAmbient.getPropDefault(SettingsAmbient.NOTES), ...
		SettingsAmbient.TOSTRING, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.PANEL, SettingsAmbient.getPropDefault(SettingsAmbient.PANEL), ...
		SettingsAmbient.PROP, SettingsAmbient.getPropDefault(SettingsAmbient.PROP), ...
		SettingsAmbient.TAG, SettingsAmbient.getPropDefault(SettingsAmbient.TAG), ...
		SettingsAmbient.I, SettingsAmbient.getPropDefault(SettingsAmbient.I), ...
		SettingsAmbient.H, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.SETUP, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.LIGHTING, SettingsAmbient.getPropDefault(SettingsAmbient.LIGHTING), ...
		SettingsAmbient.MATERIAL, SettingsAmbient.getPropDefault(SettingsAmbient.MATERIAL), ...
		SettingsAmbient.CAMLIGHT, SettingsAmbient.getPropDefault(SettingsAmbient.CAMLIGHT), ...
		SettingsAmbient.SHADING, SettingsAmbient.getPropDefault(SettingsAmbient.SHADING), ...
		SettingsAmbient.COLORMAP, SettingsAmbient.getPropDefault(SettingsAmbient.COLORMAP) ...
		);
	 
	for prop = 1:1:SettingsAmbient.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(SettingsAmbient.getPropTag(prop));
		switch SettingsAmbient.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					st.getr(prop) == SettingsAmbient.getNoValue(), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['Being a ' SettingsAmbient.getCategoryName(SettingsAmbient.getPropCategory(prop)) ', SettingsAmbient.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in SettingsAmbient.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					st.getr(TAG) == SettingsAmbient.getNoValue(), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['Being a ' SettingsAmbient.getCategoryName(SettingsAmbient.getPropCategory(prop)) ', SettingsAmbient.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in SettingsAmbient.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(st.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(st.getPropSettings(prop))
					assert( ...
						st.checkFormat(st.getPropFormat(prop), st.get(prop)), ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						['SettingsAmbient.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						st.checkFormat(st.getPropFormat(prop), st.get(prop), st.getPropSettings(prop)), ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						['SettingsAmbient.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					st.getr(prop) == SettingsAmbient.getNoValue(), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['Being a ' SettingsAmbient.getCategoryName(SettingsAmbient.getPropCategory(prop)) ', SettingsAmbient.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in SettingsAmbient.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					st.getr(TAG) == SettingsAmbient.getNoValue(), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['Being a ' SettingsAmbient.getCategoryName(SettingsAmbient.getPropCategory(prop)) ', SettingsAmbient.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in SettingsAmbient.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':SettingsAmbient']);
				assert( ...
					~isa(st.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(st.getPropSettings(prop))
					assert( ...
						st.checkFormat(st.getPropFormat(prop), st.get(prop)), ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						['SettingsAmbient.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						st.checkFormat(st.getPropFormat(prop), st.get(prop), st.getPropSettings(prop)), ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						['SettingsAmbient.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(st.getr(prop), SettingsAmbient.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by SettingsAmbient.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in SettingsAmbient.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(st.getr(TAG), SettingsAmbient.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.getr(' TAG ') must be inizialized to its default value ' ...
					'given by SettingsAmbient.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in SettingsAmbient.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = SettingsAmbient( ...
		SettingsAmbient.ELCLASS, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.NAME, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.DESCRIPTION, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.TEMPLATE, SettingsAmbient.getPropDefault(SettingsAmbient.TEMPLATE), ...
		SettingsAmbient.ID, SettingsAmbient.getPropDefault(SettingsAmbient.ID), ...
		SettingsAmbient.LABEL, SettingsAmbient.getPropDefault(SettingsAmbient.LABEL), ...
		SettingsAmbient.NOTES, SettingsAmbient.getPropDefault(SettingsAmbient.NOTES), ...
		SettingsAmbient.TOSTRING, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.PANEL, SettingsAmbient.getPropDefault(SettingsAmbient.PANEL), ...
		SettingsAmbient.PROP, SettingsAmbient.getPropDefault(SettingsAmbient.PROP), ...
		SettingsAmbient.TAG, SettingsAmbient.getPropDefault(SettingsAmbient.TAG), ...
		SettingsAmbient.I, SettingsAmbient.getPropDefault(SettingsAmbient.I), ...
		SettingsAmbient.H, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.SETUP, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.LIGHTING, SettingsAmbient.getPropDefault(SettingsAmbient.LIGHTING), ...
		SettingsAmbient.MATERIAL, SettingsAmbient.getPropDefault(SettingsAmbient.MATERIAL), ...
		SettingsAmbient.CAMLIGHT, SettingsAmbient.getPropDefault(SettingsAmbient.CAMLIGHT), ...
		SettingsAmbient.SHADING, SettingsAmbient.getPropDefault(SettingsAmbient.SHADING), ...
		SettingsAmbient.COLORMAP, SettingsAmbient.getPropDefault(SettingsAmbient.COLORMAP) ...
		);
	 
	for prop = 1:1:SettingsAmbient.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(SettingsAmbient.getPropTag(prop));
		switch SettingsAmbient.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(st.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(st.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(st.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(st.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					st.checkFormat(st.getPropFormat(prop), st.getr(prop),st.getPropSettings(prop)), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':SettingsAmbient']);
				assert( ...
					~isa(st.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(st.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':SettingsAmbient']);
	% 			assert( ...
	% 				~isa(st.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
	% 				['SettingsAmbient.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(st.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
	% 				['SettingsAmbient.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				st.checkFormat(st.getPropFormat(prop), st.getr(prop),st.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
	% 				['SettingsAmbient.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':SettingsAmbient']);
				assert( ...
					~isa(st.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(st.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(st.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(st.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					st.checkFormat(st.getPropFormat(prop), st.getr(prop),st.getPropSettings(prop)), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if st.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:SettingsAmbient');
					delete(ancestor(st.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(SettingsAmbient.getProps(Category.RESULT))
		for prop = 1:1:SettingsAmbient.getPropNumber()
	 
			% excluded props
			if any(prop == [])
				continue
			end
	 
			switch SettingsAmbient.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						st.isLocked(prop), ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						['SettingsAmbient.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~st.isLocked(prop), ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						['SettingsAmbient.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = SettingsAmbient();
	 
	for prop = 1:1:SettingsAmbient.getPropNumber()
		TAG = upper(SettingsAmbient.getPropTag(prop));
		assert( ...
			~st.isLocked(prop), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			['SettingsAmbient.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~st.isLocked(TAG), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			['SettingsAmbient.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	st.lock()
	 
	for prop = 1:1:SettingsAmbient.getPropNumber()
		switch SettingsAmbient.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					st.isLocked(prop), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~st.isLocked(prop), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = SettingsAmbient();
	 
	warning_backup = warning('off', 'BRAPH2:SettingsAmbient');
	for prop = 1:1:SettingsAmbient.getPropNumber()
		st.lock(prop)
		switch SettingsAmbient.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					st.isLocked(prop), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~st.isLocked(prop), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = SettingsAmbient();
	 
	for prop = 1:1:SettingsAmbient.getPropNumber()
		TAG = upper(SettingsAmbient.getPropTag(prop));
		assert( ...
			st.isChecked(prop), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			['SettingsAmbient.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			st.isChecked(TAG), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			['SettingsAmbient.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	st.unchecked()
	 
	for prop = 1:1:SettingsAmbient.getPropNumber()
		assert( ...
			~st.isChecked(prop), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			['SettingsAmbient.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	st.checked()
	 
	for prop = 1:1:SettingsAmbient.getPropNumber()
		assert( ...
			st.isChecked(prop), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			['SettingsAmbient.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic SettingsAmbient
	st_0 = SettingsAmbient( ...
		SettingsAmbient.ELCLASS, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.NAME, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.DESCRIPTION, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.TEMPLATE, SettingsAmbient.getPropDefault(SettingsAmbient.TEMPLATE), ...
		SettingsAmbient.ID, SettingsAmbient.getPropDefault(SettingsAmbient.ID), ...
		SettingsAmbient.LABEL, SettingsAmbient.getPropDefault(SettingsAmbient.LABEL), ...
		SettingsAmbient.NOTES, SettingsAmbient.getPropDefault(SettingsAmbient.NOTES), ...
		SettingsAmbient.TOSTRING, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.PANEL, SettingsAmbient.getPropDefault(SettingsAmbient.PANEL), ...
		SettingsAmbient.PROP, SettingsAmbient.getPropDefault(SettingsAmbient.PROP), ...
		SettingsAmbient.TAG, SettingsAmbient.getPropDefault(SettingsAmbient.TAG), ...
		SettingsAmbient.I, SettingsAmbient.getPropDefault(SettingsAmbient.I), ...
		SettingsAmbient.H, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.SETUP, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.LIGHTING, SettingsAmbient.getPropDefault(SettingsAmbient.LIGHTING), ...
		SettingsAmbient.MATERIAL, SettingsAmbient.getPropDefault(SettingsAmbient.MATERIAL), ...
		SettingsAmbient.CAMLIGHT, SettingsAmbient.getPropDefault(SettingsAmbient.CAMLIGHT), ...
		SettingsAmbient.SHADING, SettingsAmbient.getPropDefault(SettingsAmbient.SHADING), ...
		SettingsAmbient.COLORMAP, SettingsAmbient.getPropDefault(SettingsAmbient.COLORMAP) ...
		);
	 
	% SettingsAmbient with 1st callbacks
	st_1 = SettingsAmbient( ...
		SettingsAmbient.ELCLASS, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.NAME, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.DESCRIPTION, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.TEMPLATE, st_0.getCallback(4), ..., ...
		SettingsAmbient.ID, st_0.getCallback(5), ..., ...
		SettingsAmbient.LABEL, SettingsAmbient.getPropDefault(SettingsAmbient.LABEL), ...
		SettingsAmbient.NOTES, SettingsAmbient.getPropDefault(SettingsAmbient.NOTES), ...
		SettingsAmbient.TOSTRING, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.PANEL, st_0.getCallback(9), ..., ...
		SettingsAmbient.PROP, st_0.getCallback(10), ..., ...
		SettingsAmbient.TAG, st_0.getCallback(11), ..., ...
		SettingsAmbient.I, st_0.getCallback(12), ..., ...
		SettingsAmbient.H, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.SETUP, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.LIGHTING, st_0.getCallback(15), ..., ...
		SettingsAmbient.MATERIAL, st_0.getCallback(16), ..., ...
		SettingsAmbient.CAMLIGHT, st_0.getCallback(17), ..., ...
		SettingsAmbient.SHADING, st_0.getCallback(18), ..., ...
		SettingsAmbient.COLORMAP, st_0.getCallback(19) ... ...
		);
	 
	prop_number = SettingsAmbient.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(SettingsAmbient.getPropTag(prop));
		switch SettingsAmbient.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(st_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(st_1.get(prop), st_0.get(prop)) && ~isa(st_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(st_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% SettingsAmbient with 2nd callbacks
	st_2 = SettingsAmbient( ...
		SettingsAmbient.ELCLASS, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.NAME, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.DESCRIPTION, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.TEMPLATE, st_1.getCallback(4), ..., ...
		SettingsAmbient.ID, st_1.getCallback(5), ..., ...
		SettingsAmbient.LABEL, SettingsAmbient.getPropDefault(SettingsAmbient.LABEL), ...
		SettingsAmbient.NOTES, SettingsAmbient.getPropDefault(SettingsAmbient.NOTES), ...
		SettingsAmbient.TOSTRING, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.PANEL, st_1.getCallback(9), ..., ...
		SettingsAmbient.PROP, st_1.getCallback(10), ..., ...
		SettingsAmbient.TAG, st_1.getCallback(11), ..., ...
		SettingsAmbient.I, st_1.getCallback(12), ..., ...
		SettingsAmbient.H, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.SETUP, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.LIGHTING, st_1.getCallback(15), ..., ...
		SettingsAmbient.MATERIAL, st_1.getCallback(16), ..., ...
		SettingsAmbient.CAMLIGHT, st_1.getCallback(17), ..., ...
		SettingsAmbient.SHADING, st_1.getCallback(18), ..., ...
		SettingsAmbient.COLORMAP, st_1.getCallback(19) ... ...
		);
	 
	prop_number = SettingsAmbient.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(SettingsAmbient.getPropTag(prop));
		switch SettingsAmbient.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(st_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(st_2.get(prop), st_0.get(prop)) && ~isa(st_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(st_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% SettingsAmbient with 3rd callbacks
	st_3 = SettingsAmbient( ...
		SettingsAmbient.ELCLASS, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.NAME, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.DESCRIPTION, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.TEMPLATE, st_2.getCallback(4), ..., ...
		SettingsAmbient.ID, st_2.getCallback(5), ..., ...
		SettingsAmbient.LABEL, SettingsAmbient.getPropDefault(SettingsAmbient.LABEL), ...
		SettingsAmbient.NOTES, SettingsAmbient.getPropDefault(SettingsAmbient.NOTES), ...
		SettingsAmbient.TOSTRING, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.PANEL, st_2.getCallback(9), ..., ...
		SettingsAmbient.PROP, st_2.getCallback(10), ..., ...
		SettingsAmbient.TAG, st_2.getCallback(11), ..., ...
		SettingsAmbient.I, st_2.getCallback(12), ..., ...
		SettingsAmbient.H, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.SETUP, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.LIGHTING, st_2.getCallback(15), ..., ...
		SettingsAmbient.MATERIAL, st_2.getCallback(16), ..., ...
		SettingsAmbient.CAMLIGHT, st_2.getCallback(17), ..., ...
		SettingsAmbient.SHADING, st_2.getCallback(18), ..., ...
		SettingsAmbient.COLORMAP, st_2.getCallback(19) ... ...
		);
	 
	prop_number = SettingsAmbient.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(SettingsAmbient.getPropTag(prop));
		switch SettingsAmbient.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(st_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(st_3.get(prop), st_0.get(prop)) && ~isa(st_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(st_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	st = SettingsAmbient();
	 
	st_copy = st.copy();
	 
	assert(st_copy ~= st, ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'SettingsAmbient.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(st_copy, st), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'SettingsAmbient.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:SettingsAmbient.getPropNumber()
		value = st.getr(prop);
		value_copy = st_copy.getr(prop);
		switch SettingsAmbient.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					'SettingsAmbient.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						'SettingsAmbient.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						'SettingsAmbient.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						'SettingsAmbient.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
							'SettingsAmbient.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
							'SettingsAmbient.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						'SettingsAmbient.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					st_copy.isLocked(prop) == st.isLocked(prop), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					'SettingsAmbient.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					st_copy.isChecked(prop) == st.isChecked(prop), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					'SettingsAmbient.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					st_copy.getPropSeed(prop) == st.getPropSeed(prop), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					'SettingsAmbient.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	st = SettingsAmbient( ...
		SettingsAmbient.ELCLASS, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.NAME, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.DESCRIPTION, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.TEMPLATE, SettingsAmbient.getPropDefault(SettingsAmbient.TEMPLATE), ...
		SettingsAmbient.ID, SettingsAmbient.getPropDefault(SettingsAmbient.ID), ...
		SettingsAmbient.LABEL, SettingsAmbient.getPropDefault(SettingsAmbient.LABEL), ...
		SettingsAmbient.NOTES, SettingsAmbient.getPropDefault(SettingsAmbient.NOTES), ...
		SettingsAmbient.TOSTRING, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.PANEL, SettingsAmbient.getPropDefault(SettingsAmbient.PANEL), ...
		SettingsAmbient.PROP, SettingsAmbient.getPropDefault(SettingsAmbient.PROP), ...
		SettingsAmbient.TAG, SettingsAmbient.getPropDefault(SettingsAmbient.TAG), ...
		SettingsAmbient.I, SettingsAmbient.getPropDefault(SettingsAmbient.I), ...
		SettingsAmbient.H, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.SETUP, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.LIGHTING, SettingsAmbient.getPropDefault(SettingsAmbient.LIGHTING), ...
		SettingsAmbient.MATERIAL, SettingsAmbient.getPropDefault(SettingsAmbient.MATERIAL), ...
		SettingsAmbient.CAMLIGHT, SettingsAmbient.getPropDefault(SettingsAmbient.CAMLIGHT), ...
		SettingsAmbient.SHADING, SettingsAmbient.getPropDefault(SettingsAmbient.SHADING), ...
		SettingsAmbient.COLORMAP, SettingsAmbient.getPropDefault(SettingsAmbient.COLORMAP) ...
		);
	 
	for prop = 1:1:SettingsAmbient.getPropNumber()
		if SettingsAmbient.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':SettingsAmbient']);
			% st.memorize(prop);
			% warning(warning_backup)
		elseif SettingsAmbient.getPropCategory(prop) == Category.EVANESCENT && st.getPropFormat(prop) == Format.HANDLE
			st.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:SettingsAmbient');
			delete(ancestor(st.get(prop), 'figure'))
			warning(warning_backup)
		else
			st.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	st_copy = st.copy();
	 
	for prop = 1:1:SettingsAmbient.getPropNumber()
		value = st.getr(prop);
		value_copy = st_copy.getr(prop);
		switch SettingsAmbient.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					'SettingsAmbient.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						'SettingsAmbient.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						'SettingsAmbient.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						'SettingsAmbient.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
							'SettingsAmbient.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
							'SettingsAmbient.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						'SettingsAmbient.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						st_copy.isLocked(prop) == st.isLocked(prop), ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						'SettingsAmbient.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						st_copy.isChecked(prop) == st.isChecked(prop), ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						'SettingsAmbient.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						st_copy.getPropSeed(prop) == st.getPropSeed(prop), ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						'SettingsAmbient.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	st_0 = SettingsAmbient( ...
		SettingsAmbient.ELCLASS, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.NAME, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.DESCRIPTION, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.TEMPLATE, SettingsAmbient.getPropDefault(SettingsAmbient.TEMPLATE), ...
		SettingsAmbient.ID, SettingsAmbient.getPropDefault(SettingsAmbient.ID), ...
		SettingsAmbient.LABEL, SettingsAmbient.getPropDefault(SettingsAmbient.LABEL), ...
		SettingsAmbient.NOTES, SettingsAmbient.getPropDefault(SettingsAmbient.NOTES), ...
		SettingsAmbient.TOSTRING, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.PANEL, SettingsAmbient.getPropDefault(SettingsAmbient.PANEL), ...
		SettingsAmbient.PROP, SettingsAmbient.getPropDefault(SettingsAmbient.PROP), ...
		SettingsAmbient.TAG, SettingsAmbient.getPropDefault(SettingsAmbient.TAG), ...
		SettingsAmbient.I, SettingsAmbient.getPropDefault(SettingsAmbient.I), ...
		SettingsAmbient.H, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.SETUP, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.LIGHTING, SettingsAmbient.getPropDefault(SettingsAmbient.LIGHTING), ...
		SettingsAmbient.MATERIAL, SettingsAmbient.getPropDefault(SettingsAmbient.MATERIAL), ...
		SettingsAmbient.CAMLIGHT, SettingsAmbient.getPropDefault(SettingsAmbient.CAMLIGHT), ...
		SettingsAmbient.SHADING, SettingsAmbient.getPropDefault(SettingsAmbient.SHADING), ...
		SettingsAmbient.COLORMAP, SettingsAmbient.getPropDefault(SettingsAmbient.COLORMAP) ...
		);
	 
	st = SettingsAmbient( ...
		SettingsAmbient.ELCLASS, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.NAME, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.DESCRIPTION, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.TEMPLATE, st_0.getCallback(4), ..., ...
		SettingsAmbient.ID, st_0.getCallback(5), ..., ...
		SettingsAmbient.LABEL, SettingsAmbient.getPropDefault(SettingsAmbient.LABEL), ...
		SettingsAmbient.NOTES, SettingsAmbient.getPropDefault(SettingsAmbient.NOTES), ...
		SettingsAmbient.TOSTRING, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.PANEL, st_0.getCallback(9), ..., ...
		SettingsAmbient.PROP, st_0.getCallback(10), ..., ...
		SettingsAmbient.TAG, st_0.getCallback(11), ..., ...
		SettingsAmbient.I, st_0.getCallback(12), ..., ...
		SettingsAmbient.H, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.SETUP, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.LIGHTING, st_0.getCallback(15), ..., ...
		SettingsAmbient.MATERIAL, st_0.getCallback(16), ..., ...
		SettingsAmbient.CAMLIGHT, st_0.getCallback(17), ..., ...
		SettingsAmbient.SHADING, st_0.getCallback(18), ..., ...
		SettingsAmbient.COLORMAP, st_0.getCallback(19) ... ...
		);
	 
	st_copy = st.copy();
	st_0_copy = st_copy.getr('ID').get('EL');
	 
	for prop = 1:1:SettingsAmbient.getPropNumber()
		value = st.getr(prop);
		value_copy = st_copy.getr(prop);
		switch SettingsAmbient.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					'SettingsAmbient.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						'SettingsAmbient.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						'SettingsAmbient.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						'SettingsAmbient.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
							'SettingsAmbient.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
							'SettingsAmbient.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						'SettingsAmbient.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == st_0.getCallback(prop), ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						'SettingsAmbient.copy() does not work. The callback should be obtained from SettingsAmbient.getCallback().' ...
						)
					assert( ...
						value_copy == st_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						'SettingsAmbient.copy() does not work. The callback should be obtained from SettingsAmbient.getCallback().' ...
						)
				end
	 
					assert( ...
						st_copy.isLocked(prop) == st.isLocked(prop), ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						'SettingsAmbient.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						st_copy.isChecked(prop) == st.isChecked(prop), ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						'SettingsAmbient.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						st_copy.getPropSeed(prop) == st.getPropSeed(prop), ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						'SettingsAmbient.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st_template = SettingsAmbient();
	st = SettingsAmbient('TEMPLATE', st_template);
	 
	for prop = 1:1:SettingsAmbient.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(SettingsAmbient.getPropTag(prop));
		switch SettingsAmbient.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == SettingsAmbient.TEMPLATE
					assert( ...
						isa(st.getr(prop), 'SettingsAmbient'), ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						'SettingsAmbient TEMPLATE does not work. SettingsAmbient.getr(''TEMPLATE'') should be a SettingsAmbient element.' ...
						)
					assert( ...
						isa(st_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						'SettingsAmbient TEMPLATE does not work. SettingsAmbient_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(st.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						['SettingsAmbient TEMPLATE does not work. SettingsAmbient.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						st.getr(prop).get('EL') == st_template && st.getr(prop).get('PROP') == prop && strcmp(st.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						['SettingsAmbient TEMPLATE does not work. SettingsAmbient.getr(' TAG ') should be a Callback to st_template.' TAG '.'] ...
						)
					assert( ...
						isa(st_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
						['SettingsAmbient TEMPLATE does not work. SettingsAmbient_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(st.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient TEMPLATE does not work. SettingsAmbient.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(st_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
					['SettingsAmbient TEMPLATE does not work. SettingsAmbient_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = SettingsAmbient( ...
		SettingsAmbient.ELCLASS, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.NAME, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.DESCRIPTION, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.TEMPLATE, SettingsAmbient.getPropDefault(SettingsAmbient.TEMPLATE), ...
		SettingsAmbient.ID, SettingsAmbient.getPropDefault(SettingsAmbient.ID), ...
		SettingsAmbient.LABEL, SettingsAmbient.getPropDefault(SettingsAmbient.LABEL), ...
		SettingsAmbient.NOTES, SettingsAmbient.getPropDefault(SettingsAmbient.NOTES), ...
		SettingsAmbient.TOSTRING, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.PANEL, SettingsAmbient.getPropDefault(SettingsAmbient.PANEL), ...
		SettingsAmbient.PROP, SettingsAmbient.getPropDefault(SettingsAmbient.PROP), ...
		SettingsAmbient.TAG, SettingsAmbient.getPropDefault(SettingsAmbient.TAG), ...
		SettingsAmbient.I, SettingsAmbient.getPropDefault(SettingsAmbient.I), ...
		SettingsAmbient.H, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.SETUP, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.LIGHTING, SettingsAmbient.getPropDefault(SettingsAmbient.LIGHTING), ...
		SettingsAmbient.MATERIAL, SettingsAmbient.getPropDefault(SettingsAmbient.MATERIAL), ...
		SettingsAmbient.CAMLIGHT, SettingsAmbient.getPropDefault(SettingsAmbient.CAMLIGHT), ...
		SettingsAmbient.SHADING, SettingsAmbient.getPropDefault(SettingsAmbient.SHADING), ...
		SettingsAmbient.COLORMAP, SettingsAmbient.getPropDefault(SettingsAmbient.COLORMAP) ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'settingsambient_to_be_erased.b2'];
	 
	Element.save(st, filename)
	 
	st_loaded = Element.load(filename);
	 
	assert( ...
		isequal(st.copy(), st_loaded), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'SettingsAmbient.save(st) and/or SettingsAmbient.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = SettingsAmbient( ...
		SettingsAmbient.ELCLASS, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.NAME, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.DESCRIPTION, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.TEMPLATE, SettingsAmbient.getPropDefault(SettingsAmbient.TEMPLATE), ...
		SettingsAmbient.ID, SettingsAmbient.getPropDefault(SettingsAmbient.ID), ...
		SettingsAmbient.LABEL, SettingsAmbient.getPropDefault(SettingsAmbient.LABEL), ...
		SettingsAmbient.NOTES, SettingsAmbient.getPropDefault(SettingsAmbient.NOTES), ...
		SettingsAmbient.TOSTRING, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.PANEL, SettingsAmbient.getPropDefault(SettingsAmbient.PANEL), ...
		SettingsAmbient.PROP, SettingsAmbient.getPropDefault(SettingsAmbient.PROP), ...
		SettingsAmbient.TAG, SettingsAmbient.getPropDefault(SettingsAmbient.TAG), ...
		SettingsAmbient.I, SettingsAmbient.getPropDefault(SettingsAmbient.I), ...
		SettingsAmbient.H, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.SETUP, SettingsAmbient.getNoValue(), ...
		SettingsAmbient.LIGHTING, SettingsAmbient.getPropDefault(SettingsAmbient.LIGHTING), ...
		SettingsAmbient.MATERIAL, SettingsAmbient.getPropDefault(SettingsAmbient.MATERIAL), ...
		SettingsAmbient.CAMLIGHT, SettingsAmbient.getPropDefault(SettingsAmbient.CAMLIGHT), ...
		SettingsAmbient.SHADING, SettingsAmbient.getPropDefault(SettingsAmbient.SHADING), ...
		SettingsAmbient.COLORMAP, SettingsAmbient.getPropDefault(SettingsAmbient.COLORMAP) ...
		);
	 
	[json, struct, el_list] = encodeJSON(st);
	[st_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(st_dec ~= st, ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		'SettingsAmbient.encodeJSON() or SettingsAmbient.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) SettingsAmbient.getPropFormat(prop), num2cell(SettingsAmbient.getProps())) == Format.HANDLE) && all(cellfun(@(prop) SettingsAmbient.getPropFormat(prop), num2cell(SettingsAmbient.getProps())) == Format.NET)
		assert(isequal(st_dec, st), ...
			[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
			'SettingsAmbient.encodeJSON() or SettingsAmbient.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':SettingsAmbient:' BRAPH2.FAIL_TEST], ...
		[' When testing SettingsAmbient no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 13: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

