%TEST_SETTINGS

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	st = Settings();
	 
	% get('ELCLASS')
	if isa(Settings, 'ConcreteElement')
		assert(strcmp(Settings().get('ELCLASS'), 'Settings'), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Settings().get(''ELCLASS'') should return ''Settings''.')
	end
	 
	% getBuild()
	assert(Settings.getBuild() == 1 && Settings.getBuild() > 0, ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Settings.getBuild() should return the Settings build number.')
	assert(st.getBuild() == 1 && st.getBuild() > 0 , ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'st.getBuild() should return the Settings build number.')
	assert(Element.getBuild(st) == 1 && Element.getBuild(st) > 0, ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(st) should return the Settings build number.')
	assert(Element.getBuild('Settings') == 1 && Element.getBuild('Settings') > 0, ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''Settings'') should return the Settings build number.')
	 
	% getClass()
	assert(strcmp(Settings.getClass(), 'Settings'), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Settings.getClass() should return ''Settings''.')
	assert(strcmp(st.getClass(), 'Settings'), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'st.getClass() should return ''Settings''.')
	assert(strcmp(Element.getClass(st), 'Settings'), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(st) should return ''Settings''.')
	assert(strcmp(Element.getClass('Settings'), 'Settings'), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''Settings'') should return ''Settings''.')
	 
	% getSubclasses()
	assert(isequal(Settings.getSubclasses(), subclasses('Settings', [], [], true)), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Settings.getSubclasses() should return the same result as subclasses(''Settings'', [], [], true).')
	assert(isequal(st.getSubclasses(), subclasses('Settings', [], [], true)), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''Settings'', [], [], true).')
	assert(isequal(Element.getSubclasses(st), subclasses('Settings', [], [], true)), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(st) should return the same result as subclasses(''Settings'', [], [], true).')
	assert(isequal(Element.getSubclasses('Settings'), subclasses('Settings', [], [], true)), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''Settings'') should return the same result as subclasses(''Settings'', [], [], true).')
	 
	% getProps()
	assert(isempty(Settings.getProps()) || isequal(Settings.getProps(), 1:1:length(Settings.getProps())), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Settings.getProps() should return a row vector [1:1:N].')
	assert(isempty(Settings.getProps()) || isequal(st.getProps(), 1:1:length(Settings.getProps())), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'st.getProps() should return a row vector [1:1:N].')
	assert(isempty(Settings.getProps()) || isequal(Element.getProps(st), 1:1:length(Settings.getProps())), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(st) should return a row vector [1:1:N].')
	assert(isempty(Settings.getProps()) || isequal(Element.getProps('Settings'), 1:1:length(Settings.getProps())), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''Settings'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) Settings.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(Settings.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(Settings.getProps())), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Settings.getProps(category) does not work.')
	tmp = cellfun(@(category) st.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(Settings.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(Settings.getProps())), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'st.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(st, category), categories, 'UniformOutput', false);
	assert(isempty(Settings.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(Settings.getProps())), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(st, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('Settings', category), categories, 'UniformOutput', false);
	assert(isempty(Settings.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(Settings.getProps())), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''Settings'', category) does not work.')
	 
	% getPropNumber()
	assert(Settings.getPropNumber() == length(Settings.getProps()), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Settings.getPropNumber() should return the number of properties.')
	assert(st.getPropNumber() == length(Settings.getProps()), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'st.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(st) == length(Settings.getProps()), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(st) should return the number of properties.')
	assert(Element.getPropNumber('Settings') == length(Settings.getProps()), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''Settings'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) Settings.getPropNumber(category), categories)) == Settings.getPropNumber(), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Settings.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) st.getPropNumber(category), categories)) == Settings.getPropNumber(), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'st.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(st, category), categories)) == Settings.getPropNumber(), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(st, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('Settings', category), categories)) == Settings.getPropNumber(), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''Settings'', category) does not work.')
	 
	% existsProp(prop)
	assert(~Settings.existsProp(NaN), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Settings.existsProp(prop) does not work.')
	assert(~st.existsProp(NaN), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'st.existsProp(prop) does not work.')
	assert(~Element.existsProp(st, NaN), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(st, prop) does not work.')
	assert(~Element.existsProp('Settings', NaN), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''Settings'', prop) does not work.')
	 
	assert_with_error('Settings.existsProp(NaN)', [BRAPH2.STR ':Settings:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':Settings:' BRAPH2.WRONG_INPUT], st)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':Settings:' BRAPH2.WRONG_INPUT], st)
	assert_with_error('Element.existsProp(''Settings'', NaN)', [BRAPH2.STR ':Settings:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:Settings.getPropNumber()
		assert(Settings.existsProp(prop), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Settings.existsProp(prop) does not work.')
		assert(st.existsProp(prop), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'st.existsProp(prop) does not work.')
		assert(Element.existsProp(st, prop), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(st, prop) does not work.')
		assert(Element.existsProp('Settings', prop), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''Settings'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~Settings.existsTag(''), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Settings.existsTag(tag) does not work.')
	assert(~st.existsTag(''), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'st.existsTag(tag) does not work.')
	assert(~Element.existsTag(st, ''), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(st, tag) does not work.')
	assert(~Element.existsTag('Settings', ''), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''Settings'', tag) does not work.')
	 
	assert_with_error('Settings.existsTag('''')', [BRAPH2.STR ':Settings:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':Settings:' BRAPH2.WRONG_INPUT], st)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':Settings:' BRAPH2.WRONG_INPUT], st)
	assert_with_error('Element.existsTag(''Settings'', '''')', [BRAPH2.STR ':Settings:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:Settings.getPropNumber()
		tag = st.getPropTag(prop);
		assert(Settings.existsTag(tag), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Settings.existsTag(tag) does not work.')
		assert(st.existsTag(tag), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'st.existsTag(tag) does not work.')
		assert(Element.existsTag(st, tag), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(st, tga) does not work.')
		assert(Element.existsTag('Settings', tag), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''Settings'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:Settings.getPropNumber()
		assert(Settings.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Settings.getPropProp(prop) does not work.')
		assert(st.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'st.getPropProp(prop) does not work.')
		assert(Element.getPropProp(st, prop) == prop, ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(st, prop) does not work.')
		assert(Element.getPropProp('Settings', prop) == prop, ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''Settings'', prop) does not work.')
	 
		tag = st.getPropTag(prop);
		assert(Settings.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Settings.getPropProp(tag) does not work.')
		assert(st.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'st.getPropProp(tag) does not work.')
		assert(Element.getPropProp(st, tag) == prop, ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(st, tag) does not work.')
		assert(Element.getPropProp('Settings', prop) == prop, ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''Settings'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:Settings.getPropNumber()
		tag = st.getPropTag(prop);
	 
		assert(strcmp(Settings.getPropTag(prop), tag), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Settings.getPropTag(prop) does not work.')
		assert(strcmp(st.getPropTag(prop), tag), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'st.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(st, prop), tag), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(st, prop) does not work.')
		assert(strcmp(Element.getPropTag('Settings', prop), tag), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''Settings'', prop) does not work.')
	 
		assert(strcmp(Settings.getPropTag(tag), tag), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Settings.getPropTag(tag) does not work.')
		assert(strcmp(st.getPropTag(tag), tag), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'st.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(st, tag), tag), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(st, tag) does not work.')
		assert(strcmp(Element.getPropTag('Settings', prop), tag), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''Settings'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:Settings.getPropNumber()
		tag = st.getPropTag(prop);
	 
		assert(Category.existsCategory(Settings.getPropCategory(prop)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Settings.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(st.getPropCategory(prop)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'st.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(st, prop)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(st, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(st, prop)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''Settings'', prop) does not work.')
	 
		assert(Category.existsCategory(Settings.getPropCategory(tag)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Settings.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(st.getPropCategory(tag)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'st.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(st, tag)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(st, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(st, tag)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''Settings'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:Settings.getPropNumber()
		tag = st.getPropTag(prop);
	 
		assert(Format.existsFormat(Settings.getPropFormat(prop)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Settings.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(st.getPropFormat(prop)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'st.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(st, prop)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(st, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(st, prop)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''Settings'', prop) does not work.')
	 
		assert(Format.existsFormat(Settings.getPropFormat(tag)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Settings.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(st.getPropFormat(tag)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'st.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(st, tag)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(st, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(st, tag)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''Settings'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:Settings.getPropNumber()
		tag = st.getPropTag(prop);
	 
		assert(ischar(Settings.getPropDescription(prop)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Settings.getPropDescription(prop) does not work.')
		assert(ischar(st.getPropDescription(prop)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'st.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(st, prop)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(st, prop) does not work.')
		assert(ischar(Element.getPropDescription(st, prop)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''Settings'', prop) does not work.')
	 
		assert(ischar(Settings.getPropDescription(tag)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Settings.getPropDescription(tag) does not work.')
		assert(ischar(st.getPropDescription(tag)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'st.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(st, tag)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(st, tag) does not work.')
		assert(ischar(Element.getPropDescription(st, tag)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''Settings'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:Settings.getPropNumber()
		tag = st.getPropTag(prop);
	 
		settings = Settings.getPropSettings(prop);
		settings = st.getPropSettings(prop);
		settings = Element.getPropSettings(st, prop);
		settings = Element.getPropSettings('Settings', prop);
	 
		settings = Settings.getPropSettings(tag);
		settings = st.getPropSettings(tag);
		settings = Element.getPropSettings(st, tag);
		settings = Element.getPropSettings('Settings', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:Settings.getPropNumber()
		tag = st.getPropTag(prop);
	 
		default = Settings.getPropDefault(prop);
		default = st.getPropDefault(prop);
		default = Element.getPropDefault(st, prop);
		default = Element.getPropDefault('Settings', prop);
	 
		default = Settings.getPropDefault(tag);
		default = st.getPropDefault(tag);
		default = Element.getPropDefault(st, tag);
		default = Element.getPropDefault('Settings', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:Settings.getPropNumber()
		tag = st.getPropTag(prop);
	 
		conditioned_default = Settings.getPropDefaultConditioned(prop);
		conditioned_default = st.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(st, prop);
		conditioned_default = Element.getPropDefaultConditioned('Settings', prop);
	 
		conditioned_default = Settings.getPropDefaultConditioned(tag);
		conditioned_default = st.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(st, tag);
		conditioned_default = Element.getPropDefaultConditioned('Settings', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:Settings.getPropNumber()
		tag = st.getPropTag(prop);
	 
		assert(~Settings.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Settings.checkProp(prop, value) does not work.')
		assert(~st.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'st.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(st, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(st, prop, value) does not work.')
		assert(~Element.checkProp('Settings', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''Settings'', prop, value) does not work.')
	 
		assert_with_error('Settings.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':Settings:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':Settings:' BRAPH2.WRONG_INPUT], prop, st)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':Settings:' BRAPH2.WRONG_INPUT], prop, st)
		assert_with_error('Element.checkProp(''Settings'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':Settings:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~Settings.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Settings.checkProp(tag, value) does not work.')
		assert(~st.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'st.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(st, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(st, tag, value) does not work.')
		assert(~Element.checkProp('Settings', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''Settings'', tag, value) does not work.')
	 
		assert_with_error('Settings.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':Settings:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':Settings:' BRAPH2.WRONG_INPUT], tag, st)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':Settings:' BRAPH2.WRONG_INPUT], tag, st)
		assert_with_error('Element.checkProp(''Settings'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':Settings:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(Settings.checkProp(prop, Element.getPropDefaultConditioned(Settings, prop)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Settings.checkProp(prop, <conditioned default value>) does not work.')
		assert(st.checkProp(prop, Element.getPropDefaultConditioned(Settings, prop)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'st.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(st, prop, Element.getPropDefaultConditioned(Settings, prop)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(st, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('Settings', prop, Element.getPropDefaultConditioned(Settings, prop)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''Settings'', prop, <conditioned default value>) does not work.')
	 
		assert(Settings.checkProp(tag, Element.getPropDefaultConditioned(Settings, prop)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Settings.checkProp(tag, <conditioned default value>) does not work.')
		assert(st.checkProp(tag, Element.getPropDefaultConditioned(Settings, prop)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'st.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(st, tag, Element.getPropDefaultConditioned(Settings, prop)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(st, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('Settings', tag, Element.getPropDefaultConditioned(Settings, prop)), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''Settings'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = Settings( ...
		Settings.ELCLASS, Settings.getNoValue(), ...
		Settings.NAME, Settings.getNoValue(), ...
		Settings.DESCRIPTION, Settings.getNoValue(), ...
		Settings.TEMPLATE, Settings.getPropDefault(Settings.TEMPLATE), ...
		Settings.ID, Settings.getPropDefault(Settings.ID), ...
		Settings.LABEL, Settings.getPropDefault(Settings.LABEL), ...
		Settings.NOTES, Settings.getPropDefault(Settings.NOTES), ...
		Settings.TOSTRING, Settings.getNoValue(), ...
		Settings.PANEL, Settings.getPropDefault(Settings.PANEL), ...
		Settings.PROP, Settings.getPropDefault(Settings.PROP), ...
		Settings.TAG, Settings.getPropDefault(Settings.TAG), ...
		Settings.I, Settings.getPropDefault(Settings.I), ...
		Settings.H, Settings.getNoValue(), ...
		Settings.SETUP, Settings.getNoValue() ...
		);
	 
	for prop = 1:1:Settings.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(Settings.getPropTag(prop));
		switch Settings.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					st.getr(prop) == Settings.getNoValue(), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Being a ' Settings.getCategoryName(Settings.getPropCategory(prop)) ', Settings.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in Settings.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					st.getr(TAG) == Settings.getNoValue(), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Being a ' Settings.getCategoryName(Settings.getPropCategory(prop)) ', Settings.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in Settings.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(st.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(st.getPropSettings(prop))
					assert( ...
						st.checkFormat(st.getPropFormat(prop), st.get(prop)), ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						['Settings.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						st.checkFormat(st.getPropFormat(prop), st.get(prop), st.getPropSettings(prop)), ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						['Settings.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					st.getr(prop) == Settings.getNoValue(), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Being a ' Settings.getCategoryName(Settings.getPropCategory(prop)) ', Settings.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in Settings.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					st.getr(TAG) == Settings.getNoValue(), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Being a ' Settings.getCategoryName(Settings.getPropCategory(prop)) ', Settings.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in Settings.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':Settings']);
				assert( ...
					~isa(st.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(st.getPropSettings(prop))
					assert( ...
						st.checkFormat(st.getPropFormat(prop), st.get(prop)), ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						['Settings.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						st.checkFormat(st.getPropFormat(prop), st.get(prop), st.getPropSettings(prop)), ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						['Settings.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(st.getr(prop), Settings.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by Settings.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in Settings.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(st.getr(TAG), Settings.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.getr(' TAG ') must be inizialized to its default value ' ...
					'given by Settings.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in Settings.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = Settings( ...
		Settings.ELCLASS, Settings.getNoValue(), ...
		Settings.NAME, Settings.getNoValue(), ...
		Settings.DESCRIPTION, Settings.getNoValue(), ...
		Settings.TEMPLATE, Settings.getPropDefault(Settings.TEMPLATE), ...
		Settings.ID, Settings.getPropDefault(Settings.ID), ...
		Settings.LABEL, Settings.getPropDefault(Settings.LABEL), ...
		Settings.NOTES, Settings.getPropDefault(Settings.NOTES), ...
		Settings.TOSTRING, Settings.getNoValue(), ...
		Settings.PANEL, Settings.getPropDefault(Settings.PANEL), ...
		Settings.PROP, Settings.getPropDefault(Settings.PROP), ...
		Settings.TAG, Settings.getPropDefault(Settings.TAG), ...
		Settings.I, Settings.getPropDefault(Settings.I), ...
		Settings.H, Settings.getNoValue(), ...
		Settings.SETUP, Settings.getNoValue() ...
		);
	 
	for prop = 1:1:Settings.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(Settings.getPropTag(prop));
		switch Settings.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(st.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(st.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(st.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(st.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					st.checkFormat(st.getPropFormat(prop), st.getr(prop),st.getPropSettings(prop)), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':Settings']);
				assert( ...
					~isa(st.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(st.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':Settings']);
	% 			assert( ...
	% 				~isa(st.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
	% 				['Settings.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(st.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
	% 				['Settings.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				st.checkFormat(st.getPropFormat(prop), st.getr(prop),st.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
	% 				['Settings.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':Settings']);
				assert( ...
					~isa(st.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(st.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(st.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(st.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					st.checkFormat(st.getPropFormat(prop), st.getr(prop),st.getPropSettings(prop)), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if st.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:Settings');
					delete(ancestor(st.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(Settings.getProps(Category.RESULT))
		for prop = 1:1:Settings.getPropNumber()
	 
			% excluded props
			if any(prop == [])
				continue
			end
	 
			switch Settings.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						st.isLocked(prop), ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						['Settings.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~st.isLocked(prop), ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						['Settings.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = Settings();
	 
	for prop = 1:1:Settings.getPropNumber()
		TAG = upper(Settings.getPropTag(prop));
		assert( ...
			~st.isLocked(prop), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			['Settings.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~st.isLocked(TAG), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			['Settings.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	st.lock()
	 
	for prop = 1:1:Settings.getPropNumber()
		switch Settings.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					st.isLocked(prop), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~st.isLocked(prop), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = Settings();
	 
	warning_backup = warning('off', 'BRAPH2:Settings');
	for prop = 1:1:Settings.getPropNumber()
		st.lock(prop)
		switch Settings.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					st.isLocked(prop), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~st.isLocked(prop), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = Settings();
	 
	for prop = 1:1:Settings.getPropNumber()
		TAG = upper(Settings.getPropTag(prop));
		assert( ...
			st.isChecked(prop), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			['Settings.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			st.isChecked(TAG), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			['Settings.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	st.unchecked()
	 
	for prop = 1:1:Settings.getPropNumber()
		assert( ...
			~st.isChecked(prop), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			['Settings.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	st.checked()
	 
	for prop = 1:1:Settings.getPropNumber()
		assert( ...
			st.isChecked(prop), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			['Settings.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic Settings
	st_0 = Settings( ...
		Settings.ELCLASS, Settings.getNoValue(), ...
		Settings.NAME, Settings.getNoValue(), ...
		Settings.DESCRIPTION, Settings.getNoValue(), ...
		Settings.TEMPLATE, Settings.getPropDefault(Settings.TEMPLATE), ...
		Settings.ID, Settings.getPropDefault(Settings.ID), ...
		Settings.LABEL, Settings.getPropDefault(Settings.LABEL), ...
		Settings.NOTES, Settings.getPropDefault(Settings.NOTES), ...
		Settings.TOSTRING, Settings.getNoValue(), ...
		Settings.PANEL, Settings.getPropDefault(Settings.PANEL), ...
		Settings.PROP, Settings.getPropDefault(Settings.PROP), ...
		Settings.TAG, Settings.getPropDefault(Settings.TAG), ...
		Settings.I, Settings.getPropDefault(Settings.I), ...
		Settings.H, Settings.getNoValue(), ...
		Settings.SETUP, Settings.getNoValue() ...
		);
	 
	% Settings with 1st callbacks
	st_1 = Settings( ...
		Settings.ELCLASS, Settings.getNoValue(), ...
		Settings.NAME, Settings.getNoValue(), ...
		Settings.DESCRIPTION, Settings.getNoValue(), ...
		Settings.TEMPLATE, st_0.getCallback(4), ..., ...
		Settings.ID, st_0.getCallback(5), ..., ...
		Settings.LABEL, Settings.getPropDefault(Settings.LABEL), ...
		Settings.NOTES, Settings.getPropDefault(Settings.NOTES), ...
		Settings.TOSTRING, Settings.getNoValue(), ...
		Settings.PANEL, st_0.getCallback(9), ..., ...
		Settings.PROP, st_0.getCallback(10), ..., ...
		Settings.TAG, st_0.getCallback(11), ..., ...
		Settings.I, st_0.getCallback(12), ..., ...
		Settings.H, Settings.getNoValue(), ...
		Settings.SETUP, Settings.getNoValue() ...
		);
	 
	prop_number = Settings.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(Settings.getPropTag(prop));
		switch Settings.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(st_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(st_1.get(prop), st_0.get(prop)) && ~isa(st_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(st_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% Settings with 2nd callbacks
	st_2 = Settings( ...
		Settings.ELCLASS, Settings.getNoValue(), ...
		Settings.NAME, Settings.getNoValue(), ...
		Settings.DESCRIPTION, Settings.getNoValue(), ...
		Settings.TEMPLATE, st_1.getCallback(4), ..., ...
		Settings.ID, st_1.getCallback(5), ..., ...
		Settings.LABEL, Settings.getPropDefault(Settings.LABEL), ...
		Settings.NOTES, Settings.getPropDefault(Settings.NOTES), ...
		Settings.TOSTRING, Settings.getNoValue(), ...
		Settings.PANEL, st_1.getCallback(9), ..., ...
		Settings.PROP, st_1.getCallback(10), ..., ...
		Settings.TAG, st_1.getCallback(11), ..., ...
		Settings.I, st_1.getCallback(12), ..., ...
		Settings.H, Settings.getNoValue(), ...
		Settings.SETUP, Settings.getNoValue() ...
		);
	 
	prop_number = Settings.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(Settings.getPropTag(prop));
		switch Settings.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(st_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(st_2.get(prop), st_0.get(prop)) && ~isa(st_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(st_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% Settings with 3rd callbacks
	st_3 = Settings( ...
		Settings.ELCLASS, Settings.getNoValue(), ...
		Settings.NAME, Settings.getNoValue(), ...
		Settings.DESCRIPTION, Settings.getNoValue(), ...
		Settings.TEMPLATE, st_2.getCallback(4), ..., ...
		Settings.ID, st_2.getCallback(5), ..., ...
		Settings.LABEL, Settings.getPropDefault(Settings.LABEL), ...
		Settings.NOTES, Settings.getPropDefault(Settings.NOTES), ...
		Settings.TOSTRING, Settings.getNoValue(), ...
		Settings.PANEL, st_2.getCallback(9), ..., ...
		Settings.PROP, st_2.getCallback(10), ..., ...
		Settings.TAG, st_2.getCallback(11), ..., ...
		Settings.I, st_2.getCallback(12), ..., ...
		Settings.H, Settings.getNoValue(), ...
		Settings.SETUP, Settings.getNoValue() ...
		);
	 
	prop_number = Settings.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(Settings.getPropTag(prop));
		switch Settings.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(st_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(st_3.get(prop), st_0.get(prop)) && ~isa(st_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(st_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	st = Settings();
	 
	st_copy = st.copy();
	 
	assert(st_copy ~= st, ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Settings.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(st_copy, st), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Settings.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:Settings.getPropNumber()
		value = st.getr(prop);
		value_copy = st_copy.getr(prop);
		switch Settings.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					'Settings.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						'Settings.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						'Settings.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						'Settings.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
							'Settings.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
							'Settings.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						'Settings.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					st_copy.isLocked(prop) == st.isLocked(prop), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					'Settings.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					st_copy.isChecked(prop) == st.isChecked(prop), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					'Settings.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					st_copy.getPropSeed(prop) == st.getPropSeed(prop), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					'Settings.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	st = Settings( ...
		Settings.ELCLASS, Settings.getNoValue(), ...
		Settings.NAME, Settings.getNoValue(), ...
		Settings.DESCRIPTION, Settings.getNoValue(), ...
		Settings.TEMPLATE, Settings.getPropDefault(Settings.TEMPLATE), ...
		Settings.ID, Settings.getPropDefault(Settings.ID), ...
		Settings.LABEL, Settings.getPropDefault(Settings.LABEL), ...
		Settings.NOTES, Settings.getPropDefault(Settings.NOTES), ...
		Settings.TOSTRING, Settings.getNoValue(), ...
		Settings.PANEL, Settings.getPropDefault(Settings.PANEL), ...
		Settings.PROP, Settings.getPropDefault(Settings.PROP), ...
		Settings.TAG, Settings.getPropDefault(Settings.TAG), ...
		Settings.I, Settings.getPropDefault(Settings.I), ...
		Settings.H, Settings.getNoValue(), ...
		Settings.SETUP, Settings.getNoValue() ...
		);
	 
	for prop = 1:1:Settings.getPropNumber()
		if Settings.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':Settings']);
			% st.memorize(prop);
			% warning(warning_backup)
		elseif Settings.getPropCategory(prop) == Category.EVANESCENT && st.getPropFormat(prop) == Format.HANDLE
			st.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:Settings');
			delete(ancestor(st.get(prop), 'figure'))
			warning(warning_backup)
		else
			st.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	st_copy = st.copy();
	 
	for prop = 1:1:Settings.getPropNumber()
		value = st.getr(prop);
		value_copy = st_copy.getr(prop);
		switch Settings.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					'Settings.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						'Settings.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						'Settings.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						'Settings.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
							'Settings.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
							'Settings.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						'Settings.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						st_copy.isLocked(prop) == st.isLocked(prop), ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						'Settings.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						st_copy.isChecked(prop) == st.isChecked(prop), ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						'Settings.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						st_copy.getPropSeed(prop) == st.getPropSeed(prop), ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						'Settings.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	st_0 = Settings( ...
		Settings.ELCLASS, Settings.getNoValue(), ...
		Settings.NAME, Settings.getNoValue(), ...
		Settings.DESCRIPTION, Settings.getNoValue(), ...
		Settings.TEMPLATE, Settings.getPropDefault(Settings.TEMPLATE), ...
		Settings.ID, Settings.getPropDefault(Settings.ID), ...
		Settings.LABEL, Settings.getPropDefault(Settings.LABEL), ...
		Settings.NOTES, Settings.getPropDefault(Settings.NOTES), ...
		Settings.TOSTRING, Settings.getNoValue(), ...
		Settings.PANEL, Settings.getPropDefault(Settings.PANEL), ...
		Settings.PROP, Settings.getPropDefault(Settings.PROP), ...
		Settings.TAG, Settings.getPropDefault(Settings.TAG), ...
		Settings.I, Settings.getPropDefault(Settings.I), ...
		Settings.H, Settings.getNoValue(), ...
		Settings.SETUP, Settings.getNoValue() ...
		);
	 
	st = Settings( ...
		Settings.ELCLASS, Settings.getNoValue(), ...
		Settings.NAME, Settings.getNoValue(), ...
		Settings.DESCRIPTION, Settings.getNoValue(), ...
		Settings.TEMPLATE, st_0.getCallback(4), ..., ...
		Settings.ID, st_0.getCallback(5), ..., ...
		Settings.LABEL, Settings.getPropDefault(Settings.LABEL), ...
		Settings.NOTES, Settings.getPropDefault(Settings.NOTES), ...
		Settings.TOSTRING, Settings.getNoValue(), ...
		Settings.PANEL, st_0.getCallback(9), ..., ...
		Settings.PROP, st_0.getCallback(10), ..., ...
		Settings.TAG, st_0.getCallback(11), ..., ...
		Settings.I, st_0.getCallback(12), ..., ...
		Settings.H, Settings.getNoValue(), ...
		Settings.SETUP, Settings.getNoValue() ...
		);
	 
	st_copy = st.copy();
	st_0_copy = st_copy.getr('ID').get('EL');
	 
	for prop = 1:1:Settings.getPropNumber()
		value = st.getr(prop);
		value_copy = st_copy.getr(prop);
		switch Settings.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					'Settings.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						'Settings.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						'Settings.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						'Settings.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
							'Settings.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
							'Settings.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						'Settings.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == st_0.getCallback(prop), ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						'Settings.copy() does not work. The callback should be obtained from Settings.getCallback().' ...
						)
					assert( ...
						value_copy == st_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						'Settings.copy() does not work. The callback should be obtained from Settings.getCallback().' ...
						)
				end
	 
					assert( ...
						st_copy.isLocked(prop) == st.isLocked(prop), ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						'Settings.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						st_copy.isChecked(prop) == st.isChecked(prop), ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						'Settings.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						st_copy.getPropSeed(prop) == st.getPropSeed(prop), ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						'Settings.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st_template = Settings();
	st = Settings('TEMPLATE', st_template);
	 
	for prop = 1:1:Settings.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(Settings.getPropTag(prop));
		switch Settings.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == Settings.TEMPLATE
					assert( ...
						isa(st.getr(prop), 'Settings'), ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						'Settings TEMPLATE does not work. Settings.getr(''TEMPLATE'') should be a Settings element.' ...
						)
					assert( ...
						isa(st_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						'Settings TEMPLATE does not work. Settings_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(st.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						['Settings TEMPLATE does not work. Settings.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						st.getr(prop).get('EL') == st_template && st.getr(prop).get('PROP') == prop && strcmp(st.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						['Settings TEMPLATE does not work. Settings.getr(' TAG ') should be a Callback to st_template.' TAG '.'] ...
						)
					assert( ...
						isa(st_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
						['Settings TEMPLATE does not work. Settings_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(st.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings TEMPLATE does not work. Settings.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(st_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
					['Settings TEMPLATE does not work. Settings_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = Settings( ...
		Settings.ELCLASS, Settings.getNoValue(), ...
		Settings.NAME, Settings.getNoValue(), ...
		Settings.DESCRIPTION, Settings.getNoValue(), ...
		Settings.TEMPLATE, Settings.getPropDefault(Settings.TEMPLATE), ...
		Settings.ID, Settings.getPropDefault(Settings.ID), ...
		Settings.LABEL, Settings.getPropDefault(Settings.LABEL), ...
		Settings.NOTES, Settings.getPropDefault(Settings.NOTES), ...
		Settings.TOSTRING, Settings.getNoValue(), ...
		Settings.PANEL, Settings.getPropDefault(Settings.PANEL), ...
		Settings.PROP, Settings.getPropDefault(Settings.PROP), ...
		Settings.TAG, Settings.getPropDefault(Settings.TAG), ...
		Settings.I, Settings.getPropDefault(Settings.I), ...
		Settings.H, Settings.getNoValue(), ...
		Settings.SETUP, Settings.getNoValue() ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'settings_to_be_erased.b2'];
	 
	Element.save(st, filename)
	 
	st_loaded = Element.load(filename);
	 
	assert( ...
		isequal(st.copy(), st_loaded), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Settings.save(st) and/or Settings.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = Settings( ...
		Settings.ELCLASS, Settings.getNoValue(), ...
		Settings.NAME, Settings.getNoValue(), ...
		Settings.DESCRIPTION, Settings.getNoValue(), ...
		Settings.TEMPLATE, Settings.getPropDefault(Settings.TEMPLATE), ...
		Settings.ID, Settings.getPropDefault(Settings.ID), ...
		Settings.LABEL, Settings.getPropDefault(Settings.LABEL), ...
		Settings.NOTES, Settings.getPropDefault(Settings.NOTES), ...
		Settings.TOSTRING, Settings.getNoValue(), ...
		Settings.PANEL, Settings.getPropDefault(Settings.PANEL), ...
		Settings.PROP, Settings.getPropDefault(Settings.PROP), ...
		Settings.TAG, Settings.getPropDefault(Settings.TAG), ...
		Settings.I, Settings.getPropDefault(Settings.I), ...
		Settings.H, Settings.getNoValue(), ...
		Settings.SETUP, Settings.getNoValue() ...
		);
	 
	[json, struct, el_list] = encodeJSON(st);
	[st_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(st_dec ~= st, ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		'Settings.encodeJSON() or Settings.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) Settings.getPropFormat(prop), num2cell(Settings.getProps())) == Format.HANDLE) && all(cellfun(@(prop) Settings.getPropFormat(prop), num2cell(Settings.getProps())) == Format.NET)
		assert(isequal(st_dec, st), ...
			[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
			'Settings.encodeJSON() or Settings.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':Settings:' BRAPH2.FAIL_TEST], ...
		[' When testing Settings no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 13: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

