%TEST_PANELPROPSIZE

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropSize'])
	
	categories = num2cell(Category.getCategories());
	pr = PanelPropSize();
	 
	% get('ELCLASS')
	if isa(PanelPropSize, 'ConcreteElement')
		assert(strcmp(PanelPropSize().get('ELCLASS'), 'PanelPropSize'), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'PanelPropSize().get(''ELCLASS'') should return ''PanelPropSize''.')
	end
	 
	% getBuild()
	assert(PanelPropSize.getBuild() == 1 && PanelPropSize.getBuild() > 0, ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'PanelPropSize.getBuild() should return the PanelPropSize build number.')
	assert(pr.getBuild() == 1 && pr.getBuild() > 0 , ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'pr.getBuild() should return the PanelPropSize build number.')
	assert(Element.getBuild(pr) == 1 && Element.getBuild(pr) > 0, ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(pr) should return the PanelPropSize build number.')
	assert(Element.getBuild('PanelPropSize') == 1 && Element.getBuild('PanelPropSize') > 0, ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''PanelPropSize'') should return the PanelPropSize build number.')
	 
	% getClass()
	assert(strcmp(PanelPropSize.getClass(), 'PanelPropSize'), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'PanelPropSize.getClass() should return ''PanelPropSize''.')
	assert(strcmp(pr.getClass(), 'PanelPropSize'), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'pr.getClass() should return ''PanelPropSize''.')
	assert(strcmp(Element.getClass(pr), 'PanelPropSize'), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(pr) should return ''PanelPropSize''.')
	assert(strcmp(Element.getClass('PanelPropSize'), 'PanelPropSize'), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''PanelPropSize'') should return ''PanelPropSize''.')
	 
	% getSubclasses()
	assert(isequal(PanelPropSize.getSubclasses(), subclasses('PanelPropSize', [], [], true)), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'PanelPropSize.getSubclasses() should return the same result as subclasses(''PanelPropSize'', [], [], true).')
	assert(isequal(pr.getSubclasses(), subclasses('PanelPropSize', [], [], true)), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''PanelPropSize'', [], [], true).')
	assert(isequal(Element.getSubclasses(pr), subclasses('PanelPropSize', [], [], true)), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(pr) should return the same result as subclasses(''PanelPropSize'', [], [], true).')
	assert(isequal(Element.getSubclasses('PanelPropSize'), subclasses('PanelPropSize', [], [], true)), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''PanelPropSize'') should return the same result as subclasses(''PanelPropSize'', [], [], true).')
	 
	% getProps()
	assert(isempty(PanelPropSize.getProps()) || isequal(PanelPropSize.getProps(), 1:1:length(PanelPropSize.getProps())), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'PanelPropSize.getProps() should return a row vector [1:1:N].')
	assert(isempty(PanelPropSize.getProps()) || isequal(pr.getProps(), 1:1:length(PanelPropSize.getProps())), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'pr.getProps() should return a row vector [1:1:N].')
	assert(isempty(PanelPropSize.getProps()) || isequal(Element.getProps(pr), 1:1:length(PanelPropSize.getProps())), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(pr) should return a row vector [1:1:N].')
	assert(isempty(PanelPropSize.getProps()) || isequal(Element.getProps('PanelPropSize'), 1:1:length(PanelPropSize.getProps())), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''PanelPropSize'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) PanelPropSize.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(PanelPropSize.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(PanelPropSize.getProps())), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'PanelPropSize.getProps(category) does not work.')
	tmp = cellfun(@(category) pr.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(PanelPropSize.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(PanelPropSize.getProps())), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'pr.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(pr, category), categories, 'UniformOutput', false);
	assert(isempty(PanelPropSize.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(PanelPropSize.getProps())), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(pr, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('PanelPropSize', category), categories, 'UniformOutput', false);
	assert(isempty(PanelPropSize.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(PanelPropSize.getProps())), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''PanelPropSize'', category) does not work.')
	 
	% getPropNumber()
	assert(PanelPropSize.getPropNumber() == length(PanelPropSize.getProps()), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'PanelPropSize.getPropNumber() should return the number of properties.')
	assert(pr.getPropNumber() == length(PanelPropSize.getProps()), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'pr.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(pr) == length(PanelPropSize.getProps()), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(pr) should return the number of properties.')
	assert(Element.getPropNumber('PanelPropSize') == length(PanelPropSize.getProps()), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''PanelPropSize'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) PanelPropSize.getPropNumber(category), categories)) == PanelPropSize.getPropNumber(), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'PanelPropSize.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) pr.getPropNumber(category), categories)) == PanelPropSize.getPropNumber(), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'pr.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(pr, category), categories)) == PanelPropSize.getPropNumber(), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(pr, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('PanelPropSize', category), categories)) == PanelPropSize.getPropNumber(), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''PanelPropSize'', category) does not work.')
	 
	% existsProp(prop)
	assert(~PanelPropSize.existsProp(NaN), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'PanelPropSize.existsProp(prop) does not work.')
	assert(~pr.existsProp(NaN), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'pr.existsProp(prop) does not work.')
	assert(~Element.existsProp(pr, NaN), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(pr, prop) does not work.')
	assert(~Element.existsProp('PanelPropSize', NaN), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''PanelPropSize'', prop) does not work.')
	 
	assert_with_error('PanelPropSize.existsProp(NaN)', [BRAPH2.STR ':PanelPropSize:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':PanelPropSize:' BRAPH2.WRONG_INPUT], pr)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':PanelPropSize:' BRAPH2.WRONG_INPUT], pr)
	assert_with_error('Element.existsProp(''PanelPropSize'', NaN)', [BRAPH2.STR ':PanelPropSize:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:PanelPropSize.getPropNumber()
		assert(PanelPropSize.existsProp(prop), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'PanelPropSize.existsProp(prop) does not work.')
		assert(pr.existsProp(prop), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'pr.existsProp(prop) does not work.')
		assert(Element.existsProp(pr, prop), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(pr, prop) does not work.')
		assert(Element.existsProp('PanelPropSize', prop), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''PanelPropSize'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~PanelPropSize.existsTag(''), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'PanelPropSize.existsTag(tag) does not work.')
	assert(~pr.existsTag(''), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'pr.existsTag(tag) does not work.')
	assert(~Element.existsTag(pr, ''), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(pr, tag) does not work.')
	assert(~Element.existsTag('PanelPropSize', ''), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''PanelPropSize'', tag) does not work.')
	 
	assert_with_error('PanelPropSize.existsTag('''')', [BRAPH2.STR ':PanelPropSize:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':PanelPropSize:' BRAPH2.WRONG_INPUT], pr)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':PanelPropSize:' BRAPH2.WRONG_INPUT], pr)
	assert_with_error('Element.existsTag(''PanelPropSize'', '''')', [BRAPH2.STR ':PanelPropSize:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:PanelPropSize.getPropNumber()
		tag = pr.getPropTag(prop);
		assert(PanelPropSize.existsTag(tag), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'PanelPropSize.existsTag(tag) does not work.')
		assert(pr.existsTag(tag), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'pr.existsTag(tag) does not work.')
		assert(Element.existsTag(pr, tag), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(pr, tga) does not work.')
		assert(Element.existsTag('PanelPropSize', tag), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''PanelPropSize'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:PanelPropSize.getPropNumber()
		assert(PanelPropSize.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'PanelPropSize.getPropProp(prop) does not work.')
		assert(pr.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'pr.getPropProp(prop) does not work.')
		assert(Element.getPropProp(pr, prop) == prop, ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(pr, prop) does not work.')
		assert(Element.getPropProp('PanelPropSize', prop) == prop, ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''PanelPropSize'', prop) does not work.')
	 
		tag = pr.getPropTag(prop);
		assert(PanelPropSize.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'PanelPropSize.getPropProp(tag) does not work.')
		assert(pr.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'pr.getPropProp(tag) does not work.')
		assert(Element.getPropProp(pr, tag) == prop, ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(pr, tag) does not work.')
		assert(Element.getPropProp('PanelPropSize', prop) == prop, ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''PanelPropSize'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:PanelPropSize.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		assert(strcmp(PanelPropSize.getPropTag(prop), tag), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'PanelPropSize.getPropTag(prop) does not work.')
		assert(strcmp(pr.getPropTag(prop), tag), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'pr.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(pr, prop), tag), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(pr, prop) does not work.')
		assert(strcmp(Element.getPropTag('PanelPropSize', prop), tag), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''PanelPropSize'', prop) does not work.')
	 
		assert(strcmp(PanelPropSize.getPropTag(tag), tag), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'PanelPropSize.getPropTag(tag) does not work.')
		assert(strcmp(pr.getPropTag(tag), tag), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'pr.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(pr, tag), tag), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(pr, tag) does not work.')
		assert(strcmp(Element.getPropTag('PanelPropSize', prop), tag), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''PanelPropSize'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:PanelPropSize.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		assert(Category.existsCategory(PanelPropSize.getPropCategory(prop)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'PanelPropSize.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(pr.getPropCategory(prop)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'pr.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(pr, prop)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(pr, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(pr, prop)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''PanelPropSize'', prop) does not work.')
	 
		assert(Category.existsCategory(PanelPropSize.getPropCategory(tag)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'PanelPropSize.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(pr.getPropCategory(tag)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'pr.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(pr, tag)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(pr, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(pr, tag)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''PanelPropSize'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:PanelPropSize.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		assert(Format.existsFormat(PanelPropSize.getPropFormat(prop)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'PanelPropSize.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(pr.getPropFormat(prop)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'pr.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(pr, prop)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(pr, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(pr, prop)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''PanelPropSize'', prop) does not work.')
	 
		assert(Format.existsFormat(PanelPropSize.getPropFormat(tag)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'PanelPropSize.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(pr.getPropFormat(tag)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'pr.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(pr, tag)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(pr, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(pr, tag)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''PanelPropSize'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:PanelPropSize.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		assert(ischar(PanelPropSize.getPropDescription(prop)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'PanelPropSize.getPropDescription(prop) does not work.')
		assert(ischar(pr.getPropDescription(prop)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'pr.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(pr, prop)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(pr, prop) does not work.')
		assert(ischar(Element.getPropDescription(pr, prop)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''PanelPropSize'', prop) does not work.')
	 
		assert(ischar(PanelPropSize.getPropDescription(tag)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'PanelPropSize.getPropDescription(tag) does not work.')
		assert(ischar(pr.getPropDescription(tag)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'pr.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(pr, tag)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(pr, tag) does not work.')
		assert(ischar(Element.getPropDescription(pr, tag)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''PanelPropSize'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:PanelPropSize.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		settings = PanelPropSize.getPropSettings(prop);
		settings = pr.getPropSettings(prop);
		settings = Element.getPropSettings(pr, prop);
		settings = Element.getPropSettings('PanelPropSize', prop);
	 
		settings = PanelPropSize.getPropSettings(tag);
		settings = pr.getPropSettings(tag);
		settings = Element.getPropSettings(pr, tag);
		settings = Element.getPropSettings('PanelPropSize', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:PanelPropSize.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		default = PanelPropSize.getPropDefault(prop);
		default = pr.getPropDefault(prop);
		default = Element.getPropDefault(pr, prop);
		default = Element.getPropDefault('PanelPropSize', prop);
	 
		default = PanelPropSize.getPropDefault(tag);
		default = pr.getPropDefault(tag);
		default = Element.getPropDefault(pr, tag);
		default = Element.getPropDefault('PanelPropSize', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:PanelPropSize.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		conditioned_default = PanelPropSize.getPropDefaultConditioned(prop);
		conditioned_default = pr.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(pr, prop);
		conditioned_default = Element.getPropDefaultConditioned('PanelPropSize', prop);
	 
		conditioned_default = PanelPropSize.getPropDefaultConditioned(tag);
		conditioned_default = pr.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(pr, tag);
		conditioned_default = Element.getPropDefaultConditioned('PanelPropSize', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:PanelPropSize.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		assert(~PanelPropSize.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'PanelPropSize.checkProp(prop, value) does not work.')
		assert(~pr.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'pr.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(pr, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(pr, prop, value) does not work.')
		assert(~Element.checkProp('PanelPropSize', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''PanelPropSize'', prop, value) does not work.')
	 
		assert_with_error('PanelPropSize.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':PanelPropSize:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':PanelPropSize:' BRAPH2.WRONG_INPUT], prop, pr)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':PanelPropSize:' BRAPH2.WRONG_INPUT], prop, pr)
		assert_with_error('Element.checkProp(''PanelPropSize'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':PanelPropSize:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~PanelPropSize.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'PanelPropSize.checkProp(tag, value) does not work.')
		assert(~pr.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'pr.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(pr, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(pr, tag, value) does not work.')
		assert(~Element.checkProp('PanelPropSize', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''PanelPropSize'', tag, value) does not work.')
	 
		assert_with_error('PanelPropSize.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':PanelPropSize:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':PanelPropSize:' BRAPH2.WRONG_INPUT], tag, pr)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':PanelPropSize:' BRAPH2.WRONG_INPUT], tag, pr)
		assert_with_error('Element.checkProp(''PanelPropSize'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':PanelPropSize:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(PanelPropSize.checkProp(prop, Element.getPropDefaultConditioned(PanelPropSize, prop)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'PanelPropSize.checkProp(prop, <conditioned default value>) does not work.')
		assert(pr.checkProp(prop, Element.getPropDefaultConditioned(PanelPropSize, prop)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'pr.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(pr, prop, Element.getPropDefaultConditioned(PanelPropSize, prop)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(pr, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('PanelPropSize', prop, Element.getPropDefaultConditioned(PanelPropSize, prop)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''PanelPropSize'', prop, <conditioned default value>) does not work.')
	 
		assert(PanelPropSize.checkProp(tag, Element.getPropDefaultConditioned(PanelPropSize, prop)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'PanelPropSize.checkProp(tag, <conditioned default value>) does not work.')
		assert(pr.checkProp(tag, Element.getPropDefaultConditioned(PanelPropSize, prop)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'pr.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(pr, tag, Element.getPropDefaultConditioned(PanelPropSize, prop)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(pr, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('PanelPropSize', tag, Element.getPropDefaultConditioned(PanelPropSize, prop)), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''PanelPropSize'', tag, <conditioned default value>) does not work.')
	 
	end
	 
	
	warning('on', [BRAPH2.STR ':PanelPropSize'])
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropSize'])
	
	pr = PanelPropSize( ...
		PanelPropSize.ELCLASS, PanelPropSize.getNoValue(), ...
		PanelPropSize.NAME, PanelPropSize.getNoValue(), ...
		PanelPropSize.DESCRIPTION, PanelPropSize.getNoValue(), ...
		PanelPropSize.TEMPLATE, PanelPropSize.getPropDefault(PanelPropSize.TEMPLATE), ...
		PanelPropSize.ID, PanelPropSize.getPropDefault(PanelPropSize.ID), ...
		PanelPropSize.LABEL, PanelPropSize.getPropDefault(PanelPropSize.LABEL), ...
		PanelPropSize.NOTES, PanelPropSize.getPropDefault(PanelPropSize.NOTES), ...
		PanelPropSize.TOSTRING, PanelPropSize.getNoValue(), ...
		PanelPropSize.WAITBAR, PanelPropSize.getPropDefault(PanelPropSize.WAITBAR), ...
		PanelPropSize.H_WAITBAR, PanelPropSize.getNoValue(), ...
		PanelPropSize.DRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.DRAWN, PanelPropSize.getNoValue(), ...
		PanelPropSize.PARENT, PanelPropSize.getPropDefault(PanelPropSize.PARENT), ...
		PanelPropSize.BKGCOLOR, PanelPropSize.getPropDefault(PanelPropSize.BKGCOLOR), ...
		PanelPropSize.H, PanelPropSize.getNoValue(), ...
		PanelPropSize.SHOW, PanelPropSize.getNoValue(), ...
		PanelPropSize.HIDE, PanelPropSize.getNoValue(), ...
		PanelPropSize.DELETE, PanelPropSize.getNoValue(), ...
		PanelPropSize.CLOSE, PanelPropSize.getNoValue(), ...
		PanelPropSize.X_DRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.UPDATE, PanelPropSize.getNoValue(), ...
		PanelPropSize.REDRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.EL, PanelPropSize.getPropDefault(PanelPropSize.EL), ...
		PanelPropSize.PROP, PanelPropSize.getPropDefault(PanelPropSize.PROP), ...
		PanelPropSize.HEIGHT, PanelPropSize.getPropDefault(PanelPropSize.HEIGHT), ...
		PanelPropSize.TITLE, PanelPropSize.getPropDefault(PanelPropSize.TITLE), ...
		PanelPropSize.LABEL_TITLE, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_CB, PanelPropSize.getNoValue(), ...
		PanelPropSize.GUI_CB, PanelPropSize.getPropDefault(PanelPropSize.GUI_CB), ...
		PanelPropSize.LISTENER_CB, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_CALC, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_DEL, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_SET, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_MEMORIZED, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_LOCKED, PanelPropSize.getNoValue(), ...
		PanelPropSize.ENABLE, PanelPropSize.getPropDefault(PanelPropSize.ENABLE), ...
		PanelPropSize.EDITFIELD, PanelPropSize.getNoValue(), ...
		PanelPropSize.AXES, PanelPropSize.getNoValue(), ...
		PanelPropSize.LN, PanelPropSize.getNoValue() ...
		);
	 
	for prop = 1:1:PanelPropSize.getPropNumber()
	 
		% excluded props
		if any(prop == [PanelPropSize.PARENT PanelPropSize.H PanelPropSize.LISTENER_CB PanelPropSize.EDITFIELD PanelPropSize.AXES PanelPropSize.LN])
			continue
		end
	 
		TAG = upper(PanelPropSize.getPropTag(prop));
		switch PanelPropSize.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					pr.getr(prop) == PanelPropSize.getNoValue(), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['Being a ' PanelPropSize.getCategoryName(PanelPropSize.getPropCategory(prop)) ', PanelPropSize.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in PanelPropSize.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					pr.getr(TAG) == PanelPropSize.getNoValue(), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['Being a ' PanelPropSize.getCategoryName(PanelPropSize.getPropCategory(prop)) ', PanelPropSize.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in PanelPropSize.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(pr.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(pr.getPropSettings(prop))
					assert( ...
						pr.checkFormat(pr.getPropFormat(prop), pr.get(prop)), ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						['PanelPropSize.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						pr.checkFormat(pr.getPropFormat(prop), pr.get(prop), pr.getPropSettings(prop)), ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						['PanelPropSize.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					pr.getr(prop) == PanelPropSize.getNoValue(), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['Being a ' PanelPropSize.getCategoryName(PanelPropSize.getPropCategory(prop)) ', PanelPropSize.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in PanelPropSize.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					pr.getr(TAG) == PanelPropSize.getNoValue(), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['Being a ' PanelPropSize.getCategoryName(PanelPropSize.getPropCategory(prop)) ', PanelPropSize.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in PanelPropSize.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':PanelPropSize']);
				assert( ...
					~isa(pr.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(pr.getPropSettings(prop))
					assert( ...
						pr.checkFormat(pr.getPropFormat(prop), pr.get(prop)), ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						['PanelPropSize.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						pr.checkFormat(pr.getPropFormat(prop), pr.get(prop), pr.getPropSettings(prop)), ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						['PanelPropSize.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(pr.getr(prop), PanelPropSize.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by PanelPropSize.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in PanelPropSize.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(pr.getr(TAG), PanelPropSize.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.getr(' TAG ') must be inizialized to its default value ' ...
					'given by PanelPropSize.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in PanelPropSize.getr(' TAG ').'] ...
					)
		end
	end
	
	warning('on', [BRAPH2.STR ':PanelPropSize'])
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropSize'])
	
	pr = PanelPropSize( ...
		PanelPropSize.ELCLASS, PanelPropSize.getNoValue(), ...
		PanelPropSize.NAME, PanelPropSize.getNoValue(), ...
		PanelPropSize.DESCRIPTION, PanelPropSize.getNoValue(), ...
		PanelPropSize.TEMPLATE, PanelPropSize.getPropDefault(PanelPropSize.TEMPLATE), ...
		PanelPropSize.ID, PanelPropSize.getPropDefault(PanelPropSize.ID), ...
		PanelPropSize.LABEL, PanelPropSize.getPropDefault(PanelPropSize.LABEL), ...
		PanelPropSize.NOTES, PanelPropSize.getPropDefault(PanelPropSize.NOTES), ...
		PanelPropSize.TOSTRING, PanelPropSize.getNoValue(), ...
		PanelPropSize.WAITBAR, PanelPropSize.getPropDefault(PanelPropSize.WAITBAR), ...
		PanelPropSize.H_WAITBAR, PanelPropSize.getNoValue(), ...
		PanelPropSize.DRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.DRAWN, PanelPropSize.getNoValue(), ...
		PanelPropSize.PARENT, PanelPropSize.getPropDefault(PanelPropSize.PARENT), ...
		PanelPropSize.BKGCOLOR, PanelPropSize.getPropDefault(PanelPropSize.BKGCOLOR), ...
		PanelPropSize.H, PanelPropSize.getNoValue(), ...
		PanelPropSize.SHOW, PanelPropSize.getNoValue(), ...
		PanelPropSize.HIDE, PanelPropSize.getNoValue(), ...
		PanelPropSize.DELETE, PanelPropSize.getNoValue(), ...
		PanelPropSize.CLOSE, PanelPropSize.getNoValue(), ...
		PanelPropSize.X_DRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.UPDATE, PanelPropSize.getNoValue(), ...
		PanelPropSize.REDRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.EL, PanelPropSize.getPropDefault(PanelPropSize.EL), ...
		PanelPropSize.PROP, PanelPropSize.getPropDefault(PanelPropSize.PROP), ...
		PanelPropSize.HEIGHT, PanelPropSize.getPropDefault(PanelPropSize.HEIGHT), ...
		PanelPropSize.TITLE, PanelPropSize.getPropDefault(PanelPropSize.TITLE), ...
		PanelPropSize.LABEL_TITLE, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_CB, PanelPropSize.getNoValue(), ...
		PanelPropSize.GUI_CB, PanelPropSize.getPropDefault(PanelPropSize.GUI_CB), ...
		PanelPropSize.LISTENER_CB, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_CALC, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_DEL, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_SET, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_MEMORIZED, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_LOCKED, PanelPropSize.getNoValue(), ...
		PanelPropSize.ENABLE, PanelPropSize.getPropDefault(PanelPropSize.ENABLE), ...
		PanelPropSize.EDITFIELD, PanelPropSize.getNoValue(), ...
		PanelPropSize.AXES, PanelPropSize.getNoValue(), ...
		PanelPropSize.LN, PanelPropSize.getNoValue() ...
		);
	 
	for prop = 1:1:PanelPropSize.getPropNumber()
	 
		% excluded props
		if any(prop == [PanelPropSize.PARENT PanelPropSize.H PanelPropSize.LISTENER_CB PanelPropSize.EDITFIELD PanelPropSize.AXES PanelPropSize.LN])
			continue
		end
	 
		TAG = upper(PanelPropSize.getPropTag(prop));
		switch PanelPropSize.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(pr.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(pr.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(pr.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(pr.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					pr.checkFormat(pr.getPropFormat(prop), pr.getr(prop),pr.getPropSettings(prop)), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':PanelPropSize']);
				assert( ...
					~isa(pr.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(pr.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':PanelPropSize']);
	% 			assert( ...
	% 				~isa(pr.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
	% 				['PanelPropSize.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(pr.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
	% 				['PanelPropSize.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				pr.checkFormat(pr.getPropFormat(prop), pr.getr(prop),pr.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
	% 				['PanelPropSize.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':PanelPropSize']);
				assert( ...
					~isa(pr.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(pr.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(pr.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(pr.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					pr.checkFormat(pr.getPropFormat(prop), pr.getr(prop),pr.getPropSettings(prop)), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if pr.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:PanelPropSize');
					delete(ancestor(pr.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(PanelPropSize.getProps(Category.RESULT))
		for prop = 1:1:PanelPropSize.getPropNumber()
	 
			% excluded props
			if any(prop == [PanelPropSize.PARENT PanelPropSize.H PanelPropSize.LISTENER_CB PanelPropSize.EDITFIELD PanelPropSize.AXES PanelPropSize.LN])
				continue
			end
	 
			switch PanelPropSize.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						pr.isLocked(prop), ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						['PanelPropSize.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~pr.isLocked(prop), ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						['PanelPropSize.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
	
	warning('on', [BRAPH2.STR ':PanelPropSize'])
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropSize'])
	
	pr = PanelPropSize();
	 
	for prop = 1:1:PanelPropSize.getPropNumber()
		TAG = upper(PanelPropSize.getPropTag(prop));
		assert( ...
			~pr.isLocked(prop), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			['PanelPropSize.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~pr.isLocked(TAG), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			['PanelPropSize.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	pr.lock()
	 
	for prop = 1:1:PanelPropSize.getPropNumber()
		switch PanelPropSize.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					pr.isLocked(prop), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~pr.isLocked(prop), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
	
	warning('on', [BRAPH2.STR ':PanelPropSize'])
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropSize'])
	
	pr = PanelPropSize();
	 
	warning_backup = warning('off', 'BRAPH2:PanelPropSize');
	for prop = 1:1:PanelPropSize.getPropNumber()
		pr.lock(prop)
		switch PanelPropSize.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					pr.isLocked(prop), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~pr.isLocked(prop), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
	
	warning('on', [BRAPH2.STR ':PanelPropSize'])
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropSize'])
	
	pr = PanelPropSize();
	 
	for prop = 1:1:PanelPropSize.getPropNumber()
		TAG = upper(PanelPropSize.getPropTag(prop));
		assert( ...
			pr.isChecked(prop), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			['PanelPropSize.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			pr.isChecked(TAG), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			['PanelPropSize.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	pr.unchecked()
	 
	for prop = 1:1:PanelPropSize.getPropNumber()
		assert( ...
			~pr.isChecked(prop), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			['PanelPropSize.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	pr.checked()
	 
	for prop = 1:1:PanelPropSize.getPropNumber()
		assert( ...
			pr.isChecked(prop), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			['PanelPropSize.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
	
	warning('on', [BRAPH2.STR ':PanelPropSize'])
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropSize'])
	
	% basic PanelPropSize
	pr_0 = PanelPropSize( ...
		PanelPropSize.ELCLASS, PanelPropSize.getNoValue(), ...
		PanelPropSize.NAME, PanelPropSize.getNoValue(), ...
		PanelPropSize.DESCRIPTION, PanelPropSize.getNoValue(), ...
		PanelPropSize.TEMPLATE, PanelPropSize.getPropDefault(PanelPropSize.TEMPLATE), ...
		PanelPropSize.ID, PanelPropSize.getPropDefault(PanelPropSize.ID), ...
		PanelPropSize.LABEL, PanelPropSize.getPropDefault(PanelPropSize.LABEL), ...
		PanelPropSize.NOTES, PanelPropSize.getPropDefault(PanelPropSize.NOTES), ...
		PanelPropSize.TOSTRING, PanelPropSize.getNoValue(), ...
		PanelPropSize.WAITBAR, PanelPropSize.getPropDefault(PanelPropSize.WAITBAR), ...
		PanelPropSize.H_WAITBAR, PanelPropSize.getNoValue(), ...
		PanelPropSize.DRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.DRAWN, PanelPropSize.getNoValue(), ...
		PanelPropSize.PARENT, PanelPropSize.getPropDefault(PanelPropSize.PARENT), ...
		PanelPropSize.BKGCOLOR, PanelPropSize.getPropDefault(PanelPropSize.BKGCOLOR), ...
		PanelPropSize.H, PanelPropSize.getNoValue(), ...
		PanelPropSize.SHOW, PanelPropSize.getNoValue(), ...
		PanelPropSize.HIDE, PanelPropSize.getNoValue(), ...
		PanelPropSize.DELETE, PanelPropSize.getNoValue(), ...
		PanelPropSize.CLOSE, PanelPropSize.getNoValue(), ...
		PanelPropSize.X_DRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.UPDATE, PanelPropSize.getNoValue(), ...
		PanelPropSize.REDRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.EL, PanelPropSize.getPropDefault(PanelPropSize.EL), ...
		PanelPropSize.PROP, PanelPropSize.getPropDefault(PanelPropSize.PROP), ...
		PanelPropSize.HEIGHT, PanelPropSize.getPropDefault(PanelPropSize.HEIGHT), ...
		PanelPropSize.TITLE, PanelPropSize.getPropDefault(PanelPropSize.TITLE), ...
		PanelPropSize.LABEL_TITLE, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_CB, PanelPropSize.getNoValue(), ...
		PanelPropSize.GUI_CB, PanelPropSize.getPropDefault(PanelPropSize.GUI_CB), ...
		PanelPropSize.LISTENER_CB, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_CALC, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_DEL, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_SET, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_MEMORIZED, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_LOCKED, PanelPropSize.getNoValue(), ...
		PanelPropSize.ENABLE, PanelPropSize.getPropDefault(PanelPropSize.ENABLE), ...
		PanelPropSize.EDITFIELD, PanelPropSize.getNoValue(), ...
		PanelPropSize.AXES, PanelPropSize.getNoValue(), ...
		PanelPropSize.LN, PanelPropSize.getNoValue() ...
		);
	 
	% PanelPropSize with 1st callbacks
	pr_1 = PanelPropSize( ...
		PanelPropSize.ELCLASS, PanelPropSize.getNoValue(), ...
		PanelPropSize.NAME, PanelPropSize.getNoValue(), ...
		PanelPropSize.DESCRIPTION, PanelPropSize.getNoValue(), ...
		PanelPropSize.TEMPLATE, pr_0.getCallback(4), ..., ...
		PanelPropSize.ID, pr_0.getCallback(5), ..., ...
		PanelPropSize.LABEL, PanelPropSize.getPropDefault(PanelPropSize.LABEL), ...
		PanelPropSize.NOTES, PanelPropSize.getPropDefault(PanelPropSize.NOTES), ...
		PanelPropSize.TOSTRING, PanelPropSize.getNoValue(), ...
		PanelPropSize.WAITBAR, pr_0.getCallback(9), ..., ...
		PanelPropSize.H_WAITBAR, PanelPropSize.getNoValue(), ...
		PanelPropSize.DRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.DRAWN, PanelPropSize.getNoValue(), ...
		PanelPropSize.PARENT, pr_0.getCallback(13), ..., ...
		PanelPropSize.BKGCOLOR, pr_0.getCallback(14), ..., ...
		PanelPropSize.H, PanelPropSize.getNoValue(), ...
		PanelPropSize.SHOW, PanelPropSize.getNoValue(), ...
		PanelPropSize.HIDE, PanelPropSize.getNoValue(), ...
		PanelPropSize.DELETE, PanelPropSize.getNoValue(), ...
		PanelPropSize.CLOSE, PanelPropSize.getNoValue(), ...
		PanelPropSize.X_DRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.UPDATE, PanelPropSize.getNoValue(), ...
		PanelPropSize.REDRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.EL, pr_0.getCallback(23), ..., ...
		PanelPropSize.PROP, pr_0.getCallback(24), ..., ...
		PanelPropSize.HEIGHT, pr_0.getCallback(25), ..., ...
		PanelPropSize.TITLE, pr_0.getCallback(26), ..., ...
		PanelPropSize.LABEL_TITLE, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_CB, PanelPropSize.getNoValue(), ...
		PanelPropSize.GUI_CB, pr_0.getCallback(29), ..., ...
		PanelPropSize.LISTENER_CB, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_CALC, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_DEL, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_SET, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_MEMORIZED, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_LOCKED, PanelPropSize.getNoValue(), ...
		PanelPropSize.ENABLE, pr_0.getCallback(36), ..., ...
		PanelPropSize.EDITFIELD, PanelPropSize.getNoValue(), ...
		PanelPropSize.AXES, PanelPropSize.getNoValue(), ...
		PanelPropSize.LN, PanelPropSize.getNoValue() ...
		);
	 
	prop_number = PanelPropSize.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(PanelPropSize.getPropTag(prop));
		switch PanelPropSize.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(pr_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(pr_1.get(prop), pr_0.get(prop)) && ~isa(pr_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(pr_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% PanelPropSize with 2nd callbacks
	pr_2 = PanelPropSize( ...
		PanelPropSize.ELCLASS, PanelPropSize.getNoValue(), ...
		PanelPropSize.NAME, PanelPropSize.getNoValue(), ...
		PanelPropSize.DESCRIPTION, PanelPropSize.getNoValue(), ...
		PanelPropSize.TEMPLATE, pr_1.getCallback(4), ..., ...
		PanelPropSize.ID, pr_1.getCallback(5), ..., ...
		PanelPropSize.LABEL, PanelPropSize.getPropDefault(PanelPropSize.LABEL), ...
		PanelPropSize.NOTES, PanelPropSize.getPropDefault(PanelPropSize.NOTES), ...
		PanelPropSize.TOSTRING, PanelPropSize.getNoValue(), ...
		PanelPropSize.WAITBAR, pr_1.getCallback(9), ..., ...
		PanelPropSize.H_WAITBAR, PanelPropSize.getNoValue(), ...
		PanelPropSize.DRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.DRAWN, PanelPropSize.getNoValue(), ...
		PanelPropSize.PARENT, pr_1.getCallback(13), ..., ...
		PanelPropSize.BKGCOLOR, pr_1.getCallback(14), ..., ...
		PanelPropSize.H, PanelPropSize.getNoValue(), ...
		PanelPropSize.SHOW, PanelPropSize.getNoValue(), ...
		PanelPropSize.HIDE, PanelPropSize.getNoValue(), ...
		PanelPropSize.DELETE, PanelPropSize.getNoValue(), ...
		PanelPropSize.CLOSE, PanelPropSize.getNoValue(), ...
		PanelPropSize.X_DRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.UPDATE, PanelPropSize.getNoValue(), ...
		PanelPropSize.REDRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.EL, pr_1.getCallback(23), ..., ...
		PanelPropSize.PROP, pr_1.getCallback(24), ..., ...
		PanelPropSize.HEIGHT, pr_1.getCallback(25), ..., ...
		PanelPropSize.TITLE, pr_1.getCallback(26), ..., ...
		PanelPropSize.LABEL_TITLE, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_CB, PanelPropSize.getNoValue(), ...
		PanelPropSize.GUI_CB, pr_1.getCallback(29), ..., ...
		PanelPropSize.LISTENER_CB, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_CALC, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_DEL, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_SET, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_MEMORIZED, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_LOCKED, PanelPropSize.getNoValue(), ...
		PanelPropSize.ENABLE, pr_1.getCallback(36), ..., ...
		PanelPropSize.EDITFIELD, PanelPropSize.getNoValue(), ...
		PanelPropSize.AXES, PanelPropSize.getNoValue(), ...
		PanelPropSize.LN, PanelPropSize.getNoValue() ...
		);
	 
	prop_number = PanelPropSize.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(PanelPropSize.getPropTag(prop));
		switch PanelPropSize.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(pr_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(pr_2.get(prop), pr_0.get(prop)) && ~isa(pr_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(pr_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% PanelPropSize with 3rd callbacks
	pr_3 = PanelPropSize( ...
		PanelPropSize.ELCLASS, PanelPropSize.getNoValue(), ...
		PanelPropSize.NAME, PanelPropSize.getNoValue(), ...
		PanelPropSize.DESCRIPTION, PanelPropSize.getNoValue(), ...
		PanelPropSize.TEMPLATE, pr_2.getCallback(4), ..., ...
		PanelPropSize.ID, pr_2.getCallback(5), ..., ...
		PanelPropSize.LABEL, PanelPropSize.getPropDefault(PanelPropSize.LABEL), ...
		PanelPropSize.NOTES, PanelPropSize.getPropDefault(PanelPropSize.NOTES), ...
		PanelPropSize.TOSTRING, PanelPropSize.getNoValue(), ...
		PanelPropSize.WAITBAR, pr_2.getCallback(9), ..., ...
		PanelPropSize.H_WAITBAR, PanelPropSize.getNoValue(), ...
		PanelPropSize.DRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.DRAWN, PanelPropSize.getNoValue(), ...
		PanelPropSize.PARENT, pr_2.getCallback(13), ..., ...
		PanelPropSize.BKGCOLOR, pr_2.getCallback(14), ..., ...
		PanelPropSize.H, PanelPropSize.getNoValue(), ...
		PanelPropSize.SHOW, PanelPropSize.getNoValue(), ...
		PanelPropSize.HIDE, PanelPropSize.getNoValue(), ...
		PanelPropSize.DELETE, PanelPropSize.getNoValue(), ...
		PanelPropSize.CLOSE, PanelPropSize.getNoValue(), ...
		PanelPropSize.X_DRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.UPDATE, PanelPropSize.getNoValue(), ...
		PanelPropSize.REDRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.EL, pr_2.getCallback(23), ..., ...
		PanelPropSize.PROP, pr_2.getCallback(24), ..., ...
		PanelPropSize.HEIGHT, pr_2.getCallback(25), ..., ...
		PanelPropSize.TITLE, pr_2.getCallback(26), ..., ...
		PanelPropSize.LABEL_TITLE, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_CB, PanelPropSize.getNoValue(), ...
		PanelPropSize.GUI_CB, pr_2.getCallback(29), ..., ...
		PanelPropSize.LISTENER_CB, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_CALC, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_DEL, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_SET, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_MEMORIZED, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_LOCKED, PanelPropSize.getNoValue(), ...
		PanelPropSize.ENABLE, pr_2.getCallback(36), ..., ...
		PanelPropSize.EDITFIELD, PanelPropSize.getNoValue(), ...
		PanelPropSize.AXES, PanelPropSize.getNoValue(), ...
		PanelPropSize.LN, PanelPropSize.getNoValue() ...
		);
	 
	prop_number = PanelPropSize.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(PanelPropSize.getPropTag(prop));
		switch PanelPropSize.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(pr_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(pr_3.get(prop), pr_0.get(prop)) && ~isa(pr_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(pr_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	
	warning('on', [BRAPH2.STR ':PanelPropSize'])
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropSize'])
	
	% copy empty element
	pr = PanelPropSize();
	 
	pr_copy = pr.copy();
	 
	assert(pr_copy ~= pr, ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'PanelPropSize.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(pr_copy, pr), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'PanelPropSize.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:PanelPropSize.getPropNumber()
		value = pr.getr(prop);
		value_copy = pr_copy.getr(prop);
		switch PanelPropSize.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					'PanelPropSize.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						'PanelPropSize.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						'PanelPropSize.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						'PanelPropSize.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
							'PanelPropSize.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
							'PanelPropSize.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						'PanelPropSize.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					pr_copy.isLocked(prop) == pr.isLocked(prop), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					'PanelPropSize.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					pr_copy.isChecked(prop) == pr.isChecked(prop), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					'PanelPropSize.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					pr_copy.getPropSeed(prop) == pr.getPropSeed(prop), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					'PanelPropSize.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	pr = PanelPropSize( ...
		PanelPropSize.ELCLASS, PanelPropSize.getNoValue(), ...
		PanelPropSize.NAME, PanelPropSize.getNoValue(), ...
		PanelPropSize.DESCRIPTION, PanelPropSize.getNoValue(), ...
		PanelPropSize.TEMPLATE, PanelPropSize.getPropDefault(PanelPropSize.TEMPLATE), ...
		PanelPropSize.ID, PanelPropSize.getPropDefault(PanelPropSize.ID), ...
		PanelPropSize.LABEL, PanelPropSize.getPropDefault(PanelPropSize.LABEL), ...
		PanelPropSize.NOTES, PanelPropSize.getPropDefault(PanelPropSize.NOTES), ...
		PanelPropSize.TOSTRING, PanelPropSize.getNoValue(), ...
		PanelPropSize.WAITBAR, PanelPropSize.getPropDefault(PanelPropSize.WAITBAR), ...
		PanelPropSize.H_WAITBAR, PanelPropSize.getNoValue(), ...
		PanelPropSize.DRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.DRAWN, PanelPropSize.getNoValue(), ...
		PanelPropSize.PARENT, PanelPropSize.getPropDefault(PanelPropSize.PARENT), ...
		PanelPropSize.BKGCOLOR, PanelPropSize.getPropDefault(PanelPropSize.BKGCOLOR), ...
		PanelPropSize.H, PanelPropSize.getNoValue(), ...
		PanelPropSize.SHOW, PanelPropSize.getNoValue(), ...
		PanelPropSize.HIDE, PanelPropSize.getNoValue(), ...
		PanelPropSize.DELETE, PanelPropSize.getNoValue(), ...
		PanelPropSize.CLOSE, PanelPropSize.getNoValue(), ...
		PanelPropSize.X_DRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.UPDATE, PanelPropSize.getNoValue(), ...
		PanelPropSize.REDRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.EL, PanelPropSize.getPropDefault(PanelPropSize.EL), ...
		PanelPropSize.PROP, PanelPropSize.getPropDefault(PanelPropSize.PROP), ...
		PanelPropSize.HEIGHT, PanelPropSize.getPropDefault(PanelPropSize.HEIGHT), ...
		PanelPropSize.TITLE, PanelPropSize.getPropDefault(PanelPropSize.TITLE), ...
		PanelPropSize.LABEL_TITLE, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_CB, PanelPropSize.getNoValue(), ...
		PanelPropSize.GUI_CB, PanelPropSize.getPropDefault(PanelPropSize.GUI_CB), ...
		PanelPropSize.LISTENER_CB, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_CALC, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_DEL, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_SET, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_MEMORIZED, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_LOCKED, PanelPropSize.getNoValue(), ...
		PanelPropSize.ENABLE, PanelPropSize.getPropDefault(PanelPropSize.ENABLE), ...
		PanelPropSize.EDITFIELD, PanelPropSize.getNoValue(), ...
		PanelPropSize.AXES, PanelPropSize.getNoValue(), ...
		PanelPropSize.LN, PanelPropSize.getNoValue() ...
		);
	 
	for prop = 1:1:PanelPropSize.getPropNumber()
		if PanelPropSize.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':PanelPropSize']);
			% pr.memorize(prop);
			% warning(warning_backup)
		elseif PanelPropSize.getPropCategory(prop) == Category.EVANESCENT && pr.getPropFormat(prop) == Format.HANDLE
			pr.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:PanelPropSize');
			delete(ancestor(pr.get(prop), 'figure'))
			warning(warning_backup)
		else
			pr.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	pr_copy = pr.copy();
	 
	for prop = 1:1:PanelPropSize.getPropNumber()
		value = pr.getr(prop);
		value_copy = pr_copy.getr(prop);
		switch PanelPropSize.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					'PanelPropSize.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						'PanelPropSize.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						'PanelPropSize.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						'PanelPropSize.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
							'PanelPropSize.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
							'PanelPropSize.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						'PanelPropSize.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						pr_copy.isLocked(prop) == pr.isLocked(prop), ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						'PanelPropSize.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						pr_copy.isChecked(prop) == pr.isChecked(prop), ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						'PanelPropSize.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						pr_copy.getPropSeed(prop) == pr.getPropSeed(prop), ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						'PanelPropSize.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	pr_0 = PanelPropSize( ...
		PanelPropSize.ELCLASS, PanelPropSize.getNoValue(), ...
		PanelPropSize.NAME, PanelPropSize.getNoValue(), ...
		PanelPropSize.DESCRIPTION, PanelPropSize.getNoValue(), ...
		PanelPropSize.TEMPLATE, PanelPropSize.getPropDefault(PanelPropSize.TEMPLATE), ...
		PanelPropSize.ID, PanelPropSize.getPropDefault(PanelPropSize.ID), ...
		PanelPropSize.LABEL, PanelPropSize.getPropDefault(PanelPropSize.LABEL), ...
		PanelPropSize.NOTES, PanelPropSize.getPropDefault(PanelPropSize.NOTES), ...
		PanelPropSize.TOSTRING, PanelPropSize.getNoValue(), ...
		PanelPropSize.WAITBAR, PanelPropSize.getPropDefault(PanelPropSize.WAITBAR), ...
		PanelPropSize.H_WAITBAR, PanelPropSize.getNoValue(), ...
		PanelPropSize.DRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.DRAWN, PanelPropSize.getNoValue(), ...
		PanelPropSize.PARENT, PanelPropSize.getPropDefault(PanelPropSize.PARENT), ...
		PanelPropSize.BKGCOLOR, PanelPropSize.getPropDefault(PanelPropSize.BKGCOLOR), ...
		PanelPropSize.H, PanelPropSize.getNoValue(), ...
		PanelPropSize.SHOW, PanelPropSize.getNoValue(), ...
		PanelPropSize.HIDE, PanelPropSize.getNoValue(), ...
		PanelPropSize.DELETE, PanelPropSize.getNoValue(), ...
		PanelPropSize.CLOSE, PanelPropSize.getNoValue(), ...
		PanelPropSize.X_DRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.UPDATE, PanelPropSize.getNoValue(), ...
		PanelPropSize.REDRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.EL, PanelPropSize.getPropDefault(PanelPropSize.EL), ...
		PanelPropSize.PROP, PanelPropSize.getPropDefault(PanelPropSize.PROP), ...
		PanelPropSize.HEIGHT, PanelPropSize.getPropDefault(PanelPropSize.HEIGHT), ...
		PanelPropSize.TITLE, PanelPropSize.getPropDefault(PanelPropSize.TITLE), ...
		PanelPropSize.LABEL_TITLE, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_CB, PanelPropSize.getNoValue(), ...
		PanelPropSize.GUI_CB, PanelPropSize.getPropDefault(PanelPropSize.GUI_CB), ...
		PanelPropSize.LISTENER_CB, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_CALC, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_DEL, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_SET, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_MEMORIZED, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_LOCKED, PanelPropSize.getNoValue(), ...
		PanelPropSize.ENABLE, PanelPropSize.getPropDefault(PanelPropSize.ENABLE), ...
		PanelPropSize.EDITFIELD, PanelPropSize.getNoValue(), ...
		PanelPropSize.AXES, PanelPropSize.getNoValue(), ...
		PanelPropSize.LN, PanelPropSize.getNoValue() ...
		);
	 
	pr = PanelPropSize( ...
		PanelPropSize.ELCLASS, PanelPropSize.getNoValue(), ...
		PanelPropSize.NAME, PanelPropSize.getNoValue(), ...
		PanelPropSize.DESCRIPTION, PanelPropSize.getNoValue(), ...
		PanelPropSize.TEMPLATE, pr_0.getCallback(4), ..., ...
		PanelPropSize.ID, pr_0.getCallback(5), ..., ...
		PanelPropSize.LABEL, PanelPropSize.getPropDefault(PanelPropSize.LABEL), ...
		PanelPropSize.NOTES, PanelPropSize.getPropDefault(PanelPropSize.NOTES), ...
		PanelPropSize.TOSTRING, PanelPropSize.getNoValue(), ...
		PanelPropSize.WAITBAR, pr_0.getCallback(9), ..., ...
		PanelPropSize.H_WAITBAR, PanelPropSize.getNoValue(), ...
		PanelPropSize.DRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.DRAWN, PanelPropSize.getNoValue(), ...
		PanelPropSize.PARENT, pr_0.getCallback(13), ..., ...
		PanelPropSize.BKGCOLOR, pr_0.getCallback(14), ..., ...
		PanelPropSize.H, PanelPropSize.getNoValue(), ...
		PanelPropSize.SHOW, PanelPropSize.getNoValue(), ...
		PanelPropSize.HIDE, PanelPropSize.getNoValue(), ...
		PanelPropSize.DELETE, PanelPropSize.getNoValue(), ...
		PanelPropSize.CLOSE, PanelPropSize.getNoValue(), ...
		PanelPropSize.X_DRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.UPDATE, PanelPropSize.getNoValue(), ...
		PanelPropSize.REDRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.EL, pr_0.getCallback(23), ..., ...
		PanelPropSize.PROP, pr_0.getCallback(24), ..., ...
		PanelPropSize.HEIGHT, pr_0.getCallback(25), ..., ...
		PanelPropSize.TITLE, pr_0.getCallback(26), ..., ...
		PanelPropSize.LABEL_TITLE, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_CB, PanelPropSize.getNoValue(), ...
		PanelPropSize.GUI_CB, pr_0.getCallback(29), ..., ...
		PanelPropSize.LISTENER_CB, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_CALC, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_DEL, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_SET, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_MEMORIZED, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_LOCKED, PanelPropSize.getNoValue(), ...
		PanelPropSize.ENABLE, pr_0.getCallback(36), ..., ...
		PanelPropSize.EDITFIELD, PanelPropSize.getNoValue(), ...
		PanelPropSize.AXES, PanelPropSize.getNoValue(), ...
		PanelPropSize.LN, PanelPropSize.getNoValue() ...
		);
	 
	pr_copy = pr.copy();
	pr_0_copy = pr_copy.getr('ID').get('EL');
	 
	for prop = 1:1:PanelPropSize.getPropNumber()
		value = pr.getr(prop);
		value_copy = pr_copy.getr(prop);
		switch PanelPropSize.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					'PanelPropSize.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						'PanelPropSize.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						'PanelPropSize.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						'PanelPropSize.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
							'PanelPropSize.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
							'PanelPropSize.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						'PanelPropSize.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == pr_0.getCallback(prop), ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						'PanelPropSize.copy() does not work. The callback should be obtained from PanelPropSize.getCallback().' ...
						)
					assert( ...
						value_copy == pr_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						'PanelPropSize.copy() does not work. The callback should be obtained from PanelPropSize.getCallback().' ...
						)
				end
	 
					assert( ...
						pr_copy.isLocked(prop) == pr.isLocked(prop), ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						'PanelPropSize.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						pr_copy.isChecked(prop) == pr.isChecked(prop), ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						'PanelPropSize.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						pr_copy.getPropSeed(prop) == pr.getPropSeed(prop), ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						'PanelPropSize.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	
	warning('on', [BRAPH2.STR ':PanelPropSize'])
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropSize'])
	
	pr_template = PanelPropSize();
	pr = PanelPropSize('TEMPLATE', pr_template);
	 
	for prop = 1:1:PanelPropSize.getPropNumber()
	 
		% excluded props
		if any(prop == [PanelPropSize.PARENT PanelPropSize.H PanelPropSize.LISTENER_CB PanelPropSize.EDITFIELD PanelPropSize.AXES PanelPropSize.LN])
			continue
		end
	 
		TAG = upper(PanelPropSize.getPropTag(prop));
		switch PanelPropSize.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == PanelPropSize.TEMPLATE
					assert( ...
						isa(pr.getr(prop), 'PanelPropSize'), ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						'PanelPropSize TEMPLATE does not work. PanelPropSize.getr(''TEMPLATE'') should be a PanelPropSize element.' ...
						)
					assert( ...
						isa(pr_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						'PanelPropSize TEMPLATE does not work. PanelPropSize_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(pr.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						['PanelPropSize TEMPLATE does not work. PanelPropSize.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						pr.getr(prop).get('EL') == pr_template && pr.getr(prop).get('PROP') == prop && strcmp(pr.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						['PanelPropSize TEMPLATE does not work. PanelPropSize.getr(' TAG ') should be a Callback to pr_template.' TAG '.'] ...
						)
					assert( ...
						isa(pr_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
						['PanelPropSize TEMPLATE does not work. PanelPropSize_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(pr.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize TEMPLATE does not work. PanelPropSize.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(pr_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
					['PanelPropSize TEMPLATE does not work. PanelPropSize_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
	
	warning('on', [BRAPH2.STR ':PanelPropSize'])
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropSize'])
	
	pr = PanelPropSize( ...
		PanelPropSize.ELCLASS, PanelPropSize.getNoValue(), ...
		PanelPropSize.NAME, PanelPropSize.getNoValue(), ...
		PanelPropSize.DESCRIPTION, PanelPropSize.getNoValue(), ...
		PanelPropSize.TEMPLATE, PanelPropSize.getPropDefault(PanelPropSize.TEMPLATE), ...
		PanelPropSize.ID, PanelPropSize.getPropDefault(PanelPropSize.ID), ...
		PanelPropSize.LABEL, PanelPropSize.getPropDefault(PanelPropSize.LABEL), ...
		PanelPropSize.NOTES, PanelPropSize.getPropDefault(PanelPropSize.NOTES), ...
		PanelPropSize.TOSTRING, PanelPropSize.getNoValue(), ...
		PanelPropSize.WAITBAR, PanelPropSize.getPropDefault(PanelPropSize.WAITBAR), ...
		PanelPropSize.H_WAITBAR, PanelPropSize.getNoValue(), ...
		PanelPropSize.DRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.DRAWN, PanelPropSize.getNoValue(), ...
		PanelPropSize.PARENT, PanelPropSize.getPropDefault(PanelPropSize.PARENT), ...
		PanelPropSize.BKGCOLOR, PanelPropSize.getPropDefault(PanelPropSize.BKGCOLOR), ...
		PanelPropSize.H, PanelPropSize.getNoValue(), ...
		PanelPropSize.SHOW, PanelPropSize.getNoValue(), ...
		PanelPropSize.HIDE, PanelPropSize.getNoValue(), ...
		PanelPropSize.DELETE, PanelPropSize.getNoValue(), ...
		PanelPropSize.CLOSE, PanelPropSize.getNoValue(), ...
		PanelPropSize.X_DRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.UPDATE, PanelPropSize.getNoValue(), ...
		PanelPropSize.REDRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.EL, PanelPropSize.getPropDefault(PanelPropSize.EL), ...
		PanelPropSize.PROP, PanelPropSize.getPropDefault(PanelPropSize.PROP), ...
		PanelPropSize.HEIGHT, PanelPropSize.getPropDefault(PanelPropSize.HEIGHT), ...
		PanelPropSize.TITLE, PanelPropSize.getPropDefault(PanelPropSize.TITLE), ...
		PanelPropSize.LABEL_TITLE, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_CB, PanelPropSize.getNoValue(), ...
		PanelPropSize.GUI_CB, PanelPropSize.getPropDefault(PanelPropSize.GUI_CB), ...
		PanelPropSize.LISTENER_CB, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_CALC, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_DEL, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_SET, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_MEMORIZED, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_LOCKED, PanelPropSize.getNoValue(), ...
		PanelPropSize.ENABLE, PanelPropSize.getPropDefault(PanelPropSize.ENABLE), ...
		PanelPropSize.EDITFIELD, PanelPropSize.getNoValue(), ...
		PanelPropSize.AXES, PanelPropSize.getNoValue(), ...
		PanelPropSize.LN, PanelPropSize.getNoValue() ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'panelpropsize_to_be_erased.b2'];
	 
	Element.save(pr, filename)
	 
	pr_loaded = Element.load(filename);
	 
	assert( ...
		isequal(pr.copy(), pr_loaded), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'PanelPropSize.save(pr) and/or PanelPropSize.load() do not work.' ...
		)
	 
	delete(filename)
	
	warning('on', [BRAPH2.STR ':PanelPropSize'])
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropSize'])
	
	pr = PanelPropSize( ...
		PanelPropSize.ELCLASS, PanelPropSize.getNoValue(), ...
		PanelPropSize.NAME, PanelPropSize.getNoValue(), ...
		PanelPropSize.DESCRIPTION, PanelPropSize.getNoValue(), ...
		PanelPropSize.TEMPLATE, PanelPropSize.getPropDefault(PanelPropSize.TEMPLATE), ...
		PanelPropSize.ID, PanelPropSize.getPropDefault(PanelPropSize.ID), ...
		PanelPropSize.LABEL, PanelPropSize.getPropDefault(PanelPropSize.LABEL), ...
		PanelPropSize.NOTES, PanelPropSize.getPropDefault(PanelPropSize.NOTES), ...
		PanelPropSize.TOSTRING, PanelPropSize.getNoValue(), ...
		PanelPropSize.WAITBAR, PanelPropSize.getPropDefault(PanelPropSize.WAITBAR), ...
		PanelPropSize.H_WAITBAR, PanelPropSize.getNoValue(), ...
		PanelPropSize.DRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.DRAWN, PanelPropSize.getNoValue(), ...
		PanelPropSize.PARENT, PanelPropSize.getPropDefault(PanelPropSize.PARENT), ...
		PanelPropSize.BKGCOLOR, PanelPropSize.getPropDefault(PanelPropSize.BKGCOLOR), ...
		PanelPropSize.H, PanelPropSize.getNoValue(), ...
		PanelPropSize.SHOW, PanelPropSize.getNoValue(), ...
		PanelPropSize.HIDE, PanelPropSize.getNoValue(), ...
		PanelPropSize.DELETE, PanelPropSize.getNoValue(), ...
		PanelPropSize.CLOSE, PanelPropSize.getNoValue(), ...
		PanelPropSize.X_DRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.UPDATE, PanelPropSize.getNoValue(), ...
		PanelPropSize.REDRAW, PanelPropSize.getNoValue(), ...
		PanelPropSize.EL, PanelPropSize.getPropDefault(PanelPropSize.EL), ...
		PanelPropSize.PROP, PanelPropSize.getPropDefault(PanelPropSize.PROP), ...
		PanelPropSize.HEIGHT, PanelPropSize.getPropDefault(PanelPropSize.HEIGHT), ...
		PanelPropSize.TITLE, PanelPropSize.getPropDefault(PanelPropSize.TITLE), ...
		PanelPropSize.LABEL_TITLE, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_CB, PanelPropSize.getNoValue(), ...
		PanelPropSize.GUI_CB, PanelPropSize.getPropDefault(PanelPropSize.GUI_CB), ...
		PanelPropSize.LISTENER_CB, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_CALC, PanelPropSize.getNoValue(), ...
		PanelPropSize.BUTTON_DEL, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_SET, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_MEMORIZED, PanelPropSize.getNoValue(), ...
		PanelPropSize.LISTENER_LOCKED, PanelPropSize.getNoValue(), ...
		PanelPropSize.ENABLE, PanelPropSize.getPropDefault(PanelPropSize.ENABLE), ...
		PanelPropSize.EDITFIELD, PanelPropSize.getNoValue(), ...
		PanelPropSize.AXES, PanelPropSize.getNoValue(), ...
		PanelPropSize.LN, PanelPropSize.getNoValue() ...
		);
	 
	[json, struct, el_list] = encodeJSON(pr);
	[pr_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(pr_dec ~= pr, ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		'PanelPropSize.encodeJSON() or PanelPropSize.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) PanelPropSize.getPropFormat(prop), num2cell(PanelPropSize.getProps())) == Format.HANDLE) && all(cellfun(@(prop) PanelPropSize.getPropFormat(prop), num2cell(PanelPropSize.getProps())) == Format.NET)
		assert(isequal(pr_dec, pr), ...
			[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
			'PanelPropSize.encodeJSON() or PanelPropSize.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
	
	warning('on', [BRAPH2.STR ':PanelPropSize'])
end

%% Test 12: Remove Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropSize'])
	
	warning('off', [BRAPH2.STR ':PanelPropSize'])
	assert(length(findall(0, 'type', 'figure')) == 1)
	delete(findall(0, 'type', 'figure'))
	warning('on', [BRAPH2.STR ':PanelPropSize'])
	
	warning('on', [BRAPH2.STR ':PanelPropSize'])
end

%% Test 13: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropSize'])
	
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':PanelPropSize:' BRAPH2.FAIL_TEST], ...
		[' When testing PanelPropSize no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
	
	warning('on', [BRAPH2.STR ':PanelPropSize'])
end

%% Test 14: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropSize'])
	
	delete(findall(0, 'type', 'figure'))
	
	warning('on', [BRAPH2.STR ':PanelPropSize'])
end

