%TEST_PANELPROPMATRIX

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropMatrix'])
	
	categories = num2cell(Category.getCategories());
	pr = PanelPropMatrix();
	 
	% get('ELCLASS')
	if isa(PanelPropMatrix, 'ConcreteElement')
		assert(strcmp(PanelPropMatrix().get('ELCLASS'), 'PanelPropMatrix'), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'PanelPropMatrix().get(''ELCLASS'') should return ''PanelPropMatrix''.')
	end
	 
	% getBuild()
	assert(PanelPropMatrix.getBuild() == 1 && PanelPropMatrix.getBuild() > 0, ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'PanelPropMatrix.getBuild() should return the PanelPropMatrix build number.')
	assert(pr.getBuild() == 1 && pr.getBuild() > 0 , ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'pr.getBuild() should return the PanelPropMatrix build number.')
	assert(Element.getBuild(pr) == 1 && Element.getBuild(pr) > 0, ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(pr) should return the PanelPropMatrix build number.')
	assert(Element.getBuild('PanelPropMatrix') == 1 && Element.getBuild('PanelPropMatrix') > 0, ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''PanelPropMatrix'') should return the PanelPropMatrix build number.')
	 
	% getClass()
	assert(strcmp(PanelPropMatrix.getClass(), 'PanelPropMatrix'), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'PanelPropMatrix.getClass() should return ''PanelPropMatrix''.')
	assert(strcmp(pr.getClass(), 'PanelPropMatrix'), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'pr.getClass() should return ''PanelPropMatrix''.')
	assert(strcmp(Element.getClass(pr), 'PanelPropMatrix'), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(pr) should return ''PanelPropMatrix''.')
	assert(strcmp(Element.getClass('PanelPropMatrix'), 'PanelPropMatrix'), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''PanelPropMatrix'') should return ''PanelPropMatrix''.')
	 
	% getSubclasses()
	assert(isequal(PanelPropMatrix.getSubclasses(), subclasses('PanelPropMatrix', [], [], true)), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'PanelPropMatrix.getSubclasses() should return the same result as subclasses(''PanelPropMatrix'', [], [], true).')
	assert(isequal(pr.getSubclasses(), subclasses('PanelPropMatrix', [], [], true)), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''PanelPropMatrix'', [], [], true).')
	assert(isequal(Element.getSubclasses(pr), subclasses('PanelPropMatrix', [], [], true)), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(pr) should return the same result as subclasses(''PanelPropMatrix'', [], [], true).')
	assert(isequal(Element.getSubclasses('PanelPropMatrix'), subclasses('PanelPropMatrix', [], [], true)), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''PanelPropMatrix'') should return the same result as subclasses(''PanelPropMatrix'', [], [], true).')
	 
	% getProps()
	assert(isempty(PanelPropMatrix.getProps()) || isequal(PanelPropMatrix.getProps(), 1:1:length(PanelPropMatrix.getProps())), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'PanelPropMatrix.getProps() should return a row vector [1:1:N].')
	assert(isempty(PanelPropMatrix.getProps()) || isequal(pr.getProps(), 1:1:length(PanelPropMatrix.getProps())), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'pr.getProps() should return a row vector [1:1:N].')
	assert(isempty(PanelPropMatrix.getProps()) || isequal(Element.getProps(pr), 1:1:length(PanelPropMatrix.getProps())), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(pr) should return a row vector [1:1:N].')
	assert(isempty(PanelPropMatrix.getProps()) || isequal(Element.getProps('PanelPropMatrix'), 1:1:length(PanelPropMatrix.getProps())), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''PanelPropMatrix'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) PanelPropMatrix.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(PanelPropMatrix.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(PanelPropMatrix.getProps())), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'PanelPropMatrix.getProps(category) does not work.')
	tmp = cellfun(@(category) pr.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(PanelPropMatrix.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(PanelPropMatrix.getProps())), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'pr.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(pr, category), categories, 'UniformOutput', false);
	assert(isempty(PanelPropMatrix.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(PanelPropMatrix.getProps())), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(pr, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('PanelPropMatrix', category), categories, 'UniformOutput', false);
	assert(isempty(PanelPropMatrix.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(PanelPropMatrix.getProps())), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''PanelPropMatrix'', category) does not work.')
	 
	% getPropNumber()
	assert(PanelPropMatrix.getPropNumber() == length(PanelPropMatrix.getProps()), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'PanelPropMatrix.getPropNumber() should return the number of properties.')
	assert(pr.getPropNumber() == length(PanelPropMatrix.getProps()), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'pr.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(pr) == length(PanelPropMatrix.getProps()), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(pr) should return the number of properties.')
	assert(Element.getPropNumber('PanelPropMatrix') == length(PanelPropMatrix.getProps()), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''PanelPropMatrix'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) PanelPropMatrix.getPropNumber(category), categories)) == PanelPropMatrix.getPropNumber(), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'PanelPropMatrix.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) pr.getPropNumber(category), categories)) == PanelPropMatrix.getPropNumber(), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'pr.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(pr, category), categories)) == PanelPropMatrix.getPropNumber(), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(pr, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('PanelPropMatrix', category), categories)) == PanelPropMatrix.getPropNumber(), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''PanelPropMatrix'', category) does not work.')
	 
	% existsProp(prop)
	assert(~PanelPropMatrix.existsProp(NaN), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'PanelPropMatrix.existsProp(prop) does not work.')
	assert(~pr.existsProp(NaN), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'pr.existsProp(prop) does not work.')
	assert(~Element.existsProp(pr, NaN), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(pr, prop) does not work.')
	assert(~Element.existsProp('PanelPropMatrix', NaN), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''PanelPropMatrix'', prop) does not work.')
	 
	assert_with_error('PanelPropMatrix.existsProp(NaN)', [BRAPH2.STR ':PanelPropMatrix:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':PanelPropMatrix:' BRAPH2.WRONG_INPUT], pr)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':PanelPropMatrix:' BRAPH2.WRONG_INPUT], pr)
	assert_with_error('Element.existsProp(''PanelPropMatrix'', NaN)', [BRAPH2.STR ':PanelPropMatrix:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:PanelPropMatrix.getPropNumber()
		assert(PanelPropMatrix.existsProp(prop), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'PanelPropMatrix.existsProp(prop) does not work.')
		assert(pr.existsProp(prop), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'pr.existsProp(prop) does not work.')
		assert(Element.existsProp(pr, prop), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(pr, prop) does not work.')
		assert(Element.existsProp('PanelPropMatrix', prop), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''PanelPropMatrix'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~PanelPropMatrix.existsTag(''), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'PanelPropMatrix.existsTag(tag) does not work.')
	assert(~pr.existsTag(''), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'pr.existsTag(tag) does not work.')
	assert(~Element.existsTag(pr, ''), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(pr, tag) does not work.')
	assert(~Element.existsTag('PanelPropMatrix', ''), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''PanelPropMatrix'', tag) does not work.')
	 
	assert_with_error('PanelPropMatrix.existsTag('''')', [BRAPH2.STR ':PanelPropMatrix:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':PanelPropMatrix:' BRAPH2.WRONG_INPUT], pr)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':PanelPropMatrix:' BRAPH2.WRONG_INPUT], pr)
	assert_with_error('Element.existsTag(''PanelPropMatrix'', '''')', [BRAPH2.STR ':PanelPropMatrix:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:PanelPropMatrix.getPropNumber()
		tag = pr.getPropTag(prop);
		assert(PanelPropMatrix.existsTag(tag), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'PanelPropMatrix.existsTag(tag) does not work.')
		assert(pr.existsTag(tag), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'pr.existsTag(tag) does not work.')
		assert(Element.existsTag(pr, tag), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(pr, tga) does not work.')
		assert(Element.existsTag('PanelPropMatrix', tag), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''PanelPropMatrix'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:PanelPropMatrix.getPropNumber()
		assert(PanelPropMatrix.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'PanelPropMatrix.getPropProp(prop) does not work.')
		assert(pr.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'pr.getPropProp(prop) does not work.')
		assert(Element.getPropProp(pr, prop) == prop, ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(pr, prop) does not work.')
		assert(Element.getPropProp('PanelPropMatrix', prop) == prop, ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''PanelPropMatrix'', prop) does not work.')
	 
		tag = pr.getPropTag(prop);
		assert(PanelPropMatrix.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'PanelPropMatrix.getPropProp(tag) does not work.')
		assert(pr.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'pr.getPropProp(tag) does not work.')
		assert(Element.getPropProp(pr, tag) == prop, ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(pr, tag) does not work.')
		assert(Element.getPropProp('PanelPropMatrix', prop) == prop, ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''PanelPropMatrix'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:PanelPropMatrix.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		assert(strcmp(PanelPropMatrix.getPropTag(prop), tag), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'PanelPropMatrix.getPropTag(prop) does not work.')
		assert(strcmp(pr.getPropTag(prop), tag), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'pr.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(pr, prop), tag), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(pr, prop) does not work.')
		assert(strcmp(Element.getPropTag('PanelPropMatrix', prop), tag), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''PanelPropMatrix'', prop) does not work.')
	 
		assert(strcmp(PanelPropMatrix.getPropTag(tag), tag), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'PanelPropMatrix.getPropTag(tag) does not work.')
		assert(strcmp(pr.getPropTag(tag), tag), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'pr.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(pr, tag), tag), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(pr, tag) does not work.')
		assert(strcmp(Element.getPropTag('PanelPropMatrix', prop), tag), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''PanelPropMatrix'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:PanelPropMatrix.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		assert(Category.existsCategory(PanelPropMatrix.getPropCategory(prop)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'PanelPropMatrix.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(pr.getPropCategory(prop)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'pr.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(pr, prop)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(pr, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(pr, prop)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''PanelPropMatrix'', prop) does not work.')
	 
		assert(Category.existsCategory(PanelPropMatrix.getPropCategory(tag)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'PanelPropMatrix.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(pr.getPropCategory(tag)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'pr.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(pr, tag)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(pr, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(pr, tag)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''PanelPropMatrix'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:PanelPropMatrix.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		assert(Format.existsFormat(PanelPropMatrix.getPropFormat(prop)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'PanelPropMatrix.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(pr.getPropFormat(prop)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'pr.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(pr, prop)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(pr, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(pr, prop)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''PanelPropMatrix'', prop) does not work.')
	 
		assert(Format.existsFormat(PanelPropMatrix.getPropFormat(tag)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'PanelPropMatrix.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(pr.getPropFormat(tag)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'pr.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(pr, tag)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(pr, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(pr, tag)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''PanelPropMatrix'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:PanelPropMatrix.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		assert(ischar(PanelPropMatrix.getPropDescription(prop)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'PanelPropMatrix.getPropDescription(prop) does not work.')
		assert(ischar(pr.getPropDescription(prop)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'pr.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(pr, prop)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(pr, prop) does not work.')
		assert(ischar(Element.getPropDescription(pr, prop)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''PanelPropMatrix'', prop) does not work.')
	 
		assert(ischar(PanelPropMatrix.getPropDescription(tag)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'PanelPropMatrix.getPropDescription(tag) does not work.')
		assert(ischar(pr.getPropDescription(tag)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'pr.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(pr, tag)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(pr, tag) does not work.')
		assert(ischar(Element.getPropDescription(pr, tag)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''PanelPropMatrix'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:PanelPropMatrix.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		settings = PanelPropMatrix.getPropSettings(prop);
		settings = pr.getPropSettings(prop);
		settings = Element.getPropSettings(pr, prop);
		settings = Element.getPropSettings('PanelPropMatrix', prop);
	 
		settings = PanelPropMatrix.getPropSettings(tag);
		settings = pr.getPropSettings(tag);
		settings = Element.getPropSettings(pr, tag);
		settings = Element.getPropSettings('PanelPropMatrix', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:PanelPropMatrix.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		default = PanelPropMatrix.getPropDefault(prop);
		default = pr.getPropDefault(prop);
		default = Element.getPropDefault(pr, prop);
		default = Element.getPropDefault('PanelPropMatrix', prop);
	 
		default = PanelPropMatrix.getPropDefault(tag);
		default = pr.getPropDefault(tag);
		default = Element.getPropDefault(pr, tag);
		default = Element.getPropDefault('PanelPropMatrix', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:PanelPropMatrix.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		conditioned_default = PanelPropMatrix.getPropDefaultConditioned(prop);
		conditioned_default = pr.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(pr, prop);
		conditioned_default = Element.getPropDefaultConditioned('PanelPropMatrix', prop);
	 
		conditioned_default = PanelPropMatrix.getPropDefaultConditioned(tag);
		conditioned_default = pr.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(pr, tag);
		conditioned_default = Element.getPropDefaultConditioned('PanelPropMatrix', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:PanelPropMatrix.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		assert(~PanelPropMatrix.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'PanelPropMatrix.checkProp(prop, value) does not work.')
		assert(~pr.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'pr.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(pr, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(pr, prop, value) does not work.')
		assert(~Element.checkProp('PanelPropMatrix', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''PanelPropMatrix'', prop, value) does not work.')
	 
		assert_with_error('PanelPropMatrix.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':PanelPropMatrix:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':PanelPropMatrix:' BRAPH2.WRONG_INPUT], prop, pr)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':PanelPropMatrix:' BRAPH2.WRONG_INPUT], prop, pr)
		assert_with_error('Element.checkProp(''PanelPropMatrix'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':PanelPropMatrix:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~PanelPropMatrix.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'PanelPropMatrix.checkProp(tag, value) does not work.')
		assert(~pr.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'pr.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(pr, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(pr, tag, value) does not work.')
		assert(~Element.checkProp('PanelPropMatrix', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''PanelPropMatrix'', tag, value) does not work.')
	 
		assert_with_error('PanelPropMatrix.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':PanelPropMatrix:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':PanelPropMatrix:' BRAPH2.WRONG_INPUT], tag, pr)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':PanelPropMatrix:' BRAPH2.WRONG_INPUT], tag, pr)
		assert_with_error('Element.checkProp(''PanelPropMatrix'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':PanelPropMatrix:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(PanelPropMatrix.checkProp(prop, Element.getPropDefaultConditioned(PanelPropMatrix, prop)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'PanelPropMatrix.checkProp(prop, <conditioned default value>) does not work.')
		assert(pr.checkProp(prop, Element.getPropDefaultConditioned(PanelPropMatrix, prop)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'pr.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(pr, prop, Element.getPropDefaultConditioned(PanelPropMatrix, prop)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(pr, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('PanelPropMatrix', prop, Element.getPropDefaultConditioned(PanelPropMatrix, prop)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''PanelPropMatrix'', prop, <conditioned default value>) does not work.')
	 
		assert(PanelPropMatrix.checkProp(tag, Element.getPropDefaultConditioned(PanelPropMatrix, prop)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'PanelPropMatrix.checkProp(tag, <conditioned default value>) does not work.')
		assert(pr.checkProp(tag, Element.getPropDefaultConditioned(PanelPropMatrix, prop)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'pr.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(pr, tag, Element.getPropDefaultConditioned(PanelPropMatrix, prop)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(pr, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('PanelPropMatrix', tag, Element.getPropDefaultConditioned(PanelPropMatrix, prop)), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''PanelPropMatrix'', tag, <conditioned default value>) does not work.')
	 
	end
	 
	
	warning('on', [BRAPH2.STR ':PanelPropMatrix'])
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropMatrix'])
	
	pr = PanelPropMatrix( ...
		PanelPropMatrix.ELCLASS, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.NAME, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DESCRIPTION, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.TEMPLATE, PanelPropMatrix.getPropDefault(PanelPropMatrix.TEMPLATE), ...
		PanelPropMatrix.ID, PanelPropMatrix.getPropDefault(PanelPropMatrix.ID), ...
		PanelPropMatrix.LABEL, PanelPropMatrix.getPropDefault(PanelPropMatrix.LABEL), ...
		PanelPropMatrix.NOTES, PanelPropMatrix.getPropDefault(PanelPropMatrix.NOTES), ...
		PanelPropMatrix.TOSTRING, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.WAITBAR, PanelPropMatrix.getPropDefault(PanelPropMatrix.WAITBAR), ...
		PanelPropMatrix.H_WAITBAR, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DRAWN, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.PARENT, PanelPropMatrix.getPropDefault(PanelPropMatrix.PARENT), ...
		PanelPropMatrix.BKGCOLOR, PanelPropMatrix.getPropDefault(PanelPropMatrix.BKGCOLOR), ...
		PanelPropMatrix.H, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.SHOW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.HIDE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DELETE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.CLOSE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.X_DRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.UPDATE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.REDRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.EL, PanelPropMatrix.getPropDefault(PanelPropMatrix.EL), ...
		PanelPropMatrix.PROP, PanelPropMatrix.getPropDefault(PanelPropMatrix.PROP), ...
		PanelPropMatrix.HEIGHT, PanelPropMatrix.getPropDefault(PanelPropMatrix.HEIGHT), ...
		PanelPropMatrix.TITLE, PanelPropMatrix.getPropDefault(PanelPropMatrix.TITLE), ...
		PanelPropMatrix.LABEL_TITLE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_CB, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.GUI_CB, PanelPropMatrix.getPropDefault(PanelPropMatrix.GUI_CB), ...
		PanelPropMatrix.LISTENER_CB, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_CALC, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_DEL, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_SET, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_MEMORIZED, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_LOCKED, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.ENABLE, PanelPropMatrix.getPropDefault(PanelPropMatrix.ENABLE), ...
		PanelPropMatrix.ROWNAME, PanelPropMatrix.getPropDefault(PanelPropMatrix.ROWNAME), ...
		PanelPropMatrix.COLUMNNAME, PanelPropMatrix.getPropDefault(PanelPropMatrix.COLUMNNAME), ...
		PanelPropMatrix.MENU_EXPORT, PanelPropMatrix.getPropDefault(PanelPropMatrix.MENU_EXPORT), ...
		PanelPropMatrix.TABLE_HEIGHT, PanelPropMatrix.getPropDefault(PanelPropMatrix.TABLE_HEIGHT), ...
		PanelPropMatrix.TABLE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.CONTEXTMENU, PanelPropMatrix.getNoValue() ...
		);
	 
	for prop = 1:1:PanelPropMatrix.getPropNumber()
	 
		% excluded props
		if any(prop == [PanelPropMatrix.PARENT PanelPropMatrix.H PanelPropMatrix.LISTENER_CB PanelPropMatrix.HEIGHT PanelPropMatrix.TABLE PanelPropMatrix.CONTEXTMENU])
			continue
		end
	 
		TAG = upper(PanelPropMatrix.getPropTag(prop));
		switch PanelPropMatrix.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					pr.getr(prop) == PanelPropMatrix.getNoValue(), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['Being a ' PanelPropMatrix.getCategoryName(PanelPropMatrix.getPropCategory(prop)) ', PanelPropMatrix.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in PanelPropMatrix.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					pr.getr(TAG) == PanelPropMatrix.getNoValue(), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['Being a ' PanelPropMatrix.getCategoryName(PanelPropMatrix.getPropCategory(prop)) ', PanelPropMatrix.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in PanelPropMatrix.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(pr.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(pr.getPropSettings(prop))
					assert( ...
						pr.checkFormat(pr.getPropFormat(prop), pr.get(prop)), ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						['PanelPropMatrix.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						pr.checkFormat(pr.getPropFormat(prop), pr.get(prop), pr.getPropSettings(prop)), ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						['PanelPropMatrix.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					pr.getr(prop) == PanelPropMatrix.getNoValue(), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['Being a ' PanelPropMatrix.getCategoryName(PanelPropMatrix.getPropCategory(prop)) ', PanelPropMatrix.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in PanelPropMatrix.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					pr.getr(TAG) == PanelPropMatrix.getNoValue(), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['Being a ' PanelPropMatrix.getCategoryName(PanelPropMatrix.getPropCategory(prop)) ', PanelPropMatrix.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in PanelPropMatrix.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':PanelPropMatrix']);
				assert( ...
					~isa(pr.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(pr.getPropSettings(prop))
					assert( ...
						pr.checkFormat(pr.getPropFormat(prop), pr.get(prop)), ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						['PanelPropMatrix.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						pr.checkFormat(pr.getPropFormat(prop), pr.get(prop), pr.getPropSettings(prop)), ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						['PanelPropMatrix.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(pr.getr(prop), PanelPropMatrix.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by PanelPropMatrix.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in PanelPropMatrix.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(pr.getr(TAG), PanelPropMatrix.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.getr(' TAG ') must be inizialized to its default value ' ...
					'given by PanelPropMatrix.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in PanelPropMatrix.getr(' TAG ').'] ...
					)
		end
	end
	
	warning('on', [BRAPH2.STR ':PanelPropMatrix'])
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropMatrix'])
	
	pr = PanelPropMatrix( ...
		PanelPropMatrix.ELCLASS, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.NAME, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DESCRIPTION, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.TEMPLATE, PanelPropMatrix.getPropDefault(PanelPropMatrix.TEMPLATE), ...
		PanelPropMatrix.ID, PanelPropMatrix.getPropDefault(PanelPropMatrix.ID), ...
		PanelPropMatrix.LABEL, PanelPropMatrix.getPropDefault(PanelPropMatrix.LABEL), ...
		PanelPropMatrix.NOTES, PanelPropMatrix.getPropDefault(PanelPropMatrix.NOTES), ...
		PanelPropMatrix.TOSTRING, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.WAITBAR, PanelPropMatrix.getPropDefault(PanelPropMatrix.WAITBAR), ...
		PanelPropMatrix.H_WAITBAR, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DRAWN, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.PARENT, PanelPropMatrix.getPropDefault(PanelPropMatrix.PARENT), ...
		PanelPropMatrix.BKGCOLOR, PanelPropMatrix.getPropDefault(PanelPropMatrix.BKGCOLOR), ...
		PanelPropMatrix.H, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.SHOW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.HIDE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DELETE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.CLOSE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.X_DRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.UPDATE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.REDRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.EL, PanelPropMatrix.getPropDefault(PanelPropMatrix.EL), ...
		PanelPropMatrix.PROP, PanelPropMatrix.getPropDefault(PanelPropMatrix.PROP), ...
		PanelPropMatrix.HEIGHT, PanelPropMatrix.getPropDefault(PanelPropMatrix.HEIGHT), ...
		PanelPropMatrix.TITLE, PanelPropMatrix.getPropDefault(PanelPropMatrix.TITLE), ...
		PanelPropMatrix.LABEL_TITLE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_CB, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.GUI_CB, PanelPropMatrix.getPropDefault(PanelPropMatrix.GUI_CB), ...
		PanelPropMatrix.LISTENER_CB, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_CALC, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_DEL, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_SET, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_MEMORIZED, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_LOCKED, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.ENABLE, PanelPropMatrix.getPropDefault(PanelPropMatrix.ENABLE), ...
		PanelPropMatrix.ROWNAME, PanelPropMatrix.getPropDefault(PanelPropMatrix.ROWNAME), ...
		PanelPropMatrix.COLUMNNAME, PanelPropMatrix.getPropDefault(PanelPropMatrix.COLUMNNAME), ...
		PanelPropMatrix.MENU_EXPORT, PanelPropMatrix.getPropDefault(PanelPropMatrix.MENU_EXPORT), ...
		PanelPropMatrix.TABLE_HEIGHT, PanelPropMatrix.getPropDefault(PanelPropMatrix.TABLE_HEIGHT), ...
		PanelPropMatrix.TABLE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.CONTEXTMENU, PanelPropMatrix.getNoValue() ...
		);
	 
	for prop = 1:1:PanelPropMatrix.getPropNumber()
	 
		% excluded props
		if any(prop == [PanelPropMatrix.PARENT PanelPropMatrix.H PanelPropMatrix.LISTENER_CB PanelPropMatrix.HEIGHT PanelPropMatrix.TABLE PanelPropMatrix.CONTEXTMENU])
			continue
		end
	 
		TAG = upper(PanelPropMatrix.getPropTag(prop));
		switch PanelPropMatrix.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(pr.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(pr.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(pr.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(pr.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					pr.checkFormat(pr.getPropFormat(prop), pr.getr(prop),pr.getPropSettings(prop)), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':PanelPropMatrix']);
				assert( ...
					~isa(pr.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(pr.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':PanelPropMatrix']);
	% 			assert( ...
	% 				~isa(pr.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
	% 				['PanelPropMatrix.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(pr.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
	% 				['PanelPropMatrix.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				pr.checkFormat(pr.getPropFormat(prop), pr.getr(prop),pr.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
	% 				['PanelPropMatrix.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':PanelPropMatrix']);
				assert( ...
					~isa(pr.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(pr.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(pr.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(pr.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					pr.checkFormat(pr.getPropFormat(prop), pr.getr(prop),pr.getPropSettings(prop)), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if pr.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:PanelPropMatrix');
					delete(ancestor(pr.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(PanelPropMatrix.getProps(Category.RESULT))
		for prop = 1:1:PanelPropMatrix.getPropNumber()
	 
			% excluded props
			if any(prop == [PanelPropMatrix.PARENT PanelPropMatrix.H PanelPropMatrix.LISTENER_CB PanelPropMatrix.HEIGHT PanelPropMatrix.TABLE PanelPropMatrix.CONTEXTMENU])
				continue
			end
	 
			switch PanelPropMatrix.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						pr.isLocked(prop), ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						['PanelPropMatrix.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~pr.isLocked(prop), ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						['PanelPropMatrix.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
	
	warning('on', [BRAPH2.STR ':PanelPropMatrix'])
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropMatrix'])
	
	pr = PanelPropMatrix();
	 
	for prop = 1:1:PanelPropMatrix.getPropNumber()
		TAG = upper(PanelPropMatrix.getPropTag(prop));
		assert( ...
			~pr.isLocked(prop), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			['PanelPropMatrix.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~pr.isLocked(TAG), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			['PanelPropMatrix.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	pr.lock()
	 
	for prop = 1:1:PanelPropMatrix.getPropNumber()
		switch PanelPropMatrix.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					pr.isLocked(prop), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~pr.isLocked(prop), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
	
	warning('on', [BRAPH2.STR ':PanelPropMatrix'])
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropMatrix'])
	
	pr = PanelPropMatrix();
	 
	warning_backup = warning('off', 'BRAPH2:PanelPropMatrix');
	for prop = 1:1:PanelPropMatrix.getPropNumber()
		pr.lock(prop)
		switch PanelPropMatrix.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					pr.isLocked(prop), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~pr.isLocked(prop), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
	
	warning('on', [BRAPH2.STR ':PanelPropMatrix'])
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropMatrix'])
	
	pr = PanelPropMatrix();
	 
	for prop = 1:1:PanelPropMatrix.getPropNumber()
		TAG = upper(PanelPropMatrix.getPropTag(prop));
		assert( ...
			pr.isChecked(prop), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			['PanelPropMatrix.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			pr.isChecked(TAG), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			['PanelPropMatrix.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	pr.unchecked()
	 
	for prop = 1:1:PanelPropMatrix.getPropNumber()
		assert( ...
			~pr.isChecked(prop), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			['PanelPropMatrix.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	pr.checked()
	 
	for prop = 1:1:PanelPropMatrix.getPropNumber()
		assert( ...
			pr.isChecked(prop), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			['PanelPropMatrix.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
	
	warning('on', [BRAPH2.STR ':PanelPropMatrix'])
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropMatrix'])
	
	% basic PanelPropMatrix
	pr_0 = PanelPropMatrix( ...
		PanelPropMatrix.ELCLASS, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.NAME, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DESCRIPTION, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.TEMPLATE, PanelPropMatrix.getPropDefault(PanelPropMatrix.TEMPLATE), ...
		PanelPropMatrix.ID, PanelPropMatrix.getPropDefault(PanelPropMatrix.ID), ...
		PanelPropMatrix.LABEL, PanelPropMatrix.getPropDefault(PanelPropMatrix.LABEL), ...
		PanelPropMatrix.NOTES, PanelPropMatrix.getPropDefault(PanelPropMatrix.NOTES), ...
		PanelPropMatrix.TOSTRING, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.WAITBAR, PanelPropMatrix.getPropDefault(PanelPropMatrix.WAITBAR), ...
		PanelPropMatrix.H_WAITBAR, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DRAWN, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.PARENT, PanelPropMatrix.getPropDefault(PanelPropMatrix.PARENT), ...
		PanelPropMatrix.BKGCOLOR, PanelPropMatrix.getPropDefault(PanelPropMatrix.BKGCOLOR), ...
		PanelPropMatrix.H, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.SHOW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.HIDE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DELETE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.CLOSE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.X_DRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.UPDATE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.REDRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.EL, PanelPropMatrix.getPropDefault(PanelPropMatrix.EL), ...
		PanelPropMatrix.PROP, PanelPropMatrix.getPropDefault(PanelPropMatrix.PROP), ...
		PanelPropMatrix.HEIGHT, PanelPropMatrix.getPropDefault(PanelPropMatrix.HEIGHT), ...
		PanelPropMatrix.TITLE, PanelPropMatrix.getPropDefault(PanelPropMatrix.TITLE), ...
		PanelPropMatrix.LABEL_TITLE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_CB, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.GUI_CB, PanelPropMatrix.getPropDefault(PanelPropMatrix.GUI_CB), ...
		PanelPropMatrix.LISTENER_CB, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_CALC, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_DEL, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_SET, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_MEMORIZED, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_LOCKED, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.ENABLE, PanelPropMatrix.getPropDefault(PanelPropMatrix.ENABLE), ...
		PanelPropMatrix.ROWNAME, PanelPropMatrix.getPropDefault(PanelPropMatrix.ROWNAME), ...
		PanelPropMatrix.COLUMNNAME, PanelPropMatrix.getPropDefault(PanelPropMatrix.COLUMNNAME), ...
		PanelPropMatrix.MENU_EXPORT, PanelPropMatrix.getPropDefault(PanelPropMatrix.MENU_EXPORT), ...
		PanelPropMatrix.TABLE_HEIGHT, PanelPropMatrix.getPropDefault(PanelPropMatrix.TABLE_HEIGHT), ...
		PanelPropMatrix.TABLE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.CONTEXTMENU, PanelPropMatrix.getNoValue() ...
		);
	 
	% PanelPropMatrix with 1st callbacks
	pr_1 = PanelPropMatrix( ...
		PanelPropMatrix.ELCLASS, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.NAME, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DESCRIPTION, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.TEMPLATE, pr_0.getCallback(4), ..., ...
		PanelPropMatrix.ID, pr_0.getCallback(5), ..., ...
		PanelPropMatrix.LABEL, PanelPropMatrix.getPropDefault(PanelPropMatrix.LABEL), ...
		PanelPropMatrix.NOTES, PanelPropMatrix.getPropDefault(PanelPropMatrix.NOTES), ...
		PanelPropMatrix.TOSTRING, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.WAITBAR, pr_0.getCallback(9), ..., ...
		PanelPropMatrix.H_WAITBAR, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DRAWN, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.PARENT, pr_0.getCallback(13), ..., ...
		PanelPropMatrix.BKGCOLOR, pr_0.getCallback(14), ..., ...
		PanelPropMatrix.H, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.SHOW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.HIDE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DELETE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.CLOSE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.X_DRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.UPDATE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.REDRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.EL, pr_0.getCallback(23), ..., ...
		PanelPropMatrix.PROP, pr_0.getCallback(24), ..., ...
		PanelPropMatrix.HEIGHT, pr_0.getCallback(25), ..., ...
		PanelPropMatrix.TITLE, pr_0.getCallback(26), ..., ...
		PanelPropMatrix.LABEL_TITLE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_CB, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.GUI_CB, pr_0.getCallback(29), ..., ...
		PanelPropMatrix.LISTENER_CB, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_CALC, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_DEL, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_SET, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_MEMORIZED, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_LOCKED, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.ENABLE, pr_0.getCallback(36), ..., ...
		PanelPropMatrix.ROWNAME, pr_0.getCallback(37), ..., ...
		PanelPropMatrix.COLUMNNAME, pr_0.getCallback(38), ..., ...
		PanelPropMatrix.MENU_EXPORT, pr_0.getCallback(39), ..., ...
		PanelPropMatrix.TABLE_HEIGHT, pr_0.getCallback(40), ..., ...
		PanelPropMatrix.TABLE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.CONTEXTMENU, PanelPropMatrix.getNoValue() ...
		);
	 
	prop_number = PanelPropMatrix.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(PanelPropMatrix.getPropTag(prop));
		switch PanelPropMatrix.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(pr_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(pr_1.get(prop), pr_0.get(prop)) && ~isa(pr_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(pr_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% PanelPropMatrix with 2nd callbacks
	pr_2 = PanelPropMatrix( ...
		PanelPropMatrix.ELCLASS, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.NAME, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DESCRIPTION, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.TEMPLATE, pr_1.getCallback(4), ..., ...
		PanelPropMatrix.ID, pr_1.getCallback(5), ..., ...
		PanelPropMatrix.LABEL, PanelPropMatrix.getPropDefault(PanelPropMatrix.LABEL), ...
		PanelPropMatrix.NOTES, PanelPropMatrix.getPropDefault(PanelPropMatrix.NOTES), ...
		PanelPropMatrix.TOSTRING, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.WAITBAR, pr_1.getCallback(9), ..., ...
		PanelPropMatrix.H_WAITBAR, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DRAWN, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.PARENT, pr_1.getCallback(13), ..., ...
		PanelPropMatrix.BKGCOLOR, pr_1.getCallback(14), ..., ...
		PanelPropMatrix.H, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.SHOW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.HIDE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DELETE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.CLOSE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.X_DRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.UPDATE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.REDRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.EL, pr_1.getCallback(23), ..., ...
		PanelPropMatrix.PROP, pr_1.getCallback(24), ..., ...
		PanelPropMatrix.HEIGHT, pr_1.getCallback(25), ..., ...
		PanelPropMatrix.TITLE, pr_1.getCallback(26), ..., ...
		PanelPropMatrix.LABEL_TITLE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_CB, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.GUI_CB, pr_1.getCallback(29), ..., ...
		PanelPropMatrix.LISTENER_CB, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_CALC, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_DEL, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_SET, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_MEMORIZED, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_LOCKED, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.ENABLE, pr_1.getCallback(36), ..., ...
		PanelPropMatrix.ROWNAME, pr_1.getCallback(37), ..., ...
		PanelPropMatrix.COLUMNNAME, pr_1.getCallback(38), ..., ...
		PanelPropMatrix.MENU_EXPORT, pr_1.getCallback(39), ..., ...
		PanelPropMatrix.TABLE_HEIGHT, pr_1.getCallback(40), ..., ...
		PanelPropMatrix.TABLE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.CONTEXTMENU, PanelPropMatrix.getNoValue() ...
		);
	 
	prop_number = PanelPropMatrix.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(PanelPropMatrix.getPropTag(prop));
		switch PanelPropMatrix.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(pr_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(pr_2.get(prop), pr_0.get(prop)) && ~isa(pr_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(pr_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% PanelPropMatrix with 3rd callbacks
	pr_3 = PanelPropMatrix( ...
		PanelPropMatrix.ELCLASS, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.NAME, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DESCRIPTION, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.TEMPLATE, pr_2.getCallback(4), ..., ...
		PanelPropMatrix.ID, pr_2.getCallback(5), ..., ...
		PanelPropMatrix.LABEL, PanelPropMatrix.getPropDefault(PanelPropMatrix.LABEL), ...
		PanelPropMatrix.NOTES, PanelPropMatrix.getPropDefault(PanelPropMatrix.NOTES), ...
		PanelPropMatrix.TOSTRING, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.WAITBAR, pr_2.getCallback(9), ..., ...
		PanelPropMatrix.H_WAITBAR, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DRAWN, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.PARENT, pr_2.getCallback(13), ..., ...
		PanelPropMatrix.BKGCOLOR, pr_2.getCallback(14), ..., ...
		PanelPropMatrix.H, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.SHOW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.HIDE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DELETE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.CLOSE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.X_DRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.UPDATE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.REDRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.EL, pr_2.getCallback(23), ..., ...
		PanelPropMatrix.PROP, pr_2.getCallback(24), ..., ...
		PanelPropMatrix.HEIGHT, pr_2.getCallback(25), ..., ...
		PanelPropMatrix.TITLE, pr_2.getCallback(26), ..., ...
		PanelPropMatrix.LABEL_TITLE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_CB, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.GUI_CB, pr_2.getCallback(29), ..., ...
		PanelPropMatrix.LISTENER_CB, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_CALC, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_DEL, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_SET, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_MEMORIZED, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_LOCKED, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.ENABLE, pr_2.getCallback(36), ..., ...
		PanelPropMatrix.ROWNAME, pr_2.getCallback(37), ..., ...
		PanelPropMatrix.COLUMNNAME, pr_2.getCallback(38), ..., ...
		PanelPropMatrix.MENU_EXPORT, pr_2.getCallback(39), ..., ...
		PanelPropMatrix.TABLE_HEIGHT, pr_2.getCallback(40), ..., ...
		PanelPropMatrix.TABLE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.CONTEXTMENU, PanelPropMatrix.getNoValue() ...
		);
	 
	prop_number = PanelPropMatrix.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(PanelPropMatrix.getPropTag(prop));
		switch PanelPropMatrix.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(pr_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(pr_3.get(prop), pr_0.get(prop)) && ~isa(pr_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(pr_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	
	warning('on', [BRAPH2.STR ':PanelPropMatrix'])
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropMatrix'])
	
	% copy empty element
	pr = PanelPropMatrix();
	 
	pr_copy = pr.copy();
	 
	assert(pr_copy ~= pr, ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'PanelPropMatrix.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(pr_copy, pr), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'PanelPropMatrix.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:PanelPropMatrix.getPropNumber()
		value = pr.getr(prop);
		value_copy = pr_copy.getr(prop);
		switch PanelPropMatrix.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					'PanelPropMatrix.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						'PanelPropMatrix.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						'PanelPropMatrix.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						'PanelPropMatrix.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
							'PanelPropMatrix.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
							'PanelPropMatrix.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						'PanelPropMatrix.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					pr_copy.isLocked(prop) == pr.isLocked(prop), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					'PanelPropMatrix.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					pr_copy.isChecked(prop) == pr.isChecked(prop), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					'PanelPropMatrix.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					pr_copy.getPropSeed(prop) == pr.getPropSeed(prop), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					'PanelPropMatrix.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	pr = PanelPropMatrix( ...
		PanelPropMatrix.ELCLASS, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.NAME, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DESCRIPTION, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.TEMPLATE, PanelPropMatrix.getPropDefault(PanelPropMatrix.TEMPLATE), ...
		PanelPropMatrix.ID, PanelPropMatrix.getPropDefault(PanelPropMatrix.ID), ...
		PanelPropMatrix.LABEL, PanelPropMatrix.getPropDefault(PanelPropMatrix.LABEL), ...
		PanelPropMatrix.NOTES, PanelPropMatrix.getPropDefault(PanelPropMatrix.NOTES), ...
		PanelPropMatrix.TOSTRING, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.WAITBAR, PanelPropMatrix.getPropDefault(PanelPropMatrix.WAITBAR), ...
		PanelPropMatrix.H_WAITBAR, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DRAWN, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.PARENT, PanelPropMatrix.getPropDefault(PanelPropMatrix.PARENT), ...
		PanelPropMatrix.BKGCOLOR, PanelPropMatrix.getPropDefault(PanelPropMatrix.BKGCOLOR), ...
		PanelPropMatrix.H, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.SHOW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.HIDE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DELETE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.CLOSE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.X_DRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.UPDATE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.REDRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.EL, PanelPropMatrix.getPropDefault(PanelPropMatrix.EL), ...
		PanelPropMatrix.PROP, PanelPropMatrix.getPropDefault(PanelPropMatrix.PROP), ...
		PanelPropMatrix.HEIGHT, PanelPropMatrix.getPropDefault(PanelPropMatrix.HEIGHT), ...
		PanelPropMatrix.TITLE, PanelPropMatrix.getPropDefault(PanelPropMatrix.TITLE), ...
		PanelPropMatrix.LABEL_TITLE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_CB, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.GUI_CB, PanelPropMatrix.getPropDefault(PanelPropMatrix.GUI_CB), ...
		PanelPropMatrix.LISTENER_CB, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_CALC, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_DEL, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_SET, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_MEMORIZED, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_LOCKED, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.ENABLE, PanelPropMatrix.getPropDefault(PanelPropMatrix.ENABLE), ...
		PanelPropMatrix.ROWNAME, PanelPropMatrix.getPropDefault(PanelPropMatrix.ROWNAME), ...
		PanelPropMatrix.COLUMNNAME, PanelPropMatrix.getPropDefault(PanelPropMatrix.COLUMNNAME), ...
		PanelPropMatrix.MENU_EXPORT, PanelPropMatrix.getPropDefault(PanelPropMatrix.MENU_EXPORT), ...
		PanelPropMatrix.TABLE_HEIGHT, PanelPropMatrix.getPropDefault(PanelPropMatrix.TABLE_HEIGHT), ...
		PanelPropMatrix.TABLE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.CONTEXTMENU, PanelPropMatrix.getNoValue() ...
		);
	 
	for prop = 1:1:PanelPropMatrix.getPropNumber()
		if PanelPropMatrix.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':PanelPropMatrix']);
			% pr.memorize(prop);
			% warning(warning_backup)
		elseif PanelPropMatrix.getPropCategory(prop) == Category.EVANESCENT && pr.getPropFormat(prop) == Format.HANDLE
			pr.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:PanelPropMatrix');
			delete(ancestor(pr.get(prop), 'figure'))
			warning(warning_backup)
		else
			pr.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	pr_copy = pr.copy();
	 
	for prop = 1:1:PanelPropMatrix.getPropNumber()
		value = pr.getr(prop);
		value_copy = pr_copy.getr(prop);
		switch PanelPropMatrix.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					'PanelPropMatrix.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						'PanelPropMatrix.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						'PanelPropMatrix.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						'PanelPropMatrix.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
							'PanelPropMatrix.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
							'PanelPropMatrix.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						'PanelPropMatrix.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						pr_copy.isLocked(prop) == pr.isLocked(prop), ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						'PanelPropMatrix.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						pr_copy.isChecked(prop) == pr.isChecked(prop), ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						'PanelPropMatrix.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						pr_copy.getPropSeed(prop) == pr.getPropSeed(prop), ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						'PanelPropMatrix.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	pr_0 = PanelPropMatrix( ...
		PanelPropMatrix.ELCLASS, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.NAME, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DESCRIPTION, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.TEMPLATE, PanelPropMatrix.getPropDefault(PanelPropMatrix.TEMPLATE), ...
		PanelPropMatrix.ID, PanelPropMatrix.getPropDefault(PanelPropMatrix.ID), ...
		PanelPropMatrix.LABEL, PanelPropMatrix.getPropDefault(PanelPropMatrix.LABEL), ...
		PanelPropMatrix.NOTES, PanelPropMatrix.getPropDefault(PanelPropMatrix.NOTES), ...
		PanelPropMatrix.TOSTRING, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.WAITBAR, PanelPropMatrix.getPropDefault(PanelPropMatrix.WAITBAR), ...
		PanelPropMatrix.H_WAITBAR, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DRAWN, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.PARENT, PanelPropMatrix.getPropDefault(PanelPropMatrix.PARENT), ...
		PanelPropMatrix.BKGCOLOR, PanelPropMatrix.getPropDefault(PanelPropMatrix.BKGCOLOR), ...
		PanelPropMatrix.H, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.SHOW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.HIDE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DELETE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.CLOSE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.X_DRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.UPDATE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.REDRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.EL, PanelPropMatrix.getPropDefault(PanelPropMatrix.EL), ...
		PanelPropMatrix.PROP, PanelPropMatrix.getPropDefault(PanelPropMatrix.PROP), ...
		PanelPropMatrix.HEIGHT, PanelPropMatrix.getPropDefault(PanelPropMatrix.HEIGHT), ...
		PanelPropMatrix.TITLE, PanelPropMatrix.getPropDefault(PanelPropMatrix.TITLE), ...
		PanelPropMatrix.LABEL_TITLE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_CB, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.GUI_CB, PanelPropMatrix.getPropDefault(PanelPropMatrix.GUI_CB), ...
		PanelPropMatrix.LISTENER_CB, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_CALC, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_DEL, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_SET, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_MEMORIZED, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_LOCKED, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.ENABLE, PanelPropMatrix.getPropDefault(PanelPropMatrix.ENABLE), ...
		PanelPropMatrix.ROWNAME, PanelPropMatrix.getPropDefault(PanelPropMatrix.ROWNAME), ...
		PanelPropMatrix.COLUMNNAME, PanelPropMatrix.getPropDefault(PanelPropMatrix.COLUMNNAME), ...
		PanelPropMatrix.MENU_EXPORT, PanelPropMatrix.getPropDefault(PanelPropMatrix.MENU_EXPORT), ...
		PanelPropMatrix.TABLE_HEIGHT, PanelPropMatrix.getPropDefault(PanelPropMatrix.TABLE_HEIGHT), ...
		PanelPropMatrix.TABLE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.CONTEXTMENU, PanelPropMatrix.getNoValue() ...
		);
	 
	pr = PanelPropMatrix( ...
		PanelPropMatrix.ELCLASS, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.NAME, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DESCRIPTION, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.TEMPLATE, pr_0.getCallback(4), ..., ...
		PanelPropMatrix.ID, pr_0.getCallback(5), ..., ...
		PanelPropMatrix.LABEL, PanelPropMatrix.getPropDefault(PanelPropMatrix.LABEL), ...
		PanelPropMatrix.NOTES, PanelPropMatrix.getPropDefault(PanelPropMatrix.NOTES), ...
		PanelPropMatrix.TOSTRING, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.WAITBAR, pr_0.getCallback(9), ..., ...
		PanelPropMatrix.H_WAITBAR, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DRAWN, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.PARENT, pr_0.getCallback(13), ..., ...
		PanelPropMatrix.BKGCOLOR, pr_0.getCallback(14), ..., ...
		PanelPropMatrix.H, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.SHOW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.HIDE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DELETE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.CLOSE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.X_DRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.UPDATE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.REDRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.EL, pr_0.getCallback(23), ..., ...
		PanelPropMatrix.PROP, pr_0.getCallback(24), ..., ...
		PanelPropMatrix.HEIGHT, pr_0.getCallback(25), ..., ...
		PanelPropMatrix.TITLE, pr_0.getCallback(26), ..., ...
		PanelPropMatrix.LABEL_TITLE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_CB, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.GUI_CB, pr_0.getCallback(29), ..., ...
		PanelPropMatrix.LISTENER_CB, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_CALC, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_DEL, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_SET, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_MEMORIZED, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_LOCKED, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.ENABLE, pr_0.getCallback(36), ..., ...
		PanelPropMatrix.ROWNAME, pr_0.getCallback(37), ..., ...
		PanelPropMatrix.COLUMNNAME, pr_0.getCallback(38), ..., ...
		PanelPropMatrix.MENU_EXPORT, pr_0.getCallback(39), ..., ...
		PanelPropMatrix.TABLE_HEIGHT, pr_0.getCallback(40), ..., ...
		PanelPropMatrix.TABLE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.CONTEXTMENU, PanelPropMatrix.getNoValue() ...
		);
	 
	pr_copy = pr.copy();
	pr_0_copy = pr_copy.getr('ID').get('EL');
	 
	for prop = 1:1:PanelPropMatrix.getPropNumber()
		value = pr.getr(prop);
		value_copy = pr_copy.getr(prop);
		switch PanelPropMatrix.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					'PanelPropMatrix.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						'PanelPropMatrix.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						'PanelPropMatrix.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						'PanelPropMatrix.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
							'PanelPropMatrix.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
							'PanelPropMatrix.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						'PanelPropMatrix.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == pr_0.getCallback(prop), ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						'PanelPropMatrix.copy() does not work. The callback should be obtained from PanelPropMatrix.getCallback().' ...
						)
					assert( ...
						value_copy == pr_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						'PanelPropMatrix.copy() does not work. The callback should be obtained from PanelPropMatrix.getCallback().' ...
						)
				end
	 
					assert( ...
						pr_copy.isLocked(prop) == pr.isLocked(prop), ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						'PanelPropMatrix.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						pr_copy.isChecked(prop) == pr.isChecked(prop), ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						'PanelPropMatrix.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						pr_copy.getPropSeed(prop) == pr.getPropSeed(prop), ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						'PanelPropMatrix.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	
	warning('on', [BRAPH2.STR ':PanelPropMatrix'])
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropMatrix'])
	
	pr_template = PanelPropMatrix();
	pr = PanelPropMatrix('TEMPLATE', pr_template);
	 
	for prop = 1:1:PanelPropMatrix.getPropNumber()
	 
		% excluded props
		if any(prop == [PanelPropMatrix.PARENT PanelPropMatrix.H PanelPropMatrix.LISTENER_CB PanelPropMatrix.HEIGHT PanelPropMatrix.TABLE PanelPropMatrix.CONTEXTMENU])
			continue
		end
	 
		TAG = upper(PanelPropMatrix.getPropTag(prop));
		switch PanelPropMatrix.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == PanelPropMatrix.TEMPLATE
					assert( ...
						isa(pr.getr(prop), 'PanelPropMatrix'), ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						'PanelPropMatrix TEMPLATE does not work. PanelPropMatrix.getr(''TEMPLATE'') should be a PanelPropMatrix element.' ...
						)
					assert( ...
						isa(pr_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						'PanelPropMatrix TEMPLATE does not work. PanelPropMatrix_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(pr.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						['PanelPropMatrix TEMPLATE does not work. PanelPropMatrix.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						pr.getr(prop).get('EL') == pr_template && pr.getr(prop).get('PROP') == prop && strcmp(pr.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						['PanelPropMatrix TEMPLATE does not work. PanelPropMatrix.getr(' TAG ') should be a Callback to pr_template.' TAG '.'] ...
						)
					assert( ...
						isa(pr_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
						['PanelPropMatrix TEMPLATE does not work. PanelPropMatrix_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(pr.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix TEMPLATE does not work. PanelPropMatrix.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(pr_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
					['PanelPropMatrix TEMPLATE does not work. PanelPropMatrix_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
	
	warning('on', [BRAPH2.STR ':PanelPropMatrix'])
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropMatrix'])
	
	pr = PanelPropMatrix( ...
		PanelPropMatrix.ELCLASS, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.NAME, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DESCRIPTION, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.TEMPLATE, PanelPropMatrix.getPropDefault(PanelPropMatrix.TEMPLATE), ...
		PanelPropMatrix.ID, PanelPropMatrix.getPropDefault(PanelPropMatrix.ID), ...
		PanelPropMatrix.LABEL, PanelPropMatrix.getPropDefault(PanelPropMatrix.LABEL), ...
		PanelPropMatrix.NOTES, PanelPropMatrix.getPropDefault(PanelPropMatrix.NOTES), ...
		PanelPropMatrix.TOSTRING, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.WAITBAR, PanelPropMatrix.getPropDefault(PanelPropMatrix.WAITBAR), ...
		PanelPropMatrix.H_WAITBAR, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DRAWN, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.PARENT, PanelPropMatrix.getPropDefault(PanelPropMatrix.PARENT), ...
		PanelPropMatrix.BKGCOLOR, PanelPropMatrix.getPropDefault(PanelPropMatrix.BKGCOLOR), ...
		PanelPropMatrix.H, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.SHOW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.HIDE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DELETE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.CLOSE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.X_DRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.UPDATE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.REDRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.EL, PanelPropMatrix.getPropDefault(PanelPropMatrix.EL), ...
		PanelPropMatrix.PROP, PanelPropMatrix.getPropDefault(PanelPropMatrix.PROP), ...
		PanelPropMatrix.HEIGHT, PanelPropMatrix.getPropDefault(PanelPropMatrix.HEIGHT), ...
		PanelPropMatrix.TITLE, PanelPropMatrix.getPropDefault(PanelPropMatrix.TITLE), ...
		PanelPropMatrix.LABEL_TITLE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_CB, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.GUI_CB, PanelPropMatrix.getPropDefault(PanelPropMatrix.GUI_CB), ...
		PanelPropMatrix.LISTENER_CB, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_CALC, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_DEL, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_SET, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_MEMORIZED, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_LOCKED, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.ENABLE, PanelPropMatrix.getPropDefault(PanelPropMatrix.ENABLE), ...
		PanelPropMatrix.ROWNAME, PanelPropMatrix.getPropDefault(PanelPropMatrix.ROWNAME), ...
		PanelPropMatrix.COLUMNNAME, PanelPropMatrix.getPropDefault(PanelPropMatrix.COLUMNNAME), ...
		PanelPropMatrix.MENU_EXPORT, PanelPropMatrix.getPropDefault(PanelPropMatrix.MENU_EXPORT), ...
		PanelPropMatrix.TABLE_HEIGHT, PanelPropMatrix.getPropDefault(PanelPropMatrix.TABLE_HEIGHT), ...
		PanelPropMatrix.TABLE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.CONTEXTMENU, PanelPropMatrix.getNoValue() ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'panelpropmatrix_to_be_erased.b2'];
	 
	Element.save(pr, filename)
	 
	pr_loaded = Element.load(filename);
	 
	assert( ...
		isequal(pr.copy(), pr_loaded), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'PanelPropMatrix.save(pr) and/or PanelPropMatrix.load() do not work.' ...
		)
	 
	delete(filename)
	
	warning('on', [BRAPH2.STR ':PanelPropMatrix'])
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropMatrix'])
	
	pr = PanelPropMatrix( ...
		PanelPropMatrix.ELCLASS, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.NAME, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DESCRIPTION, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.TEMPLATE, PanelPropMatrix.getPropDefault(PanelPropMatrix.TEMPLATE), ...
		PanelPropMatrix.ID, PanelPropMatrix.getPropDefault(PanelPropMatrix.ID), ...
		PanelPropMatrix.LABEL, PanelPropMatrix.getPropDefault(PanelPropMatrix.LABEL), ...
		PanelPropMatrix.NOTES, PanelPropMatrix.getPropDefault(PanelPropMatrix.NOTES), ...
		PanelPropMatrix.TOSTRING, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.WAITBAR, PanelPropMatrix.getPropDefault(PanelPropMatrix.WAITBAR), ...
		PanelPropMatrix.H_WAITBAR, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DRAWN, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.PARENT, PanelPropMatrix.getPropDefault(PanelPropMatrix.PARENT), ...
		PanelPropMatrix.BKGCOLOR, PanelPropMatrix.getPropDefault(PanelPropMatrix.BKGCOLOR), ...
		PanelPropMatrix.H, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.SHOW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.HIDE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.DELETE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.CLOSE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.X_DRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.UPDATE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.REDRAW, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.EL, PanelPropMatrix.getPropDefault(PanelPropMatrix.EL), ...
		PanelPropMatrix.PROP, PanelPropMatrix.getPropDefault(PanelPropMatrix.PROP), ...
		PanelPropMatrix.HEIGHT, PanelPropMatrix.getPropDefault(PanelPropMatrix.HEIGHT), ...
		PanelPropMatrix.TITLE, PanelPropMatrix.getPropDefault(PanelPropMatrix.TITLE), ...
		PanelPropMatrix.LABEL_TITLE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_CB, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.GUI_CB, PanelPropMatrix.getPropDefault(PanelPropMatrix.GUI_CB), ...
		PanelPropMatrix.LISTENER_CB, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_CALC, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.BUTTON_DEL, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_SET, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_MEMORIZED, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.LISTENER_LOCKED, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.ENABLE, PanelPropMatrix.getPropDefault(PanelPropMatrix.ENABLE), ...
		PanelPropMatrix.ROWNAME, PanelPropMatrix.getPropDefault(PanelPropMatrix.ROWNAME), ...
		PanelPropMatrix.COLUMNNAME, PanelPropMatrix.getPropDefault(PanelPropMatrix.COLUMNNAME), ...
		PanelPropMatrix.MENU_EXPORT, PanelPropMatrix.getPropDefault(PanelPropMatrix.MENU_EXPORT), ...
		PanelPropMatrix.TABLE_HEIGHT, PanelPropMatrix.getPropDefault(PanelPropMatrix.TABLE_HEIGHT), ...
		PanelPropMatrix.TABLE, PanelPropMatrix.getNoValue(), ...
		PanelPropMatrix.CONTEXTMENU, PanelPropMatrix.getNoValue() ...
		);
	 
	[json, struct, el_list] = encodeJSON(pr);
	[pr_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(pr_dec ~= pr, ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		'PanelPropMatrix.encodeJSON() or PanelPropMatrix.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) PanelPropMatrix.getPropFormat(prop), num2cell(PanelPropMatrix.getProps())) == Format.HANDLE) && all(cellfun(@(prop) PanelPropMatrix.getPropFormat(prop), num2cell(PanelPropMatrix.getProps())) == Format.NET)
		assert(isequal(pr_dec, pr), ...
			[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
			'PanelPropMatrix.encodeJSON() or PanelPropMatrix.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
	
	warning('on', [BRAPH2.STR ':PanelPropMatrix'])
end

%% Test 12: Remove Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropMatrix'])
	
	warning('off', [BRAPH2.STR ':PanelPropMatrix'])
	assert(length(findall(0, 'type', 'figure')) == 1)
	delete(findall(0, 'type', 'figure'))
	warning('on', [BRAPH2.STR ':PanelPropMatrix'])
	
	warning('on', [BRAPH2.STR ':PanelPropMatrix'])
end

%% Test 13: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropMatrix'])
	
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':PanelPropMatrix:' BRAPH2.FAIL_TEST], ...
		[' When testing PanelPropMatrix no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
	
	warning('on', [BRAPH2.STR ':PanelPropMatrix'])
end

%% Test 14: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropMatrix'])
	
	delete(findall(0, 'type', 'figure'))
	
	warning('on', [BRAPH2.STR ':PanelPropMatrix'])
end

