%TEST_EXPORTERGROUPSUBJECTFUN_TXT

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	ex = ExporterGroupSubjectFUN_TXT();
	 
	% get('ELCLASS')
	if isa(ExporterGroupSubjectFUN_TXT, 'ConcreteElement')
		assert(strcmp(ExporterGroupSubjectFUN_TXT().get('ELCLASS'), 'ExporterGroupSubjectFUN_TXT'), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ExporterGroupSubjectFUN_TXT().get(''ELCLASS'') should return ''ExporterGroupSubjectFUN_TXT''.')
	end
	 
	% getBuild()
	assert(ExporterGroupSubjectFUN_TXT.getBuild() == 1 && ExporterGroupSubjectFUN_TXT.getBuild() > 0, ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'ExporterGroupSubjectFUN_TXT.getBuild() should return the ExporterGroupSubjectFUN_TXT build number.')
	assert(ex.getBuild() == 1 && ex.getBuild() > 0 , ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'ex.getBuild() should return the ExporterGroupSubjectFUN_TXT build number.')
	assert(Element.getBuild(ex) == 1 && Element.getBuild(ex) > 0, ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(ex) should return the ExporterGroupSubjectFUN_TXT build number.')
	assert(Element.getBuild('ExporterGroupSubjectFUN_TXT') == 1 && Element.getBuild('ExporterGroupSubjectFUN_TXT') > 0, ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''ExporterGroupSubjectFUN_TXT'') should return the ExporterGroupSubjectFUN_TXT build number.')
	 
	% getClass()
	assert(strcmp(ExporterGroupSubjectFUN_TXT.getClass(), 'ExporterGroupSubjectFUN_TXT'), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'ExporterGroupSubjectFUN_TXT.getClass() should return ''ExporterGroupSubjectFUN_TXT''.')
	assert(strcmp(ex.getClass(), 'ExporterGroupSubjectFUN_TXT'), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'ex.getClass() should return ''ExporterGroupSubjectFUN_TXT''.')
	assert(strcmp(Element.getClass(ex), 'ExporterGroupSubjectFUN_TXT'), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(ex) should return ''ExporterGroupSubjectFUN_TXT''.')
	assert(strcmp(Element.getClass('ExporterGroupSubjectFUN_TXT'), 'ExporterGroupSubjectFUN_TXT'), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''ExporterGroupSubjectFUN_TXT'') should return ''ExporterGroupSubjectFUN_TXT''.')
	 
	% getSubclasses()
	assert(isequal(ExporterGroupSubjectFUN_TXT.getSubclasses(), subclasses('ExporterGroupSubjectFUN_TXT', [], [], true)), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'ExporterGroupSubjectFUN_TXT.getSubclasses() should return the same result as subclasses(''ExporterGroupSubjectFUN_TXT'', [], [], true).')
	assert(isequal(ex.getSubclasses(), subclasses('ExporterGroupSubjectFUN_TXT', [], [], true)), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''ExporterGroupSubjectFUN_TXT'', [], [], true).')
	assert(isequal(Element.getSubclasses(ex), subclasses('ExporterGroupSubjectFUN_TXT', [], [], true)), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(ex) should return the same result as subclasses(''ExporterGroupSubjectFUN_TXT'', [], [], true).')
	assert(isequal(Element.getSubclasses('ExporterGroupSubjectFUN_TXT'), subclasses('ExporterGroupSubjectFUN_TXT', [], [], true)), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''ExporterGroupSubjectFUN_TXT'') should return the same result as subclasses(''ExporterGroupSubjectFUN_TXT'', [], [], true).')
	 
	% getProps()
	assert(isempty(ExporterGroupSubjectFUN_TXT.getProps()) || isequal(ExporterGroupSubjectFUN_TXT.getProps(), 1:1:length(ExporterGroupSubjectFUN_TXT.getProps())), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'ExporterGroupSubjectFUN_TXT.getProps() should return a row vector [1:1:N].')
	assert(isempty(ExporterGroupSubjectFUN_TXT.getProps()) || isequal(ex.getProps(), 1:1:length(ExporterGroupSubjectFUN_TXT.getProps())), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'ex.getProps() should return a row vector [1:1:N].')
	assert(isempty(ExporterGroupSubjectFUN_TXT.getProps()) || isequal(Element.getProps(ex), 1:1:length(ExporterGroupSubjectFUN_TXT.getProps())), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(ex) should return a row vector [1:1:N].')
	assert(isempty(ExporterGroupSubjectFUN_TXT.getProps()) || isequal(Element.getProps('ExporterGroupSubjectFUN_TXT'), 1:1:length(ExporterGroupSubjectFUN_TXT.getProps())), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''ExporterGroupSubjectFUN_TXT'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) ExporterGroupSubjectFUN_TXT.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(ExporterGroupSubjectFUN_TXT.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ExporterGroupSubjectFUN_TXT.getProps())), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'ExporterGroupSubjectFUN_TXT.getProps(category) does not work.')
	tmp = cellfun(@(category) ex.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(ExporterGroupSubjectFUN_TXT.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ExporterGroupSubjectFUN_TXT.getProps())), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'ex.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(ex, category), categories, 'UniformOutput', false);
	assert(isempty(ExporterGroupSubjectFUN_TXT.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ExporterGroupSubjectFUN_TXT.getProps())), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(ex, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('ExporterGroupSubjectFUN_TXT', category), categories, 'UniformOutput', false);
	assert(isempty(ExporterGroupSubjectFUN_TXT.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ExporterGroupSubjectFUN_TXT.getProps())), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''ExporterGroupSubjectFUN_TXT'', category) does not work.')
	 
	% getPropNumber()
	assert(ExporterGroupSubjectFUN_TXT.getPropNumber() == length(ExporterGroupSubjectFUN_TXT.getProps()), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'ExporterGroupSubjectFUN_TXT.getPropNumber() should return the number of properties.')
	assert(ex.getPropNumber() == length(ExporterGroupSubjectFUN_TXT.getProps()), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'ex.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(ex) == length(ExporterGroupSubjectFUN_TXT.getProps()), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(ex) should return the number of properties.')
	assert(Element.getPropNumber('ExporterGroupSubjectFUN_TXT') == length(ExporterGroupSubjectFUN_TXT.getProps()), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''ExporterGroupSubjectFUN_TXT'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) ExporterGroupSubjectFUN_TXT.getPropNumber(category), categories)) == ExporterGroupSubjectFUN_TXT.getPropNumber(), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'ExporterGroupSubjectFUN_TXT.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) ex.getPropNumber(category), categories)) == ExporterGroupSubjectFUN_TXT.getPropNumber(), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'ex.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(ex, category), categories)) == ExporterGroupSubjectFUN_TXT.getPropNumber(), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(ex, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('ExporterGroupSubjectFUN_TXT', category), categories)) == ExporterGroupSubjectFUN_TXT.getPropNumber(), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''ExporterGroupSubjectFUN_TXT'', category) does not work.')
	 
	% existsProp(prop)
	assert(~ExporterGroupSubjectFUN_TXT.existsProp(NaN), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'ExporterGroupSubjectFUN_TXT.existsProp(prop) does not work.')
	assert(~ex.existsProp(NaN), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'ex.existsProp(prop) does not work.')
	assert(~Element.existsProp(ex, NaN), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(ex, prop) does not work.')
	assert(~Element.existsProp('ExporterGroupSubjectFUN_TXT', NaN), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''ExporterGroupSubjectFUN_TXT'', prop) does not work.')
	 
	assert_with_error('ExporterGroupSubjectFUN_TXT.existsProp(NaN)', [BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.WRONG_INPUT], ex)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.WRONG_INPUT], ex)
	assert_with_error('Element.existsProp(''ExporterGroupSubjectFUN_TXT'', NaN)', [BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:ExporterGroupSubjectFUN_TXT.getPropNumber()
		assert(ExporterGroupSubjectFUN_TXT.existsProp(prop), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ExporterGroupSubjectFUN_TXT.existsProp(prop) does not work.')
		assert(ex.existsProp(prop), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ex.existsProp(prop) does not work.')
		assert(Element.existsProp(ex, prop), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(ex, prop) does not work.')
		assert(Element.existsProp('ExporterGroupSubjectFUN_TXT', prop), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''ExporterGroupSubjectFUN_TXT'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~ExporterGroupSubjectFUN_TXT.existsTag(''), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'ExporterGroupSubjectFUN_TXT.existsTag(tag) does not work.')
	assert(~ex.existsTag(''), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'ex.existsTag(tag) does not work.')
	assert(~Element.existsTag(ex, ''), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(ex, tag) does not work.')
	assert(~Element.existsTag('ExporterGroupSubjectFUN_TXT', ''), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''ExporterGroupSubjectFUN_TXT'', tag) does not work.')
	 
	assert_with_error('ExporterGroupSubjectFUN_TXT.existsTag('''')', [BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.WRONG_INPUT], ex)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.WRONG_INPUT], ex)
	assert_with_error('Element.existsTag(''ExporterGroupSubjectFUN_TXT'', '''')', [BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:ExporterGroupSubjectFUN_TXT.getPropNumber()
		tag = ex.getPropTag(prop);
		assert(ExporterGroupSubjectFUN_TXT.existsTag(tag), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ExporterGroupSubjectFUN_TXT.existsTag(tag) does not work.')
		assert(ex.existsTag(tag), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ex.existsTag(tag) does not work.')
		assert(Element.existsTag(ex, tag), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(ex, tga) does not work.')
		assert(Element.existsTag('ExporterGroupSubjectFUN_TXT', tag), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''ExporterGroupSubjectFUN_TXT'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:ExporterGroupSubjectFUN_TXT.getPropNumber()
		assert(ExporterGroupSubjectFUN_TXT.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ExporterGroupSubjectFUN_TXT.getPropProp(prop) does not work.')
		assert(ex.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ex.getPropProp(prop) does not work.')
		assert(Element.getPropProp(ex, prop) == prop, ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(ex, prop) does not work.')
		assert(Element.getPropProp('ExporterGroupSubjectFUN_TXT', prop) == prop, ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''ExporterGroupSubjectFUN_TXT'', prop) does not work.')
	 
		tag = ex.getPropTag(prop);
		assert(ExporterGroupSubjectFUN_TXT.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ExporterGroupSubjectFUN_TXT.getPropProp(tag) does not work.')
		assert(ex.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ex.getPropProp(tag) does not work.')
		assert(Element.getPropProp(ex, tag) == prop, ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(ex, tag) does not work.')
		assert(Element.getPropProp('ExporterGroupSubjectFUN_TXT', prop) == prop, ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''ExporterGroupSubjectFUN_TXT'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:ExporterGroupSubjectFUN_TXT.getPropNumber()
		tag = ex.getPropTag(prop);
	 
		assert(strcmp(ExporterGroupSubjectFUN_TXT.getPropTag(prop), tag), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ExporterGroupSubjectFUN_TXT.getPropTag(prop) does not work.')
		assert(strcmp(ex.getPropTag(prop), tag), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ex.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(ex, prop), tag), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(ex, prop) does not work.')
		assert(strcmp(Element.getPropTag('ExporterGroupSubjectFUN_TXT', prop), tag), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''ExporterGroupSubjectFUN_TXT'', prop) does not work.')
	 
		assert(strcmp(ExporterGroupSubjectFUN_TXT.getPropTag(tag), tag), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ExporterGroupSubjectFUN_TXT.getPropTag(tag) does not work.')
		assert(strcmp(ex.getPropTag(tag), tag), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ex.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(ex, tag), tag), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(ex, tag) does not work.')
		assert(strcmp(Element.getPropTag('ExporterGroupSubjectFUN_TXT', prop), tag), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''ExporterGroupSubjectFUN_TXT'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:ExporterGroupSubjectFUN_TXT.getPropNumber()
		tag = ex.getPropTag(prop);
	 
		assert(Category.existsCategory(ExporterGroupSubjectFUN_TXT.getPropCategory(prop)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ExporterGroupSubjectFUN_TXT.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(ex.getPropCategory(prop)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ex.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(ex, prop)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(ex, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(ex, prop)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''ExporterGroupSubjectFUN_TXT'', prop) does not work.')
	 
		assert(Category.existsCategory(ExporterGroupSubjectFUN_TXT.getPropCategory(tag)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ExporterGroupSubjectFUN_TXT.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(ex.getPropCategory(tag)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ex.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(ex, tag)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(ex, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(ex, tag)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''ExporterGroupSubjectFUN_TXT'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:ExporterGroupSubjectFUN_TXT.getPropNumber()
		tag = ex.getPropTag(prop);
	 
		assert(Format.existsFormat(ExporterGroupSubjectFUN_TXT.getPropFormat(prop)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ExporterGroupSubjectFUN_TXT.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(ex.getPropFormat(prop)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ex.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(ex, prop)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(ex, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(ex, prop)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''ExporterGroupSubjectFUN_TXT'', prop) does not work.')
	 
		assert(Format.existsFormat(ExporterGroupSubjectFUN_TXT.getPropFormat(tag)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ExporterGroupSubjectFUN_TXT.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(ex.getPropFormat(tag)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ex.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(ex, tag)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(ex, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(ex, tag)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''ExporterGroupSubjectFUN_TXT'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:ExporterGroupSubjectFUN_TXT.getPropNumber()
		tag = ex.getPropTag(prop);
	 
		assert(ischar(ExporterGroupSubjectFUN_TXT.getPropDescription(prop)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ExporterGroupSubjectFUN_TXT.getPropDescription(prop) does not work.')
		assert(ischar(ex.getPropDescription(prop)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ex.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(ex, prop)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(ex, prop) does not work.')
		assert(ischar(Element.getPropDescription(ex, prop)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''ExporterGroupSubjectFUN_TXT'', prop) does not work.')
	 
		assert(ischar(ExporterGroupSubjectFUN_TXT.getPropDescription(tag)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ExporterGroupSubjectFUN_TXT.getPropDescription(tag) does not work.')
		assert(ischar(ex.getPropDescription(tag)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ex.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(ex, tag)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(ex, tag) does not work.')
		assert(ischar(Element.getPropDescription(ex, tag)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''ExporterGroupSubjectFUN_TXT'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:ExporterGroupSubjectFUN_TXT.getPropNumber()
		tag = ex.getPropTag(prop);
	 
		settings = ExporterGroupSubjectFUN_TXT.getPropSettings(prop);
		settings = ex.getPropSettings(prop);
		settings = Element.getPropSettings(ex, prop);
		settings = Element.getPropSettings('ExporterGroupSubjectFUN_TXT', prop);
	 
		settings = ExporterGroupSubjectFUN_TXT.getPropSettings(tag);
		settings = ex.getPropSettings(tag);
		settings = Element.getPropSettings(ex, tag);
		settings = Element.getPropSettings('ExporterGroupSubjectFUN_TXT', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:ExporterGroupSubjectFUN_TXT.getPropNumber()
		tag = ex.getPropTag(prop);
	 
		default = ExporterGroupSubjectFUN_TXT.getPropDefault(prop);
		default = ex.getPropDefault(prop);
		default = Element.getPropDefault(ex, prop);
		default = Element.getPropDefault('ExporterGroupSubjectFUN_TXT', prop);
	 
		default = ExporterGroupSubjectFUN_TXT.getPropDefault(tag);
		default = ex.getPropDefault(tag);
		default = Element.getPropDefault(ex, tag);
		default = Element.getPropDefault('ExporterGroupSubjectFUN_TXT', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:ExporterGroupSubjectFUN_TXT.getPropNumber()
		tag = ex.getPropTag(prop);
	 
		conditioned_default = ExporterGroupSubjectFUN_TXT.getPropDefaultConditioned(prop);
		conditioned_default = ex.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(ex, prop);
		conditioned_default = Element.getPropDefaultConditioned('ExporterGroupSubjectFUN_TXT', prop);
	 
		conditioned_default = ExporterGroupSubjectFUN_TXT.getPropDefaultConditioned(tag);
		conditioned_default = ex.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(ex, tag);
		conditioned_default = Element.getPropDefaultConditioned('ExporterGroupSubjectFUN_TXT', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:ExporterGroupSubjectFUN_TXT.getPropNumber()
		tag = ex.getPropTag(prop);
	 
		assert(~ExporterGroupSubjectFUN_TXT.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ExporterGroupSubjectFUN_TXT.checkProp(prop, value) does not work.')
		assert(~ex.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ex.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(ex, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(ex, prop, value) does not work.')
		assert(~Element.checkProp('ExporterGroupSubjectFUN_TXT', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ExporterGroupSubjectFUN_TXT'', prop, value) does not work.')
	 
		assert_with_error('ExporterGroupSubjectFUN_TXT.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.WRONG_INPUT], prop, ex)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.WRONG_INPUT], prop, ex)
		assert_with_error('Element.checkProp(''ExporterGroupSubjectFUN_TXT'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~ExporterGroupSubjectFUN_TXT.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ExporterGroupSubjectFUN_TXT.checkProp(tag, value) does not work.')
		assert(~ex.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ex.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(ex, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(ex, tag, value) does not work.')
		assert(~Element.checkProp('ExporterGroupSubjectFUN_TXT', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ExporterGroupSubjectFUN_TXT'', tag, value) does not work.')
	 
		assert_with_error('ExporterGroupSubjectFUN_TXT.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.WRONG_INPUT], tag, ex)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.WRONG_INPUT], tag, ex)
		assert_with_error('Element.checkProp(''ExporterGroupSubjectFUN_TXT'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(ExporterGroupSubjectFUN_TXT.checkProp(prop, Element.getPropDefaultConditioned(ExporterGroupSubjectFUN_TXT, prop)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ExporterGroupSubjectFUN_TXT.checkProp(prop, <conditioned default value>) does not work.')
		assert(ex.checkProp(prop, Element.getPropDefaultConditioned(ExporterGroupSubjectFUN_TXT, prop)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ex.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(ex, prop, Element.getPropDefaultConditioned(ExporterGroupSubjectFUN_TXT, prop)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(ex, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('ExporterGroupSubjectFUN_TXT', prop, Element.getPropDefaultConditioned(ExporterGroupSubjectFUN_TXT, prop)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ExporterGroupSubjectFUN_TXT'', prop, <conditioned default value>) does not work.')
	 
		assert(ExporterGroupSubjectFUN_TXT.checkProp(tag, Element.getPropDefaultConditioned(ExporterGroupSubjectFUN_TXT, prop)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ExporterGroupSubjectFUN_TXT.checkProp(tag, <conditioned default value>) does not work.')
		assert(ex.checkProp(tag, Element.getPropDefaultConditioned(ExporterGroupSubjectFUN_TXT, prop)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ex.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(ex, tag, Element.getPropDefaultConditioned(ExporterGroupSubjectFUN_TXT, prop)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(ex, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('ExporterGroupSubjectFUN_TXT', tag, Element.getPropDefaultConditioned(ExporterGroupSubjectFUN_TXT, prop)), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ExporterGroupSubjectFUN_TXT'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	ex = ExporterGroupSubjectFUN_TXT( ...
		ExporterGroupSubjectFUN_TXT.ELCLASS, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.NAME, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.DESCRIPTION, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.TEMPLATE, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.TEMPLATE), ...
		ExporterGroupSubjectFUN_TXT.ID, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.ID), ...
		ExporterGroupSubjectFUN_TXT.LABEL, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.LABEL), ...
		ExporterGroupSubjectFUN_TXT.NOTES, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.NOTES), ...
		ExporterGroupSubjectFUN_TXT.TOSTRING, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.WAITBAR, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.WAITBAR), ...
		ExporterGroupSubjectFUN_TXT.GR, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.GR), ...
		ExporterGroupSubjectFUN_TXT.DIRECTORY, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.DIRECTORY), ...
		ExporterGroupSubjectFUN_TXT.PUT_DIR, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.SAVE, ExporterGroupSubjectFUN_TXT.getNoValue() ...
		);
	 
	for prop = 1:1:ExporterGroupSubjectFUN_TXT.getPropNumber()
	 
		% excluded props
		if any(prop == [ExporterGroupSubjectFUN_TXT.PUT_DIR])
			continue
		end
	 
		TAG = upper(ExporterGroupSubjectFUN_TXT.getPropTag(prop));
		switch ExporterGroupSubjectFUN_TXT.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					ex.getr(prop) == ExporterGroupSubjectFUN_TXT.getNoValue(), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['Being a ' ExporterGroupSubjectFUN_TXT.getCategoryName(ExporterGroupSubjectFUN_TXT.getPropCategory(prop)) ', ExporterGroupSubjectFUN_TXT.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ExporterGroupSubjectFUN_TXT.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					ex.getr(TAG) == ExporterGroupSubjectFUN_TXT.getNoValue(), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['Being a ' ExporterGroupSubjectFUN_TXT.getCategoryName(ExporterGroupSubjectFUN_TXT.getPropCategory(prop)) ', ExporterGroupSubjectFUN_TXT.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ExporterGroupSubjectFUN_TXT.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(ex.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(ex.getPropSettings(prop))
					assert( ...
						ex.checkFormat(ex.getPropFormat(prop), ex.get(prop)), ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						['ExporterGroupSubjectFUN_TXT.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						ex.checkFormat(ex.getPropFormat(prop), ex.get(prop), ex.getPropSettings(prop)), ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						['ExporterGroupSubjectFUN_TXT.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					ex.getr(prop) == ExporterGroupSubjectFUN_TXT.getNoValue(), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['Being a ' ExporterGroupSubjectFUN_TXT.getCategoryName(ExporterGroupSubjectFUN_TXT.getPropCategory(prop)) ', ExporterGroupSubjectFUN_TXT.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ExporterGroupSubjectFUN_TXT.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					ex.getr(TAG) == ExporterGroupSubjectFUN_TXT.getNoValue(), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['Being a ' ExporterGroupSubjectFUN_TXT.getCategoryName(ExporterGroupSubjectFUN_TXT.getPropCategory(prop)) ', ExporterGroupSubjectFUN_TXT.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ExporterGroupSubjectFUN_TXT.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':ExporterGroupSubjectFUN_TXT']);
				assert( ...
					~isa(ex.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(ex.getPropSettings(prop))
					assert( ...
						ex.checkFormat(ex.getPropFormat(prop), ex.get(prop)), ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						['ExporterGroupSubjectFUN_TXT.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						ex.checkFormat(ex.getPropFormat(prop), ex.get(prop), ex.getPropSettings(prop)), ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						['ExporterGroupSubjectFUN_TXT.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(ex.getr(prop), ExporterGroupSubjectFUN_TXT.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by ExporterGroupSubjectFUN_TXT.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in ExporterGroupSubjectFUN_TXT.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(ex.getr(TAG), ExporterGroupSubjectFUN_TXT.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.getr(' TAG ') must be inizialized to its default value ' ...
					'given by ExporterGroupSubjectFUN_TXT.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in ExporterGroupSubjectFUN_TXT.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	ex = ExporterGroupSubjectFUN_TXT( ...
		ExporterGroupSubjectFUN_TXT.ELCLASS, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.NAME, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.DESCRIPTION, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.TEMPLATE, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.TEMPLATE), ...
		ExporterGroupSubjectFUN_TXT.ID, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.ID), ...
		ExporterGroupSubjectFUN_TXT.LABEL, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.LABEL), ...
		ExporterGroupSubjectFUN_TXT.NOTES, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.NOTES), ...
		ExporterGroupSubjectFUN_TXT.TOSTRING, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.WAITBAR, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.WAITBAR), ...
		ExporterGroupSubjectFUN_TXT.GR, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.GR), ...
		ExporterGroupSubjectFUN_TXT.DIRECTORY, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.DIRECTORY), ...
		ExporterGroupSubjectFUN_TXT.PUT_DIR, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.SAVE, ExporterGroupSubjectFUN_TXT.getNoValue() ...
		);
	 
	for prop = 1:1:ExporterGroupSubjectFUN_TXT.getPropNumber()
	 
		% excluded props
		if any(prop == [ExporterGroupSubjectFUN_TXT.PUT_DIR])
			continue
		end
	 
		TAG = upper(ExporterGroupSubjectFUN_TXT.getPropTag(prop));
		switch ExporterGroupSubjectFUN_TXT.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(ex.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(ex.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(ex.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(ex.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					ex.checkFormat(ex.getPropFormat(prop), ex.getr(prop),ex.getPropSettings(prop)), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':ExporterGroupSubjectFUN_TXT']);
				assert( ...
					~isa(ex.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(ex.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':ExporterGroupSubjectFUN_TXT']);
	% 			assert( ...
	% 				~isa(ex.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
	% 				['ExporterGroupSubjectFUN_TXT.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(ex.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
	% 				['ExporterGroupSubjectFUN_TXT.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				ex.checkFormat(ex.getPropFormat(prop), ex.getr(prop),ex.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
	% 				['ExporterGroupSubjectFUN_TXT.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':ExporterGroupSubjectFUN_TXT']);
				assert( ...
					~isa(ex.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(ex.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(ex.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(ex.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					ex.checkFormat(ex.getPropFormat(prop), ex.getr(prop),ex.getPropSettings(prop)), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if ex.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:ExporterGroupSubjectFUN_TXT');
					delete(ancestor(ex.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(ExporterGroupSubjectFUN_TXT.getProps(Category.RESULT))
		for prop = 1:1:ExporterGroupSubjectFUN_TXT.getPropNumber()
	 
			% excluded props
			if any(prop == [ExporterGroupSubjectFUN_TXT.PUT_DIR])
				continue
			end
	 
			switch ExporterGroupSubjectFUN_TXT.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						ex.isLocked(prop), ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						['ExporterGroupSubjectFUN_TXT.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~ex.isLocked(prop), ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						['ExporterGroupSubjectFUN_TXT.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	ex = ExporterGroupSubjectFUN_TXT();
	 
	for prop = 1:1:ExporterGroupSubjectFUN_TXT.getPropNumber()
		TAG = upper(ExporterGroupSubjectFUN_TXT.getPropTag(prop));
		assert( ...
			~ex.isLocked(prop), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			['ExporterGroupSubjectFUN_TXT.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~ex.isLocked(TAG), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			['ExporterGroupSubjectFUN_TXT.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	ex.lock()
	 
	for prop = 1:1:ExporterGroupSubjectFUN_TXT.getPropNumber()
		switch ExporterGroupSubjectFUN_TXT.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					ex.isLocked(prop), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~ex.isLocked(prop), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	ex = ExporterGroupSubjectFUN_TXT();
	 
	warning_backup = warning('off', 'BRAPH2:ExporterGroupSubjectFUN_TXT');
	for prop = 1:1:ExporterGroupSubjectFUN_TXT.getPropNumber()
		ex.lock(prop)
		switch ExporterGroupSubjectFUN_TXT.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					ex.isLocked(prop), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~ex.isLocked(prop), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	ex = ExporterGroupSubjectFUN_TXT();
	 
	for prop = 1:1:ExporterGroupSubjectFUN_TXT.getPropNumber()
		TAG = upper(ExporterGroupSubjectFUN_TXT.getPropTag(prop));
		assert( ...
			ex.isChecked(prop), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			['ExporterGroupSubjectFUN_TXT.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			ex.isChecked(TAG), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			['ExporterGroupSubjectFUN_TXT.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	ex.unchecked()
	 
	for prop = 1:1:ExporterGroupSubjectFUN_TXT.getPropNumber()
		assert( ...
			~ex.isChecked(prop), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			['ExporterGroupSubjectFUN_TXT.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	ex.checked()
	 
	for prop = 1:1:ExporterGroupSubjectFUN_TXT.getPropNumber()
		assert( ...
			ex.isChecked(prop), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			['ExporterGroupSubjectFUN_TXT.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic ExporterGroupSubjectFUN_TXT
	ex_0 = ExporterGroupSubjectFUN_TXT( ...
		ExporterGroupSubjectFUN_TXT.ELCLASS, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.NAME, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.DESCRIPTION, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.TEMPLATE, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.TEMPLATE), ...
		ExporterGroupSubjectFUN_TXT.ID, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.ID), ...
		ExporterGroupSubjectFUN_TXT.LABEL, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.LABEL), ...
		ExporterGroupSubjectFUN_TXT.NOTES, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.NOTES), ...
		ExporterGroupSubjectFUN_TXT.TOSTRING, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.WAITBAR, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.WAITBAR), ...
		ExporterGroupSubjectFUN_TXT.GR, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.GR), ...
		ExporterGroupSubjectFUN_TXT.DIRECTORY, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.DIRECTORY), ...
		ExporterGroupSubjectFUN_TXT.PUT_DIR, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.SAVE, ExporterGroupSubjectFUN_TXT.getNoValue() ...
		);
	 
	% ExporterGroupSubjectFUN_TXT with 1st callbacks
	ex_1 = ExporterGroupSubjectFUN_TXT( ...
		ExporterGroupSubjectFUN_TXT.ELCLASS, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.NAME, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.DESCRIPTION, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.TEMPLATE, ex_0.getCallback(4), ..., ...
		ExporterGroupSubjectFUN_TXT.ID, ex_0.getCallback(5), ..., ...
		ExporterGroupSubjectFUN_TXT.LABEL, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.LABEL), ...
		ExporterGroupSubjectFUN_TXT.NOTES, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.NOTES), ...
		ExporterGroupSubjectFUN_TXT.TOSTRING, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.WAITBAR, ex_0.getCallback(9), ..., ...
		ExporterGroupSubjectFUN_TXT.GR, ex_0.getCallback(10), ..., ...
		ExporterGroupSubjectFUN_TXT.DIRECTORY, ex_0.getCallback(11), ..., ...
		ExporterGroupSubjectFUN_TXT.PUT_DIR, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.SAVE, ExporterGroupSubjectFUN_TXT.getNoValue() ...
		);
	 
	prop_number = ExporterGroupSubjectFUN_TXT.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ExporterGroupSubjectFUN_TXT.getPropTag(prop));
		switch ExporterGroupSubjectFUN_TXT.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(ex_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(ex_1.get(prop), ex_0.get(prop)) && ~isa(ex_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(ex_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% ExporterGroupSubjectFUN_TXT with 2nd callbacks
	ex_2 = ExporterGroupSubjectFUN_TXT( ...
		ExporterGroupSubjectFUN_TXT.ELCLASS, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.NAME, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.DESCRIPTION, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.TEMPLATE, ex_1.getCallback(4), ..., ...
		ExporterGroupSubjectFUN_TXT.ID, ex_1.getCallback(5), ..., ...
		ExporterGroupSubjectFUN_TXT.LABEL, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.LABEL), ...
		ExporterGroupSubjectFUN_TXT.NOTES, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.NOTES), ...
		ExporterGroupSubjectFUN_TXT.TOSTRING, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.WAITBAR, ex_1.getCallback(9), ..., ...
		ExporterGroupSubjectFUN_TXT.GR, ex_1.getCallback(10), ..., ...
		ExporterGroupSubjectFUN_TXT.DIRECTORY, ex_1.getCallback(11), ..., ...
		ExporterGroupSubjectFUN_TXT.PUT_DIR, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.SAVE, ExporterGroupSubjectFUN_TXT.getNoValue() ...
		);
	 
	prop_number = ExporterGroupSubjectFUN_TXT.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ExporterGroupSubjectFUN_TXT.getPropTag(prop));
		switch ExporterGroupSubjectFUN_TXT.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(ex_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(ex_2.get(prop), ex_0.get(prop)) && ~isa(ex_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(ex_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% ExporterGroupSubjectFUN_TXT with 3rd callbacks
	ex_3 = ExporterGroupSubjectFUN_TXT( ...
		ExporterGroupSubjectFUN_TXT.ELCLASS, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.NAME, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.DESCRIPTION, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.TEMPLATE, ex_2.getCallback(4), ..., ...
		ExporterGroupSubjectFUN_TXT.ID, ex_2.getCallback(5), ..., ...
		ExporterGroupSubjectFUN_TXT.LABEL, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.LABEL), ...
		ExporterGroupSubjectFUN_TXT.NOTES, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.NOTES), ...
		ExporterGroupSubjectFUN_TXT.TOSTRING, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.WAITBAR, ex_2.getCallback(9), ..., ...
		ExporterGroupSubjectFUN_TXT.GR, ex_2.getCallback(10), ..., ...
		ExporterGroupSubjectFUN_TXT.DIRECTORY, ex_2.getCallback(11), ..., ...
		ExporterGroupSubjectFUN_TXT.PUT_DIR, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.SAVE, ExporterGroupSubjectFUN_TXT.getNoValue() ...
		);
	 
	prop_number = ExporterGroupSubjectFUN_TXT.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ExporterGroupSubjectFUN_TXT.getPropTag(prop));
		switch ExporterGroupSubjectFUN_TXT.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(ex_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(ex_3.get(prop), ex_0.get(prop)) && ~isa(ex_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(ex_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	ex = ExporterGroupSubjectFUN_TXT();
	 
	ex_copy = ex.copy();
	 
	assert(ex_copy ~= ex, ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'ExporterGroupSubjectFUN_TXT.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(ex_copy, ex), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'ExporterGroupSubjectFUN_TXT.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:ExporterGroupSubjectFUN_TXT.getPropNumber()
		value = ex.getr(prop);
		value_copy = ex_copy.getr(prop);
		switch ExporterGroupSubjectFUN_TXT.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					'ExporterGroupSubjectFUN_TXT.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						'ExporterGroupSubjectFUN_TXT.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						'ExporterGroupSubjectFUN_TXT.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						'ExporterGroupSubjectFUN_TXT.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
							'ExporterGroupSubjectFUN_TXT.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
							'ExporterGroupSubjectFUN_TXT.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						'ExporterGroupSubjectFUN_TXT.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					ex_copy.isLocked(prop) == ex.isLocked(prop), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					'ExporterGroupSubjectFUN_TXT.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					ex_copy.isChecked(prop) == ex.isChecked(prop), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					'ExporterGroupSubjectFUN_TXT.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					ex_copy.getPropSeed(prop) == ex.getPropSeed(prop), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					'ExporterGroupSubjectFUN_TXT.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	ex = ExporterGroupSubjectFUN_TXT( ...
		ExporterGroupSubjectFUN_TXT.ELCLASS, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.NAME, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.DESCRIPTION, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.TEMPLATE, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.TEMPLATE), ...
		ExporterGroupSubjectFUN_TXT.ID, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.ID), ...
		ExporterGroupSubjectFUN_TXT.LABEL, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.LABEL), ...
		ExporterGroupSubjectFUN_TXT.NOTES, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.NOTES), ...
		ExporterGroupSubjectFUN_TXT.TOSTRING, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.WAITBAR, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.WAITBAR), ...
		ExporterGroupSubjectFUN_TXT.GR, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.GR), ...
		ExporterGroupSubjectFUN_TXT.DIRECTORY, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.DIRECTORY), ...
		ExporterGroupSubjectFUN_TXT.PUT_DIR, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.SAVE, ExporterGroupSubjectFUN_TXT.getNoValue() ...
		);
	 
	for prop = 1:1:ExporterGroupSubjectFUN_TXT.getPropNumber()
		if ExporterGroupSubjectFUN_TXT.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':ExporterGroupSubjectFUN_TXT']);
			% ex.memorize(prop);
			% warning(warning_backup)
		elseif ExporterGroupSubjectFUN_TXT.getPropCategory(prop) == Category.EVANESCENT && ex.getPropFormat(prop) == Format.HANDLE
			ex.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:ExporterGroupSubjectFUN_TXT');
			delete(ancestor(ex.get(prop), 'figure'))
			warning(warning_backup)
		else
			ex.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	ex_copy = ex.copy();
	 
	for prop = 1:1:ExporterGroupSubjectFUN_TXT.getPropNumber()
		value = ex.getr(prop);
		value_copy = ex_copy.getr(prop);
		switch ExporterGroupSubjectFUN_TXT.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					'ExporterGroupSubjectFUN_TXT.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						'ExporterGroupSubjectFUN_TXT.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						'ExporterGroupSubjectFUN_TXT.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						'ExporterGroupSubjectFUN_TXT.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
							'ExporterGroupSubjectFUN_TXT.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
							'ExporterGroupSubjectFUN_TXT.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						'ExporterGroupSubjectFUN_TXT.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						ex_copy.isLocked(prop) == ex.isLocked(prop), ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						'ExporterGroupSubjectFUN_TXT.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						ex_copy.isChecked(prop) == ex.isChecked(prop), ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						'ExporterGroupSubjectFUN_TXT.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						ex_copy.getPropSeed(prop) == ex.getPropSeed(prop), ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						'ExporterGroupSubjectFUN_TXT.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	ex_0 = ExporterGroupSubjectFUN_TXT( ...
		ExporterGroupSubjectFUN_TXT.ELCLASS, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.NAME, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.DESCRIPTION, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.TEMPLATE, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.TEMPLATE), ...
		ExporterGroupSubjectFUN_TXT.ID, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.ID), ...
		ExporterGroupSubjectFUN_TXT.LABEL, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.LABEL), ...
		ExporterGroupSubjectFUN_TXT.NOTES, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.NOTES), ...
		ExporterGroupSubjectFUN_TXT.TOSTRING, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.WAITBAR, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.WAITBAR), ...
		ExporterGroupSubjectFUN_TXT.GR, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.GR), ...
		ExporterGroupSubjectFUN_TXT.DIRECTORY, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.DIRECTORY), ...
		ExporterGroupSubjectFUN_TXT.PUT_DIR, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.SAVE, ExporterGroupSubjectFUN_TXT.getNoValue() ...
		);
	 
	ex = ExporterGroupSubjectFUN_TXT( ...
		ExporterGroupSubjectFUN_TXT.ELCLASS, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.NAME, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.DESCRIPTION, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.TEMPLATE, ex_0.getCallback(4), ..., ...
		ExporterGroupSubjectFUN_TXT.ID, ex_0.getCallback(5), ..., ...
		ExporterGroupSubjectFUN_TXT.LABEL, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.LABEL), ...
		ExporterGroupSubjectFUN_TXT.NOTES, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.NOTES), ...
		ExporterGroupSubjectFUN_TXT.TOSTRING, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.WAITBAR, ex_0.getCallback(9), ..., ...
		ExporterGroupSubjectFUN_TXT.GR, ex_0.getCallback(10), ..., ...
		ExporterGroupSubjectFUN_TXT.DIRECTORY, ex_0.getCallback(11), ..., ...
		ExporterGroupSubjectFUN_TXT.PUT_DIR, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.SAVE, ExporterGroupSubjectFUN_TXT.getNoValue() ...
		);
	 
	ex_copy = ex.copy();
	ex_0_copy = ex_copy.getr('ID').get('EL');
	 
	for prop = 1:1:ExporterGroupSubjectFUN_TXT.getPropNumber()
		value = ex.getr(prop);
		value_copy = ex_copy.getr(prop);
		switch ExporterGroupSubjectFUN_TXT.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					'ExporterGroupSubjectFUN_TXT.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						'ExporterGroupSubjectFUN_TXT.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						'ExporterGroupSubjectFUN_TXT.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						'ExporterGroupSubjectFUN_TXT.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
							'ExporterGroupSubjectFUN_TXT.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
							'ExporterGroupSubjectFUN_TXT.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						'ExporterGroupSubjectFUN_TXT.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == ex_0.getCallback(prop), ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						'ExporterGroupSubjectFUN_TXT.copy() does not work. The callback should be obtained from ExporterGroupSubjectFUN_TXT.getCallback().' ...
						)
					assert( ...
						value_copy == ex_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						'ExporterGroupSubjectFUN_TXT.copy() does not work. The callback should be obtained from ExporterGroupSubjectFUN_TXT.getCallback().' ...
						)
				end
	 
					assert( ...
						ex_copy.isLocked(prop) == ex.isLocked(prop), ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						'ExporterGroupSubjectFUN_TXT.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						ex_copy.isChecked(prop) == ex.isChecked(prop), ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						'ExporterGroupSubjectFUN_TXT.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						ex_copy.getPropSeed(prop) == ex.getPropSeed(prop), ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						'ExporterGroupSubjectFUN_TXT.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	ex_template = ExporterGroupSubjectFUN_TXT();
	ex = ExporterGroupSubjectFUN_TXT('TEMPLATE', ex_template);
	 
	for prop = 1:1:ExporterGroupSubjectFUN_TXT.getPropNumber()
	 
		% excluded props
		if any(prop == [ExporterGroupSubjectFUN_TXT.PUT_DIR])
			continue
		end
	 
		TAG = upper(ExporterGroupSubjectFUN_TXT.getPropTag(prop));
		switch ExporterGroupSubjectFUN_TXT.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == ExporterGroupSubjectFUN_TXT.TEMPLATE
					assert( ...
						isa(ex.getr(prop), 'ExporterGroupSubjectFUN_TXT'), ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						'ExporterGroupSubjectFUN_TXT TEMPLATE does not work. ExporterGroupSubjectFUN_TXT.getr(''TEMPLATE'') should be a ExporterGroupSubjectFUN_TXT element.' ...
						)
					assert( ...
						isa(ex_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						'ExporterGroupSubjectFUN_TXT TEMPLATE does not work. ExporterGroupSubjectFUN_TXT_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(ex.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						['ExporterGroupSubjectFUN_TXT TEMPLATE does not work. ExporterGroupSubjectFUN_TXT.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						ex.getr(prop).get('EL') == ex_template && ex.getr(prop).get('PROP') == prop && strcmp(ex.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						['ExporterGroupSubjectFUN_TXT TEMPLATE does not work. ExporterGroupSubjectFUN_TXT.getr(' TAG ') should be a Callback to ex_template.' TAG '.'] ...
						)
					assert( ...
						isa(ex_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
						['ExporterGroupSubjectFUN_TXT TEMPLATE does not work. ExporterGroupSubjectFUN_TXT_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(ex.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT TEMPLATE does not work. ExporterGroupSubjectFUN_TXT.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(ex_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
					['ExporterGroupSubjectFUN_TXT TEMPLATE does not work. ExporterGroupSubjectFUN_TXT_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	ex = ExporterGroupSubjectFUN_TXT( ...
		ExporterGroupSubjectFUN_TXT.ELCLASS, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.NAME, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.DESCRIPTION, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.TEMPLATE, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.TEMPLATE), ...
		ExporterGroupSubjectFUN_TXT.ID, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.ID), ...
		ExporterGroupSubjectFUN_TXT.LABEL, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.LABEL), ...
		ExporterGroupSubjectFUN_TXT.NOTES, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.NOTES), ...
		ExporterGroupSubjectFUN_TXT.TOSTRING, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.WAITBAR, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.WAITBAR), ...
		ExporterGroupSubjectFUN_TXT.GR, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.GR), ...
		ExporterGroupSubjectFUN_TXT.DIRECTORY, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.DIRECTORY), ...
		ExporterGroupSubjectFUN_TXT.PUT_DIR, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.SAVE, ExporterGroupSubjectFUN_TXT.getNoValue() ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'exportergroupsubjectfun_txt_to_be_erased.b2'];
	 
	Element.save(ex, filename)
	 
	ex_loaded = Element.load(filename);
	 
	assert( ...
		isequal(ex.copy(), ex_loaded), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'ExporterGroupSubjectFUN_TXT.save(ex) and/or ExporterGroupSubjectFUN_TXT.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	ex = ExporterGroupSubjectFUN_TXT( ...
		ExporterGroupSubjectFUN_TXT.ELCLASS, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.NAME, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.DESCRIPTION, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.TEMPLATE, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.TEMPLATE), ...
		ExporterGroupSubjectFUN_TXT.ID, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.ID), ...
		ExporterGroupSubjectFUN_TXT.LABEL, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.LABEL), ...
		ExporterGroupSubjectFUN_TXT.NOTES, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.NOTES), ...
		ExporterGroupSubjectFUN_TXT.TOSTRING, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.WAITBAR, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.WAITBAR), ...
		ExporterGroupSubjectFUN_TXT.GR, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.GR), ...
		ExporterGroupSubjectFUN_TXT.DIRECTORY, ExporterGroupSubjectFUN_TXT.getPropDefault(ExporterGroupSubjectFUN_TXT.DIRECTORY), ...
		ExporterGroupSubjectFUN_TXT.PUT_DIR, ExporterGroupSubjectFUN_TXT.getNoValue(), ...
		ExporterGroupSubjectFUN_TXT.SAVE, ExporterGroupSubjectFUN_TXT.getNoValue() ...
		);
	 
	[json, struct, el_list] = encodeJSON(ex);
	[ex_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(ex_dec ~= ex, ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		'ExporterGroupSubjectFUN_TXT.encodeJSON() or ExporterGroupSubjectFUN_TXT.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) ExporterGroupSubjectFUN_TXT.getPropFormat(prop), num2cell(ExporterGroupSubjectFUN_TXT.getProps())) == Format.HANDLE) && all(cellfun(@(prop) ExporterGroupSubjectFUN_TXT.getPropFormat(prop), num2cell(ExporterGroupSubjectFUN_TXT.getProps())) == Format.NET)
		assert(isequal(ex_dec, ex), ...
			[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
			'ExporterGroupSubjectFUN_TXT.encodeJSON() or ExporterGroupSubjectFUN_TXT.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: Delete directory TBE
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	warning('off', 'MATLAB:DELETE:FileNotFound')
	dir_to_be_erased = ExporterGroupSubjectFUN_TXT.getPropDefault('DIRECTORY');
	if isfolder(dir_to_be_erased)
	    rmdir(dir_to_be_erased, 's')
	end
	warning('on', 'MATLAB:DELETE:FileNotFound')
end

%% Test 13: Export and import
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	br1 = BrainRegion( ...
	    'ID', 'ISF', ...
	    'LABEL', 'superiorfrontal', ...
	    'NOTES', 'notes1', ...
	    'X', -12.6, ...
	    'Y', 22.9, ...
	    'Z', 42.4 ...
	    );
	br2 = BrainRegion( ...
	    'ID', 'lFP', ...
	    'LABEL', 'frontalpole', ...
	    'NOTES', 'notes2', ...
	    'X', -8.6, ...
	    'Y', 61.7, ...
	    'Z', -8.7 ...
	    );
	br3 = BrainRegion( ...
	    'ID', 'lRMF', ...
	    'LABEL', 'rostralmiddlefrontal', ...
	    'NOTES', 'notes3', ...
	    'X', -31.3, ...
	    'Y', 41.2, ...
	    'Z', 16.5 ...
	    );
	br4 = BrainRegion( ...
	    'ID', 'lCMF', ...
	    'LABEL', 'caudalmiddlefrontal', ...
	    'NOTES', 'notes4', ...
	    'X', -34.6, ...
	    'Y', 10.2, ...
	    'Z', 42.8 ...
	    );
	br5 = BrainRegion( ...
	    'ID', 'lPOB', ...
	    'LABEL', 'parsorbitalis', ...
	    'NOTES', 'notes5', ...
	    'X', -41, ...
	    'Y', 38.8, ...
	    'Z', -11.1 ...
	    );
	
	ba = BrainAtlas( ...
	    'ID', 'TestToSaveCoolID', ...
	    'LABEL', 'Brain Atlas', ...
	    'NOTES', 'Brain atlas notes', ...
	    'BR_DICT', IndexedDictionary('IT_CLASS', 'BrainRegion', 'IT_LIST', {br1, br2, br3, br4, br5}) ...
	    );
	
	sub1 = SubjectFUN( ...
	    'ID', 'SUB FUN 1', ...
	    'LABEL', 'Subejct FUN 1', ...
	    'NOTES', 'Notes on subject FUN 1', ...
	    'BA', ba, ...
	    'FUN', rand(10, ba.get('BR_DICT').get('LENGTH')) ...
	    );
	sub1.memorize('VOI_DICT').get('ADD', VOINumeric('ID', 'Age', 'V', 75))
	sub1.memorize('VOI_DICT').get('ADD', VOICategoric('ID', 'Sex', 'CATEGORIES', {'Female', 'Male'}, 'V', find(strcmp('Female', {'Female', 'Male'}))))
	
	sub2 = SubjectFUN( ...
	    'ID', 'SUB FUN 2', ...
	    'LABEL', 'Subejct FUN 2', ...
	    'NOTES', 'Notes on subject FUN 2', ...
	    'BA', ba, ...
	    'FUN', rand(10, ba.get('BR_DICT').get('LENGTH')) ...
	    );
	sub2.memorize('VOI_DICT').get('ADD', VOINumeric('ID', 'Age', 'V', 70))
	sub2.memorize('VOI_DICT').get('ADD', VOICategoric('ID', 'Sex', 'CATEGORIES', {'Female', 'Male'}, 'V', find(strcmp('Male', {'Female', 'Male'}))))
	
	sub3 = SubjectFUN( ...
	    'ID', 'SUB FUN 3', ...
	    'LABEL', 'Subejct FUN 3', ...
	    'NOTES', 'Notes on subject FUN 3', ...
	    'BA', ba, ...
	    'FUN', rand(10, ba.get('BR_DICT').get('LENGTH')) ...
	    );
	sub3.memorize('VOI_DICT').get('ADD', VOINumeric('ID', 'Age', 'V', 50))
	sub3.memorize('VOI_DICT').get('ADD', VOICategoric('ID', 'Sex', 'CATEGORIES', {'Female', 'Male'}, 'V', find(strcmp('Female', {'Female', 'Male'}))))
	
	gr = Group( ...
	    'ID', 'GR FUN', ...
	    'LABEL', 'Group label', ...
	    'NOTES', 'Group notes', ...
	    'SUB_CLASS', 'SubjectFUN', ...
	    'SUB_DICT', IndexedDictionary('IT_CLASS', 'SubjectFUN', 'IT_LIST', {sub1, sub2, sub3}) ...
	    );
	
	directory = [fileparts(which('test_braph2')) filesep 'trial_group_subjects_FUN_to_be_erased'];
	if ~exist(directory, 'dir')
	    mkdir(directory)
	end
	
	ex = ExporterGroupSubjectFUN_TXT( ...
	    'DIRECTORY', directory, ...
	    'GR', gr ...
	    );
	ex.get('SAVE');
	
	% import with same brain atlas
	im1 = ImporterGroupSubjectFUN_TXT( ...
	    'DIRECTORY', [directory filesep() gr.get(Group.ID)], ...
	    'BA', ba ...
	    );
	gr_loaded1 = im1.get('GR');
	
	assert(gr.get('SUB_DICT').get('LENGTH') == gr_loaded1.get('SUB_DICT').get('LENGTH'), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
	    'Problems saving or loading a group.')
	for i = 1:1:max(gr.get('SUB_DICT').get('LENGTH'), gr_loaded1.get('SUB_DICT').get('LENGTH'))
	    sub = gr.get('SUB_DICT').get('IT', i);
	    sub_loaded = gr_loaded1.get('SUB_DICT').get('IT', i);    
	    assert( ...
	        isequal(sub.get('ID'), sub_loaded.get('ID')) & ...
	        isequal(sub.get('BA'), sub_loaded.get('BA')) & ...
	        isequal(sub.get('VOI_DICT').get('IT', 'Age').get('V'), sub_loaded.get('VOI_DICT').get('IT', 'Age').get('V')) & ... 
	        isequal(sub.get('VOI_DICT').get('IT', 'Sex').get('V'), sub_loaded.get('VOI_DICT').get('IT', 'Sex').get('V')) & ...        
	        isequal(round(sub.get('FUN'), 10), round(sub_loaded.get('FUN'), 10)), ...
	        [BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
	        'Problems saving or loading a group.')    
	end
	
	% import with new brain atlas
	im2 = ImporterGroupSubjectFUN_TXT( ...
	    'DIRECTORY', [directory filesep() gr.get(Group.ID)] ...
	    );
	gr_loaded2 = im2.get('GR');
	
	assert(gr.get('SUB_DICT').get('LENGTH') == gr_loaded2.get('SUB_DICT').get('LENGTH'), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
	    'Problems saving or loading a group.')
	for i = 1:1:max(gr.get('SUB_DICT').get('LENGTH'), gr_loaded2.get('SUB_DICT').get('LENGTH'))
	    sub = gr.get('SUB_DICT').get('IT', i);
	    sub_loaded = gr_loaded2.get('SUB_DICT').get('IT', i);    
	    assert( ...
	        isequal(sub.get('ID'), sub_loaded.get('ID')) & ...
	        ~isequal(sub.get('BA').get('ID'), sub_loaded.get('BA').get('ID')) & ...
	        isequal(round(sub.get('FUN'), 10), round(sub_loaded.get('FUN'), 10)), ...
	        isequal(sub.get('VOI_DICT').get('IT', 'Age').get('V'), sub_loaded.get('VOI_DICT').get('IT', 'Age').get('V')) & ...         
	        isequal(round(sub.get('FUN'), 10), round(sub_loaded.get('FUN'), 10)), ...
	        [BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
	        'Problems saving or loading a group.')    
	end
	
	rmdir(directory, 's')
end

%% Test 14: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':ExporterGroupSubjectFUN_TXT:' BRAPH2.FAIL_TEST], ...
		[' When testing ExporterGroupSubjectFUN_TXT no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 15: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

