clear all

% create figure, panel, and slider
f = figure('Menubar', 'figure', ...
    'Resize', 'on', ...
    'Units', 'normalized', ...
    'Position', [.2 .2 .5 .6]);
p = uipanel('Parent', f, ...
    'Units', 'normalized', ...
    'Position', [0 -.5 .95 1.5]);
s = uicontrol('Parent', f, ...
    'Style', 'slider', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position',[.95 0 .05 1], ...
    'Min', -.5, 'Max', 0, 'Value', 0, ...
    'Callback', {@onSlide, p});

%# add and plot to axes one-by-one
uicontrol('Parent', p, ...
    'Style', 'text', ...
    'String', 'sssss', ...
    'TooltipString', 'sss sksk sks os sssss', ...
    'Units', 'normalized', ...
    'Position', [0 .9 .1 .1]);

a1 = axes('Parent', p, ...
    'Units', 'normalized', ...
    'Position', [.1 .5 .8 .4]);
plot(a1, cumsum(rand(100,1)-0.5), 'LineWidth', 2, 'Color', 'r')
title(a1, sprintf('plot 1'))

a2 = axes('Parent', p, ...
    'Units', 'normalized', ...
    'Position', [.1 .1 .8 .4]);
plot(a2, cumsum(rand(100,1)-0.5), 'LineWidth', 2, 'Color', 'g')
title(a2, sprintf('plot 2'))

function onSlide(s, ev, p)
    %# slider value
    offset = get(s,'Value')

    %# update panel position
    pos = get(p, 'Position');  %# panel current position
    set(p, 'Position',[pos(1) -.5-offset pos(3) pos(4)])
end
