%TEST_PPMEASUREENSEMBLE_M

%% Test 1.1: Instantiation - empty

pr = PPMeasureEnsemble_M();

prop_number = PPMeasureEnsemble_M.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(PPMeasureEnsemble_M.getPropTag(prop));
	assert( ...
		isa(pr.getr(prop), 'NoValue'), ...
		[BRAPH2.STR ':PPMeasureEnsemble_M:' BRAPH2.BUG_FUNC], ...
		['PPMeasureEnsemble_M.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
		'Or there could be an error in PPMeasureEnsemble_M.getr(' int2str(prop) ').'] ...
		)
	assert( ...
		isa(pr.getr(TAG), 'NoValue'), ...
		[BRAPH2.STR ':PPMeasureEnsemble_M:' BRAPH2.BUG_FUNC], ...
		['PPMeasureEnsemble_M.getr(''' TAG ''') must be inizialized to NoValue(). ' ...
		'Or there could be an error in PPMeasureEnsemble_M.getr(''' TAG ''').'] ...
		)
end

%% Test 1.2: Instantiation - defaults

warning('off', 'BRAPH2:PPMeasureEnsemble_M')
pr = PPMeasureEnsemble_M( ...
	PPMeasureEnsemble_M.ID, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.ID), ...
	PPMeasureEnsemble_M.BKGCOLOR, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.BKGCOLOR), ...
	PPMeasureEnsemble_M.EL, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.EL), ...
	PPMeasureEnsemble_M.PROP, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.PROP), ...
	PPMeasureEnsemble_M.TITLE, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.TITLE), ...
	PPMeasureEnsemble_M.ENABLE, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.ENABLE), ...
	PPMeasureEnsemble_M.WAITBAR, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.WAITBAR) ...
	);
warning('on', 'BRAPH2:PPMeasureEnsemble_M')

for prop = 1:1:PPMeasureEnsemble_M.getPropNumber()
	TAG = upper(PPMeasureEnsemble_M.getPropTag(prop));
	switch PPMeasureEnsemble_M.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isequal(pr.getr(prop), PPMeasureEnsemble_M.getPropDefaultConditioned(prop)), ...
				[BRAPH2.STR ':PPMeasureEnsemble_M:' BRAPH2.BUG_FUNC], ...
				['PPMeasureEnsemble_M.getr(' int2str(prop) ') must be inizialized to its default value ' ...
				'given by PPMeasureEnsemble_M.getPropDefaultConditioned(' int2str(prop) '). ' ...
				'Or there could be an error in PPMeasureEnsemble_M.getr(' int2str(prop) ').'] ...
				)
			assert( ...
				isequal(pr.getr(TAG), PPMeasureEnsemble_M.getPropDefaultConditioned(prop)), ...
				[BRAPH2.STR ':PPMeasureEnsemble_M:' BRAPH2.BUG_FUNC], ...
				['PPMeasureEnsemble_M.getr(''' TAG ''') must be inizialized to its default value ' ...
				'given by PPMeasureEnsemble_M.getPropDefaultConditioned(' int2str(prop) '). ' ...
				'Or there could be an error in PPMeasureEnsemble_M.getr(''' TAG ''').'] ...
				)
		case Category.RESULT
			assert( ...
				isa(pr.getr(prop), 'NoValue'), ...
				[BRAPH2.STR ':PPMeasureEnsemble_M:' BRAPH2.BUG_FUNC], ...
				['Being a result, PPMeasureEnsemble_M.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
				'Or there could be an error in PPMeasureEnsemble_M.getr(' int2str(prop) ').'] ...
				)
			assert( ...
				isa(pr.getr(TAG), 'NoValue'), ...
				[BRAPH2.STR ':PPMeasureEnsemble_M:' BRAPH2.BUG_FUNC], ...
				['Being a result, PPMeasureEnsemble_M.getr(''' TAG ''') must be inizialized to NoValue(). ' ...
				'Or there could be an error in PPMeasureEnsemble_M.getr(''' TAG ''').'] ...
				)
	end
end

%% Test 2: Callbacks

warning('off', 'BRAPH2:PPMeasureEnsemble_M')
pr_0 = PPMeasureEnsemble_M( ...
	PPMeasureEnsemble_M.ID, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.ID), ...
	PPMeasureEnsemble_M.BKGCOLOR, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.BKGCOLOR), ...
	PPMeasureEnsemble_M.EL, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.EL), ...
	PPMeasureEnsemble_M.PROP, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.PROP), ...
	PPMeasureEnsemble_M.TITLE, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.TITLE), ...
	PPMeasureEnsemble_M.ENABLE, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.ENABLE), ...
	PPMeasureEnsemble_M.WAITBAR, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.WAITBAR) ...
	);
warning('on', 'BRAPH2:PPMeasureEnsemble_M')

pr_1 = PPMeasureEnsemble_M( ...
	PPMeasureEnsemble_M.ID, Callback('EL', pr_0, 'PROP', 1), ...
	PPMeasureEnsemble_M.BKGCOLOR, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.BKGCOLOR), ...
	PPMeasureEnsemble_M.EL, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.EL), ...
	PPMeasureEnsemble_M.PROP, Callback('EL', pr_0, 'PROP', 4), ...
	PPMeasureEnsemble_M.TITLE, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.TITLE), ...
	PPMeasureEnsemble_M.ENABLE, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.ENABLE), ...
	PPMeasureEnsemble_M.WAITBAR, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.WAITBAR) ...
	);
	
prop_number = PPMeasureEnsemble_M.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(PPMeasureEnsemble_M.getPropTag(prop));
	switch PPMeasureEnsemble_M.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(pr_1.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':PPMeasureEnsemble_M:' BRAPH2.BUG_FUNC], ...
				['PPMeasureEnsemble_M.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(pr_1.get(prop), pr_0.get(prop)) && ~isa(pr_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':PPMeasureEnsemble_M:' BRAPH2.BUG_FUNC], ...
				['PPMeasureEnsemble_M.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(pr_1.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':PPMeasureEnsemble_M:' BRAPH2.BUG_FUNC], ...
				['PPMeasureEnsemble_M.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end
pr_2 = PPMeasureEnsemble_M( ...
	PPMeasureEnsemble_M.ID, Callback('EL', pr_1, 'PROP', 1), ...
	PPMeasureEnsemble_M.BKGCOLOR, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.BKGCOLOR), ...
	PPMeasureEnsemble_M.EL, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.EL), ...
	PPMeasureEnsemble_M.PROP, Callback('EL', pr_1, 'PROP', 4), ...
	PPMeasureEnsemble_M.TITLE, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.TITLE), ...
	PPMeasureEnsemble_M.ENABLE, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.ENABLE), ...
	PPMeasureEnsemble_M.WAITBAR, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.WAITBAR) ...
	);
	
prop_number = PPMeasureEnsemble_M.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(PPMeasureEnsemble_M.getPropTag(prop));
	switch PPMeasureEnsemble_M.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(pr_2.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':PPMeasureEnsemble_M:' BRAPH2.BUG_FUNC], ...
				['PPMeasureEnsemble_M.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(pr_2.get(prop), pr_0.get(prop)) && ~isa(pr_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':PPMeasureEnsemble_M:' BRAPH2.BUG_FUNC], ...
				['PPMeasureEnsemble_M.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(pr_2.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':PPMeasureEnsemble_M:' BRAPH2.BUG_FUNC], ...
				['PPMeasureEnsemble_M.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end
pr_3 = PPMeasureEnsemble_M( ...
	PPMeasureEnsemble_M.ID, Callback('EL', pr_2, 'PROP', 1), ...
	PPMeasureEnsemble_M.BKGCOLOR, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.BKGCOLOR), ...
	PPMeasureEnsemble_M.EL, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.EL), ...
	PPMeasureEnsemble_M.PROP, Callback('EL', pr_2, 'PROP', 4), ...
	PPMeasureEnsemble_M.TITLE, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.TITLE), ...
	PPMeasureEnsemble_M.ENABLE, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.ENABLE), ...
	PPMeasureEnsemble_M.WAITBAR, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.WAITBAR) ...
	);
	
prop_number = PPMeasureEnsemble_M.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(PPMeasureEnsemble_M.getPropTag(prop));
	switch PPMeasureEnsemble_M.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(pr_3.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':PPMeasureEnsemble_M:' BRAPH2.BUG_FUNC], ...
				['PPMeasureEnsemble_M.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(pr_3.get(prop), pr_0.get(prop)) && ~isa(pr_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':PPMeasureEnsemble_M:' BRAPH2.BUG_FUNC], ...
				['PPMeasureEnsemble_M.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(pr_3.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':PPMeasureEnsemble_M:' BRAPH2.BUG_FUNC], ...
				['PPMeasureEnsemble_M.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end

%% Test 3: Result

warning('off', 'BRAPH2:PPMeasureEnsemble_M')
pr = PPMeasureEnsemble_M( ...
	PPMeasureEnsemble_M.ID, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.ID), ...
	PPMeasureEnsemble_M.BKGCOLOR, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.BKGCOLOR), ...
	PPMeasureEnsemble_M.EL, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.EL), ...
	PPMeasureEnsemble_M.PROP, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.PROP), ...
	PPMeasureEnsemble_M.TITLE, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.TITLE), ...
	PPMeasureEnsemble_M.ENABLE, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.ENABLE), ...
	PPMeasureEnsemble_M.WAITBAR, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.WAITBAR) ...
	);
warning('on', 'BRAPH2:PPMeasureEnsemble_M')

prop_number = PPMeasureEnsemble_M.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(PPMeasureEnsemble_M.getPropTag(prop));
	switch PPMeasureEnsemble_M.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
		case Category.RESULT
			assert( ...
				~isa(pr.get(prop),  'NoValue'), ...
				[BRAPH2.STR ':PPMeasureEnsemble_M:' BRAPH2.BUG_FUNC], ...
				['PPMeasureEnsemble_M.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				isa(pr.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':PPMeasureEnsemble_M:' BRAPH2.BUG_FUNC], ...
				['PPMeasureEnsemble_M.getr(' int2str(prop) ') must be a NoValue, because it has not been memorized.'] ...
				)
			if isempty(pr.getPropSettings(prop))
				assert( ...
					pr.checkFormat(pr.getPropFormat(prop), pr.get(prop)), ...
					[BRAPH2.STR ':PPMeasureEnsemble_M:' BRAPH2.BUG_FUNC], ...
					['PPMeasureEnsemble_M.get(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			else
				assert( ...
					pr.checkFormat(pr.getPropFormat(prop), pr.get(prop), pr.getPropSettings(prop)), ...
					[BRAPH2.STR ':PPMeasureEnsemble_M:' BRAPH2.BUG_FUNC], ...
					['PPMeasureEnsemble_M.get(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			end
	end
end

%% Test 4: Memorize

warning('off', 'BRAPH2:PPMeasureEnsemble_M')
pr = PPMeasureEnsemble_M( ...
	PPMeasureEnsemble_M.ID, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.ID), ...
	PPMeasureEnsemble_M.BKGCOLOR, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.BKGCOLOR), ...
	PPMeasureEnsemble_M.EL, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.EL), ...
	PPMeasureEnsemble_M.PROP, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.PROP), ...
	PPMeasureEnsemble_M.TITLE, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.TITLE), ...
	PPMeasureEnsemble_M.ENABLE, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.ENABLE), ...
	PPMeasureEnsemble_M.WAITBAR, PPMeasureEnsemble_M.getPropDefault(PPMeasureEnsemble_M.WAITBAR) ...
	);
warning('on', 'BRAPH2:PPMeasureEnsemble_M')

for prop = 1:1:PPMeasureEnsemble_M.getPropNumber()
	TAG = upper(PPMeasureEnsemble_M.getPropTag(prop));
	switch PPMeasureEnsemble_M.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
		case Category.RESULT
			assert( ...
				~isa(pr.get(prop),  'NoValue'), ...
				[BRAPH2.STR ':PPMeasureEnsemble_M:' BRAPH2.BUG_FUNC], ...
				['PPMeasureEnsemble_M.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				isa(pr.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':PPMeasureEnsemble_M:' BRAPH2.BUG_FUNC], ...
				['PPMeasureEnsemble_M.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
				)
			assert( ...
				~isa(pr.memorize(prop),  'NoValue'), ...
				[BRAPH2.STR ':PPMeasureEnsemble_M:' BRAPH2.BUG_FUNC], ...
				['PPMeasureEnsemble_M.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				~isa(pr.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':PPMeasureEnsemble_M:' BRAPH2.BUG_FUNC], ...
				['PPMeasureEnsemble_M.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
				)
			assert( ...
				pr.checkFormat(pr.getPropFormat(prop), pr.getr(prop),pr.getPropSettings(prop)), ...
				[BRAPH2.STR ':PPMeasureEnsemble_M:' BRAPH2.BUG_FUNC], ...
				['PPMeasureEnsemble_M.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
				)
	end
end

