%TEST_MEASUREENSEMBLEPF_BB

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
	
	categories = num2cell(Category.getCategories());
	pf = MeasureEnsemblePF_BB();
	 
	% get('ELCLASS')
	if isa(MeasureEnsemblePF_BB, 'ConcreteElement')
		assert(strcmp(MeasureEnsemblePF_BB().get('ELCLASS'), 'MeasureEnsemblePF_BB'), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'MeasureEnsemblePF_BB().get(''ELCLASS'') should return ''MeasureEnsemblePF_BB''.')
	end
	 
	% getBuild()
	assert(MeasureEnsemblePF_BB.getBuild() == 1 && MeasureEnsemblePF_BB.getBuild() > 0, ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'MeasureEnsemblePF_BB.getBuild() should return the MeasureEnsemblePF_BB build number.')
	assert(pf.getBuild() == 1 && pf.getBuild() > 0 , ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'pf.getBuild() should return the MeasureEnsemblePF_BB build number.')
	assert(Element.getBuild(pf) == 1 && Element.getBuild(pf) > 0, ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(pf) should return the MeasureEnsemblePF_BB build number.')
	assert(Element.getBuild('MeasureEnsemblePF_BB') == 1 && Element.getBuild('MeasureEnsemblePF_BB') > 0, ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''MeasureEnsemblePF_BB'') should return the MeasureEnsemblePF_BB build number.')
	 
	% getClass()
	assert(strcmp(MeasureEnsemblePF_BB.getClass(), 'MeasureEnsemblePF_BB'), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'MeasureEnsemblePF_BB.getClass() should return ''MeasureEnsemblePF_BB''.')
	assert(strcmp(pf.getClass(), 'MeasureEnsemblePF_BB'), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'pf.getClass() should return ''MeasureEnsemblePF_BB''.')
	assert(strcmp(Element.getClass(pf), 'MeasureEnsemblePF_BB'), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(pf) should return ''MeasureEnsemblePF_BB''.')
	assert(strcmp(Element.getClass('MeasureEnsemblePF_BB'), 'MeasureEnsemblePF_BB'), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''MeasureEnsemblePF_BB'') should return ''MeasureEnsemblePF_BB''.')
	 
	% getSubclasses()
	assert(isequal(MeasureEnsemblePF_BB.getSubclasses(), subclasses('MeasureEnsemblePF_BB', [], [], true)), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'MeasureEnsemblePF_BB.getSubclasses() should return the same result as subclasses(''MeasureEnsemblePF_BB'', [], [], true).')
	assert(isequal(pf.getSubclasses(), subclasses('MeasureEnsemblePF_BB', [], [], true)), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''MeasureEnsemblePF_BB'', [], [], true).')
	assert(isequal(Element.getSubclasses(pf), subclasses('MeasureEnsemblePF_BB', [], [], true)), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(pf) should return the same result as subclasses(''MeasureEnsemblePF_BB'', [], [], true).')
	assert(isequal(Element.getSubclasses('MeasureEnsemblePF_BB'), subclasses('MeasureEnsemblePF_BB', [], [], true)), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''MeasureEnsemblePF_BB'') should return the same result as subclasses(''MeasureEnsemblePF_BB'', [], [], true).')
	 
	% getProps()
	assert(isempty(MeasureEnsemblePF_BB.getProps()) || isequal(MeasureEnsemblePF_BB.getProps(), 1:1:length(MeasureEnsemblePF_BB.getProps())), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'MeasureEnsemblePF_BB.getProps() should return a row vector [1:1:N].')
	assert(isempty(MeasureEnsemblePF_BB.getProps()) || isequal(pf.getProps(), 1:1:length(MeasureEnsemblePF_BB.getProps())), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'pf.getProps() should return a row vector [1:1:N].')
	assert(isempty(MeasureEnsemblePF_BB.getProps()) || isequal(Element.getProps(pf), 1:1:length(MeasureEnsemblePF_BB.getProps())), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(pf) should return a row vector [1:1:N].')
	assert(isempty(MeasureEnsemblePF_BB.getProps()) || isequal(Element.getProps('MeasureEnsemblePF_BB'), 1:1:length(MeasureEnsemblePF_BB.getProps())), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''MeasureEnsemblePF_BB'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) MeasureEnsemblePF_BB.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(MeasureEnsemblePF_BB.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(MeasureEnsemblePF_BB.getProps())), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'MeasureEnsemblePF_BB.getProps(category) does not work.')
	tmp = cellfun(@(category) pf.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(MeasureEnsemblePF_BB.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(MeasureEnsemblePF_BB.getProps())), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'pf.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(pf, category), categories, 'UniformOutput', false);
	assert(isempty(MeasureEnsemblePF_BB.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(MeasureEnsemblePF_BB.getProps())), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(pf, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('MeasureEnsemblePF_BB', category), categories, 'UniformOutput', false);
	assert(isempty(MeasureEnsemblePF_BB.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(MeasureEnsemblePF_BB.getProps())), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''MeasureEnsemblePF_BB'', category) does not work.')
	 
	% getPropNumber()
	assert(MeasureEnsemblePF_BB.getPropNumber() == length(MeasureEnsemblePF_BB.getProps()), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'MeasureEnsemblePF_BB.getPropNumber() should return the number of properties.')
	assert(pf.getPropNumber() == length(MeasureEnsemblePF_BB.getProps()), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'pf.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(pf) == length(MeasureEnsemblePF_BB.getProps()), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(pf) should return the number of properties.')
	assert(Element.getPropNumber('MeasureEnsemblePF_BB') == length(MeasureEnsemblePF_BB.getProps()), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''MeasureEnsemblePF_BB'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) MeasureEnsemblePF_BB.getPropNumber(category), categories)) == MeasureEnsemblePF_BB.getPropNumber(), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'MeasureEnsemblePF_BB.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) pf.getPropNumber(category), categories)) == MeasureEnsemblePF_BB.getPropNumber(), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'pf.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(pf, category), categories)) == MeasureEnsemblePF_BB.getPropNumber(), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(pf, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('MeasureEnsemblePF_BB', category), categories)) == MeasureEnsemblePF_BB.getPropNumber(), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''MeasureEnsemblePF_BB'', category) does not work.')
	 
	% existsProp(prop)
	assert(~MeasureEnsemblePF_BB.existsProp(NaN), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'MeasureEnsemblePF_BB.existsProp(prop) does not work.')
	assert(~pf.existsProp(NaN), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'pf.existsProp(prop) does not work.')
	assert(~Element.existsProp(pf, NaN), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(pf, prop) does not work.')
	assert(~Element.existsProp('MeasureEnsemblePF_BB', NaN), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''MeasureEnsemblePF_BB'', prop) does not work.')
	 
	assert_with_error('MeasureEnsemblePF_BB.existsProp(NaN)', [BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.WRONG_INPUT], pf)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.WRONG_INPUT], pf)
	assert_with_error('Element.existsProp(''MeasureEnsemblePF_BB'', NaN)', [BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:MeasureEnsemblePF_BB.getPropNumber()
		assert(MeasureEnsemblePF_BB.existsProp(prop), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'MeasureEnsemblePF_BB.existsProp(prop) does not work.')
		assert(pf.existsProp(prop), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'pf.existsProp(prop) does not work.')
		assert(Element.existsProp(pf, prop), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(pf, prop) does not work.')
		assert(Element.existsProp('MeasureEnsemblePF_BB', prop), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''MeasureEnsemblePF_BB'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~MeasureEnsemblePF_BB.existsTag(''), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'MeasureEnsemblePF_BB.existsTag(tag) does not work.')
	assert(~pf.existsTag(''), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'pf.existsTag(tag) does not work.')
	assert(~Element.existsTag(pf, ''), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(pf, tag) does not work.')
	assert(~Element.existsTag('MeasureEnsemblePF_BB', ''), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''MeasureEnsemblePF_BB'', tag) does not work.')
	 
	assert_with_error('MeasureEnsemblePF_BB.existsTag('''')', [BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.WRONG_INPUT], pf)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.WRONG_INPUT], pf)
	assert_with_error('Element.existsTag(''MeasureEnsemblePF_BB'', '''')', [BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:MeasureEnsemblePF_BB.getPropNumber()
		tag = pf.getPropTag(prop);
		assert(MeasureEnsemblePF_BB.existsTag(tag), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'MeasureEnsemblePF_BB.existsTag(tag) does not work.')
		assert(pf.existsTag(tag), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'pf.existsTag(tag) does not work.')
		assert(Element.existsTag(pf, tag), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(pf, tga) does not work.')
		assert(Element.existsTag('MeasureEnsemblePF_BB', tag), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''MeasureEnsemblePF_BB'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:MeasureEnsemblePF_BB.getPropNumber()
		assert(MeasureEnsemblePF_BB.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'MeasureEnsemblePF_BB.getPropProp(prop) does not work.')
		assert(pf.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'pf.getPropProp(prop) does not work.')
		assert(Element.getPropProp(pf, prop) == prop, ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(pf, prop) does not work.')
		assert(Element.getPropProp('MeasureEnsemblePF_BB', prop) == prop, ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''MeasureEnsemblePF_BB'', prop) does not work.')
	 
		tag = pf.getPropTag(prop);
		assert(MeasureEnsemblePF_BB.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'MeasureEnsemblePF_BB.getPropProp(tag) does not work.')
		assert(pf.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'pf.getPropProp(tag) does not work.')
		assert(Element.getPropProp(pf, tag) == prop, ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(pf, tag) does not work.')
		assert(Element.getPropProp('MeasureEnsemblePF_BB', prop) == prop, ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''MeasureEnsemblePF_BB'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:MeasureEnsemblePF_BB.getPropNumber()
		tag = pf.getPropTag(prop);
	 
		assert(strcmp(MeasureEnsemblePF_BB.getPropTag(prop), tag), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'MeasureEnsemblePF_BB.getPropTag(prop) does not work.')
		assert(strcmp(pf.getPropTag(prop), tag), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'pf.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(pf, prop), tag), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(pf, prop) does not work.')
		assert(strcmp(Element.getPropTag('MeasureEnsemblePF_BB', prop), tag), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''MeasureEnsemblePF_BB'', prop) does not work.')
	 
		assert(strcmp(MeasureEnsemblePF_BB.getPropTag(tag), tag), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'MeasureEnsemblePF_BB.getPropTag(tag) does not work.')
		assert(strcmp(pf.getPropTag(tag), tag), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'pf.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(pf, tag), tag), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(pf, tag) does not work.')
		assert(strcmp(Element.getPropTag('MeasureEnsemblePF_BB', prop), tag), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''MeasureEnsemblePF_BB'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:MeasureEnsemblePF_BB.getPropNumber()
		tag = pf.getPropTag(prop);
	 
		assert(Category.existsCategory(MeasureEnsemblePF_BB.getPropCategory(prop)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'MeasureEnsemblePF_BB.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(pf.getPropCategory(prop)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'pf.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(pf, prop)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(pf, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(pf, prop)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''MeasureEnsemblePF_BB'', prop) does not work.')
	 
		assert(Category.existsCategory(MeasureEnsemblePF_BB.getPropCategory(tag)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'MeasureEnsemblePF_BB.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(pf.getPropCategory(tag)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'pf.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(pf, tag)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(pf, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(pf, tag)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''MeasureEnsemblePF_BB'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:MeasureEnsemblePF_BB.getPropNumber()
		tag = pf.getPropTag(prop);
	 
		assert(Format.existsFormat(MeasureEnsemblePF_BB.getPropFormat(prop)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'MeasureEnsemblePF_BB.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(pf.getPropFormat(prop)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'pf.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(pf, prop)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(pf, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(pf, prop)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''MeasureEnsemblePF_BB'', prop) does not work.')
	 
		assert(Format.existsFormat(MeasureEnsemblePF_BB.getPropFormat(tag)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'MeasureEnsemblePF_BB.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(pf.getPropFormat(tag)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'pf.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(pf, tag)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(pf, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(pf, tag)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''MeasureEnsemblePF_BB'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:MeasureEnsemblePF_BB.getPropNumber()
		tag = pf.getPropTag(prop);
	 
		assert(ischar(MeasureEnsemblePF_BB.getPropDescription(prop)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'MeasureEnsemblePF_BB.getPropDescription(prop) does not work.')
		assert(ischar(pf.getPropDescription(prop)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'pf.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(pf, prop)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(pf, prop) does not work.')
		assert(ischar(Element.getPropDescription(pf, prop)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''MeasureEnsemblePF_BB'', prop) does not work.')
	 
		assert(ischar(MeasureEnsemblePF_BB.getPropDescription(tag)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'MeasureEnsemblePF_BB.getPropDescription(tag) does not work.')
		assert(ischar(pf.getPropDescription(tag)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'pf.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(pf, tag)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(pf, tag) does not work.')
		assert(ischar(Element.getPropDescription(pf, tag)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''MeasureEnsemblePF_BB'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:MeasureEnsemblePF_BB.getPropNumber()
		tag = pf.getPropTag(prop);
	 
		settings = MeasureEnsemblePF_BB.getPropSettings(prop);
		settings = pf.getPropSettings(prop);
		settings = Element.getPropSettings(pf, prop);
		settings = Element.getPropSettings('MeasureEnsemblePF_BB', prop);
	 
		settings = MeasureEnsemblePF_BB.getPropSettings(tag);
		settings = pf.getPropSettings(tag);
		settings = Element.getPropSettings(pf, tag);
		settings = Element.getPropSettings('MeasureEnsemblePF_BB', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:MeasureEnsemblePF_BB.getPropNumber()
		tag = pf.getPropTag(prop);
	 
		default = MeasureEnsemblePF_BB.getPropDefault(prop);
		default = pf.getPropDefault(prop);
		default = Element.getPropDefault(pf, prop);
		default = Element.getPropDefault('MeasureEnsemblePF_BB', prop);
	 
		default = MeasureEnsemblePF_BB.getPropDefault(tag);
		default = pf.getPropDefault(tag);
		default = Element.getPropDefault(pf, tag);
		default = Element.getPropDefault('MeasureEnsemblePF_BB', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:MeasureEnsemblePF_BB.getPropNumber()
		tag = pf.getPropTag(prop);
	 
		conditioned_default = MeasureEnsemblePF_BB.getPropDefaultConditioned(prop);
		conditioned_default = pf.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(pf, prop);
		conditioned_default = Element.getPropDefaultConditioned('MeasureEnsemblePF_BB', prop);
	 
		conditioned_default = MeasureEnsemblePF_BB.getPropDefaultConditioned(tag);
		conditioned_default = pf.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(pf, tag);
		conditioned_default = Element.getPropDefaultConditioned('MeasureEnsemblePF_BB', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:MeasureEnsemblePF_BB.getPropNumber()
		tag = pf.getPropTag(prop);
	 
		assert(~MeasureEnsemblePF_BB.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'MeasureEnsemblePF_BB.checkProp(prop, value) does not work.')
		assert(~pf.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'pf.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(pf, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(pf, prop, value) does not work.')
		assert(~Element.checkProp('MeasureEnsemblePF_BB', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''MeasureEnsemblePF_BB'', prop, value) does not work.')
	 
		assert_with_error('MeasureEnsemblePF_BB.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.WRONG_INPUT], prop, pf)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.WRONG_INPUT], prop, pf)
		assert_with_error('Element.checkProp(''MeasureEnsemblePF_BB'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~MeasureEnsemblePF_BB.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'MeasureEnsemblePF_BB.checkProp(tag, value) does not work.')
		assert(~pf.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'pf.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(pf, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(pf, tag, value) does not work.')
		assert(~Element.checkProp('MeasureEnsemblePF_BB', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''MeasureEnsemblePF_BB'', tag, value) does not work.')
	 
		assert_with_error('MeasureEnsemblePF_BB.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.WRONG_INPUT], tag, pf)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.WRONG_INPUT], tag, pf)
		assert_with_error('Element.checkProp(''MeasureEnsemblePF_BB'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(MeasureEnsemblePF_BB.checkProp(prop, Element.getPropDefaultConditioned(MeasureEnsemblePF_BB, prop)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'MeasureEnsemblePF_BB.checkProp(prop, <conditioned default value>) does not work.')
		assert(pf.checkProp(prop, Element.getPropDefaultConditioned(MeasureEnsemblePF_BB, prop)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'pf.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(pf, prop, Element.getPropDefaultConditioned(MeasureEnsemblePF_BB, prop)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(pf, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('MeasureEnsemblePF_BB', prop, Element.getPropDefaultConditioned(MeasureEnsemblePF_BB, prop)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''MeasureEnsemblePF_BB'', prop, <conditioned default value>) does not work.')
	 
		assert(MeasureEnsemblePF_BB.checkProp(tag, Element.getPropDefaultConditioned(MeasureEnsemblePF_BB, prop)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'MeasureEnsemblePF_BB.checkProp(tag, <conditioned default value>) does not work.')
		assert(pf.checkProp(tag, Element.getPropDefaultConditioned(MeasureEnsemblePF_BB, prop)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'pf.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(pf, tag, Element.getPropDefaultConditioned(MeasureEnsemblePF_BB, prop)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(pf, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('MeasureEnsemblePF_BB', tag, Element.getPropDefaultConditioned(MeasureEnsemblePF_BB, prop)), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''MeasureEnsemblePF_BB'', tag, <conditioned default value>) does not work.')
	 
	end
	 
	
	warning('on', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
	
	pf = MeasureEnsemblePF_BB( ...
		MeasureEnsemblePF_BB.ELCLASS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.NAME, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DESCRIPTION, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.TEMPLATE, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.TEMPLATE), ...
		MeasureEnsemblePF_BB.ID, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ID), ...
		MeasureEnsemblePF_BB.LABEL, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.LABEL), ...
		MeasureEnsemblePF_BB.NOTES, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.NOTES), ...
		MeasureEnsemblePF_BB.TOSTRING, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.WAITBAR, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.WAITBAR), ...
		MeasureEnsemblePF_BB.H_WAITBAR, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DRAW, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DRAWN, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.PARENT, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.PARENT), ...
		MeasureEnsemblePF_BB.BKGCOLOR, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.BKGCOLOR), ...
		MeasureEnsemblePF_BB.H, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.SHOW, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.HIDE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DELETE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.CLOSE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_POSITION, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_POSITION), ...
		MeasureEnsemblePF_BB.H_TOOLBAR, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_TOOLS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_AXES, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_AXIS, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_AXIS), ...
		MeasureEnsemblePF_BB.LISTENER_ST_AXIS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ME, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ME), ...
		MeasureEnsemblePF_BB.SETUP, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_AREA, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_AREA, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_AREA), ...
		MeasureEnsemblePF_BB.LISTENER_ST_AREA, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_LINE_M, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_LINE_M, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_LINE_M), ...
		MeasureEnsemblePF_BB.LISTENER_ST_LINE_M, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_TITLE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_TITLE, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_TITLE), ...
		MeasureEnsemblePF_BB.H_XLABEL, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_XLABEL, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_XLABEL), ...
		MeasureEnsemblePF_BB.H_YLABEL, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_YLABEL, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_YLABEL), ...
		MeasureEnsemblePF_BB.NODES, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.NODES) ...
		);
	 
	for prop = 1:1:MeasureEnsemblePF_BB.getPropNumber()
	 
		% excluded props
		if any(prop == [MeasureEnsemblePF_BB.PARENT MeasureEnsemblePF_BB.H MeasureEnsemblePF_BB.ST_POSITION MeasureEnsemblePF_BB.ST_AXIS MeasureEnsemblePF_BB.ST_AREA MeasureEnsemblePF_BB.ST_LINE_M MeasureEnsemblePF_BB.ST_TITLE MeasureEnsemblePF_BB.ST_XLABEL MeasureEnsemblePF_BB.ST_YLABEL])
			continue
		end
	 
		TAG = upper(MeasureEnsemblePF_BB.getPropTag(prop));
		switch MeasureEnsemblePF_BB.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					pf.getr(prop) == MeasureEnsemblePF_BB.getNoValue(), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['Being a ' MeasureEnsemblePF_BB.getCategoryName(MeasureEnsemblePF_BB.getPropCategory(prop)) ', MeasureEnsemblePF_BB.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in MeasureEnsemblePF_BB.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					pf.getr(TAG) == MeasureEnsemblePF_BB.getNoValue(), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['Being a ' MeasureEnsemblePF_BB.getCategoryName(MeasureEnsemblePF_BB.getPropCategory(prop)) ', MeasureEnsemblePF_BB.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in MeasureEnsemblePF_BB.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(pf.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(pf.getPropSettings(prop))
					assert( ...
						pf.checkFormat(pf.getPropFormat(prop), pf.get(prop)), ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						['MeasureEnsemblePF_BB.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						pf.checkFormat(pf.getPropFormat(prop), pf.get(prop), pf.getPropSettings(prop)), ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						['MeasureEnsemblePF_BB.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					pf.getr(prop) == MeasureEnsemblePF_BB.getNoValue(), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['Being a ' MeasureEnsemblePF_BB.getCategoryName(MeasureEnsemblePF_BB.getPropCategory(prop)) ', MeasureEnsemblePF_BB.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in MeasureEnsemblePF_BB.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					pf.getr(TAG) == MeasureEnsemblePF_BB.getNoValue(), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['Being a ' MeasureEnsemblePF_BB.getCategoryName(MeasureEnsemblePF_BB.getPropCategory(prop)) ', MeasureEnsemblePF_BB.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in MeasureEnsemblePF_BB.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':MeasureEnsemblePF_BB']);
				assert( ...
					~isa(pf.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(pf.getPropSettings(prop))
					assert( ...
						pf.checkFormat(pf.getPropFormat(prop), pf.get(prop)), ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						['MeasureEnsemblePF_BB.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						pf.checkFormat(pf.getPropFormat(prop), pf.get(prop), pf.getPropSettings(prop)), ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						['MeasureEnsemblePF_BB.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(pf.getr(prop), MeasureEnsemblePF_BB.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by MeasureEnsemblePF_BB.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in MeasureEnsemblePF_BB.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(pf.getr(TAG), MeasureEnsemblePF_BB.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.getr(' TAG ') must be inizialized to its default value ' ...
					'given by MeasureEnsemblePF_BB.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in MeasureEnsemblePF_BB.getr(' TAG ').'] ...
					)
		end
	end
	
	warning('on', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
	
	pf = MeasureEnsemblePF_BB( ...
		MeasureEnsemblePF_BB.ELCLASS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.NAME, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DESCRIPTION, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.TEMPLATE, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.TEMPLATE), ...
		MeasureEnsemblePF_BB.ID, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ID), ...
		MeasureEnsemblePF_BB.LABEL, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.LABEL), ...
		MeasureEnsemblePF_BB.NOTES, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.NOTES), ...
		MeasureEnsemblePF_BB.TOSTRING, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.WAITBAR, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.WAITBAR), ...
		MeasureEnsemblePF_BB.H_WAITBAR, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DRAW, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DRAWN, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.PARENT, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.PARENT), ...
		MeasureEnsemblePF_BB.BKGCOLOR, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.BKGCOLOR), ...
		MeasureEnsemblePF_BB.H, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.SHOW, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.HIDE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DELETE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.CLOSE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_POSITION, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_POSITION), ...
		MeasureEnsemblePF_BB.H_TOOLBAR, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_TOOLS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_AXES, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_AXIS, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_AXIS), ...
		MeasureEnsemblePF_BB.LISTENER_ST_AXIS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ME, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ME), ...
		MeasureEnsemblePF_BB.SETUP, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_AREA, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_AREA, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_AREA), ...
		MeasureEnsemblePF_BB.LISTENER_ST_AREA, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_LINE_M, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_LINE_M, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_LINE_M), ...
		MeasureEnsemblePF_BB.LISTENER_ST_LINE_M, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_TITLE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_TITLE, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_TITLE), ...
		MeasureEnsemblePF_BB.H_XLABEL, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_XLABEL, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_XLABEL), ...
		MeasureEnsemblePF_BB.H_YLABEL, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_YLABEL, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_YLABEL), ...
		MeasureEnsemblePF_BB.NODES, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.NODES) ...
		);
	 
	for prop = 1:1:MeasureEnsemblePF_BB.getPropNumber()
	 
		% excluded props
		if any(prop == [MeasureEnsemblePF_BB.PARENT MeasureEnsemblePF_BB.H MeasureEnsemblePF_BB.ST_POSITION MeasureEnsemblePF_BB.ST_AXIS MeasureEnsemblePF_BB.ST_AREA MeasureEnsemblePF_BB.ST_LINE_M MeasureEnsemblePF_BB.ST_TITLE MeasureEnsemblePF_BB.ST_XLABEL MeasureEnsemblePF_BB.ST_YLABEL])
			continue
		end
	 
		TAG = upper(MeasureEnsemblePF_BB.getPropTag(prop));
		switch MeasureEnsemblePF_BB.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(pf.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(pf.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(pf.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(pf.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					pf.checkFormat(pf.getPropFormat(prop), pf.getr(prop),pf.getPropSettings(prop)), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':MeasureEnsemblePF_BB']);
				assert( ...
					~isa(pf.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(pf.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':MeasureEnsemblePF_BB']);
	% 			assert( ...
	% 				~isa(pf.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
	% 				['MeasureEnsemblePF_BB.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(pf.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
	% 				['MeasureEnsemblePF_BB.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				pf.checkFormat(pf.getPropFormat(prop), pf.getr(prop),pf.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
	% 				['MeasureEnsemblePF_BB.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':MeasureEnsemblePF_BB']);
				assert( ...
					~isa(pf.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(pf.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(pf.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(pf.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					pf.checkFormat(pf.getPropFormat(prop), pf.getr(prop),pf.getPropSettings(prop)), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if pf.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:MeasureEnsemblePF_BB');
					delete(ancestor(pf.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(MeasureEnsemblePF_BB.getProps(Category.RESULT))
		for prop = 1:1:MeasureEnsemblePF_BB.getPropNumber()
	 
			% excluded props
			if any(prop == [MeasureEnsemblePF_BB.PARENT MeasureEnsemblePF_BB.H MeasureEnsemblePF_BB.ST_POSITION MeasureEnsemblePF_BB.ST_AXIS MeasureEnsemblePF_BB.ST_AREA MeasureEnsemblePF_BB.ST_LINE_M MeasureEnsemblePF_BB.ST_TITLE MeasureEnsemblePF_BB.ST_XLABEL MeasureEnsemblePF_BB.ST_YLABEL])
				continue
			end
	 
			switch MeasureEnsemblePF_BB.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						pf.isLocked(prop), ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						['MeasureEnsemblePF_BB.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~pf.isLocked(prop), ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						['MeasureEnsemblePF_BB.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
	
	warning('on', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
	
	pf = MeasureEnsemblePF_BB();
	 
	for prop = 1:1:MeasureEnsemblePF_BB.getPropNumber()
		TAG = upper(MeasureEnsemblePF_BB.getPropTag(prop));
		assert( ...
			~pf.isLocked(prop), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			['MeasureEnsemblePF_BB.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~pf.isLocked(TAG), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			['MeasureEnsemblePF_BB.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	pf.lock()
	 
	for prop = 1:1:MeasureEnsemblePF_BB.getPropNumber()
		switch MeasureEnsemblePF_BB.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					pf.isLocked(prop), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~pf.isLocked(prop), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
	
	warning('on', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
	
	pf = MeasureEnsemblePF_BB();
	 
	warning_backup = warning('off', 'BRAPH2:MeasureEnsemblePF_BB');
	for prop = 1:1:MeasureEnsemblePF_BB.getPropNumber()
		pf.lock(prop)
		switch MeasureEnsemblePF_BB.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					pf.isLocked(prop), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~pf.isLocked(prop), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
	
	warning('on', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
	
	pf = MeasureEnsemblePF_BB();
	 
	for prop = 1:1:MeasureEnsemblePF_BB.getPropNumber()
		TAG = upper(MeasureEnsemblePF_BB.getPropTag(prop));
		assert( ...
			pf.isChecked(prop), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			['MeasureEnsemblePF_BB.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			pf.isChecked(TAG), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			['MeasureEnsemblePF_BB.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	pf.unchecked()
	 
	for prop = 1:1:MeasureEnsemblePF_BB.getPropNumber()
		assert( ...
			~pf.isChecked(prop), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			['MeasureEnsemblePF_BB.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	pf.checked()
	 
	for prop = 1:1:MeasureEnsemblePF_BB.getPropNumber()
		assert( ...
			pf.isChecked(prop), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			['MeasureEnsemblePF_BB.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
	
	warning('on', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
	
	% basic MeasureEnsemblePF_BB
	pf_0 = MeasureEnsemblePF_BB( ...
		MeasureEnsemblePF_BB.ELCLASS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.NAME, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DESCRIPTION, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.TEMPLATE, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.TEMPLATE), ...
		MeasureEnsemblePF_BB.ID, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ID), ...
		MeasureEnsemblePF_BB.LABEL, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.LABEL), ...
		MeasureEnsemblePF_BB.NOTES, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.NOTES), ...
		MeasureEnsemblePF_BB.TOSTRING, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.WAITBAR, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.WAITBAR), ...
		MeasureEnsemblePF_BB.H_WAITBAR, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DRAW, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DRAWN, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.PARENT, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.PARENT), ...
		MeasureEnsemblePF_BB.BKGCOLOR, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.BKGCOLOR), ...
		MeasureEnsemblePF_BB.H, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.SHOW, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.HIDE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DELETE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.CLOSE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_POSITION, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_POSITION), ...
		MeasureEnsemblePF_BB.H_TOOLBAR, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_TOOLS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_AXES, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_AXIS, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_AXIS), ...
		MeasureEnsemblePF_BB.LISTENER_ST_AXIS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ME, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ME), ...
		MeasureEnsemblePF_BB.SETUP, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_AREA, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_AREA, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_AREA), ...
		MeasureEnsemblePF_BB.LISTENER_ST_AREA, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_LINE_M, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_LINE_M, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_LINE_M), ...
		MeasureEnsemblePF_BB.LISTENER_ST_LINE_M, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_TITLE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_TITLE, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_TITLE), ...
		MeasureEnsemblePF_BB.H_XLABEL, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_XLABEL, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_XLABEL), ...
		MeasureEnsemblePF_BB.H_YLABEL, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_YLABEL, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_YLABEL), ...
		MeasureEnsemblePF_BB.NODES, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.NODES) ...
		);
	 
	% MeasureEnsemblePF_BB with 1st callbacks
	pf_1 = MeasureEnsemblePF_BB( ...
		MeasureEnsemblePF_BB.ELCLASS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.NAME, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DESCRIPTION, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.TEMPLATE, pf_0.getCallback(4), ..., ...
		MeasureEnsemblePF_BB.ID, pf_0.getCallback(5), ..., ...
		MeasureEnsemblePF_BB.LABEL, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.LABEL), ...
		MeasureEnsemblePF_BB.NOTES, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.NOTES), ...
		MeasureEnsemblePF_BB.TOSTRING, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.WAITBAR, pf_0.getCallback(9), ..., ...
		MeasureEnsemblePF_BB.H_WAITBAR, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DRAW, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DRAWN, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.PARENT, pf_0.getCallback(13), ..., ...
		MeasureEnsemblePF_BB.BKGCOLOR, pf_0.getCallback(14), ..., ...
		MeasureEnsemblePF_BB.H, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.SHOW, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.HIDE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DELETE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.CLOSE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_POSITION, pf_0.getCallback(20), ..., ...
		MeasureEnsemblePF_BB.H_TOOLBAR, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_TOOLS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_AXES, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_AXIS, pf_0.getCallback(24), ..., ...
		MeasureEnsemblePF_BB.LISTENER_ST_AXIS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ME, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ME), ...
		MeasureEnsemblePF_BB.SETUP, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_AREA, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_AREA, pf_0.getCallback(29), ..., ...
		MeasureEnsemblePF_BB.LISTENER_ST_AREA, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_LINE_M, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_LINE_M, pf_0.getCallback(32), ..., ...
		MeasureEnsemblePF_BB.LISTENER_ST_LINE_M, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_TITLE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_TITLE, pf_0.getCallback(35), ..., ...
		MeasureEnsemblePF_BB.H_XLABEL, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_XLABEL, pf_0.getCallback(37), ..., ...
		MeasureEnsemblePF_BB.H_YLABEL, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_YLABEL, pf_0.getCallback(39), ..., ...
		MeasureEnsemblePF_BB.NODES, pf_0.getCallback(40) ... ...
		);
	 
	prop_number = MeasureEnsemblePF_BB.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(MeasureEnsemblePF_BB.getPropTag(prop));
		switch MeasureEnsemblePF_BB.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(pf_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(pf_1.get(prop), pf_0.get(prop)) && ~isa(pf_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(pf_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% MeasureEnsemblePF_BB with 2nd callbacks
	pf_2 = MeasureEnsemblePF_BB( ...
		MeasureEnsemblePF_BB.ELCLASS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.NAME, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DESCRIPTION, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.TEMPLATE, pf_1.getCallback(4), ..., ...
		MeasureEnsemblePF_BB.ID, pf_1.getCallback(5), ..., ...
		MeasureEnsemblePF_BB.LABEL, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.LABEL), ...
		MeasureEnsemblePF_BB.NOTES, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.NOTES), ...
		MeasureEnsemblePF_BB.TOSTRING, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.WAITBAR, pf_1.getCallback(9), ..., ...
		MeasureEnsemblePF_BB.H_WAITBAR, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DRAW, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DRAWN, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.PARENT, pf_1.getCallback(13), ..., ...
		MeasureEnsemblePF_BB.BKGCOLOR, pf_1.getCallback(14), ..., ...
		MeasureEnsemblePF_BB.H, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.SHOW, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.HIDE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DELETE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.CLOSE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_POSITION, pf_1.getCallback(20), ..., ...
		MeasureEnsemblePF_BB.H_TOOLBAR, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_TOOLS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_AXES, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_AXIS, pf_1.getCallback(24), ..., ...
		MeasureEnsemblePF_BB.LISTENER_ST_AXIS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ME, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ME), ...
		MeasureEnsemblePF_BB.SETUP, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_AREA, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_AREA, pf_1.getCallback(29), ..., ...
		MeasureEnsemblePF_BB.LISTENER_ST_AREA, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_LINE_M, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_LINE_M, pf_1.getCallback(32), ..., ...
		MeasureEnsemblePF_BB.LISTENER_ST_LINE_M, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_TITLE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_TITLE, pf_1.getCallback(35), ..., ...
		MeasureEnsemblePF_BB.H_XLABEL, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_XLABEL, pf_1.getCallback(37), ..., ...
		MeasureEnsemblePF_BB.H_YLABEL, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_YLABEL, pf_1.getCallback(39), ..., ...
		MeasureEnsemblePF_BB.NODES, pf_1.getCallback(40) ... ...
		);
	 
	prop_number = MeasureEnsemblePF_BB.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(MeasureEnsemblePF_BB.getPropTag(prop));
		switch MeasureEnsemblePF_BB.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(pf_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(pf_2.get(prop), pf_0.get(prop)) && ~isa(pf_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(pf_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% MeasureEnsemblePF_BB with 3rd callbacks
	pf_3 = MeasureEnsemblePF_BB( ...
		MeasureEnsemblePF_BB.ELCLASS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.NAME, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DESCRIPTION, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.TEMPLATE, pf_2.getCallback(4), ..., ...
		MeasureEnsemblePF_BB.ID, pf_2.getCallback(5), ..., ...
		MeasureEnsemblePF_BB.LABEL, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.LABEL), ...
		MeasureEnsemblePF_BB.NOTES, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.NOTES), ...
		MeasureEnsemblePF_BB.TOSTRING, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.WAITBAR, pf_2.getCallback(9), ..., ...
		MeasureEnsemblePF_BB.H_WAITBAR, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DRAW, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DRAWN, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.PARENT, pf_2.getCallback(13), ..., ...
		MeasureEnsemblePF_BB.BKGCOLOR, pf_2.getCallback(14), ..., ...
		MeasureEnsemblePF_BB.H, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.SHOW, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.HIDE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DELETE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.CLOSE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_POSITION, pf_2.getCallback(20), ..., ...
		MeasureEnsemblePF_BB.H_TOOLBAR, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_TOOLS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_AXES, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_AXIS, pf_2.getCallback(24), ..., ...
		MeasureEnsemblePF_BB.LISTENER_ST_AXIS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ME, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ME), ...
		MeasureEnsemblePF_BB.SETUP, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_AREA, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_AREA, pf_2.getCallback(29), ..., ...
		MeasureEnsemblePF_BB.LISTENER_ST_AREA, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_LINE_M, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_LINE_M, pf_2.getCallback(32), ..., ...
		MeasureEnsemblePF_BB.LISTENER_ST_LINE_M, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_TITLE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_TITLE, pf_2.getCallback(35), ..., ...
		MeasureEnsemblePF_BB.H_XLABEL, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_XLABEL, pf_2.getCallback(37), ..., ...
		MeasureEnsemblePF_BB.H_YLABEL, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_YLABEL, pf_2.getCallback(39), ..., ...
		MeasureEnsemblePF_BB.NODES, pf_2.getCallback(40) ... ...
		);
	 
	prop_number = MeasureEnsemblePF_BB.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(MeasureEnsemblePF_BB.getPropTag(prop));
		switch MeasureEnsemblePF_BB.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(pf_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(pf_3.get(prop), pf_0.get(prop)) && ~isa(pf_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(pf_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	
	warning('on', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
	
	% copy empty element
	pf = MeasureEnsemblePF_BB();
	 
	pf_copy = pf.copy();
	 
	assert(pf_copy ~= pf, ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'MeasureEnsemblePF_BB.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(pf_copy, pf), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'MeasureEnsemblePF_BB.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:MeasureEnsemblePF_BB.getPropNumber()
		value = pf.getr(prop);
		value_copy = pf_copy.getr(prop);
		switch MeasureEnsemblePF_BB.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					'MeasureEnsemblePF_BB.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						'MeasureEnsemblePF_BB.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						'MeasureEnsemblePF_BB.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						'MeasureEnsemblePF_BB.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
							'MeasureEnsemblePF_BB.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
							'MeasureEnsemblePF_BB.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						'MeasureEnsemblePF_BB.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					pf_copy.isLocked(prop) == pf.isLocked(prop), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					'MeasureEnsemblePF_BB.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					pf_copy.isChecked(prop) == pf.isChecked(prop), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					'MeasureEnsemblePF_BB.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					pf_copy.getPropSeed(prop) == pf.getPropSeed(prop), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					'MeasureEnsemblePF_BB.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	pf = MeasureEnsemblePF_BB( ...
		MeasureEnsemblePF_BB.ELCLASS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.NAME, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DESCRIPTION, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.TEMPLATE, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.TEMPLATE), ...
		MeasureEnsemblePF_BB.ID, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ID), ...
		MeasureEnsemblePF_BB.LABEL, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.LABEL), ...
		MeasureEnsemblePF_BB.NOTES, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.NOTES), ...
		MeasureEnsemblePF_BB.TOSTRING, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.WAITBAR, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.WAITBAR), ...
		MeasureEnsemblePF_BB.H_WAITBAR, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DRAW, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DRAWN, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.PARENT, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.PARENT), ...
		MeasureEnsemblePF_BB.BKGCOLOR, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.BKGCOLOR), ...
		MeasureEnsemblePF_BB.H, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.SHOW, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.HIDE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DELETE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.CLOSE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_POSITION, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_POSITION), ...
		MeasureEnsemblePF_BB.H_TOOLBAR, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_TOOLS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_AXES, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_AXIS, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_AXIS), ...
		MeasureEnsemblePF_BB.LISTENER_ST_AXIS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ME, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ME), ...
		MeasureEnsemblePF_BB.SETUP, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_AREA, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_AREA, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_AREA), ...
		MeasureEnsemblePF_BB.LISTENER_ST_AREA, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_LINE_M, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_LINE_M, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_LINE_M), ...
		MeasureEnsemblePF_BB.LISTENER_ST_LINE_M, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_TITLE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_TITLE, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_TITLE), ...
		MeasureEnsemblePF_BB.H_XLABEL, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_XLABEL, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_XLABEL), ...
		MeasureEnsemblePF_BB.H_YLABEL, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_YLABEL, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_YLABEL), ...
		MeasureEnsemblePF_BB.NODES, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.NODES) ...
		);
	 
	for prop = 1:1:MeasureEnsemblePF_BB.getPropNumber()
		if MeasureEnsemblePF_BB.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':MeasureEnsemblePF_BB']);
			% pf.memorize(prop);
			% warning(warning_backup)
		elseif MeasureEnsemblePF_BB.getPropCategory(prop) == Category.EVANESCENT && pf.getPropFormat(prop) == Format.HANDLE
			pf.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:MeasureEnsemblePF_BB');
			delete(ancestor(pf.get(prop), 'figure'))
			warning(warning_backup)
		else
			pf.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	pf_copy = pf.copy();
	 
	for prop = 1:1:MeasureEnsemblePF_BB.getPropNumber()
		value = pf.getr(prop);
		value_copy = pf_copy.getr(prop);
		switch MeasureEnsemblePF_BB.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					'MeasureEnsemblePF_BB.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						'MeasureEnsemblePF_BB.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						'MeasureEnsemblePF_BB.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						'MeasureEnsemblePF_BB.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
							'MeasureEnsemblePF_BB.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
							'MeasureEnsemblePF_BB.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						'MeasureEnsemblePF_BB.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						pf_copy.isLocked(prop) == pf.isLocked(prop), ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						'MeasureEnsemblePF_BB.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						pf_copy.isChecked(prop) == pf.isChecked(prop), ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						'MeasureEnsemblePF_BB.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						pf_copy.getPropSeed(prop) == pf.getPropSeed(prop), ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						'MeasureEnsemblePF_BB.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	pf_0 = MeasureEnsemblePF_BB( ...
		MeasureEnsemblePF_BB.ELCLASS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.NAME, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DESCRIPTION, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.TEMPLATE, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.TEMPLATE), ...
		MeasureEnsemblePF_BB.ID, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ID), ...
		MeasureEnsemblePF_BB.LABEL, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.LABEL), ...
		MeasureEnsemblePF_BB.NOTES, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.NOTES), ...
		MeasureEnsemblePF_BB.TOSTRING, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.WAITBAR, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.WAITBAR), ...
		MeasureEnsemblePF_BB.H_WAITBAR, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DRAW, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DRAWN, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.PARENT, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.PARENT), ...
		MeasureEnsemblePF_BB.BKGCOLOR, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.BKGCOLOR), ...
		MeasureEnsemblePF_BB.H, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.SHOW, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.HIDE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DELETE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.CLOSE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_POSITION, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_POSITION), ...
		MeasureEnsemblePF_BB.H_TOOLBAR, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_TOOLS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_AXES, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_AXIS, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_AXIS), ...
		MeasureEnsemblePF_BB.LISTENER_ST_AXIS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ME, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ME), ...
		MeasureEnsemblePF_BB.SETUP, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_AREA, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_AREA, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_AREA), ...
		MeasureEnsemblePF_BB.LISTENER_ST_AREA, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_LINE_M, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_LINE_M, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_LINE_M), ...
		MeasureEnsemblePF_BB.LISTENER_ST_LINE_M, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_TITLE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_TITLE, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_TITLE), ...
		MeasureEnsemblePF_BB.H_XLABEL, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_XLABEL, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_XLABEL), ...
		MeasureEnsemblePF_BB.H_YLABEL, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_YLABEL, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_YLABEL), ...
		MeasureEnsemblePF_BB.NODES, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.NODES) ...
		);
	 
	pf = MeasureEnsemblePF_BB( ...
		MeasureEnsemblePF_BB.ELCLASS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.NAME, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DESCRIPTION, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.TEMPLATE, pf_0.getCallback(4), ..., ...
		MeasureEnsemblePF_BB.ID, pf_0.getCallback(5), ..., ...
		MeasureEnsemblePF_BB.LABEL, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.LABEL), ...
		MeasureEnsemblePF_BB.NOTES, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.NOTES), ...
		MeasureEnsemblePF_BB.TOSTRING, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.WAITBAR, pf_0.getCallback(9), ..., ...
		MeasureEnsemblePF_BB.H_WAITBAR, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DRAW, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DRAWN, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.PARENT, pf_0.getCallback(13), ..., ...
		MeasureEnsemblePF_BB.BKGCOLOR, pf_0.getCallback(14), ..., ...
		MeasureEnsemblePF_BB.H, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.SHOW, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.HIDE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DELETE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.CLOSE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_POSITION, pf_0.getCallback(20), ..., ...
		MeasureEnsemblePF_BB.H_TOOLBAR, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_TOOLS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_AXES, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_AXIS, pf_0.getCallback(24), ..., ...
		MeasureEnsemblePF_BB.LISTENER_ST_AXIS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ME, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ME), ...
		MeasureEnsemblePF_BB.SETUP, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_AREA, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_AREA, pf_0.getCallback(29), ..., ...
		MeasureEnsemblePF_BB.LISTENER_ST_AREA, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_LINE_M, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_LINE_M, pf_0.getCallback(32), ..., ...
		MeasureEnsemblePF_BB.LISTENER_ST_LINE_M, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_TITLE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_TITLE, pf_0.getCallback(35), ..., ...
		MeasureEnsemblePF_BB.H_XLABEL, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_XLABEL, pf_0.getCallback(37), ..., ...
		MeasureEnsemblePF_BB.H_YLABEL, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_YLABEL, pf_0.getCallback(39), ..., ...
		MeasureEnsemblePF_BB.NODES, pf_0.getCallback(40) ... ...
		);
	 
	pf_copy = pf.copy();
	pf_0_copy = pf_copy.getr('ID').get('EL');
	 
	for prop = 1:1:MeasureEnsemblePF_BB.getPropNumber()
		value = pf.getr(prop);
		value_copy = pf_copy.getr(prop);
		switch MeasureEnsemblePF_BB.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					'MeasureEnsemblePF_BB.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						'MeasureEnsemblePF_BB.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						'MeasureEnsemblePF_BB.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						'MeasureEnsemblePF_BB.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
							'MeasureEnsemblePF_BB.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
							'MeasureEnsemblePF_BB.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						'MeasureEnsemblePF_BB.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == pf_0.getCallback(prop), ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						'MeasureEnsemblePF_BB.copy() does not work. The callback should be obtained from MeasureEnsemblePF_BB.getCallback().' ...
						)
					assert( ...
						value_copy == pf_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						'MeasureEnsemblePF_BB.copy() does not work. The callback should be obtained from MeasureEnsemblePF_BB.getCallback().' ...
						)
				end
	 
					assert( ...
						pf_copy.isLocked(prop) == pf.isLocked(prop), ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						'MeasureEnsemblePF_BB.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						pf_copy.isChecked(prop) == pf.isChecked(prop), ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						'MeasureEnsemblePF_BB.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						pf_copy.getPropSeed(prop) == pf.getPropSeed(prop), ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						'MeasureEnsemblePF_BB.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	
	warning('on', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
	
	pf_template = MeasureEnsemblePF_BB();
	pf = MeasureEnsemblePF_BB('TEMPLATE', pf_template);
	 
	for prop = 1:1:MeasureEnsemblePF_BB.getPropNumber()
	 
		% excluded props
		if any(prop == [MeasureEnsemblePF_BB.PARENT MeasureEnsemblePF_BB.H MeasureEnsemblePF_BB.ST_POSITION MeasureEnsemblePF_BB.ST_AXIS MeasureEnsemblePF_BB.ST_AREA MeasureEnsemblePF_BB.ST_LINE_M MeasureEnsemblePF_BB.ST_TITLE MeasureEnsemblePF_BB.ST_XLABEL MeasureEnsemblePF_BB.ST_YLABEL])
			continue
		end
	 
		TAG = upper(MeasureEnsemblePF_BB.getPropTag(prop));
		switch MeasureEnsemblePF_BB.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == MeasureEnsemblePF_BB.TEMPLATE
					assert( ...
						isa(pf.getr(prop), 'MeasureEnsemblePF_BB'), ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						'MeasureEnsemblePF_BB TEMPLATE does not work. MeasureEnsemblePF_BB.getr(''TEMPLATE'') should be a MeasureEnsemblePF_BB element.' ...
						)
					assert( ...
						isa(pf_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						'MeasureEnsemblePF_BB TEMPLATE does not work. MeasureEnsemblePF_BB_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(pf.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						['MeasureEnsemblePF_BB TEMPLATE does not work. MeasureEnsemblePF_BB.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						pf.getr(prop).get('EL') == pf_template && pf.getr(prop).get('PROP') == prop && strcmp(pf.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						['MeasureEnsemblePF_BB TEMPLATE does not work. MeasureEnsemblePF_BB.getr(' TAG ') should be a Callback to pf_template.' TAG '.'] ...
						)
					assert( ...
						isa(pf_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
						['MeasureEnsemblePF_BB TEMPLATE does not work. MeasureEnsemblePF_BB_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(pf.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB TEMPLATE does not work. MeasureEnsemblePF_BB.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(pf_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
					['MeasureEnsemblePF_BB TEMPLATE does not work. MeasureEnsemblePF_BB_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
	
	warning('on', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
	
	pf = MeasureEnsemblePF_BB( ...
		MeasureEnsemblePF_BB.ELCLASS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.NAME, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DESCRIPTION, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.TEMPLATE, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.TEMPLATE), ...
		MeasureEnsemblePF_BB.ID, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ID), ...
		MeasureEnsemblePF_BB.LABEL, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.LABEL), ...
		MeasureEnsemblePF_BB.NOTES, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.NOTES), ...
		MeasureEnsemblePF_BB.TOSTRING, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.WAITBAR, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.WAITBAR), ...
		MeasureEnsemblePF_BB.H_WAITBAR, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DRAW, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DRAWN, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.PARENT, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.PARENT), ...
		MeasureEnsemblePF_BB.BKGCOLOR, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.BKGCOLOR), ...
		MeasureEnsemblePF_BB.H, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.SHOW, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.HIDE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DELETE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.CLOSE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_POSITION, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_POSITION), ...
		MeasureEnsemblePF_BB.H_TOOLBAR, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_TOOLS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_AXES, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_AXIS, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_AXIS), ...
		MeasureEnsemblePF_BB.LISTENER_ST_AXIS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ME, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ME), ...
		MeasureEnsemblePF_BB.SETUP, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_AREA, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_AREA, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_AREA), ...
		MeasureEnsemblePF_BB.LISTENER_ST_AREA, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_LINE_M, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_LINE_M, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_LINE_M), ...
		MeasureEnsemblePF_BB.LISTENER_ST_LINE_M, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_TITLE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_TITLE, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_TITLE), ...
		MeasureEnsemblePF_BB.H_XLABEL, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_XLABEL, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_XLABEL), ...
		MeasureEnsemblePF_BB.H_YLABEL, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_YLABEL, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_YLABEL), ...
		MeasureEnsemblePF_BB.NODES, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.NODES) ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'measureensemblepf_bb_to_be_erased.b2'];
	 
	Element.save(pf, filename)
	 
	pf_loaded = Element.load(filename);
	 
	assert( ...
		isequal(pf.copy(), pf_loaded), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'MeasureEnsemblePF_BB.save(pf) and/or MeasureEnsemblePF_BB.load() do not work.' ...
		)
	 
	delete(filename)
	
	warning('on', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
	
	pf = MeasureEnsemblePF_BB( ...
		MeasureEnsemblePF_BB.ELCLASS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.NAME, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DESCRIPTION, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.TEMPLATE, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.TEMPLATE), ...
		MeasureEnsemblePF_BB.ID, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ID), ...
		MeasureEnsemblePF_BB.LABEL, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.LABEL), ...
		MeasureEnsemblePF_BB.NOTES, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.NOTES), ...
		MeasureEnsemblePF_BB.TOSTRING, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.WAITBAR, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.WAITBAR), ...
		MeasureEnsemblePF_BB.H_WAITBAR, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DRAW, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DRAWN, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.PARENT, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.PARENT), ...
		MeasureEnsemblePF_BB.BKGCOLOR, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.BKGCOLOR), ...
		MeasureEnsemblePF_BB.H, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.SHOW, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.HIDE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.DELETE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.CLOSE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_POSITION, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_POSITION), ...
		MeasureEnsemblePF_BB.H_TOOLBAR, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_TOOLS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_AXES, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_AXIS, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_AXIS), ...
		MeasureEnsemblePF_BB.LISTENER_ST_AXIS, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ME, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ME), ...
		MeasureEnsemblePF_BB.SETUP, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_AREA, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_AREA, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_AREA), ...
		MeasureEnsemblePF_BB.LISTENER_ST_AREA, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_LINE_M, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_LINE_M, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_LINE_M), ...
		MeasureEnsemblePF_BB.LISTENER_ST_LINE_M, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.H_TITLE, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_TITLE, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_TITLE), ...
		MeasureEnsemblePF_BB.H_XLABEL, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_XLABEL, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_XLABEL), ...
		MeasureEnsemblePF_BB.H_YLABEL, MeasureEnsemblePF_BB.getNoValue(), ...
		MeasureEnsemblePF_BB.ST_YLABEL, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.ST_YLABEL), ...
		MeasureEnsemblePF_BB.NODES, MeasureEnsemblePF_BB.getPropDefault(MeasureEnsemblePF_BB.NODES) ...
		);
	 
	[json, struct, el_list] = encodeJSON(pf);
	[pf_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(pf_dec ~= pf, ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		'MeasureEnsemblePF_BB.encodeJSON() or MeasureEnsemblePF_BB.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) MeasureEnsemblePF_BB.getPropFormat(prop), num2cell(MeasureEnsemblePF_BB.getProps())) == Format.HANDLE) && all(cellfun(@(prop) MeasureEnsemblePF_BB.getPropFormat(prop), num2cell(MeasureEnsemblePF_BB.getProps())) == Format.NET)
		assert(isequal(pf_dec, pf), ...
			[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
			'MeasureEnsemblePF_BB.encodeJSON() or MeasureEnsemblePF_BB.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
	
	warning('on', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
end

%% Test 12: Remove Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
	
	warning('off', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
	assert(length(findall(0, 'type', 'figure')) == 1)
	delete(findall(0, 'type', 'figure'))
	warning('on', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
	
	warning('on', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
end

%% Test 13: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
	
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':MeasureEnsemblePF_BB:' BRAPH2.FAIL_TEST], ...
		[' When testing MeasureEnsemblePF_BB no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
	
	warning('on', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
end

%% Test 14: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
	
	delete(findall(0, 'type', 'figure'))
	
	warning('on', [BRAPH2.STR ':MeasureEnsemblePF_BB'])
end

