%TEST_MEASURE

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	m = Measure();
	 
	% get('ELCLASS')
	if isa(Measure, 'ConcreteElement')
		assert(strcmp(Measure().get('ELCLASS'), 'Measure'), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Measure().get(''ELCLASS'') should return ''Measure''.')
	end
	 
	% getBuild()
	assert(Measure.getBuild() == 1 && Measure.getBuild() > 0, ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Measure.getBuild() should return the Measure build number.')
	assert(m.getBuild() == 1 && m.getBuild() > 0 , ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'm.getBuild() should return the Measure build number.')
	assert(Element.getBuild(m) == 1 && Element.getBuild(m) > 0, ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(m) should return the Measure build number.')
	assert(Element.getBuild('Measure') == 1 && Element.getBuild('Measure') > 0, ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''Measure'') should return the Measure build number.')
	 
	% getClass()
	assert(strcmp(Measure.getClass(), 'Measure'), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Measure.getClass() should return ''Measure''.')
	assert(strcmp(m.getClass(), 'Measure'), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'm.getClass() should return ''Measure''.')
	assert(strcmp(Element.getClass(m), 'Measure'), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(m) should return ''Measure''.')
	assert(strcmp(Element.getClass('Measure'), 'Measure'), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''Measure'') should return ''Measure''.')
	 
	% getSubclasses()
	assert(isequal(Measure.getSubclasses(), subclasses('Measure', [], [], true)), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Measure.getSubclasses() should return the same result as subclasses(''Measure'', [], [], true).')
	assert(isequal(m.getSubclasses(), subclasses('Measure', [], [], true)), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''Measure'', [], [], true).')
	assert(isequal(Element.getSubclasses(m), subclasses('Measure', [], [], true)), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(m) should return the same result as subclasses(''Measure'', [], [], true).')
	assert(isequal(Element.getSubclasses('Measure'), subclasses('Measure', [], [], true)), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''Measure'') should return the same result as subclasses(''Measure'', [], [], true).')
	 
	% getProps()
	assert(isempty(Measure.getProps()) || isequal(Measure.getProps(), 1:1:length(Measure.getProps())), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Measure.getProps() should return a row vector [1:1:N].')
	assert(isempty(Measure.getProps()) || isequal(m.getProps(), 1:1:length(Measure.getProps())), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'm.getProps() should return a row vector [1:1:N].')
	assert(isempty(Measure.getProps()) || isequal(Element.getProps(m), 1:1:length(Measure.getProps())), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(m) should return a row vector [1:1:N].')
	assert(isempty(Measure.getProps()) || isequal(Element.getProps('Measure'), 1:1:length(Measure.getProps())), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''Measure'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) Measure.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(Measure.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(Measure.getProps())), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Measure.getProps(category) does not work.')
	tmp = cellfun(@(category) m.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(Measure.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(Measure.getProps())), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'm.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(m, category), categories, 'UniformOutput', false);
	assert(isempty(Measure.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(Measure.getProps())), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(m, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('Measure', category), categories, 'UniformOutput', false);
	assert(isempty(Measure.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(Measure.getProps())), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''Measure'', category) does not work.')
	 
	% getPropNumber()
	assert(Measure.getPropNumber() == length(Measure.getProps()), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Measure.getPropNumber() should return the number of properties.')
	assert(m.getPropNumber() == length(Measure.getProps()), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'm.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(m) == length(Measure.getProps()), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(m) should return the number of properties.')
	assert(Element.getPropNumber('Measure') == length(Measure.getProps()), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''Measure'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) Measure.getPropNumber(category), categories)) == Measure.getPropNumber(), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Measure.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) m.getPropNumber(category), categories)) == Measure.getPropNumber(), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'm.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(m, category), categories)) == Measure.getPropNumber(), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(m, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('Measure', category), categories)) == Measure.getPropNumber(), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''Measure'', category) does not work.')
	 
	% existsProp(prop)
	assert(~Measure.existsProp(NaN), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Measure.existsProp(prop) does not work.')
	assert(~m.existsProp(NaN), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'm.existsProp(prop) does not work.')
	assert(~Element.existsProp(m, NaN), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(m, prop) does not work.')
	assert(~Element.existsProp('Measure', NaN), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''Measure'', prop) does not work.')
	 
	assert_with_error('Measure.existsProp(NaN)', [BRAPH2.STR ':Measure:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':Measure:' BRAPH2.WRONG_INPUT], m)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':Measure:' BRAPH2.WRONG_INPUT], m)
	assert_with_error('Element.existsProp(''Measure'', NaN)', [BRAPH2.STR ':Measure:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:Measure.getPropNumber()
		assert(Measure.existsProp(prop), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Measure.existsProp(prop) does not work.')
		assert(m.existsProp(prop), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'm.existsProp(prop) does not work.')
		assert(Element.existsProp(m, prop), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(m, prop) does not work.')
		assert(Element.existsProp('Measure', prop), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''Measure'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~Measure.existsTag(''), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Measure.existsTag(tag) does not work.')
	assert(~m.existsTag(''), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'm.existsTag(tag) does not work.')
	assert(~Element.existsTag(m, ''), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(m, tag) does not work.')
	assert(~Element.existsTag('Measure', ''), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''Measure'', tag) does not work.')
	 
	assert_with_error('Measure.existsTag('''')', [BRAPH2.STR ':Measure:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':Measure:' BRAPH2.WRONG_INPUT], m)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':Measure:' BRAPH2.WRONG_INPUT], m)
	assert_with_error('Element.existsTag(''Measure'', '''')', [BRAPH2.STR ':Measure:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:Measure.getPropNumber()
		tag = m.getPropTag(prop);
		assert(Measure.existsTag(tag), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Measure.existsTag(tag) does not work.')
		assert(m.existsTag(tag), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'm.existsTag(tag) does not work.')
		assert(Element.existsTag(m, tag), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(m, tga) does not work.')
		assert(Element.existsTag('Measure', tag), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''Measure'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:Measure.getPropNumber()
		assert(Measure.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Measure.getPropProp(prop) does not work.')
		assert(m.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'm.getPropProp(prop) does not work.')
		assert(Element.getPropProp(m, prop) == prop, ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(m, prop) does not work.')
		assert(Element.getPropProp('Measure', prop) == prop, ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''Measure'', prop) does not work.')
	 
		tag = m.getPropTag(prop);
		assert(Measure.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Measure.getPropProp(tag) does not work.')
		assert(m.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'm.getPropProp(tag) does not work.')
		assert(Element.getPropProp(m, tag) == prop, ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(m, tag) does not work.')
		assert(Element.getPropProp('Measure', prop) == prop, ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''Measure'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:Measure.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(strcmp(Measure.getPropTag(prop), tag), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Measure.getPropTag(prop) does not work.')
		assert(strcmp(m.getPropTag(prop), tag), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'm.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(m, prop), tag), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(m, prop) does not work.')
		assert(strcmp(Element.getPropTag('Measure', prop), tag), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''Measure'', prop) does not work.')
	 
		assert(strcmp(Measure.getPropTag(tag), tag), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Measure.getPropTag(tag) does not work.')
		assert(strcmp(m.getPropTag(tag), tag), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'm.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(m, tag), tag), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(m, tag) does not work.')
		assert(strcmp(Element.getPropTag('Measure', prop), tag), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''Measure'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:Measure.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(Category.existsCategory(Measure.getPropCategory(prop)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Measure.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(m.getPropCategory(prop)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'm.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(m, prop)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(m, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(m, prop)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''Measure'', prop) does not work.')
	 
		assert(Category.existsCategory(Measure.getPropCategory(tag)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Measure.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(m.getPropCategory(tag)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'm.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(m, tag)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(m, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(m, tag)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''Measure'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:Measure.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(Format.existsFormat(Measure.getPropFormat(prop)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Measure.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(m.getPropFormat(prop)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'm.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(m, prop)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(m, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(m, prop)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''Measure'', prop) does not work.')
	 
		assert(Format.existsFormat(Measure.getPropFormat(tag)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Measure.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(m.getPropFormat(tag)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'm.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(m, tag)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(m, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(m, tag)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''Measure'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:Measure.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(ischar(Measure.getPropDescription(prop)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Measure.getPropDescription(prop) does not work.')
		assert(ischar(m.getPropDescription(prop)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'm.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(m, prop)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(m, prop) does not work.')
		assert(ischar(Element.getPropDescription(m, prop)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''Measure'', prop) does not work.')
	 
		assert(ischar(Measure.getPropDescription(tag)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Measure.getPropDescription(tag) does not work.')
		assert(ischar(m.getPropDescription(tag)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'm.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(m, tag)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(m, tag) does not work.')
		assert(ischar(Element.getPropDescription(m, tag)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''Measure'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:Measure.getPropNumber()
		tag = m.getPropTag(prop);
	 
		settings = Measure.getPropSettings(prop);
		settings = m.getPropSettings(prop);
		settings = Element.getPropSettings(m, prop);
		settings = Element.getPropSettings('Measure', prop);
	 
		settings = Measure.getPropSettings(tag);
		settings = m.getPropSettings(tag);
		settings = Element.getPropSettings(m, tag);
		settings = Element.getPropSettings('Measure', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:Measure.getPropNumber()
		tag = m.getPropTag(prop);
	 
		default = Measure.getPropDefault(prop);
		default = m.getPropDefault(prop);
		default = Element.getPropDefault(m, prop);
		default = Element.getPropDefault('Measure', prop);
	 
		default = Measure.getPropDefault(tag);
		default = m.getPropDefault(tag);
		default = Element.getPropDefault(m, tag);
		default = Element.getPropDefault('Measure', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:Measure.getPropNumber()
		tag = m.getPropTag(prop);
	 
		conditioned_default = Measure.getPropDefaultConditioned(prop);
		conditioned_default = m.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(m, prop);
		conditioned_default = Element.getPropDefaultConditioned('Measure', prop);
	 
		conditioned_default = Measure.getPropDefaultConditioned(tag);
		conditioned_default = m.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(m, tag);
		conditioned_default = Element.getPropDefaultConditioned('Measure', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:Measure.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(~Measure.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Measure.checkProp(prop, value) does not work.')
		assert(~m.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'm.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(m, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(m, prop, value) does not work.')
		assert(~Element.checkProp('Measure', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''Measure'', prop, value) does not work.')
	 
		assert_with_error('Measure.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':Measure:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':Measure:' BRAPH2.WRONG_INPUT], prop, m)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':Measure:' BRAPH2.WRONG_INPUT], prop, m)
		assert_with_error('Element.checkProp(''Measure'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':Measure:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~Measure.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Measure.checkProp(tag, value) does not work.')
		assert(~m.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'm.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(m, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(m, tag, value) does not work.')
		assert(~Element.checkProp('Measure', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''Measure'', tag, value) does not work.')
	 
		assert_with_error('Measure.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':Measure:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':Measure:' BRAPH2.WRONG_INPUT], tag, m)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':Measure:' BRAPH2.WRONG_INPUT], tag, m)
		assert_with_error('Element.checkProp(''Measure'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':Measure:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(Measure.checkProp(prop, Element.getPropDefaultConditioned(Measure, prop)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Measure.checkProp(prop, <conditioned default value>) does not work.')
		assert(m.checkProp(prop, Element.getPropDefaultConditioned(Measure, prop)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'm.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(m, prop, Element.getPropDefaultConditioned(Measure, prop)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(m, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('Measure', prop, Element.getPropDefaultConditioned(Measure, prop)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''Measure'', prop, <conditioned default value>) does not work.')
	 
		assert(Measure.checkProp(tag, Element.getPropDefaultConditioned(Measure, prop)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Measure.checkProp(tag, <conditioned default value>) does not work.')
		assert(m.checkProp(tag, Element.getPropDefaultConditioned(Measure, prop)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'm.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(m, tag, Element.getPropDefaultConditioned(Measure, prop)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(m, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('Measure', tag, Element.getPropDefaultConditioned(Measure, prop)), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''Measure'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = Measure( ...
		Measure.ELCLASS, Measure.getNoValue(), ...
		Measure.NAME, Measure.getNoValue(), ...
		Measure.DESCRIPTION, Measure.getNoValue(), ...
		Measure.TEMPLATE, Measure.getPropDefault(Measure.TEMPLATE), ...
		Measure.ID, Measure.getPropDefault(Measure.ID), ...
		Measure.LABEL, Measure.getPropDefault(Measure.LABEL), ...
		Measure.NOTES, Measure.getPropDefault(Measure.NOTES), ...
		Measure.TOSTRING, Measure.getNoValue(), ...
		Measure.SHAPE, Measure.getNoValue(), ...
		Measure.SCOPE, Measure.getNoValue(), ...
		Measure.PARAMETRICITY, Measure.getNoValue(), ...
		Measure.COMPATIBLE_GRAPHS, Measure.getNoValue(), ...
		Measure.G, Measure.getPropDefault(Measure.G), ...
		Measure.M, Measure.getNoValue(), ...
		Measure.PFM, Measure.getPropDefault(Measure.PFM) ...
		);
	 
	for prop = 1:1:Measure.getPropNumber()
	 
		% excluded props
		if any(prop == [Measure.TEMPLATE Measure.PFM])
			continue
		end
	 
		TAG = upper(Measure.getPropTag(prop));
		switch Measure.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					m.getr(prop) == Measure.getNoValue(), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Being a ' Measure.getCategoryName(Measure.getPropCategory(prop)) ', Measure.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in Measure.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					m.getr(TAG) == Measure.getNoValue(), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Being a ' Measure.getCategoryName(Measure.getPropCategory(prop)) ', Measure.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in Measure.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(m.getPropSettings(prop))
					assert( ...
						m.checkFormat(m.getPropFormat(prop), m.get(prop)), ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						['Measure.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						m.checkFormat(m.getPropFormat(prop), m.get(prop), m.getPropSettings(prop)), ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						['Measure.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					m.getr(prop) == Measure.getNoValue(), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Being a ' Measure.getCategoryName(Measure.getPropCategory(prop)) ', Measure.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in Measure.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					m.getr(TAG) == Measure.getNoValue(), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Being a ' Measure.getCategoryName(Measure.getPropCategory(prop)) ', Measure.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in Measure.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':Measure']);
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(m.getPropSettings(prop))
					assert( ...
						m.checkFormat(m.getPropFormat(prop), m.get(prop)), ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						['Measure.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						m.checkFormat(m.getPropFormat(prop), m.get(prop), m.getPropSettings(prop)), ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						['Measure.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(m.getr(prop), Measure.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by Measure.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in Measure.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(m.getr(TAG), Measure.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.getr(' TAG ') must be inizialized to its default value ' ...
					'given by Measure.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in Measure.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = Measure( ...
		Measure.ELCLASS, Measure.getNoValue(), ...
		Measure.NAME, Measure.getNoValue(), ...
		Measure.DESCRIPTION, Measure.getNoValue(), ...
		Measure.TEMPLATE, Measure.getPropDefault(Measure.TEMPLATE), ...
		Measure.ID, Measure.getPropDefault(Measure.ID), ...
		Measure.LABEL, Measure.getPropDefault(Measure.LABEL), ...
		Measure.NOTES, Measure.getPropDefault(Measure.NOTES), ...
		Measure.TOSTRING, Measure.getNoValue(), ...
		Measure.SHAPE, Measure.getNoValue(), ...
		Measure.SCOPE, Measure.getNoValue(), ...
		Measure.PARAMETRICITY, Measure.getNoValue(), ...
		Measure.COMPATIBLE_GRAPHS, Measure.getNoValue(), ...
		Measure.G, Measure.getPropDefault(Measure.G), ...
		Measure.M, Measure.getNoValue(), ...
		Measure.PFM, Measure.getPropDefault(Measure.PFM) ...
		);
	 
	for prop = 1:1:Measure.getPropNumber()
	 
		% excluded props
		if any(prop == [Measure.TEMPLATE Measure.PFM])
			continue
		end
	 
		TAG = upper(Measure.getPropTag(prop));
		switch Measure.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(m.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					m.checkFormat(m.getPropFormat(prop), m.getr(prop),m.getPropSettings(prop)), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':Measure']);
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':Measure']);
	% 			assert( ...
	% 				~isa(m.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
	% 				['Measure.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(m.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
	% 				['Measure.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				m.checkFormat(m.getPropFormat(prop), m.getr(prop),m.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
	% 				['Measure.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':Measure']);
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(m.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					m.checkFormat(m.getPropFormat(prop), m.getr(prop),m.getPropSettings(prop)), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if m.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:Measure');
					delete(ancestor(m.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(Measure.getProps(Category.RESULT))
		for prop = 1:1:Measure.getPropNumber()
	 
			% excluded props
			if any(prop == [Measure.TEMPLATE Measure.PFM])
				continue
			end
	 
			switch Measure.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						m.isLocked(prop), ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						['Measure.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~m.isLocked(prop), ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						['Measure.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = Measure();
	 
	for prop = 1:1:Measure.getPropNumber()
		TAG = upper(Measure.getPropTag(prop));
		assert( ...
			~m.isLocked(prop), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			['Measure.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~m.isLocked(TAG), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			['Measure.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	m.lock()
	 
	for prop = 1:1:Measure.getPropNumber()
		switch Measure.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					m.isLocked(prop), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~m.isLocked(prop), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = Measure();
	 
	warning_backup = warning('off', 'BRAPH2:Measure');
	for prop = 1:1:Measure.getPropNumber()
		m.lock(prop)
		switch Measure.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					m.isLocked(prop), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~m.isLocked(prop), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = Measure();
	 
	for prop = 1:1:Measure.getPropNumber()
		TAG = upper(Measure.getPropTag(prop));
		assert( ...
			m.isChecked(prop), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			['Measure.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			m.isChecked(TAG), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			['Measure.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	m.unchecked()
	 
	for prop = 1:1:Measure.getPropNumber()
		assert( ...
			~m.isChecked(prop), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			['Measure.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	m.checked()
	 
	for prop = 1:1:Measure.getPropNumber()
		assert( ...
			m.isChecked(prop), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			['Measure.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic Measure
	m_0 = Measure( ...
		Measure.ELCLASS, Measure.getNoValue(), ...
		Measure.NAME, Measure.getNoValue(), ...
		Measure.DESCRIPTION, Measure.getNoValue(), ...
		Measure.TEMPLATE, Measure.getPropDefault(Measure.TEMPLATE), ...
		Measure.ID, Measure.getPropDefault(Measure.ID), ...
		Measure.LABEL, Measure.getPropDefault(Measure.LABEL), ...
		Measure.NOTES, Measure.getPropDefault(Measure.NOTES), ...
		Measure.TOSTRING, Measure.getNoValue(), ...
		Measure.SHAPE, Measure.getNoValue(), ...
		Measure.SCOPE, Measure.getNoValue(), ...
		Measure.PARAMETRICITY, Measure.getNoValue(), ...
		Measure.COMPATIBLE_GRAPHS, Measure.getNoValue(), ...
		Measure.G, Measure.getPropDefault(Measure.G), ...
		Measure.M, Measure.getNoValue(), ...
		Measure.PFM, Measure.getPropDefault(Measure.PFM) ...
		);
	 
	% Measure with 1st callbacks
	m_1 = Measure( ...
		Measure.ELCLASS, Measure.getNoValue(), ...
		Measure.NAME, Measure.getNoValue(), ...
		Measure.DESCRIPTION, Measure.getNoValue(), ...
		Measure.TEMPLATE, m_0.getCallback(4), ..., ...
		Measure.ID, m_0.getCallback(5), ..., ...
		Measure.LABEL, Measure.getPropDefault(Measure.LABEL), ...
		Measure.NOTES, Measure.getPropDefault(Measure.NOTES), ...
		Measure.TOSTRING, Measure.getNoValue(), ...
		Measure.SHAPE, Measure.getNoValue(), ...
		Measure.SCOPE, Measure.getNoValue(), ...
		Measure.PARAMETRICITY, Measure.getNoValue(), ...
		Measure.COMPATIBLE_GRAPHS, Measure.getNoValue(), ...
		Measure.G, m_0.getCallback(13), ..., ...
		Measure.M, Measure.getNoValue(), ...
		Measure.PFM, m_0.getCallback(15) ... ...
		);
	 
	prop_number = Measure.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(Measure.getPropTag(prop));
		switch Measure.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(m_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(m_1.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(m_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% Measure with 2nd callbacks
	m_2 = Measure( ...
		Measure.ELCLASS, Measure.getNoValue(), ...
		Measure.NAME, Measure.getNoValue(), ...
		Measure.DESCRIPTION, Measure.getNoValue(), ...
		Measure.TEMPLATE, m_1.getCallback(4), ..., ...
		Measure.ID, m_1.getCallback(5), ..., ...
		Measure.LABEL, Measure.getPropDefault(Measure.LABEL), ...
		Measure.NOTES, Measure.getPropDefault(Measure.NOTES), ...
		Measure.TOSTRING, Measure.getNoValue(), ...
		Measure.SHAPE, Measure.getNoValue(), ...
		Measure.SCOPE, Measure.getNoValue(), ...
		Measure.PARAMETRICITY, Measure.getNoValue(), ...
		Measure.COMPATIBLE_GRAPHS, Measure.getNoValue(), ...
		Measure.G, m_1.getCallback(13), ..., ...
		Measure.M, Measure.getNoValue(), ...
		Measure.PFM, m_1.getCallback(15) ... ...
		);
	 
	prop_number = Measure.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(Measure.getPropTag(prop));
		switch Measure.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(m_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(m_2.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(m_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% Measure with 3rd callbacks
	m_3 = Measure( ...
		Measure.ELCLASS, Measure.getNoValue(), ...
		Measure.NAME, Measure.getNoValue(), ...
		Measure.DESCRIPTION, Measure.getNoValue(), ...
		Measure.TEMPLATE, m_2.getCallback(4), ..., ...
		Measure.ID, m_2.getCallback(5), ..., ...
		Measure.LABEL, Measure.getPropDefault(Measure.LABEL), ...
		Measure.NOTES, Measure.getPropDefault(Measure.NOTES), ...
		Measure.TOSTRING, Measure.getNoValue(), ...
		Measure.SHAPE, Measure.getNoValue(), ...
		Measure.SCOPE, Measure.getNoValue(), ...
		Measure.PARAMETRICITY, Measure.getNoValue(), ...
		Measure.COMPATIBLE_GRAPHS, Measure.getNoValue(), ...
		Measure.G, m_2.getCallback(13), ..., ...
		Measure.M, Measure.getNoValue(), ...
		Measure.PFM, m_2.getCallback(15) ... ...
		);
	 
	prop_number = Measure.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(Measure.getPropTag(prop));
		switch Measure.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(m_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(m_3.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(m_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	m = Measure();
	 
	m_copy = m.copy();
	 
	assert(m_copy ~= m, ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Measure.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(m_copy, m), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Measure.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:Measure.getPropNumber()
		value = m.getr(prop);
		value_copy = m_copy.getr(prop);
		switch Measure.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					'Measure.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						'Measure.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						'Measure.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						'Measure.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
							'Measure.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
							'Measure.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						'Measure.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					m_copy.isLocked(prop) == m.isLocked(prop), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					'Measure.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					m_copy.isChecked(prop) == m.isChecked(prop), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					'Measure.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					m_copy.getPropSeed(prop) == m.getPropSeed(prop), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					'Measure.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	m = Measure( ...
		Measure.ELCLASS, Measure.getNoValue(), ...
		Measure.NAME, Measure.getNoValue(), ...
		Measure.DESCRIPTION, Measure.getNoValue(), ...
		Measure.TEMPLATE, Measure.getPropDefault(Measure.TEMPLATE), ...
		Measure.ID, Measure.getPropDefault(Measure.ID), ...
		Measure.LABEL, Measure.getPropDefault(Measure.LABEL), ...
		Measure.NOTES, Measure.getPropDefault(Measure.NOTES), ...
		Measure.TOSTRING, Measure.getNoValue(), ...
		Measure.SHAPE, Measure.getNoValue(), ...
		Measure.SCOPE, Measure.getNoValue(), ...
		Measure.PARAMETRICITY, Measure.getNoValue(), ...
		Measure.COMPATIBLE_GRAPHS, Measure.getNoValue(), ...
		Measure.G, Measure.getPropDefault(Measure.G), ...
		Measure.M, Measure.getNoValue(), ...
		Measure.PFM, Measure.getPropDefault(Measure.PFM) ...
		);
	 
	for prop = 1:1:Measure.getPropNumber()
		if Measure.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':Measure']);
			% m.memorize(prop);
			% warning(warning_backup)
		elseif Measure.getPropCategory(prop) == Category.EVANESCENT && m.getPropFormat(prop) == Format.HANDLE
			m.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:Measure');
			delete(ancestor(m.get(prop), 'figure'))
			warning(warning_backup)
		else
			m.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	m_copy = m.copy();
	 
	for prop = 1:1:Measure.getPropNumber()
		value = m.getr(prop);
		value_copy = m_copy.getr(prop);
		switch Measure.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					'Measure.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						'Measure.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						'Measure.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						'Measure.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
							'Measure.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
							'Measure.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						'Measure.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						m_copy.isLocked(prop) == m.isLocked(prop), ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						'Measure.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						m_copy.isChecked(prop) == m.isChecked(prop), ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						'Measure.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						m_copy.getPropSeed(prop) == m.getPropSeed(prop), ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						'Measure.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	m_0 = Measure( ...
		Measure.ELCLASS, Measure.getNoValue(), ...
		Measure.NAME, Measure.getNoValue(), ...
		Measure.DESCRIPTION, Measure.getNoValue(), ...
		Measure.TEMPLATE, Measure.getPropDefault(Measure.TEMPLATE), ...
		Measure.ID, Measure.getPropDefault(Measure.ID), ...
		Measure.LABEL, Measure.getPropDefault(Measure.LABEL), ...
		Measure.NOTES, Measure.getPropDefault(Measure.NOTES), ...
		Measure.TOSTRING, Measure.getNoValue(), ...
		Measure.SHAPE, Measure.getNoValue(), ...
		Measure.SCOPE, Measure.getNoValue(), ...
		Measure.PARAMETRICITY, Measure.getNoValue(), ...
		Measure.COMPATIBLE_GRAPHS, Measure.getNoValue(), ...
		Measure.G, Measure.getPropDefault(Measure.G), ...
		Measure.M, Measure.getNoValue(), ...
		Measure.PFM, Measure.getPropDefault(Measure.PFM) ...
		);
	 
	m = Measure( ...
		Measure.ELCLASS, Measure.getNoValue(), ...
		Measure.NAME, Measure.getNoValue(), ...
		Measure.DESCRIPTION, Measure.getNoValue(), ...
		Measure.TEMPLATE, m_0.getCallback(4), ..., ...
		Measure.ID, m_0.getCallback(5), ..., ...
		Measure.LABEL, Measure.getPropDefault(Measure.LABEL), ...
		Measure.NOTES, Measure.getPropDefault(Measure.NOTES), ...
		Measure.TOSTRING, Measure.getNoValue(), ...
		Measure.SHAPE, Measure.getNoValue(), ...
		Measure.SCOPE, Measure.getNoValue(), ...
		Measure.PARAMETRICITY, Measure.getNoValue(), ...
		Measure.COMPATIBLE_GRAPHS, Measure.getNoValue(), ...
		Measure.G, m_0.getCallback(13), ..., ...
		Measure.M, Measure.getNoValue(), ...
		Measure.PFM, m_0.getCallback(15) ... ...
		);
	 
	m_copy = m.copy();
	m_0_copy = m_copy.getr('ID').get('EL');
	 
	for prop = 1:1:Measure.getPropNumber()
		value = m.getr(prop);
		value_copy = m_copy.getr(prop);
		switch Measure.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					'Measure.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						'Measure.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						'Measure.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						'Measure.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
							'Measure.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
							'Measure.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						'Measure.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == m_0.getCallback(prop), ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						'Measure.copy() does not work. The callback should be obtained from Measure.getCallback().' ...
						)
					assert( ...
						value_copy == m_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						'Measure.copy() does not work. The callback should be obtained from Measure.getCallback().' ...
						)
				end
	 
					assert( ...
						m_copy.isLocked(prop) == m.isLocked(prop), ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						'Measure.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						m_copy.isChecked(prop) == m.isChecked(prop), ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						'Measure.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						m_copy.getPropSeed(prop) == m.getPropSeed(prop), ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						'Measure.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m_template = Measure();
	m = Measure('TEMPLATE', m_template);
	 
	for prop = 1:1:Measure.getPropNumber()
	 
		% excluded props
		if any(prop == [Measure.TEMPLATE Measure.PFM])
			continue
		end
	 
		TAG = upper(Measure.getPropTag(prop));
		switch Measure.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == Measure.TEMPLATE
					assert( ...
						isa(m.getr(prop), 'Measure'), ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						'Measure TEMPLATE does not work. Measure.getr(''TEMPLATE'') should be a Measure element.' ...
						)
					assert( ...
						isa(m_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						'Measure TEMPLATE does not work. Measure_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(m.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						['Measure TEMPLATE does not work. Measure.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						m.getr(prop).get('EL') == m_template && m.getr(prop).get('PROP') == prop && strcmp(m.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						['Measure TEMPLATE does not work. Measure.getr(' TAG ') should be a Callback to m_template.' TAG '.'] ...
						)
					assert( ...
						isa(m_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
						['Measure TEMPLATE does not work. Measure_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure TEMPLATE does not work. Measure.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(m_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
					['Measure TEMPLATE does not work. Measure_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = Measure( ...
		Measure.ELCLASS, Measure.getNoValue(), ...
		Measure.NAME, Measure.getNoValue(), ...
		Measure.DESCRIPTION, Measure.getNoValue(), ...
		Measure.TEMPLATE, Measure.getPropDefault(Measure.TEMPLATE), ...
		Measure.ID, Measure.getPropDefault(Measure.ID), ...
		Measure.LABEL, Measure.getPropDefault(Measure.LABEL), ...
		Measure.NOTES, Measure.getPropDefault(Measure.NOTES), ...
		Measure.TOSTRING, Measure.getNoValue(), ...
		Measure.SHAPE, Measure.getNoValue(), ...
		Measure.SCOPE, Measure.getNoValue(), ...
		Measure.PARAMETRICITY, Measure.getNoValue(), ...
		Measure.COMPATIBLE_GRAPHS, Measure.getNoValue(), ...
		Measure.G, Measure.getPropDefault(Measure.G), ...
		Measure.M, Measure.getNoValue(), ...
		Measure.PFM, Measure.getPropDefault(Measure.PFM) ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'measure_to_be_erased.b2'];
	 
	Element.save(m, filename)
	 
	m_loaded = Element.load(filename);
	 
	assert( ...
		isequal(m.copy(), m_loaded), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Measure.save(m) and/or Measure.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = Measure( ...
		Measure.ELCLASS, Measure.getNoValue(), ...
		Measure.NAME, Measure.getNoValue(), ...
		Measure.DESCRIPTION, Measure.getNoValue(), ...
		Measure.TEMPLATE, Measure.getPropDefault(Measure.TEMPLATE), ...
		Measure.ID, Measure.getPropDefault(Measure.ID), ...
		Measure.LABEL, Measure.getPropDefault(Measure.LABEL), ...
		Measure.NOTES, Measure.getPropDefault(Measure.NOTES), ...
		Measure.TOSTRING, Measure.getNoValue(), ...
		Measure.SHAPE, Measure.getNoValue(), ...
		Measure.SCOPE, Measure.getNoValue(), ...
		Measure.PARAMETRICITY, Measure.getNoValue(), ...
		Measure.COMPATIBLE_GRAPHS, Measure.getNoValue(), ...
		Measure.G, Measure.getPropDefault(Measure.G), ...
		Measure.M, Measure.getNoValue(), ...
		Measure.PFM, Measure.getPropDefault(Measure.PFM) ...
		);
	 
	[json, struct, el_list] = encodeJSON(m);
	[m_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(m_dec ~= m, ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		'Measure.encodeJSON() or Measure.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) Measure.getPropFormat(prop), num2cell(Measure.getProps())) == Format.HANDLE) && all(cellfun(@(prop) Measure.getPropFormat(prop), num2cell(Measure.getProps())) == Format.NET)
		assert(isequal(m_dec, m), ...
			[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
			'Measure.encodeJSON() or Measure.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':Measure:' BRAPH2.FAIL_TEST], ...
		[' When testing Measure no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 13: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

