%TEST_ANALYZEGROUP_ST_MP_BUT

%% Test 1.1: Instantiation - empty

a = AnalyzeGroup_ST_MP_BUT();

prop_number = AnalyzeGroup_ST_MP_BUT.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(AnalyzeGroup_ST_MP_BUT.getPropTag(prop));
	assert( ...
		isa(a.getr(prop), 'NoValue'), ...
		[BRAPH2.STR ':AnalyzeGroup_ST_MP_BUT:' BRAPH2.BUG_FUNC], ...
		['AnalyzeGroup_ST_MP_BUT.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
		'Or there could be an error in AnalyzeGroup_ST_MP_BUT.getr(' int2str(prop) ').'] ...
		)
	assert( ...
		isa(a.getr(TAG), 'NoValue'), ...
		[BRAPH2.STR ':AnalyzeGroup_ST_MP_BUT:' BRAPH2.BUG_FUNC], ...
		['AnalyzeGroup_ST_MP_BUT.getr(''' TAG ''') must be inizialized to NoValue(). ' ...
		'Or there could be an error in AnalyzeGroup_ST_MP_BUT.getr(''' TAG ''').'] ...
		)
end

%% Test 1.2: Instantiation - defaults

warning('off', 'BRAPH2:AnalyzeGroup_ST_MP_BUT')
a = AnalyzeGroup_ST_MP_BUT( ...
	AnalyzeGroup_ST_MP_BUT.ID, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.ID), ...
	AnalyzeGroup_ST_MP_BUT.LABEL, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.LABEL), ...
	AnalyzeGroup_ST_MP_BUT.NOTES, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.NOTES), ...
	AnalyzeGroup_ST_MP_BUT.GR, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.GR), ...
	AnalyzeGroup_ST_MP_BUT.G, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.G), ...
	AnalyzeGroup_ST_MP_BUT.CORRELATION_RULE, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.CORRELATION_RULE), ...
	AnalyzeGroup_ST_MP_BUT.NEGATIVE_WEIGHT_RULE, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.NEGATIVE_WEIGHT_RULE), ...
	AnalyzeGroup_ST_MP_BUT.THRESHOLDS, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.THRESHOLDS) ...
	);
warning('on', 'BRAPH2:AnalyzeGroup_ST_MP_BUT')

for prop = 1:1:AnalyzeGroup_ST_MP_BUT.getPropNumber()
	TAG = upper(AnalyzeGroup_ST_MP_BUT.getPropTag(prop));
	switch AnalyzeGroup_ST_MP_BUT.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isequal(a.getr(prop), AnalyzeGroup_ST_MP_BUT.getPropDefaultConditioned(prop)), ...
				[BRAPH2.STR ':AnalyzeGroup_ST_MP_BUT:' BRAPH2.BUG_FUNC], ...
				['AnalyzeGroup_ST_MP_BUT.getr(' int2str(prop) ') must be inizialized to its default value ' ...
				'given by AnalyzeGroup_ST_MP_BUT.getPropDefaultConditioned(' int2str(prop) '). ' ...
				'Or there could be an error in AnalyzeGroup_ST_MP_BUT.getr(' int2str(prop) ').'] ...
				)
			assert( ...
				isequal(a.getr(TAG), AnalyzeGroup_ST_MP_BUT.getPropDefaultConditioned(prop)), ...
				[BRAPH2.STR ':AnalyzeGroup_ST_MP_BUT:' BRAPH2.BUG_FUNC], ...
				['AnalyzeGroup_ST_MP_BUT.getr(''' TAG ''') must be inizialized to its default value ' ...
				'given by AnalyzeGroup_ST_MP_BUT.getPropDefaultConditioned(' int2str(prop) '). ' ...
				'Or there could be an error in AnalyzeGroup_ST_MP_BUT.getr(''' TAG ''').'] ...
				)
		case Category.RESULT
			assert( ...
				isa(a.getr(prop), 'NoValue'), ...
				[BRAPH2.STR ':AnalyzeGroup_ST_MP_BUT:' BRAPH2.BUG_FUNC], ...
				['Being a result, AnalyzeGroup_ST_MP_BUT.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
				'Or there could be an error in AnalyzeGroup_ST_MP_BUT.getr(' int2str(prop) ').'] ...
				)
			assert( ...
				isa(a.getr(TAG), 'NoValue'), ...
				[BRAPH2.STR ':AnalyzeGroup_ST_MP_BUT:' BRAPH2.BUG_FUNC], ...
				['Being a result, AnalyzeGroup_ST_MP_BUT.getr(''' TAG ''') must be inizialized to NoValue(). ' ...
				'Or there could be an error in AnalyzeGroup_ST_MP_BUT.getr(''' TAG ''').'] ...
				)
	end
end

%% Test 2: Callbacks

warning('off', 'BRAPH2:AnalyzeGroup_ST_MP_BUT')
a_0 = AnalyzeGroup_ST_MP_BUT( ...
	AnalyzeGroup_ST_MP_BUT.ID, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.ID), ...
	AnalyzeGroup_ST_MP_BUT.LABEL, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.LABEL), ...
	AnalyzeGroup_ST_MP_BUT.NOTES, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.NOTES), ...
	AnalyzeGroup_ST_MP_BUT.GR, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.GR), ...
	AnalyzeGroup_ST_MP_BUT.G, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.G), ...
	AnalyzeGroup_ST_MP_BUT.CORRELATION_RULE, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.CORRELATION_RULE), ...
	AnalyzeGroup_ST_MP_BUT.NEGATIVE_WEIGHT_RULE, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.NEGATIVE_WEIGHT_RULE), ...
	AnalyzeGroup_ST_MP_BUT.THRESHOLDS, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.THRESHOLDS) ...
	);
warning('on', 'BRAPH2:AnalyzeGroup_ST_MP_BUT')

a_1 = AnalyzeGroup_ST_MP_BUT( ...
	AnalyzeGroup_ST_MP_BUT.ID, Callback('EL', a_0, 'PROP', 1), ...
	AnalyzeGroup_ST_MP_BUT.LABEL, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.LABEL), ...
	AnalyzeGroup_ST_MP_BUT.NOTES, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.NOTES), ...
	AnalyzeGroup_ST_MP_BUT.GR, Callback('EL', a_0, 'PROP', 4), ...
	AnalyzeGroup_ST_MP_BUT.G, NoValue(), ...
	AnalyzeGroup_ST_MP_BUT.CORRELATION_RULE, Callback('EL', a_0, 'PROP', 6), ...
	AnalyzeGroup_ST_MP_BUT.NEGATIVE_WEIGHT_RULE, Callback('EL', a_0, 'PROP', 7), ...
	AnalyzeGroup_ST_MP_BUT.THRESHOLDS, Callback('EL', a_0, 'PROP', 8) ...
	);
	
prop_number = AnalyzeGroup_ST_MP_BUT.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(AnalyzeGroup_ST_MP_BUT.getPropTag(prop));
	switch AnalyzeGroup_ST_MP_BUT.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(a_1.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':AnalyzeGroup_ST_MP_BUT:' BRAPH2.BUG_FUNC], ...
				['AnalyzeGroup_ST_MP_BUT.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(a_1.get(prop), a_0.get(prop)) && ~isa(a_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':AnalyzeGroup_ST_MP_BUT:' BRAPH2.BUG_FUNC], ...
				['AnalyzeGroup_ST_MP_BUT.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(a_1.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':AnalyzeGroup_ST_MP_BUT:' BRAPH2.BUG_FUNC], ...
				['AnalyzeGroup_ST_MP_BUT.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end
a_2 = AnalyzeGroup_ST_MP_BUT( ...
	AnalyzeGroup_ST_MP_BUT.ID, Callback('EL', a_1, 'PROP', 1), ...
	AnalyzeGroup_ST_MP_BUT.LABEL, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.LABEL), ...
	AnalyzeGroup_ST_MP_BUT.NOTES, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.NOTES), ...
	AnalyzeGroup_ST_MP_BUT.GR, Callback('EL', a_1, 'PROP', 4), ...
	AnalyzeGroup_ST_MP_BUT.G, NoValue(), ...
	AnalyzeGroup_ST_MP_BUT.CORRELATION_RULE, Callback('EL', a_1, 'PROP', 6), ...
	AnalyzeGroup_ST_MP_BUT.NEGATIVE_WEIGHT_RULE, Callback('EL', a_1, 'PROP', 7), ...
	AnalyzeGroup_ST_MP_BUT.THRESHOLDS, Callback('EL', a_1, 'PROP', 8) ...
	);
	
prop_number = AnalyzeGroup_ST_MP_BUT.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(AnalyzeGroup_ST_MP_BUT.getPropTag(prop));
	switch AnalyzeGroup_ST_MP_BUT.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(a_2.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':AnalyzeGroup_ST_MP_BUT:' BRAPH2.BUG_FUNC], ...
				['AnalyzeGroup_ST_MP_BUT.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(a_2.get(prop), a_0.get(prop)) && ~isa(a_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':AnalyzeGroup_ST_MP_BUT:' BRAPH2.BUG_FUNC], ...
				['AnalyzeGroup_ST_MP_BUT.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(a_2.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':AnalyzeGroup_ST_MP_BUT:' BRAPH2.BUG_FUNC], ...
				['AnalyzeGroup_ST_MP_BUT.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end
a_3 = AnalyzeGroup_ST_MP_BUT( ...
	AnalyzeGroup_ST_MP_BUT.ID, Callback('EL', a_2, 'PROP', 1), ...
	AnalyzeGroup_ST_MP_BUT.LABEL, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.LABEL), ...
	AnalyzeGroup_ST_MP_BUT.NOTES, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.NOTES), ...
	AnalyzeGroup_ST_MP_BUT.GR, Callback('EL', a_2, 'PROP', 4), ...
	AnalyzeGroup_ST_MP_BUT.G, NoValue(), ...
	AnalyzeGroup_ST_MP_BUT.CORRELATION_RULE, Callback('EL', a_2, 'PROP', 6), ...
	AnalyzeGroup_ST_MP_BUT.NEGATIVE_WEIGHT_RULE, Callback('EL', a_2, 'PROP', 7), ...
	AnalyzeGroup_ST_MP_BUT.THRESHOLDS, Callback('EL', a_2, 'PROP', 8) ...
	);
	
prop_number = AnalyzeGroup_ST_MP_BUT.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(AnalyzeGroup_ST_MP_BUT.getPropTag(prop));
	switch AnalyzeGroup_ST_MP_BUT.getPropCategory(prop)
		case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
			assert( ...
				isa(a_3.getr(prop),  'Callback'), ...
				[BRAPH2.STR ':AnalyzeGroup_ST_MP_BUT:' BRAPH2.BUG_FUNC], ...
				['AnalyzeGroup_ST_MP_BUT.getr(' int2str(prop) ') must be a callback.'] ...
				)
			assert( ...
				isequal(a_3.get(prop), a_0.get(prop)) && ~isa(a_1.get(prop), 'Callback'), ...
				[BRAPH2.STR ':AnalyzeGroup_ST_MP_BUT:' BRAPH2.BUG_FUNC], ...
				['AnalyzeGroup_ST_MP_BUT.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
				)
		case {Category.METADATA, Category.RESULT}
			assert( ...
				~isa(a_3.getr(prop), 'Callback'), ...
				[BRAPH2.STR ':AnalyzeGroup_ST_MP_BUT:' BRAPH2.BUG_FUNC], ...
				['AnalyzeGroup_ST_MP_BUT.getr(' int2str(prop) ') must NOT be a callback.'] ...
				)
	end
end

%% Test 3: Result

warning('off', 'BRAPH2:AnalyzeGroup_ST_MP_BUT')
a = AnalyzeGroup_ST_MP_BUT( ...
	AnalyzeGroup_ST_MP_BUT.ID, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.ID), ...
	AnalyzeGroup_ST_MP_BUT.LABEL, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.LABEL), ...
	AnalyzeGroup_ST_MP_BUT.NOTES, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.NOTES), ...
	AnalyzeGroup_ST_MP_BUT.GR, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.GR), ...
	AnalyzeGroup_ST_MP_BUT.G, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.G), ...
	AnalyzeGroup_ST_MP_BUT.CORRELATION_RULE, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.CORRELATION_RULE), ...
	AnalyzeGroup_ST_MP_BUT.NEGATIVE_WEIGHT_RULE, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.NEGATIVE_WEIGHT_RULE), ...
	AnalyzeGroup_ST_MP_BUT.THRESHOLDS, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.THRESHOLDS) ...
	);
warning('on', 'BRAPH2:AnalyzeGroup_ST_MP_BUT')

prop_number = AnalyzeGroup_ST_MP_BUT.getPropNumber();
for prop = 1:1:prop_number
	TAG = upper(AnalyzeGroup_ST_MP_BUT.getPropTag(prop));
	switch AnalyzeGroup_ST_MP_BUT.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
		case Category.RESULT
			assert( ...
				~isa(a.get(prop),  'NoValue'), ...
				[BRAPH2.STR ':AnalyzeGroup_ST_MP_BUT:' BRAPH2.BUG_FUNC], ...
				['AnalyzeGroup_ST_MP_BUT.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				isa(a.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':AnalyzeGroup_ST_MP_BUT:' BRAPH2.BUG_FUNC], ...
				['AnalyzeGroup_ST_MP_BUT.getr(' int2str(prop) ') must be a NoValue, because it has not been memorized.'] ...
				)
			if isempty(a.getPropSettings(prop))
				assert( ...
					a.checkFormat(a.getPropFormat(prop), a.get(prop)), ...
					[BRAPH2.STR ':AnalyzeGroup_ST_MP_BUT:' BRAPH2.BUG_FUNC], ...
					['AnalyzeGroup_ST_MP_BUT.get(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			else
				assert( ...
					a.checkFormat(a.getPropFormat(prop), a.get(prop), a.getPropSettings(prop)), ...
					[BRAPH2.STR ':AnalyzeGroup_ST_MP_BUT:' BRAPH2.BUG_FUNC], ...
					['AnalyzeGroup_ST_MP_BUT.get(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			end
	end
end

%% Test 4: Memorize

warning('off', 'BRAPH2:AnalyzeGroup_ST_MP_BUT')
a = AnalyzeGroup_ST_MP_BUT( ...
	AnalyzeGroup_ST_MP_BUT.ID, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.ID), ...
	AnalyzeGroup_ST_MP_BUT.LABEL, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.LABEL), ...
	AnalyzeGroup_ST_MP_BUT.NOTES, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.NOTES), ...
	AnalyzeGroup_ST_MP_BUT.GR, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.GR), ...
	AnalyzeGroup_ST_MP_BUT.G, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.G), ...
	AnalyzeGroup_ST_MP_BUT.CORRELATION_RULE, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.CORRELATION_RULE), ...
	AnalyzeGroup_ST_MP_BUT.NEGATIVE_WEIGHT_RULE, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.NEGATIVE_WEIGHT_RULE), ...
	AnalyzeGroup_ST_MP_BUT.THRESHOLDS, AnalyzeGroup_ST_MP_BUT.getPropDefault(AnalyzeGroup_ST_MP_BUT.THRESHOLDS) ...
	);
warning('on', 'BRAPH2:AnalyzeGroup_ST_MP_BUT')

for prop = 1:1:AnalyzeGroup_ST_MP_BUT.getPropNumber()
	TAG = upper(AnalyzeGroup_ST_MP_BUT.getPropTag(prop));
	switch AnalyzeGroup_ST_MP_BUT.getPropCategory(prop)
		case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
		case Category.RESULT
			assert( ...
				~isa(a.get(prop),  'NoValue'), ...
				[BRAPH2.STR ':AnalyzeGroup_ST_MP_BUT:' BRAPH2.BUG_FUNC], ...
				['AnalyzeGroup_ST_MP_BUT.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				isa(a.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':AnalyzeGroup_ST_MP_BUT:' BRAPH2.BUG_FUNC], ...
				['AnalyzeGroup_ST_MP_BUT.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
				)
			assert( ...
				~isa(a.memorize(prop),  'NoValue'), ...
				[BRAPH2.STR ':AnalyzeGroup_ST_MP_BUT:' BRAPH2.BUG_FUNC], ...
				['AnalyzeGroup_ST_MP_BUT.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
				)
			assert( ...
				~isa(a.getr(prop),  'NoValue'), ...
				[BRAPH2.STR ':AnalyzeGroup_ST_MP_BUT:' BRAPH2.BUG_FUNC], ...
				['AnalyzeGroup_ST_MP_BUT.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
				)
			assert( ...
				a.checkFormat(a.getPropFormat(prop), a.getr(prop),a.getPropSettings(prop)), ...
				[BRAPH2.STR ':AnalyzeGroup_ST_MP_BUT:' BRAPH2.BUG_FUNC], ...
				['AnalyzeGroup_ST_MP_BUT.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
				)
	end
end

%% Test 5: Example

example_ST_MP_BUT

